### PR TITLE
fix(ZNTA-1632): Make non-essential put-project fields optional

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1632

Client put-project now requires id only, or id, name and type for
new projects.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/147)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutProjectCommand.java, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/147#-KaeUEGxraWPZn4LN8Df:-KaeUEGxraWPZn4LN8Dg:b-d47b7k) ([raw file](https://github.com/zanata/zanata-platform/blob/7d8c49027d646620162615d5ae2b3f33cc56584c/client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutProjectCommand.java#L64)):*
> ```Java
>                 getOpts().getProjectSlug());
>         client.put(project);
>         log.info("Done");
> ```

More descriptive message? project "XXX" created or updated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/147#-:-KaeWIU1ZHqZs_HTyDT3:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/147)*

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/147)*

**Comment by djansen-redhat** [comment]
Test:
[ ] A project can be made active to readonly (and back to active)
[ ] A command with all arguments changes all fields
[ ] project-slug is the only required argument for update, all other fields untouched
[ ] project-slug, project-name, default-project-type are required for create, all other fields untouched

**Comment by spathare21** [comment]
Verified we are able to create project using zanata-cli wihout project desc.

**Pull request merged**
