### PR TITLE
Update maven-javadoc-plugin, maven-source-plugin, maven-compiler-plug…

### PR DESCRIPTION
**Pull request by definite**
…in for Fedora 28

JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[build-tools/pom.xml, line 111 at r1](https://reviewable.io/reviews/zanata/zanata-platform/855#-LDt9WnH7Uw9qKK5xNhd:-LDt9WnH7Uw9qKK5xNhe:b72eckz) ([raw file](https://github.com/zanata/zanata-platform/blob/681f64dca88d1e7b01f0ecc84e94f624a51e55bf/build-tools/pom.xml#L111)):*
> ```XML
>             <version>3.0.0</version>
>             <configuration>
>               <additionalparam>-Xdoclint:none</additionalparam>
> ```

    

---

*[build-tools/pom.xml, line 112 at r1](https://reviewable.io/reviews/zanata/zanata-platform/855#-LDt9c6s6EjIrbCBHl7C:-LDt9c6s6EjIrbCBHl7D:blqsmt0) ([raw file](https://github.com/zanata/zanata-platform/blob/681f64dca88d1e7b01f0ecc84e94f624a51e55bf/build-tools/pom.xml#L112)):*
> ```XML
>             <configuration>
>               <additionalparam>-Xdoclint:none</additionalparam>
>               <doclint>none</doclint>
> ```

    

---

*[client/pom.xml, line 38 at r1](https://reviewable.io/reviews/zanata/zanata-platform/855#-LDt9u528nX8hJnvHl1x:-LDt9u528nX8hJnvHl1y:b-6x90ah) ([raw file](https://github.com/zanata/zanata-platform/blob/3fbc165258165eea88d786f589eda95444abf5a1/client/pom.xml#L38)):*
> ```XML
>   <properties>
>     <powermock.version>1.6.2</powermock.version>
>     <resteasy.version>3.0.13.Final</resteasy.version>
> ```

Is it possible to keep this here (with an upgrade) and omit it from parent?

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/855)*

**Comment by definite** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[client/pom.xml, line 38 at r1](https://reviewable.io/reviews/zanata/zanata-platform/855#-LDt9u528nX8hJnvHl1x:-LDtf-NfEQjMg2WbdP-8:b33oiet) ([raw file](https://github.com/zanata/zanata-platform/blob/3fbc165258165eea88d786f589eda95444abf5a1/client/pom.xml#L38)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Is it possible to keep this here (with an upgrade) and omit it from parent?
</blockquote></details>

zanata-common-api and services seem to need them

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/855)*

**Comment by seanf** [comment]
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[client/pom.xml, line 38 at r1](https://reviewable.io/reviews/zanata/zanata-platform/855#-LDt9u528nX8hJnvHl1x:-LDtpYax95aOmbidRJ_W:bsyyi8) ([raw file](https://github.com/zanata/zanata-platform/blob/3fbc165258165eea88d786f589eda95444abf5a1/client/pom.xml#L38)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary><blockquote>

zanata-common-api and services seem to need them
</blockquote></details>

Yes, but is we often need different versions of dependencies in client/api versus server, because only client/api are constrained by Fedora's packages (and we prefer to use newer dependencies in the server). 

Still, we don't have a common pom for client and api yet (other than parent).

---

*[client/stub-server/pom.xml, line 98 at r2](https://reviewable.io/reviews/zanata/zanata-platform/855#-LDtqNjN9r-MjrAwhMcu:-LDtqNjN9r-MjrAwhMcv:b-rny1e9) ([raw file](https://github.com/zanata/zanata-platform/blob/86352b6603bdec99e197416faa804346f7d38e54/client/stub-server/pom.xml#L98)):*
> ```XML
>       <groupId>org.jboss.resteasy</groupId>
>       <artifactId>resteasy-jackson-provider</artifactId>
>       <version>${resteasy.version}</version>
> ```

Why aren't the resteasy versions being inherited in this file?

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/855)*

**Comment by definite** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/pom.xml, line 38 at r1](https://reviewable.io/reviews/zanata/zanata-platform/855#-LDt9u528nX8hJnvHl1x:-LDu1vCm67Zt5HAq30Xi:b-uw5ym2) ([raw file](https://github.com/zanata/zanata-platform/blob/3fbc165258165eea88d786f589eda95444abf5a1/client/pom.xml#L38)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Yes, but is we often need different versions of dependencies in client/api versus server, because only client/api are constrained by Fedora's packages (and we prefer to use newer dependencies in the server). 

Still, we don't have a common pom for client and api yet (other than parent).
</blockquote></details>

Previously the resteasy version was 3.0.13.Final for both place. Now I put 3.0.19.Final

---

*[client/stub-server/pom.xml, line 98 at r2](https://reviewable.io/reviews/zanata/zanata-platform/855#-LDtqNjN9r-MjrAwhMcu:-LDu2D0g0A7rwCAgEQn8:b-886gsx) ([raw file](https://github.com/zanata/zanata-platform/blob/86352b6603bdec99e197416faa804346f7d38e54/client/stub-server/pom.xml#L98)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Why aren't the resteasy versions being inherited in this file?
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/855)*

**Comment by seanf** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/855#-:-LDu39wq1YFxwSmzCisg:bnfp4nl)*

**Pull request merged**
