### PR TITLE
 fix(ZNTA-2522) added spacing between languages on user profile

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2522

added spacing between languages on user profile

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by efloden** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/zanata-frontend/src/app/containers/UserProfile/index.jsx, line 113 at r1](https://reviewable.io/reviews/zanata/zanata-platform/840#-LDEmFD5EJc_yctpXAgZ:-LDEmBJEDs-DOx4uKrZg:b-va6f83) ([raw file](https://github.com/zanata/zanata-platform/blob/b6f2a0db401ce5f3dbc3f9252bdd4d435f6d52d8/server/zanata-frontend/src/app/containers/UserProfile/index.jsx#L113)):*
> ```JSX
>                 <Icon name='language' className='s0' title='Spoken languages'
>                   parentClassName='iconLanguage u-pullLeft' />
>                 <li>{languageTeams}</li>
> ```

If these are meant to display as list elements then the \<li>< should wrap the languageTeams \<a> element inside the map on line 72

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/840)*

**Comment by kathryngo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/app/containers/UserProfile/index.jsx, line 113 at r1](https://reviewable.io/reviews/zanata/zanata-platform/840#-LDEmFD5EJc_yctpXAgZ:-LDF4ioW2ZYa_5u-01PR:b-jwmzu9) ([raw file](https://github.com/zanata/zanata-platform/blob/b6f2a0db401ce5f3dbc3f9252bdd4d435f6d52d8/server/zanata-frontend/src/app/containers/UserProfile/index.jsx#L113)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

If these are meant to display as list elements then the \<li>< should wrap the languageTeams \<a> element inside the map on line 72
</blockquote></details>

I tried this and the list does not appear as I wish. I want the languages to appear stacked, not inline - so the <li> needs to be outside the map on line 72

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/840)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/app/containers/UserProfile/index.jsx, line 113 at r1](https://reviewable.io/reviews/zanata/zanata-platform/840#-LDEmFD5EJc_yctpXAgZ:-LDF4tJG20hF6r9XXe8H:b-oe1fz) ([raw file](https://github.com/zanata/zanata-platform/blob/b6f2a0db401ce5f3dbc3f9252bdd4d435f6d52d8/server/zanata-frontend/src/app/containers/UserProfile/index.jsx#L113)):*
<details><summary><i>Previously, kathryngo (Kathryn Gough) wrote…</i></summary><blockquote>

I tried this and the list does not appear as I wish. I want the languages to appear stacked, not inline - so the <li> needs to be outside the map on line 72
</blockquote></details>

Lets try that again...

I tried this and the list does not appear as I wish. I want the languages to appear stacked, not inline - so the li needs to be outside the map on line 72

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/840)*

**Comment by efloden** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/840#-:-LDFEnck1Ka5QdncxtkG:bnfp4nl)*

**Pull request merged**
