### PR TITLE
fix(ZNTA-1924): compiler warning of unchecked method invocation

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1924

JIRA issue URL: *paste URL here*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/361)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 12 of 13 files at r1.
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-war/src/test/java/org/zanata/service/impl/TranslationUpdatedManagerTest.java, line 143 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/361#-Klbg8zSOu5lNOnf1Q1e:-Klbg8zSOu5lNOnf1Q1f:bis4ce8) ([raw file](https://github.com/zanata/zanata-platform/blob/99d3d5354d4bfa94a7291a2233d3c491674774d1/server/zanata-war/src/test/java/org/zanata/service/impl/TranslationUpdatedManagerTest.java#L143)):*
> ```Java
> 
>         Map<ContentState, Long> contentStates = new HashMap<>();
>         Long longWordCount = (long) wordCount;
> ```

simpler if we just changed the field to long

---

*[server/zanata-war/src/test/java/org/zanata/ui/faces/FacesMessagesTest.java, line 94 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/361#-KlbqORuiADbUPdkdojP:-KlbqORuiADbUPdkdojQ:b-u44q8l) ([raw file](https://github.com/zanata/zanata-platform/blob/99d3d5354d4bfa94a7291a2233d3c491674774d1/server/zanata-war/src/test/java/org/zanata/ui/faces/FacesMessagesTest.java#L94)):*
> ```Java
>         assertThat(message.getValue().getSummary()).isEqualTo(testMessage);
>         assertThat(message.getValue().getSeverity().equals(SEVERITY_INFO))
>                 .isTrue();
> ```

I never like to see `x == true` or the AssertJ equivalent because it's redundant, but it's quite hard to solve this one with Java's limited type system.

I tried converting this class to Kotlin with assertj-core-kotlin and mockito-kotlin. It doesn't come out much shorter in Kotlin, but there's a lot less explicit typing. I can add the change to this branch if you like.

See https://gist.github.com/seanf/a69e80c4020b73fb6ee518365a49542a

---

*[server/zanata-war/src/test/java/org/zanata/webtrans/client/service/TranslatorInteractionServiceTest.java, line 55 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/361#-KlbqzPZeW4AXiDwa6jh:-KlbqzPZeW4AXiDwa6ji:bkhlv6b) ([raw file](https://github.com/zanata/zanata-platform/blob/99d3d5354d4bfa94a7291a2233d3c491674774d1/server/zanata-war/src/test/java/org/zanata/webtrans/client/service/TranslatorInteractionServiceTest.java#L55)):*
> ```Java
> 
>     @Test
>     @SuppressWarnings("unchecked")
> ```

At least it's just a test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/361)*

**Comment by seanf** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/test/java/org/zanata/ui/faces/FacesMessagesTest.java, line 94 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/361#-KlbqORuiADbUPdkdojP:-KlcHGDn2qZh6nRmGgc_:b-ic8jlc) ([raw file](https://github.com/zanata/zanata-platform/blob/99d3d5354d4bfa94a7291a2233d3c491674774d1/server/zanata-war/src/test/java/org/zanata/ui/faces/FacesMessagesTest.java#L94)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I never like to see `x == true` or the AssertJ equivalent because it's redundant, but it's quite hard to solve this one with Java's limited type system.

I tried converting this class to Kotlin with assertj-core-kotlin and mockito-kotlin. It doesn't come out much shorter in Kotlin, but there's a lot less explicit typing. I can add the change to this branch if you like.

See https://gist.github.com/seanf/a69e80c4020b73fb6ee518365a49542a
</blockquote></details>

Otherwise, I think it would better to keep the comparison as it was before (for better failure messages from AssertJ) and suppress the type warning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/361)*

**Comment by seanf** [comment]
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/test/java/org/zanata/service/impl/TranslationUpdatedManagerTest.java, line 137 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/361#-KlpaEQNJ8j8bpXVZFGm:-KlpaEQOeX2rQFf7Ha1t:b-tykpfc) ([raw file](https://github.com/zanata/zanata-platform/blob/4079f3624b8475f6fe00081f1b8eeb8c7cb93183/server/zanata-war/src/test/java/org/zanata/service/impl/TranslationUpdatedManagerTest.java#L137)):*
> ```Java
>         WordStatistic oldStats = StatisticsUtil.copyWordStatistic(stats);
>         oldStats.decrement(newState, wordCount.intValue());
>         oldStats.increment(oldState, wordCount.intValue());
> ```

Sorry to change my mind, but I think the upcast to `long` you had further down was a lesser evil than narrowing `long` to `int` with `wordCount.intValue()`. I'll revert this commit when I add the Kotlin change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/361)*

**Comment by aeng** [comment]
Reviewed 1 of 13 files at r1, 4 of 5 files at r3.
Review status: 15 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt, line 57 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/361#-KlpfJCpodh5L2VvHxBv:-KlpfJCpodh5L2VvHxBw:b-pgdmk1) ([raw file](https://github.com/zanata/zanata-platform/blob/5e0785da40d4c10f1e6a2931984839690833776f/server/zanata-war/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt#L57)):*
> ```Kotlin
> @AdditionalClasses(WithActiveWindowInterceptor::class)
> @InRequestScope
> @WithActiveWindow("34")
> ```

Just curious, what ActiveWindow does?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/361)*

**Comment by aeng** [comment]
Reviewed 1 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/361)*

**Comment by seanf** [comment]
Reviewed 1 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt, line 57 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/361#-KlpfJCpodh5L2VvHxBv:-Klpfjs7krtL-KxvVkdw:b6nqma3) ([raw file](https://github.com/zanata/zanata-platform/blob/5e0785da40d4c10f1e6a2931984839690833776f/server/zanata-war/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt#L57)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Just curious, what ActiveWindow does?
</blockquote></details>

It's to do with DeltaSpike's idea of windows (browser tabs within an HTTP session, based on the `dswid` URL parameter). It sets up this test to have the window scope active.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/361)*

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/361)*

**Comment by seanf** [comment]
@aeng I added another commit to upgrade the Kotlin point release.

I recommend that we don't use squash merge for this one.

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/361)*

**Pull request merged**
