### PR TITLE
fix(ZNTA-2730): clear hibernate cache before and after batch

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2730

Use EntityManager:clear after processing a batch of textflowtargets in a transaction, to prevent progressively increasing memory usage.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by djansen-redhat** [comment]
Uses the batch change from ZNTA-2721 (#1004) because large documents were a pain to work with.
This change decreases the allocated entities from 3000+ to 500 and processing time from about 10s  increasing to roughly 1.5s consistent.

Fails at the indicated line for attribution, with a session error. It may be a good idea, if possible, to move attribution to immediately after the batch, as it may run into a similar problem.

**Comment by seanf** [comment]
@djansen-redhat Oh, you mean https://github.com/KengoTODA/findbugs-slf4j ? I wondered why you got rid of all the "[PERF]" prepending. SLF4J_FORMAT_SHOULD_BE_CONST was complaining, I assume.

**Comment by djansen-redhat** [comment]
@seanf that, and after I removed it there was a missing parameter/list value in one of the calls so my approach was risky anyhow.

**Comment by djansen-redhat** [comment]
@seanf #1004 was merged, and release merged into this. I noticed I added some whitespace to TranslationServiceImpl - should I remove it?

**Pull request merged**
