### PR TITLE
chore(ZNTA-1391): update references for zanata-platform

### PR DESCRIPTION
**Pull request by seanf**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1391
also: https://zanata.atlassian.net/browse/ZNTA-1457

We still had some references to source code in zanata-server and other modules, in docs and in the build metadata (pom.xml and package.json). I have updated these to point to the zanata-platform repository.

Also moved CONTRIBUTING.md and licences files from server to root.

NB: The wiki is still hosted under the zanata-server project.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/36)

### CODE REVIEW

**Comment by definite** [comment]
Do you think it will be better to use variable instead?
Like the example provided at https://issues.apache.org/jira/browse/MPIR-234

---

Review status: 0 of 31 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/36#-:-KW0ePusPlrPkEr2yBQc:bg6p7lq)*

**Comment by seanf** [comment]
That doesn't work with Maven 3.

---

Review status: 0 of 31 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/36#-:-KW0ffqaSpAzlNHZOrsp:b-cap9oz)*

**Comment by definite** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/36#-:-KW0gLoymGTUPEdYIrDQ:b49ms4)*

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
Verified

**Comment by definite** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/36)*

**Pull request merged**
