### PR TITLE
fix(ZNTA-544): include user content in emails as plain text

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-544

User messages should be plaintext, to avoid malicious links hidden in anchors

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by djansen-redhat** [comment]
Yeah that's a better title.

**Comment by seanf** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java, line 56 at r2](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCR_7B89whoX0hjY0zB:-LCR_7B97rUbX_FLijT4:b-tfoudi) ([raw file](https://github.com/zanata/zanata-platform/blob/a17f2010e6de1f28d0b5d73b2116999b013f4289/server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java#L56)):*
> ```Java
>                 super.makeContext(genericContext, toAddresses);
>         String plainText = HtmlUtil.htmlToText(
>                 HtmlUtil.SANITIZER.sanitize(htmlMessage));
> ```

If we're going to turn all user input to plain text, we should just ensure it is treated as plain text. Keeping "send email" UIs which accept rich HTML is just going to lead to confusion.

---

*[server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java, line 57 at r2](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCRZyQ-DpvUxmJJePSw:-LCRZyQ-DpvUxmJJePSx:bxxfei5) ([raw file](https://github.com/zanata/zanata-platform/blob/a17f2010e6de1f28d0b5d73b2116999b013f4289/server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java#L57)):*
> ```Java
>         String plainText = HtmlUtil.htmlToText(
>                 HtmlUtil.SANITIZER.sanitize(htmlMessage));
>         return context.put("ipAddress", ipAddress).put("htmlMessage", plainText);
> ```

If it's just plain text, calling it `htmlMessage` is misleading. And if the end result contains angle brackets or ampersands, I suspect it will produce invalid HTML messages.

I was going to suggest calling the parameter `plainText`. However, I don't think Velocity can encode text safely as HTML, so perhaps we should rename the context parameter to `safeHtml` - and then make sure we encode the text as safe HTML before putting it in the `context`.

I suggest we run the plain text through StringEscapeUtils.escapeHtml4, followed by the HTML sanitizer to be safe.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/815)*

**Comment by seanf** [comment]
Reviewed 1 of 7 files at r3.
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java, line 57 at r2](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCRZyQ-DpvUxmJJePSw:-LCWVSvl09mQwpHs3qRs:b4qt89v) ([raw file](https://github.com/zanata/zanata-platform/blob/a17f2010e6de1f28d0b5d73b2116999b013f4289/server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java#L57)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

If it's just plain text, calling it `htmlMessage` is misleading. And if the end result contains angle brackets or ampersands, I suspect it will produce invalid HTML messages.

I was going to suggest calling the parameter `plainText`. However, I don't think Velocity can encode text safely as HTML, so perhaps we should rename the context parameter to `safeHtml` - and then make sure we encode the text as safe HTML before putting it in the `context`.

I suggest we run the plain text through StringEscapeUtils.escapeHtml4, followed by the HTML sanitizer to be safe.
</blockquote></details>

I still think worth renaming htmlMessage to safeHtmlMessage (also in the .vm files) - it may help us to avoid repeating the mistake.

---

*[server/services/src/main/java/org/zanata/util/HtmlUtil.java, line 66 at r3](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCWUtzQCk6iLhFUprFc:-LCWUtzQCk6iLhFUprFd:b-b3rdhj) ([raw file](https://github.com/zanata/zanata-platform/blob/bdcbcbbb0b9928c7fe14bdd4f0b1889054ed1676/server/services/src/main/java/org/zanata/util/HtmlUtil.java#L66)):*
> ```Java
>     }
> 
>     public static String escapeAndSanitizeHtml(String html) {
> ```

The method and parameter names are misleading. I suggest:

    public static String textToSafeHtml(String text) {

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/815)*

**Comment by djansen-redhat** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java, line 57 at r2](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCRZyQ-DpvUxmJJePSw:-LCXK2VN--iKoJo-A609:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/a17f2010e6de1f28d0b5d73b2116999b013f4289/server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java#L57)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I still think worth renaming htmlMessage to safeHtmlMessage (also in the .vm files) - it may help us to avoid repeating the mistake.
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/util/HtmlUtil.java, line 66 at r3](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCWUtzQCk6iLhFUprFc:-LCXK9jS10v2gYn3Mkbf:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/bdcbcbbb0b9928c7fe14bdd4f0b1889054ed1676/server/services/src/main/java/org/zanata/util/HtmlUtil.java#L66)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

The method and parameter names are misleading. I suggest:

    public static String textToSafeHtml(String text) {
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/815)*

**Comment by seanf** [comment]
Reviewed 17 of 17 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[server/services/src/main/java/org/zanata/email/ContactAdminEmailStrategy.java, line 64 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbX3KD0opdVXG6Qb3h:-LCbX3KD0opdVXG6Qb3i:b6u1fei) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/ContactAdminEmailStrategy.java#L64)):*
> ```Java
>         return context.put("fromLoginName", fromLoginName)
>                 .put("fromName", fromName).put("replyEmail", replyEmail)
>                 .put("safeHtmlMessage", textToSafeHtml(htmlMessage));
> ```

Is htmlMessage really made of HTML? That's a problem, or else the name is.

We should probably rename htmlMessage to userMessage.

---

*[server/services/src/main/java/org/zanata/email/ContactLanguageCoordinatorEmailStrategy.java, line 70 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbXIegE5I3KOJpit6o:-LCbXIegE5I3KOJpit6p:b-82jrwy) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/ContactLanguageCoordinatorEmailStrategy.java#L70)):*
> ```Java
>                 .put("localeId", localeId)
>                 .put("localeNativeName", localeNativeName)
>                 .put("safeHtmlMessage", textToSafeHtml(htmlMessage));
> ```

We should probably rename htmlMessage to userMessage.

---

*[server/services/src/main/java/org/zanata/email/ContactLanguageTeamMembersEmailStrategy.java, line 58 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbXKdqCsuJKk6FHy1o:-LCbXKdqCsuJKk6FHy1p:b-82jrwy) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/ContactLanguageTeamMembersEmailStrategy.java#L58)):*
> ```Java
>         return context.put("contactCoordinatorLink", contactCoordinatorLink)
>                 .put("localeNativeName", localeNativeName)
>                 .put("safeHtmlMessage", SANITIZER.sanitize(htmlMessage));
> ```

We should probably rename htmlMessage to userMessage.

---

*[server/services/src/main/java/org/zanata/email/DeclineLanguageRequestEmailStrategy.java, line 38 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbXLqEAl79qwAO1eeo:-LCbXLqEAl79qwAO1eep:b-82jrwy) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/DeclineLanguageRequestEmailStrategy.java#L38)):*
> ```Java
>                 .put("localeDisplayName", localeDisplayName)
>                 .put("contactCoordinatorLink", contactCoordinatorLink)
>                 .put("safeHtmlMessage", SANITIZER.sanitize(htmlMessage));
> ```

We should probably rename htmlMessage to userMessage.

---

*[server/services/src/main/java/org/zanata/email/RequestToJoinLanguageEmailStrategy.java, line 71 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbXN492jW0BYZwjjqD:-LCbXN492jW0BYZwjjqE:b-82jrwy) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/RequestToJoinLanguageEmailStrategy.java#L71)):*
> ```Java
>                 .put("localeId", localeId)
>                 .put("localeNativeName", localeNativeName)
>                 .put("safeHtmlMessage", textToSafeHtml(htmlMessage))
> ```

We should probably rename htmlMessage to userMessage.

---

*[server/services/src/main/java/org/zanata/email/RequestToJoinVersionGroupEmailStrategy.java, line 69 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbXO8D7pY1b7xetsDx:-LCbXO8D7pY1b7xetsDy:b-82jrwy) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/RequestToJoinVersionGroupEmailStrategy.java#L69)):*
> ```Java
>                 .put("groupName", groupName).put("versionGroupSlug", groupSlug)
>                 .put("projectIterationIds", projectIterationIds)
>                 .put("safeHtmlMessage", textToSafeHtml(htmlMessage));
> ```

We should probably rename htmlMessage to userMessage.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/815)*

**Comment by djansen-redhat** [comment]
Review status: 9 of 17 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[server/services/src/main/java/org/zanata/email/ContactAdminEmailStrategy.java, line 64 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbX3KD0opdVXG6Qb3h:-LCc_HRv8QwgJKYF7nzy:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/ContactAdminEmailStrategy.java#L64)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Is htmlMessage really made of HTML? That's a problem, or else the name is.

We should probably rename htmlMessage to userMessage.
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/email/ContactLanguageCoordinatorEmailStrategy.java, line 70 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbXIegE5I3KOJpit6o:-LCc_LWcDUesozzuIT4z:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/ContactLanguageCoordinatorEmailStrategy.java#L70)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should probably rename htmlMessage to userMessage.
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/email/ContactLanguageTeamMembersEmailStrategy.java, line 58 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbXKdqCsuJKk6FHy1o:-LCc_SwB1ifR_2-5bUBM:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/ContactLanguageTeamMembersEmailStrategy.java#L58)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should probably rename htmlMessage to userMessage.
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/email/DeclineLanguageRequestEmailStrategy.java, line 38 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbXLqEAl79qwAO1eeo:-LCc_U92CVJ5UFt3rtM_:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/DeclineLanguageRequestEmailStrategy.java#L38)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should probably rename htmlMessage to userMessage.
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/email/RequestToJoinLanguageEmailStrategy.java, line 71 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbXN492jW0BYZwjjqD:-LCc_VPy54mHPsEZkeip:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/RequestToJoinLanguageEmailStrategy.java#L71)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should probably rename htmlMessage to userMessage.
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/email/RequestToJoinVersionGroupEmailStrategy.java, line 69 at r4](https://reviewable.io/reviews/zanata/zanata-platform/815#-LCbXO8D7pY1b7xetsDx:-LCc_WHkAQBz_4GJtgOE:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/ed9700e69be9943013cc42f14a3721b8bbc88369/server/services/src/main/java/org/zanata/email/RequestToJoinVersionGroupEmailStrategy.java#L69)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should probably rename htmlMessage to userMessage.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/815)*

**Comment by djansen-redhat** [comment]
**Target branch changed to release**

**Comment by seanf** [comment]
:lgtm: -(Under review) +Reviewed 

---

Review status: 14 of 119 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/815#-:-LDo8WP7CqdHGkFs30hp:bns32bj)*

**Comment by djansen-redhat** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/815)*

**Comment by seanf** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/815#-:-LDoELvp9eBqVErPk9BX:bnfp4nl)*

**Comment by djansen-redhat** [comment]
@spathare21 step 7 in the Jira indicates a piece of text that should clearly display the url in the email, rather than just the text of the anchor.

**Comment by seanf** [comment]
@djansen-redhat I've rebased the branch onto release, using: `git rebase --onto origin/release origin/master ZNTA-544-escape-html-in-messages`

I suppose this means that the QA has been _somewhat_ invalidated, but other than some merge nodes and updating the Zanata version in the pom.xml files, I think it's not too bad, because the only commits removed by the rebase were these:

- https://github.com/zanata/zanata-platform/commit/35156bd238206890f288bb4f70a89cd2a4ae9106 (front-end changes, nothing to do with email)
- https://github.com/zanata/zanata-platform/commit/6eecd8c531216584eb96100cb7e1575167a386a2 (my AssertJ changes which only affected automated tests)

You can see the complete previous list of commits here: https://github.com/zanata/zanata-platform/compare/release...escape-html-in-messages

**Comment by djansen-redhat** [comment]
Thanks for that, @seanf - I appreciate it. I'll give it a quick check and merge it.

**Pull request merged**
