### PR TITLE
ZNTA-1693 project version sidebar

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1693

Implement sidebar using bootstrap and react components as a story

sidebar

Components/Sidebar/index.js
Components/Sidebar/Sidebar.story.js

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/203)

### CODE REVIEW

**Comment by carlosmunoz** [comment]
@kathryngo looking good so far! ... :tada:

**Comment by djansen-redhat** [comment]
This is looking really good.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Root.js, line 27 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/203#-Ke60s-6vYNXunXZMdqs:-Ke60s-6vYNXunXZMdqt:bsf9o9x) ([raw file](https://github.com/zanata/zanata-platform/blob/bad38a429020a058d670fffa23df0c66adc975b5/server/zanata-frontend/src/frontend/app/containers/Root.js#L27)):*
> ```JavaScript
>             <Route path='glossary' component={Glossary} />
>             <Route path='languages' component={Languages} />
>             <Route path='projsidebar' component={ProjSidebar} />
> ```

This is alright for now. But need to decide on the path with slug + version + slug during implementation.

---

*[server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, line 74 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/203#-Ke60hbqw2SPmccVVhPV:-Ke60hbqw2SPmccVVhPW:b-vjeyo0) ([raw file](https://github.com/zanata/zanata-platform/blob/bad38a429020a058d670fffa23df0c66adc975b5/server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java#L74)):*
> ```Java
>                 .where("path").matches(anyOf(
>                         "explore",
>                         "projsidebar",
> ```

This is alright for now. But will need to decide on the url pattern and design in implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/203#-:-Ke614CvSlBEN_o3SraO:bnfp4nl)*

**Comment by seanf** [comment]
@kathryngo What's happening with this one? 

It doesn't seem right to have "No QA" and "DO NOT MERGE" on the same PR.

**Comment by kathryngo** [comment]
@seanf you're right, it does need QA. This is the sidebar component for the new project version pages so it shouldn't be merged in yet until there are some pages that use it.

**Comment by spathare21** [comment]
project version sidebar looks fine in different screen views and size. but it doesn't looks good on the left side attached to menu bar. it should have to place on another side/place.

**Comment by seanf** [comment]
@kathryngo @aeng @djansen-redhat @carlosmunoz 

Even if the new code won't be used yet, perhaps we should merge it in (after fixing conflicts and any required QA). If we just leave it lying around without integrating, the bits will rot, we could get more merge conflicts. Merge early and often!

**Comment by carlosmunoz** [comment]
@seanf  Agreed. The DONOMERGE label might be there from before, as we agreed with @kathryngo that components which were not in use could be merged if they were ready.

**Comment by aeng** [comment]
@seanf @carlosmunoz The component itself is developed but no storybook or test is attached to it. The idea was having component ready with storybook or test, then we can merge in without it being used yet.

**Comment by carlosmunoz** [comment]
Ack on the storybook, but makes me wonder why then it's reviewed if it's missing pieces (unit tests) for it to be merged. Perhaps something to bring up on the next retrospective.

**Comment by aeng** [comment]
@carlosmunoz this was reviewed on the design only and before we agreed on having jest and storybook attachted to it.

**Comment by seanf** [comment]
I've added the "work in progress" tag pending the storybook and unit tests.

**Comment by kathryngo** [comment]
@carlosmunoz @seanf @aeng 
Yep this branch was created and reviewed well before the storybook and unit test stuff was agreed upon. I also agree that we should make it mergeable so it doesn't go stale, shall work on that this upcoming sprint. 
I will also add the storybook component and see how I go writing unit tests also. Thanks for the discussion everyone.

**Comment by kathryngo** [comment]
@aeng This is ready for another review

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/containers/Root.js, line 27 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/203#-Ke60s-6vYNXunXZMdqs:-KktOLMtShmh1cDmgkIu:bqwbijx) ([raw file](https://github.com/zanata/zanata-platform/blob/bad38a429020a058d670fffa23df0c66adc975b5/server/zanata-frontend/src/frontend/app/containers/Root.js#L27)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This is alright for now. But need to decide on the path with slug + version + slug during implementation.
</blockquote></details>

Removed this also for the meantime because story exists

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/203)*

**Comment by aeng** [comment]
Reviewed 1 of 3 files at r2, 3 of 4 files at r4, 2 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/203)*

**Comment by kathryngo** [comment]
@zanata-jenkins retest this please

**Comment by kathryngo** [comment]
@zanata-jenkins retest this please

**Pull request merged**
