### PR TITLE
fix: handles special char for explore search

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-2129

JIRA issue URL: *paste URL here*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/476)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/dao/PersonDAO.java, line 126 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/476#-KrEUSH85jHk2R0-nz0v:-KrEUSH9WgD7Q0vpHsxV:b-602fc7) ([raw file](https://github.com/zanata/zanata-platform/blob/44541633797e06b0c2b1f4f61e9eabf4b8e45bb4/server/services/src/main/java/org/zanata/dao/PersonDAO.java#L126)):*
> ```Java
>                     .replace("!", "!!")
>                     .replace("%", "!%")
>                     .replace("_", "!_");
> ```

We should create a method in AbstractDAO class and let the child classes to call it. The escape character may also be a static final constant in AbstractDAO and used in query.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/476)*

**Comment by aeng** [comment]
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/dao/PersonDAO.java, line 126 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/476#-KrEUSH85jHk2R0-nz0v:-KrEan9U3oR90bZcTsn9:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/44541633797e06b0c2b1f4f61e9eabf4b8e45bb4/server/services/src/main/java/org/zanata/dao/PersonDAO.java#L126)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

We should create a method in AbstractDAO class and let the child classes to call it. The escape character may also be a static final constant in AbstractDAO and used in query.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/476)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/476#-:-KrEp85m_sgQQs4wHzFf:b49ms4)*

**Comment by spathare21** [comment]
Other special char works well if we enter n number of times. But if we enter * more than 2 times it still gives the same error. 

screenshot from 2017-08-14 09-03-51

**Pull request merged**
