### PR TITLE
feat(ZNTA-2233): add linting rules to frontend

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2233

Add stylelint rules to frontend build 
https://stylelint.io/user-guide/rules/

Have included rules which align with the Zanata frontend code for consistency. Some rules cannot be included because fixing them will break the css such as overrides, ordering and removing !important declarations
## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/615)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 11 of 14 files at r1.
Review status: 11 of 14 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.css, line 279 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-L-5DmLlkjU5mgcVz45M:-L-5DmLlkjU5mgcVz45N:bfvqluh) ([raw file](https://github.com/zanata/zanata-platform/blob/ea235429125456308747ff5445f6b437aab313d0/server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.css#L279)):*
> ```CSS
>   border-color: var(--Sidebar-panel-dark);
>   display: block;
>   font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
> ```

double quote only the first item? 

---

*[server/zanata-frontend/src/frontend/app/styles/variables.less, line 186 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-L-5DU-WFPGNH-2gvMfV:-L-5DU-WFPGNH-2gvMfW:bplnch1) ([raw file](https://github.com/zanata/zanata-platform/blob/ea235429125456308747ff5445f6b437aab313d0/server/zanata-frontend/src/frontend/app/styles/variables.less#L186)):*
> ```Less
> //== Buttons
> //
> //## For each of Bootstrap"s buttons, define text, background and border color.
> ```

typo? `Bootstrap''s`

---

*[server/zanata-frontend/src/frontend/app/styles/variables.less, line 287 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-L-5D_C2_yEkmXKGdyJP:-L-5D_C2_yEkmXKGdyJQ:b-ix3agk) ([raw file](https://github.com/zanata/zanata-platform/blob/ea235429125456308747ff5445f6b437aab313d0/server/zanata-frontend/src/frontend/app/styles/variables.less#L287)):*
> ```Less
> //-- Z-index master list
> //
> // Warning: Avoid customizing these values. They"re used for a bird"s eye view
> ```

Typo? `They''re` and `bird''s`

---

*[server/zanata-frontend/src/frontend/app/styles/variables.less, line 328 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-L-5DsW2EPsu_opB6WQu:-L-5DsW2EPsu_opB6WQv:b-trjbrh) ([raw file](https://github.com/zanata/zanata-platform/blob/ea235429125456308747ff5445f6b437aab313d0/server/zanata-frontend/src/frontend/app/styles/variables.less#L328)):*
> ```Less
> @screen-lg-desktop: @screen-lg-min;
> 
> // So media queries don"t overlap when required, provide a maximum
> ```

typo? `dont''t`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/615)*

**Comment by kathryngo** [comment]
Review status: 11 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.css, line 279 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-L-5DmLlkjU5mgcVz45M:-L-5EhuMErVCmuiqKWjc:b-rmtgg4) ([raw file](https://github.com/zanata/zanata-platform/blob/ea235429125456308747ff5445f6b437aab313d0/server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.css#L279)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

double quote only the first item? 
</blockquote></details>

Yes, only when there is a font with more than one word.

---

*[server/zanata-frontend/src/frontend/app/styles/variables.less, line 186 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-L-5DU-WFPGNH-2gvMfV:-L-5FE_TYbkGNETk-cvd:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/ea235429125456308747ff5445f6b437aab313d0/server/zanata-frontend/src/frontend/app/styles/variables.less#L186)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

typo? `Bootstrap''s`
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/frontend/app/styles/variables.less, line 287 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-L-5D_C2_yEkmXKGdyJP:-L-5FE25MQc4_OFwhBCK:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/ea235429125456308747ff5445f6b437aab313d0/server/zanata-frontend/src/frontend/app/styles/variables.less#L287)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Typo? `They''re` and `bird''s`
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/frontend/app/styles/variables.less, line 328 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-L-5DsW2EPsu_opB6WQu:-L-5FDBqBlTp7-QHBsx9:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/ea235429125456308747ff5445f6b437aab313d0/server/zanata-frontend/src/frontend/app/styles/variables.less#L328)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

typo? `dont''t`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/615)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-:-L-5Gwo43EoXlWyhdSjz:bnfp4nl)*

**Comment by aeng** [comment]
Jenkins build failed.

**Comment by kathryngo** [comment]
I am aware of this, it's to do with some of my linting rules. Shall fix.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-:-L-5HKoby98Wgaohb-48:b-pn661s)*

**Comment by kathryngo** [comment]
@aeng There's  a few rules to fix/remove here. Shall tell you when it's ready for another look.

---

Review status: 13 of 14 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-:-L-5JyZBwFQMwBWZSJTJ:bvr2fx2)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/615#-:-L-9nMbApe2Y7rpJzgEH:bnfp4nl)*

**Comment by djansen-redhat** [comment]
Looks good to me

**Pull request merged**
