### PR TITLE
Update JVM args

### PR DESCRIPTION
**Pull request by seanf**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/517)

### CODE REVIEW

**Comment by seanf** [comment]
@definite @djansen-redhat 
This view might be better for review purposes (ignores whitespace changes): https://github.com/zanata/zanata-platform/pull/517/files?w=1

**Comment by definite** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/functional-test/pom.xml, line 787 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/517#-Kty8nTaPZQvjb1kIeT_:-Kty8nTaPZQvjb1kIeTa:b-yyuza8) ([raw file](https://github.com/zanata/zanata-platform/blob/3279e5b7d2f2adfa5c0e0b470a60035b0d61bd29/server/functional-test/pom.xml#L787)):*
> ```XML
>                       <cargo.jvmargs>
>                         
>                         -server
> ```

Do you think it worth the effort to put the shared  JVM args in a variable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/517)*

**Comment by seanf** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/functional-test/pom.xml, line 787 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/517#-Kty8nTaPZQvjb1kIeT_:-KtyBjTIn9vVLVl8ndsv:br4r5zl) ([raw file](https://github.com/zanata/zanata-platform/blob/3279e5b7d2f2adfa5c0e0b470a60035b0d61bd29/server/functional-test/pom.xml#L787)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary><blockquote>

Do you think it worth the effort to put the shared  JVM args in a variable?
</blockquote></details>

Okay, you twisted my arm!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/517)*

**Comment by definite** [comment]
:lgtm: -(Awaiting review) +Reviewed +(No QA \(1st vote\)) 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/517#-:-KtzT27wdwVNd9Z5L7FG:b-91vs6r)*

**Comment by seanf** [comment]
@definite Could you please review the changes again when you're able? Note that the target is now `release`.

**Comment by definite** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/517#-:-Kuw0IzSQSBERvvprGvF:bnfp4nl)*

**Pull request merged**
