### PR TITLE
fix(ZNTA-1970): flex nav on older Android/iOS devices

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1970

The frontend css to make sure that the sidebar navigation works across a range of Apple devices alongside Safari and some Android models. Although providing support to these devices is not top priority, there is obviously a problem with flex css that should be resolved for consistent layouts.

## Cross-browser compatibility notes

Fixed nav in
- Safari 8+
- iOS 9+
- Android 4.3+

**Please note: flex issues can only be fixed in iOS 9+ and Android 4.3+. In lower screen sized Apple devices (<= v8) and Android <=4.2 the mobile menu appears stacked - a bug that can't be fixed in Safari even with -webkit prefixes.**

In the future I will test for Android 4.3+ (released 2012) and iOS 9+ (released mid 2015). Sadly there is no way to get the nav working correctly in mobile on iOS devices in v8 and below, with it looking like this (but at least it is usable):

bs_realios_mobile_iphone 6 plus-8 0

## QAs please note

Please pay specific attention to the layout of the following pages in frontend for any UI bugs during testing:

- dashboard
- glossary
- user profile
- languages 
- explore

## Screenshots of example fixes

Safari 8
bs_macyos_safari_8 0

iPhone 6S (iOS9)
bs_realios_mobile_iphone 6s-9 0

Nexus 5 (Android 4.4)
bs_realdroid_mobile_google nexus 5-4 4-1080x1920

Galaxy Note 3 (Android 4.3)
bs_realdroid_mobile_samsung galaxy note 3-4 3-1080x1920

Galaxy Note 4 10.1 (Android 4.4)
bs_realdroid_tablet_samsung galaxy tab 4-4 4-1280x800

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/332)

### CODE REVIEW

**Comment by kathryngo** [comment]
@aeng, @djansen-redhat:  should I target release instead of master?

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/332#-:-Kkhm6smQLAhfIwG96pz:bnfp4nl)*

**Comment by aeng** [comment]
@kathryngo The changes looks alright. But are there any rules of thumb or practises to use seperate CSS for browser specific css?

**Comment by kathryngo** [comment]
not for minor changes link this, since they are prefixes that apply to a range of browsers. definitely best to leave where they are

**Comment by aeng** [comment]
@kathryngo :+1:

**Comment by djansen-redhat** [comment]
✅ Tested across several device via browserstack

**Pull request merged**
