### PR TITLE
chore(ZNTA-2390): run all tests if PR description contains allFuncTests

### PR DESCRIPTION
**Pull request by seanf**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2390

Jenkins: allFuncTests

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/846#-:-LDKAa_oBRmBHTcGjAw3:bnfp4nl)*

**Comment by seanf** [comment]
Despite putting allFuncTests in the PR description (and title), all functional tests were **not** run.

Looks like we have two problems to solve before this is useful:

- some jobs don't seem to end up with the PR title info anyway - perhaps a rate limiting issue somewhere?
- job descriptions are truncated at 50 chars, and they're based on the PR title, not description - we would need to extract that from the github API (see https://github.com/zanata/zanata-pipeline-library/blob/e29afd6fceb6269de26b7aef308ca1a2ceb2263d/src/org/zanata/jenkins/PullRequests.groovy#L49 )

It looks like the method above doesn't handle rate limit exceptions well - this probably prevents any PR details from being copied to the Jenkins job at all. getSourceBranchLabel should probably catch any exception, log it, and try to continue.

**Comment by seanf** [comment]
Blocked by (testing for) https://github.com/zanata/zanata-pipeline-library/pull/8

**Comment by seanf** [comment]
Might as well treat the limitations of zanata-pipeline-library as a separate issue and merge this. Until then it may not quite work as intended.

**Pull request merged**
