### PR TITLE
Modal Notifications and Error Messages ZNTA-2136

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2136

Using the react-bootstrap Alert component for notifications in the TM Merge Modal.
Created a custom style to ensure the notification is fixed to the modal and will be visible when scrolling.

##QA:
Can trigger an error in the TM Merge Modal by attempting to run two TM Merges at the same time.
*easiest to achieve when merging into a large target file - like [moby dick](https://www.gutenberg.org/ebooks/2701)

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/465)

### CODE REVIEW

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 1834 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/465#-KqbN7IATRFuszwdjmg2:-KqbN7IB2YBCTqrPbnWg:b-qp3sy6) ([raw file](https://github.com/zanata/zanata-platform/blob/516d373e6bcca4be7f634c40c3cc260d6004ecf6/server/zanata-frontend/src/frontend/app/styles/style.less#L1834)):*
> ```Less
> 
> .alert-info {
>   background-color: @color-light !important;
> ```

Added this code temporarily to stop overrides from assets making the background of the alert white.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/465#-:-KqbMwuM6pjteKkhRQEk:bnfp4nl)*

**Comment by djansen-redhat** [comment]
I'm testing the merge branch for this and getting this error in the console:
> ReferenceError: toggleTMMergeModal is not defined

**Comment by efloden** [comment]
@djansen-redhat build passing now :+1:

**Comment by djansen-redhat** [comment]
Both @spathare21 and I have had trouble making this work. To me, it appears in an inconsistent manner when I've triggered two merges. All other times, the button has no action.

**Comment by spathare21** [comment]
@efloden or anyone is looking into it. looks like no work on it from long time.

**Pull request closed without merging**
