### PR TITLE
fix: prevent logged in user in sign_in page

### PR DESCRIPTION
**Pull request by aeng**
JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/595)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
Is there a Jira for this one?

**Comment by aeng** [comment]
Nope.

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/595#-:-KxBXmuS_L4Fz14zDdJL:b49ms4)*

**Comment by spathare21** [comment]
is there any steps to reproduce this ? also the jenkins build is failing

**Comment by spathare21** [comment]
Verified merge on successful build

**Comment by huangp** [comment]
Reviewed 1 of 2 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/595)*

**Pull request merged**
