### PR TITLE
feat(ZNTA-2380): react editor project review / translate permissions

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2380

Implement backend REST API to provide the react editor with all necessary user permission information.
Configure frontend editor to only display options to users with required permissions.

## QA
On a high level the alpha editor should have parity with how the GWT editor manages user permissions now: users should not be able to make translations if they do not have translation permissions and they should not be able to reject or approve translations if they do not have review permissions.

If a user does not have review permissions the approve/reject translation options are not available to them in the user interface (or trigger able through the keyboard shortcuts)

If a user does not have translate permissions the translation text areas should be non-editable and no options are available for changing a translation status.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/719)

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/services/src/main/java/org/zanata/rest/editor/service/UserService.java, line 151 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L4t4fq1ZjH3MWkHYmYn:-L4t4fq1ZjH3MWkHYmYo:bm4um9k) ([raw file](https://github.com/zanata/zanata-platform/blob/a0f5a14191e28d419f6427da291ebf8ec7db2f2f/server/services/src/main/java/org/zanata/rest/editor/service/UserService.java#L151)):*
> ```Java
> 
>     @Override
>     public Response getUserPermissions(HLocale locale, HProject project) {
> ```

Think this should be `String localeId, String projectSlug` looking at the interface. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/719)*

**Comment by aeng** [comment]
Reviewed 5 of 7 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/rest/editor/service/resource/UserResource.java, line 126 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L5Bg9OC37vsLrUXukJC:-L5Bg9OC37vsLrUXukJD:b-53f3b2) ([raw file](https://github.com/zanata/zanata-platform/blob/10428be7af90a55b8a9def42b0a5f5837d6f5911/server/services/src/main/java/org/zanata/rest/editor/service/resource/UserResource.java#L126)):*
> ```Java
>     @Path("/permission/roles/locale/{localeId}/project/{projectSlug}")
>     @GET
>     Response getUserPermissions(@PathParam("localeId") String localeId,
> ```

I prefer to use queryParam (?localeid=) rather than pathParam. That would merge with getLocalesPermission() method.

---

*[server/zanata-frontend/src/app/editor/api/index.js, line 39 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L5BgQ--xlnAiqclp4Qh:-L5BgQ--xlnAiqclp4Qi:b9hyfc8) ([raw file](https://github.com/zanata/zanata-platform/blob/10428be7af90a55b8a9def42b0a5f5837d6f5911/server/zanata-frontend/src/app/editor/api/index.js#L39)):*
> ```JavaScript
> export function getUserPermissions (localeId, projectSlug) {
>   const endpoint =
>   `${apiUrl}/user/permission/roles/locale/${localeId}/project/${projectSlug}`
> ```

need to update this url if we change to query-param

---

*[server/zanata-frontend/src/app/editor/reducers/header-data-reducer.js, line 45 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L5BgVoEsYgUv7cZiuxI:-L5BgVoEsYgUv7cZiuxJ:bv13wyg) ([raw file](https://github.com/zanata/zanata-platform/blob/10428be7af90a55b8a9def42b0a5f5837d6f5911/server/zanata-frontend/src/app/editor/reducers/header-data-reducer.js#L45)):*
> ```JavaScript
>     selectedLocale: '',
>     permissions: {
>       reviewer: false,
> ```

Great default!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/719)*

**Comment by efloden** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/rest/editor/service/UserService.java, line 151 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L4t4fq1ZjH3MWkHYmYn:-L5BoiiyD35q-m2BcVz7:b7xmuxg) ([raw file](https://github.com/zanata/zanata-platform/blob/a0f5a14191e28d419f6427da291ebf8ec7db2f2f/server/services/src/main/java/org/zanata/rest/editor/service/UserService.java#L151)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Think this should be `String localeId, String projectSlug` looking at the interface. 
</blockquote></details>

removed the @PathParams (I guess these were redundant?)

---

*[server/services/src/main/java/org/zanata/rest/editor/service/resource/UserResource.java, line 126 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L5Bg9OC37vsLrUXukJC:-L5BodTKcYAtizclYgqy:btxwjcy) ([raw file](https://github.com/zanata/zanata-platform/blob/10428be7af90a55b8a9def42b0a5f5837d6f5911/server/services/src/main/java/org/zanata/rest/editor/service/resource/UserResource.java#L126)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I prefer to use queryParam (?localeid=) rather than pathParam. That would merge with getLocalesPermission() method.
</blockquote></details>

refactored to use ?localeId= query param

---

*[server/zanata-frontend/src/app/editor/api/index.js, line 39 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L5BgQ--xlnAiqclp4Qh:-L5BoUwT8_amIYmB2Kaf:b-gg9ks5) ([raw file](https://github.com/zanata/zanata-platform/blob/10428be7af90a55b8a9def42b0a5f5837d6f5911/server/zanata-frontend/src/app/editor/api/index.js#L39)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

need to update this url if we change to query-param
</blockquote></details>

Updated the request endpoint to use query-param

---

*[server/zanata-frontend/src/app/editor/reducers/header-data-reducer.js, line 45 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L5BgVoEsYgUv7cZiuxI:-L5BoTmyNVCaU-mFW1Xg:bd5l6mr) ([raw file](https://github.com/zanata/zanata-platform/blob/10428be7af90a55b8a9def42b0a5f5837d6f5911/server/zanata-frontend/src/app/editor/reducers/header-data-reducer.js#L45)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Great default!
</blockquote></details>

thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/719)*

**Comment by aeng** [comment]
Reviewed 2 of 3 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/rest/editor/service/UserService.java, line 152 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L5C6p9GUIODUBMdLTEV:-L5C6p9GUIODUBMdLTEW:b-ukp59a) ([raw file](https://github.com/zanata/zanata-platform/blob/f18f7ff9fa41388285f56556cfb8b5d261f4cdc1/server/services/src/main/java/org/zanata/rest/editor/service/UserService.java#L152)):*
> ```Java
> 
>     @Override
>     public Response getUserPermissions(String projectSlug, String localeId) {
> ```

not a blocker, but nice to have the annotation here too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/719)*

**Comment by aeng** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/719)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-:-L5CPS9z8p2W5QaAs78-:bnfp4nl)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-:-L5RowmO7j6HQ1Ywt_q9:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r5.
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/rest/editor/service/UserService.java, line 155 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L5lE-Etbzv7_PKBpv6Y:-L5lE-Etbzv7_PKBpv6Z:bbey4wl) ([raw file](https://github.com/zanata/zanata-platform/blob/7043c44bd9b461af606a340aa679106948a1faaf/server/services/src/main/java/org/zanata/rest/editor/service/UserService.java#L155)):*
> ```Java
> 
>     @Override
>     public Response getUserPermissions(
> ```

Might want to rename this to `getTranslationPermission` since this is mainly for editor roles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/719)*

**Comment by efloden** [comment]
Review status: 9 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/rest/editor/service/UserService.java, line 152 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L5C6p9GUIODUBMdLTEV:-L5lMlj4PhQKzLLiR-lm:bpgvo00) ([raw file](https://github.com/zanata/zanata-platform/blob/f18f7ff9fa41388285f56556cfb8b5d261f4cdc1/server/services/src/main/java/org/zanata/rest/editor/service/UserService.java#L152)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

not a blocker, but nice to have the annotation here too.
</blockquote></details>

Added the annotations here

---

*[server/services/src/main/java/org/zanata/rest/editor/service/UserService.java, line 155 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-L5lE-Etbzv7_PKBpv6Y:-L5lMpRI0vNlfH3SGXOo:b-folgzv) ([raw file](https://github.com/zanata/zanata-platform/blob/7043c44bd9b461af606a340aa679106948a1faaf/server/services/src/main/java/org/zanata/rest/editor/service/UserService.java#L155)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Might want to rename this to `getTranslationPermission` since this is mainly for editor roles.
</blockquote></details>

refactored to getTranslationPermission

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/719)*

**Comment by spathare21** [comment]
@efloden got below error while opening editor 

"10:42:12,817 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-42) Unknown column 'this_.editable' in 'field list'
10:42:12,820 ERROR [org.zanata.webtrans.server.SeamDispatch] (default task-42) Error dispatching action: org.hibernate.exception.SQLGrammarException: could not extract ResultSet"


screenshot from 2018-02-21 16-13-25

**Comment by efloden** [comment]
@spathare21 PR #724 changes that field in the database, I've merged that PR into master now, so merging master into this branch should resolve that error

**Comment by spathare21** [comment]
@efloden 

- Approve and reject translation options are not working but still those options are available/visible to user who does not have review permission

screenshot from 2018-02-22 11-14-14



- If user did not have translation permission still able to edit translation text area and options are available for changing a translation status.


screenshot from 2018-02-22 11-16-41

**Comment by efloden** [comment]
@spathare21 should have fixed the approve and reject options now.
For that second issue, looks like review permissions include translate permissions, so the behavior for users with only the review permission enabled should match the GWT editor

**Comment by spathare21** [comment]
@efloden now 
User who don't have review permission still be able to reject/approve the translation and I didn't get your second point.

screenshot from 2018-02-23 11-37-57

Have created another user test123 and given translation Maintainer permission to only 1 language, but still be able to do translate, approve/reject translation for another language as well.


screenshot from 2018-02-23 11-36-18

**Comment by djansen-redhat** [comment]
@efloden @spathare21 @aeng 
Discussion note: Reviewer currently has translate permission by default. It was decided that this should be changed to Reviewer permissions only - if they need Translate they can be assigned the appropriate permission.
This will be changed in a following PR.

**Comment by seanf** [comment]
Removing "Ignore codecov" - I think we should be able to unit test most of the affected code.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 5 of 8 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/719#-:-L6Pdk4Dy765tMSi56lV:bnfp4nl)*

**Pull request merged**
