### PR TITLE
refactor(ZNTA-2494): replace bootstrap modals with ant.design modals

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2494

replace react-bootstrap modals with ant.design modals in the React Frontend and Editor:
https://ant.design/components/modal/

- [x] Editor RejectTranslationModal *
rejecttranslation
- [x] Editor SuggestionDetailModal
suggestiondetail
- [x] Editor GlossaryTermModal
glossaryeditor
- [x] Frontend NewLanguageModal *
newlanguage
- [x] Frontend User Profile RecentContributions Modal
profiledaterange
- [x] Frontend TMXExportModal
tmxexport
- [x] Frontend Glossary NewEntry Modal *
glossarynew
- [x] Frontend Glossary Import Modal *
glossaryimport
- [x] Frontend Glossary Export Modal *
glossaryexport

\* Also converted all contained react-bootstrap components to ant.design

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by kathryngo** [comment]
Reviewed 8 of 9 files at r2, 10 of 10 files at r3.
Review status: 18 of 19 files reviewed at latest revision, all discussions resolved.

---

*[server/zanata-frontend/src/app/components/Modal/Modal.story.js, line 8 at r3](https://reviewable.io/reviews/zanata/zanata-platform/799#-LBT7fNX6Ghh_JH9J1E0:-LBT7fNYBENWMv9XH9_N:b-cm15m1) ([raw file](https://github.com/zanata/zanata-platform/blob/b2b604568153453755a45fcbb7a62021f51935ee/server/zanata-frontend/src/app/components/Modal/Modal.story.js#L8)):*
> ```JavaScript
> // // import 'antd/lib/modal/style/index.less'
> // import Button from 'antd/lib/button'
> // // import 'antd/lib/button/style/index.less'
> ```

Do we need to reference the less files for the button? I have been using the styling without doing this.

---

*[server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.js, line 9 at r3](https://reviewable.io/reviews/zanata/zanata-platform/799#-LBTAxTJCEpOXXAiLwku:-LBTAxTJCEpOXXAiLwkv:b-a0ybhb) ([raw file](https://github.com/zanata/zanata-platform/blob/b2b604568153453755a45fcbb7a62021f51935ee/server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.js#L9)):*
> ```JavaScript
> import Select from 'antd/lib/select'
> import 'antd/lib/select/style/index.less'
> import 'antd/lib/icon/style/'
> ```

Icon style necessary?

---

*[server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.test.js, line 6 at r3](https://reviewable.io/reviews/zanata/zanata-platform/799#-LBTB1-Q1TUt_wsWp97m:-LBTB1-Q1TUt_wsWp97n:b-1gf4cr) ([raw file](https://github.com/zanata/zanata-platform/blob/b2b604568153453755a45fcbb7a62021f51935ee/server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.test.js#L6)):*
> ```JavaScript
> import { MINOR, MAJOR, CRITICAL } from '../../utils/reject-trans-util'
> import Select from 'antd/lib/select'
> import 'antd/lib/select/style/index.less'
> ```

Is this necessary also? Go through these style imports and see if they are required - pretty sure antd pulls this stuff in

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/799)*

**Comment by efloden** [comment]
Review status: 12 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/app/components/Modal/Modal.story.js, line 8 at r3](https://reviewable.io/reviews/zanata/zanata-platform/799#-LBT7fNX6Ghh_JH9J1E0:-LBUPwZ7D3vTtZXKzhB7:b-qoek3a) ([raw file](https://github.com/zanata/zanata-platform/blob/b2b604568153453755a45fcbb7a62021f51935ee/server/zanata-frontend/src/app/components/Modal/Modal.story.js#L8)):*
<details><summary><i>Previously, kathryngo (Kathryn Gough) wrote…</i></summary><blockquote>

Do we need to reference the less files for the button? I have been using the styling without doing this.
</blockquote></details>

In the Frontend to use the Antd styles and style related props (size, type etc) I had to reference with
``` import 'antd/lib/button/style/index.less' ```
In the Editor I use the css import instead as it doesn't handle less:
``` import 'antd/lib/button/style/css' ``` 

---

*[server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.js, line 9 at r3](https://reviewable.io/reviews/zanata/zanata-platform/799#-LBTAxTJCEpOXXAiLwku:-LBUQcdT1zoVCsy077gZ:b6q5pat) ([raw file](https://github.com/zanata/zanata-platform/blob/b2b604568153453755a45fcbb7a62021f51935ee/server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.js#L9)):*
<details><summary><i>Previously, kathryngo (Kathryn Gough) wrote…</i></summary><blockquote>

Icon style necessary?
</blockquote></details>

Wasn't necessary, the index.less should pull it in, changed to use the css import here for Editor as well

---

*[server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.test.js, line 6 at r3](https://reviewable.io/reviews/zanata/zanata-platform/799#-LBTB1-Q1TUt_wsWp97m:-LBUR0Cw0MHyZORD_RnT:b-6wcv09) ([raw file](https://github.com/zanata/zanata-platform/blob/b2b604568153453755a45fcbb7a62021f51935ee/server/zanata-frontend/src/app/editor/components/RejectTranslationModal/CriteriaDropdown.test.js#L6)):*
<details><summary><i>Previously, kathryngo (Kathryn Gough) wrote…</i></summary><blockquote>

Is this necessary also? Go through these style imports and see if they are required - pretty sure antd pulls this stuff in
</blockquote></details>

Without babel loader or an equivalent it looks like we will need the separate import statement for style: https://ant.design/docs/react/getting-started#Import-on-Demand

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/799)*

**Comment by kathryngo** [comment]
@efloden once the merge conflicts are resolved I shall review this for you again

**Comment by kathryngo** [comment]
also the TM Merge Modal in containers/ProjectVersion/TMMergeModal.js needs to be refactored

**Comment by kathryngo** [comment]
@efloden disregard comment above, I am nearly finished the TM Merge modal refactor

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 10 of 13 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/799#-:-LC2G1v2DpY17MarJ4sJ:bnfp4nl)*

**Comment by djansen-redhat** [comment]
New language dialog:
screenshot from 2018-05-14 12-38-26
- [ ] No border around search dropdown
- [ ] No space between name and locale code (eg. Russiaru)
- [ ] Save button can be pressed before all fields are filled in, saving each field as the searched term

**Comment by djansen-redhat** [comment]
Contributions (profile) view:
- [ ] The date buttons are oversized
screenshot from 2018-05-14 12-46-29
- [ ] The default display is one day, at the end of this week (not today). Should it have been a week view?

And there really needs to be a date 'title' mouseover or range down the side. It's difficult to click particular dates over a range of several months.

**Comment by djansen-redhat** [comment]
Version TMX export modal:
- [ ] Woah
screenshot from 2018-05-14 12-57-54

**Comment by spathare21** [comment]
@efloden  looks good to me

**Comment by kathryngo** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/799)*

**Comment by efloden** [comment]
@djansen-redhat @spathare21 Fixed a few more issues, aslo
Contributions (profile) view:
- Button sizes should be fixed in #877
- The default dateRange state should be this week, appears to be a bug in the DateHelper.ts file - might tackle this one separately
Version TMX export modal:
- Can't reproduce this, but it looks the the styles haven't loaded

**Comment by seanf** [comment]
@efloden Looks like this PR broke AddLanguageTest in master. Could you take a look please?

**Pull request merged**
