### PR TITLE
Draft frontend builds (ZNTA-1394)

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1394

zanata-frontend does a fast draft build by default. Use -Doptimise to do an optimised production build.

Opening for review since the changes so far are separate from the remaining changes.

 - [x] zanata-frontend/src/frontend
 - [x] zanata-frontend/src/editor

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/48)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/pom.xml, line 340 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/48#-KWa4Bc238iFojb40EV9:-KWa4Bc238iFojb40EVA:b8sgrlt) ([raw file](https://github.com/zanata/zanata-platform/blob/8c8e2224ba70994daa15aeb52a37af9a99536479/server/zanata-frontend/pom.xml#L340)):*
> ```XML
>     
>     <profile>
>       <id>releaseBuild</id>
> ```

So we need to update our jenkins to use this profile?

---

*[server/zanata-frontend/src/frontend/webpack.prod.config.js, line 52 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/48#-KWa2m7OzPTv7_W0e3An:-KWa2m7OzPTv7_W0e3Ao:b21vvay) ([raw file](https://github.com/zanata/zanata-platform/blob/3578cc8ee03434414923a301a17c0502031c53fb/server/zanata-frontend/src/frontend/webpack.prod.config.js#L52)):*
> ```JavaScript
>   plugins: defaultConfig.plugins.concat([
>     new ExtractTextPlugin('frontend.css'),
>     new webpack.optimize.DedupePlugin(),
> ```

Why we remove this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/48)*

**Comment by davidmason** [comment]
Review status: 6 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/pom.xml, line 340 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/48#-KWa4Bc238iFojb40EV9:-KWaF3bqUYkLQpQWJvcs:b-o71fsu) ([raw file](https://github.com/zanata/zanata-platform/blob/8c8e2224ba70994daa15aeb52a37af9a99536479/server/zanata-frontend/pom.xml#L340)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> So we need to update our jenkins to use this profile?
</details>
I think so. For production build we definitely need to add `-Drelease`, for the Jenkins jobs it will add a few minutes but it is best if we include it so that all the testing is done with the same build as production.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/48)*

**Comment by davidmason** [comment]
Review status: 6 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/webpack.prod.config.js, line 52 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/48#-KWa2m7OzPTv7_W0e3An:-KWaF_ryk0ZU33rg5eDY:b6uxm3d) ([raw file](https://github.com/zanata/zanata-platform/blob/3578cc8ee03434414923a301a17c0502031c53fb/server/zanata-frontend/src/frontend/webpack.prod.config.js#L52)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Why we remove this?
</details>
There were 2 copies, so this is just making sure it only has 1.

1 already in `defaultConfig` (i.e. `webpack.config.js`) then it was adding this one as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/48)*

**Comment by aeng** [comment]
Reviewed 1 of 8 files at r1, 4 of 6 files at r2.
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/editor/app/webpack.config.js, line 63 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/48#-KWaIHzIOsowGPv-lgOk:-KWaIHzJZ76hFOrb3ywA:b-n85g3g) ([raw file](https://github.com/zanata/zanata-platform/blob/e82fe46e2be9d554c55cd260d51f5d620ea4cacf/server/zanata-frontend/src/editor/app/webpack.config.js#L63)):*
> ```JavaScript
> 
>   eslint: {
>     failOnWarning: false,
> ```

Do we have the same config for frontend on eslint not failing?

---

*[server/zanata-frontend/src/editor/app/webpack.prod.config.js, line 22 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/48#-KWaIft985QvvrOx7nhX:-KWaIftAQA58qVwNC7mG:b-ogzwd4) ([raw file](https://github.com/zanata/zanata-platform/blob/e82fe46e2be9d554c55cd260d51f5d620ea4cacf/server/zanata-frontend/src/editor/app/webpack.prod.config.js#L22)):*
> ```JavaScript
>   eslint: {
>     failOnWarning: true,
>   }
> ```

do we need failOnError: true for prod?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/48)*

**Comment by davidmason** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/editor/app/webpack.config.js, line 63 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/48#-KWaIHzIOsowGPv-lgOk:-KWaJHzhFcTmim-ft4Xt:b190ehj) ([raw file](https://github.com/zanata/zanata-platform/blob/e82fe46e2be9d554c55cd260d51f5d620ea4cacf/server/zanata-frontend/src/editor/app/webpack.config.js#L63)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Do we have the same config for frontend on eslint not failing?
</details>
Yes, this was copied straight from `frontend/webpack.config.js`. The production config overrides it (in both frontend and editor) to have `failOnWarning: true` so there should be no errors or warnings in production build.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/48)*

**Comment by davidmason** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/editor/app/webpack.prod.config.js, line 22 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/48#-KWaIft985QvvrOx7nhX:-KWaK06j_0Wspaj9sSMJ:b-dflgp1) ([raw file](https://github.com/zanata/zanata-platform/blob/e82fe46e2be9d554c55cd260d51f5d620ea4cacf/server/zanata-frontend/src/editor/app/webpack.prod.config.js#L22)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> do we need failOnError: true for prod?
</details>
It already inherits the default `failOnError: true` from `webpack.config.js`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/48)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: 11 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/48#-:-KWaK_ldyU89UqUjK7Y-:bnfp4nl)*

**Comment by aeng** [comment]
@davidmason make sure we update the jenkins job to use the right profile.

**Comment by davidmason** [comment]
@zanata-jenkins retest this please

**Comment by davidmason** [comment]
Review status: 10 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/pom.xml, line 340 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/48#-KWa4Bc238iFojb40EV9:-KWeZyBcuwRV_ozp1GVf:bhgjs2w) ([raw file](https://github.com/zanata/zanata-platform/blob/8c8e2224ba70994daa15aeb52a37af9a99536479/server/zanata-frontend/pom.xml#L340)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> I think so. For production build we definitely need to add `-Drelease`, for the Jenkins jobs it will add a few minutes but it is best if we include it so that all the testing is done with the same build as production.
</details>
Done. Discussed with Sean and settled on running zanata-platform-master with optimised build, and leave the others with the faster draft build.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/48)*

**Comment by davidmason** [comment]
@zanata-jenkins retest this please.

**Comment by aeng** [comment]
Reviewed 2 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/48)*

**Comment by djansen-redhat** [comment]
@davidmason some questions sir
- [ ] What is '-Drelease'? I could only find reference to 'optimise'.
- [ ] I see a mixture of optimise and optimize - is there are reason we use the real spelling in the parameter?
- [ ] Any drawbacks of using draft build?

**Comment by davidmason** [comment]
@djansen-redhat 

> - What is '-Drelease'? I could only find reference to 'optimise'.

`-Drelease` has changed to `-Doptimise` and I forgot to update the description.

> - I see a mixture of optimise and optimize - is there are reason we use the real spelling in the parameter?

Just a typo in the description

> - Any drawbacks of using draft build?

There should be no difference in execution between the draft and optimised build. The optimised one is just slower and generates a smaller jar file for frontend. Just to be safe, I have optimisations turned on for the master build job.

**Comment by djansen-redhat** [comment]
:white_check_mark: verified

**Pull request merged**
