### PR TITLE
ZNTA-2201-correctSHA

### PR DESCRIPTION
**Pull request by definite**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2201

See also zanata/zanata-pipeline-library#4
*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/522)

### CODE REVIEW

**Comment by seanf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Jenkinsfile, line 14 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/522#-Kus2oux-OFiaM0rQgST:-Kus2oux-OFiaM0rQgSU:b-3hb7pt) ([raw file](https://github.com/zanata/zanata-platform/blob/1bb32cc32addeaa2f4b7e791223ad64ab9c8f92a/Jenkinsfile#L14)):*
> ```Groovy
> // GROOVY-3278:
> //   Using referenced String constant as value of Annotation causes compile error
> @Library('zanata-pipeline-library@ZNTA-2201-correctSHA')
> ```

Instead of the annotation, try doing this programmatically so that we can avoid repeating the branch name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/522)*

**Comment by definite** [comment]
*[Jenkinsfile, line 14 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/522#-Kus2oux-OFiaM0rQgST:-KuxFeW9HgBtbbpQ-MKW:b-ldxpsc) ([raw file](https://github.com/zanata/zanata-platform/blob/1bb32cc32addeaa2f4b7e791223ad64ab9c8f92a/Jenkinsfile#L14)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Instead of the annotation, try doing this programmatically so that we can avoid repeating the branch name.
</blockquote></details>

It seems like we need to accommodate something like library('zanata-pipeline-library@' + PIPELINE_LIBRARY_BRANCH).org.zanata.jenkins
Thus I revert it back to static

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/522)*

**Comment by seanf** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Jenkinsfile, line 14 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/522#-KvAPDl622M40BMXQRPL:-KvAPDl622M40BMXQRPM:b4aejmb) ([raw file](https://github.com/zanata/zanata-platform/blob/58115e9b87129a51a646555252e55a98373ece6c/Jenkinsfile#L14)):*
> ```Groovy
> // GROOVY-3278:
> //   Using referenced String constant as value of Annotation causes compile error
> @Library('zanata-pipeline-library@ZNTA-2201-correctSHA')
> ```

todo: master

---

*[build-tools/src/test/java/TestJenkinsfile.java, line 37 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/522#-KvAOoRj4RDg8gBt7rCL:-KvAOoRj4RDg8gBt7rCM:b4aejmb) ([raw file](https://github.com/zanata/zanata-platform/blob/58115e9b87129a51a646555252e55a98373ece6c/build-tools/src/test/java/TestJenkinsfile.java#L37)):*
> ```Java
> //                .retriever(localSource(LIB_PATH))
>                 .targetPath(LIB_PATH)
>                 .defaultVersion("ZNTA-2201-correctSHA")
> ```

todo: master

---

*[build-tools/src/test/java/TestJenkinsfile.java, line 116 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/522#-KvAP1FMsBy4a9v1xtLZ:-KvAP1FMsBy4a9v1xtL_:b-njwvh6) ([raw file](https://github.com/zanata/zanata-platform/blob/58115e9b87129a51a646555252e55a98373ece6c/build-tools/src/test/java/TestJenkinsfile.java#L116)):*
> ```Java
>         steps.put("emailextrecipients", Closure.IDENTITY);
>         steps.put("library", Closure.IDENTITY);
>         steps.put("sh", Closure.IDENTITY);
> ```

This line may be redundant. `sh` is handled with this above:

    getHelper().registerAllowedMethod(method("sh", Map.class),

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/522)*

**Comment by definite** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[build-tools/src/test/java/TestJenkinsfile.java, line 116 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/522#-KvAP1FMsBy4a9v1xtLZ:-KvAlpvRJxwvE20LWBe9:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/58115e9b87129a51a646555252e55a98373ece6c/build-tools/src/test/java/TestJenkinsfile.java#L116)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

This line may be redundant. `sh` is handled with this above:

    getHelper().registerAllowedMethod(method("sh", Map.class),

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/522)*

**Comment by seanf** [comment]
Looks fine apart from the pipeline branch business. The sooner we automate that the better.

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/522#-:-KvAvglnp7Zzj9Gqdrt3:b-gycqbh)*

**Comment by seanf** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/522)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/522#-:-KvVU-_qWMuAPOz5jZ68:bnfp4nl)*

**Pull request merged**
