### PR TITLE
ZNTA-1652-glossary

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1652

Removed all zanata UI components from the containers/Glossary/... in frontend:
- DeleteAllEntriesModal.jsx
- DeleteEntryModal.jsx
- Entry.js
- EntryModal.js
- ExportModal.js
- Header.jsx
- ImportModal.js
- index.jsx
- NewEntryModal.js
- ViewHeader.js
+ a heap of css tweaks 

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/171)

### CODE REVIEW

**Comment by kathryngo** [comment]
Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/Entry.js, line 5 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-KbhxMxdDN2cr3zncldY:-Kbi12s_LZVRQ2e9jpRf:b2nhswy) ([raw file](https://github.com/zanata/zanata-platform/blob/730c8bf1e0a59ce0c6ce316d19e6cb2c27f55366/server/zanata-frontend/src/frontend/app/containers/Glossary/Entry.js#L5)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This passes eslint check? on the length
</blockquote></details>

Yes

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/index.js, line 6 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-KbhxmsX11OEw-jaWJlY:-Kbi19k37S7trroMcEFB:b2nhswy) ([raw file](https://github.com/zanata/zanata-platform/blob/730c8bf1e0a59ce0c6ce316d19e6cb2c27f55366/server/zanata-frontend/src/frontend/app/containers/Glossary/index.js#L6)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

again, eslint passed?
</blockquote></details>

Yes

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 255 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-Kbhy2hg0nG0ur9mbnNC:-Kbi1Dd3GEBzlRyIrk3D:b32w1t) ([raw file](https://github.com/zanata/zanata-platform/blob/730c8bf1e0a59ce0c6ce316d19e6cb2c27f55366/server/zanata-frontend/src/frontend/app/styles/style.less#L255)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think stick with either "glossary" full word or "gloss". 
</blockquote></details>

Ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171)*

**Comment by kathryngo** [comment]
Review status: 8 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 255 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-Kbhy2hg0nG0ur9mbnNC:-KbiIWeL-Q7Kmcx1u75O:b-1ryscn) ([raw file](https://github.com/zanata/zanata-platform/blob/730c8bf1e0a59ce0c6ce316d19e6cb2c27f55366/server/zanata-frontend/src/frontend/app/styles/style.less#L255)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Ok
</blockquote></details>

Done. Ready to review again. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 12 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-:-KblLjmOzoUzG10z1nxr:bnfp4nl)*

**Comment by kathryngo** [comment]
:thumbsup: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-:-KblX7hFmv7ecK4LeOOA:b4c9lyr)*

**Comment by spathare21** [comment]
@kathryngo , search is not working on glossary page, also the delete all pop-up is quite compact. 
language selector box is too long and search field box is  short. also the ui is not aligned properly.

glossary2

glossary1


glossary3

screenshot from 2017-01-31 09-05-40

**Comment by kathryngo** [comment]
For future reference, please state which browser and version plus which operating system you are on when submitting issues like this. Will get to fixing these issues now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-:-KbmdobJjnQ50b-mpZ1F:b3mioje)*

**Comment by spathare21** [comment]
@kathryngo sorry I forgot to mention it. 

Environment : Fedora 25 X86 64  + firefox 50.1.0

**Comment by kathryngo** [comment]
Thanks :smile: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-:-KbmgFSggkbzfHrskMXn:b-awrxcq)*

**Comment by spathare21** [comment]
@kathryngo Now UI looks good and previous issue resolved but when I click on export and save for adding new glossary the buttons css/size changed. 

screenshot from 2017-01-31 11-23-18

**Comment by kathryngo** [comment]
Aha, that has something to do with the loading status on the button. I shall fix that as part of this PR.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-:-Kbn5oXoBRfCqeJCLTGS:bvgo37c)*

**Comment by kathryngo** [comment]
Fixed that issue @spathare21 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-:-KbnDI1rmrPiCuVeMFYn:b-29uzn0)*

**Comment by spathare21** [comment]
Hi @kathryngo  , the long glossary terms are not wrapped correctly .


screenshot from 2017-01-31 12-25-27

**Comment by kathryngo** [comment]
fixing it now

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-:-KbnNPZtKcRht3vUG-YX:b-qq7ru9)*

**Comment by kathryngo** [comment]
@spathare21, ready again. To deal with the positioning of the glossary term count in the language drop down, I have hid it on less than large screens. I have also decreased the font size of the glossary list slightly. Long names will now wrap to two lines on medium - small screens - I will work out how to fix the bottom padding on these items in my next task  which is removing the last of the atomic css from frontend, if that is fine with you.

**Comment by kathryngo** [comment]
@spathare21 I am fixing one small thing! Shall not be much longer.

**Comment by kathryngo** [comment]
@spathare21, it's ready for review again. Long text fields are now handled correctly.

**Comment by spathare21** [comment]
@kathryngo , everything works fine but UI looks different, part of speech header shows in middle and its values shows at the right. can you manage those things , please cross verify above screen capture ,  if you will take language selector in middle and part of speech header text at the top of its values will look good. the above UI was good except the terms wrapping.

screenshot from 2017-01-31 15-00-14

**Comment by kathryngo** [comment]
No worries. Onto it now

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-:-Kbnsb_uGxxFCMWwPuG2:b-syhvo0)*

**Comment by kathryngo** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-:-Kbnwbte6klcHy1Gnm8n:b-896fix)*

**Comment by spathare21** [comment]
thanks @kathryngo for your quick fixes and replies. 👍   :)

**Comment by kathryngo** [comment]
All good. Thanks for noticing these issues.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/171#-:-KbqXhFuofpD_RT31zVP:b-z8jl2x)*

**Comment by kathryngo** [comment]
@spathare21, needed to fix some merge conflicts and then remove a little css. Please retest and if it is all good, tell me to go ahead and merge.

**Pull request merged**
