### PR TITLE
Activate storybook addons (ZNTA-2119)

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2119

Turns on addons:

 - Info: shows code and props data, and can add notes to display
 - Host: allows positioning the story component (put in a specific-sized box, center, etc.)
 - Knobs: adds "Knobs" tab next to activity tab, to do live changing of props values etc.
 - Storyshots: adds snapshot tests

## Testing notes

This updates some library versions used in frontend and React editor, so probably needs some general testing.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/478)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 16 of 26 files at r1.
Review status: 16 of 24 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/package.json, line 17 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEsmoC0gR6MhXmcUsg:-KrEsmoDpuJ9KCC7O8SW:b-pe01s6) ([raw file](https://github.com/zanata/zanata-platform/blob/6efa616cc1048a100bd6a09718207f6471840c43/server/zanata-frontend/src/frontend/package.json#L17)):*
> ```JSON
>     "storybook-frontend": "start-storybook -p 9001 -s ./dist --config-dir .storybook-frontend",
>     "storybook-build": "build-storybook -s ./dist",
>     "test": "jest --coverage",
> ```

How we trigger the jest.config.js file?

---

*[server/zanata-frontend/src/frontend/.storybook-editor/storyshots-editor.test.js, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEsuQiJjPOgRDHo2e0:-KrEsuQiJjPOgRDHo2e1:b-mchmwo) ([raw file](https://github.com/zanata/zanata-platform/blob/6efa616cc1048a100bd6a09718207f6471840c43/server/zanata-frontend/src/frontend/.storybook-editor/storyshots-editor.test.js#L1)):*
> ```JavaScript
> import initStoryshots from '@storybook/addon-storyshots'
> ```

Is this a test file? What is it used for.

---

*[server/zanata-frontend/src/frontend/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEtGkOL5eQRVZMlfFD:-KrEtGkOL5eQRVZMlfFE:b-c0lmj0) ([raw file](https://github.com/zanata/zanata-platform/blob/6efa616cc1048a100bd6a09718207f6471840c43/server/zanata-frontend/src/frontend/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap#L1)):*
> ```
> // Jest Snapshot v1, https://goo.gl/fbAQLP
> ```

This is a big file. Is this generated? or a copy of some library?

---

*[server/zanata-frontend/src/frontend/.storybook-frontend/storyshots-frontend.test.js, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEtSm1eGIyi6344XJX:-KrEtSm1eGIyi6344XJY:b-opjtmu) ([raw file](https://github.com/zanata/zanata-platform/blob/6efa616cc1048a100bd6a09718207f6471840c43/server/zanata-frontend/src/frontend/.storybook-frontend/storyshots-frontend.test.js#L1)):*
> ```JavaScript
> import initStoryshots from '@storybook/addon-storyshots'
> ```

Is this a test file? some comments would be nice.

---

*[server/zanata-frontend/src/frontend/__mocks__/cssMock.js, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrErwHirblxnbDqos5n:-KrErwHirblxnbDqos5o:bnezcny) ([raw file](https://github.com/zanata/zanata-platform/blob/fed25e3002f41b890fef36d9dc483ca88e0ac97b/server/zanata-frontend/src/frontend/__mocks__/cssMock.js#L7)):*
> ```JavaScript
> }
> 
> export default mockCss
> ```

Any reason to move this outside of "tests"? I think it make senses since this is used only by test 

---

*[server/zanata-frontend/src/frontend/__mocks__/mockAngularGettext.js, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEs6d0NXJAU45QpqYG:-KrEs6d0NXJAU45QpqYH:bnezcny) ([raw file](https://github.com/zanata/zanata-platform/blob/fed25e3002f41b890fef36d9dc483ca88e0ac97b/server/zanata-frontend/src/frontend/__mocks__/mockAngularGettext.js#L1)):*
> ```JavaScript
> import { reduce, isUndefined } from 'lodash'
> ```

Any reason to move this outside of "tests"? I think it make senses since this is used only by test 

---

*[server/zanata-frontend/src/frontend/app/components/Modal/Modal.story.js, line 3 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEsCDOD8C1n2mcRxsT:-KrEsCDOD8C1n2mcRxsU:b-p9oio2) ([raw file](https://github.com/zanata/zanata-platform/blob/6efa616cc1048a100bd6a09718207f6471840c43/server/zanata-frontend/src/frontend/app/components/Modal/Modal.story.js#L3)):*
> ```JavaScript
> import React from 'react'
> // import ReactDOM from 'react-dom'
> // import Draggable from 'react-draggable'
> ```

Can delete if not used anymore . Unless there's a plan to restore it, then we might need to put comment on these lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/478)*

**Comment by davidmason** [comment]
Review status: 16 of 24 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/package.json, line 17 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEsmoC0gR6MhXmcUsg:-KrEtuBebQYxhzMHyN8L:b-fp7l1j) ([raw file](https://github.com/zanata/zanata-platform/blob/6efa616cc1048a100bd6a09718207f6471840c43/server/zanata-frontend/src/frontend/package.json#L17)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

How we trigger the jest.config.js file?
</blockquote></details>

It has the default name, so it just uses it. No need to include it in the command.

---

*[server/zanata-frontend/src/frontend/.storybook-editor/storyshots-editor.test.js, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEsuQiJjPOgRDHo2e0:-KrEtz8IHvEqK167RiJW:bdpefww) ([raw file](https://github.com/zanata/zanata-platform/blob/6efa616cc1048a100bd6a09718207f6471840c43/server/zanata-frontend/src/frontend/.storybook-editor/storyshots-editor.test.js#L1)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is this a test file? What is it used for.
</blockquote></details>

This file is the storyshots test for the editor components. You see it as a test when you run `make test` and it shows the results for all the editor components under this test.

---

*[server/zanata-frontend/src/frontend/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEtGkOL5eQRVZMlfFD:-KrEuAGZocVsWttGqlqk:b-fxlliw) ([raw file](https://github.com/zanata/zanata-platform/blob/6efa616cc1048a100bd6a09718207f6471840c43/server/zanata-frontend/src/frontend/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap#L1)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This is a big file. Is this generated? or a copy of some library?
</blockquote></details>

This is the snapshots that are compared when you run the storyshots test. You have to check it in so it can compare. When you change how a component renders, the snapshot test fails - if it is changed on purpose you tell jest to update the snapshot, then check in the new one.

It is not ideal, because the snapshot for all the components are not in the component directory - harder to deal with in review because the snapshot is not next to the component and storybook code. There is a PR on storyshots that will change this to put the snapshots for each component in the component directory (so lots of small files instead) so I think it is ok to have these large files until that PR is merged and we can update.

There is a way to not use storyshots and do it all manually and get snapshots in the component directories, but I think not worth it since they are already fixing it.

---

*[server/zanata-frontend/src/frontend/.storybook-frontend/storyshots-frontend.test.js, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEtSm1eGIyi6344XJX:-KrEvECuG-W8rE6EIVV4:bvcrz8w) ([raw file](https://github.com/zanata/zanata-platform/blob/6efa616cc1048a100bd6a09718207f6471840c43/server/zanata-frontend/src/frontend/.storybook-frontend/storyshots-frontend.test.js#L1)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is this a test file? some comments would be nice.
</blockquote></details>

Same as storyshots-editor but this one is the non-editor components.

---

*[server/zanata-frontend/src/frontend/__mocks__/cssMock.js, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrErwHirblxnbDqos5n:-KrEvs_GpFQ3FJoOyIVE:bu13gyz) ([raw file](https://github.com/zanata/zanata-platform/blob/fed25e3002f41b890fef36d9dc483ca88e0ac97b/server/zanata-frontend/src/frontend/__mocks__/cssMock.js#L7)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Any reason to move this outside of "tests"? I think it make senses since this is used only by test 
</blockquote></details>

The `__mocks__` directory is the standard place for jest mocks. I think it means we don't need to manually exclude `__tests__/mock` from the test path.

---

*[server/zanata-frontend/src/frontend/__mocks__/mockAngularGettext.js, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEs6d0NXJAU45QpqYG:-KrEvtIK73kejtPLZmEC:b3qbncu) ([raw file](https://github.com/zanata/zanata-platform/blob/fed25e3002f41b890fef36d9dc483ca88e0ac97b/server/zanata-frontend/src/frontend/__mocks__/mockAngularGettext.js#L1)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Any reason to move this outside of "tests"? I think it make senses since this is used only by test 
</blockquote></details>

see above: `__mocks__` is the standard place so just making it standard

---

*[server/zanata-frontend/src/frontend/app/components/Modal/Modal.story.js, line 3 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEsCDOD8C1n2mcRxsT:-KrEvhY0tJE4y3oDjfXM:blxbil6) ([raw file](https://github.com/zanata/zanata-platform/blob/6efa616cc1048a100bd6a09718207f6471840c43/server/zanata-frontend/src/frontend/app/components/Modal/Modal.story.js#L3)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Can delete if not used anymore . Unless there's a plan to restore it, then we might need to put comment on these lines
</blockquote></details>

Will do - too much cleanup on this file so I missed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/478)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 9 of 26 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-KrEtGkOL5eQRVZMlfFD:-KrStM9FOIr4rafvVH6_:bfqb3bc) ([raw file](https://github.com/zanata/zanata-platform/blob/6efa616cc1048a100bd6a09718207f6471840c43/server/zanata-frontend/src/frontend/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap#L1)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

This is the snapshots that are compared when you run the storyshots test. You have to check it in so it can compare. When you change how a component renders, the snapshot test fails - if it is changed on purpose you tell jest to update the snapshot, then check in the new one.

It is not ideal, because the snapshot for all the components are not in the component directory - harder to deal with in review because the snapshot is not next to the component and storybook code. There is a PR on storyshots that will change this to put the snapshots for each component in the component directory (so lots of small files instead) so I think it is ok to have these large files until that PR is merged and we can update.

There is a way to not use storyshots and do it all manually and get snapshots in the component directories, but I think not worth it since they are already fixing it.
</blockquote></details>

Understood. We got to be careful when include binary/lib into the repo. Make sure there's a todo task to remove this once we can get away from it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/478#-:-KrSu-nGvPuZq1oaABhj:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/478)*

**Pull request merged**
