### PR TITLE
ZNTA-1703 - eliminate error log on ZanataIdentity.preDestroy

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1703

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/183)

### CODE REVIEW

**Comment by seanf** [comment]
@huangp are we getting concurrent requests from the browser during the logout process? Was that the trigger? We've seen that before, when we first added support for WildFly, or it might have been when we upgraded to WildFly 9.

Incidentally, is the problem is harder to reproduce, now that the `onLogout` method no longer tries to inject the account, even if you remove the synchronisation?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/zanata-war/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java, line 71 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/183#-KcLhKE5lIx39vrCC9n7:-KcLhKE5lIx39vrCC9n8:btddbmj) ([raw file](https://github.com/zanata/zanata-platform/blob/0390133a40eaf0730e71a70c504badd6ebc6bffb/server/zanata-war/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java#L71)):*
> ```Java
> @Named("identityStore")
> @ApplicationScoped
> @Synchronized(timeout = ServerConstants.DEFAULT_TIMEOUT)
> ```

We shouldn't synchronise the **entire** ApplicationScoped identityStore. We need to find a way to localise the synchronisation to a smaller scope. Perhaps we need to introduce another object which holds both the `Instance<AuthenticatedAccountHolders>`. Or could we just synchronise the methods in the identityStore which touch the `Instance<AuthenticatedAccountHolders>`?

---

*[server/zanata-war/src/main/java/org/zanata/security/oauth/SecurityTokens.java, line 98 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/183#-KcLhFxH5ji4xPU-cm81:-KcLhFxH5ji4xPU-cm82:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-platform/blob/97c79e6666d103938811822790151b7d9477b787/server/zanata-war/src/main/java/org/zanata/security/oauth/SecurityTokens.java#L98)):*
> ```Java
>      */
>     public void onLogout(@Observes LogoutEvent event,
>             @Authenticated HAccount authenticatedAccount) {
> ```

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/183#-:-KcLhQwGJCNFQk1CS5LV:b-c64rdc)*

**Comment by huangp** [comment]
The trigger is the onLogout method expecting an authenticated account being injected while the session/request is closing (during logout). Not because of concurrent requests. I can remove the synchronization (not related to this issue) but I remember you added that annoation/interceptor to simulate what Seam does (all session and application scoped bean are synchronized by default). 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-war/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java, line 71 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/183#-KcLhKE5lIx39vrCC9n7:-KcM3Gdq0GUF8TmuKmEt:b-zbxl9s) ([raw file](https://github.com/zanata/zanata-platform/blob/0390133a40eaf0730e71a70c504badd6ebc6bffb/server/zanata-war/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java#L71)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We shouldn't synchronise the **entire** ApplicationScoped identityStore. We need to find a way to localise the synchronisation to a smaller scope. Perhaps we need to introduce another object which holds both the `Instance<AuthenticatedAccountHolders>`. Or could we just synchronise the methods in the identityStore which touch the `Instance<AuthenticatedAccountHolders>`?
</blockquote></details>

I probably don't need this but I've seen other application and session scoped beans with this annotation so I thought I'd add to it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/183#-:-KcM3VXbJ-Zkeb3359OK:b-n9u1zk)*

**Comment by seanf** [comment]
> The trigger is the onLogout method expecting an authenticated account being injected while the session/request is closing (during logout). Not because of concurrent requests. 

Okay, thanks.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-war/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java, line 71 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/183#-KcLhKE5lIx39vrCC9n7:-KcMAmlLMCIO1p2LQV7v:b-rpwmwq) ([raw file](https://github.com/zanata/zanata-platform/blob/0390133a40eaf0730e71a70c504badd6ebc6bffb/server/zanata-war/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java#L71)):*
> I can remove the synchronization (not related to this issue) but I remember you added that annoation/interceptor to simulate what Seam does (all session and application scoped bean are synchronized by default).

True, but if it's not related to this issue, it's probably best to avoid introducing a possible performance issue here right now (after all, we do authenticate users a lot, especially from REST). 

The class itself looks thread-safe to me (the only state is a bunch of CDI proxies), although if any of the injected CDI beans are ApplicationScoped or SessionScoped they could probably use some attention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/183#-:-KcMAHD4kNZeo7tKha1-:bnvwmip)*

**Comment by huangp** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java, line 71 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/183#-KcLhKE5lIx39vrCC9n7:-KcQ0D41T29LPAMoYuYx:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/0390133a40eaf0730e71a70c504badd6ebc6bffb/server/zanata-war/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java#L71)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

> I can remove the synchronization (not related to this issue) but I remember you added that annoation/interceptor to simulate what Seam does (all session and application scoped bean are synchronized by default).

True, but if it's not related to this issue, it's probably best to avoid introducing a possible performance issue here right now (after all, we do authenticate users a lot, especially from REST). 

The class itself looks thread-safe to me (the only state is a bunch of CDI proxies), although if any of the injected CDI beans are ApplicationScoped or SessionScoped they could probably use some attention.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/183)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/183#-:-KcV8iSU9U_o106mEaWe:bnfp4nl)*

**Pull request merged**
