### PR TITLE
Limit npm script execution (ZNTA-1355)

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1355

Script execution on third-party modules is suppressed, but allowed for all our own scripts. User `.npmrc` settings should no longer be able to interfere with our frontend build.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/67)

### CODE REVIEW

**Comment by davidmason** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/pom.xml, line 103 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/67#-KX00PsxFPMKEszV0nQv:-KX00PsxFPMKEszV0nQw:b-5rnyvf) ([raw file](https://github.com/zanata/zanata-platform/blob/38ddc68b2af987fb7068be3afa9b5ffbdb865d6b/server/zanata-frontend/pom.xml#L103)):*
> ```XML
>           </dependency>
>         </dependencies>
>       </plugin>
> ```

This check should not be needed any more since the individual commands now include `--ignore-scripts=false`.

---

*[server/zanata-frontend/src/frontend/package.json, line 21 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/67#-KX00eWqAdyV5I_KeSM7:-KX00eWqAdyV5I_KeSM8:b-hrk3wt) ([raw file](https://github.com/zanata/zanata-platform/blob/38ddc68b2af987fb7068be3afa9b5ffbdb865d6b/server/zanata-frontend/src/frontend/package.json#L21)):*
> ```JSON
>     "styleguide-build": "styleguidist build",
>     "test": "jest",
>     "copycss": "cp ./app/styles/style.css ./dist && cp ./app/styles/bootstrap.css ./dist"
> ```

These files were being copied, but not included in the jar package, so this script is completely useless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/67)*

**Comment by seanf** [comment]
Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/editor/.npmrc, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/67#-KX3JEsmA6xzQxsbysrB:-KX3JEsmA6xzQxsbysrC:b-yo2e7h) ([raw file](https://github.com/zanata/zanata-platform/blob/0fd297390de0b6439224b4bf00ab57d7e56c2955/server/zanata-frontend/src/editor/.npmrc#L1)):*
> ```
> ignore-scripts=true
> ```

What's this file? Does it override ~/.npmrc?

Could it be used to avoid the need for repeating `--ignore-scripts=false` everywhere (except npm install)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/67)*

**Comment by davidmason** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/editor/.npmrc, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/67#-KX3JEsmA6xzQxsbysrB:-KX3L2TNIvfS79RzHmG_:bwdb92r) ([raw file](https://github.com/zanata/zanata-platform/blob/0fd297390de0b6439224b4bf00ab57d7e56c2955/server/zanata-frontend/src/editor/.npmrc#L1)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> What's this file? Does it override ~/.npmrc?
> 
> Could it be used to avoid the need for repeating `--ignore-scripts=false` everywhere (except npm install)?
</details>
It takes precedence over ~/.npmrc (see https://docs.npmjs.com/files/npmrc#per-project-config-file).

This file ensures that we do not run third-party scripts, so it is the reason that our own script executions have `--ignore-scripts=false`. This is taking a whitelist approach, so this file bans all scripts, and we whitelist our own scripts by adding the `--ignore-scripts=false` flag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/67)*

**Comment by seanf** [comment]
Reviewed 3 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/pom.xml, line 103 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/67#-KX00PsxFPMKEszV0nQv:-KX3OSPducmHgSnCFe0Z:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-platform/blob/38ddc68b2af987fb7068be3afa9b5ffbdb865d6b/server/zanata-frontend/pom.xml#L103)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> This check should not be needed any more since the individual commands now include `--ignore-scripts=false`.
</details>
:+1: 

---

*[server/zanata-frontend/src/editor/.npmrc, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/67#-KX3JEsmA6xzQxsbysrB:-KX3MYz3Dxe1HMopdnAZ:be0lt7y) ([raw file](https://github.com/zanata/zanata-platform/blob/0fd297390de0b6439224b4bf00ab57d7e56c2955/server/zanata-frontend/src/editor/.npmrc#L1)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> It takes precedence over ~/.npmrc (see https://docs.npmjs.com/files/npmrc#per-project-config-file).
> 
> This file ensures that we do not run third-party scripts, so it is the reason that our own script executions have `--ignore-scripts=false`. This is taking a whitelist approach, so this file bans all scripts, and we whitelist our own scripts by adding the `--ignore-scripts=false` flag.
</details>
But isn't `npm install` the one and *only* time we want to disable scripts? The rest of the time, aren't we invoking npm specifically because we *want* to run a script? I really wish they'd had the sense to add an option `ignore-install-scripts` (or made it the default!).

Still I suppose this is the only way to ensure we never accidentally run `npm install` without the `ignore-scripts` option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/67)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/editor/.npmrc, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/67#-KX3JEsmA6xzQxsbysrB:-KX3PpgyJhB2ToB9YWHj:beo8pb2) ([raw file](https://github.com/zanata/zanata-platform/blob/0fd297390de0b6439224b4bf00ab57d7e56c2955/server/zanata-frontend/src/editor/.npmrc#L1)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> But isn't `npm install` the one and *only* time we want to disable scripts? The rest of the time, aren't we invoking npm specifically because we *want* to run a script? I really wish they'd had the sense to add an option `ignore-install-scripts` (or made it the default!).
> 
> Still I suppose this is the only way to ensure we never accidentally run `npm install` without the `ignore-scripts` option.
</details>
Yeah, it would be nice if there were an option for just npm install. I guess it comes down to whether we want to make it hard to accidentally run them, or just make sure that our builds don't run scripts by default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/67)*

**Pull request merged**
