### PR TITLE
fix(ZNTA-2473) background colour of editor sidebar panels

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL:  https://zanata.atlassian.net/browse/ZNTA-2473

Improve spacing and layout of activity panel in react editor

### Before

activity

### After
activity2

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by efloden** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/769)*

**Comment by efloden** [comment]
@kathryngo the Activity, Glossary, and Details titles look quite close to their icons, maybe we can space them a little bit? Could be done with a JSX space: {' '} but I think we were trying to avoid these

**Comment by kathryngo** [comment]
@efloden changes you requested have been made
sidebar

**Comment by efloden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/769)*

**Comment by efloden** [comment]
@kathryngo looks good, thanks :+1:

**Comment by efloden** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/769#-:-L9NA5415rt107frW9IG:bnfp4nl)*

**Comment by spathare21** [comment]
Verified looks fine

**Comment by kathryngo** [comment]
@spathare21 thanks, will run full functional tests before merging

**Pull request merged**
