### PR TITLE
fix(redirection): update editor redirection url

### PR DESCRIPTION
**Pull request by aeng**
JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1348*

Should no longer redirect to http://localhost:8080/http://localhost:8080/webtrans/translate?project=test after login from GWT editor.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

https://zanata.atlassian.net/browse/ZNTA-1348

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/64)

### CODE REVIEW

**Comment by davidmason** [comment]
The code looks fine, so feel free to proceed to QA.

I don't understand how the change fixes it though. What was going wrong?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/64#-:-KX2ieag4gX2NnQZQ4QF:bjesozr)*

**Comment by aeng** [comment]
@davidmason the url passed through can be a valid url (http://...) or internal url (/zanata/page.xhtml). The encodeScheme method assume it is all internal url which causing the duplicate of `http:` hence the wrong url (http://localhost/http://localost)

**Comment by davidmason** [comment]
That's embarrassing - I was reading the diff backwards so I thought you removed those lines. I should have waited until after I had tea this morning.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/64#-:-KX36IFAFXLRCXnlGKdE:b6beoaa)*

**Comment by davidmason** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/64#-:-KX36_l1T4d4w9CKHVnW:bnfp4nl)*

**Comment by djansen-redhat** [comment]
:white_check_mark: tested

**Pull request merged**
