### PR TITLE
feat(ZNTA-2230) add chunkhashes to css and js files in frontend

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2230

chunkhashes added to css and js files in frontend

index.xhtml files still need to reference hashes - needs engineer skills

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/556)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 9 of 11 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/gwt-editor/src/main/webapp/webtrans/Application.xhtml, line 80 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/556#-KxQFv_c3wNdrJqi3lCE:-KxQFv_c3wNdrJqi3lCF:b-6k3k1g) ([raw file](https://github.com/zanata/zanata-platform/blob/04bf0bb2500bc7089d7dd891a187ff18694e7d4b/server/gwt-editor/src/main/webapp/webtrans/Application.xhtml#L80)):*
> ```HTML
>       src="#{frontendAction.runtime}"></script>
>     <script type="text/javascript"
>       src="#{frontendAction.legacyJs}"></script>
> ```

Given that there aren't any actual "actions" in that class, I think it would be more understandable if frontendAction were renamed.

eg one of these:
* `frontendContents.runtime` `frontendContents.legacyJS`
* `frontendAssets.runtime` `frontendAssets.legacyJS`
* `frontendPaths.runtime` `frontendPaths.legacyJS`
* `frontendUrls.runtime` `frontendUrls.legacyJS`

---

*[server/services/src/test/java/org/zanata/action/FrontendActionTest.kt, line 29 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/556#-KxQHb2AwBcGFCTsUKfL:-KxQHb2AwBcGFCTsUKfM:bytyvqr) ([raw file](https://github.com/zanata/zanata-platform/blob/04bf0bb2500bc7089d7dd891a187ff18694e7d4b/server/services/src/test/java/org/zanata/action/FrontendActionTest.kt#L29)):*
> ```Kotlin
>     """
> 
>     private val manifestParent = File(Thread.currentThread().contextClassLoader.getResource(".")?.file, "META-INF/resources")
> ```

It's just a test, so it doesn't matter much, but I think this means the first arg to File() could be passed as null if getResource unexpectedly returned null. In cases like this I think it's better to use `Thread.currentThread().contextClassLoader.getResource(".")!!.file` since it will fail fast instead of trying to continue with an unexpected null.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/556)*

**Comment by huangp** [comment]
Review status: 5 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/gwt-editor/src/main/webapp/webtrans/Application.xhtml, line 80 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/556#-KxQFv_c3wNdrJqi3lCE:-KxQKJXl6oFdJ8vy5sC9:bb6un1j) ([raw file](https://github.com/zanata/zanata-platform/blob/04bf0bb2500bc7089d7dd891a187ff18694e7d4b/server/gwt-editor/src/main/webapp/webtrans/Application.xhtml#L80)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Given that there aren't any actual "actions" in that class, I think it would be more understandable if frontendAction were renamed.

eg one of these:
* `frontendContents.runtime` `frontendContents.legacyJS`
* `frontendAssets.runtime` `frontendAssets.legacyJS`
* `frontendPaths.runtime` `frontendPaths.legacyJS`
* `frontendUrls.runtime` `frontendUrls.legacyJS`
</blockquote></details>

Done

---

*[server/services/src/test/java/org/zanata/action/FrontendAssetsTest.kt, line 29 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/556#-KxQHb2AwBcGFCTsUKfL:-KxQKGz4KMK7XD6krB_o:bb6un1j) ([raw file](https://github.com/zanata/zanata-platform/blob/04bf0bb2500bc7089d7dd891a187ff18694e7d4b/server/services/src/test/java/org/zanata/action/FrontendAssetsTest.kt#L29)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

It's just a test, so it doesn't matter much, but I think this means the first arg to File() could be passed as null if getResource unexpectedly returned null. In cases like this I think it's better to use `Thread.currentThread().contextClassLoader.getResource(".")!!.file` since it will fail fast instead of trying to continue with an unexpected null.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/556)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/556#-:-KxQTdUmTgkJcq9RXcwW:bnfp4nl)*

**Comment by spathare21** [comment]
All pages looks and working fine as expected

**Pull request merged**
