### PR TITLE
chore(ZNTA-1572) use javaslang, not totallylazy

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-1572

Replace TotallyLazy with Javaslang and remove the non-Central Maven repository repo.bodar.com.

Among other things, Javaslang is better documented and doesn't require using the bodar Maven repo.

http://www.javaslang.io/

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/93)

### CODE REVIEW

**Comment by davidmason** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/main/java/org/zanata/rest/ZanataRestSecurityInterceptor.java, line 151 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/93#-KXoH1kpLMK3tWo8lcBn:-KXoH1kpLMK3tWo8lcBo:b-r6hgag) ([raw file](https://github.com/zanata/zanata-platform/blob/25ab93d76558cfa6b6be795d88b089788217f471/server/zanata-war/src/main/java/org/zanata/rest/ZanataRestSecurityInterceptor.java#L151)):*
> ```Java
>         }
>         String username = usernameOpt.get();
>         return Either.right(username);
> ```

What was the reasoning for swapping `left` and `right` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/93)*

**Comment by davidmason** [comment]
Feel free to proceed to QA with this, the question isn't a blocker.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/93#-:-KXoHiBBm15NETdf6Rbd:b-75k8nw)*

**Comment by seanf** [comment]
Thanks.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/main/java/org/zanata/rest/ZanataRestSecurityInterceptor.java, line 151 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/93#-KXoH1kpLMK3tWo8lcBn:-KXoKzBEwxmQM_AeHNVz:b-dp4h2i) ([raw file](https://github.com/zanata/zanata-platform/blob/25ab93d76558cfa6b6be795d88b089788217f471/server/zanata-war/src/main/java/org/zanata/rest/ZanataRestSecurityInterceptor.java#L151)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

What was the reasoning for swapping `left` and `right` here?
</blockquote></details>

The javaslang docs point out that Either.right is conventionally used for the success path (hence get() rather than getRight() in their api - a minor asymmetry). Eg see Haskell docs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/93#-:-KXoKu7iHC1VlhWwZ4F_:b-ucfkn4)*

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
✅ looks fine to me

**Pull request merged**
