### PR TITLE
ZNTA-2093-VersionTMMergeModal-design

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2093

Design for the new Version TM Merge Modal. Was created in storybook as it was the easiest way to generate a modal and show different elements. 

Please get me to look at the design once the backend is done to tidy up anything that may need it. I will add the styling for disabled checkboxes for each section when one is selected, and other small styling changes reliant on backend interaction in panels etc. Thanks! 

To view run
`make storybook-frontend` in frontend then go to **VersionTMMergeModal**

I have included 3 stories:
1. Has versions in the sort list
2. Has no versions in the sort list
3. From TM Source is disabled

vtm111
tm2222

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/491)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/package.json, line 138 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/491#-KsCNCvSVoOHteqJOYT6:-KsCNCvSVoOHteqJOYT7:b4kaf0s) ([raw file](https://github.com/zanata/zanata-platform/blob/2e681f70c961a56df2fef3a63f435ec8d11fe7cd/server/zanata-frontend/src/frontend/package.json#L138)):*
> ```JSON
>     "text-diff": "1.0.1",
>     "webfontloader": "1.6.24",
>     "yarn": "^0.27.5"
> ```

Use exact version, removing ^

---

*[server/zanata-frontend/src/frontend/app/components/VersionTMMergeModal/diagram.png, line 0 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/491#-KsCNloUWvP77tUFFDYF:-KsCNloUWvP77tUFFDYG:b-m7vt5p) ([raw file](https://github.com/zanata/zanata-platform/blob/2e681f70c961a56df2fef3a63f435ec8d11fe7cd/server/zanata-frontend/src/frontend/app/components/VersionTMMergeModal/diagram.png#L0)):*
Do we need this diagram? or it should be part of documentation?

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/index.css, line 32 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/491#-KsCO4P_y8R7V4r65ohJ:-KsCO4P_y8R7V4r65ohK:b-7dnfbz) ([raw file](https://github.com/zanata/zanata-platform/blob/2e681f70c961a56df2fef3a63f435ec8d11fe7cd/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/index.css#L32)):*
> ```CSS
> 
> #TM-merge-modal .label {
>   font-size: 0.975rem;
> ```

does this styling (font-size and weight) used by anywhere else? We should standardize how all label should be styled. Not keep creating a new class for each component/page.  Please make sure the other added classes too. 

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 1637 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/491#-KsCOslpGtSulLhr2xy4:-KsCOslpGtSulLhr2xy5:b-f4ipeu) ([raw file](https://github.com/zanata/zanata-platform/blob/2e681f70c961a56df2fef3a63f435ec8d11fe7cd/server/zanata-frontend/src/frontend/app/styles/style.less#L1637)):*
> ```Less
> 
> .text-new-blue {
>   color: @color-new-zanata-blue;
> ```

Good one for reusable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/491)*

**Comment by kathryngo** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/package.json, line 138 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/491#-KsCNCvSVoOHteqJOYT6:-KsCPt6ad6_EM7jB9MZB:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/2e681f70c961a56df2fef3a63f435ec8d11fe7cd/server/zanata-frontend/src/frontend/package.json#L138)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Use exact version, removing ^
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/frontend/app/components/VersionTMMergeModal/diagram.png, line  at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/491#-KsCNloUWvP77tUFFDYF:-KsCPTZoiU3MPVh7cAqR:b-r9dj1n) ([raw file](https://github.com/zanata/zanata-platform/blob/2e681f70c961a56df2fef3a63f435ec8d11fe7cd/server/zanata-frontend/src/frontend/app/components/VersionTMMergeModal/diagram.png#L)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we need this diagram? or it should be part of documentation?
</blockquote></details>

I think this diagram helps. Gives the user an idea of whats going on when they make selections without navigating away from the modal.

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/index.css, line 32 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/491#-KsCO4P_y8R7V4r65ohJ:-KsCPN7jBsvndRjrfFyk:b-2g2eey) ([raw file](https://github.com/zanata/zanata-platform/blob/2e681f70c961a56df2fef3a63f435ec8d11fe7cd/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/index.css#L32)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

does this styling (font-size and weight) used by anywhere else? We should standardize how all label should be styled. Not keep creating a new class for each component/page.  Please make sure the other added classes too. 
</blockquote></details>

No it isn't. It's specifically for the status labels - so I think it should stay here for the moment. As I find css that isn't specific to components, I am moving it to style.less. When I work on the other TM Merge components, then I will move this stuff over.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/491)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/491#-:-KsCQhOBCJym9oXXsdOj:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/491)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/491#-:-KsHhCIQRw-YODqflkb5:bnfp4nl)*

**Pull request merged**
