### PR TITLE
fix(ZNTA-2114): Broken help icons and links

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2114

Fix broken help icons and links. Also add _blank target to open in new tab/page.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/423)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@davidmason I don't know what Codecov is doing here, I only altered xhtml.

**Comment by davidmason** [comment]
@djansen-redhat I think we're good. Codecov is high or something.

codecov-what-you-smoking-screenshot from 2017-07-18 10-35-22

**Comment by spathare21** [comment]
@djansen-redhat verified this PR and following are the observations 
- for maven plugin url should be http://zanata.readthedocs.io/en/release/client/maven-plugin/installation/ 
- webhooks help still redirecting to docs.zanata.org.  
- And also can we have help icon on page while creating group, glossary, language, Admin->Create new user and anywhere we think help is required.

**Comment by djansen-redhat** [comment]
@spathare21:

- good catch
- docs.zanata.org == zanata.readthedocs.io, but I now changed them to be consistent. Searched for any instances of zanata.org/help and fixed
- definitely we should do that in master, separate change

**Comment by spathare21** [comment]
thanks @djansen-redhat verified

**Pull request merged**
