### PR TITLE
refactor(warnings): Remove/suppress some findbugs warnings

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: n/a

Handle some warnings reported by findbugs and friends.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/223)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/functional-test/src/main/java/org/zanata/util/TestEventForScreenshotListener.java, line 81 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/223#-KefI2vWNI0Qb6bHeysC:-KefI2vWNI0Qb6bHeysD:b-h5nt9f) ([raw file](https://github.com/zanata/zanata-platform/blob/2ada29c728914e4bffa367f7b272ae2d09ec62f4/server/functional-test/src/main/java/org/zanata/util/TestEventForScreenshotListener.java#L81)):*
> ```Java
>                         testIDDir.getAbsolutePath());
>                 assert testIDDir.mkdirs();
>                 assert testIDDir.isDirectory();
> ```

You shouldn't use an expression with side effects (mkdirs) with `assert`, because the directories won't be created if assertions are turned off at runtime.
Better to save the result to a boolean and then assert it:

    boolean created = testIDDir.mkdirs();
    assert created;

Although honestly, in this case the isDirectory assertion should be sufficient all by itself.

If I want to check the result of mkdirs, I use java.nio.file.Files#createDirectories instead, because it gives proper exceptions with error messages.

---

*[server/functional-test/src/main/java/org/zanata/util/TestFileGenerator.java, line 175 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/223#-KefIcgTiBWrafSixbed:-KefIcgTiBWrafSixbee:b-hbvzq8) ([raw file](https://github.com/zanata/zanata-platform/blob/2ada29c728914e4bffa367f7b272ae2d09ec62f4/server/functional-test/src/main/java/org/zanata/util/TestFileGenerator.java#L175)):*
> ```Java
>                     new File(directory).list(), new String[0]);
>             return list[0];
>         } catch (ArrayIndexOutOfBoundsException arrayException) {
> ```

Do you still need this?

---

*[server/zanata-model/src/main/java/org/zanata/model/po/HPoTargetHeader.java, line 74 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/223#-KefIrtEL8Yu6TKnQd9d:-KefIrtFAy0KC14MClFR:b-4wjgry) ([raw file](https://github.com/zanata/zanata-platform/blob/2ada29c728914e4bffa367f7b272ae2d09ec62f4/server/zanata-model/src/main/java/org/zanata/model/po/HPoTargetHeader.java#L74)):*
> ```Java
>     public boolean equals(Object obj) {
>         return super.equals(obj);
>     }
> ```

What's this about? And why not do the same for hashCode?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/223)*

**Comment by djansen-redhat** [comment]
*[server/functional-test/src/main/java/org/zanata/util/TestEventForScreenshotListener.java, line 81 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/223#-KefI2vWNI0Qb6bHeysC:-KefOxhDn-JA8mdcuudC:b-xjuyys) ([raw file](https://github.com/zanata/zanata-platform/blob/2ada29c728914e4bffa367f7b272ae2d09ec62f4/server/functional-test/src/main/java/org/zanata/util/TestEventForScreenshotListener.java#L81)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

You shouldn't use an expression with side effects (mkdirs) with `assert`, because the directories won't be created if assertions are turned off at runtime.
Better to save the result to a boolean and then assert it:

    boolean created = testIDDir.mkdirs();
    assert created;

Although honestly, in this case the isDirectory assertion should be sufficient all by itself.

If I want to check the result of mkdirs, I use java.nio.file.Files#createDirectories instead, because it gives proper exceptions with error messages.
</blockquote></details>

It complained, and didn't seem unreasonable :)
Updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/223)*

**Comment by djansen-redhat** [comment]
*[server/functional-test/src/main/java/org/zanata/util/TestFileGenerator.java, line 175 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/223#-KefIcgTiBWrafSixbed:-KefPW4jxvivJ6QQz-CE:b-z27yym) ([raw file](https://github.com/zanata/zanata-platform/blob/2ada29c728914e4bffa367f7b272ae2d09ec62f4/server/functional-test/src/main/java/org/zanata/util/TestFileGenerator.java#L175)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Do you still need this?
</blockquote></details>

As far as I can tell... yes? If the new File(directory).list() returns null, I'll end up with an empty array.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/223)*

**Comment by djansen-redhat** [comment]
*[server/zanata-model/src/main/java/org/zanata/model/po/HPoTargetHeader.java, line 74 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/223#-KefIrtEL8Yu6TKnQd9d:-KefPoc4QjZFDhYKFFUj:b-3bsb3) ([raw file](https://github.com/zanata/zanata-platform/blob/2ada29c728914e4bffa367f7b272ae2d09ec62f4/server/zanata-model/src/main/java/org/zanata/model/po/HPoTargetHeader.java#L74)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

What's this about? And why not do the same for hashCode?
</blockquote></details>

I should have commented with the reason. I wasn't really sure if it was better to ignore the warning or just explicitly state the override.

```
HPoTargetHeader.java:1, EQ_DOESNT_OVERRIDE_EQUALS, Priority: Normal
org.zanata.model.po.HPoTargetHeader doesn't override 
org.zanata.model.ModelEntityBase.equals(Object)

This class extends a class that defines an equals method and adds fields, 
but doesn't define an equals method itself. Thus, equality on instances of 
this class will ignore the identity of the subclass and the added fields. 
Be sure this is what is intended, and that you don't need to override the equals method. 
Even if you don't need to override the equals method, consider overriding it anyway to 
document the fact that the equals method for the subclass just return the result of 
invoking super.equals(o). 
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/223)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/223#-:-KegBhImewxcst9Pe-iW:bnfp4nl)*

**Pull request merged**
