### PR TITLE
fix: cleanup obsolete groups

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-2588

JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by huangp** [comment]
-(Awaiting review) +Reviewed +(On QA) 
The code also removes read only groups. So the title should change to reflect that

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/859#-:-LDnVsJPALSUpHHCXDta:b7zm4n)*

**Comment by spathare21** [comment]
didn't get actually what to test,  did you mean readonly groups ? but there is no such options on group settings . Also build looks failing on jenkins

**Comment by aeng** [comment]
@spathare21 you probably need to run zanata 4.3 to create a version group and delete it, this will mark the entry status as 'O'. Then recompile this pr and startup zanata. This PR is meant to clean up the obsolete group from the database that is marked as obsolete.

**Comment by djansen-redhat** [comment]
Or just use docker exec to change it in the db?

**Pull request merged**
