### PR TITLE
ZNTA-2216 - admin page to CRUD review criteria

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2216

* admin is able to create, retrieve, update or delete review criteria

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/530)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 22 of 24 files at r1.
Review status: 22 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/rest/review/ReviewService.java, line 55 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/530#-KurTsnw2wK_sA2ERD_Q:-KurTsnxlKnHpMTpbXSn:b-lus2jt) ([raw file](https://github.com/zanata/zanata-platform/blob/a891c8e2f57618d258aa89c3963cb6e4867add65/server/services/src/main/java/org/zanata/rest/review/ReviewService.java#L55)):*
> ```Java
> @Consumes(MediaType.APPLICATION_JSON)
> @Produces(MediaType.APPLICATION_JSON)
> public class ReviewService {
> ```

Do we need a scope for this bean?

---

*[server/services/src/main/java/org/zanata/rest/review/dto/TransReviewCriteria.java, line 51 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/530#-KurUTrXyWNFM17MQGBz:-KurUTrXyWNFM17MQGC-:b-ptqup2) ([raw file](https://github.com/zanata/zanata-platform/blob/a891c8e2f57618d258aa89c3963cb6e4867add65/server/services/src/main/java/org/zanata/rest/review/dto/TransReviewCriteria.java#L51)):*
> ```Java
> 
>     public ReviewCriteria toModel() {
>         return new ReviewCriteria(priority, editable, description);
> ```

Does DTO from API have the dependency to zanata-modal?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/530)*

**Comment by huangp** [comment]
Review status: 22 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/rest/review/ReviewService.java, line 55 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/530#-KurTsnw2wK_sA2ERD_Q:-KurnL7Yq7H4CjRwKi1Y:blbrnyc) ([raw file](https://github.com/zanata/zanata-platform/blob/a891c8e2f57618d258aa89c3963cb6e4867add65/server/services/src/main/java/org/zanata/rest/review/ReviewService.java#L55)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we need a scope for this bean?
</blockquote></details>

REST endpoint in resteasy defaults to request scope. But I will add it explicitly.

---

*[server/services/src/main/java/org/zanata/rest/review/dto/TransReviewCriteria.java, line 51 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/530#-KurUTrXyWNFM17MQGBz:-KurnS4dD5Vvg8QD9CEW:b-m1knpa) ([raw file](https://github.com/zanata/zanata-platform/blob/a891c8e2f57618d258aa89c3963cb6e4867add65/server/services/src/main/java/org/zanata/rest/review/dto/TransReviewCriteria.java#L51)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Does DTO from API have the dependency to zanata-modal?
</blockquote></details>

No. This is not in public API. But I will move the method out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/530)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/530#-:-Kv-tBv3J8B0lkKVR9Bs:bnfp4nl)*

**Comment by spathare21** [comment]
@huangp  not sure but looks like this PR causing some issue for user. after login i get below error screen and error messages in logs.

screenshot from 2017-09-28 15-12-29


[logs.txt](https://github.com/zanata/zanata-platform/files/1340333/logs.txt)

Before merging this PR everything was working fine but when i merge it got above errors and even though after reseting to master got same error.

**Comment by huangp** [comment]
@spathare21 The error came from a change in PR509. I think you need to clean up database. Or you can try to use an ephemeral database. Here is how you can do it:
```
docker rm -f zanatadb
server/docker/rundb.sh -e 
```
The -e option to rundb.sh will ask it to create a container that is ephemeral. When you stop the container nothing will be persisted on disk. It's good for testing different changes from different branches.
Once you are done with testing it and want to switch back to normal container (e.g. database changes will persist), just do 
```
docker rm -f zanatadb
server/docker/rundb.sh
```

**Comment by spathare21** [comment]
@huangp thanks will check it, but is there any other way to clean up the database and resolve this issue without creating an ephermal database.

**Comment by spathare21** [comment]
@huangp it looks like conflict here can you please check it.

**Comment by huangp** [comment]
@spathare21 fixed the conflict

**Comment by spathare21** [comment]
1. Why the priority and criteria feilds are editable in example criteria.

screenshot from 2017-10-04 12-49-37


2. placeholder (fill in criteria) in Criteria text area should be greyed out (or light text). 

3. Pencil icon button after editable is confusing (I think pencil icon is for editing and after clicking it adds one more entry)

4. Tool tip needed for pencil icon, and icon should be same as per its work.

screenshot from 2017-10-04 12-52-09

**Comment by kathryngo** [comment]
@spathare21, @huangp  

1. Because the examples should be editable, well that is my understanding.

2. Ok, shall update placeholder text

3. If it adds one more entry then is it even necessary? There is another add review criteria button underneath.

4. Do we even need the button here? See point 3.

I will have a look at the UI and make changes as necessary.

**Comment by kathryngo** [comment]
@spathare21 @huangp changes made

**Comment by spathare21** [comment]
@kathryngo conflicts

**Comment by kathryngo** [comment]
@spathare21 I know. I have left this for @huangp since I do not want to break anything.

**Comment by huangp** [comment]
@spathare21 build fixed

**Pull request merged**
