### PR TITLE
(fix) added project and version icons to TMX export modal

### PR DESCRIPTION
**Pull request by kathryngo**
See title

*note*: this design uses the new version icon (from the react components) which I am slowly implementing across Zanata as a replacement to the [v] icon that does not represent versions in other languages.

tmx

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/396)

### CODE REVIEW

**Comment by huangp** [comment]
If we want to standardize the project version display through out our app, we will need a reusable Component for it. Then everywhere can just reuse that component.   

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/396#-:-KmZNyEb_PoWjy1OgL8j:b75chv4)*

**Comment by kathryngo** [comment]
Understood, will create one when I get the chance. It's not blocking is it?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/396#-:-KmZ_OmUc4kH3MULy_BO:b980a3f)*

**Comment by huangp** [comment]
No. We can create the Component in our code.
-(Awaiting review) +(No QA \(2nd vote\)) 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/396#-:-KmZ_plqpCMOCy3B9d_D:bu1rujg)*

**Comment by huangp** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/396)*

**Pull request merged**
