### PR TITLE
ZNTA-1760 - modify constraint and fix functional test

### PR DESCRIPTION
**Pull request by huangp**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/255)

### CODE REVIEW

**Comment by seanf** [comment]
@huangp What changes did you make to FK_HProject_LocaleMember_HLocale?

**Comment by seanf** [comment]
@huangp Oh, I see you just added `onDelete="CASCADE"` - so what does that do exactly, when applied to a join table?

**Comment by huangp** [comment]
@seanf it means it someone delete a HLocale, it will delete the rows in HProject_LocaleMember. I thought we don't support language delete (see the comment in previous changelog) but I was wrong. We do support it as long as there is no translation. So I thought it's better to add the cascade rule there too. Same as HPerson.

**Comment by djansen-redhat** [comment]
✅ looks ok to me

**Pull request merged**
