### PR TITLE
Combine frontend builds ZNTA-1531

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1531

Move the editor under the frontend npm project so they both share npm/yarn config and webpack build.

## Testing notes

Major potential impacting changes are:

* css and javascript bundle names changed for react editor, frontend and legacy pages (potential to point to wrong bundle name)
* css and javascript bundle builds combined for frontend and react editor (potential for them to be bundled wrong)

so I would think a check that editor, explore and one of the 'legacy' pages look right and can do a couple of their usual behaviours would prove we didn't mess it up. I think dashboard is a legacy page, so it would do.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/224)

### CODE REVIEW

**Comment by davidmason** [comment]
@aeng @djansen-redhat please review and test this as a priority since there is very high chance of conflicts if we delay.

Please merge this for me if it passes review and testing, since I think I will be away tomorrow (technically today since I stayed up to finish this).

**Comment by kathryngo** [comment]
@davidmason could you add me as a reviewer also? That way I can be sure that the css is all correct.

**Comment by kathryngo** [comment]
@davidmason @aeng I cannot seem to run ./build command anymore on this branch.

**Comment by djansen-redhat** [comment]
-[ ] Was making the Glossary "no content" icon large intentional?
-[ ] Clicking the Try the new alpha editor button results in:
```
Need a URL in the form .../project/translate/project-slug/v/version-slug/doc-id-with-slashes?lang=locale-id
e.g. project/translate/my-project/v/my-version/document.txt?lang=fr
```

**Comment by davidmason** [comment]
@kathryngo can you give more detail about what happens when you try to run ./build?

**Comment by kathryngo** [comment]
@damason, if I run `./build -Q --server` or `./build -c --server` it returns with
`bash: ./build: No such file or directory`

**Comment by davidmason** [comment]
@djansen-redhat 

- I saw the big no-content icon in the glossary but just assumed that was how it always was. If it isn't like that in master it will need fixing.
- The "Try the new alpha editor" button should just be a link and it works for me. What URL does your button have that it is trying to open?

**Comment by kathryngo** [comment]
@davidmason @djansen-redhat, yeah the no content icon has always been large, I'd leave as is.

**Comment by davidmason** [comment]
@kathryngo sounds like you're in the wrong directory when trying to run it.

I'm PTO today, was just sending the email and had a quick look here, but someone should be able to help if this doesn't solve it for you.

**Comment by kathryngo** [comment]
@davidmason, still gives me the same error if I'm in the server folder where build.sh is located so I don't think that is the issue.

@djansen-redhat, how did you get this branch up and running? I have tried checking out to a new branch and a clean build, but even `mvn clean install` results in a complete build that fails. What command did you run and where?

**Comment by kathryngo** [comment]
@davidmason, resolved. Was on the wrong branch

**Comment by kathryngo** [comment]
LGTM

**Comment by kathryngo** [comment]
:lgtm:

---

Review status: 0 of 197 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/224#-:-KegFiqB_zy9Fpry6DRu:bnfp4nl)*

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 90 of 364 files at r1.
Review status: 60 of 197 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/224#-:-KegYw2__hxE3y4lq9Mu:b9a2vem)*

**Pull request merged**
