### PR TITLE
Update to Kotlin 1.2.0

### PR DESCRIPTION
**Pull request by seanf**
https://blog.jetbrains.com/kotlin/2017/11/kotlin-1-2-released/

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/620)

### CODE REVIEW

**Comment by seanf** [comment]
Codecov (or more likely Jacoco) is being random again. I can't see why the GWT class TransUnitNavigationView should have lower coverage. We did change the compiler version, but only for Kotlin!

**Comment by aeng** [comment]
Do we need to update our build.sh script too to include the kotlin.compiler.incremental?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/620#-:-L-GFjwIqS73Q-cROxTI:b-evm6vl)*

**Comment by seanf** [comment]
> Do we need to update our build.sh script too to include the kotlin.compiler.incremental?

Not unless we want to turn it off - it's enabled by default in `pom.xml`.

I did see some weird "class not found" errors in the second half of the `Jenkinsfile` build when `kotlin.compiler.incremental` was turned on, but I think it's related to the things we do in `Jenkinsfile` to avoid repeated compilation (eg skipping java compilation). This is one of the reasons I turned off `kotlin.compiler.incremental` for `Jenkinsfile`.

See also https://youtrack.jetbrains.com/issue/KT-21552

@aeng - any opinion on the No_QA vote?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/620#-:-L-dS2JFzDu08eAPIrC4:b-oftms0)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/620#-:-L-dVH66dKHj2XD0021L:bnfp4nl)*

**Pull request merged**
