### PR TITLE
fix(log): add build info in error log

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1376

JIRA issue URL: *[paste URL here]*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/167)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/167#-:-KbEFcbAehHgYYRib29e:b49ms4)*

**Comment by huangp** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java, line 127 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/167#-KbgcU272qg3BZmMrQbO:-KbgcU272qg3BZmMrQbP:bvb0koj) ([raw file](https://github.com/zanata/zanata-platform/blob/e8268dcbada70e07cfd99592d9b165e68b18f942/server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java#L127)):*
> ```Java
>     private String fromEmailAddr;
>     private String serverPath;
>     private String emailLogLevel;
> ```

All these fields are read in in load() method as PostConstruct. This means if user change any of those settings, they won't get picked up. It's better to produce these values and inject as Provider<> xxx. See AllowAnonymousAccess for reference.

---

*[server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java, line 142 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/167#-Kbgc3D1UAqtp5nj5C4F:-Kbgc3D1UAqtp5nj5C4G:bhqq7df) ([raw file](https://github.com/zanata/zanata-platform/blob/e8268dcbada70e07cfd99592d9b165e68b18f942/server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java#L142)):*
> ```Java
> 
>         String strVal = databaseBackedConfig.getShouldLogEvents();
>         shouldLogEvent = strVal != null && Boolean.parseBoolean(strVal);
> ```

Boolean.parseBoolean already checks null internally so no need to check strVal != null

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/167)*

**Comment by huangp** [comment]
:lgtm: -(Work in progress) 

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/167#-:-KbhutKLanHbYNe4Jhuy:bian1mi)*

**Comment by spathare21** [comment]
Verified not it shows the build info in error logs.

screenshot from 2017-01-30 11-38-46

**Pull request merged**
