### PR TITLE
Combine frontend builds (ZNTA-1529)

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1529

 - Combines the triple webpack builds to single webpack builds (for both draft and production build)
 - Uses a better merge library specifically for webpack configuration

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/111)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/webpack.prod.config.js, line 20 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/111#-KYuFiRKTKcRFg6GUdSO:-KYuFiRKTKcRFg6GUdSP:b-d0w4di) ([raw file](https://github.com/zanata/zanata-platform/blob/3f12690fcc0aefb459597e0eaf1f03ceaf3097c1/server/zanata-frontend/src/frontend/webpack.prod.config.js#L20)):*
> ```JavaScript
>   cache: false,
>   output: {
>     filename: 'frontend.[name].min.js'
> ```

So now its only 1 js file? fontend.bundle.legacy.min.js? What happen to the other `frontend.bundle.min.js`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/111)*

**Comment by davidmason** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/webpack.prod.config.js, line 20 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/111#-KYuFiRKTKcRFg6GUdSO:-KYuG0CMDjE42VZy2wUO:bgn3fnu) ([raw file](https://github.com/zanata/zanata-platform/blob/3f12690fcc0aefb459597e0eaf1f03ceaf3097c1/server/zanata-frontend/src/frontend/webpack.prod.config.js#L20)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

So now its only 1 js file? fontend.bundle.legacy.min.js? What happen to the other `frontend.bundle.min.js`
</blockquote></details>

No, still the same files with the same names. It is merging `entry` from `webpack.config.js` with this one, so it ends up as:

```
entry: {
  'bundle': './app/index'
  'bundle.legacy': './app/legacy'
}
```

and it outputs a file for each of those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/111)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/111#-:-KYuGoV8b6oyKlXw-7em:bnfp4nl)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/111#-:-KZ-euVBqXTeEFgQPRXV:bnfp4nl)*

**Comment by spathare21** [comment]
@davidmason after merging this PR with latest master branch the read editor page view is looking weird.

**Comment by spathare21** [comment]
@davidmason after merging this PR with latest master branch the read editor page view is looking weird. 

due to some issue unable to attached screen captured here hence added it to the ZNTA-1529

**Comment by spathare21** [comment]
Verified everything is working fine.

**Pull request merged**
