### PR TITLE
docs: add links explaining MDC

### PR DESCRIPTION
**Pull request by seanf**
## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.
- Code quality
  - [ ] Code passes style check (checkstyle/eslint)
  - [ ] Code is clear and concise
  - [ ] UI code is internationalised
  - [ ] Code has adequate comments where appropriate
  - Code is in an appropriate place
    - [ ] Classes are in appropriate packages
    - [ ] Code fits with class's responsibilities (SRP)
  - [ ] Configuration files are documented enough
  - If code is removed
    - [ ] No remaining code references the removed code
      - [ ] No orphaned rewrite rules
    - [ ] No orphaned config settings
    - [ ] No remaining comments refer to the removed code
    - [ ] Unused imports and libraries are removed
- Testing
  - [ ] New code has tests
  - [ ] Changed code has tests
  - [ ] All tests pass
  - [ ] Test coverage stable or increased
- Documentation
  - [ ] New features are documented
  - [ ] Docs removed for deleted features
  - [ ] Docs updated for all changed features
  - [ ] Developer/sysadmin docs updated if appropriate
- If there are new dependencies
  - [ ] Does each new dependency pass all the
     [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?
---

_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/24)

### CODE REVIEW

**Comment by davidmason** [comment]
Is there a JIRA for this?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/24#-:-KW0cjcyda3DzOgB2Wto:bvbuhk4)*

**Comment by davidmason** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/servlet/MDCInsertingServletFilter.java, line 35 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/24#-KW0djepe4k9e268hhbz:-KW0djeqIxLu5Ge4kcn6:b-8oac5x) ([raw file](https://github.com/zanata/zanata-platform/blob/148bf33236dbfe0969d14c64af0ccf7cc970b4c9/server/zanata-war/src/main/java/org/zanata/servlet/MDCInsertingServletFilter.java#L35)):*
> ```Java
> /**
>  * A servlet filter that inserts various values retrieved from the incoming http
>  * request into the MDC.
> ```

1. Does "various values" translate to just request+response URLs and status code?
2. What is the MDC?

---

*[server/zanata-war/src/main/java/org/zanata/servlet/MDCInsertingServletFilter.java, line 44 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/24#-KW0dKYr3fmgfk-BJQqa:-KW0dKYr3fmgfk-BJQqb:b-gh4sz7) ([raw file](https://github.com/zanata/zanata-platform/blob/148bf33236dbfe0969d14c64af0ccf7cc970b4c9/server/zanata-war/src/main/java/org/zanata/servlet/MDCInsertingServletFilter.java#L44)):*
> ```Java
> @WebFilter(filterName = "MDCInsertingServletFilter")
> public class MDCInsertingServletFilter implements Filter {
>     private static final org.slf4j.Logger logReq = org.slf4j.LoggerFactory.getLogger("org.zanata.requests");
> ```

Can `logReq` have less ambiguous name? I don't really know which word "Req" is short for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/24)*

**Comment by seanf** [comment]
Sorry @davidmason, I created this from an old branch I had sitting around, but forgot I had created a class called RequestLoggingFilter for this purpose.

I've made a change to the javadoc though, based on your feedback.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/24#-:-KW0plZDoVS5k032RKl4:b-69tk3x)*

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/24#-:-KW1GjWb2ZoAwf5WBhIL:bnfp4nl)*

**Pull request merged**
