### PR TITLE
ZNTA-1437 allow dev docker container to send mail

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1437

Update docker dev image and script so that user can specify a working smtp server.
Run the script ```rundev.sh -e smtphost```

*NOTE* this PR is based on top of #30 Only the last commit is relevant to the task.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/35)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/docker/rundev.sh, line 85 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW0W5kDyxfjmUdS9p5Z:-KW0W5kEEgV7j17jdtyR:bawh35n) ([raw file](https://github.com/zanata/zanata-platform/blob/e04332ce5463f52b76b68490eba3d6066a070d83/server/docker/rundev.sh#L85)):*
> ```Shell
>       echo "========   HELP   ========="
>       echo "-e <smtp email host>  : smtp mail host"
>       echo "-l <username:password>: smtp username and password separated by colon"
> ```

`-l` seems like an odd choice. I suppose it stands for login? It would be easier to remember as a mnemonic if the help was something like:

    echo "-l <username:password>: smtp login: username and password separated by colon"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/35)*

**Comment by seanf** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/docker/Dockerfile, line 3 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63RyHCKmkHqz2ySWG:-KW63RyHCKmkHqz2ySWH:b-z6tgli) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/docker/Dockerfile#L3)):*
> ```Dockerfile
> FROM jboss/wildfly:10.1.0.Final
> 
> ENV DB_HOSTNAME=zanatadb MAIL_HOST=localhost MAIL_USERNAME=' ' MAIL_PASSWORD=' '
> ```

Why the spaces between the quotes?

---

*[server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63YiU99xYcWgfNGSY:-KW63YiU99xYcWgfNGSZ:b-6sabh5) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml#L21)):*
> ```XML
>   <resource-ref>
>     <res-ref-name>mail/Default</res-ref-name>
>     <jndi-name>java:jboss/mail/Default</jndi-name>
> ```

Will the appserver still be able to reject the deployment if the JNDI resource is not available?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/35)*

**Comment by huangp** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/docker/Dockerfile, line 3 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63RyHCKmkHqz2ySWG:-KW66PW7X1UUECv61T71:b-2eui9q) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/docker/Dockerfile#L3)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Why the spaces between the quotes?
</details>
This is the limitation of including env variable in jboss cli script. You got to provide it in such form```${env.some:defaultValue}```. The defaultValue there must not be empty or jboss cli will reject it.

---

*[server/docker/rundev.sh, line 85 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW0W5kDyxfjmUdS9p5Z:-KW673U2daDAvh6LNecr:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/e04332ce5463f52b76b68490eba3d6066a070d83/server/docker/rundev.sh#L85)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> `-l` seems like an odd choice. I suppose it stands for login? It would be easier to remember as a mnemonic if the help was something like:
> 
>     echo "-l <username:password>: smtp login: username and password separated by colon"
</details>
Done.

---

*[server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63YiU99xYcWgfNGSY:-KW674urr3ABTFL_Osq9:b-7e8isy) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml#L21)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Will the appserver still be able to reject the deployment if the JNDI resource is not available?
</details>
Apparently no. It's not working when Damian tried to test it because the jndi is not available (but the deployment still goes on). This change is to make sure it's available. There is no check in our code to make sure it's there AFAIK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/35)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/docker/Dockerfile, line 3 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63RyHCKmkHqz2ySWG:-KW6udBONdsCUz85G6vf:bom3j3b) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/docker/Dockerfile#L3)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> This is the limitation of including env variable in jboss cli script. You got to provide it in such form```${env.some:defaultValue}```. The defaultValue there must not be empty or jboss cli will reject it.
</details>
Have you tried using `${env.some}` instead of `${env.some:defaultValue}` in the cli script? If it's anything like the variable expansion in standalone.xml, the `:defaultValue` bit is optional.

---

*[server/docker/conf/zanata-config.cli, line 104 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW6vAEeI_ON8b6mrQ25:-KW6vAEeI_ON8b6mrQ26:b-5o0r1p) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/docker/conf/zanata-config.cli#L104)):*
> ```
> /subsystem=mail/mail-session=default/server=smtp:write-attribute(name=outbound-socket-binding-ref,value=my-smtp)
> /subsystem=mail/mail-session=default/server=smtp:write-attribute(name=username,value=${env.MAIL_USERNAME: })
> /subsystem=mail/mail-session=default/server=smtp:write-attribute(name=password,value=${env.MAIL_PASSWORD: })
> ```

I think you should be able to use `${env.MAIL_USERNAME}` and `${env.MAIL_PASSWORD}`.

---

*[server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63YiU99xYcWgfNGSY:-KW6v_TAXi2tlRir7qAn:b3zgex7) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml#L21)):*
I'm confused. I was under the impression you removed this, but now it looks like you added it. Which would be good.

> This change is to make sure it's available. 

How do you mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/35)*

**Comment by seanf** [comment]
@huangp Could you please give this PR a proper name?

Also, looks like it needs rebasing.

**Comment by huangp** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/docker/Dockerfile, line 3 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63RyHCKmkHqz2ySWG:-KWAM5-kh5lzYwBL6-kF:b6uzd) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/docker/Dockerfile#L3)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Have you tried using `${env.some}` instead of `${env.some:defaultValue}` in the cli script? If it's anything like the variable expansion in standalone.xml, the `:defaultValue` bit is optional.
</details>
It will not work. See http://stackoverflow.com/questions/29823173/wildfly-cli-disable-environment-variable-resolution-i-e-write-unresolved-var/29824058#29824058 but I am not sure whether wildfly 10 or offline mode is different. 

---

*[server/docker/conf/zanata-config.cli, line 104 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW6vAEeI_ON8b6mrQ25:-KWAMRxJxiSD3TwNxEWd:b-mkr36f) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/docker/conf/zanata-config.cli#L104)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I think you should be able to use `${env.MAIL_USERNAME}` and `${env.MAIL_PASSWORD}`.
</details>
See above. But I will give it a try and see.

---

*[server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63YiU99xYcWgfNGSY:-KWAM_THEQP6TIC3xuH-:b-ntll0e) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml#L21)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I'm confused. I was under the impression you removed this, but now it looks like you added it. Which would be good.
> 
> > This change is to make sure it's available. 
> 
> How do you mean?
</details>
Before my last commit, in the Dockerfile, I declare ENV MAIL_USERNAME and MAIL_PASSWORD and the value are all empty. At startup time, jboss displays an error saying username attribute can not have empty value and caused the mail session JNDI resource to fail. But it won't stop Zanata from being deployed. Only when you try to use mail session, you will get exception.

So no I didn't remove it. It wasn't checking at all (I vaguely remember we did back in the Seam days so probably lost it during migration). This change still won't check whether it's available. I will do another commit to check it on startup. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/35)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/docker/Dockerfile, line 3 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63RyHCKmkHqz2ySWG:-KWAdGPLV0gI_MUlMTQ9:b-n1xf1y) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/docker/Dockerfile#L3)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> It will not work. See http://stackoverflow.com/questions/29823173/wildfly-cli-disable-environment-variable-resolution-i-e-write-unresolved-var/29824058#29824058 but I am not sure whether wildfly 10 or offline mode is different. 
</details>
(Just for the record, the real problem is that WildFly doesn't like it _at runtime_ if these values expand to the empty string (disallowed by the XML schema or something), so we have to put something there.)

---

*[server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63YiU99xYcWgfNGSY:-KWAdwePZ1GpPHmIgg9-:b-r7w2j6) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml#L21)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Before my last commit, in the Dockerfile, I declare ENV MAIL_USERNAME and MAIL_PASSWORD and the value are all empty. At startup time, jboss displays an error saying username attribute can not have empty value and caused the mail session JNDI resource to fail. But it won't stop Zanata from being deployed. Only when you try to use mail session, you will get exception.
> 
> So no I didn't remove it. It wasn't checking at all (I vaguely remember we did back in the Seam days so probably lost it during migration). This change still won't check whether it's available. I will do another commit to check it on startup. 
</details>
Sorry, just to clarify: does the presence of `java:jboss/mail/Default` in jboss-web.xml cause deployment to be aborted if that JNDI binding doesn't exist? If not, what is it for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/35)*

**Comment by huangp** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/docker/Dockerfile, line 3 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63RyHCKmkHqz2ySWG:-KWASQ49FPztJOoMBK1z:b-z8urp0) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/docker/Dockerfile#L3)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> It will not work. See http://stackoverflow.com/questions/29823173/wildfly-cli-disable-environment-variable-resolution-i-e-write-unresolved-var/29824058#29824058 but I am not sure whether wildfly 10 or offline mode is different. 
</details>
So from EAP6.1.0 onward, the default value of variable substitution is false by default now. https://access.redhat.com/solutions/321513 So now I don't need to apply the workaround anymore. 

---

*[server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63YiU99xYcWgfNGSY:-KWArSntKeYvDqrT2lz1:bi6jvrl) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml#L21)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Sorry, just to clarify: does the presence of `java:jboss/mail/Default` in jboss-web.xml cause deployment to be aborted if that JNDI binding doesn't exist? If not, what is it for?
</details>
Yes it will fail the deployment. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/35)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-KW63YiU99xYcWgfNGSY:-KWBlH9iR3Yb5nhJK0sB:bndjf5i) ([raw file](https://github.com/zanata/zanata-platform/blob/7a4a233a659a87bf8eafdbbb316de3eafceb32ce/server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml#L21)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Yes it will fail the deployment. 
</details>
Okay, that's good. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/35#-:-KWBlPG5aWoCtDuMSb0w:bnfp4nl)*

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested, thanks for doing this.
@huangp will this be executed by Jenkins at all? Should it?

**Comment by huangp** [comment]
I wasn't touching the code when I started but then I changed some config in code. So I guess now it should go through jenkins. I removed the no ci tag from the description. Will let jenkins check it.

**Comment by huangp** [comment]
@zanata-jenkins retest this please

**Pull request merged**
