### PR TITLE
chore(storybook): skip coverage stats on storybook files

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: *There is no JIRA for this*

All stories.js and story.js files are just for the storybook overview,
and similar to test files it is not appropriate to unit test them.
This change excludes all files with either of those names from the
coverage statistics.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/276)

### CODE REVIEW

**Comment by seanf** [comment]
@davidmason If these files are similar to tests, could we put them in the tests directories instead? There'd be no need for a filename exclusion then.

**Comment by davidmason** [comment]
@seanf I think jest would try to execute them, so we would need an exclusion in a different place. It is convenient to develop the component in parallel with the component's story, so I would want more than just avoiding a line of config to justify putting them somewhere distant from the component definition.

**Comment by seanf** [comment]
> It is convenient to develop the component in parallel with the component's story, 

The same should be very much true of tests. But we cope with them being in a separate "tests" directory. That's what IDEs are for.

> so I would want more than just avoiding a line of config to justify putting them somewhere distant from the component definition

@davidmason It's just that excluding source files which are in the source directory is a slippery slope. We ended up with far too many exclusions with Cobertura, in the Java code, before we switched to JaCoCo and reset the lot. 

And that line of config means that if we ever have a real source file named `story.js` or `stories.js` (for whatever reason) its test coverage will be ignored. So now we have to remember never to name a real source file by either of those names. Keeping a very clear separation between production code and non-production code is a good thing.

Doesn't jest support exclusion patterns?

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/276#-:-Ki5KAnJKGgrnS0J4wD6:bnfp4nl)*

**Comment by aeng** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/package.json, line 140 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/276#-Ki5LVjuBOYshTHS3qAx:-Ki5LVjuBOYshTHS3qAy:b-afcsai) ([raw file](https://github.com/zanata/zanata-platform/blob/f3bf7b57a1ef88d5a76602b23eaf927a6f0337d0/server/zanata-frontend/src/frontend/package.json#L140)):*
> ```JSON
>       "app/**/*.{js,jsx}",
>       "!**/node_modules/**",
>       "!app/**/stor{y,ies}.js"
> ```

Should we use this? 

https://facebook.github.io/jest/docs/configuration.html#coveragepathignorepatterns-array-string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/276)*

**Comment by davidmason** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/package.json, line 140 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/276#-Ki5LVjuBOYshTHS3qAx:-Ki7bP94WEdLvRgae_Um:bk7ln50) ([raw file](https://github.com/zanata/zanata-platform/blob/f3bf7b57a1ef88d5a76602b23eaf927a6f0337d0/server/zanata-frontend/src/frontend/package.json#L140)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should we use this? 

https://facebook.github.io/jest/docs/configuration.html#coveragepathignorepatterns-array-string
</blockquote></details>

I think that has a different use-case - when there is something too complicated to represent with a glob pattern. Since this is just some simple filenames, I prefer this way since it keeps everything in one place so it is easy to see which files are covered by just looking at this one block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/276)*

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/276)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/package.json, line 140 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/276#-Ki3zyyY2KPGnkWIoNqH-r1-140:-Ki7dZ-DQmZuRHETf_bv:b-keipjz) ([raw file](https://github.com/zanata/zanata-platform/blob/f3bf7b57a1ef88d5a76602b23eaf927a6f0337d0/server/zanata-frontend/src/frontend/package.json#L140)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should use jest converageIgnore?

https://facebook.github.io/jest/docs/configuration.html#coveragepathignorepatterns-array-string
</blockquote></details>

Do you own stocks in Jest `coveragePathIgnorePatterns` or something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/276)*

**Pull request merged**
