### PR TITLE
Enable TMXDummyRestTest

### PR DESCRIPTION
**Pull request by seanf**
I recommend reviewing the commits separately.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/387)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/test/java/org/zanata/ZanataRestTest.java, line 88 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/387#-KmOVgY456Q0FSzQzdpp:-KmOVgY5jTDXpTivNzwr:b-i3p1gj) ([raw file](https://github.com/zanata/zanata-platform/blob/0dff56f6fcf4a19030a0ec4dc28823181ba47e25/server/zanata-war/src/test/java/org/zanata/ZanataRestTest.java#L88)):*
> ```Java
>         }
> 
>         // TODO: attach mock dispatcher into resteasyClient
> ```

Note: This is removed in seperate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/387)*

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r2.
Review status: 3 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-war/src/test/java/org/zanata/rest/service/TMXDummyRestTest.java, line 67 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/387#-KmOW3A1q7IF9imPFK0c:-KmOW3A1q7IF9imPFK0d:b-8egfha) ([raw file](https://github.com/zanata/zanata-platform/blob/d72e28ccab82a8dc8b57f80c165ba880e5bcf8d1/server/zanata-war/src/test/java/org/zanata/rest/service/TMXDummyRestTest.java#L67)):*
> ```Java
>     @Zanata
>     HibernateEntityManagerFactory hibernateEntityManagerFactory;
> //    SessionFactory sessionFactory;
> ```

Should remove this line

---

*[server/zanata-war/src/test/java/org/zanata/rest/service/TMXDummyRestTest.java, line 140 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/387#-KmOWIM4FETxH-v1NTHW:-KmOWIM4FETxH-v1NTHX:bdeq0uc) ([raw file](https://github.com/zanata/zanata-platform/blob/d72e28ccab82a8dc8b57f80c165ba880e5bcf8d1/server/zanata-war/src/test/java/org/zanata/rest/service/TMXDummyRestTest.java#L140)):*
> ```Java
>     @Test
>     @InRequestScope
>     public void testGetTmx() throws Exception {
> ```

This test not working yet?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/387)*

**Comment by seanf** [comment]
Review status: 3 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-war/src/test/java/org/zanata/ZanataRestTest.java, line 88 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/387#-KmOVgY456Q0FSzQzdpp:-KmOdd0LeO7iEuk1z5Fh:b32w0x) ([raw file](https://github.com/zanata/zanata-platform/blob/0dff56f6fcf4a19030a0ec4dc28823181ba47e25/server/zanata-war/src/test/java/org/zanata/ZanataRestTest.java#L88)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Note: This is removed in seperate PR.
</blockquote></details>

OK

---

*[server/zanata-war/src/test/java/org/zanata/rest/service/TMXDummyRestTest.java, line 67 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/387#-KmOW3A1q7IF9imPFK0c:-KmOdUiFJdOWBRl08_L2:b43oxvl) ([raw file](https://github.com/zanata/zanata-platform/blob/d72e28ccab82a8dc8b57f80c165ba880e5bcf8d1/server/zanata-war/src/test/java/org/zanata/rest/service/TMXDummyRestTest.java#L67)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should remove this line
</blockquote></details>

It's removed in the later commit, where I switched from HibernateEntityManagerFactory to SessionFactory.

---

*[server/zanata-war/src/test/java/org/zanata/rest/service/TMXDummyRestTest.java, line 140 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/387#-KmOWIM4FETxH-v1NTHW:-KmOcythS4JN6NoviB5o:b-oj8rml) ([raw file](https://github.com/zanata/zanata-platform/blob/d72e28ccab82a8dc8b57f80c165ba880e5bcf8d1/server/zanata-war/src/test/java/org/zanata/rest/service/TMXDummyRestTest.java#L140)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This test not working yet?
</blockquote></details>

Not yet. This is basically the same test which was there before and ignored. I didn't want to spend a lot of time right now on setting up Sessions and things. The idea for now is just to get the in-memory executor hooked up, and the other, simpler test was enough for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/387)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/387#-:-Km_FNqs9UmCNzADxX3Q:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r2.
Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/387)*

**Comment by aeng** [comment]
Reviewed 4 of 4 files at r3.
Review status: 2 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/387)*

**Comment by aeng** [comment]
Reviewed 6 of 8 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/387)*

**Pull request merged**
