### PR TITLE
Improve REST API docs

### PR DESCRIPTION
**Pull request by carlosmunoz**
Updates to our enunciate declarations so that API docs have an improved presentation. Changes include:

- Color coded response codes
- Response examples
- Additional documentation for parameters and headers
- other minor improvements...

To generate the api docs locally, type the following command at the root of `zanata-platform`:

```sh
mvn com.webcohesion.enunciate:enunciate-slim-maven-plugin:docs -pl :zanata-common-api
```

Then open the following file in a browser:

`zanata-platform/api/zanata-common-api/target/site/rest-api-docs/index.html`

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/415)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 28 of 29 files at r1.
Review status: 28 of 29 files reviewed at latest revision, 3 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 274 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-Kodjsz3Be8IajQidjj7:-Kodjsz3Be8IajQidjj8:b-kl8g4c) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L274)):*
> ```Java
> 
>     /**
>      * Upload glossary file (currently supported formats: po, csv)
> ```

good catch!

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 326 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodkcM21xjF2_iPefxJ:-KodkcM21xjF2_iPefxK:b-yk7n5t) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L326)):*
> ```Java
>      * @responseExample
>      *
>      * TODO Need to define a 'produces' header
> ```

It just return count of deleted entries. Integer.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java, line 82 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodksiRZKh450m6rwJR:-KodksiRZKh450m6rwJS:b-rfbrbs) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java#L82)):*
> ```Java
>             @ResponseCode(code = 404, condition = "A project iteration could " +
>                     "not be found for the given parameters"),
>             @ResponseCode(code = 500,
> ```

I think we can move all 500 error code to class level for all method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/415)*

**Comment by seanf** [comment]
Review status: 28 of 29 files reviewed at latest revision, 9 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/dto/VersionInfo.java, line 59 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodxVFHNCo9U1RI40O_:-KodxVFHNCo9U1RI40Oa:b-itl3r8) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/dto/VersionInfo.java#L59)):*
> ```Java
> 
>     /**
>      * Timestamp when the current system version was built
> ```

Going by the example, perhaps we should say ISO8601 timestamp.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/CopyTransResource.java, line 70 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodxnFMsVlfVpCHOCiS:-KodxnFMsVlfVpCHOCiT:b-2i4fhb) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/CopyTransResource.java#L70)):*
> ```Java
>                             "The status of the process is also returned in the response's body."),
>             @ResponseCode(code = 500,
>                     condition = "If there is an unexpected error in the server while performing this operation")
> ```

I'm not sure if it's worth listing 5xx codes in these places. Internal server errors are a possibility on *every* end-point if there's a bug, but do we really want to list it every time? What about 502 and 503 which the client will see if there's a proxy error? I don't think we need to list the codes which apply to every resource on the internet.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 193 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodyyzCq_6psgI60snv:-KodyyzDDjClIfJ2Migu:b-5o5u5w) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L193)):*
> ```Java
>             @ResponseCode(code = 400, condition = "When searchText is missing"),
>             @ResponseCode(code = 400, condition = "When transLocale is missing"),
>             @ResponseCode(code = 400, condition = "When there is an error parsing the searchText"),
> ```

Is Enunciate using these '400' duplicates as expected? Perhaps it would be simpler to reduce them to one ResponseCode.

That's assuming we even need to document such low-level details of the implementation here. It's probably better to document such assumptions/requirements against the relevant parameters.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 229 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodzEU849YBgB-FGeyu:-KodzEU849YBgB-FGeyv:b-rqs6rk) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L229)):*
> ```Java
>      * Download all glossary entries as a file
>      *
>      * @param fileType po or cvs (case insensitive)
> ```

Should be 'csv'. But do we want to say "currently supported" here too?

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java, line 82 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodksiRZKh450m6rwJR:-KodzSknbnyeNohw8825:b2ek3v0) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java#L82)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think we can move all 500 error code to class level for all method.
</blockquote></details>

Or package level, if that's possible? Or just delete them entirely as assumed knowledge.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java, line 154 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodziI9pJAHU1VD98Y4:-KodziI9pJAHU1VD98Y5:b-1yvfns) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java#L154)):*
> ```Java
>                     " for the specified parameters"),
>             @ResponseCode(code = 404, condition = "A project version could " +
>                     "not be found for the given parameters"),
> ```

Can't we just say somewhere, once, that 404 means the resource is not found? Maintaining all the little specific reasons why Zanata might give a 404 seems like overkill, since it's just standard REST/HTTP.

I think the same might apply to all the 4xx codes, since they have known meanings in REST, and we try to follow them.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslatedDocResource.java, line 88 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-Koe-EI5oVYjawmN4HVH:-Koe-EI5oVYjawmN4HVI:b1qokqw) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslatedDocResource.java#L88)):*
> ```Java
>      *            The translation extensions to retrieve (e.g. "comment"). This
>      *            parameter allows multiple values.
>      * @param createSkeletons
> ```

Perhaps we should rename the Java parameter to match the HTTP parameter ("skeletons")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/415)*

**Comment by carlosmunoz** [comment]
Review status: 28 of 29 files reviewed at latest revision, 9 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/CopyTransResource.java, line 70 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodxnFMsVlfVpCHOCiS:-Kogwt_5YQ1p0oPYVacz:bwefx3q) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/CopyTransResource.java#L70)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I'm not sure if it's worth listing 5xx codes in these places. Internal server errors are a possibility on *every* end-point if there's a bug, but do we really want to list it every time? What about 502 and 503 which the client will see if there's a proxy error? I don't think we need to list the codes which apply to every resource on the internet.
</blockquote></details>

It isn't. I've been slowly moving these up to the class level, but not all of them have been covered. 

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 193 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodyyzCq_6psgI60snv:-Kogx6z5YSL7X4QGNNZS:b4grikq) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L193)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Is Enunciate using these '400' duplicates as expected? Perhaps it would be simpler to reduce them to one ResponseCode.

That's assuming we even need to document such low-level details of the implementation here. It's probably better to document such assumptions/requirements against the relevant parameters.
</blockquote></details>

It is treating them as expected. Sample:


I think this is pretty informative, showing the user each specific reason why their request might 404.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 326 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodkcM21xjF2_iPefxJ:-KogxqqQpAtNDWNMJUIo:b-2f474) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L326)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

It just return count of deleted entries. Integer.
</blockquote></details>

Yeah, still added the comment there as there might be a way to specify that, even if it's just a plain text header.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java, line 82 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodksiRZKh450m6rwJR:-Kogy0CqBmRc101zA8Sf:bsm5rq1) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java#L82)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Or package level, if that's possible? Or just delete them entirely as assumed knowledge.
</blockquote></details>

I tried package level, didn't work unfortunately. Best next thing is class level which should be a work in progress... you know, continuous integration FTW.

As for assumed knowledge... nah, lets be specific about these things. If anything it's a reminder that things might go awry at any given time.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java, line 154 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodziI9pJAHU1VD98Y4:-KogyTwrp2deRKH9yHvh:b-neofbz) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java#L154)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Can't we just say somewhere, once, that 404 means the resource is not found? Maintaining all the little specific reasons why Zanata might give a 404 seems like overkill, since it's just standard REST/HTTP.

I think the same might apply to all the 4xx codes, since they have known meanings in REST, and we try to follow them.
</blockquote></details>

Yes we could. It's useful to know which part of the resource may be the problem. For instance, a version resource might 404 because of the version or project. Same for documents. I'd say we could just say the resource if we provided the specific message as part of a response header or something, but then that would fall outside the scope of my pull request.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/415)*

**Comment by aeng** [comment]
Reviewed 1 of 29 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/415)*

**Comment by aeng** [comment]
@carlosmunoz I'm good with this PR. Maybe wait for @seanf to finish his review.

**Comment by seanf** [comment]
Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/415)*

**Comment by carlosmunoz** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/dto/VersionInfo.java, line 59 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodxVFHNCo9U1RI40O_:-KomL1n8iQjQnmmsw1-v:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/dto/VersionInfo.java#L59)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Going by the example, perhaps we should say ISO8601 timestamp.
</blockquote></details>

Done.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 229 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-KodzEU849YBgB-FGeyu:-KomLQEu-jCHhgBKx5tI:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L229)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Should be 'csv'. But do we want to say "currently supported" here too?
</blockquote></details>

Done.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslatedDocResource.java, line 88 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-Koe-EI5oVYjawmN4HVH:-KomM1mIBr0eJiNQXHsx:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/b9133fa6362292ae4c1e0b47a6620d3892d8eabf/api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslatedDocResource.java#L88)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Perhaps we should rename the Java parameter to match the HTTP parameter ("skeletons")
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/415)*

**Comment by carlosmunoz** [comment]
oh... something went wrong with my last push

**Comment by carlosmunoz** [comment]
better now...

**Comment by seanf** [comment]
I still don't like the precedent of documenting standard error codes (especially 500), but I suppose most of them were there already. Otherwise it LGTM.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-:-KooPwWvjwPWSlrQWMh0:b-nugdw9)*

**Comment by carlosmunoz** [comment]
@djansen-redhat @spathare21 Not sure if you want to check QA for this. Instructions on how to generate the docs are in the PR description.
@aeng There are still 3 unresolved discussions on Reviewable, but based on your go-ahead, I'll assume they are resolved.

**Comment by spathare21** [comment]
yes sure @carlosmunoz , I think reviewer haven't approved this PR until?

**Comment by seanf** [comment]
@spathare21 we're working an the assumption that @aeng just forgot to dismiss those 3 discussions in Reviewable.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/415#-:-KoxyVbr60bzk2ZKsQN1:bnfp4nl)*

**Comment by aeng** [comment]
Need QA?

**Comment by carlosmunoz** [comment]
@spathare21 @djansen-redhat I'll leave the second NO QA vote to one of you guys.

**Pull request merged**
