### PR TITLE
ZNTA-1651-explore

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1651

- Remove all zanata UI components from the containers/Explore/... in frontend
- Minor styling tweaks

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/150)

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/app/containers/Explore/GroupTeaser.jsx, line 34 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KairZj1vQ3Nek1AyZ5O:-KairZj1vQ3Nek1AyZ5P:b3volnw) ([raw file](https://github.com/zanata/zanata-platform/blob/82bf26abfeb3ebec06121d311ba9652d71f01748/server/zanata-frontend/src/frontend/app/containers/Explore/GroupTeaser.jsx#L34)):*
> ```JSX
>   const link = window.config.baseUrl + '/version-group/view/' + details.id
>   const className = status !== statusIcons.ACTIVE
>                   ? 'Fw(600) C(muted)'
> ```

I think you got a new class called bold-font? should the class name "text-bold"?

---

*[server/zanata-frontend/src/frontend/app/containers/Explore/LanguageTeamTeaser.jsx, line 16 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KairhYUqvQYyRlP5frN:-KairhYUqvQYyRlP5frO:b-cne5cr) ([raw file](https://github.com/zanata/zanata-platform/blob/82bf26abfeb3ebec06121d311ba9652d71f01748/server/zanata-frontend/src/frontend/app/containers/Explore/LanguageTeamTeaser.jsx#L16)):*
> ```JSX
>     <div className='teamTeaserView' name={name}>
>       <div className='flex-row'>
>         <Link link={link} className='bold-font'>
> ```

"text-bold"?

---

*[server/zanata-frontend/src/frontend/app/containers/Explore/LanguageTeamTeaser.jsx, line 23 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KairjCFeaR0aB2pfCPl:-KairjCG7l9zapgSRxoH:b-rcfz1d) ([raw file](https://github.com/zanata/zanata-platform/blob/82bf26abfeb3ebec06121d311ba9652d71f01748/server/zanata-frontend/src/frontend/app/containers/Explore/LanguageTeamTeaser.jsx#L23)):*
> ```JSX
>         </span>
>         <div className='langTeamTeaserViewMembers'>
>           <Icon name='users' className='s1 usersicon-muted' />
> ```

usericon-muted should use camel-case or hyphen seperated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/containers/Explore/LanguageTeamTeaser.jsx, line 23 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KairjCFeaR0aB2pfCPl:-KaiwfLIfZpK3KTA7FVg:b3679kr) ([raw file](https://github.com/zanata/zanata-platform/blob/82bf26abfeb3ebec06121d311ba9652d71f01748/server/zanata-frontend/src/frontend/app/containers/Explore/LanguageTeamTeaser.jsx#L23)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

usericon-muted should use camel-case or hyphen seperated?
</blockquote></details>

Hyphen separated for the moment, will make everything consistent in the atomic -> bootstrap css migration (ZNTA-1606) because there are a heap of icons with a hyphenated name. 
Bootstrap uses hypens not camel case, so I think removing camel case from css is the best approach for when I make things consistent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by kathryngo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Explore/GroupTeaser.jsx, line 34 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KairZj1vQ3Nek1AyZ5O:-Kaj-lyF0IRtmw8boq-b:bb6un1j) ([raw file](https://github.com/zanata/zanata-platform/blob/82bf26abfeb3ebec06121d311ba9652d71f01748/server/zanata-frontend/src/frontend/app/containers/Explore/GroupTeaser.jsx#L34)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think you got a new class called bold-font? should the class name "text-bold"?
</blockquote></details>

Done

---

*[server/zanata-frontend/src/frontend/app/containers/Explore/LanguageTeamTeaser.jsx, line 16 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KairhYUqvQYyRlP5frN:-Kaj-kbNWWbFiLFWDTXt:bb6un1j) ([raw file](https://github.com/zanata/zanata-platform/blob/82bf26abfeb3ebec06121d311ba9652d71f01748/server/zanata-frontend/src/frontend/app/containers/Explore/LanguageTeamTeaser.jsx#L16)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

"text-bold"?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by aeng** [comment]
Reviewed 2 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx, line 38 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KajYcmcQbap_Pq_-tS7:-KajYcmcQbap_Pq_-tS8:b-b6uk5d) ([raw file](https://github.com/zanata/zanata-platform/blob/eb046546178a9e5fdc9a951ee3dfad62e54d18c2/server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx#L38)):*
> ```JSX
>   const link = window.config.baseUrl + '/project/view/' + details.id
>   const className = status !== statusIcons.ACTIVE
>     ? 'Fw(600) C(muted)'
> ```

text-bold?

---

*[server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx, line 45 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KajYLNko5vSxV0H30lc:-KajYLNluHU_F3HF8pWH:b-5sar8i) ([raw file](https://github.com/zanata/zanata-platform/blob/eb046546178a9e5fdc9a951ee3dfad62e54d18c2/server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx#L45)):*
> ```JSX
>   return (
>     <div className='teaserViewTheme' name={name}>
>       <div className='teaserInner'>
> ```

There's alot of inconsistency in naming css class. I think for all the new classes that added in this PR, we should use hyphen `teaser-inner`, also `status-icons`, `header-icons`. Please go through the list and make sure its all hyphen seperated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by aeng** [comment]
Reviewed 1 of 8 files at r1.
Review status: 3 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx, line 45 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KajYLNko5vSxV0H30lc:-Kaja2O-X9hWAShswWMx:bebrt1w) ([raw file](https://github.com/zanata/zanata-platform/blob/eb046546178a9e5fdc9a951ee3dfad62e54d18c2/server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx#L45)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

There's alot of inconsistency in naming css class. I think for all the new classes that added in this PR, we should use hyphen `teaser-inner`, also `status-icons`, `header-icons`. Please go through the list and make sure its all hyphen seperated.
</blockquote></details>

Will do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx, line 45 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KajYLNko5vSxV0H30lc:-KajfmhgJ1S85fHMcX7U:bnvdhj7) ([raw file](https://github.com/zanata/zanata-platform/blob/eb046546178a9e5fdc9a951ee3dfad62e54d18c2/server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx#L45)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Will do
</blockquote></details>

@aeng , I cannot refactor many of these classes as they are used in the language container and other bootstrap branches. As I said earlier, this will need to wait until the atomic -> bootstrap tasks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by kathryngo** [comment]
Review status: 3 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx, line 38 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KajYcmcQbap_Pq_-tS7:-KajgLfcn6QUHQtdRpFg:bhshwnx) ([raw file](https://github.com/zanata/zanata-platform/blob/eb046546178a9e5fdc9a951ee3dfad62e54d18c2/server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx#L38)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

text-bold?
</blockquote></details>

Done. Will be in next commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by aeng** [comment]
Reviewed 1 of 8 files at r1, 3 of 3 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by aeng** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx, line 45 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KajYLNko5vSxV0H30lc:-KazHZ2ZDkQyT6eTYLkH:bud2t7y) ([raw file](https://github.com/zanata/zanata-platform/blob/eb046546178a9e5fdc9a951ee3dfad62e54d18c2/server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx#L45)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

@aeng , I cannot refactor many of these classes as they are used in the language container and other bootstrap branches. As I said earlier, this will need to wait until the atomic -> bootstrap tasks.
</blockquote></details>

We will run into big refactoring in the other task which I think we should avoid. At least fix all the "**teaserList**" class to be properly named.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx, line 45 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KajYLNko5vSxV0H30lc:-KazQ9lGf4DF2lDkbCZV:b-vnsh0q) ([raw file](https://github.com/zanata/zanata-platform/blob/eb046546178a9e5fdc9a951ee3dfad62e54d18c2/server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx#L45)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

We will run into big refactoring in the other task which I think we should avoid. At least fix all the "**teaserList**" class to be properly named.
</blockquote></details>

Some refactoring will be unavoidable due to changes across branches that arent merged. I'll change what I can though...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx, line 45 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KajYLNko5vSxV0H30lc:-Kb-YpaqA6zr3Y9XfCPd:bjrxeun) ([raw file](https://github.com/zanata/zanata-platform/blob/eb046546178a9e5fdc9a951ee3dfad62e54d18c2/server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx#L45)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Some refactoring will be unavoidable due to changes across branches that arent merged. I'll change what I can though...
</blockquote></details>

Ah, since the languages pages are merged into master I can go ahead and refactor all of this, no problem. I will remove the PR for my other branch (user-profile), so I can make sure the css is correct once this current branch has been pulled into master. That way I can do a progressive refactor and there won't be too much left over at the end. Still will need a bit of work, but it won't be too bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx, line 45 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-KajYLNko5vSxV0H30lc:-Kb7YTrinu6dzzT2OtsZ:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/eb046546178a9e5fdc9a951ee3dfad62e54d18c2/server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx#L45)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Ah, since the languages pages are merged into master I can go ahead and refactor all of this, no problem. I will remove the PR for my other branch (user-profile), so I can make sure the css is correct once this current branch has been pulled into master. That way I can do a progressive refactor and there won't be too much left over at the end. Still will need a bit of work, but it won't be too bad.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by aeng** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-:-Kb7dgGi_Lakop8CSfuP:bnfp4nl)*

**Comment by djansen-redhat** [comment]
Explore list icons are on a separate line to header - was this intentional?
This is otherwise fine.

**Comment by kathryngo** [comment]
Oops, I'll fix that!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-:-Kb7kpCPyuFrBPQWuciR:b1io0n5)*

**Comment by kathryngo** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/150#-:-Kb7p2Jue3KKwTRH4pGY:b-896fix)*

**Comment by djansen-redhat** [comment]
Looks good to me. Still waiting on Jenkins build.

**Pull request merged**
