### PR TITLE
Add Typescript (and bypass Babel)

### PR DESCRIPTION
**Pull request by seanf**
See https://github.com/Microsoft/TypeScript-React-Conversion-Guide#typescript-react-conversion-guide

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/658)

### CODE REVIEW

**Comment by seanf** [comment]
Unit tests are passing, but currently having problems resolving some modules in the browser when loading the root web page. Both with frontend's `make watch` (http://localhost:8000)

```
frontend.css Failed to load resource: the server responded with a status of 404 (Not Found)
webpack:///./app/utils/DateHelper.js?:101 Uncaught TypeError: moment_1.default is not a function
    at Object.startDate (webpack:///./app/utils/DateHelper.js?:101)
    at Object.getDateRange (webpack:///./app/utils/DateHelper.js?:144)
    at eval (webpack:///./app/reducers/profile-reducer.js?:204)
    at Object.<anonymous> (frontend.js:17057)
    at __webpack_require__ (frontend.js:20)
    at eval (webpack:///./app/reducers/index.js?:8)
    at Object.<anonymous> (frontend.js:16145)
    at __webpack_require__ (frontend.js:20)
    at eval (webpack:///./app/index.js?:14)
    at Object.<anonymous> (frontend.js:11337)
frontend.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

and proper war deployment (apparently having trouble with `import PropTypes from 'prop-types'`):
```
NavIcon.jsx:31 Uncaught TypeError: Cannot read property 'string' of undefined
    at eval (NavIcon.jsx:31)
    at Object.08gb (runtime.69fb9ed8.cache.js:441)
    at __webpack_require__ (runtime.69fb9ed8.cache.js:55)
    at eval (NavItem.jsx:22)
    at Object.HPNb (runtime.69fb9ed8.cache.js:2797)
    at __webpack_require__ (runtime.69fb9ed8.cache.js:55)
    at eval (index.jsx:22)
    at Object.3pQB (runtime.69fb9ed8.cache.js:869)
    at __webpack_require__ (runtime.69fb9ed8.cache.js:55)
    at eval (index.js:3)
```

**Comment by huangp** [comment]
Reviewed 2 of 8 files at r1, 1 of 3 files at r2, 24 of 248 files at r3, 14 of 34 files at r4, 28 of 35 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/tsconfig.json, line 8 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/658#-L4E5W0h_29eok7jhRDN:-L4E5W0h_29eok7jhRDO:b3x3b9v) ([raw file](https://github.com/zanata/zanata-platform/blob/86c1a993f09b44cd414b51ed0bf1ea9483679d74/server/zanata-frontend/src/tsconfig.json#L8)):*
> ```JSON
>         "useCache": true
>     },
>     "compilerOptions": {
> ```

a link to the doc will be helpful

---

*[server/zanata-frontend/src/app/components/Loader/index.tsx, line 16 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/658#-L4DydlNrZVn3Rj0N43C:-L4DydlO7A0yWr8AqNd8:bg84f59) ([raw file](https://github.com/zanata/zanata-platform/blob/86c1a993f09b44cd414b51ed0bf1ea9483679d74/server/zanata-frontend/src/app/components/Loader/index.tsx#L16)):*
> ```XML
> 
> interface LoaderProps {
>   className: string
> ```

This should be optional

---

*[server/zanata-frontend/src/app/components/LockIcon/index.tsx, line 24 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/658#-L4DyuPQSDh2Gpv8Xx9i:-L4DyuPQSDh2Gpv8Xx9j:b-j573pr) ([raw file](https://github.com/zanata/zanata-platform/blob/86c1a993f09b44cd414b51ed0bf1ea9483679d74/server/zanata-frontend/src/app/components/LockIcon/index.tsx#L24)):*
> ```XML
> 
> interface LockIconProps {
>   status: any // TODO should be one of entityStatuses
> ```

make entityStatus a ts file and add types

---

*[server/zanata-frontend/src/app/editor/actions/settings-actions.js, line 33 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/658#-L4E--e_YYoHig1Lmm9s:-L4E--e_YYoHig1Lmm9t:b-fs6kxd) ([raw file](https://github.com/zanata/zanata-platform/blob/86c1a993f09b44cd414b51ed0bf1ea9483679d74/server/zanata-frontend/src/app/editor/actions/settings-actions.js#L33)):*
> ```JavaScript
> 
> // Should be pretty fast: https://stackoverflow.com/a/34491287/14379
> function emptyObject (obj) {
> ```

move this to util

---

*[server/zanata-frontend/src/scripts/silence-React-15-deprecations.js, line 1 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/658#-L4E4-7Z9st6tbLhN2Ue:-L4E4-7Z9st6tbLhN2Uf:b693hld) ([raw file](https://github.com/zanata/zanata-platform/blob/86c1a993f09b44cd414b51ed0bf1ea9483679d74/server/zanata-frontend/src/scripts/silence-React-15-deprecations.js#L1)):*
> ```JavaScript
> const React = require('react')
> ```

this file is not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/658)*

**Comment by seanf** [comment]
Review status: 51 of 71 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/zanata-frontend/src/tsconfig.json, line 8 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/658#-L4E5W0h_29eok7jhRDN:-L4EybHb-ij45FrIEPId:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/86c1a993f09b44cd414b51ed0bf1ea9483679d74/server/zanata-frontend/src/tsconfig.json#L8)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

a link to the doc will be helpful
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/app/components/Loader/index.tsx, line 16 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/658#-L4DydlNrZVn3Rj0N43C:-L4F-m6y8XsQy92cG6J1:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/86c1a993f09b44cd414b51ed0bf1ea9483679d74/server/zanata-frontend/src/app/components/Loader/index.tsx#L16)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

This should be optional
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/app/components/LockIcon/index.tsx, line 24 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/658#-L4DyuPQSDh2Gpv8Xx9i:-L4FI8AVri6Xe0OcQEq2:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/86c1a993f09b44cd414b51ed0bf1ea9483679d74/server/zanata-frontend/src/app/components/LockIcon/index.tsx#L24)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

make entityStatus a ts file and add types
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/app/editor/actions/settings-actions.js, line 33 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/658#-L4E--e_YYoHig1Lmm9s:-L4EzzkN-Nq5gcxbArVk:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/86c1a993f09b44cd414b51ed0bf1ea9483679d74/server/zanata-frontend/src/app/editor/actions/settings-actions.js#L33)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

move this to util
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/scripts/silence-React-15-deprecations.js, line 1 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/658#-L4E4-7Z9st6tbLhN2Ue:-L4F-DcCNg5LUSFMoSlr:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/86c1a993f09b44cd414b51ed0bf1ea9483679d74/server/zanata-frontend/src/scripts/silence-React-15-deprecations.js#L1)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

this file is not needed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/658)*

**Comment by seanf** [comment]
@huangp Ready for another review. Thanks!

**Comment by huangp** [comment]
:lgtm: +Reviewed 

---

Reviewed 5 of 36 files at r5, 18 of 23 files at r6, 14 of 14 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/658#-:-L4IgjjMr_mkKPiPU4gC:biv5e4t)*

**Comment by huangp** [comment]
Reviewed 1 of 23 files at r6, 5 of 5 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/658)*

**Comment by djansen-redhat** [comment]
Verified (exploratory testing)

**Pull request merged**
