### PR TITLE
Znta 845 findbugs

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-845

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/303)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@aeng I noticed the codecov checks are not showing - any idea why?

**Comment by aeng** [comment]
@djansen-redhat no idea.. lol

**Comment by huangp** [comment]
Reviewed 234 of 270 files at r1, 52 of 52 files at r2.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/UserConfigHolder.java, line 42 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjpfPdUb-kqriAaAjip:-KjpfPdVot0RxXvtiCUl:bxsvscd) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/UserConfigHolder.java#L42)):*
> ```Java
> public class UserConfigHolder implements IsSerializable {
>     @SuppressFBWarnings("SE_BAD_FIELD")
>     public static final Predicate<ContentState> INCOMPLETE_PREDICATE =
> ```

Can you add transient to these fields to get rid of the warning? I think it will better to suppress them

---

*[server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetReviewComment.java, line 122 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjpjRJkvr-6KvPnKEa4:-KjpjRJkvr-6KvPnKEa5:bylwqzh) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetReviewComment.java#L122)):*
> ```Java
>         if (targetVersion != null ? !targetVersion.equals(that.targetVersion) :
>                 that.targetVersion != null) return false;
>         return commenterName != null ?
> ```

commenterName should not be part of equal and hashcode

---

*[server/zanata-war/src/main/java/org/zanata/H2DocumentHistoryTrigger.java, line 17 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjpnhk2mZwSarFQZ7-c:-Kjpnhk3gKnUE7ApIc4H:b-yyok9f) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/H2DocumentHistoryTrigger.java#L17)):*
> ```Java
>             throws SQLException {
>         PreparedStatement prep = null;
>         try {
> ```

Could use try with resources

---

*[server/zanata-war/src/main/java/org/zanata/action/CopyTransOptionsModel.java, line 160 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjpoYTchRYBpWnqjZMk:-KjpoYTchRYBpWnqjZMl:b-7r6bds) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/action/CopyTransOptionsModel.java#L160)):*
> ```Java
>     }
> 
>     public synchronized List<RuleAction> getRuleActions() {
> ```

This change will slow the method call down. Previously synchronization only happen when value is null. Now it will happen all the time

---

*[server/zanata-war/src/main/java/org/zanata/action/ProjectHome.java, line 1305 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjporBKmG1nPq1TdHlU:-KjporBKmG1nPq1TdHlV:bvd5yzd) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/action/ProjectHome.java#L1305)):*
> ```Java
>     }
> 
>     public synchronized List<HProjectIteration> getVersions() {
> ```

This change means synchronization will happen all the time oppose to only happen when value is null

---

*[server/zanata-war/src/main/java/org/zanata/action/RoleSearch.java, line 52 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjppccmUmtfk9xSGWUI:-Kjppccnz1PA8v5Sr9EB:b-sl5zdk) ([raw file](https://github.com/zanata/zanata-platform/blob/9819a47f418d5767f17f49cac1bc0eaba07b0e0a/server/zanata-war/src/main/java/org/zanata/action/RoleSearch.java#L52)):*
> ```Java
> 
>         if (roles == null) return "";
> ```

Why is this removed?

---

*[server/zanata-war/src/main/java/org/zanata/action/SortingType.java, line 47 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjppqw4bHuVfD6qMf-p:-Kjppqw4bHuVfD6qMf-q:b278o20) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/action/SortingType.java#L47)):*
> ```Java
>         public final static SortOption CREATED_DATE = new SortOption("Created date", true);
>         public final static SortOption NAME = new SortOption("Name", true);
>         public final static SortOption ROLE = new SortOption("Role", true);
> ```

Any reason for making this change?

---

*[server/zanata-war/src/main/java/org/zanata/action/UserSearch.java, line 46 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjppwaDmon9bsULPGMM:-KjppwaDmon9bsULPGMN:b-sl5zdk) ([raw file](https://github.com/zanata/zanata-platform/blob/9819a47f418d5767f17f49cac1bc0eaba07b0e0a/server/zanata-war/src/main/java/org/zanata/action/UserSearch.java#L46)):*
> ```Java
>             return "";
>         }
> ```

Why is this removed?

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java, line 52 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjps4GKXtz--vSGIewn:-Kjps4GKXtz--vSGIewo:b-xs4rxr) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java#L52)):*
> ```Java
>             ResultSet rs2 = null;
>             ResultSet rs3 = null;
>             try {
> ```

Should use try with resources

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/GenerateHashForGlossaryEntry.java, line 97 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjps97-2h0pdGxIEE-P:-Kjps97-2h0pdGxIEE-Q:b-xs4rxr) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/GenerateHashForGlossaryEntry.java#L97)):*
> ```Java
>             ResultSet rs2 = null;
> 
>             try {
> ```

Should use try with resources

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateDataToHCredentials.java, line 55 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjpsIAJgP9797jRUnwr:-KjpsIAKv6QHlyJR0cVs:b-c7uz9q) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateDataToHCredentials.java#L55)):*
> ```Java
>             JdbcConnection conn = (JdbcConnection) database.getConnection();
>             ResultSet rset = null;
>             try (Statement stmt = conn.createStatement()) {
> ```

Should move rset to the try with resources block too.

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateHTermCommentToString.java, line 80 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjpsVvTHovlAXwk18eU:-KjpsVvTHovlAXwk18eV:b-m4qnnz) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateHTermCommentToString.java#L80)):*
> ```Java
>             ResultSet rs1 = null;
>             ResultSet rs2 = null;
>             try {
> ```

should use try with resources

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateRawDocumentsToFileSystem.java, line 136 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjps_fDgthVeQMqzoSk:-Kjps_fDgthVeQMqzoSl:b-m4qnnz) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateRawDocumentsToFileSystem.java#L136)):*
> ```Java
>     private void migrateAllRawContents() throws Exception {
>         ResultSet contentsResult = null;
>         try {
> ```

should use try with resources

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateRawDocumentsToFileSystem.java, line 161 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjpscYoIKV7XNXQdqvV:-KjpscYoIKV7XNXQdqvW:b-2guby3) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateRawDocumentsToFileSystem.java#L161)):*
> ```Java
>         idAndTypeStatement.setString(1, oldFileId);
>         ResultSet idAndTypeResult = null;
>         try {
> ```

same here

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/RebuildTMXPlainText.java, line 59 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjpsiRc9HnkA7ItmpW_:-KjpsiRdyFFyg0JjKZnJ:b-m4qnnz) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/RebuildTMXPlainText.java#L59)):*
> ```Java
>         ResultSet rsCount = null;
>         ResultSet rsUpdatable = null;
>         try {
> ```

should use try with resources

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/RequestServiceImpl.java, line 165 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjpuj8mrQc7AHqG8JWR:-Kjpuj8mrQc7AHqG8JWS:b-l327nv) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/service/impl/RequestServiceImpl.java#L165)):*
> ```Java
>                         .append(strategy.getSubject(msgs))
>                         .append("\' , message \'").append(message).append("\'");
>                 log.error(sb.toString(), e);
> ```

the toName part will not be logged after this change.

---

*[server/zanata-war/src/main/java/org/zanata/util/FileUtil.java, line 98 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjpvkK2diMfOaSK2_LM:-KjpvkK2diMfOaSK2_LN:b-m4qnnz) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/util/FileUtil.java#L98)):*
> ```Java
>         int bytesRead;
>         FileInputStream input = null;
>         try  {
> ```

should use try with resources

---

*[server/zanata-war/src/main/java/org/zanata/webtrans/server/TranslationUpdateListenerLazyLoader.java, line 42 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjpw3hjbjn4mERSBYDI:-Kjpw3hjbjn4mERSBYDJ:bamirll) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/webtrans/server/TranslationUpdateListenerLazyLoader.java#L42)):*
> ```Java
> 
>     public void init() {
>         synchronized (this) {
> ```

This means synchronization will happen all the time instead of only when delegate is null

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/303)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[server/zanata-war/src/main/java/org/zanata/action/RoleSearch.java, line 52 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjppccmUmtfk9xSGWUI:-KjqICvUfwUIgaYCVljM:b4dtnpk) ([raw file](https://github.com/zanata/zanata-platform/blob/9819a47f418d5767f17f49cac1bc0eaba07b0e0a/server/zanata-war/src/main/java/org/zanata/action/RoleSearch.java#L52)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Why is this removed?
</blockquote></details>

Its a non-null from identityManager.getRoleGroups

---

*[server/zanata-war/src/main/java/org/zanata/action/SortingType.java, line 47 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjppqw4bHuVfD6qMf-p:-KjqINlgrZ01Hw3nTmMT:b-n6a6h2) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/action/SortingType.java#L47)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Any reason for making this change?
</blockquote></details>

Findbugs was 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/303)*

**Comment by aeng** [comment]
Review status: 280 of 285 files reviewed at latest revision, 18 unresolved discussions, some commit checks broke.

---

*[server/zanata-war/src/main/java/org/zanata/action/SortingType.java, line 47 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjppqw4bHuVfD6qMf-p:-KjqJPLem0gyq1IOZqIQ:bjxw92k) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/action/SortingType.java#L47)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Findbugs was 
</blockquote></details>

Findbugs was complaining about mutating the enum which we shouldn't do. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/303)*

**Comment by aeng** [comment]
Review status: 280 of 285 files reviewed at latest revision, 18 unresolved discussions, some commit checks broke.

---

*[server/zanata-war/src/main/java/org/zanata/action/UserSearch.java, line 46 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjppwaDmon9bsULPGMM:-KjtMC-Z28_BA62Jai7D:b4vk5jf) ([raw file](https://github.com/zanata/zanata-platform/blob/9819a47f418d5767f17f49cac1bc0eaba07b0e0a/server/zanata-war/src/main/java/org/zanata/action/UserSearch.java#L46)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Why is this removed?
</blockquote></details>

identityManager.getGrantedRoles return non-null

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/303)*

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
Reviewed 2 of 19 files at r3.
Review status: 268 of 284 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java, line 468 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjtukpXRXIifFARR08a:-KjtukpXRXIifFARR08b:b-nwab4k) ([raw file](https://github.com/zanata/zanata-platform/blob/74e6c243df6038bf507e4ccd3ef876ea4baee7ec/server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java#L468)):*
> ```Java
>         // clear the browser's memory of the dswid
>         getExecutor().executeScript("window.name = \'\'");
>         if (dswidParamChecker != null) {
> ```

Instead of adding lots of null checks, this could be handled by refactoring to ensure that variable can never be null. (Perhaps by wrapping the WebDriver in a new object in createDriver().)

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/UserConfigHolder.java, line 42 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjpfPdUb-kqriAaAjip:-KjtvjgAIIw_3cvqp3ei:b-oyt29m) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/UserConfigHolder.java#L42)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Can you add transient to these fields to get rid of the warning? I think it will better to suppress them
</blockquote></details>

This seems like a bug in FindBugs. A static field shouldn't be serialised anyway, and `transient static` is basically meaningless.

---

*[server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetReviewComment.java, line 122 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjpjRJkvr-6KvPnKEa4:-KjtwR8qvUoyqG9DAcrn:bnoyh4s) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetReviewComment.java#L122)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

commenterName should not be part of equal and hashcode
</blockquote></details>

For DB entities, it's usually best to look at the constraints or DAO queries to work out what the natural key is, and implement equals/hashCode with the natural key fields.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/303)*

**Comment by seanf** [comment]
I think try with resources should always be used for ResultSets, rather than using null. (I think I accidentally "reviewed" a couple of files with these nulls.)

---

Reviewed 8 of 19 files at r3, 8 of 8 files at r4.
Review status: 283 of 286 files reviewed at latest revision, 24 unresolved discussions, some commit checks failed.

---

*[server/zanata-war/src/main/java/org/zanata/action/CopyTransOptionsModel.java, line 162 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjuIwFZF7ZhU5E9Nrf_:-KjuIwFZF7ZhU5E9Nrfa:b-ics341) ([raw file](https://github.com/zanata/zanata-platform/blob/bff8fc426f37e82d3dfaf9d3f70b2f972b70e863/server/zanata-war/src/main/java/org/zanata/action/CopyTransOptionsModel.java#L162)):*
> ```Java
>     public List<RuleAction> getRuleActions() {
>         Object value = this.ruleActions.get();
>         if (value == null) {
> ```

This looks like DCL. We should use java.util.concurrent.atomic.AtomicReference#compareAndSet or something.

---

*[server/zanata-war/src/main/java/org/zanata/action/ProjectHome.java, line 1308 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjuJ5XvwVfUb_2q-MQJ:-KjuJ5XvwVfUb_2q-MQK:b-bhswej) ([raw file](https://github.com/zanata/zanata-platform/blob/bff8fc426f37e82d3dfaf9d3f70b2f972b70e863/server/zanata-war/src/main/java/org/zanata/action/ProjectHome.java#L1308)):*
> ```Java
>         Object value = this.versions.get();
>         if (value == null) {
>             synchronized (this.versions) {
> ```

DCL. Should use java.util.concurrent.atomic.AtomicReference#compareAndSet or similar.

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java, line 52 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjps4GKXtz--vSGIewn:-KjuLzi6gerniqJ-2oQ9:b-ofm3bo) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java#L52)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Should use try with resources
</blockquote></details>

And for the ResultSets.

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/GenerateHashForGlossaryEntry.java, line 97 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjps97-2h0pdGxIEE-P:-KjuM5XWsx83m3u8uvmJ:b-u6gi42) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/GenerateHashForGlossaryEntry.java#L97)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Should use try with resources
</blockquote></details>

including ResultSets

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateHTermCommentToString.java, line 80 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjpsVvTHovlAXwk18eU:-KjuMCJEoGXdxUz9RNPQ:b4vn1fk) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateHTermCommentToString.java#L80)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

should use try with resources
</blockquote></details>

ditto for ResultSets

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateSeamTextToCommonMark.java, line 105 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjuJ_uCFhIWmgBb1Wgs:-KjuJ_uCFhIWmgBb1Wgt:b-qtjaui) ([raw file](https://github.com/zanata/zanata-platform/blob/bff8fc426f37e82d3dfaf9d3f70b2f972b70e863/server/zanata-war/src/main/java/org/zanata/liquibase/custom/MigrateSeamTextToCommonMark.java#L105)):*
> ```Java
>                 .createStatement(ResultSet.TYPE_FORWARD_ONLY,
>                         ResultSet.CONCUR_UPDATABLE)) {
>             ResultSet rs2 = null;
> ```

try with resources is better than using nulls

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/RebuildTMXPlainText.java, line 62 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjuK1attsL1SmHemm4L:-KjuK1attsL1SmHemm4M:b-n19ghc) ([raw file](https://github.com/zanata/zanata-platform/blob/bff8fc426f37e82d3dfaf9d3f70b2f972b70e863/server/zanata-war/src/main/java/org/zanata/liquibase/custom/RebuildTMXPlainText.java#L62)):*
> ```Java
>                         ResultSet.CONCUR_UPDATABLE)) {
>             ResultSet rsCount = null;
>             ResultSet rsUpdatable = null;
> ```

try with resources for ResultSets

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/ValidateAccountPasswords.java, line 86 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-KjuKA2Rw-2Vyxgma0Wq:-KjuKA2Rw-2Vyxgma0Wr:b-j5uydy) ([raw file](https://github.com/zanata/zanata-platform/blob/c91b82822774b379749709b57cc7d0d9d5f1c7b1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/ValidateAccountPasswords.java#L86)):*
> ```Java
>             try {
>                 if (rset != null) {
>                     rset.close();
> ```

Should use try with resources for the ResultSet too.

---

*[server/zanata-war/src/main/java/org/zanata/webtrans/server/TranslationUpdateListenerLazyLoader.java, line 42 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjpw3hjbjn4mERSBYDI:-KjuKNNb4kpL5bDZZ8SP:b671bzf) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/webtrans/server/TranslationUpdateListenerLazyLoader.java#L42)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

This means synchronization will happen all the time instead of only when delegate is null
</blockquote></details>

This looks like the broken Double Checked Locking idiom: https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java 

Sometimes you just have to synchronize the lot, or refactor into another solution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-:-KjuJyn7LdFqVJm5vCUS:b7hpbkm)*

**Comment by aeng** [comment]
Review status: 283 of 286 files reviewed at latest revision, 24 unresolved discussions, some commit checks failed.

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java, line 52 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjps4GKXtz--vSGIewn:-KjudXk6xJkDQQjLZY90:b-52b4fe) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java#L52)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

And for the ResultSets.
</blockquote></details>

For some reason, when I put resultSets in resources, hibernate complains about cannot execute closed resultSet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/303)*

**Comment by seanf** [comment]
Reviewed 1 of 4 files at r5.
Review status: 282 of 288 files reviewed at latest revision, 24 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java, line 52 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjps4GKXtz--vSGIewn:-KjunHKmsH3aft_PQmwC:b-6uxsof) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java#L52)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

For some reason, when I put resultSets in resources, hibernate complains about cannot execute closed resultSet.
</blockquote></details>

Can you give me an example? Preferably one which is covered by a unit test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/303)*

**Comment by seanf** [comment]
Review status: 282 of 288 files reviewed at latest revision, 25 unresolved discussions.

---

*[build-tools/src/main/resources/zanata-build-tools/findbugs-filter.xml, line 4 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjuo4gWt5q_GiSo6HRQ:-Kjuo4gWt5q_GiSo6HRR:b-lxvywb) ([raw file](https://github.com/zanata/zanata-platform/blob/438ce130ac999e3a86e00f9da726d7ca266746dd/build-tools/src/main/resources/zanata-build-tools/findbugs-filter.xml#L4)):*
> ```XML
>   <Match>
>     <Class name="~.*\.HelpMojo" />
>     <Source name="~.*\.kt"/>
> ```

Note that will be addressed by enabling Detekt for our Kotlin files: https://github.com/zanata/zanata-platform/pull/314 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/303)*

**Comment by aeng** [comment]
Review status: 282 of 288 files reviewed at latest revision, 25 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java, line 52 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-Kjps4GKXtz--vSGIewn:-KjuypR1J3PFoF8UycZt:b-w0lm0c) ([raw file](https://github.com/zanata/zanata-platform/blob/8a18374c4934e08b5b0c607c47d8a6ef80baddd1/server/zanata-war/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java#L52)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Can you give me an example? Preferably one which is covered by a unit test?
</blockquote></details>

Can only see the exception it during startup with empty database. e.g http://zanata-build.lab.eng.bne.redhat.com:8080/job/zanata-platform-pull-requests/1214/console

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/303)*

**Comment by huangp** [comment]
:lgtm: I will suggest a QA but it can be done as part of release testing I suppose

---

Reviewed 3 of 19 files at r3, 3 of 4 files at r5.
Review status: all files reviewed at latest revision, 25 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/303#-:-Kjv2G7vzD9ZgrYW6flW:b-u8rlpt)*

**Pull request merged**
