### PR TITLE
ZNTA-1835-zanataui-removal-editor

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1835

Remove zanata-UI components from editor
* Icon,
* Icons,
* LogoLoader,
* Row

Minor css styling fixes to editor
Remove references to zanata-ui from tests
Remove zanata-ui from build

## Testing Notes

This affects all icons in the alpha editor, as well as some layout panels. It requires a thorough check through all panels on that editor to ensure all icons are visible and displaying correctly, and that there are no new layout issues.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/298)

### CODE REVIEW

**Comment by davidmason** [comment]
Added DO NOT MERGE label as a reminder to wait until after the frontend file renames are merged before merging other frontend stories.

**Comment by davidmason** [comment]
Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 72 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBa4LxqhJenDeRo0lC:-KjBa4LxqhJenDeRo0lD:b-qdi1sv) ([raw file](https://github.com/zanata/zanata-platform/blob/94a8d8369fbed01662eab7c4039df59dcd4e781a/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L72)):*
> ```CSS
> .LogoLoader .LogoLoader-logo {
>   transform-origin: 50% 50% 0;
>   /*transform: scale(.8, .8);*/
> ```

Is this still needed?

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 302 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBaIYXTXrvvN3nhex3:-KjBaIYXTXrvvN3nhex4:b-x9e4g0) ([raw file](https://github.com/zanata/zanata-platform/blob/94a8d8369fbed01662eab7c4039df59dcd4e781a/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L302)):*
> ```CSS
> 
> .modal-title {
>   font-weight:300;
> ```

Why is there a mix of style: with and without space after colon:

```
opacity: 0.0;
font-weight:300;
```

It isn't a huge deal in the short term, but if we keep these little things consistent we're less likely to see extra edits and conflicts from just formatting changes (which slow down reviews and make it easier to miss errors).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by kathryngo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 72 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBa4LxqhJenDeRo0lC:-KjBhH5X2ZqTce2lJprr:bwhs7jb) ([raw file](https://github.com/zanata/zanata-platform/blob/94a8d8369fbed01662eab7c4039df59dcd4e781a/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L72)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Is this still needed?
</blockquote></details>

negative, will remove it

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 302 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBaIYXTXrvvN3nhex3:-KjBh2otYNXOpJNYEnLh:b-600chn) ([raw file](https://github.com/zanata/zanata-platform/blob/94a8d8369fbed01662eab7c4039df59dcd4e781a/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L302)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Why is there a mix of style: with and without space after colon:

```
opacity: 0.0;
font-weight:300;
```

It isn't a huge deal in the short term, but if we keep these little things consistent we're less likely to see extra edits and conflicts from just formatting changes (which slow down reviews and make it easier to miss errors).
</blockquote></details>

I will fix this so there are no spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 302 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBaIYXTXrvvN3nhex3:-KjBhZH7Rmcd4ryd9Kx-:b-af60z0) ([raw file](https://github.com/zanata/zanata-platform/blob/94a8d8369fbed01662eab7c4039df59dcd4e781a/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L302)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

I will fix this so there are no spaces
</blockquote></details>

I mean there ARE spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 302 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBaIYXTXrvvN3nhex3:-KjBi6aNx5UEd_TTOQEE:b1drx3q) ([raw file](https://github.com/zanata/zanata-platform/blob/94a8d8369fbed01662eab7c4039df59dcd4e781a/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L302)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

I mean there ARE spaces
</blockquote></details>

But why is it like that in the first place? Was code copied in from 2 different places?

I ask why because that info will let me know whether I should be asking for the copied-in code to have added comments to say where it came from (and it would not make sense to reformat it if it is just copied in).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by kathryngo** [comment]
Review status: 36 of 37 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 72 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBa4LxqhJenDeRo0lC:-KjBj2nljMwIYEDVY3p5:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/94a8d8369fbed01662eab7c4039df59dcd4e781a/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L72)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

negative, will remove it
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 302 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBaIYXTXrvvN3nhex3:-KjBiuwepUc36K4QMLXj:b-s64y54) ([raw file](https://github.com/zanata/zanata-platform/blob/94a8d8369fbed01662eab7c4039df59dcd4e781a/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L302)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

But why is it like that in the first place? Was code copied in from 2 different places?

I ask why because that info will let me know whether I should be asking for the copied-in code to have added comments to say where it came from (and it would not make sense to reformat it if it is just copied in).
</blockquote></details>

Done. And no idea, copied from a different place I guess (probably Inspector)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by davidmason** [comment]
Review status: 36 of 37 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 302 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBaIYXTXrvvN3nhex3:-KjBjC8yoPuNVHrNGwln:bkhh3bi) ([raw file](https://github.com/zanata/zanata-platform/blob/94a8d8369fbed01662eab7c4039df59dcd4e781a/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L302)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Done. And no idea, copied from a different place I guess (probably Inspector)
</blockquote></details>

Cool, as long as it isn't from e.g. a bootstrap file or something, where we would want a comment to remind us to delete it when we combine editor and frontend.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 302 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBaIYXTXrvvN3nhex3:-KjBkph8xvTqmNh56s4o:bt0xsf) ([raw file](https://github.com/zanata/zanata-platform/blob/94a8d8369fbed01662eab7c4039df59dcd4e781a/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L302)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Cool, as long as it isn't from e.g. a bootstrap file or something, where we would want a comment to remind us to delete it when we combine editor and frontend.
</blockquote></details>

Bootstrap uses spaces after : 
No issues

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-:-KjBsB4zjljQVmrnRriM:bnfp4nl)*

**Comment by davidmason** [comment]
I have removed the DO NOT MERGE label since the frontend restructure is complete. Note that all the __tests__ files have been moved into their component directories, and some components that were just a single file now have directories.

I tried to make the changes in a way that would allow rebase to work regardless of changes in the files, but it looks like there are some conflicts anyway.

**Comment by kathryngo** [comment]
@davidmason, shall look at the conflicts tomorrow morning when my brain has rebooted

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/app/editor/components/IconButton.js, line 27 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBx8bTelQgunplpOxC:-KjBx8bTelQgunplpOxD:bio9fd9) ([raw file](https://github.com/zanata/zanata-platform/blob/83a7cb1b115dde676c92aa871ae7db05da8a38d3/server/zanata-frontend/src/frontend/app/editor/components/IconButton.js#L27)):*
> ```JavaScript
>         title={this.props.title}>
>         <Icon
>           size={this.props.iconSize || '1'}
> ```

Oops, missed this before. The new code does not use the `iconSize` prop, so this can break things.

We need to either map the old icon sizes to an appropriate `className` here (I can help show you an efficient way to do this), or we need to update any place that uses `iconSize` to pass in the equivalent class name, or if none use it then we can remove the prop completely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/editor/components/IconButton.js, line 27 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBx8bTelQgunplpOxC:-KjC1zgCMNudKurNZ2VY:btg9ci5) ([raw file](https://github.com/zanata/zanata-platform/blob/83a7cb1b115dde676c92aa871ae7db05da8a38d3/server/zanata-frontend/src/frontend/app/editor/components/IconButton.js#L27)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Oops, missed this before. The new code does not use the `iconSize` prop, so this can break things.

We need to either map the old icon sizes to an appropriate `className` here (I can help show you an efficient way to do this), or we need to update any place that uses `iconSize` to pass in the equivalent class name, or if none use it then we can remove the prop completely.
</blockquote></details>

 would `className="s1"` suffice?

That's how Ive mapped the other icons from using size to className. Just stick an `s` in front of the number so it calls the right css class, unless the size is nX where X=1,2 or 3 - which caters for small icon sizes and would be `className="n1"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/editor/components/IconButton.js, line 27 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBx8bTelQgunplpOxC:-KjC2tuWCS1PK7iTdg3D:bvlhl7j) ([raw file](https://github.com/zanata/zanata-platform/blob/83a7cb1b115dde676c92aa871ae7db05da8a38d3/server/zanata-frontend/src/frontend/app/editor/components/IconButton.js#L27)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

 would `className="s1"` suffice?

That's how Ive mapped the other icons from using size to className. Just stick an `s` in front of the number so it calls the right css class, unless the size is nX where X=1,2 or 3 - which caters for small icon sizes and would be `className="n1"`
</blockquote></details>

Or will this still break things even if I change the test also?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/app/editor/components/IconButton.js, line 27 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBx8bTelQgunplpOxC:-KjC3JmlRpyvpcMnt-Iy:b-6sbkoh) ([raw file](https://github.com/zanata/zanata-platform/blob/83a7cb1b115dde676c92aa871ae7db05da8a38d3/server/zanata-frontend/src/frontend/app/editor/components/IconButton.js#L27)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Or will this still break things even if I change the test also?
</blockquote></details>

At the moment the code takes a prop in, which could be any valid size. The default was `1` which is correctly mapped to `s1`, but the code was only using that if there is no prop `iconSize` passed in. There is no single value you can use here to keep the same functionality, you have to make sure it will do the proper thing with that prop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/editor/components/IconButton.js, line 27 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBx8bTelQgunplpOxC:-KjC57MeoiW8W8fdWl6d:bp3nf21) ([raw file](https://github.com/zanata/zanata-platform/blob/83a7cb1b115dde676c92aa871ae7db05da8a38d3/server/zanata-frontend/src/frontend/app/editor/components/IconButton.js#L27)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

At the moment the code takes a prop in, which could be any valid size. The default was `1` which is correctly mapped to `s1`, but the code was only using that if there is no prop `iconSize` passed in. There is no single value you can use here to keep the same functionality, you have to make sure it will do the proper thing with that prop.
</blockquote></details>

Aha. Is it ok if we look at this tomorrow? Just want to make sure I approach this correctly. Thanks heaps for your help with this. I'm learning :grinning: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/app/editor/components/IconButton.js, line 27 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBx8bTelQgunplpOxC:-KjC5S69oIgz-3E01fnN:baabv02) ([raw file](https://github.com/zanata/zanata-platform/blob/83a7cb1b115dde676c92aa871ae7db05da8a38d3/server/zanata-frontend/src/frontend/app/editor/components/IconButton.js#L27)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Aha. Is it ok if we look at this tomorrow? Just want to make sure I approach this correctly. Thanks heaps for your help with this. I'm learning :grinning: 
</blockquote></details>

Yep, that was my intent. If it were urgent I would have used chat.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by davidmason** [comment]
Reviewed 20 of 35 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/IconButton/index.js, line 28 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjC72eNpB2T2yPawzAa:-KjC72eNpB2T2yPawzAb:bmls1zt) ([raw file](https://github.com/zanata/zanata-platform/blob/5665a562ad477bd99c36f72979f10b7782b0b73d/server/zanata-frontend/src/frontend/app/editor/components/IconButton/index.js#L28)):*
> ```JavaScript
>         <Icon
>           title={this.props.title}
>           className="s1"
> ```

This needs to react vary based on `props.iconSize` (discussion moved from old filename, so I will mark it as resolved there).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/IconButton.js, line 27 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-KjBx8bTelQgunplpOxC:-KjC7KrbFhdPtglJZcUL:b-ohsj11) ([raw file](https://github.com/zanata/zanata-platform/blob/83a7cb1b115dde676c92aa871ae7db05da8a38d3/server/zanata-frontend/src/frontend/app/editor/components/IconButton.js#L27)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Yep, that was my intent. If it were urgent I would have used chat.
</blockquote></details>

This file moved, so I am marking this resolved and we can continue discussion against the new filename.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by kathryngo** [comment]
There are still build errors with the tests. I will fix this right now. 
Example error:
`[ERROR] Cannot find module '../../app/components' from 'IconButton.test.js'`

**Comment by davidmason** [comment]
Reviewed 7 of 7 files at r4, 9 of 9 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by davidmason** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298)*

**Comment by davidmason** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-:-KjFvI-rkPoEjhNoBv45:bnfp4nl)*

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/298#-:-KjGYcNF9Im1eOB40fxO:bnfp4nl)*

**Comment by djansen-redhat** [comment]
✅ verified

**Pull request merged**
