### PR TITLE
fix(ZNTA-2329) update css loaders in webpack and minify all css 

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2329

Description: CSS problems in webpack - bugs with css-loader

https://github.com/webpack-contrib/css-loader/issues/295
https://github.com/webpack/webpack/issues/1754
https://github.com/webpack-contrib/css-loader/issues/163

I hhad to make css loaders less complicated so that no conflicts and errors were occuring in the frontend build while still passing. This was eventually resolved with the following approach:

* Added postcss add-ons to mitigate css problems
  Remove minified option from css-loader and instead use ccsnano minified through postcss)

* **Removed draft and prod options for css builds so that errors could be resolved**. a result of this is that both draft and prod builds have minified css. this is easy to deal with as the web inspector still shows which class applies to the element so it can be fixed in the original css/less files.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/657)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/package.json, line 116 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/657#-L2cnOqWFHVwP7D9qEIX:-L2cnOqWFHVwP7D9qEIY:b-57w9xv) ([raw file](https://github.com/zanata/zanata-platform/blob/56f759dce88b88cb34322c2f29faedd1f86f4640/server/zanata-frontend/src/frontend/package.json#L116)):*
> ```JSON
>     "postcss": "6.0.13",
>     "postcss-cssnext": "3.0.2",
>     "postcss-less-engine": "^0.6.2",
> ```

exact version?

---

*[server/zanata-frontend/src/frontend/webpack.config.js, line 169 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/657#-L2cngMvgWG7Y-rO4x8_:-L2cngMvgWG7Y-rO4x8a:b-6tlgb3) ([raw file](https://github.com/zanata/zanata-platform/blob/56f759dce88b88cb34322c2f29faedd1f86f4640/server/zanata-frontend/src/frontend/webpack.config.js#L169)):*
> ```JavaScript
>          * imports, variables, calculations, and non-prefixed codes.
>          * The draft and prod options were removed as they were causing
>          * errors with css-loader. In both cases, the css is minified.
> ```

does that mean we minimize the css in all environment now? not just PROD?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/657)*

**Comment by kathryngo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/package.json, line 116 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/657#-L2cnOqWFHVwP7D9qEIX:-L2cpEyeMXWfL-ySnFWM:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/56f759dce88b88cb34322c2f29faedd1f86f4640/server/zanata-frontend/src/frontend/package.json#L116)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

exact version?
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/frontend/webpack.config.js, line 169 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/657#-L2cngMvgWG7Y-rO4x8_:-L2cpBLcZiyacazRLXmG:b-qzt3vn) ([raw file](https://github.com/zanata/zanata-platform/blob/56f759dce88b88cb34322c2f29faedd1f86f4640/server/zanata-frontend/src/frontend/webpack.config.js#L169)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

does that mean we minimize the css in all environment now? not just PROD?
</blockquote></details>

yes, all. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/657)*

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/webpack.config.js, line 169 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/657#-L2cngMvgWG7Y-rO4x8_:-L2cpnIcM4hFI3SD3Ram:b-cmew6c) ([raw file](https://github.com/zanata/zanata-platform/blob/56f759dce88b88cb34322c2f29faedd1f86f4640/server/zanata-frontend/src/frontend/webpack.config.js#L169)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

yes, all. 
</blockquote></details>

what about dev mode? Minified css won't help in dev mode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/657)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/657#-:-L2cria_qe16e9fRcY8F:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/657)*

**Comment by kathryngo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/webpack.config.js, line 169 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/657#-L2cngMvgWG7Y-rO4x8_:-L2czYlJN4olZmeBWvmI:b-agdu02) ([raw file](https://github.com/zanata/zanata-platform/blob/56f759dce88b88cb34322c2f29faedd1f86f4640/server/zanata-frontend/src/frontend/webpack.config.js#L169)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

what about dev mode? Minified css won't help in dev mode.
</blockquote></details>

@aeng ^ blocking comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/657)*

**Comment by kathryngo** [comment]
Oh wow. For some reason when I merged in master and it brought in all the directory changes, this PR has picked them all up.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/657#-:-L36EYVugFcDb9tHKJYu:b62oth0)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 4 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/657#-:-L36HyZ3nlndAGr3nJsF:bnfp4nl)*

**Comment by huangp** [comment]
:lgtm: 

---

Reviewed 3 of 8 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/657#-:-L36NdQak-ei1e5uEye9:bg7igkv)*

**Pull request merged**
