### PR TITLE
Add more types

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by efloden** [comment]
Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/webpack.config.js, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/737#-L6PHlNYcxjhEydhjVy2:-L6PHlNYcxjhEydhjVy3:bcnhfne) ([raw file](https://github.com/zanata/zanata-platform/blob/5cc722e005a2de5f30e264b74612c0fd44d502bd/server/zanata-frontend/src/webpack.config.js#L25)):*
> ```JavaScript
> // We need this plugin to detect a `--watch` mode. It may be removed later
> // after https://github.com/webpack/webpack/issues/3460 will be resolved.
> const CheckerPlugin = require('awesome-typescript-loader').CheckerPlugin
> ```

Is this a preferred way to reference exports from a package? Or just necessary here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/737)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/webpack.config.js, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/737#-L6PHlNYcxjhEydhjVy2:-L6PN963qOuSammkF7_P:b-hjpu2n) ([raw file](https://github.com/zanata/zanata-platform/blob/5cc722e005a2de5f30e264b74612c0fd44d502bd/server/zanata-frontend/src/webpack.config.js#L25)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Is this a preferred way to reference exports from a package? Or just necessary here?
</blockquote></details>

Not normally preferred. This webpack config file is now being checked by TypeScript in my VS Code, and I found that the old way (destructuring) didn't preserve the type. If this were normal ES6/TypeScript code, I would use this:

    import { CheckerPlugin } from 'awesome-typescript-loader'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/737)*

**Comment by efloden** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/737#-:-L6PW3jUZNULB08C1AF0:bnfp4nl)*

**Comment by efloden** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/737)*

**Comment by efloden** [comment]
Reviewed 1 of 49 files at r1, 6 of 6 files at r3, 20 of 20 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/737)*

**Comment by efloden** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/737)*

**Pull request merged**
