### PR TITLE
fix(ZNTA-2554): remove ant design badge component

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2553

The Ant Design badge styles appeared to cause a bug which affected the layout of the TMX Export modal, removed this component to resolve the issue.
tmxexportnobadge

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by kathryngo** [comment]
@efloden  Afaik there is no badge for antd, just the tag component. Is that what you mean?

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/app/components/TMX/TMXExportModal.js, line 8 at r1](https://reviewable.io/reviews/zanata/zanata-platform/831#-LD0UuQYCJV_h4ftqU0X:-LD0UuQYCJV_h4ftqU0Y:b-mfr098) ([raw file](https://github.com/zanata/zanata-platform/blob/6b41f62b019491cfa9d23cb5f5d6af05376abb52/server/zanata-frontend/src/app/components/TMX/TMXExportModal.js#L8)):*
> ```JavaScript
> import {connect} from 'react-redux'
> import {Icon} from '../index'
> import Badge from 'antd/lib/badge'
> ```

There is no badge component. Maybe you mean Tag? https://ant.design/components/tag/

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/831)*

**Comment by spathare21** [comment]
@efloden If you see export modal from admin panel and from project version, close [X ] icon CSS/border looks different in a project version export modal box, see attached screen. it should be like admin -> export modal box. 

screenshot from 2018-05-21 16-00-04

**Comment by efloden** [comment]
@spathare21 Looks like different global styles on these pages interfered with the ant modal, wrote some overrides to ensure the close button has the correct style.
iterationpagetmxexport

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/831#-:-LD5O3Qa5IU_knkVe4ez:bnfp4nl)*

**Pull request merged**
