### PR TITLE
fix: fixed long file name wrapping in language panel of documents tab (ZNTA-1647)

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1647

Long file names in languages panel of documents tab do not appear on one line and file name overlays languages panel content. 

Issue:
longname-overflow

Fix:
longfilenamefix

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/141)

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 3706 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/141#-KaLDOKxe3CndyqWVITD:-KaLDOKxe3CndyqWVITE:b1hg340) ([raw file](https://github.com/zanata/zanata-platform/blob/a16a8dbf02f8b87f6cd774b933a71d8465c25d80/server/zanata-frontend/src/frontend/app/styles/style.less#L3706)):*
> ```Less
> }
> 
> #documents h2 span#document-label {
> ```

Can we have a common class which we can use for ellipsis display?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/141)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/styles/style.less, line 3706 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/141#-KaLDOKxe3CndyqWVITD:-KaLErawSA0C0QpGrYBa:b-6dpi7c) ([raw file](https://github.com/zanata/zanata-platform/blob/a16a8dbf02f8b87f6cd774b933a71d8465c25d80/server/zanata-frontend/src/frontend/app/styles/style.less#L3706)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Can we have a common class which we can use for ellipsis display?
</blockquote></details>

Yup. Onto it now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/141)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/styles/style.less, line 3706 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/141#-KaLDOKxe3CndyqWVITD:-KaLFb6kr8XO5YA9dpIY:bp0umx7) ([raw file](https://github.com/zanata/zanata-platform/blob/a16a8dbf02f8b87f6cd774b933a71d8465c25d80/server/zanata-frontend/src/frontend/app/styles/style.less#L3706)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Yup. Onto it now. 
</blockquote></details>

FYI this class will need to still exist as it specifies exactly how big the title container should be. This is needed for every element with the ellipsis tag. 
Long CSS classes such as the above will be needed throughout this design to cater for very specific styling settings on some elements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/141)*

**Comment by aeng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 3706 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/141#-KaLDOKxe3CndyqWVITD:-KaLHWvKtNGeAtdSh8Ac:b-q9qp0r) ([raw file](https://github.com/zanata/zanata-platform/blob/a16a8dbf02f8b87f6cd774b933a71d8465c25d80/server/zanata-frontend/src/frontend/app/styles/style.less#L3706)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

FYI this class will need to still exist as it specifies exactly how big the title container should be. This is needed for every element with the ellipsis tag. 
Long CSS classes such as the above will be needed throughout this design to cater for very specific styling settings on some elements.
</blockquote></details>

I would split it to 2 css, .ellipsis { ..all the css except max-width}, then keep this css class but extends the .ellipsis.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/141)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/styles/style.less, line 3706 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/141#-KaLDOKxe3CndyqWVITD:-KaLIY4BwuqhyfzIfHqg:bc6wg9i) ([raw file](https://github.com/zanata/zanata-platform/blob/a16a8dbf02f8b87f6cd774b933a71d8465c25d80/server/zanata-frontend/src/frontend/app/styles/style.less#L3706)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I would split it to 2 css, .ellipsis { ..all the css except max-width}, then keep this css class but extends the .ellipsis.
</blockquote></details>

:+1:  That's what I did. 

Ready for review again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/141)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/styles/style.less, line 3706 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/141#-KaLDOKxe3CndyqWVITD:-KaLIo0ejs4kfNBso_Iw:bn0qocn) ([raw file](https://github.com/zanata/zanata-platform/blob/a16a8dbf02f8b87f6cd774b933a71d8465c25d80/server/zanata-frontend/src/frontend/app/styles/style.less#L3706)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

:+1:  That's what I did. 

Ready for review again.
</blockquote></details>

Also, that specific element needs hypen styling added also, to override the hypen settings already there. This isn't needed on other elements which use ellipsis.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/141)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/styles/style.less, line 3706 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/141#-KaLDOKxe3CndyqWVITD:-KaLJ1pMZneQ9tjaCv-u:b-75uqix) ([raw file](https://github.com/zanata/zanata-platform/blob/a16a8dbf02f8b87f6cd774b933a71d8465c25d80/server/zanata-frontend/src/frontend/app/styles/style.less#L3706)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Also, that specific element needs hypen styling added also, to override the hypen settings already there. This isn't needed on other elements which use ellipsis.
</blockquote></details>

*hyphen

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/141)*

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/141)*

**Pull request merged**
