### PR TITLE
ZNTA-2173 hide private project

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-2173

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/547)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/services/src/main/java/org/zanata/action/ProjectHome.java, line 696 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-KvUY6eVZ8FiS86LiX_b:-KvUY6eVZ8FiS86LiX_c:b-6sljtp) ([raw file](https://github.com/zanata/zanata-platform/blob/d45c8bd09b6eca389654e7baa61adcb0c20fa646/server/services/src/main/java/org/zanata/action/ProjectHome.java#L696)):*
> ```Java
>             }
>         }
>         identity.checkPermission(getInstance(), "read");
> ```

I think creating an interceptor with annotation can centralize and simplify all these checks. See ```@CheckRole``` for example. Then you just need to put the annotation on every single JSF bean methods.

---

*[server/services/src/main/java/org/zanata/dao/ProjectDAO.java, line 88 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-KvUYqO9UP8rE324hP9e:-KvUYqO9UP8rE324hP9f:b-7iqcup) ([raw file](https://github.com/zanata/zanata-platform/blob/d45c8bd09b6eca389654e7baa61adcb0c20fa646/server/services/src/main/java/org/zanata/dao/ProjectDAO.java#L88)):*
> ```Java
>     public List<HProject> getOffsetList(int offset, int count,
>                     boolean filterOutActive, boolean filterOutReadOnly,
>                     boolean filterOutObsolete, @Nullable HPerson person) {
> ```

Instead of pass in the HPerson parameter, you could inject ```@Authenticated HAccount``` into Project DAO. Then use it in all the queries.

---

*[server/services/src/main/java/org/zanata/rest/service/ProjectsService.java, line 84 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-KvUZTGUOY9yMT1XvhgI:-KvUZTGUOY9yMT1XvhgJ:b-s1cidf) ([raw file](https://github.com/zanata/zanata-platform/blob/d45c8bd09b6eca389654e7baa61adcb0c20fa646/server/services/src/main/java/org/zanata/rest/service/ProjectsService.java#L84)):*
> ```Java
>                 projectDAO.getOffsetList(-1, -1, false, false, true,
>                         authenticatedAccount != null ?
>                                 authenticatedAccount.getPerson() : null);
> ```

Same as JSF beans, better use interceptor and annotation to centralize all security checks.

---

*[server/services/src/main/java/org/zanata/security/SecurityFunctions.java, line 182 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-KvUcHfOCRLxuhCdqFfN:-KvUcHfOCRLxuhCdqFfO:bczfgj1) ([raw file](https://github.com/zanata/zanata-platform/blob/d45c8bd09b6eca389654e7baa61adcb0c20fa646/server/services/src/main/java/org/zanata/security/SecurityFunctions.java#L182)):*
> ```Java
>     @GrantsPermission(actions = "read")
>     public boolean canReadProject(HProject target) {
>         if (isAdmin()) {
> ```

I think admin is covered by one of the methods at the top.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/547)*

**Comment by huangp** [comment]
-(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 3 of 7 files at r2, 15 of 15 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-:-KvVQcN0iJHnN_oNPDjp:b-1amvkm)*

**Comment by spathare21** [comment]
@aeng conflicts

**Comment by djansen-redhat** [comment]
*[server/services/src/main/java/org/zanata/rest/service/ETagUtils.java, line 57 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-KvdzdomE6RBPxdtRn7S:-KvdzdomE6RBPxdtRn7T:bt1up9v) ([raw file](https://github.com/zanata/zanata-platform/blob/489306141211558637b9b6d68a51ab16a93d74fa/server/services/src/main/java/org/zanata/rest/service/ETagUtils.java#L57)):*
> ```Java
>                 session.createQuery(
>                         "select i.versionNum from HProjectIteration i "
>                                 +
> ```

Weird formatting here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/547)*

**Comment by djansen-redhat** [comment]
@aeng where it says `if(person != null) {...` (eg. ProjectDAO) does this check the user is/not authenticated?

**Comment by aeng** [comment]
Review status: 25 of 29 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/services/src/main/java/org/zanata/rest/service/ETagUtils.java, line 57 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-KvdzdomE6RBPxdtRn7S:-Kve1ApLwVzGtdJ5_hcm:b-qssebl) ([raw file](https://github.com/zanata/zanata-platform/blob/489306141211558637b9b6d68a51ab16a93d74fa/server/services/src/main/java/org/zanata/rest/service/ETagUtils.java#L57)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Weird formatting here
</blockquote></details>

fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/547)*

**Comment by aeng** [comment]
> if(person != null) {... (eg. ProjectDAO) 
Mean there is an authenticated account.

**Comment by djansen-redhat** [comment]
*[server/services/src/main/java/org/zanata/security/SecurityFunctions.java, line 185 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-Kve1RQrifrcmBxhUfrd:-Kve1RQrifrcmBxhUfre:bmeiszw) ([raw file](https://github.com/zanata/zanata-platform/blob/489306141211558637b9b6d68a51ab16a93d74fa/server/services/src/main/java/org/zanata/security/SecurityFunctions.java#L185)):*
> ```Java
>             return true;
>         }
>         return isProjectMember(target);
> ```

Could be a one liner

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/547)*

**Comment by djansen-redhat** [comment]
*[server/services/src/main/java/org/zanata/security/SecurityFunctions.java, line 197 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-Kve1UnMKZuRGRvv4wCM:-Kve1UnMKZuRGRvv4wCN:bmeiszw) ([raw file](https://github.com/zanata/zanata-platform/blob/489306141211558637b9b6d68a51ab16a93d74fa/server/services/src/main/java/org/zanata/security/SecurityFunctions.java#L197)):*
> ```Java
>             return true;
>         }
>         return isProjectMember(target.getProject());
> ```

Could be a one liner

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/547)*

**Comment by djansen-redhat** [comment]
*[server/services/src/main/java/org/zanata/dao/ProjectDAO.java, line 150 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-Kve7j5dIipEkWJp6s1p:-Kve7j5eML7wx5Bu1gqV:buebsyk) ([raw file](https://github.com/zanata/zanata-platform/blob/489306141211558637b9b6d68a51ab16a93d74fa/server/services/src/main/java/org/zanata/dao/ProjectDAO.java#L150)):*
> ```Java
> 
>         if (person != null) {
>             condition
> ```

Weird formatting here - one character difference

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/547)*

**Comment by djansen-redhat** [comment]
Tester notes:
- [ ] Activity displays for translations changed
- [ ] Activity will show entries for projects that the viewing user is not a member of as `(private)`
- [ ] Not logged in user cannot access private projects, by search or url
- [ ] Logged in user can not see or access projects they are not a member of
- [ ] Logged in user can see and access see projects they are a member of
- [ ] Admin can access both private and non-private projects, versions
- [ ] If a user is a _non-maintainer member_ of a group, but not a member of a project/version, the existing project will show as `(private)`
- [ ] If a user is a _maintainer_ of a group, but not a member of a project/version, the existing project will show as name only. The maintainer can remove the project version.
- [ ] If a user is a _maintainer_ of a group, but not a member of a specific project/version, they cannot add that version to the group.
- [ ] If a user is a _maintainer_ of a group, and a member of a project/version, the existing project will show as name with link, and can be removed.

**Comment by djansen-redhat** [comment]
@aeng this change also seems to not meet unit test requirements

**Comment by spathare21** [comment]
Hi @aeng 

Tested this PR and observed following points.

1. Translator not able to view private project in project page he needs to search on explore page.

screenshot from 2017-10-05 12-18-37

screenshot from 2017-10-05 12-02-42


2. Is it prosible that Admin can see the translation changes done by maintainer and tranlator in project on Activity tab ?

3. Not logged in user is able to access/view project by url.

screenshot from 2017-10-05 12-36-08


4. Not logged in user and logged in user who is not a member of private project, is able to see private project via Explore search and got 'record not found but you can help us fix it' error is this valid/expectd error.

@djansen-redhat  not able to get your last 3 points from above comment little bit confusing for me.

**Comment by aeng** [comment]
> Translator not able to view private project in project page he needs to search on explore page.

Explore page should not return the private project if the users are not part of the project members. Fixed in new commit.

> Is it prosible that Admin can see the translation changes done by maintainer and tranlator in project on Activity tab ?

Yes. Only user that has access to the private project, eg. admin or members of the project can see the name and the link to the project. Users without permission can see the activity entry and the project name, but not the link.

> Not logged in user is able to access/view project by url.

They should not be able to see the project by url. Should be returning "record not found" page.

> not logged in user and logged in user who is not a member of private project, is able to see private project via Explore search and got 'record not found but you can help us fix it' error is this valid/expectd error.

Fixed in new commit.

**Comment by huangp** [comment]
Reviewed 3 of 4 files at r4, 5 of 5 files at r5, 13 of 13 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/547)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/dao/ProjectDAO.java, line 150 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-Kve7j5dIipEkWJp6s1p:-KvzOLcbzkCjyKJyJd9C:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/489306141211558637b9b6d68a51ab16a93d74fa/server/services/src/main/java/org/zanata/dao/ProjectDAO.java#L150)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Weird formatting here - one character difference
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/security/SecurityFunctions.java, line 185 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-Kve1RQrifrcmBxhUfrd:-KvzOMS0AXcsucf2thmx:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/489306141211558637b9b6d68a51ab16a93d74fa/server/services/src/main/java/org/zanata/security/SecurityFunctions.java#L185)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Could be a one liner
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/security/SecurityFunctions.java, line 197 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/547#-Kve1UnMKZuRGRvv4wCM:-KvzOMyW5d77ViBZCLUx:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/489306141211558637b9b6d68a51ab16a93d74fa/server/services/src/main/java/org/zanata/security/SecurityFunctions.java#L197)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Could be a one liner
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/547)*

**Comment by spathare21** [comment]
1. "No error" message shown if we hit private project URL. I think it should project not found or you don't have an access to the project your searching for.

2. If we have a URL/link of private project version, the Private project is accessible to not logged in user and other members who don't have access to the project. 

e.g http://localhost:8180/iteration/view/541/master?dswid=-4256

3. Translator is not able to access the private project through Dashboard- > project. 

4. If Translator search for private project on explore page project not listed

**Comment by aeng** [comment]
> "No error" message shown if we hit private project URL. I think it should project not found or you don't have an access to the project your searching for

It is an existing issue with the non-existing project. We should fix this in separate PR.

> If we have a URL/link of private project version, the Private project is accessible to not logged in user and other members who don't have access to the project. e.g http://localhost:8180/iteration/view/541/master?dswid=-4256

fixed.

> Translator is not able to access the private project through Dashboard- > project.

fixed.

> If Translator search for private project on explore page project not listed

fixed.

**Comment by spathare21** [comment]
@aeng have you pushed the changes, I did not see any new commit or changes on PR

**Comment by spathare21** [comment]
Verified looks good to me

**Pull request merged**
