### PR TITLE
fix(ZNTA-1993): Fix the role manager validation

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1993

Prevent empty role name or greater than 255 characters
Prevent role name changes
Prevent overwriting an existing role
Remove users from role before deleting it
Add test

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 52 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7eh7RCrZn8FyjljiG:-LC7eh7RCrZn8FyjljiH:b-3zcgq2) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L52)):*
> ```Java
>         if (StringUtils.isBlank(role)) {
>             // creating new role
>             groups = new ArrayList<>();
> ```

    // to be explicit
    this.originalRole = null

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 57 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7eYph-apmyuvynAA-:-LC7eYph-apmyuvynAA0:b-rhd3zr) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L57)):*
> ```Java
>             groups = identityManager.getRoleGroups(role);
>         }
>     }
> ```

    private boolean isNewRole() { return originalRole == null }

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 72 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7epj757rooEn0aFqZ:-LC7bLFjDhQn3mfdUWrz:b-trrk5) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L72)):*
> ```Java
>             return false;
>         }
>         if (!StringUtils.isBlank(originalRole) && !roleName.equals(originalRole)) {
> ```

    if (!isNewRole() & !roleName.equals(originalRole)) {

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 81 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7fDca7Jds36QsFVC5:-LC7fDca7Jds36QsFVC6:bmwlgrd) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L81)):*
> ```Java
> 
>     public String save() {
>         boolean roleExists = role != null && identityManager.roleExists(role);
> ```

Don't think we need this

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 97 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7fGEb5D4Abo5SRVP7:-LC7fGEb5D4Abo5SRVP8:b-cdc8d9) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L97)):*
> ```Java
>         }
> 
>         if (roleExists && !role.equals(originalRole)) {
> ```

or this (see below)

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 106 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7ezvBDnM4em8wGBcu:-LC7dZln6lKGNsg9bj65:b-ze52et) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L106)):*
> ```Java
>         }
> 
>         if (roleExists) {
> ```

    if (!isNewRole) {
        if (!role.equals(originalRole)) you may not rename roles

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 69 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7ZIBuErTgBiYmngux:-LC7ZIBuErTgBiYmnguy:b-m5u440) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L69)):*
> ```Java
> 
>     @Test
>     public void saveFailWhenEmptyID() {
> ```

whenBlankID

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 79 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7ZMwz9Ujp45KG5tNn:-LC7ZMwz9Ujp45KG5tNo:bp23ts) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L79)):*
> ```Java
> 
>     @Test
>     public void saveFailWhenRoleExists() {
> ```

cantCreateRoleWithDuplicate(Role)Name

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 88 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7_sqL3XmEKZzgnys4:-LC7_sqL3XmEKZzgnys5:bv35xmv) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L88)):*
> ```Java
> 
>     @Test
>     public void validateRoleName() {
> ```

duplicateRoleNameFailsValidation

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 101 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7_jMc4ovePK3sVevt:-LC7_jMc4ovePK3sVevu:b-9apqno) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L101)):*
> ```Java
> 
>     @Test
>     public void validateRoleNameLength() {
> ```

longRoleNameFailsValidation

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 110 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7aDCX1Emb7Iqmo98J:-LC7aDCX1Emb7Iqmo98K:bfp8rb) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L110)):*
> ```Java
> 
>     @Test
>     public void rejectUpdatedRoleName() {
> ```

modifiedRoleNameFailsValidation

    // because we disallow role renaming

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/814)*

**Comment by djansen-redhat** [comment]
Review status: 2 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 52 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7eh7RCrZn8FyjljiG:-LC7gbne54qYGbYuPX1Q:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L52)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

    // to be explicit
    this.originalRole = null
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 57 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7eYph-apmyuvynAA-:-LC7gicO73JQlxqexR4B:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L57)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

    private boolean isNewRole() { return originalRole == null }
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 72 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7epj757rooEn0aFqZ:-LC7gv8lAsogfWJuHzRe:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L72)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

    if (!isNewRole() & !roleName.equals(originalRole)) {
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 81 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7fDca7Jds36QsFVC5:-LC7hb_E2Ul3Smk2mc2p:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L81)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Don't think we need this
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 97 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7fGEb5D4Abo5SRVP7:-LC7i0s92-kmoVGtBLX2:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L97)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

or this (see below)
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 106 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7ezvBDnM4em8wGBcu:-LC7krvW5R1-LsdsQmej:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/main/java/org/zanata/action/RoleAction.java#L106)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

    if (!isNewRole) {
        if (!role.equals(originalRole)) you may not rename roles
</blockquote></details>

Done.

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 69 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7ZIBuErTgBiYmngux:-LC7kzLl2hshuzUrW_sB:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L69)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

whenBlankID
</blockquote></details>

Done.

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 79 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7ZMwz9Ujp45KG5tNn:-LC7l3Xp6nqVjX8PDswF:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L79)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

cantCreateRoleWithDuplicate(Role)Name
</blockquote></details>

Done.

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 88 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7_sqL3XmEKZzgnys4:-LC7lGYd3lmXRyc05fjh:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L88)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

duplicateRoleNameFailsValidation
</blockquote></details>

Done.

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 101 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7_jMc4ovePK3sVevt:-LC7lEP-1KERWtv019Qy:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L101)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

longRoleNameFailsValidation
</blockquote></details>

Done.

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 110 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7aDCX1Emb7Iqmo98J:-LC7lE-n32u4xmA3B2uT:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L110)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

modifiedRoleNameFailsValidation

    // because we disallow role renaming
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/814)*

**Comment by seanf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/services/src/main/java/org/zanata/action/RoleAction.java, line 37 at r2](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7qNG_CFOF97ofUjFV:-LC7qNG_CFOF97ofUjFW:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-platform/blob/211786915a2009a0e5d7279cee2da04ee4af457e/server/services/src/main/java/org/zanata/action/RoleAction.java#L37)):*
> ```Java
>     private static final long serialVersionUID = -3830647911484729768L;
>     private String originalRoleName;
>     private String roleName;
> ```

:+1: 

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 110 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7aDCX1Emb7Iqmo98J:-LC7rgScCTNmSIlEbEw8:b806fkz) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L110)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could you add that comment too, please?

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/814)*

**Comment by djansen-redhat** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/test/java/org/zanata/action/RoleActionTest.java, line 110 at r1](https://reviewable.io/reviews/zanata/zanata-platform/814#-LC7aDCX1Emb7Iqmo98J:-LC84wXkEzyJuxsjKIpo:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/425a0b588760ca8178132eee3603e014ba356d57/server/services/src/test/java/org/zanata/action/RoleActionTest.java#L110)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Could you add that comment too, please?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/814)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/814#-:-LCBWwjJ2JWBzpo5YWIH:bnfp4nl)*

**Comment by djansen-redhat** [comment]
@seanf I angered the FindBugs Gods. Is 'static' really necessary for a private final "variable"?

**Comment by seanf** [comment]
> I angered the FindBugs Gods. Is 'static' really necessary for a private final "variable"?

It's not "necessary" but it is a waste of memory (and a little confusing) to make it an instance variable if it holds the same value in all instances of the class. 

Plus ALL_CAPS is a misleading name for an instance variable.

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/814#-:-LCRYB7fBSxN0EQ86UTx:bnfp4nl)*

**Comment by spathare21** [comment]
@djansen-redhat We can delete role before removing user from role.

**Comment by djansen-redhat** [comment]
@spathare21 previously not, there would be a constraint exception. I handle this in code now, removing all users from the role and then deleting the role (assuming I haven't messed it up?)

**Comment by spathare21** [comment]
ohh ok got it @djansen-redhat once I delete the role, it removed all user from the role and that user gets user role.

**Pull request merged**
