### PR TITLE
Znta 1732 editorsidebar

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1732

Adds a sidebar to the editor, with details about the selected text flow.

details-pane

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/211)

### CODE REVIEW

**Comment by kathryngo** [comment]
I have added the 'X' icon to close the sidebar but have had difficulty implementing it (have added the 'X' button to SidebarContent, unsure how to get it to close the entire sidebar. 
@davidmason, would you mind having a look when you have the chance? I tried the referring to the example on the react-sidebar repo, but had no luck. Thank you.
Apart from that, it's good to go.w

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/211#-:-Ke0xfyqQ3kuhqt5V4F1:b-oomp97)*

**Comment by aeng** [comment]
Reviewed 2 of 82 files at r1, 8 of 90 files at r2, 5 of 6 files at r6, 3 of 3 files at r7.
Review status: 18 of 20 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/editor/package.json, line 94 at r7](https://reviewable.io:443/reviews/zanata/zanata-platform/211#-Ke7PZ4TH9sHXh_Sl1Vp:-Ke7PZ4TH9sHXh_Sl1Vq:b-vjgxkl) ([raw file](https://github.com/zanata/zanata-platform/blob/ffa09d6d1e8ff36896b3c42e6ebe1c67ba9cc0f5/server/zanata-frontend/src/editor/package.json#L94)):*
> ```JSON
>     "combokeys": "2.4.6",
>     "normalize.css": "3.0.1",
>     "react-sidebar": "^2.3.0",
> ```

might want to change this to exact version (removing ^), and update yarn.

---

*[server/zanata-frontend/src/editor/app/containers/SidebarContent.js, line 10 at r7](https://reviewable.io:443/reviews/zanata/zanata-platform/211#-Ke7Pxbf_6wGHriJahuu:-Ke7Pxbf_6wGHriJahuv:bpmnpld) ([raw file](https://github.com/zanata/zanata-platform/blob/ffa09d6d1e8ff36896b3c42e6ebe1c67ba9cc0f5/server/zanata-frontend/src/editor/app/containers/SidebarContent.js#L10)):*
> ```JavaScript
> import { FormattedDate, FormattedTime } from 'react-intl'
> 
> // const activityTitle = 'Activity'
> ```

I assume these will be used in the future?

---

*[server/zanata-frontend/src/editor/app/containers/SidebarContent.js, line 117 at r7](https://reviewable.io:443/reviews/zanata/zanata-platform/211#-Ke7QAmGJEEdIjCq3tMU:-Ke7QAmGJEEdIjCq3tMV:bkqwmid) ([raw file](https://github.com/zanata/zanata-platform/blob/ffa09d6d1e8ff36896b3c42e6ebe1c67ba9cc0f5/server/zanata-frontend/src/editor/app/containers/SidebarContent.js#L117)):*
> ```JavaScript
>         <div className="sidebar-wrapper">
>           {this.sidebarDetails()}
>           {/* this.phraseLink() */}
> ```

Remove if not required anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/211)*

**Comment by kathryngo** [comment]
Review status: 18 of 20 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/editor/package.json, line 94 at r7](https://reviewable.io:443/reviews/zanata/zanata-platform/211#-Ke7PZ4TH9sHXh_Sl1Vp:-Ke7_7bZuWg6amKGwwtW:b-d7bhn0) ([raw file](https://github.com/zanata/zanata-platform/blob/ffa09d6d1e8ff36896b3c42e6ebe1c67ba9cc0f5/server/zanata-frontend/src/editor/package.json#L94)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

might want to change this to exact version (removing ^), and update yarn.
</blockquote></details>

will do

---

*[server/zanata-frontend/src/editor/app/containers/SidebarContent.js, line 10 at r7](https://reviewable.io:443/reviews/zanata/zanata-platform/211#-Ke7Pxbf_6wGHriJahuu:-Ke7_GSnRxhebdkkc72E:bhwxqsw) ([raw file](https://github.com/zanata/zanata-platform/blob/ffa09d6d1e8ff36896b3c42e6ebe1c67ba9cc0f5/server/zanata-frontend/src/editor/app/containers/SidebarContent.js#L10)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I assume these will be used in the future?
</blockquote></details>

Needed for the glossary and activity tabs

---

*[server/zanata-frontend/src/editor/app/containers/SidebarContent.js, line 117 at r7](https://reviewable.io:443/reviews/zanata/zanata-platform/211#-Ke7QAmGJEEdIjCq3tMU:-Ke7_Lsxn9k8tCd5Py8t:bebrt1w) ([raw file](https://github.com/zanata/zanata-platform/blob/ffa09d6d1e8ff36896b3c42e6ebe1c67ba9cc0f5/server/zanata-frontend/src/editor/app/containers/SidebarContent.js#L117)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Remove if not required anymore.
</blockquote></details>

Will do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/211)*

**Comment by kathryngo** [comment]
@aeng, changes made based on your comments in PR. Ready for another look.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/211#-:-KeAk0guVm37P5WDu9Qe:bnfp4nl)*

**Comment by djansen-redhat** [comment]
✅ verified

**Pull request merged**
