### PR TITLE
fix(ZNTA-2100): Gettext "Language" header field inconsistent format

### PR DESCRIPTION
**Pull request by KieCap**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2100

Language field locale in gettext file headers should always be underscore-separated.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/499)

### CODE REVIEW

**Comment by KieCap** [comment]
@seanf what's the status with this? Is there something I need to do?

**Comment by aeng** [comment]
@KieCap You might want to rebase with our master branch before we can rebuild this PR again.

**Comment by KieCap** [comment]
Current master merged and edits now allowed. Thanks.

**Comment by djansen-redhat** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/499)*

**Comment by djansen-redhat** [comment]
@aeng @seanf added my review, looks fine.

**Comment by seanf** [comment]
@KieCap on second thought, we don't really need to add anything to the release notes except a link to the fixed bug (which will be done by a script during release). 

But I've changed the pull request to target `release` branch so that we can get the fix into 4.3.x (perhaps not for 4.3.0, probably 4.3.1) instead of waiting for 4.4.0. Sorry about the huge delay!

**Comment by KieCap** [comment]
No problem at all, @seanf. Thanks!

**Comment by spathare21** [comment]
I am unable to reproduce issue to verify this PR @djansen-redhat are you ?

**Comment by seanf** [comment]
Thanks for the pull request @KieCap!

**Pull request merged**
