### PR TITLE
Move entry points, require all source files as test

### PR DESCRIPTION
**Pull request by seanf**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/678)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: +Reviewed 

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/678#-:-L3QGm2Ok6JgnVylW-12:biv5e4t)*

**Comment by seanf** [comment]
@aeng Could I get you to review the last commit? And have you ever hot-loaded reducer functions in this module?

**Comment by aeng** [comment]
Reviewed 4 of 11 files at r1, 5 of 7 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/package.json, line 131 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/678#-L5ImZDlw_SC-CqrajE4:-L5ImZDmVWtXgon7AmIx:bb6wunm) ([raw file](https://github.com/zanata/zanata-platform/blob/3b5fbbadf0afd629beb6fe72861411a0786b0c01/server/zanata-frontend/src/package.json#L131)):*
> ```JSON
>     "react-test-renderer": "15.6.1",
>     "react-transform-hmr": "1.0.4",
>     "require.all": "^2.0.3",
> ```

should use exact version. 'Yarn add require.all@2.0.3'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/678)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 11 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/678#-:-L5QvFAhFr494I91BFZs:bnfp4nl)*

**Comment by seanf** [comment]
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/package.json, line 131 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/678#-L5ImZDlw_SC-CqrajE4:-L5R7PqzVSf4irJvo4tv:bixes50) ([raw file](https://github.com/zanata/zanata-platform/blob/3b5fbbadf0afd629beb6fe72861411a0786b0c01/server/zanata-frontend/src/package.json#L131)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

should use exact version. 'Yarn add require.all@2.0.3'
</blockquote></details>

For the record, we discussed this and decided that there's no need to lock the exact version in `package.json` when we're using `yarn.lock`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/678)*

**Pull request merged**
