### PR TITLE
refactor(ZNTA-181): split up gwt-editor and zanata-war

### PR DESCRIPTION
**Pull request by seanf**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-181

Split up gwt-editor and zanata-war.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/425)

### CODE REVIEW

**Comment by seanf** [comment]
@aeng 
Note that overall test coverage has gone down by 0.46%, because JaCoCo only counts coverage from unit tests which are in the same Maven module as the code under test, some of our GWT "shared" code is only covered by tests in gwt-editor and some GWT code is only covered by NavigationServiceIntegrationTest in zanata-war.

**Comment by aeng** [comment]
Reviewed 221 of 2834 files at r1.
Review status: 132 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/pom.xml, line 2504 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-Kpqgs2wuJHgRYvZ6PpU:-Kpqgs2wuJHgRYvZ6PpV:b-b25qmq) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/pom.xml#L2504)):*
> ```XML
>     <module>gwt-editor</module>
>     <module>security-common</module>
>     <module>services</module>
> ```

should we follow the naming we had for the rest of the modules? zanata-services?

---

*[server/functional-test/pom.xml, line 147 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-Kpqh2W0ZDraDeM_ZDui:-Kpqh2W0ZDraDeM_ZDuj:bjvbrkw) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/functional-test/pom.xml#L147)):*
> ```XML
>     <dependency>
>       <groupId>org.zanata</groupId>
>       <artifactId>services</artifactId>
> ```

zanata-services?

---

*[server/gwt-editor/pom.xml, line 198 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KpqhA_IS9VSC9Wu7Vk4:-KpqhA_IS9VSC9Wu7Vk5:b-yuyd2j) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/gwt-editor/pom.xml#L198)):*
> ```XML
>     </dependency>
>     <dependency>
>       <groupId>org.hamcrest</groupId>
> ```

We should try to migrate to assertJ, but can be separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 261 of 2834 files at r1, 1 of 2 files at r2.
Review status: 265 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 2 of 2834 files at r1.
Review status: 266 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 26 of 2834 files at r1.
Review status: 279 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 50 of 2834 files at r1.
Review status: 304 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 118 of 2834 files at r1.
Review status: 363 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 124 of 2834 files at r1.
Review status: 425 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 110 of 2834 files at r1.
Review status: 480 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 12 of 2834 files at r1.
Review status: 486 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 72 of 2834 files at r1.
Review status: 522 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 202 of 2834 files at r1.
Review status: 623 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 2 of 2834 files at r1.
Review status: 624 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 186 of 2834 files at r1.
Review status: 717 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 108 of 2834 files at r1.
Review status: 771 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 112 of 2834 files at r1.
Review status: 827 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 220 of 2834 files at r1.
Review status: 937 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 131 of 2834 files at r1.
Review status: 1019 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 187 of 2834 files at r1.
Review status: 1129 of 1517 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 290 of 2834 files at r1.
Review status: 1274 of 1517 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/services/src/test/java/org/zanata/adapter/DTDAdapterTest.java, line 54 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KprhOkwYHMS2dFrwl6B:-KprhOkwYHMS2dFrwl6C:byrjxga) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/services/src/test/java/org/zanata/adapter/DTDAdapterTest.java#L54)):*
> ```Java
>     @Test
>     public void testTranslatedDTDDocument() throws Exception {
>         File testFile = getTestFile("basicdtd.dtd");
> ```

No need to check the file exists anymore?

---

*[server/services/src/test/java/org/zanata/cdi/WithActiveWindowInterceptor.java, line 34 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KprhaWEm-MtjWm2O3nD:-KprhaWFQM0ciDuGLA39:b-lamaqf) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/services/src/test/java/org/zanata/cdi/WithActiveWindowInterceptor.java#L34)):*
> ```Java
> @Interceptor
> @WithActiveWindow
> //@Priority(Interceptor.Priority.LIBRARY_BEFORE + 3)
> ```

Remove if not used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by aeng** [comment]
Reviewed 391 of 2834 files at r1.
Review status: 1511 of 1517 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[server/services/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt, line 58 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-Kprim84VdUR79_n9REh:-Kprim84VdUR79_n9REi:bp41j75) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/services/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt#L58)):*
> ```Kotlin
> @RunWith(CdiUnitRunner::class)
> @AdditionalClasses(WithActiveWindowInterceptor::class)
> //@AdditionalClasses(WithActiveWindowInterceptor::class, WithRequestScopeInterceptor::class)
> ```

Remove if not needed?

---

*[server/services/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt, line 60 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KprioAmr1MEASQWMWh9:-KprioAnGQn4cb4WImDH:b-2ux2hl) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/services/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt#L60)):*
> ```Kotlin
> //@AdditionalClasses(WithActiveWindowInterceptor::class, WithRequestScopeInterceptor::class)
> @InRequestScope
> //@WithRequestScope
> ```

Remove if not needed?x

---

*[server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java, line 88 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KprlEQd6X3GCzTQCBB-:-KprlEQd6X3GCzTQCBB0:b-lgxe99) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java#L88)):*
> ```Java
>         printArchiveContents(archive);
> 
>         // Export to .war (to actually see what is being deployed)
> ```

Should clean this block of comment?

---

*[server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java, line 105 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KprlIRmj-QOm58ZrDbz:-KprlIRmj-QOm58ZrDc-:b-qaqs3p) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java#L105)):*
> ```Java
>         System.out.println("Deployment contents:");
>         paths.forEach(it -> System.out.println("  " + it.get()));
> //        System.out.println("beans.xml: ");
> ```

Should clean this block of comment?n

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by seanf** [comment]
Review status: 1511 of 1517 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[server/pom.xml, line 2504 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-Kpqgs2wuJHgRYvZ6PpU:-KqQphtScTZeL9GA3EWU:b-i6pfh4) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/pom.xml#L2504)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

should we follow the naming we had for the rest of the modules? zanata-services?
</blockquote></details>

You mean, other than functional-test, gwt-editor, and security-common? I think we've been moving towards keeping the "zanata-" prefix out of the artifact names when creating new modules. Putting "zanata-" there doesn't really add any information.

---

*[server/gwt-editor/pom.xml, line 198 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KpqhA_IS9VSC9Wu7Vk4:-KqQqc790jsSxp28F7we:b-alw65l) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/gwt-editor/pom.xml#L198)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

We should try to migrate to assertJ, but can be separate PR.
</blockquote></details>

Yes, I'm trying to avoid unnecessary code changes at the same time. But now I'm afraid https://github.com/zanata/zanata-platform/pull/452 has caused conflicts for this PR. Then again, it might be be different files.

---

*[server/services/src/test/java/org/zanata/adapter/DTDAdapterTest.java, line 54 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KprhOkwYHMS2dFrwl6B:-KqQquIaIrpK9Fwia6b7:ba7tl6d) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/services/src/test/java/org/zanata/adapter/DTDAdapterTest.java#L54)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

No need to check the file exists anymore?
</blockquote></details>

That's AbstractAdapterTest.parseTestFile's job now, so you get the better error message in *all* the adapter tests.

---

*[server/services/src/test/java/org/zanata/cdi/WithActiveWindowInterceptor.java, line 34 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KprhaWEm-MtjWm2O3nD:-KqQrDGd5k8ZOcs0QmJe:b-8e3ak4) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/services/src/test/java/org/zanata/cdi/WithActiveWindowInterceptor.java#L34)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Remove if not used?
</blockquote></details>

I'm hoping to add it back in later. Interceptor Priority is a CDI 1.1? feature which should be more future-proof than listing interceptors in beans.xml, but I turned out not to need it yet.

---

*[server/services/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt, line 58 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-Kprim84VdUR79_n9REh:-KqQs6RmlEoltRYvdhCV:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/services/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt#L58)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Remove if not needed?
</blockquote></details>

Done.

---

*[server/services/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt, line 60 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KprioAmr1MEASQWMWh9:-KqQs7C-tetNLPUNMPT0:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/services/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt#L60)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Remove if not needed?x
</blockquote></details>

Done.

---

*[server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java, line 88 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KprlEQd6X3GCzTQCBB-:-KqQsLM-cGZC3AKJl4bj:b-qrwoy9) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java#L88)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should clean this block of comment?
</blockquote></details>

Sometimes it's enough to see the list of filenames, other times you want the war or the exploded war. I could implement an option parser, but I think it's simpler to uncomment the bit you need at the time you're debugging this problem.

I'll improve the comments though.

---

*[server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java, line 105 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-KprlIRmj-QOm58ZrDbz:-KqQtjtgaaiQcaNfzYKj:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/9454d444089d3671f40783fb9fab6c2a6dd9789a/server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java#L105)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should clean this block of comment?n
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425)*

**Comment by seanf** [comment]
@aeng I've pushed some changes to the comments (which I should have done before publishing my replies in Reviewable), but I'm still working on the merge conflicts.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 175 of 2834 files at r1, 2 of 2 files at r3, 180 of 183 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/425#-:-KqfKYFlFUgmRb_JxaE_:bnfp4nl)*

**Comment by aeng** [comment]
@seanf no-QA as long as jenkins build is green.

**Comment by djansen-redhat** [comment]
Build 31 is green (32 seems accidental+aborted?)
+1 for no QA due to refactoring and full FT run.

**Comment by seanf** [comment]
Thanks for the review @aeng !

**Pull request merged**
