### PR TITLE
Add advanced search component to editor (ZNTA-975)

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-975

Adds the advanced search box at the top of the editor.

*Please get me on the line to give an overview of the new architecture - it will make the review much easier. This includes some restructuring of the editor to allow it to work with phrase lists that are filtered or unfiltered, as well as a few improvements in the involved code.*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/443)

### CODE REVIEW

**Comment by kathryngo** [comment]
Fixed the icon alignment @davidmason:
adv-search-alignfix
 
I will have a look at improving the font size in the advanced search drop-down at a later date - it will involve a fair bit of tinkering. At the moment the way it flows over two lines hinders readability.

**Comment by huangp** [comment]
Reviewed 46 of 46 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java, line 280 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/443#-Kpmp9XyShPxtTGGvE2Q:-Kpmp9XyShPxtTGGvE2R:b-ysn68r) ([raw file](https://github.com/zanata/zanata-platform/blob/6d1455a6b463be4641af54e00abd8615a6c3dcab/api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java#L280)):*
> ```Java
>         @QueryParam("sourceComment") String sourceComment,
>         @QueryParam("transComment") String transComment,
>         @QueryParam("msgContext") String msgContext);
> ```

I think we need to create a DTO to capture all the search parameters. It's getting too long. GET with body is supported by the spec https://stackoverflow.com/questions/978061/http-get-with-request-body#comment68112820_983458 but we might want to test and see how it interacts in browser (caching etc). Otherwise maybe create a new endpoint with POST since the result is likely not cacheable.

---

*[server/zanata-frontend/src/frontend/app/editor/watchers/phrase-detail.js, line 23 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/443#-KpxC0RN0GhvZNdAWma9:-KpxC0RN0GhvZNdAWmaA:b-25msy1) ([raw file](https://github.com/zanata/zanata-platform/blob/5a7db827ac7df0a119b8c7ef269e6ce810eb77b1/server/zanata-frontend/src/frontend/app/editor/watchers/phrase-detail.js#L23)):*
> ```JavaScript
>   FETCHING_PHRASE_DETAIL,
>   PHRASE_DETAIL_FETCHED,
>   PHRASE_DETAIL_FETCH_FAILED
> ```

These are not standard rudex api name. 

---

*[server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java, line 318 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/443#-KpxDeKaZyZFZSJQIg6z:-KpxDeKaZyZFZSJQIg7-:bvxz2ip) ([raw file](https://github.com/zanata/zanata-platform/blob/6d1455a6b463be4641af54e00abd8615a6c3dcab/server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java#L318)):*
> ```Java
>             @QueryParam("sourceComment") String sourceComment,
>             @QueryParam("transComment") String transComment,
>             @QueryParam("msgContext") String msgContext) {
> ```

Same here. It would be better to use body entity instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/443)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java, line 280 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/443#-Kpmp9XyShPxtTGGvE2Q:-KpxRPgrbzXAAR2PV8oI:b-78pe91) ([raw file](https://github.com/zanata/zanata-platform/blob/6d1455a6b463be4641af54e00abd8615a6c3dcab/api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java#L280)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

I think we need to create a DTO to capture all the search parameters. It's getting too long. GET with body is supported by the spec https://stackoverflow.com/questions/978061/http-get-with-request-body#comment68112820_983458 but we might want to test and see how it interacts in browser (caching etc). Otherwise maybe create a new endpoint with POST since the result is likely not cacheable.
</blockquote></details>

The URLs will be fine because most of the time it is only a few fields being used, but the signature of these methods is quite long. This is only used for the editor so it is cleaner just to change this endpoint to use POST and avoid duplication.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/443)*

**Comment by huangp** [comment]
Reviewed 2 of 46 files at r1, 20 of 20 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/app/editor/api/index.js, line 64 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/443#-Kq6gZJJTi9UgbpEftuN:-Kq6gZJJTi9UgbpEftuO:bcz5yrx) ([raw file](https://github.com/zanata/zanata-platform/blob/c8a801f75faa5eb7aefedeea331756fba1d06e57/server/zanata-frontend/src/frontend/app/editor/api/index.js#L64)):*
> ```JavaScript
>     .toPairs()
>     .filter(([key, value]) => !isEmpty(value))
>     .map(([key, value]) => `${key}=${encodeURIComponent(value)}`)
> ```

Do we still need to encode if it's in the body entity?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/443)*

**Comment by davidmason** [comment]
Review status: 38 of 50 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java, line 280 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/443#-Kpmp9XyShPxtTGGvE2Q:-KqL9a3cjLrs0ae9EI8O:bsrni4h) ([raw file](https://github.com/zanata/zanata-platform/blob/6d1455a6b463be4641af54e00abd8615a6c3dcab/api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java#L280)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

The URLs will be fine because most of the time it is only a few fields being used, but the signature of these methods is quite long. This is only used for the editor so it is cleaner just to change this endpoint to use POST and avoid duplication.
</blockquote></details>

Body is now `FilterFields` instead of all the query params.

---

*[server/zanata-frontend/src/frontend/app/editor/api/index.js, line 64 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/443#-Kq6gZJJTi9UgbpEftuN:-KqLAfrmZFSFt9TJ9M5U:bspsikm) ([raw file](https://github.com/zanata/zanata-platform/blob/c8a801f75faa5eb7aefedeea331756fba1d06e57/server/zanata-frontend/src/frontend/app/editor/api/index.js#L64)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Do we still need to encode if it's in the body entity?
</blockquote></details>

Good catch. This function and the next one are replaced in `watchers/phrase-list` and `watchers/phrase-detail` using the api middleware, so I should have deleted them before.

---

*[server/zanata-frontend/src/frontend/app/editor/watchers/phrase-detail.js, line 23 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/443#-KpxC0RN0GhvZNdAWma9:-KqLB6y1Jr363I3HfJJz:b-tfi7ol) ([raw file](https://github.com/zanata/zanata-platform/blob/5a7db827ac7df0a119b8c7ef269e6ce810eb77b1/server/zanata-frontend/src/frontend/app/editor/watchers/phrase-detail.js#L23)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

These are not standard rudex api name. 
</blockquote></details>

Updated to REQUEST, SUCCESS, FAILURE

---

*[server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java, line 318 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/443#-KpxDeKaZyZFZSJQIg6z:-KqLBB9Pxxq5klUOVd3_:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/6d1455a6b463be4641af54e00abd8615a6c3dcab/server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java#L318)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Same here. It would be better to use body entity instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/443)*

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 1 of 46 files at r1, 1 of 20 files at r3, 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/443#-:-KqLSVoZIiQIeylsSlrF:b9a2vem)*

**Comment by kathryngo** [comment]
I just improved the advanced search panel layout width. The advanced search panel now handles the labels in one row regardless of screen size. See image:

advsearchpanel

**Comment by spathare21** [comment]
@davidmason , @kathryngo looks like there is conflict. @huangp I think you forgot to approve changes as it still shows review requested

**Comment by davidmason** [comment]
Sorry @spathare21, I did not realize this had the QA label on it yet. I'll set it back on when I am sure it is ready.

**Comment by huangp** [comment]
Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
Review status: 49 of 50 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/443)*

**Comment by spathare21** [comment]
@davidmason  it shows conflict above not sure why  and also build failure on jenkins

**Comment by davidmason** [comment]
@spathare21 maybe another merge since I fixed the conflicts. I'll look into it but probably won't have it working until tomorrow.

**Comment by kathryngo** [comment]
@spathare21, @davidmason the merge conflict was with style.less due to a merge from release. I fixed that and now there are others. I shall leave that with you David.

**Comment by davidmason** [comment]
@spathare21 this has been rebased and should be ready to test now.

**Comment by spathare21** [comment]
Is it possible to align the advanced search boxes? , also the advance search closed if we click anywhere on the page but "Hide advanced" text not changing. 

screenshot from 2017-08-08 10-51-59

Hide advance text not changing even if search box hidden. and afer that to open advace search we need to click twice. 

screenshot from 2017-08-08 10-52-08

**Comment by davidmason** [comment]
@spathare21 for the closing, advanced search will be visible again when you click the text box, so show/hide advanced is whether it should show when the focus is on that element. It is working as I expect, but I might need to re-think that so that it is not confusing to users.

I could change it so that it toggles back to hiding advanced and you have to click it again to show, or I could change it so that advanced will keep showing regardless of focus, until you hide it.

@kathryngo what sounds best to you?

**Comment by spathare21** [comment]
@davidmason again there is conflict

**Comment by davidmason** [comment]
@spathare21 I think from the branch I just merged. I will fix that now.

**Comment by davidmason** [comment]
@spathare21 rebased to fix the conflicts.

**Comment by kathryngo** [comment]
@davidmason I am leaning towards "so that it toggles back to hiding advanced and you have to click it again to show"

**Comment by spathare21** [comment]
@davidmason have you resolved conflicts as it still shows the same. @kathryngo are you going to do changes for toggle back ?

**Comment by davidmason** [comment]
@spathare21 it is a different conflict caused by a PR that @aeng merged, will fix it shortly.

I am also still working on the focus issue (browser focus is complicated to deal with).

**Comment by davidmason** [comment]
@spathare21 I have fixed the conflicts and now the advanced search panel will stay open until you toggle it closed.

I am still working on aligning the advanced search input fields.

**Comment by spathare21** [comment]
@davidmason ok, but Build is failing on Jenkins as well as locally.

**Comment by davidmason** [comment]
@spathare21 I have fixed the alignment of the advanced search fields, and updated the tests so the build now completest.

It was marked unstable due to java compiler warnings, so I have addressed some of those - it should be enough to bring the warnings below the threshold so the build can be green - that change should not have any influence on the advanced search component (or anything in the editor).

**Comment by spathare21** [comment]
@davidmason changes looks good to me but build failed on jenkins

**Comment by davidmason** [comment]
@spathare21 I'll fix that tonight if I have time, otherwise first thing tomorrow.

**Comment by davidmason** [comment]
@spathare21 finally got a passing build.

**Comment by spathare21** [comment]
@davidmason cool, the advance search is working fine but the advanced search panel overlaps with the Details in chrome browser and and looks to short in Fierfox browser. the width of advanced search panel should be same as a search box.

See the attached screen captured. and also let me know if needs to create separate issue. 

Chrome : 
chrome_advance_panel


Firefox : 
firefox_advace_panel

**Comment by davidmason** [comment]
@spathare21 I think the appearance in chrome is how it was designed, but I may be wrong about that assumption. I will have to check with @kathryngo then fix it on Monday.

@kathryngo please let me know which appearance is expected and I will fix it to be the same in both browsers. I see that the width of the search box is incorrect in Firefox (not expanding so the media queries must not be applying properly) so I will fix that while I'm at it.

**Comment by kathryngo** [comment]
@davidmason the Chrome view is the correct one

**Comment by davidmason** [comment]
Thanks @kathryngo - I'll sort it out so it works the same in Firefox.

**Comment by spathare21** [comment]
@kathryngo , if the chrome view is correct one, then how can we see the details by clicking on "i" to enter the resource id or any info. i think the advance search box size should be same as the normal search box shown in chrome.

**Comment by kathryngo** [comment]
@davidmason it might be good to make sure there is a max-width set so that it doesn't cover the i icon like @spathare21 mentioned. Go with the firefox view if its easier to implement

**Comment by davidmason** [comment]
@kathryngo the ideal would be to expand that whole bar across its full width, but that is tricky with the way the layout elements are positioned at the moment. Since the search box should be reasonably wide with the media queries (once fixed in firefox) that will be adequate and a lot easier to implement for now.

**Comment by spathare21** [comment]
@davidmason is this ready for QA

**Comment by davidmason** [comment]
@spathare21 yes, please go ahead with testing. The difference between chrome and firefox should be fixed now and build is passing.

**Pull request merged**
