### PR TITLE
chore(ZNTA-2652): Upgrade Webpack

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2652

- [x] Upgrade Webpack and related dependancies
 - Webpack upgraded 3.10.0 ->  4.16.1
- [x] Split webpack.config.js into dev, prod, storybook, and common
- [x] Improve webpack bundle size
## Before
Webpack Bundle:
masterbundle
Visualized with webpack-bundle-analyzer:
masterbundleanalyze
## After:
Webpack Bundle:
afterbundle
Visualized with webpack-bundle-analyzer:
analyzerafter

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by seanf** [comment]
@efloden The only possibility is that the key "frontend.css" really is missing from manifest.json during the build (somehow). 
I can get the exact same error message in FrontendAssetsTest by removing that line:

```
org.codehaus.jackson.map.JsonMappingException: Instantiation of [simple type, class org.zanata.action.FrontendManifest] value failed: Parameter specified as non-null is null: method org.zanata.action.FrontendManifest.<init>, parameter frontendCss

	at org.codehaus.jackson.map.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:388)
	at org.codehaus.jackson.map.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:232)
	at org.codehaus.jackson.map.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:118)
	at org.codehaus.jackson.map.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:956)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObjectUsingNonDefault(BeanDeserializer.java:739)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:683)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1909)
	at org.zanata.action.FrontendAssets$Companion.readManifest(FrontendAssets.kt:68)
	at org.zanata.action.FrontendAssets$Companion.access$readManifest(FrontendAssets.kt:61)
	at org.zanata.action.FrontendAssets.<init>(FrontendAssets.kt:39)
	at org.zanata.action.FrontendAssetsTest.canGetAllFrontendJsAndCss(FrontendAssetsTest.kt:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method org.zanata.action.FrontendManifest.<init>, parameter frontendCss
	at org.zanata.action.FrontendManifest.<init>(FrontendManifest.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.jackson.map.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:104)
	at org.codehaus.jackson.map.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:228)
	... 35 more
```

**Comment by efloden** [comment]
@seanf Yes it does seem to be some difference with the build on Jenkins, checking the build logs the frontend.css does not appear to be generated.

**Comment by aeng** [comment]
Lets make it part of 4.6 release.

**Comment by djansen-redhat** [comment]
This is a significant improvement. :+1:

**Pull request merged**
