### PR TITLE
fix(ZNTA-1998): handling of target and source table cells in search&replace

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1998

Fixed text wrapping on projects with long document names in Search and Replace.

To replicate:

- Go to vendor instance in Chrome 58
- Find RHV VM Management Guide
- Download document Explanation of Settings in the New Template and Edit Template Windows
- Download translated PO for Chinese (Simplified) for this document
- Upload document and translations in new project
- Go to search and replace and search 'virtual machine'
- View table layout

It now should not look broken like it does in this image:
vendors-zanata-layout-issue

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/346)

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6334 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/346#-KlLiBg8v3EyrHaZclBs:-KlLiBg8v3EyrHaZclBt:b-imtktp) ([raw file](https://github.com/zanata/zanata-platform/blob/3270a77fb977d8317e257f926ad79aa9a5a98f92/server/zanata-frontend/src/frontend/app/styles/style.less#L6334)):*
> ```Less
> }
> 
> table .projectWideSearchResultsDocumentBody {
> ```

I think we should have a comment in here to indicate this is for GWT editor. easier to remove later on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/346)*

**Comment by kathryngo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6334 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/346#-KlLiBg8v3EyrHaZclBs:-KlLpX7U5BGcPHpuM8P5:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/3270a77fb977d8317e257f926ad79aa9a5a98f92/server/zanata-frontend/src/frontend/app/styles/style.less#L6334)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think we should have a comment in here to indicate this is for GWT editor. easier to remove later on.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/346)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/346#-:-KlLqHsXYL0KQiN-XORG:bnfp4nl)*

**Comment by spathare21** [comment]
Verified

**Pull request merged**
