### PR TITLE
ZNTA-1141 - enable windows bat script to be included

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1141

* include generated bat script for windows into the dist tar.gz and zip
* upgrade the plugin version

This also brings in the changes in https://github.com/zanata/zanata-client/pull/90 (I had to manually apply the changes because the file and repo has all moved.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/172)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/172#-:-Kc-szIiQX1GAJEuT9Nq:bnfp4nl)*

**Comment by aeng** [comment]
@huangp I believe you still need to bring in some old commit from zanata-server repo?

**Comment by huangp** [comment]
@aeng what commits are your referring to? I have manually brought in the documentation change from https://github.com/zanata/zanata-client/pull/90

**Comment by aeng** [comment]
@huangp Thats the one I'm referring to :+1:

**Comment by huangp** [comment]
The codecov thing has gone nuts. I didn't touch all those js files.

**Comment by aeng** [comment]
@huangp Agreed. Ignore codec for this PR.

**Comment by spathare21** [comment]
this needs to be verified on Windows machine right ?

**Comment by aeng** [comment]
@spathare21 Yes please.

**Comment by spathare21** [comment]
@djansen-redhat , can you please check this if you have any windows machine there ,I didn't found any Windows machine here.

**Comment by djansen-redhat** [comment]
✅ Verified. There seems to be a separate issue with 0install that obstructed testing.

**Pull request merged**
