### PR TITLE
 refactor(ZNTA-2529) remove react-bootstrap css

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2529

Removed `.bstrapReact` class, react-bootstrap package and variables.less file

- [x] antd.less will be tidied up
- [x] Variables for padding, margins etc will be refactored into antd.less from the variables file 
- [x] Variables for media queries 
- [x] Make sure all files refer to antd variables file, not the old bootstrap one
- [x] Tachyon utility classes are used where only minor changes are needed in component/container css
- [x] Storybooks will have all references to react-bootstrap removed and stories that are just bootstrap will be removed- will add antd stories in another PR for [ZNTA-2537](http://zanata.atlassian.net/browse/ZNTA-2537)
- [x] React-bootstrap package will be removed entirely (YAY!) 
- [x] Delete bootstrap variables.less file
- [x] Thorough check of frontend for inconsistencies including icon colours and alignment 

**Please note** there is something funky going on with some of the antd variables where they can't be used. So in these cases I have made my styling changes in and.less (for example .ant-switch-* code)

## Useful links
* [Tachyon utility classes](http://tachyons.io/docs/table-of-styles/)
* [Ant-design (antd) components](https://ant.design/docs/react/introduce)

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by kathryngo** [comment]
# Layout/design fixes
__After removing .bstrapReact class__
Most of these issues can be resolved by moving select classes from style.less to antd.less. In some cases (where base antd components do not need to be directly styled) utility classes are best used.

After that is complete:
- [ ] antd.less will be tidied up
- [ ] an audit will be done to ensure all unused css is removed
- [ ] storybooks will have all references to react-bootstrap removed
- [ ] react-bootstrap package will be removed entirely (YAY!) 

## ALL
- [ ] Tooltip/button icon color/hover consistency
- [ ] Utility class consistency
- [ ] Input consistency (input and textareas should use textInput and the same hover/focus styling)
- [ ] Dropdown focus styling
- [ ] Modal heading and footer styling
- [ ] Padding for page containers - same space between page top and left for all react containers except centred Explore page

## EXPLORE
- [ ] Remove search heading
- [ ] Layout for small media query
- [ ] Hover fix for input
- [ ] Muted text colour
- [ ] Result heading colours

## PROJECT VERSION PAGES
- [ ] Merge translation modal - text muted
- [ ] Merge translation modal - footer button positioning
- [ ] TM Merge modal - text styling (text muted, text danger etc)

## PROFILE
- [ ] Container width (wideView)
- [ ] Translation filter button styles
- [ ] Calendar input text colour
- [ ] Calendar input hover styling

## GLOSSARY
- [ ] Container width (wideView)
- [ ] Row styling
- [ ] Row hover - background styling, delete button only shows on Hover
- [ ] Glossary term modal - being migrated from custom modal component to antd by @efloden 
- [ ] React-select language dropdown styling

## LANGUAGES
- [ ] Container width (wideView)
- [ ] Row alignment
- [ ] Delete button styling (same as glossary page)
- [ ] Toolbar responsive layout fixes
- [ ] Toolbar button Padding

## ADMIN LANDING
- [ ] Button Padding
- [ ] Button hover feedback

## ADMIN REVIEW CRITERIA
- [ ] Layout width
- [ ] Row styling

## REACT EDITOR 
- [ ] Weird code chunk - `Toolip>` in Target TransUnit
- [ ] TransUnit header styles
- [ ] Glossary tab info icon colour
- [ ] TM Suggestion modal link colour

**Comment by kathryngo** [comment]
@efloden I keep getting editor test warnings, and I am unsure how to go about fixing them. We can look at this together next week if its easier.
```
PASS  .storybook-frontend/storyshots-frontend.test.js (15.101s)
PASS  .storybook-editor/storyshots-editor.test.js (16.722s)
 ● Console

   console.error node_modules/fbjs/lib/warning.js:33
     Warning: <Button /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
   console.error node_modules/fbjs/lib/warning.js:33
     Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
         in div (created by Tag)
         in AnimateChild (created by Animate)
         in Animate (created by Tag)
         in Tag (created by ConcurrentModal)
         in p (created by ConcurrentModal)
         in div (created by Card)
         in div (created by Card)
         in Card (created by ConcurrentModal)
         in div (created by ModalBody)
         in ModalBody (created by ConcurrentModal)
         in div (created by Modal)
         in div (created by Modal)
         in div (created by Modal)
   console.error node_modules/fbjs/lib/warning.js:33
     Warning: <Button /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
   console.error node_modules/fbjs/lib/warning.js:33
     Warning: <Button /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
```

**Comment by kathryngo** [comment]
merging in master broke some of my css, looks like antd.less and/or the variables are not being loaded. 
mergebreak

**Comment by kathryngo** [comment]
@spathare21 fixed merge conflict - thanks for bringing that to my attention
I will make sure to test this branch after this merge once again to ensure everything builds without errors.

**Comment by djansen-redhat** [comment]
Looks good to me

**Pull request merged**
