### PR TITLE
test(adapter): Add TSAdapter unit tests

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: n/a

Add TSAdapter tests
Remove unused SubDocument check and related stripPath method
Check for extracomment before comment
Fix generated filename without extension

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/190)

### CODE REVIEW

**Comment by seanf** [comment]
Looks like there's a few changes in the TSAdapter implementation, but I don't understand the code very well.

---

Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java, line 320 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/190#-KcaVOikgLueMB6DRqPU:-KcaVOikgLueMB6DRqPV:b3ii7s6) ([raw file](https://github.com/zanata/zanata-platform/blob/a6f6a3650e93171f676cce0656a1ca895d24c514/server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java#L320)):*
> ```Java
>                     context = "";
>                 } else if (event
>                         .getEventType() == EventType.START_SUBDOCUMENT) {
> ```

Should these three if-else statements perhaps have else blocks which throw an exception (or just warn) if an unexpected okapi event is seen? 

---

*[server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java, line 134 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/190#-KcaStd8bqy5KLzLjbHY:-KcaStd9swROd_wps4tC:bdbfagv) ([raw file](https://github.com/zanata/zanata-platform/blob/09729d7a1ba58d32bd6be30e74a2b4eb7ea69755/server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java#L134)):*
> ```Java
>     public void testSourceLocaleCannotBeNull() {
>         File testFile = new File(filePath.concat("basicts.ts"));
>         exception.expect(IllegalArgumentException.class);
> ```

IllegalArgumentException usually means a violated method contract, which doesn't usually make sense for a unit test. How about putting `@NonNull` on the parameter, and removing both the check and this test?

---

*[server/zanata-war/src/test/resources/org/zanata/adapter/test-ts-plurals.ts, line 6 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/190#-KcaUUVPKe9qncHn4FBo:-KcaUUVPKe9qncHn4FBp:by9q25l) ([raw file](https://github.com/zanata/zanata-platform/blob/09729d7a1ba58d32bd6be30e74a2b4eb7ea69755/server/zanata-war/src/test/resources/org/zanata/adapter/test-ts-plurals.ts#L6)):*
> ```XML
>     <name>testContext</name>
>     <message numerus="yes">
>       <source>%1 takes at most %n argument(s). %2 is therefore invalid.</source>
> ```

Just out of interest, can a .ts file be written so that the source text has separate text for singular and plural forms?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/190#-:-KcaV2U7vo5vv3rLWr59:b-ej8w4u)*

**Comment by djansen-redhat** [comment]
*[server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java, line 320 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/190#-KcaVOikgLueMB6DRqPU:-KcaXTBpVCEsreoEsYoP:b-5bztc2) ([raw file](https://github.com/zanata/zanata-platform/blob/a6f6a3650e93171f676cce0656a1ca895d24c514/server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java#L320)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Should these three if-else statements perhaps have else blocks which throw an exception (or just warn) if an unexpected okapi event is seen? 
</blockquote></details>

Yes? I'm not sure to be honest. More research required there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/190)*

**Comment by djansen-redhat** [comment]
*[server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java, line 134 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/190#-KcaStd8bqy5KLzLjbHY:-KcaZBW1E8i63Dg4bgso:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/09729d7a1ba58d32bd6be30e74a2b4eb7ea69755/server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java#L134)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

IllegalArgumentException usually means a violated method contract, which doesn't usually make sense for a unit test. How about putting `@NonNull` on the parameter, and removing both the check and this test?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/190)*

**Comment by djansen-redhat** [comment]
*[server/zanata-war/src/test/resources/org/zanata/adapter/test-ts-plurals.ts, line 6 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/190#-KcaUUVPKe9qncHn4FBo:-KcaZF8imgChy8jaWP7M:bv48ltx) ([raw file](https://github.com/zanata/zanata-platform/blob/09729d7a1ba58d32bd6be30e74a2b4eb7ea69755/server/zanata-war/src/test/resources/org/zanata/adapter/test-ts-plurals.ts#L6)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Just out of interest, can a .ts file be written so that the source text has separate text for singular and plural forms?
</blockquote></details>

No. The .ts source has a 'programmable' placeholder and refers to all plural forms. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/190)*

**Comment by djansen-redhat** [comment]
There are, very minor. Removing unused stuff mostly (thanks codecov), but there was a minor bug in what comment was picked up by the parser.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/190#-:-KcaZYt1sWi3X4TWhdm1:b-uvvmbj)*

**Comment by seanf** [comment]
> Looks like there's a few changes in the TSAdapter implementation, but I don't understand the code very well.

@djansen-redhat You can ignore that bit. I forgot that was still there.

**Comment by djansen-redhat** [comment]
@seanf re the three else-if blocks, I think anything else is basically ignored by that implementation, but I'll look into it later.

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/190#-:-Kca_w5B3LouKQX_9yIA:bnfp4nl)*

**Pull request merged**
