### PR TITLE
Rest api docs

### PR DESCRIPTION
**Pull request by carlosmunoz**
*Constant additions to improve the REST API documentation*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/291)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[api/zanata-common-api/README.md, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim2nQyf4tfifSJl7-a:-Kim2nQyf4tfifSJl7-b:b-br302k) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/README.md#L7)):*
> ```Markdown
> To open the file you can use
> 
>     google-chrome target/site/apidocs/index.html
> ```

We should probably add the `mvn site` version too (or instead), since the results were quite different.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/dto/ProcessStatus.java, line 79 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim3PwJ00JyvHz_U5Qt:-Kim3PwM4XrcKSU7-s5A:bbxubu) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/dto/ProcessStatus.java#L79)):*
> ```Java
> 
>     @XmlElement(required = true)
>     @DocumentationExample("http://example.com")
> ```

Maybe zanata.example.com would be clearer?

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/AsynchronousProcessResource.java, line 46 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim7MVyPXHDDRAB-fGn:-Kim7MVyPXHDDRAB-fGo:b-okfyiv) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/service/AsynchronousProcessResource.java#L46)):*
> Only certain processes are exposed as an asynchronous resource.

suggestion: Only certain *types of* processes are exposed as *asynchronous resources*.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/FileResource.java, line 44 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim3xWmL5NVtdxLyhl5:-Kim3xWmL5NVtdxLyhl6:b6r453j) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/service/FileResource.java#L44)):*
> Represents binary translation files.

Not necessarily binary, but it can handle binary files. And more like translatable files - they're not MO files.

suggestion: Represents various types of translatable files to be converted by the server instead of the REST client.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/package-info.java, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim4eELdTRJ14e9c_F5:-Kim4eELdTRJ14e9c_F6:b-fna1ig) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/service/package-info.java#L1)):*
> ```Java
> package org.zanata.rest.service;
> ```

Looks like we don't need this file at all.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslationMemoryResource.java, line 43 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim62dEUqUmiRy6B0zF:-Kim62dEUqUmiRy6B0zG:bdoaz9c) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslationMemoryResource.java#L43)):*
> ```Java
> 
> /**
>  * This API allows clients to [push and] pull translation memories.
> ```

The *whole* thing is the API. This is just one resource within the REST API - that's what these things are called in REST.

What's really unfortunate is that we have a REST resource named Resource. :-(

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/VersionResource.java, line 53 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim6u0hsjw5LNJiz8E3:-Kim6u0hsjw5LNJiz8E4:bb095rv) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/service/VersionResource.java#L53)):*
> ```Java
>      *         content.<br>
>      *         INTERNAL SERVER ERROR(500) - If there is an unexpected error in
>      *         the server while performing this operation.
> ```

It would be nice to clean these up at some point. There's not much point in documenting "500 = internal server error" at the resource level over and over, since 500 means "internal server error" for every resource on the internet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/291)*

**Comment by carlosmunoz** [comment]
*[api/zanata-common-api/src/main/java/org/zanata/rest/service/FileResource.java, line 44 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim3xWmL5NVtdxLyhl5:-KimA4AYLH6HHJb5X0Rn:b-62uove) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/service/FileResource.java#L44)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

> Represents binary translation files.

Not necessarily binary, but it can handle binary files. And more like translatable files - they're not MO files.

suggestion: Represents various types of translatable files to be converted by the server instead of the REST client.
</blockquote></details>

I will change 'converted' to 'processed' and take the rest of your suggestion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/291)*

**Comment by carlosmunoz** [comment]
*[api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslationMemoryResource.java, line 43 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim62dEUqUmiRy6B0zF:-KimAVuk-VOvBb_Bdqrk:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslationMemoryResource.java#L43)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

The *whole* thing is the API. This is just one resource within the REST API - that's what these things are called in REST.

What's really unfortunate is that we have a REST resource named Resource. :-(
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/291)*

**Comment by seanf** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/AsynchronousProcessResource.java, line 46 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim7MVyPXHDDRAB-fGn:-KimkFiiNtOXW7eQz0gZ:b-e8b6m1) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/service/AsynchronousProcessResource.java#L46)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

> Only certain processes are exposed as an asynchronous resource.

suggestion: Only certain *types of* processes are exposed as *asynchronous resources*.
</blockquote></details>

Should remove "an".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/291)*

**Comment by carlosmunoz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[api/zanata-common-api/README.md, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim2nQyf4tfifSJl7-a:-KimnAkyHbibcWxfem-M:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/README.md#L7)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should probably add the `mvn site` version too (or instead), since the results were quite different.
</blockquote></details>

Done.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/dto/ProcessStatus.java, line 79 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim3PwJ00JyvHz_U5Qt:-KimnBPdZ8IfKS3v5OcD:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/dto/ProcessStatus.java#L79)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Maybe zanata.example.com would be clearer?
</blockquote></details>

Done.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/AsynchronousProcessResource.java, line 46 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim7MVyPXHDDRAB-fGn:-KimmymQRhu2SfMg1Duf:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/service/AsynchronousProcessResource.java#L46)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Should remove "an".
</blockquote></details>

Done.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/package-info.java, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-Kim4eELdTRJ14e9c_F5:-Kimn6dq6cIoU9qEnEZX:bss4a2b) ([raw file](https://github.com/zanata/zanata-platform/blob/5772eef4e49a2e80a3c46e6680b6c142c106574f/api/zanata-common-api/src/main/java/org/zanata/rest/service/package-info.java#L1)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Looks like we don't need this file at all.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/291)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/291#-:-KimneotVPpCQcihfnfP:bnfp4nl)*

**Comment by seanf** [comment]
Looks like codecov is talking nonsense again.

**Comment by carlosmunoz** [comment]
@spathare21 @djansen-redhat please verify that the documentation still builds (See README). This combined with a green build should be enough to merge this.

**Comment by spathare21** [comment]
Jenkins build is green.

**Pull request merged**
