### PR TITLE
fix(ZNTA-2314) tidy up styling of reject translation modal

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2314

Before
b4-moadl

After
after-modal

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/656)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/656#-:-L2Yk9GbdQjqyieLs_mf:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo  I am not sure here what to test reject criteria or reject translation in editor/Alpha editor.

ticket looks for reject criteria and PR look for reject translation.

**Comment by kathryngo** [comment]
It's just an interface in storybook

Run `make storybook-editor` from `zanata-frontend/src/frontend`

then go to `localhost:9001`

and view the `RejectTranslationModal`

I usually mark this as NO QA but forgot this time

**Comment by spathare21** [comment]
ohh ok thanks

**Pull request merged**
