### PR TITLE
ZNATA-2232 Upload source document '+' icon.

### PR DESCRIPTION
**Pull request by spathare21**
JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-2232*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/561)

### CODE REVIEW

**Comment by kathryngo** [comment]
@spathare21 I tried to add some styling changes to this PR but I can't due to permissions. 
To fix the alignment of the source button and make the colour more suitable, please open up
`server/zanata-frontend/src/frontend/app/styles/gwt.less`

and add this before the last `}`

`.panel__header__actions a#file-upload-component-toggle-button {
        margin-top: 0.5rem !important;
        color: #546677;
  }`

**Comment by spathare21** [comment]
@kathryngo done

**Comment by kathryngo** [comment]
@spathare21 reviewing and testing now

**Comment by kathryngo** [comment]
Reviewed 1 of 1 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/styles/gwt.less, line 62 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/561#-Kvk_kchrdxLxeos3xsR:-Kvk_kchrdxLxeos3xsS:bmy1ee) ([raw file](https://github.com/zanata/zanata-platform/blob/941be0989be2a235321d1e075c2f288bf27436b2/server/zanata-frontend/src/frontend/app/styles/gwt.less#L62)):*
> ```Less
>     min-width: unset;
>   }
>   .panel__header__actions a#file-upload-component-toggle-button {
> ```

This classname does not seem to be working for me. I will fiddle around and try to resolve what is going on here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/561)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/styles/gwt.less, line 62 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/561#-Kvk_kchrdxLxeos3xsR:-KvkcS0vQymW5FXtp5ZM:blm2oic) ([raw file](https://github.com/zanata/zanata-platform/blob/941be0989be2a235321d1e075c2f288bf27436b2/server/zanata-frontend/src/frontend/app/styles/gwt.less#L62)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

This classname does not seem to be working for me. I will fiddle around and try to resolve what is going on here.
</blockquote></details>

@spathare21 Ok, best to just remove this css since I can't get it to work. It's not critical.

One thing I have noticed is that needs fixing is that `line 20` of this file is missing a `;` after    `padding: 0.75rem`


I will make this css change at a future date. Let's just get this onto QA after you add the missing semicolon.  :smiley: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/561)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/styles/gwt.less, line 62 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/561#-Kvk_kchrdxLxeos3xsR:-Kvkd3nQwmiKPxX7Xfi_:b-tqw7rj) ([raw file](https://github.com/zanata/zanata-platform/blob/941be0989be2a235321d1e075c2f288bf27436b2/server/zanata-frontend/src/frontend/app/styles/gwt.less#L62)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

@spathare21 Ok, best to just remove this css since I can't get it to work. It's not critical.

One thing I have noticed is that needs fixing is that `line 20` of this file is missing a `;` after    `padding: 0.75rem`


I will make this css change at a future date. Let's just get this onto QA after you add the missing semicolon.  :smiley: 
</blockquote></details>

To clarify, I will make the changes to the toggle button styling that you added in your second commit at a future date.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/561)*

**Comment by spathare21** [comment]
@kathryngo have to remove these css changes right ? also have to add ; which was was mention in your above comment ?

**Comment by kathryngo** [comment]
Yes and yes 😄

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/561#-:-KvvmoSqX0Z5Vhn9tXNz:bnfp4nl)*

**Comment by kathryngo** [comment]
@spathare21 would you like to add the label for NO QA (2nd vote)? I think this can skip QA since it's such a tiny change. Once you have done that, you should be good to merge.

**Comment by spathare21** [comment]
yup thanks : )

**Pull request merged**
