### PR TITLE
Switch to JDT compiler; other static analysis changes

### PR DESCRIPTION
**Pull request by seanf**
- Eliminate double compilation in server (maven-compiler plus takari-lifecycle)
- Switch to Eclipse JDT compiler to restore missing warnings
- Fix some compiler warnings
- Increase javac warnings threshold to match JDT warnings
- Lower FindBugs warnings thresholds
- Add kotlin warnings parser (custom)
- Update detekt

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/395)

### CODE REVIEW

**Comment by aeng** [comment]
@seanf Jenkins build failed.

**Comment by aeng** [comment]
Reviewed 11 of 13 files at r1.
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/zanata-model/src/main/java/org/zanata/model/HLocale.kt, line 125 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/395#-KmZkRjXPQSypXiXJ7Nh:-KmZkRjXPQSypXiXJ7Ni:b-7sh6sz) ([raw file](https://github.com/zanata/zanata-platform/blob/778d239093a0de34452c462ebf34d00d02bd7c8a/server/zanata-model/src/main/java/org/zanata/model/HLocale.kt#L125)):*
> ```Kotlin
>      * Gets the default name of the locale according to that locale, from ICU4J.
>      */
>     fun retrieveDefaultNativeName() = asULocale().getDisplayName(asULocale())
> ```

do we have max length styling for kotlin?

---

*[server/zanata-war/src/main/java/org/zanata/dao/LocaleDAO.kt, line 41 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/395#-KmZk_PObUXJlABdyXWa:-KmZk_PObUXJlABdyXWb:bbrbmy2) ([raw file](https://github.com/zanata/zanata-platform/blob/778d239093a0de34452c462ebf34d00d02bd7c8a/server/zanata-war/src/main/java/org/zanata/dao/LocaleDAO.kt#L41)):*
> ```Kotlin
>     constructor(session: Session) : super(HLocale::class.java, session) {}
> 
>     fun findByLocaleId(locale: LocaleId) = session.byNaturalId(HLocale::class.java)
> ```

max length styling?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/395)*

**Comment by seanf** [comment]
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-model/src/main/java/org/zanata/model/HLocale.kt, line 125 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/395#-KmZkRjXPQSypXiXJ7Nh:-KmZzX6c3eIVnViKN4zS:b-oqnfkb) ([raw file](https://github.com/zanata/zanata-platform/blob/778d239093a0de34452c462ebf34d00d02bd7c8a/server/zanata-model/src/main/java/org/zanata/model/HLocale.kt#L125)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

do we have max length styling for kotlin?
</blockquote></details>

My IDE is configured for 80 columns, but the Kotlin formatter seems to ignore it. 

Detekt will complain if we go over 120 characters, but in general I suggest we use Intellij's soft wrapping feature, which will let us use our various screen widths to maximum advantage.

---

*[server/zanata-war/src/main/java/org/zanata/dao/LocaleDAO.kt, line 41 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/395#-KmZk_PObUXJlABdyXWa:-Km_BKlsbHGEPPIQJeMk:b-83xp56) ([raw file](https://github.com/zanata/zanata-platform/blob/778d239093a0de34452c462ebf34d00d02bd7c8a/server/zanata-war/src/main/java/org/zanata/dao/LocaleDAO.kt#L41)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

max length styling?
</blockquote></details>

Naaa.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/395)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/395#-:-Km_G4FIiB9kW8NXo_jI:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/395)*

**Comment by seanf** [comment]
@aeng Could I get you to take another look please?

**Comment by seanf** [comment]
@djansen-redhat I have made sure to run all the functional tests, but given the compiler switch, do you want to veto the No_QA?

**Comment by aeng** [comment]
Reviewed 18 of 22 files at r4.
Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/common/DocumentType.java, line 151 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/395#-Kn1I1RvGA7luBWxf1bs:-Kn1I1RvGA7luBWxf1bt:bjhedqx) ([raw file](https://github.com/zanata/zanata-platform/blob/96d7b66b29cd8e54b2dfa51199fdda6d3dc5451a/api/zanata-common-api/src/main/java/org/zanata/common/DocumentType.java#L151)):*
> ```Java
>     DocumentType(String... extensions) throws IllegalArgumentException {
>         Map<String, String> extensionsMap = new HashMap<>();
>         for (String extension : extensions) {
> ```

Should we check for null for `extensions` if the annotation is removed?

---

*[api/zanata-common-api/src/main/java/org/zanata/common/DocumentType.java, line 163 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/395#-Kn1I9TWY_qPVMRO2xOO:-Kn1I9TWY_qPVMRO2xOP:brhumzt) ([raw file](https://github.com/zanata/zanata-platform/blob/96d7b66b29cd8e54b2dfa51199fdda6d3dc5451a/api/zanata-common-api/src/main/java/org/zanata/common/DocumentType.java#L163)):*
> ```Java
>     // https://bugs.eclipse.org/bugs/show_bug.cgi?id=388314 and
>     // https://bugs.openjdk.java.net/browse/JDK-8024694
>     DocumentType(Map<String, String> extensions) throws IllegalArgumentException {
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/395)*

**Comment by seanf** [comment]
Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/common/DocumentType.java, line 151 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/395#-Kn1I1RvGA7luBWxf1bs:-Kn1pM-51jyDlrfOAmyi:b-n2grta) ([raw file](https://github.com/zanata/zanata-platform/blob/96d7b66b29cd8e54b2dfa51199fdda6d3dc5451a/api/zanata-common-api/src/main/java/org/zanata/common/DocumentType.java#L151)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should we check for null for `extensions` if the annotation is removed?
</blockquote></details>

No need, because the only thing calling the constructor is this enum. Besides, the NonNull was just there to help static analysis, not to add runtime checks.

---

*[api/zanata-common-api/src/main/java/org/zanata/common/DocumentType.java, line 163 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/395#-Kn1I9TWY_qPVMRO2xOO:-Kn1pfTatE2KeVwCwxYB:bs4q9op) ([raw file](https://github.com/zanata/zanata-platform/blob/96d7b66b29cd8e54b2dfa51199fdda6d3dc5451a/api/zanata-common-api/src/main/java/org/zanata/common/DocumentType.java#L163)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Ditto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/395)*

**Comment by aeng** [comment]
Reviewed 1 of 22 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/395)*

**Pull request merged**
