### PR TITLE
feat(ZNTA-2300): editor concurrent save resolution

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2300

Handle concurrent save resolution in the alpha editor.

1. Trigger a concurrent edit in two instances of the alpha editor
2. Conflict error is displayed as a Notification, the text flow save button changes to 'Resolve Conflicts'
3. Clicking 'Resolve Conflicts' opens the conflict resolution modal
4. Save as Latest or Original

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 15 of 17 files at r2.
Review status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @efloden and @aeng)

---

*[server/services/src/main/java/org/zanata/rest/editor/service/TranslationService.java, line 139 at r2](https://reviewable.io/reviews/zanata/zanata-platform/911#-LFpKK1s1jMdNbg0ptZR:-LFpKK1s1jMdNbg0ptZS:bstvfaz) ([raw file](https://github.com/zanata/zanata-platform/blob/124926fd9fed6d2492a3890161f3b967c4999685/server/services/src/main/java/org/zanata/rest/editor/service/TranslationService.java#L139)):*
> ```Java
>                     : "";
>             requestData.setLastModifiedBy(lastModifiedByUserName);
>             requestData.setLastModifiedDate(latest.getLastChanged().toString());
> ```

Best to return as "Date" type and convert to the desired format in the frontend.

---

*[server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.js, line 68 at r2](https://reviewable.io/reviews/zanata/zanata-platform/911#-LFpKbRo9wQl_KbA3_NA:-LFpKbRo9wQl_KbA3_NB:b-ck9qm4) ([raw file](https://github.com/zanata/zanata-platform/blob/47dc61cbf5b2792c74b6b4919b50b06c7ddd6a38/server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.js#L68)):*
> ```JavaScript
>       name: PropTypes.string.isRequired
>     }).isRequired,
>     undoEdit: PropTypes.func.isRequired,
> ```

We removed undoEdit?

---

*[server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js, line 71 at r2](https://reviewable.io/reviews/zanata/zanata-platform/911#-LFpKkm_B5KGfxwgGsfR:-LFpKkm_B5KGfxwgGsfS:bmg4nvd) ([raw file](https://github.com/zanata/zanata-platform/blob/124926fd9fed6d2492a3890161f3b967c4999685/server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js#L71)):*
> ```JavaScript
>       severity: PropTypes.string,
>       message: PropTypes.string,
>       description: PropTypes.any,
> ```

Can be not string?

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/911)*

**Comment by efloden** [comment]
Review status: 11 of 17 files reviewed, 3 unresolved discussions (waiting on @aeng and @efloden)

---

*[server/services/src/main/java/org/zanata/rest/editor/service/TranslationService.java, line 139 at r2](https://reviewable.io/reviews/zanata/zanata-platform/911#-LFpKK1s1jMdNbg0ptZR:-LFpgC7s2fPTT_JYIXBO:b-1surjn) ([raw file](https://github.com/zanata/zanata-platform/blob/124926fd9fed6d2492a3890161f3b967c4999685/server/services/src/main/java/org/zanata/rest/editor/service/TranslationService.java#L139)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Best to return as "Date" type and convert to the desired format in the frontend.
</blockquote></details>

refactored to use the Date type here now

---

*[server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.js, line 68 at r2](https://reviewable.io/reviews/zanata/zanata-platform/911#-LFpKbRo9wQl_KbA3_NA:-LFpL_MU0xTRIJIg4qLt:b-if0lqr) ([raw file](https://github.com/zanata/zanata-platform/blob/47dc61cbf5b2792c74b6b4919b50b06c7ddd6a38/server/zanata-frontend/src/app/editor/components/TransUnitTranslationPanel.js#L68)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

We removed undoEdit?
</blockquote></details>

That was unintentional, thanks for catching it - put it back in the proptypes now

---

*[server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js, line 71 at r2](https://reviewable.io/reviews/zanata/zanata-platform/911#-LFpKkm_B5KGfxwgGsfR:-LFpMI36-JoykxZ7HRUa:b-cgrhqa) ([raw file](https://github.com/zanata/zanata-platform/blob/124926fd9fed6d2492a3890161f3b967c4999685/server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js#L71)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Can be not string?
</blockquote></details>

The ant notification will accept anything that can be rendered for a description, I can use Proptypes.node instead here to make it a bit more specific

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/911)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/911#-:-LFssMVBAnCPK18E4ceb:bnfp4nl)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/911#-:-LGOF39S7AFA3hrX0uee:bnfp4nl)*

**Comment by spathare21** [comment]
@efloden looks like still there is build failure

**Comment by efloden** [comment]
@spathare21 ran another build with full functional tests - passing on Jenkins :ship:

**Comment by efloden** [comment]
Thanks @spathare21, fixed the status update to match the latest/original save.
For the notifications the 'Concurrent edit detected' error notification will now close when saving as latest/original. The 'Concurrent edit successfully resolved' info notification should disappear after 3.5 seconds.

**Pull request merged**
