### PR TITLE
refactor(ZNTA-2379) grommet button test

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2379

## Task
- test Grommet with Typescript (webpack build) ✅ 
- replace bootstrap button with grommet button in all of frontend - static buttons only. will need grommet equivalent to react-bootstrap Overlay component to get the pop-up buttons working. ✅ 
- check that everything is OK after merging in master ✅

## Findings
- no `disabled` prop for buttons. Must be solved through toggling the onClick prop on and off. https://github.com/grommet/grommet/issues/901
- quite a few buttons need extra props. have only replaced the real simple ones that I could get working.
- a lot of buttons contain other components - this is difficult to implement with the grommet.io buttons as they are self-closing. might need a framework like Rebass that allows you to wrap components easier. The more I look at grommet.io the more restrictive it looks, and Rebass looks like a great alternative http://jxnblk.com/rebass/
- Hard to override icon/button styling (ie. add custom styling for complex components/change svg stroke colours). - Rebass is better for this - pretty much ‘bootstrap for react’ - simple, allows us to wrap components in buttons unlike Grommet, in stable v2.0 - will test it out

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/749#-:-L7ScUh9CMBmgxt0izHu:bnfp4nl)*

**Comment by aeng** [comment]
@kathryngo Failure in Jenkins build.

**Comment by kathryngo** [comment]
@aeng cheers, looking at that now

**Comment by spathare21** [comment]
build failed

**Comment by kathryngo** [comment]
Builds are failing. I have attempted to add npm to the pom file to fix the problem but I am obviously messing something up. @aeng or @huangp mind having a look? I tried to do this myself and ended up having to revert my commits that broke things further

```
04:41:06 [ERROR] /bin/sh: npm: command not found
04:41:06 [ERROR] error Command failed with exit code 127.
```

**Comment by spathare21** [comment]
A scroll is not working on the language page created issue for it https://zanata.atlassian.net/browse/ZNTA-2429 as it occurs on master branch as well Add language button looks and working fine.

**Comment by aeng** [comment]
Since this is a test, should we expend the scope to replace all the buttons in frontend (excluding editor) use grommet button?  that way we might have a better picture on the scope when migrating for other components.

**Comment by kathryngo** [comment]
@aeng good idea. Will mark as WIP

**Comment by kathryngo** [comment]
❗- not a simple button replacement
✅- done

## Containers

### Languages (1/2)
✅ Add new language  
❗New language modal buttons - needs disabled prop also

### Explore (1/3) 
✅Cancel search   
❗Pagination left - need to create props to toggle whether button is disabled
❗Pagination right - (as above)

### Admin - review (1/1)
✅ Add new review criteria

### Glossary (1/19)
❗DeleteAllEntriesModal - footer button -  needs disabled prop also - cannot add Grommet.io button without dealing with button overlays also 
❗DeleteEntryModal - footer button - needs disabled prop also - cannot add Grommet.io button without dealing with button overlays also 
❗Entry - x2 -  needs disabled prop also - cannot wrap around LoaderText since it is a self closing component. Will we need to create a custom component for LoaderText buttons?
❗EntryModal - x2 footer button - LoaderText custom button component needed
❗ExportModal - x2 footer button - LoaderText custom button component needed
❗ImportModal - x2 footer button - LoaderText custom button component needed
✅Pagination
❗NewEntryModal - x2 footer button - LoaderText custom button component needed
❗ViewHeader -  x6 - need to be able to toggle icons used

### User profile (1/6)
✅CalendarMonthMatrix - x1
**WIP:** ContentStateFilter - x1
**To Do:** DayMatrix - x1
❗Recent contributions - x2 footer buttons + textInput - need custom textInput component, adding the Grommet.io button while still using react-bootstrap buttons not possible

### Project Version frontend designs (x/x)  
lowest priority

**Comment by kathryngo** [comment]
## Components

✅ DraggableVersionPanels
❗Modal  cannot override stroke colour of icon from #000 using external stylesheet
✅ Notification
❗ProgressBar  needs disabled prop and ability to set status as background colour

**Comment by kathryngo** [comment]
(for my reference) To fix:
pagination-arrows

Plus layout widths in frontend - why are they all inconsistent???

**Comment by kathryngo** [comment]
A better alternative to Grommet.io (ant-design) has been found. Need to refactor bootstrap to that instead. https://github.com/ant-design/ant-design

**Pull request closed without merging**
