### PR TITLE
ZNTA-2325 Implement Syntax Highlighting as an option in the React Editor

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2325

Implemented Syntax Highlighting as an option in the React Editor
There a quite a few styles to choose from for the syntax highlighting which can been demoed here:
http://conor.rodeo/react-syntax-highlighter/demo/
altier-lakeside-light is the style being used in the editor to give some contrast, dark themes to not appear to work in the editor (possibly a css clash)

## QA: 
The checkbox is available in the editors settings panel and the selection should persist after refreshing.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/653)

### CODE REVIEW

**Comment by kathryngo** [comment]
@efloden,  build isn't passing. Shall review once it does if you don't mind

**Comment by kathryngo** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/package.json, line 132 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/653#-L2XREsTSFRbeG281kap:-L2XREsTSFRbeG281kaq:b-jt3fq2) ([raw file](https://github.com/zanata/zanata-platform/blob/aa4067dbfdb822f13a62b8b31da0e0b54797c0f5/server/zanata-frontend/src/frontend/package.json#L132)):*
> ```JSON
>     "react-select": "1.0.0-rc.5",
>     "react-sortable-hoc": "0.6.3",
>     "react-syntax-highlighter": "^6.1.1",
> ```

Use exact version (remove ^)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/653)*

**Comment by efloden** [comment]
*[server/zanata-frontend/src/frontend/package.json, line 132 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/653#-L2XREsTSFRbeG281kap:-L2Y8t91SLXizuWeE9F2:b-bsktfw) ([raw file](https://github.com/zanata/zanata-platform/blob/aa4067dbfdb822f13a62b8b31da0e0b54797c0f5/server/zanata-frontend/src/frontend/package.json#L132)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Use exact version (remove ^)
</blockquote></details>

Updated to use the exact version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/653)*

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/653#-:-L2YAVhVpXcEmyZmOlKi:bnfp4nl)*

**Comment by spathare21** [comment]
@efloden  is it the right syntax highlight.  as it shows text twice one with the syntax and one with highlight

screenshot from 2018-01-11 11-48-02

**Comment by efloden** [comment]
@spathare21 Yes this syntax highlighting is not editable, so we display it below the editable text-area. 
It does work out to be much more performance efficient though.

**Comment by spathare21** [comment]
ok thanks @efloden marking it verified

**Pull request merged**
