### PR TITLE
feat(ZNTA-68): Implement highlighting words in source text that match filter text in editor.

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-68

When a filter is active and the "text" key is one of the keys in the filter, highlight the appropriate matching parts of text in the search results. Text in the source text that matches the value for "text" should be highlighted.
Highlighting of the translation text may not be possible due to this text being editable as part of a text-area.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/647)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/editor/app.css, line 68 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/647#-L23mE8H8c0idGSfGpQc:-L23mE8H8c0idGSfGpQd:bed3fjc) ([raw file](https://github.com/zanata/zanata-platform/blob/205f93843a1048772d821127ffaedd1e072d3d70/server/zanata-frontend/src/frontend/app/editor/app.css#L68)):*
> ```CSS
> 
> .highlight {
>   background-color: #ff6;
> ```

possible to get this `#ff6` from a less file somewhere?

---

*[server/zanata-frontend/src/frontend/app/editor/components/TransUnitSourcePanel.js, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/647#-L23mg6NjHB5ctmbMFQz:-L23mg6NjHB5ctmbMFR-:b-qxq1r6) ([raw file](https://github.com/zanata/zanata-platform/blob/205f93843a1048772d821127ffaedd1e072d3d70/server/zanata-frontend/src/frontend/app/editor/components/TransUnitSourcePanel.js#L7)):*
> ```JavaScript
> import IconButton from './IconButton'
> import { getFilterString } from '../selectors'
> import { connect } from 'react-redux'
> ```

best to keep this component stateless and pass down the `filterString` instead from the caller

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/647)*

**Comment by efloden** [comment]
*[server/zanata-frontend/src/frontend/app/editor/app.css, line 68 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/647#-L23mE8H8c0idGSfGpQc:-L23pCzk7Yj-me95BWDH:b-71b858) ([raw file](https://github.com/zanata/zanata-platform/blob/205f93843a1048772d821127ffaedd1e072d3d70/server/zanata-frontend/src/frontend/app/editor/app.css#L68)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

possible to get this `#ff6` from a less file somewhere?
</blockquote></details>

Not sure if we can source the variable from outside the editor, and might not be possible to use less in the editor: https://zanata.atlassian.net/browse/ZNTA-2296

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/647)*

**Comment by efloden** [comment]
*[server/zanata-frontend/src/frontend/app/editor/components/TransUnitSourcePanel.js, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/647#-L23mg6NjHB5ctmbMFQz:-L23q5Iev5-UWEe_OdXj:b34f5dx) ([raw file](https://github.com/zanata/zanata-platform/blob/205f93843a1048772d821127ffaedd1e072d3d70/server/zanata-frontend/src/frontend/app/editor/components/TransUnitSourcePanel.js#L7)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

best to keep this component stateless and pass down the `filterString` instead from the caller
</blockquote></details>

Considered this as the first approach, would have to lift the prop up to the root component to share it with the TransUnitSourcePanel
Root_/
  EditorHeader -> ControlsHeader -> EditorSearchInput -> filter prop
  TransUnitSourcePanel -> filter prop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/647)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/647#-:-L23rlDA2lBUiWjaEGDR:bnfp4nl)*

**Comment by djansen-redhat** [comment]
Works on single words, but not phrases
screenshot from 2018-01-09 13-38-05

**Comment by spathare21** [comment]
works for single as well as phrase on alpha editor.

screenshot from 2018-01-09 11-22-41

**Comment by djansen-redhat** [comment]
Looks fine, but Jenkins CI appears broken

**Comment by djansen-redhat** [comment]
PR verified

**Comment by efloden** [comment]
@aeng passing in the latest build https://zanata-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/github-zanata-org/job/zanata-platform/job/PR-647/

**Pull request merged**
