### PR TITLE
ZNTA-1653-languages-containers

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1653

Remove all zanata UI components from the containers/Languages/... in frontend
Also fixed vertical alignment of nav sidebar

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/146)

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/DeleteEntry.js, line 30 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/146#-Kady7ipfHDKhHqNPWcS:-Kady7ipfHDKhHqNPWcT:b-wfxspm) ([raw file](https://github.com/zanata/zanata-platform/blob/2087714036ba35709239255e29b4e40c139a7162/server/zanata-frontend/src/frontend/app/containers/Languages/DeleteEntry.js#L30)):*
> ```JavaScript
>         <Button bsSize='small' className='langdel-btn'
>           onClick={() => handleDeleteEntryDisplay(true)}>
>           <i className='fa fa-times Mend(ee)'></i>Delete
> ```

If we got equivalent style in style.less, use that.

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/NewLanguageModal.js, line 192 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/146#-KadyHf9kMqCOSjshZ4u:-KadyHf9kMqCOSjshZ4v:bcugwtd) ([raw file](https://github.com/zanata/zanata-platform/blob/2087714036ba35709239255e29b4e40c139a7162/server/zanata-frontend/src/frontend/app/containers/Languages/NewLanguageModal.js#L192)):*
> ```JavaScript
>                   target='_blank'>
>                   <Icon name='info'
>                     className='s0' atomic={{m: 'Mstart(re) Va(sub)'}}
> ```

Atomic attribute is not longer valid in the new component. Move these class to className attribute. Also, if we got equivalent style in style.less, use that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/146)*

**Comment by kathryngo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/DeleteEntry.js, line 30 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/146#-Kady7ipfHDKhHqNPWcS:-Kae6zGhKSWah2dYKhUw:bb6un1j) ([raw file](https://github.com/zanata/zanata-platform/blob/2087714036ba35709239255e29b4e40c139a7162/server/zanata-frontend/src/frontend/app/containers/Languages/DeleteEntry.js#L30)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

If we got equivalent style in style.less, use that.
</blockquote></details>

Done

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/NewLanguageModal.js, line 192 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/146#-KadyHf9kMqCOSjshZ4u:-Kae7-mgd0bCT7iBdqEL:bb6un1j) ([raw file](https://github.com/zanata/zanata-platform/blob/2087714036ba35709239255e29b4e40c139a7162/server/zanata-frontend/src/frontend/app/containers/Languages/NewLanguageModal.js#L192)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Atomic attribute is not longer valid in the new component. Move these class to className attribute. Also, if we got equivalent style in style.less, use that.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/146)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r5, 2 of 5 files at r6.
Review status: 2 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/146#-:-Kae9xVYJTbOD8xwSGhB:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo , language page works fine but Add new language and notification pop-up is too big on language page than previous one. i thinks it should be like adding new glossary pop-up.

screenshot from 2017-01-17 11-27-39

**Comment by kathryngo** [comment]
Shall fix that now

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/146#-:-Kaf9nbyDDFTnOFcwLbl:brc7w81)*

**Comment by kathryngo** [comment]
ready for review again @spathare21

**Comment by spathare21** [comment]
@kathryngo does it need review again from aeng or can I test it directly.

**Comment by kathryngo** [comment]
You can test directly, only minor css changes

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/146#-:-KafHq7j_tjZWuJ5pu6E:b-39tqhj)*

**Comment by spathare21** [comment]
Verified

**Comment by aeng** [comment]
Reviewed 2 of 5 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/146)*

**Pull request merged**
