### PR TITLE
Update to Selenium 3, update AbstractPage

### PR DESCRIPTION
**Pull request by seanf**
Now more lambda-friendly, from Java and from Kotlin!

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/393)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
Found Banned Dependency: commons-logging:commons-logging:jar:1.2

---

Reviewed 24 of 28 files at r1.
Review status: 24 of 28 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt, line 2 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUbD1olGsmewJPDlED:-KmUbD1pIes_-XR-viOR:bb6ht2h) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt#L2)):*
> ```Kotlin
> /*
>  * Copyright 2010, Red Hat, Inc. and individual contributors as indicated by the
> ```

2017

---

*[server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt, line 109 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUbKWbaKKKGUCBVu2O:-KmUbKWbaKKKGUCBVu2P:bbp40t) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt#L109)):*
> ```Kotlin
>     /**
>      * @param currentPage
>      * *
> ```

Formatting issues (multiple javadoc headers here)

---

*[server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt, line 413 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUcdkgkz9IJlJJLHKk:-KmUcdkhesvz3IKhDdkO:b-utrtcx) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt#L413)):*
> ```Kotlin
>                 .until({ _ -> element.isDisplayed && element.isEnabled })
>     }
>     // Assert the element is available and visible
> ```

Comment in wrong place

---

*[server/functional-test/src/main/java/org/zanata/util/WebDriverLogWait.java, line 43 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUfu8vplAP8uXLC1Q7:-KmUfu8vplAP8uXLC1Q8:b-cp3lj3) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/util/WebDriverLogWait.java#L43)):*
> ```Java
> 
>     @Override
>     public <V> V until(java.util.function.Function<? super WebDriver, V> isTruthy) {
> ```

Intentional change?

---

*[server/functional-test/src/main/java/org/zanata/workflow/AbstractWebWorkFlow.java, line 46 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUg3x6IBN4m45Hn09B:-KmUg3x6IBN4m45Hn09C:bfig3t7) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/workflow/AbstractWebWorkFlow.java#L46)):*
> ```Java
>             driver.get(hostUrl);
>             new BasePage(driver).waitForAMoment().until(
>                     it ->
> ```

Unnecessary line splitting

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-:-KmUeKEg25iWkfRObQ_5:b-erowoq)*

**Comment by seanf** [comment]
Review status: 24 of 28 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt, line 2 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUbD1olGsmewJPDlED:-KmUgrrUTe-cLrH-_wBs:bodthnm) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt#L2)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

2017
</blockquote></details>

Eeeehh. I don't know. It's really just a modified version of AbstractPage.java, which is copyright 2010.

---

*[server/functional-test/src/main/java/org/zanata/util/WebDriverLogWait.java, line 43 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUfu8vplAP8uXLC1Q7:-KmUhNUUb8BqIVB_1ugM:b78qdrd) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/util/WebDriverLogWait.java#L43)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Intentional change?
</blockquote></details>

Um, more or less. java.util.function.Function is better than Guava's com.google.common.base.Function. I should clean up the imports though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/393)*

**Comment by seanf** [comment]
Review status: 2 of 29 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt, line 2 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUbD1olGsmewJPDlED:-KmVLEYZ4HY09RUNCueT:b57b847) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt#L2)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Eeeehh. I don't know. It's really just a modified version of AbstractPage.java, which is copyright 2010.
</blockquote></details>

Unless we're going to list every year when there were some changes, I don't think we should generally change the copyright year ("year of first publication").

---

*[server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt, line 109 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUbKWbaKKKGUCBVu2O:-KmVL3njHKHwEvfDJsZd:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt#L109)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Formatting issues (multiple javadoc headers here)
</blockquote></details>

Done.

---

*[server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt, line 413 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUcdkgkz9IJlJJLHKk:-KmVL4PMaYkkE68uWzGG:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt#L413)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Comment in wrong place
</blockquote></details>

Done.

---

*[server/functional-test/src/main/java/org/zanata/util/WebDriverLogWait.java, line 43 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUfu8vplAP8uXLC1Q7:-KmVM7D-z8RQb68ICrkb:b6otk1y) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/util/WebDriverLogWait.java#L43)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Um, more or less. java.util.function.Function is better than Guava's com.google.common.base.Function. I should clean up the imports though.
</blockquote></details>

Turns out it was using the fully-qualified name because the overridden method signature had the Java Function interface, but the `until` call below was using the Guava function interface. It's all cleaned up with a lambda now.

---

*[server/functional-test/src/main/java/org/zanata/workflow/AbstractWebWorkFlow.java, line 46 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/393#-KmUg3x6IBN4m45Hn09B:-KmVL5LqPdYw-uQWUv2c:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/607b64c306effdf78c7d43e3857c4cd10a4794e2/server/functional-test/src/main/java/org/zanata/workflow/AbstractWebWorkFlow.java#L46)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Unnecessary line splitting
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/393)*

**Comment by djansen-redhat** [comment]
Reviewed 33 of 33 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/393)*

**Pull request merged**
