### PR TITLE
chore(ZNTA-1586,ZNTA-1612): enable Jacoco and Jest/Instanbul test coverage

### PR DESCRIPTION
**Pull request by seanf**
**Enable Jacoco and Jest/Instanbul test coverage**

Note that JavaScript coverage will be **greatly** overstated until https://zanata.atlassian.net/browse/ZNTA-1613

JIRA issues:

- https://zanata.atlassian.net/browse/ZNTA-1586
- https://zanata.atlassian.net/browse/ZNTA-1612

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/101)

### CODE REVIEW

**Comment by seanf** [comment]
Note that JaCoCo has no configured exclusions except in the functional-test module. These exclusions could be brought across, but there were far too many exclusions.

Also note that JaCoCo does not respect the `@CoverageIgnore` annotation yet. We probably use it far too much too, but I'm leaving it in for now, since it's not affecting anything. If and when https://github.com/jacoco/jacoco/issues/14 is fixed, we should probably check our usages of `@CoverageIgnore` before using it for exclusions again.

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@definite Could you please look into this build failure? It seems to be a problem with the artifactory configuration.

doxia-site-renderer-1.1.2.jar appears to be missing from the maven central mirror.

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please.

**Comment by carlosmunoz** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/101)*

**Pull request merged**
