### PR TITLE
Update to Kotlin 1.2.30

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by seanf** [comment]
@kathryngo Could I get you to sanity test `rundev.sh` on your setup with this branch? It's working okay for me, this time around. Seems like they've fixed whatever that problem with Kotlin was last time.

**Comment by kathryngo** [comment]
@seanf sure, will do

**Comment by kathryngo** [comment]
@seanf it works, passes through rundev now.
One issue, there is still an error in rundev, but it does not seem to affect how things function (afaik)
```
03:27:14,971 ERROR [org.zanata.ApplicationConfiguration] 
(ServerService Thread Pool -- 82) 
server path is not configured in database and not yet generated from Http request!!!. 
Admin need to configure it in database
```

**Comment by seanf** [comment]
Okay, thanks @kathryngo.

I think that error message is for an existing problem, added by @huangp recently. See https://zanata.atlassian.net/browse/ZNTA-2319

It shouldn't break rundev because it runs Zanata in the root context anyway.

**Comment by seanf** [comment]
Full functional tests passed.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/739#-:-L6ZtqEHjM4afATYIeL8:bnfp4nl)*

**Pull request merged**
