### PR TITLE
test(action): AccountMergeAction unit tests

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: n/a

AccountMergeAction unit tests. Also
- changes the private static inner class to be a package private class
- injects ZanataIdentity rather than using .Instance()

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/222)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/action/AccountMergeAction.java, line 81 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/222#-KekirQh9Dv4SIRdXI91:-KekirQh9Dv4SIRdXI92:blx0a3t) ([raw file](https://github.com/zanata/zanata-platform/blob/1cfca2ec63c539eb14c98b8a0b4ff74c7b223124/server/zanata-war/src/main/java/org/zanata/action/AccountMergeAction.java#L81)):*
> ```Java
>     private boolean accountsValid;
>     @Inject
>     ZanataIdentity zanataIdentity;
> ```

private ZanataIdentity zanataIdentity? just to make it consistent.

---

*[server/zanata-war/src/main/java/org/zanata/action/AccountMergeAction.java, line 99 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/222#-KekiyunamGRx-chVNV6:-KekiyunamGRx-chVNV7:b7avjxi) ([raw file](https://github.com/zanata/zanata-platform/blob/1cfca2ec63c539eb14c98b8a0b4ff74c7b223124/server/zanata-war/src/main/java/org/zanata/action/AccountMergeAction.java#L99)):*
> ```Java
>     @PostConstruct
>     public void onCreate() {
>         zanataIdentity.checkLoggedIn();
> ```

good one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/222)*

**Comment by djansen-redhat** [comment]
*[server/zanata-war/src/main/java/org/zanata/action/AccountMergeAction.java, line 99 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/222#-KekiyunamGRx-chVNV6:-Kekj_ojXQhUddqP74B8:bnte4s3) ([raw file](https://github.com/zanata/zanata-platform/blob/1cfca2ec63c539eb14c98b8a0b4ff74c7b223124/server/zanata-war/src/main/java/org/zanata/action/AccountMergeAction.java#L99)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

good one.
</blockquote></details>

That's pretty standard now, right? To Inject the identity rather than pulling it from the instance?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/222)*

**Comment by djansen-redhat** [comment]
*[server/zanata-war/src/main/java/org/zanata/action/AccountMergeAction.java, line 81 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/222#-KekirQh9Dv4SIRdXI91:-KekjVBrUVt3hxM4M3ZT:bonvjkx) ([raw file](https://github.com/zanata/zanata-platform/blob/1cfca2ec63c539eb14c98b8a0b4ff74c7b223124/server/zanata-war/src/main/java/org/zanata/action/AccountMergeAction.java#L81)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

private ZanataIdentity zanataIdentity? just to make it consistent.
</blockquote></details>

Yep you're right, will do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/222)*

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/222#-:-KelJNTXaF4kVjcILQcF:bnfp4nl)*

**Pull request merged**
