### PR TITLE
Design: ZNTA-1737-editor-advsearch

### PR DESCRIPTION
**Pull request by kathryngo**
MOVED to https://github.com/zanata/zanata-platform/pull/290 (because I rebased it)

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1737

_Add advanced search with dropdown from GWT editor to the react editor._
When the search field is clicked, the advanced search fields will open underneath. 
Fields that are filled out will be autofilled into the search input field. 
~The blue background cannot be removed from the advanced search as it is part of the parent header, and in the second image below you can see it is necessary for small screened devices.~

## To Do
1. Fix onClick functionality to make the panel appear when the search input is clicked. The panel should be closed by default. I had to use the panels from react-bootstrap components. See: https://react-bootstrap.github.io/components.html#panels-collapsible for an example of a collapsible panel. - @davidmason 
2. ~Remove all SearchModal references and files~ - @kathryngo
3. Add functionality to clear search icon - @davidmason (I tried...)
4. Backend stuff including autofill search field - @davidmason 
5. ~Set panel position to absolute so the header colour does not expand also~ - @kathryngo

advsearch

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/234)

### CODE REVIEW

**Comment by kathryngo** [comment]
I have removed all references to SearchModal and the search is visible if a clean build is run then docker rundev. Using yarn watch results in the following error:
`ERROR in multi main
Module not found: Error: Cannot resolve module 'false' in /Users/kathryngough/IdeaProjects/zanata-platform/server/zanata-frontend/src/frontend
 @ multi main`

**Comment by kathryngo** [comment]
Build works if rundev is used, but the hot-dev server gives this console error:

`[react-router] Location "/project/translate/b1/v/b/odyssey.txt?dswid=8104&lang=ar-BH" did not match any routes`

**Comment by davidmason** [comment]
@kathryngo there are some problems with the makefile and scripts in master. I think in master it is still running the frontend build instead of editor build when you use `make watch-editor`.

I fixed it properly in glossary branch, so if we can get that merged soon it will help. If the errors are slowing you down, I could probably split the fixes into a separate branch and get them merged sooner.

**Comment by kathryngo** [comment]
@davidmason, at this point it's not slowing me down too much. I only have a half a days work or so left with the glossary styling so I think it can wait until we merge this branch.

**Comment by kathryngo** [comment]
@zanata-jenkins retest this please

**Comment by davidmason** [comment]
@kathryngo I'm talking there about rewriting the history to make it as though you never accidentally merged master - not for everyday use since it means everyone who has the branch can get a conflict but handy if used carefully.

**Comment by kathryngo** [comment]
@davidmason, I noticed a small issue on the glossary page, in the glossary search input. There is something weird going on where the glossary text input and the icons are not the same height - you can see what I mean in the bottom border of the search box in this image:
glossissue

Unsure how to fix this because any fix I make to padding or margins messes up the styling of the storybook components. Also, I have tried fiddling around with line-heights but the same issue happens, can't get things looking consistent in storybook and editor. 

(╯°□°）╯︵ ┻━┻

I am thinking that maybe this will resolve itself with a merge, unsure. This branch uses the old storybook build so perhaps that has something to do with it. Any help appreciated

**Comment by huangp** [comment]
:lgtm: but it has merge conflicts 

---

Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/234#-:-Kihp0GyTcyOihs5-f_0:beppyt0)*

**Comment by kathryngo** [comment]
@huangp this branch *was* the advanced search branch but @davidmason updated it to a different PR :`
https://github.com/zanata/zanata-platform/pull/290

Thank you for reviewing this. The new PR has already been reviewed.

**Pull request closed without merging**
