### PR TITLE
fix(ZNTA-1840): Remove the introduction dialog for auto-accepted locale joins

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1840

Remove the "introduce yourself" step for auto accepted translator join.
Also remove requests for the same, which may occur if admin set auto
accept to true with requests pending.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/253)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/action/LanguageAction.java, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/253#-Kgka7AGi2gvuPcguAp7:-Kgka7AGi2gvuPcguAp8:bs33p4h) ([raw file](https://github.com/zanata/zanata-platform/blob/d7dabcc4aa1e189a2ec0eda3a805b7c8f9779186/server/zanata-war/src/main/java/org/zanata/action/LanguageAction.java#L24)):*
> ```Java
> 
> import java.io.Serializable;
> import java.nio.file.AccessDeniedException;
> ```

Don't think this is the right exception to use.

---

*[server/zanata-war/src/main/java/org/zanata/action/LanguageAction.java, line 318 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/253#-Kgkbe8n7JlvMKIcHqV-:-Kgkbe8n7JlvMKIcHqV0:bs2ns2p) ([raw file](https://github.com/zanata/zanata-platform/blob/d7dabcc4aa1e189a2ec0eda3a805b7c8f9779186/server/zanata-war/src/main/java/org/zanata/action/LanguageAction.java#L318)):*
> ```Java
>                     true, isAdmin, isAdmin);
> 
>             LanguageRequest languageRequest = requestServiceImpl
> ```

I assume we are trying to cancel existing requests made before the auto accept request option is enabled?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/253)*

**Comment by djansen-redhat** [comment]
*[server/zanata-war/src/main/java/org/zanata/action/LanguageAction.java, line 318 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/253#-Kgkbe8n7JlvMKIcHqV-:-KgkzRilBxgNYn2xso_Q:bs0km1p) ([raw file](https://github.com/zanata/zanata-platform/blob/d7dabcc4aa1e189a2ec0eda3a805b7c8f9779186/server/zanata-war/src/main/java/org/zanata/action/LanguageAction.java#L318)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I assume we are trying to cancel existing requests made before the auto accept request option is enabled?
</blockquote></details>

Yes - it's the only way I could think of "nicely" handling that situation, other than cycling through all of the requests and granting them immediately. But I think that may be too dangerous (e.g. if the admin changes their mind right after saving the config)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/253)*

**Comment by djansen-redhat** [comment]
*[server/zanata-war/src/main/java/org/zanata/action/LanguageAction.java, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/253#-Kgka7AGi2gvuPcguAp7:-KgkzpQ04u-S52MypMhQ:bvlnvdf) ([raw file](https://github.com/zanata/zanata-platform/blob/d7dabcc4aa1e189a2ec0eda3a805b7c8f9779186/server/zanata-war/src/main/java/org/zanata/action/LanguageAction.java#L24)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Don't think this is the right exception to use.
</blockquote></details>

Is there another AccessDeniedException? I believe it was the one given by the CheckRole annotation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/253)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/253#-:-Kgl2kKWGSUxFUWDo6Qb:bnfp4nl)*

**Pull request merged**
