### PR TITLE
fix: merge trans stops before completing

### PR DESCRIPTION
**Pull request by aeng**
JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/711)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/711#-:-L4ZZdNs-NQMp_E0B064:bnfp4nl)*

**Comment by spathare21** [comment]
@aeng Verified that TM merge is working fine with threshold 80%+ to copy fuzzy strings.
but looks like it was merging before merging this PR as well. so not sure to mark as verified or not

**Comment by spathare21** [comment]
@aeng  ok thanks then marking it as verified have to ignore the codecov ?

**Comment by aeng** [comment]
@spathare21 thanks

**Pull request merged**
