### PR TITLE
fix(ZNTA-1762): Add request count to languages list

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1762

Add the request count to the languages list to indicate outstanding requests.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/455)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@kathryngo I can't seem to get the icon+count to hide when !permission.canAddLocale - can you see what I'm doing wrong?

**Comment by djansen-redhat** [comment]
@kathryngo thanks!

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/455#-:-KqQ5SD8ESRkJQWAC9ZE:bnfp4nl)*

**Comment by djansen-redhat** [comment]
@aeng I got the Collector working! Let me know what you think.

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r2.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/rest/service/LocalesService.java, line 121 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/455#-KqV5k0-UmcjDTFXtQJ4:-KqV5k0-UmcjDTFXtQJ5:bqox3zz) ([raw file](https://github.com/zanata/zanata-platform/blob/d32ee895683d22c97552e622abb438d4043bad68/server/zanata-war/src/main/java/org/zanata/rest/service/LocalesService.java#L121)):*
> ```Java
>             Map<LocaleId, Long> allRequests =
>                     requestService.getPendingLanguageRequests(
>                             localeIds.toArray(new LocaleId[0]))
> ```

Shouldn't it be `new LocaleId[localeIds.size()]`?

---

*[server/zanata-war/src/main/java/org/zanata/rest/service/LocalesService.java, line 123 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/455#-KqV6-ZuYki44j45r2KF:-KqV6-ZuYki44j45r2KG:b-10del5) ([raw file](https://github.com/zanata/zanata-platform/blob/d32ee895683d22c97552e622abb438d4043bad68/server/zanata-war/src/main/java/org/zanata/rest/service/LocalesService.java#L123)):*
> ```Java
>                             localeIds.toArray(new LocaleId[0]))
>                             .stream().collect(Collectors.groupingBy(languageRequest ->
>                             languageRequest.getLocale().getLocaleId(), Collectors.counting()));
> ```

We probably need some unit test on this, just to make sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/455)*

**Comment by aeng** [comment]
Reviewed 1 of 4 files at r1, 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/455)*

**Comment by djansen-redhat** [comment]
@aeng ah yes, thanks for the reminder

**Comment by aeng** [comment]
Reviewed 1 of 4 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/455)*

**Comment by djansen-redhat** [comment]
@aeng - added a test

**Comment by djansen-redhat** [comment]
@aeng oops, missed the previous comment.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/455#-:-Kqa9ViWStSbB6SHewWC:bnfp4nl)*

**Comment by djansen-redhat** [comment]
Build 6 in progress

**Pull request merged**
