### PR TITLE
ZNTA-2169-storybook-rejection-admin

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2169

Storybook for admin interface for reject translation criteria:

By default the criteria decided on by the in-house translation team will be provided. 
When the edit button is clicked, the fields will become editable (dark button).

For the devs: The first input field (Review) on a row that has edit selected should have the focus on so the user knows that this field can be edited.

rejtrans

To see storybook run `make storybook-frontend`
Then go to RejectionsForm to see one locked row, one editable row, and a unified admin interface.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/482)

### CODE REVIEW

**Comment by aeng** [comment]
Do we require sub-category? I'm thinking just the "Review criteria" + "Priority" + input field.

**Comment by kathryngo** [comment]
@aeng ok, shall remove that field from this and the modal

**Comment by aeng** [comment]
@kathryngo how do we delete a criteria?

**Comment by kathryngo** [comment]
@aeng hmm didn't think of that. shall fix the admin interface

**Comment by aeng** [comment]
Reviewed 1 of 4 files at r3.
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KriSG1Fn5QQv7bKjr2M:b-5kvp0u) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
> ```JavaScript
> class RejectionsForm extends Component {
>   static PropTypes = {
>     priority: PropTypes.oneOf([
> ```

This should be a list of constants.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6605 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriRrnYRsw-pxmKN31z:-KriRrnZcjbcDZnInA0k:b7y6rsy) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6605)):*
> ```Less
> }
> 
> form.rejections input.text-input::placeholder,
> ```

is this suitcss way of naming class?

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6623 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriRwtAlV48QJzt9k0c:-KriRwtAlV48QJzt9k0d:bvk5aox) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6623)):*
> ```Less
> }
> 
> .form-group.flex-grow1 {
> ```

This class can be made general to be reused, flex-grow1

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6627 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriS6-8HqCrDjqKWIAZ:-KriS6-8HqCrDjqKWIA_:bvk5aox) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6627)):*
> ```Less
> }
> 
> .form-group.flex-grow2 {
> ```

This class can be made general to be reused, flex-grow1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KriWGTqkuL_pEcNMUis:bvhzvti) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This should be a list of constants.
</blockquote></details>

Can you explain why? I thought if there were some strings that need to be used they are best passed in as props like this. 

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6605 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriRrnYRsw-pxmKN31z:-KriVz5avzWyolv8k521:b-1d2ni1) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6605)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

is this suitcss way of naming class?
</blockquote></details>

No, that is how you target placeholder text in html.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6623 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriRwtAlV48QJzt9k0c:-KriW90nvG1Q1mPkzDOP:bshgf6p) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6623)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This class can be made general to be reused, flex-grow1
</blockquote></details>

It needs to target the form-group for it to work in this case

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6627 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriS6-8HqCrDjqKWIAZ:-KriW1dQIun7fDzzwP-3:bu4v8b5) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6627)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This class can be made general to be reused, flex-grow1
</blockquote></details>

It is a different class to the one above and also needs to target the form group for it to work in this case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KriY-PLtE1_FaxlRnx-:b-erlk5v) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Can you explain why? I thought if there were some strings that need to be used they are best passed in as props like this. 
</blockquote></details>

I tried this btw by adding a list of constants but it then means that the priority drop down shows all of the options at once. I am shocking with using arrays so I think this is best left in someone elses hands unless you want to go through this with me when you are free.



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
Reviewed 1 of 4 files at r1, 1 of 4 files at r3.
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KriYPCaawB8LGc5xBSV:b-7jypuc) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Can you explain why? I thought if there were some strings that need to be used they are best passed in as props like this. 
</blockquote></details>

PropTypes of constant list of string should be extracted so that it can be reused by whichever component that calls it. See 
TMXExportModal#58

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6605 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriRrnYRsw-pxmKN31z:-KriZESQjp28q6aDo0fJ:b-7g6ozs) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6605)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

No, that is how you target placeholder text in html.
</blockquote></details>

should we start using suitcss standard for all new class?

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6623 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriRwtAlV48QJzt9k0c:-KriZVoMADk274wLKIh8:bar4nfc) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6623)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

It needs to target the form-group for it to work in this case
</blockquote></details>

but we can always have such general class. Dont need to locked down with form-group.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KriZkf_m08Lp_uL8LZd:b1ebhui) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

PropTypes of constant list of string should be extracted so that it can be reused by whichever component that calls it. See 
TMXExportModal#58
</blockquote></details>

Ok cheers, I shall look at that tomorrow. Thanks for giving me an example to look at.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6623 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriRwtAlV48QJzt9k0c:-KriZrOpLM7FEVP9rUuZ:bzca49f) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6623)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

but we can always have such general class. Dont need to locked down with form-group.
</blockquote></details>

true, but in this case I had to target .form-group .flex-grow1 to get it to work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6623 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriRwtAlV48QJzt9k0c:-Kri_Wxv8yQpSpZoVxJo:b-dvd82k) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6623)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

true, but in this case I had to target .form-group .flex-grow1 to get it to work
</blockquote></details>

I think its a better solution for reusability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6623 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriRwtAlV48QJzt9k0c:-KrileZX0QIqBqroGtBL:bbzvt7n) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6623)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think its a better solution for reusability.
</blockquote></details>

Ok, I will add the classes, although they aren't being used at the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6605 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriRrnYRsw-pxmKN31z:-KrirA8ZSrvFRY8RgFHD:bfsrlci) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/styles/style.less#L6605)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

should we start using suitcss standard for all new class?
</blockquote></details>

I would prefer to go through and do it all at once, still learning a bit about implementing it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KrmOaFzJ-ddbm1JBmUz:b-ob265n) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Ok cheers, I shall look at that tomorrow. Thanks for giving me an example to look at.
</blockquote></details>

#58 isn't related. Can you check the # again please @aeng 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KrmSKzTKI3enIll-hRZ:b-cakkqz) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
> TMXExportModal
https://github.com/zanata/zanata-platform/blob/master/server/zanata-frontend/src/frontend/app/components/TMX/TMXExportModal.js#L58

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KrmTgss9KBCTxixOj7C:br3nqmh) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

> TMXExportModal
https://github.com/zanata/zanata-platform/blob/master/server/zanata-frontend/src/frontend/app/components/TMX/TMXExportModal.js#L58
</blockquote></details>

Isn't that what I have done here?  I have done the *exact* thing as the line you linked me to.

Also, what else am I expected to do? The mapStateToProps stuff? The switch statement? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KrmVI9g0COuaYkpxZUZ:b-bvhmkw) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Isn't that what I have done here?  I have done the *exact* thing as the line you linked me to.

Also, what else am I expected to do? The mapStateToProps stuff? The switch statement? 
</blockquote></details>

The string "Minor", "Major" and "Critical" should be constants that can be reused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
Reviewed 1 of 4 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KrmW03PErtWRV2S-4jD:b-ezhoio) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

The string "Minor", "Major" and "Critical" should be constants that can be reused.
</blockquote></details>

This still does not help me understand what I need to do based on the code example you have given me. Lets leave this until we can talk in person.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KrmXZs_cGg6wdt_1_ry:b-fv5urt) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

This still does not help me understand what I need to do based on the code example you have given me. Lets leave this until we can talk in person.
</blockquote></details>

For now, above the line static PropTypes, put `const  MINOR = 'minor'`, `const MAJOR = 'MAJOR'`, `const CRITICAL = 'critical'`. Then `priority: PropTypes.oneOf ([MINOR, MAJOR, CRITICAL])`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KrmYDFooKyYGfoMx8M1:bb6un1j) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

For now, above the line static PropTypes, put `const  MINOR = 'minor'`, `const MAJOR = 'MAJOR'`, `const CRITICAL = 'critical'`. Then `priority: PropTypes.oneOf ([MINOR, MAJOR, CRITICAL])`
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-Krm_v57crOo0-Bw1bmg:b-dfdycw) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Done
</blockquote></details>

before the line `static PropTypes`, 
put 

const MINOR = 'minor' 
const MAJOR = 'MAJOR'
const CRITICAL = 'critical'


Then `priority: PropTypes.oneOf ([MINOR, MAJOR, CRITICAL])`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 10 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KriSG1E-903bBfv1_ZJ:-KrmjDUHC4iS0VALxTIx:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/9ff9efbfd9af2dd28fb5d195789718892cfaff45/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L10)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

before the line `static PropTypes`, 
put 

const MINOR = 'minor' 
const MAJOR = 'MAJOR'
const CRITICAL = 'critical'


Then `priority: PropTypes.oneOf ([MINOR, MAJOR, CRITICAL])`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 16 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-Krml13h0CamPvVcclQI:-Krml13ic4WPWbrbJfhT:bk5sof4) ([raw file](https://github.com/zanata/zanata-platform/blob/c49748715532b248defb812dcbbdbd3eaf9eb718/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L16)):*
> ```JavaScript
>     priority: PropTypes.oneOf([
>       'MINOR',
>       'MAJOR',
> ```

remove the single quote on these options to make it use the constant you declared above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 16 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-Krml13h0CamPvVcclQI:-KrmlEBADi9f-bWzTd7E:bsqktor) ([raw file](https://github.com/zanata/zanata-platform/blob/c49748715532b248defb812dcbbdbd3eaf9eb718/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L16)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

remove the single quote on these options to make it use the constant you declared above.
</blockquote></details>

priority: PropTypes.oneOf ([MINOR, MAJOR, CRITICAL]), without the single quote

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by kathryngo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 16 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-Krml13h0CamPvVcclQI:-Krmwvpb63IU7xLNxjmm:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/c49748715532b248defb812dcbbdbd3eaf9eb718/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L16)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

priority: PropTypes.oneOf ([MINOR, MAJOR, CRITICAL]), without the single quote
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-:-KrnDiYVj_0xSGlTRLpi:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 3 of 4 files at r6.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/RejectionsForm.test.js, line 28 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-KsHAFpHmDaLmvIZiqs_:-KsHAFpHmDaLmvIZiqsa:bh1g47v) ([raw file](https://github.com/zanata/zanata-platform/blob/7a12c954938e7206df50e4fa421c40ef94ba6fe2/server/zanata-frontend/src/frontend/app/components/RejectionsForm/RejectionsForm.test.js#L28)):*
> ```JavaScript
>         editable={false}
>         criteriaPlaceholder='Criteria here'
>         priority='Major' textState='text-warning'/>
> ```

The `priority` props needs to change to use the const?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/482#-:-KsHNQzcXc1WMOLzkHyF:bnfp4nl)*

**Pull request merged**
