### PR TITLE
fix(version group): update project search to use name

### PR DESCRIPTION
**Pull request by aeng**
JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1550*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

https://zanata.atlassian.net/browse/ZNTA-1550

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/84)

### CODE REVIEW

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/84#-:-KXhAGsxgdzWWMaRCaiA:bnfp4nl)*

**Comment by spathare21** [comment]
Verified

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@djansen-redhat is this "verified", or "testing needed"? The two labels don't seem compatible.

**Comment by djansen-redhat** [comment]
@seanf the build failed, so I put 'testing needed' on there to prevent accidental merge. The build has passed now.
@spathare21 @aeng However, I don't think this is the _right_ fix for this problem. Project names can be duplicated, so you could have 30 projects named 'Test' with 'master' version and you won't be able to determine which one is yours.
IMO the fix is to display the text like **ProjectName (projectId) [V] master**

**Comment by seanf** [comment]
> However, I don't think this is the right fix for this problem. Project names can be duplicated, so you could have 30 projects named 'Test' with 'master' version and you won't be able to determine which one is yours.
> IMO the fix is to display the text like `ProjectName (projectId) [V] master`

Good points, except `[V]` may not localise well, since it's an abbreviation for "version" in English. 

It's tricky to solve in a compact way. What about this?

`ProjectName (projectId) - master`

**Comment by spathare21** [comment]
Verified 
project_search

**Pull request merged**
