### PR TITLE
ZNTA-1837 frontend component stories

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1837

All of the frontend components I have created have been added to storybook. I have marked all of the issues as on review. 

Was not sure about some of the needed props for this (ie. the actions). I referred to the react-bootstrap manual where needed: https://react-bootstrap.github.io/components.html

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/281)

### CODE REVIEW

**Comment by davidmason** [comment]
Review status: 0 of 23 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/app/components/Icon/story.js, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-KiDyy13fuJ7KIBZPUdd:-KiDyy14vJckOOxK4aZk:b9dt3vp) ([raw file](https://github.com/zanata/zanata-platform/blob/12af0e7449d53c116980c5a898dd5f391ba7fb31/server/zanata-frontend/src/frontend/app/components/Icon/story.js#L7)):*
> ```JavaScript
> storiesOf('Icon', module)
>     .add('default', () => (
> <span>
> ```

There is loads of repetition here. We could get all sizes of all components without all the repetition. Something along these lines:

```
const allIconNames = ['admin', 'all', 'assign', ... 'zanata']

function renderIcon (name, size) {
  return <span title={name}> <Icon name={name} className={size} /> </span>
}

const size0Icons = allIconNames.map((name) => renderIcon(name, 's0')
const size1Icons = allIconNames.map((name) => renderIcon(name, 's1')

return (
  <div>
    <h2>Size 0</h2>
    {size0Icons}
    <h2>Size 1</h2>
    {size1Icons}
  </div>
)

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/281)*

**Comment by davidmason** [comment]
Review status: 0 of 23 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/app/components/Icon/story.js, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-KiDyy13fuJ7KIBZPUdd:-KiE05J8C5MznkMsvkou:b8sbwow) ([raw file](https://github.com/zanata/zanata-platform/blob/12af0e7449d53c116980c5a898dd5f391ba7fb31/server/zanata-frontend/src/frontend/app/components/Icon/story.js#L7)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

There is loads of repetition here. We could get all sizes of all components without all the repetition. Something along these lines:

```
const allIconNames = ['admin', 'all', 'assign', ... 'zanata']

function renderIcon (name, size) {
  return <span title={name}> <Icon name={name} className={size} /> </span>
}

const size0Icons = allIconNames.map((name) => renderIcon(name, 's0')
const size1Icons = allIconNames.map((name) => renderIcon(name, 's1')

return (
  <div>
    <h2>Size 0</h2>
    {size0Icons}
    <h2>Size 1</h2>
    {size1Icons}
  </div>
)

```
</blockquote></details>

I think the icon script generates a list of icon names somewhere too, so we shouldn't need to repeat those. Just figure out what file they end up in and import that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/281)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/components/Icon/story.js, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-KiDyy13fuJ7KIBZPUdd:-KiSC3BkxurtWOVBnbHa:bbm2ibr) ([raw file](https://github.com/zanata/zanata-platform/blob/12af0e7449d53c116980c5a898dd5f391ba7fb31/server/zanata-frontend/src/frontend/app/components/Icon/story.js#L7)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

I think the icon script generates a list of icon names somewhere too, so we shouldn't need to repeat those. Just figure out what file they end up in and import that.
</blockquote></details>

Done.

But I couldn't work out how exactly to import the list so I have just included the list of icons in the story file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/281)*

**Comment by davidmason** [comment]
Reviewed 2 of 23 files at r1, 1 of 4 files at r2.
Review status: 3 of 24 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/Alert/story.js, line 2 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-Kin3tJeJokEEguonkBa:-Kin3tJeJokEEguonkBb:b3of2tx) ([raw file](https://github.com/zanata/zanata-platform/blob/7c87ad691daf74fdaf876427a9886ccff910118b/server/zanata-frontend/src/frontend/app/components/Alert/story.js#L2)):*
> ```JavaScript
> import React from 'react'
> import { storiesOf, action } from '@kadira/storybook'
> ```

Importing action here, but not using it.

---

*[server/zanata-frontend/src/frontend/app/components/Label/story.js, line 2 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-Kin3HkUfEiS4gcSR7tK:-Kin3HkVW8_ZYZ0XH_0w:b-yfs00z) ([raw file](https://github.com/zanata/zanata-platform/blob/7c87ad691daf74fdaf876427a9886ccff910118b/server/zanata-frontend/src/frontend/app/components/Label/story.js#L2)):*
> ```JavaScript
> import React from 'react'
> import { storiesOf, action } from '@kadira/storybook'
> ```

Lots of these are importing `action` but not using it. Please go through and remove it from the import wherever it isn't used.

---

*[server/zanata-frontend/src/frontend/app/components/Label/story.js, line 23 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-Kin3XJfemh3JA2ISQZL:-Kin3XJfemh3JA2ISQZM:b-t2p4jp) ([raw file](https://github.com/zanata/zanata-platform/blob/7c87ad691daf74fdaf876427a9886ccff910118b/server/zanata-frontend/src/frontend/app/components/Label/story.js#L23)):*
> ```JavaScript
>     <Label bsStyle='success'>Success</Label>
>     <Label bsStyle='warning'>Warning</Label>
>     <Label bsStyle='danger'>Danger</Label>
> ```

Indentation not enough for these 5 lines.
I should really make sure the linter is running in storybook, I think it isn't right now - it would pick up all these little things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/281)*

**Comment by davidmason** [comment]
Reviewed 18 of 23 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/Button/story.js, line 50 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-Kin7039CCuTcgiDl7tq:-Kin703Abc8ojLwdCRUX:b-5orqfl) ([raw file](https://github.com/zanata/zanata-platform/blob/7c87ad691daf74fdaf876427a9886ccff910118b/server/zanata-frontend/src/frontend/app/components/Button/story.js#L50)):*
> ```JavaScript
>     <Button bsStyle='primary' bsSize='xsmall' onClick={action('onClick')}>
>     Extra small button</Button>
>     <Button bsSize='xsmall' onClick={action('onClick')}>Extra small button</Button>
> ```

Indentation is inconsistent here.

---

*[server/zanata-frontend/src/frontend/app/components/Icon/story.js, line 6 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-Kin94hMf4fBUWLMuUql:-Kin94hMf4fBUWLMuUqm:b-aliv3o) ([raw file](https://github.com/zanata/zanata-platform/blob/7c87ad691daf74fdaf876427a9886ccff910118b/server/zanata-frontend/src/frontend/app/components/Icon/story.js#L6)):*
> ```JavaScript
> import iconList from '../Icon/list'
> 
> const allIconNames = iconList
> ```

unnecessary, just use `iconList` below.

---

*[server/zanata-frontend/src/frontend/app/components/Icon/story.js, line 18 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-Kin9927Fp3G7mQPogZe:-Kin9927Fp3G7mQPogZf:bjbyapi) ([raw file](https://github.com/zanata/zanata-platform/blob/7c87ad691daf74fdaf876427a9886ccff910118b/server/zanata-frontend/src/frontend/app/components/Icon/story.js#L18)):*
> ```JavaScript
> const size2Icons = allIconNames.map((name) => renderIcon(name, 's2'))
> const size3Icons = allIconNames.map((name) => renderIcon(name, 's3'))
> const size4Icons = allIconNames.map((name) => renderIcon(name, 's4'))
> ```

Can make a little helper function that takes 'n2' or whichever and wraps this up, then use that function inline to make this briefer.

---

*[server/zanata-frontend/src/frontend/app/components/List/story.js, line 25 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-KinAEEE_8THQ2anVGEA:-KinAEEE_8THQ2anVGEB:bzcyy9n) ([raw file](https://github.com/zanata/zanata-platform/blob/7c87ad691daf74fdaf876427a9886ccff910118b/server/zanata-frontend/src/frontend/app/components/List/story.js#L25)):*
> ```JavaScript
>             Some body text</ListGroupItem>
>             <ListGroupItem header='Heading 2' href='#'>
>             Linked item</ListGroupItem>
> ```

Indentation inconsistent.

---

*[server/zanata-frontend/src/frontend/app/components/Panel/story.js, line 26 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-KinC316Pk8OflFwwIa1:-KinC317xP4nfZfyO-8L:b-7xnnsh) ([raw file](https://github.com/zanata/zanata-platform/blob/7c87ad691daf74fdaf876427a9886ccff910118b/server/zanata-frontend/src/frontend/app/components/Panel/story.js#L26)):*
> ```JavaScript
>     .add('success', () => (
> 
>         <Panel header='Panel header' bsStyle='success'>
> ```

Extra whitespace on this and the rest of these.

---

*[server/zanata-frontend/src/frontend/app/components/Tabs/story.js, line 44 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-KinCSy2d1Ux6wCTHXtY:-KinCSy2d1Ux6wCTHXtZ:b-ikbncm) ([raw file](https://github.com/zanata/zanata-platform/blob/7c87ad691daf74fdaf876427a9886ccff910118b/server/zanata-frontend/src/frontend/app/components/Tabs/story.js#L44)):*
> ```JavaScript
>           </Row>
>         </Tab.Container>
>         ))
> ```

indentation.

---

*[server/zanata-frontend/src/frontend/app/components/TextInput/story.js, line 19 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-KinCW-xXgJb-LWfLg7w:-KinCW-xXgJb-LWfLg7x:bbdhgck) ([raw file](https://github.com/zanata/zanata-platform/blob/7c87ad691daf74fdaf876427a9886ccff910118b/server/zanata-frontend/src/frontend/app/components/TextInput/story.js#L19)):*
> ```JavaScript
>     }}
> />
>     ))
> ```

indentation of all this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/281)*

**Comment by davidmason** [comment]
Reviewed 19 of 19 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/281)*

**Comment by davidmason** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/281#-:-KinN0YSlwoOuu_UoZNg:bnfp4nl)*

**Pull request merged**
