### PR TITLE
Added comprehensive test for language page

### PR DESCRIPTION
**Pull request by spathare21**
JIRA issue URL: *paste URL here*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/402)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[server/functional-test/src/main/java/org/zanata/page/languages/LanguagePage.java, line 55 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/402#-KnA13njmBX-TdHwDDC_:-KnA13nk9KQsue0sogNo:b-lsz2yx) ([raw file](https://github.com/zanata/zanata-platform/blob/c729c6d410fc4f5c3115aac48dbe35b0175ebeb6/server/functional-test/src/main/java/org/zanata/page/languages/LanguagePage.java#L55)):*
> ```Java
>     private By addSelectedButton = By.id("addSelectedBtn");
>     private By requestToJoinLanguage = By.xpath(".//button[contains(text(),'Request To Join')]");
>     private By cancelRequest = By.id("member-info:cancelRequest:j_idt94");
> ```

You can't use these j_id* tags - they are generated at compile time. You'll have to either locate the items a different way or add ids to them in their xhtml files.

---

*[server/functional-test/src/main/java/org/zanata/page/languages/RequestToJoinPage.java, line 32 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/402#-KnA0tVFiBV5VNSTGknz:-KnA0tVFiBV5VNSTGko-:b-gdqijo) ([raw file](https://github.com/zanata/zanata-platform/blob/c729c6d410fc4f5c3115aac48dbe35b0175ebeb6/server/functional-test/src/main/java/org/zanata/page/languages/RequestToJoinPage.java#L32)):*
> ```Java
>  *         href="mailto:spathare@redhat.com">spathare@redhat.com</a>
>  */
> public class RequestToJoinPage extends BasePage {
> ```

Is this a page, or a popup?

---

*[server/functional-test/src/main/java/org/zanata/page/languages/RequestToJoinPage.java, line 34 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/402#-KnA07DOW70AOlTY36aO:-KnA07DOW70AOlTY36aP:b-xaxcel) ([raw file](https://github.com/zanata/zanata-platform/blob/c729c6d410fc4f5c3115aac48dbe35b0175ebeb6/server/functional-test/src/main/java/org/zanata/page/languages/RequestToJoinPage.java#L34)):*
> ```Java
> public class RequestToJoinPage extends BasePage {
>     private static final org.slf4j.Logger log =
>             org.slf4j.LoggerFactory.getLogger(ContactTeamPage.class);
> ```

Incorrect class in getLogger

---

*[server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java, line 60 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/402#-KnA37Ctau5tDHHfUeE8:-KnA37Ctau5tDHHfUeE9:bw9p8d) ([raw file](https://github.com/zanata/zanata-platform/blob/c729c6d410fc4f5c3115aac48dbe35b0175ebeb6/server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java#L60)):*
> ```Java
>     }
> 
>     @Trace(summary = "Translator can search for language")
> ```

Add the numerical ZAN id from the test spec as 'testIds = (num)'

---

*[server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java, line 74 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/402#-KnA3L5FYKDXXVXyz43j:-KnA3L5FYKDXXVXyz43k:bw9p8d) ([raw file](https://github.com/zanata/zanata-platform/blob/c729c6d410fc4f5c3115aac48dbe35b0175ebeb6/server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java#L74)):*
> ```Java
>     }
> 
>     @Trace(summary = "Translator can request to join language team")
> ```

Add the numerical ZAN id from the test spec as 'testIds = (num)'

---

*[server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java, line 111 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/402#-KnA3PKactLSVTzDCWDP:-KnA3PKactLSVTzDCWDQ:bw9p8d) ([raw file](https://github.com/zanata/zanata-platform/blob/c729c6d410fc4f5c3115aac48dbe35b0175ebeb6/server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java#L111)):*
> ```Java
>     }
> 
>     @Trace(summary = "Translator can cancel request")
> ```

Add the numerical ZAN id from the test spec as 'testIds = (num)'

---

*[server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java, line 141 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/402#-KnA3TGgw2H2Ng61Rx4v:-KnA3TGgw2H2Ng61Rx4w:boc42bj) ([raw file](https://github.com/zanata/zanata-platform/blob/c729c6d410fc4f5c3115aac48dbe35b0175ebeb6/server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java#L141)):*
> ```Java
>         assertThat(languagePage.getNotificationMessage())
>                 .contains("You have left the français language team")
>                 .as("Leaved language team " + language);
> ```

The user has left...
Could also check that the user is no longer in the list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/402)*

**Comment by spathare21** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java, line 60 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/402#-KnA37Ctau5tDHHfUeE8:-KnAYq-B81bIVF9o3gk-:blsjjc7) ([raw file](https://github.com/zanata/zanata-platform/blob/c729c6d410fc4f5c3115aac48dbe35b0175ebeb6/server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java#L60)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Add the numerical ZAN id from the test spec as 'testIds = (num)'
</blockquote></details>

do you mean to add add like this  "testPlanIds = 5681, testCaseIds = {5689}" in @trace and testCaseIds have to take from polarion ? what if there is not such test case ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/402)*

**Comment by spathare21** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[server/functional-test/src/main/java/org/zanata/page/languages/RequestToJoinPage.java, line 32 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/402#-KnA0tVFiBV5VNSTGknz:-KnAZiI_I1pZ7iNZwhbG:b-1wim8v) ([raw file](https://github.com/zanata/zanata-platform/blob/c729c6d410fc4f5c3115aac48dbe35b0175ebeb6/server/functional-test/src/main/java/org/zanata/page/languages/RequestToJoinPage.java#L32)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Is this a page, or a popup?
</blockquote></details>

added as RequestToJoinPopup

---

*[server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java, line 141 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/402#-KnA3TGgw2H2Ng61Rx4v:-KnAZcUQdcpY9S7k7XBM:bgj3hxt) ([raw file](https://github.com/zanata/zanata-platform/blob/c729c6d410fc4f5c3115aac48dbe35b0175ebeb6/server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java#L141)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

The user has left...
Could also check that the user is no longer in the list.
</blockquote></details>

like this assertThat(languagePage.getMemberUsernames())
                .doesNotContain("translator")
                .as("Now translator is not a member of "+ language + "tram");

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/402)*

**Comment by djansen-redhat** [comment]
Reviewed 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/402)*

**Pull request merged**
