### PR TITLE
GWT editor module

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1449

GWT client code lives in its own module so that we can skip building it when there is no change in there.
## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.
- Code quality
  - [ ] Code passes style check (checkstyle/eslint)
  - [ ] Code is clear and concise
  - [ ] UI code is internationalised
  - [ ] Code has adequate comments where appropriate
  - Code is in an appropriate place
    - [ ] Classes are in appropriate packages
    - [ ] Code fits with class's responsibilities (SRP)
  - [ ] Configuration files are documented enough
  - If code is removed
    - [ ] No remaining code references the removed code
      - [ ] No orphaned rewrite rules
    - [ ] No orphaned config settings
    - [ ] No remaining comments refer to the removed code
    - [ ] Unused imports and libraries are removed
- Testing
  - [ ] New code has tests
  - [ ] Changed code has tests
  - [ ] All tests pass
  - [ ] Test coverage stable or increased
- Documentation
  - [ ] New features are documented
  - [ ] Docs removed for deleted features
  - [ ] Docs updated for all changed features
  - [ ] Developer/sysadmin docs updated if appropriate
- If there are new dependencies
  - [ ] Does each new dependency pass all the
     [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?
---

_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/9)

### CODE REVIEW

**Comment by huangp** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
Please don't duplicate CoverageIgnore.java. I think you should be able to consume it from gwt-editor in zanata-war.

**Comment by seanf** [comment]
Reviewed 1155 of 1155 files at r1.
Review status: 565 of 601 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/pom.xml, line 1848 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOJHTely17f6ciKSe1:-KVOJHTf7WwexLyK_Spv:bb5gb0c) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/pom.xml#L1848)):*
> ```XML
>                 <echo message="DISPLAY=${env.DISPLAY}"/>
>                 <echo message="WARNING: 'appserver' property must be set unless skipping integration tests" unless:set="appserver"/>
>                 <echo message="WARNING: 'cargo.installation' property is null. You might need to set the env var EAP7_URL" unless:set="cargo.installation"/>
> ```

Why did this whitespace change? I've noticed a few other whitespace changes which are making the review process more difficult that it needs to be.

---

*[server/gwt-editor/src/main/resources/org/zanata/webtrans/public/codemirror/codemirror-compressed-3.21.cache.js, line 0 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOJwlPtZ0DsVOXhgta:-KVOJwlPtZ0DsVOXhgtb:b-lfa4um) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/gwt-editor/src/main/resources/org/zanata/webtrans/public/codemirror/codemirror-compressed-3.21.cache.js#L0)):*
This file appears to have a whitespace change (probably added the missing newline at the end), but it is just adding another blob into git. Please don't reformat unchanged files!

---

*[server/zanata-war/pom.xml, line 2104 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOKWilNbGdBVadXQT8:-KVOKWilNbGdBVadXQT9:bpp8385) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/zanata-war/pom.xml#L2104)):*
> ```XML
>     </dependency>
> 
>     
> ```

Should this start with "This dependency is needed"?

---

*[server/zanata-war/pom.xml, line 2305 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOK_jd1epW1A7J94tD:-KVOK_jd1epW1A7J94tE:b-9v0iyx) ([raw file](https://github.com/zanata/zanata-platform/blob/66da6f81b694f283b5c7ace0b1c07a154d25b385/server/zanata-war/pom.xml#L2305)):*
> ```XML
>     
>     
> ```

I think this comment is still important. In fact, we should probably make sure gwt-editor is at the end of the list, to help keep all GWT dependencies at the end of the classpath.

---

*[server/zanata-war/src/main/java/org/zanata/action/VersionGroupJoinAction.java, line 253 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOJe1cZb2exafJB2Qm:-KVOJe1do1Mafm9gOblj:b-n21b9g) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/zanata-war/src/main/java/org/zanata/action/VersionGroupJoinAction.java#L253)):*
> ```Java
> 
>     // TODO this is using a GWT shared class and should change to something else
>     public final class SelectableVersion extends ProjectIterationId {
> ```

What's wrong with that? We want to share code, not duplicate it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/9)*

**Comment by seanf** [comment]
Reviewed 34 of 1155 files at r1, 34 of 35 files at r3.
Review status: 599 of 601 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/gwt-editor/pom.xml, line 295 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOXtzl20NspuNtpjB-:-KVOXtzl20NspuNtpjB0:bnzo3a9) ([raw file](https://github.com/zanata/zanata-platform/blob/04d7cd6ce886ad4f0c45d44c73ae899bd545bf37/server/gwt-editor/pom.xml#L295)):*
> ```XML
>             </goals>
>             <configuration>
>               <outputDirectory>${project.build.outputDirectory}/${project.artifactId}</outputDirectory>
> ```

We should try packaging this content (GWT-generated .js files, sourceMaps, etc) using the `maven-war-plugin`, and packaging the .class files as jars using the `archiveClasses` option.

---

*[server/gwt-editor/pom.xml, line 315 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOXhlZXdSVFTKPk5qK:-KVOXhlZXdSVFTKPk5qL:b5nxspd) ([raw file](https://github.com/zanata/zanata-platform/blob/04d7cd6ce886ad4f0c45d44c73ae899bd545bf37/server/gwt-editor/pom.xml#L315)):*
> ```XML
>           <includes>
>             <include>**/*</include>
>             <include>${project.artifactId}-${project.version}/**</include>
> ```

This doesn't seem to do anything.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 31 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVONz56wndqqJZ7OJBe:-KVONz56wndqqJZ7OJBf:bklkhp8) ([raw file](https://github.com/zanata/zanata-platform/blob/04d7cd6ce886ad4f0c45d44c73ae899bd545bf37/server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L31)):*
> ```Java
>     @CoverageIgnore("JSNI")
>     public static native void syntaxHighlight(String text, Element elem)
>         /*-{
> ```

We should probably have changed the checkstyle rules to handle JSNI cases like this. I notice that the new version is sometimes indented, sometimes not. But it doesn't really matter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/9)*

**Comment by huangp** [comment]
done

---

Review status: 562 of 601 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/pom.xml, line 1848 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOJHTely17f6ciKSe1:-KVS8BcYvq9TWXZ8FpEC:bwp1cg3) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/pom.xml#L1848)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Why did this whitespace change? I've noticed a few other whitespace changes which are making the review process more difficult that it needs to be.
</details>
I ran mvn archetype:generate to add the new module. It must have modify the indentation somehow. Fixed.

---

*[server/gwt-editor/pom.xml, line 295 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOXtzl20NspuNtpjB-:-KVSayv4lNrKOfJtRO-E:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/04d7cd6ce886ad4f0c45d44c73ae899bd545bf37/server/gwt-editor/pom.xml#L295)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> We should try packaging this content (GWT-generated .js files, sourceMaps, etc) using the `maven-war-plugin`, and packaging the .class files as jars using the `archiveClasses` option.
</details>
Done.

---

*[server/gwt-editor/src/main/resources/org/zanata/webtrans/public/codemirror/codemirror-compressed-3.21.cache.js, line  at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOJwlPtZ0DsVOXhgta:-KVSZunhqVFDceqvBZBi:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/gwt-editor/src/main/resources/org/zanata/webtrans/public/codemirror/codemirror-compressed-3.21.cache.js#L)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> This file appears to have a whitespace change (probably added the missing newline at the end), but it is just adding another blob into git. Please don't reformat unchanged files!
</details>
Done.

---

*[server/zanata-war/pom.xml, line 2104 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOKWilNbGdBVadXQT8:-KVSZrVP9lNhcDz2e-vm:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/zanata-war/pom.xml#L2104)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Should this start with "This dependency is needed"?
</details>
Done.

---

*[server/zanata-war/pom.xml, line 2305 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOK_jd1epW1A7J94tD:-KVSZxig4VGOP7rE7CIg:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/66da6f81b694f283b5c7ace0b1c07a154d25b385/server/zanata-war/pom.xml#L2305)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I think this comment is still important. In fact, we should probably make sure gwt-editor is at the end of the list, to help keep all GWT dependencies at the end of the classpath.
</details>
Done.

---

*[server/zanata-war/src/main/java/org/zanata/action/VersionGroupJoinAction.java, line 253 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOJe1cZb2exafJB2Qm:-KVSa1Of_tEm0XMsrt3z:bo2hju5) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/zanata-war/src/main/java/org/zanata/action/VersionGroupJoinAction.java#L253)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> What's wrong with that? We want to share code, not duplicate it.
</details>
It means once we replace GWT editor with the pure javascript editor, this class won't compile anymore. I found this out when I remove gwt-servlet dependency from zanata-war. I guess no need to put a TODO since if we remove gwt dep, it will show up as compilation error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-:-KVSb0p3c_M05wl6nPKD:bb7f2mf)*

**Comment by seanf** [comment]
Reviewed 35 of 1156 files at r1, 35 of 36 files at r6, 1 of 2 files at r7, 34 of 35 files at r8, 6 of 7 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/action/VersionGroupJoinAction.java, line 253 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOJe1cZb2exafJB2Qm:-KVSvr7PHQ8PwsKZpgIG:b-dvqzgs) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/zanata-war/src/main/java/org/zanata/action/VersionGroupJoinAction.java#L253)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> It means once we replace GWT editor with the pure javascript editor, this class won't compile anymore. I found this out when I remove gwt-servlet dependency from zanata-war. I guess no need to put a TODO since if we remove gwt dep, it will show up as compilation error.
</details>
Yes, and if we still need the class at that time, we can just refactor it to a different package if necessary.

Is the shared class in question GWT's IsSerializable annotation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/9)*

**Comment by huangp** [comment]
Review status: 600 of 601 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/action/VersionGroupJoinAction.java, line 253 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOJe1cZb2exafJB2Qm:-KVT4M33FJjIllR0P9z-:bomrot5) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/zanata-war/src/main/java/org/zanata/action/VersionGroupJoinAction.java#L253)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Yes, and if we still need the class at that time, we can just refactor it to a different package if necessary.
> 
> Is the shared class in question GWT's IsSerializable annotation?
</details>
Not an annotation but an interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/9)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1156 files at r1, 1 of 7 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/gwt-editor/src/main/resources/org/zanata/webtrans/public/codemirror/codemirror-compressed-3.21.cache.js, line  at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOJwlPtZ0DsVOXhgta:-KVT5gUVf8tbnATAVWmL:b-tsz16q) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/gwt-editor/src/main/resources/org/zanata/webtrans/public/codemirror/codemirror-compressed-3.21.cache.js#L)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Done.
</details>
Okay. That last commit 07ee473965700ec8b33b1e56600be9214225470d has indeed reverted to the original MD5 for that file.

d7ad1973a526ee253f615f84ba47b412  server/zanata-war/src/main/resources/org/zanata/webtrans/public/codemirror/codemirror-compressed-3.21.cache.js

---

*[server/zanata-war/src/main/java/org/zanata/action/VersionGroupJoinAction.java, line 253 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVOJe1cZb2exafJB2Qm:-KVT5NwqEFU3Qxj6Uu9y:bhpwu4a) ([raw file](https://github.com/zanata/zanata-platform/blob/a3dd2576f6ae8eaf0ce5e5c8b26338334e994e02/server/zanata-war/src/main/java/org/zanata/action/VersionGroupJoinAction.java#L253)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Not an annotation but an interface.
</details>
Okay, so we'll just have to remove such references to IsSerializable when the time comes to remove GWT.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-:-KVT6C_WZRhh57z6uHdU:bnfp4nl)*

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
866fileschanged

**Comment by seanf** [comment]
@huangp Were there many merge conflicts? Do we need another review?

**Comment by seanf** [comment]
*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/UncaughtExceptionHandlerImpl.java, line 121 at r13](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVhnS3iiALLFTRemMRh:-KVhnS3iiALLFTRemMRi:b-d7fjh8) ([raw file](https://github.com/zanata/zanata-platform/blob/e70dc7b743e438d58bea2a48b66e835321bc64f7/server/gwt-editor/src/main/java/org/zanata/webtrans/client/UncaughtExceptionHandlerImpl.java#L121)):*
> ```Java
>         disclosurePanel.getHeader().getParent().setStyleName(""); // conflict
>                                                                   // style from
>                                                                   // menu.css
> ```

Did this change back?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/9)*

**Comment by huangp** [comment]
Only 2 conflicts (One is in SearchResultPresenter where you have changed to lambda and I have change some trailing comment). The other one is zanata-war pom file. You added the java 8 memory args which I need to move to gwt-editor module. I do need to add validator-api to gwt-editor module as provided scope after merge.  Maybe it's removed from a transitive dep after the version upgrade. 

---

Review status: 0 of 607 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/UncaughtExceptionHandlerImpl.java, line 121 at r13](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVhnS3iiALLFTRemMRh:-KVhpsixM_k1mA3BKhVP:bypyvi3) ([raw file](https://github.com/zanata/zanata-platform/blob/e70dc7b743e438d58bea2a48b66e835321bc64f7/server/gwt-editor/src/main/java/org/zanata/webtrans/client/UncaughtExceptionHandlerImpl.java#L121)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Did this change back?
</details>
I don't know what are you referring to. The final result is the comment is above the code (no trailing comment).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-:-KVhqS9ebwNbUAljak7b:b572dwc)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 11 of 1156 files at r1, 12 of 1157 files at r13, 6 of 1157 files at r15.
Review status: 3 of 607 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/UncaughtExceptionHandlerImpl.java, line 121 at r13](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-KVhnS3iiALLFTRemMRh:-KVhrcprjn08nrQRJ4B1:b-em4ayb) ([raw file](https://github.com/zanata/zanata-platform/blob/e70dc7b743e438d58bea2a48b66e835321bc64f7/server/gwt-editor/src/main/java/org/zanata/webtrans/client/UncaughtExceptionHandlerImpl.java#L121)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> I don't know what are you referring to. The final result is the comment is above the code (no trailing comment).
</details>
I guess it was just Reviewable being confusing in commit-by-commit mode, again. Looks okay now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/9#-:-KVhr_Iah2Bh0FJaDm9H:bnfp4nl)*

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by huangp** [comment]
note this PR has merged in #32

**Comment by djansen-redhat** [comment]
:+1:

**Pull request merged**
