### PR TITLE
ZNTA-2215 - review criteria in gwt editor

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2215

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/604)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 28 of 32 files at r2.
Review status: 26 of 30 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/ForceReviewCommentPresenter.java, line 64 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/604#-KyTf3usxWdGAuePFtv2:-KyTf3usxWdGAuePFtv3:bbbdf6s) ([raw file](https://github.com/zanata/zanata-platform/blob/4fb0111832da924c93b71be5e7972f0917a49fc4/server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/ForceReviewCommentPresenter.java#L64)):*
> ```Java
>     private TransUnitSaveEvent saveEvent;
>     private ReviewCriterionId reviewCriterionId;
>     private boolean reviewCriteriaInitialized = false;
> ```

Can we force initialise this in the constructor?

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/TranslationHistoryPresenter.java, line 148 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/604#-KyTfeaS736t92_A8C4g:-KyTfeaS736t92_A8C4h:babvioo) ([raw file](https://github.com/zanata/zanata-platform/blob/4fb0111832da924c93b71be5e7972f0917a49fc4/server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/TranslationHistoryPresenter.java#L148)):*
> ```Java
>     @Override
>     public void addComment(String commentContent) {
>         if (Strings.isNullOrEmpty(commentContent) || commentContent.trim().length() == 0) {
> ```

I think isNullOrEmpty already check for trim().length == 0?

---

*[server/services/src/main/java/org/zanata/rest/review/ReviewService.java, line 88 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/604#-KyTgzxgeYlMh8S0qORK:-KyTgzxgeYlMh8S0qORL:blxbvsy) ([raw file](https://github.com/zanata/zanata-platform/blob/4fb0111832da924c93b71be5e7972f0917a49fc4/server/services/src/main/java/org/zanata/rest/review/ReviewService.java#L88)):*
> ```Java
>                 new ReviewCriteria(criteria.getPriority(),
>                         criteria.isEditable(), criteria.getDescription());
>         reviewCriteriaDAO.makePersistent(reviewCriteria);
> ```

Do we check for duplication?

---

*[server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetReviewComment.java, line 115 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/604#-KyThSBCW8nvR4Gp95-m:-KyThSBCW8nvR4Gp95-n:b-mfeosi) ([raw file](https://github.com/zanata/zanata-platform/blob/4fb0111832da924c93b71be5e7972f0917a49fc4/server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetReviewComment.java#L115)):*
> ```Java
> 
>     private String joinUserComment() {
>         if (Strings.isNullOrEmpty(comment) || comment.trim().length() == 0) {
> ```

Strings.isNullOrEmpty should covers the .trim().length check already?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/604)*

**Comment by huangp** [comment]
Review status: 26 of 30 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/ForceReviewCommentPresenter.java, line 64 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/604#-KyTf3usxWdGAuePFtv2:-KyTiO4vF0Y0dcLSinNx:b-syp4p1) ([raw file](https://github.com/zanata/zanata-platform/blob/4fb0111832da924c93b71be5e7972f0917a49fc4/server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/ForceReviewCommentPresenter.java#L64)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Can we force initialise this in the constructor?
</blockquote></details>

No we can't. I explained it in the method comment below. This presenter is not referenced by any other presenter so it has to be created as *eager* singleton. At the time of creation, userWorkspaceContext is not yet returned from the server.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/TranslationHistoryPresenter.java, line 148 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/604#-KyTfeaS736t92_A8C4g:-KyTikU0KptL2IExtqDc:b-p4pfc4) ([raw file](https://github.com/zanata/zanata-platform/blob/4fb0111832da924c93b71be5e7972f0917a49fc4/server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/TranslationHistoryPresenter.java#L148)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think isNullOrEmpty already check for trim().length == 0?
</blockquote></details>

If the value is several space, it's not empty, but after trim the length will be 0. 

---

*[server/services/src/main/java/org/zanata/rest/review/ReviewService.java, line 88 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/604#-KyTgzxgeYlMh8S0qORK:-KyThuLWyCQDZzvDhiSQ:bhh7f5m) ([raw file](https://github.com/zanata/zanata-platform/blob/4fb0111832da924c93b71be5e7972f0917a49fc4/server/services/src/main/java/org/zanata/rest/review/ReviewService.java#L88)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we check for duplication?
</blockquote></details>

This is a POST for adding new ones only. There is a PUT for editing existing one. We don't really check for duplication. No definition or requirement for duplicate criteria.

---

*[server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetReviewComment.java, line 115 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/604#-KyThSBCW8nvR4Gp95-m:-KyTiDdd9Tmq9w4Kxyu0:biq8zda) ([raw file](https://github.com/zanata/zanata-platform/blob/4fb0111832da924c93b71be5e7972f0917a49fc4/server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetReviewComment.java#L115)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Strings.isNullOrEmpty should covers the .trim().length check already?
</blockquote></details>

Explained above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/604)*

**Comment by aeng** [comment]
Reviewed 2 of 32 files at r2.
Review status: 28 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/rest/review/ReviewService.java, line 88 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/604#-KyTgzxgeYlMh8S0qORK:-KyTkPpbpWgdczvMzkYJ:b8qh39b) ([raw file](https://github.com/zanata/zanata-platform/blob/4fb0111832da924c93b71be5e7972f0917a49fc4/server/services/src/main/java/org/zanata/rest/review/ReviewService.java#L88)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

This is a POST for adding new ones only. There is a PUT for editing existing one. We don't really check for duplication. No definition or requirement for duplicate criteria.
</blockquote></details>

I guess it should safe for now since it is only available to admin. Do you think we should impleent some basic check? with same desc?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/604)*

**Comment by huangp** [comment]
Review status: 28 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/rest/review/ReviewService.java, line 88 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/604#-KyTgzxgeYlMh8S0qORK:-KyTlWNvQmR2MaMEk_YP:biw154) ([raw file](https://github.com/zanata/zanata-platform/blob/4fb0111832da924c93b71be5e7972f0917a49fc4/server/services/src/main/java/org/zanata/rest/review/ReviewService.java#L88)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I guess it should safe for now since it is only available to admin. Do you think we should impleent some basic check? with same desc?
</blockquote></details>

database unique constraint will create indexes. Not worth the cost IMO. It's only for admin and the total number of entries is probably less than 20.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/604)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 32 files at r2.
Review status: 29 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/604#-:-KyTmCdTaCyOUb95UDAB:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 1 of 32 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/604)*

**Pull request merged**
