### PR TITLE
feat(ZNTA-2635): editor validators error behavior

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2635

The Alpha Editor should implement some UI behavior when validation errors are detected.

* Set the default save as status to needswork
* Open a confirmation modal when using key commands to save (ALT+ENTER) or navigate away (ALT+KEYUP/KEYDOWN)
* Display an error indicating icon in the transunit status bar for transunits with detected errors
* Hide the validators information panel when a textflow is not selected (as the status bar will indicate errors)

savewitherrors

validatorserrorstatus

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 5 of 22 files at r2.
Review status: 5 of 23 files reviewed, 2 unresolved discussions (waiting on @efloden and @aeng)

---

*[server/zanata-frontend/src/app/editor/actions/key-shortcuts-actions.js, line 243 at r2](https://reviewable.io/reviews/zanata/zanata-platform/924#-LGTG2ZM9DrD7MqecrNj:-LGTG2ZNC58FW-yOaKzt:b32189r) ([raw file](https://github.com/zanata/zanata-platform/blob/84c6236f33ee4a0f3071ed1d6041291fd3b62531/server/zanata-frontend/src/app/editor/actions/key-shortcuts-actions.js#L243)):*
> ```JavaScript
>           if (phrase.errors) {
>             dispatch(toggleSaveErrorModal(phrase.id, true))
>             return
> ```

is the `return` statement required?

---

*[server/zanata-frontend/src/app/editor/components/ValidationErrorsModal/index.tsx, line 102 at r2](https://reviewable.io/reviews/zanata/zanata-platform/924#-LGTGpRdCxsjZXXZ03JK:-LGTGpRdCxsjZXXZ03JL:b-9sja5z) ([raw file](https://github.com/zanata/zanata-platform/blob/84c6236f33ee4a0f3071ed1d6041291fd3b62531/server/zanata-frontend/src/app/editor/components/ValidationErrorsModal/index.tsx#L102)):*
> ```XML
> }
> 
> export default ValidaitonErrorsModal
> ```

typo, validation?

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/924)*

**Comment by aeng** [comment]
Reviewed 1 of 13 files at r1, 12 of 22 files at r2.
Review status: 18 of 23 files reviewed, 2 unresolved discussions (waiting on @efloden and @aeng)

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/924)*

**Comment by aeng** [comment]
Reviewed 1 of 22 files at r2.
Review status: 19 of 23 files reviewed, 2 unresolved discussions (waiting on @efloden and @aeng)

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/924)*

**Comment by aeng** [comment]
Reviewed 2 of 22 files at r2.
Review status: 21 of 23 files reviewed, 2 unresolved discussions (waiting on @efloden and @aeng)

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/924)*

**Comment by efloden** [comment]
Review status: 21 of 23 files reviewed, 2 unresolved discussions (waiting on @efloden and @aeng)

---

*[server/zanata-frontend/src/app/editor/actions/key-shortcuts-actions.js, line 243 at r2](https://reviewable.io/reviews/zanata/zanata-platform/924#-LGTG2ZM9DrD7MqecrNj:-LGTPK-g-jqJhYmwp_Wz:btjxjuo) ([raw file](https://github.com/zanata/zanata-platform/blob/84c6236f33ee4a0f3071ed1d6041291fd3b62531/server/zanata-frontend/src/app/editor/actions/key-shortcuts-actions.js#L243)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

is the `return` statement required?
</blockquote></details>

It prevented the `dispatch(operation())` outside of the if block, which moves to the next textflow
Refactored and commented this block to make the logic clearer

---

*[server/zanata-frontend/src/app/editor/components/ValidationErrorsModal/index.tsx, line 102 at r2](https://reviewable.io/reviews/zanata/zanata-platform/924#-LGTGpRdCxsjZXXZ03JK:-LGTS6MgB9xvYyLVx49M:b-ac4n1v) ([raw file](https://github.com/zanata/zanata-platform/blob/84c6236f33ee4a0f3071ed1d6041291fd3b62531/server/zanata-frontend/src/app/editor/components/ValidationErrorsModal/index.tsx#L102)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

typo, validation?
</blockquote></details>

Ah yes, fixed

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/924)*

**Pull request merged**
