### PR TITLE
 perf(ZNTA-2459): improve activity panel / translationinfo panel performance

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2459

The Activity Panel can renders all Translation History items including revisions and comments.

If a single textflow has a significant amount of work done on it, rendering all of its Activity items can cause performance issues.
Though this will not generally be the case for most trans units, it presents some user experience problems as the translation history is fetched when moving to a new text flow, creating revisions and comments.

We should also limit unnecessary calls to fetchTranslationHistory when new revisions or comments are created if the Activity Panel is not displayed ( When the Glossary Panel is selected or the sidebar is hidden entirely).

1. Paginate the Activity Panel's Translation History items, re-using the Pager component.
pagination
2. Track and display the visible state of the Activity Panels Tab in the Control Header.
controlsheader
3. Create a condition to only call fetchTranslationHistory if the Activity Panel is active.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by efloden** [comment]
Review status: 13 of 17 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/app/editor/components/Pager/index.js, line 85 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/771#-LAjcxIB-CAZSfNyoSbk:-LAk9faHCkfQ3Z5cSF-G:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/b781f34243cfca9a4ffcabe4367fc5fd40ddf1aa/server/zanata-frontend/src/app/editor/components/Pager/index.js#L85)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Remove this line if it is not used anymore.
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx, line 2 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/771#-LAjd6KG4oYrOxia42Bv:-LAk7Tg68TefRq1ew1ZP:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/b781f34243cfca9a4ffcabe4367fc5fd40ddf1aa/server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx#L2)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Remove this line if it is not used anymore
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx, line 28 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/771#-LAjdBMH6PHoYF86duAU:-LAk9QU55ejEBQH-Ny0Q:b-qa2uh9) ([raw file](https://github.com/zanata/zanata-platform/blob/b781f34243cfca9a4ffcabe4367fc5fd40ddf1aa/server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx#L28)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Remove this section if it is not used anymore
</blockquote></details>

Done. Changed the function signature to return the ActivityItem type defined in activity-util.ts

---

*[server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx, line 39 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/771#-LAjdFNG-gKD4BcbyGDw:-LAk9OO-BVDL2NiG1X2V:b-uk8umo) ([raw file](https://github.com/zanata/zanata-platform/blob/b781f34243cfca9a4ffcabe4367fc5fd40ddf1aa/server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx#L39)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This should be some sort of enum
</blockquote></details>

Using an activityTypes enum defined in activity-util.ts now

---

*[server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx, line 52 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/771#-LAjdKytD0jElc5vPbCG:-LAk9PP23tY39eComj6P:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/b781f34243cfca9a4ffcabe4367fc5fd40ddf1aa/server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx#L52)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This should be some sort of enum
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx, line 65 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/771#-LAjdNpvAsP6ir5efjKO:-LAk9MLt0oeO4dxdxk8y:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/b781f34243cfca9a4ffcabe4367fc5fd40ddf1aa/server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx#L65)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This should be some sort of enum
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/DetailsPane.tsx, line 36 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/771#-LAjdtoq96vOVgxSQSqG:-LAk97HI5hoTazXVRDVq:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/b781f34243cfca9a4ffcabe4367fc5fd40ddf1aa/server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/DetailsPane.tsx#L36)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Can be simplify with `const modifiedByIcon = isUndefined(lastModifiedBy) && <Icon name="user" className="n1" />`
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js, line 80 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/771#-LAjeLXg2Vb7wPA3GGtK:-LAkDhjW2Sp-XLcQzsou:bqj4x34) ([raw file](https://github.com/zanata/zanata-platform/blob/b781f34243cfca9a4ffcabe4367fc5fd40ddf1aa/server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/index.js#L80)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we have cases where the key can be activityTab and glossaryKey? maybe `if else` check?
</blockquote></details>

The key would be which tab to select, so it shouldn't correspond to both tabs - but I've gated it in an if else to be sure

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/771)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/771#-:-LAkTDJQ-LQ8XNxdFfDr:bnfp4nl)*

**Comment by spathare21** [comment]
@efloden activity panel pagination works fine but looks like here is build failure

**Comment by spathare21** [comment]
@efloden still build shows a failure on GitHub is it a configuration issue?

**Comment by efloden** [comment]
@spathare21 I'm not sure, I ran another Jenkins build which has passed and I can see the confirmation in Github

**Comment by djansen-redhat** [comment]
screenshot from 2018-05-01 14-12-47

Pagination should not show "1 of " when there is nothing to show. It should be "1 of 1", "None" or similar.
Arguably, it shouldn't show pagination _at all_ when there are less then two pages.

**Comment by spathare21** [comment]
@efloden looks fine now as per Damian comment, I think its good to have edit/delete comment option also, if wrongly commented

**Comment by djansen-redhat** [comment]
@spathare21 an edit/delete comment option would be great, but in a different PR. If you're happy with this one, feel free to label it verified :+1:

**Pull request merged**
