### PR TITLE
fix(ZNTA-2312) props for Icon component

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2312

- Props for Icon component corrected so className is used everywhere instead of size
- Updated snapshot tests
- Fixed alignment and size of notification modal icons

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/640)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/640#-:-L1tPr4NuIb8GpVtq6ZK:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo gravatar icon is not displaying on dashboard and setting page 

with PR merge

screenshot from 2018-01-03 11-08-32

without pr merge 

screenshot from 2018-01-03 11-21-44

**Comment by kathryngo** [comment]
@spathare21 odd, shall look at what is going on here. Thanks for picking that up.

**Comment by kathryngo** [comment]
@spathare21 Hmm, please try again. I think it may have been a problem with the gravatar servers. I cannot replicate your problem.
I will see if @djansen-redhat can replicate it also.

**Comment by spathare21** [comment]
Thanks @kathryngo it's working fine now may it was gravatar server issue.

**Pull request merged**
