### PR TITLE
Add settings component with a few settings (ZNTA-1927)

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1927

 - Adds settings icon that will show/hide the settings panel on the right
 - Adds settings:
   - Whether the suggestions panel is open (implicit setting, not shown on settings panel)
   - Enter key saves immediately (explicit setting, shown on settings panel)

Expected settings panel behaviour: show/hide toggle when you click the gear icon. Sidebar should keep its prior open or closed state. Clicking any info/glossary icon will hide settings and show sidebar.

## Tester Notes
Changes the behaviour of how the sidebar opens (glossary/info/etc.), so probably want to toggle all those panels with the icons at the top right, and under textflows (glossary icon).

*Reviewer note: there is a test of using Flow in this PR, and some restructuring to allow settings to be taken into account in a few parts of the app. I highly recommend pairing in person or with screenshare for the review so I can immediately answer questions about the changes.*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/524)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 49 of 162 files at r1.
Review status: 49 of 162 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/services/src/main/java/org/zanata/rest/editor/service/UserService.java, line 256 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/524#-KuNoC-a9I91VFjPiI2V:-KuNoC-a9I91VFjPiI2W:b-x7clkf) ([raw file](https://github.com/zanata/zanata-platform/blob/615cf01ba8436138c6c25cf6fd41d3f0ee5442fb/server/services/src/main/java/org/zanata/rest/editor/service/UserService.java#L256)):*
> ```Java
>           options.put(option.getName().substring(trim), option.getValue());
>         }
>       }
> ```

This file's indentation is wrong. You probably already saw a checkstyle error in build.
This for loop can be replaced by java 8 stream to make it easier to read.
```
account.getEditorOptions().values().stream()
    .filter(o -> o.getName().startsWith(dotPrefix))
    .forEach(o -> options.put(o.getName().substring(trim), o.getValue()))
```

---

*[server/zanata-frontend/src/frontend/app/editor/index.js, line 18 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/524#-KuNZws0ppf9BTSFM4e-:-KuNZws0ppf9BTSFM4e0:b-pi9d9n) ([raw file](https://github.com/zanata/zanata-platform/blob/615cf01ba8436138c6c25cf6fd41d3f0ee5442fb/server/zanata-frontend/src/frontend/app/editor/index.js#L18)):*
> ```JavaScript
> import NeedSlugMessage from './containers/NeedSlugMessage'
> 
> // FIXME remove this, it is just for a test
> ```

remove this

---

*[server/zanata-frontend/src/frontend/app/editor/components/SettingsOptions/index.js, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/524#-KuNjd2zAU5QM8j5KbtR:-KuNjd2zAU5QM8j5KbtS:b-u9p8mw) ([raw file](https://github.com/zanata/zanata-platform/blob/615cf01ba8436138c6c25cf6fd41d3f0ee5442fb/server/zanata-frontend/src/frontend/app/editor/components/SettingsOptions/index.js#L24)):*
> ```JavaScript
> SettingsOptions.propTypes = {
>   settings: PropTypes.arrayOf(PropTypes.shape({
>     // FIXME update to appropriate type
> ```

remove comment

---

*[server/zanata-frontend/src/frontend/flow-typed/npm/autoprefixer-loader_vx.x.x.js, line 2 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/524#-KuNaVdkUf5kFQalsLS0:-KuNaVdkUf5kFQalsLS1:b6srkra) ([raw file](https://github.com/zanata/zanata-platform/blob/615cf01ba8436138c6c25cf6fd41d3f0ee5442fb/server/zanata-frontend/src/frontend/flow-typed/npm/autoprefixer-loader_vx.x.x.js#L2)):*
> ```JavaScript
> // flow-typed signature: f168e10c27890fca98f7ddfa452744f5
> // flow-typed version: <<STUB>>/autoprefixer-loader_v3.2.0/flow_v0.54.1
> ```

Maybe put all flow-typed files in a separate PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/524)*

**Comment by davidmason** [comment]
Review status: 44 of 61 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/rest/editor/service/UserService.java, line 256 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/524#-KuNoC-a9I91VFjPiI2V:-KuRWib5B_2CyXlgGdLv:bezlic4) ([raw file](https://github.com/zanata/zanata-platform/blob/615cf01ba8436138c6c25cf6fd41d3f0ee5442fb/server/services/src/main/java/org/zanata/rest/editor/service/UserService.java#L256)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

This file's indentation is wrong. You probably already saw a checkstyle error in build.
This for loop can be replaced by java 8 stream to make it easier to read.
```
account.getEditorOptions().values().stream()
    .filter(o -> o.getName().startsWith(dotPrefix))
    .forEach(o -> options.put(o.getName().substring(trim), o.getValue()))
```
</blockquote></details>

Much better, thanks :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/524)*

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 3 of 117 files at r2, 15 of 15 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/524#-:-KuWro0NUuhjxoKsegAj:b9a2vem)*

**Comment by djansen-redhat** [comment]
How do I add a newline in a translation when _Enter saves immediately_ is on? My first instinct was Shift+Enter, but that saves and traverses a row up.

**Comment by aeng** [comment]
ALT + Enter for new line in cell?

**Comment by spathare21** [comment]
Unable to add new line in cell using Shitf + Enter / Ctrl + Enter . other expected functionality works fine.

**Comment by davidmason** [comment]
Thanks @spathare21 , I will update to have Shift+Enter add a newline when in "Enter saves immediately" mode.

**Comment by spathare21** [comment]
@davidmason I think its good to have Enter for new line and Shift + Enter for saving.

**Comment by davidmason** [comment]
@spathare21 That is the default behaviour, but some translators need to use shortcuts that do not overlap with their input method editor - that is why the "Enter saves immediately" option was added.

**Comment by davidmason** [comment]
@djansen-redhat @spathare21 this is ready to re-test. Shift+Enter should now create a newline.

**Comment by davidmason** [comment]
Review status: 47 of 48 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/index.js, line 18 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/524#-KuNZws0ppf9BTSFM4e-:-Kv54jj2p3RDjAAyaFC1:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/615cf01ba8436138c6c25cf6fd41d3f0ee5442fb/server/zanata-frontend/src/frontend/app/editor/index.js#L18)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

remove this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/524)*

**Comment by aeng** [comment]
Reviewed 1 of 8 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/524)*

**Comment by djansen-redhat** [comment]
Reviewed 1 of 117 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/524)*

**Comment by djansen-redhat** [comment]
Thanks for testing, @spathare21 
This looks good to go @davidmason

**Pull request merged**
