### PR TITLE
refactor(async): use CompletableFuture

### PR DESCRIPTION
**Pull request by carlosmunoz**
Use the platform's managed executor service which can be configured via standalone.xml in both wildfly and eap. Also changed to use CompletableFuture from the jdk instead of Guava's listenable future.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/230)

### CODE REVIEW

**Comment by seanf** [comment]
@carlosmunoz It's just as well I was planning to re-implement the new File service instead of rebasing. I'll do it on top of this code. :-)

> Use the platform's managed executor service which can be configured via standalone.xml in both wildfly and eap.

Is that actually a good thing, for us? Does this preclude managing the executor via Zanata server configuration in future? The more things we add to standalone.xml, the more deployment pain we seem to encounter.

The non-managed executor just had a hard-coded size before, is that right?

> Also changed to use CompletableFuture from the jdk instead of Guava's listenable future

+1 to that (not saying I've reviewed the code yet)

**Comment by seanf** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java, line 61 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqAmdeDwe9dsd6nWoQ:-KeqAmdeDwe9dsd6nWoR:b-ms7zw8) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java#L61)):*
> ```Java
> 
>     @Resource
>     private ManagedExecutorService scheduler;
> ```

But you weren't able to inject UserTransaction, is that right?

---

*[server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqBBZCiX56DMZ5dsLV:-KeqBBZDFt6X_KZzDS57:b-6jmlf4) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java#L64)):*
> ```Java
> 
>     @Inject
>     private AsyncConfig asyncConfig;
> ```

Seems like this isn't used any more.

Which means we can no longer change the pool size at runtime, I suppose.

---

*[server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java, line 68 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqBSngd8QGhETmIxMJ:-KeqBSngd8QGhETmIxMK:b-89d31m) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java#L68)):*
> ```Java
>     @PostConstruct
>     public void init() {
>     }
> ```

Dead?

---

*[server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java, line 72 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqBOWt8LV8TMsRk66-:-KeqBOWuKKR9y1HlC8Dm:b-r17hg6) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java#L72)):*
> ```Java
>     @PreDestroy
>     public void cleanup() {
>         scheduler.shutdown();
> ```

Is this a good idea, for a shared resource?

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/DocumentServiceImpl.java, line 147 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqBgyOhyy_af9cNUzg:-KeqBgyOhyy_af9cNUzh:bsn0nk4) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/service/impl/DocumentServiceImpl.java#L147)):*
> ```Java
>             boolean copyTrans, boolean lock,
>             AsyncTaskHandle<HDocument> handle) {
>         // TODO Use the passed in handle
> ```

:+1: That has been annoying me, but it wasn't worth a PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/230)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqBBZCiX56DMZ5dsLV:-KeqCaz1MotCxz-rzBiK:b-16fepb) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java#L64)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Seems like this isn't used any more.

Which means we can no longer change the pool size at runtime, I suppose.
</blockquote></details>

Ah. Not that we ever did change it at runtime, seeing as AsyncConfig uses system properties, not ServerConfiguration. I guess AsyncConfig is dead code now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/230)*

**Comment by carlosmunoz** [comment]
My initial hope was that it would create the necessary CDI contexts as well, but sadly that isn't the case. 

I like the idea of standalone-based configuration as the platform probably does a better job of managing these resources, but yes, it stops us from doing live changes.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-:-KeqIk5wbYgop6JkOWoA:bt910iz)*

**Comment by carlosmunoz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java, line 61 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqAmdeDwe9dsd6nWoQ:-KeqJQKCanNYWBjJ5Uea:bmcv9fh) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java#L61)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

But you weren't able to inject UserTransaction, is that right?
</blockquote></details>

No need really. I think we are already starting it when needed in any case.

---

*[server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqBBZCiX56DMZ5dsLV:-KeqJcAROUmvhyPmGlQQ:b-ugl8c5) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java#L64)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Ah. Not that we ever did change it at runtime, seeing as AsyncConfig uses system properties, not ServerConfiguration. I guess AsyncConfig is dead code now.
</blockquote></details>

Yes, seems to be. I can remove it if it we move ahead with this change.

---

*[server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java, line 68 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqBSngd8QGhETmIxMJ:-KeqJjU5wPhG0YQrEyZd:b-fzy03a) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java#L68)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Dead?
</blockquote></details>

Sure is. I'll remove.

---

*[server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java, line 72 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqBOWt8LV8TMsRk66-:-KeqJmq1-HFOLGDapn-2:b4yr1v1) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java#L72)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Is this a good idea, for a shared resource?
</blockquote></details>

Nope. Will remove as well.

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/DocumentServiceImpl.java, line 147 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqBgyOhyy_af9cNUzg:-KeqKGWQzGEEb-aOjr4b:blhnl68) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/service/impl/DocumentServiceImpl.java#L147)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

:+1: That has been annoying me, but it wasn't worth a PR.
</blockquote></details>

Not sure what you mean here. I'm still not solving this TODO in this change :smile: 

Just refactored a return type and a method name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/230)*

**Comment by seanf** [comment]
I think it might be better to split this into two PRs - one for CompletableFuture, one for ManagedExecutorService.

If we're going to move to ManagedExecutorService, we need to add a migration note to the release notes, add something to the admin guide, maybe output a warning at startup if the obsolete system property is still present, potentially update all the copies of standalone.xml and zanata-config.cli, potentially update ansible, puppet and Dockerfiles.

If all of that doesn't even get us CDI contexts for free, I'm not sure it's worth it, unfortunately. At least not until we have a much better way of managing standalone.xml in place.

But switching from Guava's ListenableFuture to JDK CompletableFuture is definitely a positive.

---

Review status: 18 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/DocumentServiceImpl.java, line 147 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-KeqBgyOhyy_af9cNUzg:-KeqLwZX6QcE5jPIrvuA:b8f9kmj) ([raw file](https://github.com/zanata/zanata-platform/blob/5834e8c3df398cc116520fe3dfac458a7b977be6/server/zanata-war/src/main/java/org/zanata/service/impl/DocumentServiceImpl.java#L147)):*
<details><summary><i>Previously, carlosmunoz (Carlos Munoz) wrote…</i></summary><blockquote>

Not sure what you mean here. I'm still not solving this TODO in this change :smile: 

Just refactored a return type and a method name
</blockquote></details>

It used to say "pased in".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-:-KeqMTzOyR3BH5A-xQaG:b5z9kvt)*

**Comment by carlosmunoz** [comment]
I guess there wasn't a test for AsyncConfig

---

Reviewed 17 of 19 files at r1, 2 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-:-Kf5D1eIZYCZ56g_cAjS:b-jebv0b)*

**Comment by seanf** [comment]
There was, but as it is now totally unchanged, Reviewable is not showing in the list of files.

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-:-Kf5Qttkw1fZHlN5mGYK:byfdwmu)*

**Comment by djansen-redhat** [comment]
Codecov patch has not achieved the minimum, but a review discussion has determined that this is acceptable.

**Comment by seanf** [comment]
@djansen-redhat are you planning to do any manual QA on this?

**Comment by djansen-redhat** [comment]
Sachin had the reigns on that one.

**Comment by seanf** [comment]
I have added the label "Suggest No QA", since it is just a refactoring with no user-visible changes. 

@carlosmunoz If you agree, could you please add "No QA"? @djansen-redhat agreed that this approach is worth a try (ie No QA if dev and reviewer concur.)

**Comment by djansen-redhat** [comment]
@carlosmunoz @seanf I'll disagree slightly with the assessment of "Suggest No_QA", there was enough in there to give me some pause.
I ran a simple upload + copytrans to verify.

**Comment by seanf** [comment]
Okay, thanks @djansen-redhat

---

Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/230#-:-KfsbHmKKe9o8iF-fVEw:bzhw4n8)*

**Pull request merged**
