### PR TITLE
feat(ZNTA-2113) Zanata Frontend Internationalization

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2113

Implementing react-intl as an internationalization provider for the Frontend.
JSON translation messages hosted on /messages to be consumed by the app.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/720)

### CODE REVIEW

**Comment by aeng** [comment]
I can see the locale being passed through the xhtml file. But what about when user change the app locale? How do we detect that?

---

Reviewed 3 of 7 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/720#-:-L5LH8GYDQ9ZFAy6iF7e:bkt5jd4)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/720#-:-L5R0lOeCdXhbsDvDLFV:bnfp4nl)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/720#-:-L5lVfrFWjH7BfeVUm_E:bnfp4nl)*

**Comment by spathare21** [comment]
@efloden exactly what needs to be tested here? or All functionality have to test by changing the locale from more options ?

**Comment by spathare21** [comment]
@efloden 
- can we add language name in English itself (or LanguageName(language code) format )in language selector drop-down from more options  

screenshot from 2018-02-20 12-18-42


- Translating indicator is not changing except Japanese

- Are all strings not translated into frontend for languages displayed in dropdown right?

- By changing locale some the options from Administration panel looks like below

screenshot from 2018-02-20 12-33-09

screenshot from 2018-02-20 12-36-46


- for few languages react editor is not opened (Postugues (Brasil), chinees HANS,CN and Chines Hant)

screenshot from 2018-02-20 12-11-05

**Comment by spathare21** [comment]
@efloden ohh ok then above issues should not be consider now  marking it verified then

**Pull request merged**
