### PR TITLE
fix(ZNTA-2152): removed css overrides that affected 'add' icon in dropdowns throughout frontend

### PR DESCRIPTION
**Pull request by kathryngo**
https://zanata.atlassian.net/browse/ZNTA-2152

plus-ddown

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/461)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/461#-:-KqVrlO6M7oP7U3h7UYZ:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo I did not see any changes with the + icon before and after merging this PR. also the build is not started on jenkins.

**Comment by kathryngo** [comment]
@spathare21 it was probably a different drop down it wasn't showing on. there are sooo many that are similar, I went through them all to check they all were visible.

builds need to be started manually. I will do this asap.

**Comment by kathryngo** [comment]
@spathare21 cannot see the build in jenkins either, odd. I will check again in a few hours. This isn't an urgent PR so it can wait until tomorrow even.

**Comment by spathare21** [comment]
@kathryngo ok thanks np.  but i see for + icon you have already fixed the issue https://zanata.atlassian.net/browse/ZNTA-2105

**Comment by kathryngo** [comment]
I fixed it in one place, but not everywhere. This PR tidies up the css to remove some overrides that I didn't deal with in the one you just linked me to

**Comment by spathare21** [comment]
okies : )

**Comment by spathare21** [comment]
build 1 pass

**Pull request merged**
