### PR TITLE
refactor(docs): Merge Zanata server and client docs

### PR DESCRIPTION
**Pull request by aeng**
JIRA issue URL: *[paste URL here]*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [x] Code passes style check (checkstyle/eslint)
   - [x] Code is clear and concise
   - [x] UI code is internationalised
   - [x] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [x] Classes are in appropriate packages
     - [x] Code fits with class's responsibilities (SRP)
   - [x] Configuration files are documented enough
   - If code is removed
     - [x] No remaining code references the removed code
       - [x] No orphaned rewrite rules
       - [x] No orphaned config settings
     - [x] No remaining comments refer to the removed code
     - [x] Unused imports and libraries are removed
 - Testing
   - [x] New code has tests
   - [x] Changed code has tests
   - [x] All tests pass
   - [x] Test coverage stable or increased
 - Documentation
   - [x] New features are documented
   - [x] Docs removed for deleted features
   - [x] Docs updated for all changed features
   - [x] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [x] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

https://zanata.atlassian.net/browse/ZNTA-1459

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/31)

### CODE REVIEW

**Comment by aeng** [comment]
Temporary doc generation for this PR: http://docs.zanata.org/en/znta-1459-readthedocs/

**Comment by carlosmunoz** [comment]
Reviewed 460 of 460 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/release-notes.md, line 71 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/31#-KVXpmbfvSPKihTGXdCi:-KVXpmbgZHRIKjY5Sq0s:b-31r6j6) ([raw file](https://github.com/zanata/zanata-platform/blob/a915f794d5ea672c0af20f17d38cff24cc09f0e5/docs/release-notes.md#L71)):*
> ```Markdown
>  * [ZNTA-1275](https://zanata.atlassian.net/browse/ZNTA-1275) - Fedora: login failed if name contains non-ascii characters
>  * [ZNTA-1112](https://zanata.atlassian.net/browse/ZNTA-1112) - Yahoo login indicates "Login failed" despite login success
>  * [ZNTA-1178](https://zanata.atlassian.net/browse/ZNTA-1178) - File type project can not be pulled using zanata cli
> ```

Why does this file have changes at all? It should only be a rename and maybe style updates, but not adding bug fixes to the list.

---

*[docs/user-guide/project-maintainer-guide.md, line 8 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/31#-KVXqlYC75FJxePTYHt-:-KVXqlYDVF-G6-Lp6Yfl:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-platform/blob/a915f794d5ea672c0af20f17d38cff24cc09f0e5/docs/user-guide/project-maintainer-guide.md#L8)):*
> ```Markdown
> 
> 1. Create a [project](/user-guide/projects/create-project) and [version](/user-guide/versions/create-version).
> 1. [Install](/client#installation) and [configure](/client/configuration) Zanata client.
> ```

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/31)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/release-notes.md, line 71 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/31#-KVXpmbfvSPKihTGXdCi:-KVXsdFARoakPoRAbprV:b-tspzua) ([raw file](https://github.com/zanata/zanata-platform/blob/a915f794d5ea672c0af20f17d38cff24cc09f0e5/docs/release-notes.md#L71)):*
<details><summary><i>Previously, carlosmunoz (Carlos Munoz) wrote…</i></summary>
> Why does this file have changes at all? It should only be a rename and maybe style updates, but not adding bug fixes to the list.
</details>
I've combined both client and server release notes since the version is in sync since 3.7. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/31)*

**Comment by aeng** [comment]
@camunoz, is this good for QA?

**Comment by carlosmunoz** [comment]
:lgtm:
-(Awaiting review) +Reviewed 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/release-notes.md, line 71 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/31#-KVXpmbfvSPKihTGXdCi:-KVb3SnY6L3wc6G4WGwD:b-703qn8) ([raw file](https://github.com/zanata/zanata-platform/blob/a915f794d5ea672c0af20f17d38cff24cc09f0e5/docs/release-notes.md#L71)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> I've combined both client and server release notes since the version is in sync since 3.7. 
</details>
Ok, I see. I'm fine with this to get out the door, but perhaps we should break up client and server sections, or even pages in the future. We can decide later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/31#-:-KVb44prjg5dMWiCu3W9:b-j0a94j)*

**Pull request merged**
