### PR TITLE
feat(ZNTA-1818): generate email report for TM Merge

### PR DESCRIPTION
**Pull request by seanf**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1818

Generate summary email report when running TM Merge for a project version

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 1 of 6 files at r1, 12 of 86 files at r2, 24 of 77 files at r3, 6 of 21 files at r4.
Review status: 42 of 106 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/services/src/main/java/org/zanata/email/AbstractEmailStrategy.java, line 37 at r4](https://reviewable.io/reviews/zanata/zanata-platform/818#-LD-s-nY8lA54oB8y6HI:-LD-s-nY8lA54oB8y6HJ:by2alon) ([raw file](https://github.com/zanata/zanata-platform/blob/95007a0256f3c2f22b4fdc98d90e72ea4bfaff2f/server/services/src/main/java/org/zanata/email/AbstractEmailStrategy.java#L37)):*
> ```Java
>     /**
>      * For absent, use the default From address configured by the server
>      * @return
> ```

either delete the empty ```@return``` or fill it with some detail.

---

*[server/services/src/main/java/org/zanata/email/HtmlEmailBuilder.kt, line 82 at r4](https://reviewable.io/reviews/zanata/zanata-platform/818#-LD-vVFJ-Ai4DRElrkiZ:-LD-vVFJ-Ai4DRElrki_:bh6w9zh) ([raw file](https://github.com/zanata/zanata-platform/blob/95007a0256f3c2f22b4fdc98d90e72ea4bfaff2f/server/services/src/main/java/org/zanata/email/HtmlEmailBuilder.kt#L82)):*
> ```Kotlin
>         serverPath: String = "",
>         receivedReasons: List<String> = listOf(),
>         bodyCallback: BODY.(Messages) -> Unit): String {
> ```

What is this ```BODY.(Messages) -> Unit```? I can't work out what the left hand side is

---

*[server/services/src/main/java/org/zanata/log4j/logger.kt, line 11 at r4](https://reviewable.io/reviews/zanata/zanata-platform/818#-LD-xvVGEMlw3EAShtPJ:-LD-xvVGEMlw3EAShtPK:b-v5rnl5) ([raw file](https://github.com/zanata/zanata-platform/blob/95007a0256f3c2f22b4fdc98d90e72ea4bfaff2f/server/services/src/main/java/org/zanata/log4j/logger.kt#L11)):*
> ```Kotlin
> 
> /**
>  * Returns a logger for the package containing the lambda (which may be empty: `getLogger {}`)
> ```

The code seems to use the lambda class as logger instead of package

---

*[server/services/src/main/java/org/zanata/log4j/logger.kt, line 16 at r4](https://reviewable.io/reviews/zanata/zanata-platform/818#-LD-xtF04WTvzQXfvSii:-LD-xtF04WTvzQXfvSij:bfqrefl) ([raw file](https://github.com/zanata/zanata-platform/blob/95007a0256f3c2f22b4fdc98d90e72ea4bfaff2f/server/services/src/main/java/org/zanata/log4j/logger.kt#L16)):*
> ```Kotlin
>         LoggerFactory.getLogger(lambda.javaClass)
> 
> private fun getLoggerForPackage(clazz: Class<*>): Logger =
> ```

Is this used?

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/818)*

**Comment by seanf** [comment]
Review status: 40 of 106 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/services/src/main/java/org/zanata/email/AbstractEmailStrategy.java, line 37 at r4](https://reviewable.io/reviews/zanata/zanata-platform/818#-LD-s-nY8lA54oB8y6HI:-LD00zE39XUTWb3eG43H:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/95007a0256f3c2f22b4fdc98d90e72ea4bfaff2f/server/services/src/main/java/org/zanata/email/AbstractEmailStrategy.java#L37)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

either delete the empty ```@return``` or fill it with some detail.
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/email/HtmlEmailBuilder.kt, line 82 at r4](https://reviewable.io/reviews/zanata/zanata-platform/818#-LD-vVFJ-Ai4DRElrkiZ:-LD01K608bz0O1HO4YZg:b-8gqswr) ([raw file](https://github.com/zanata/zanata-platform/blob/95007a0256f3c2f22b4fdc98d90e72ea4bfaff2f/server/services/src/main/java/org/zanata/email/HtmlEmailBuilder.kt#L82)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

What is this ```BODY.(Messages) -> Unit```? I can't work out what the left hand side is
</blockquote></details>

It's a Kotlin pattern called lambda with receiver, heavily used by kotlinx.htmlbuilder.

In this case it means this `bodyCallback` lambda will execute with a `this` value of type `BODY`, which allows it to call the various builder functions which are allowed within an HTML body element.

---

*[server/services/src/main/java/org/zanata/log4j/logger.kt, line 11 at r4](https://reviewable.io/reviews/zanata/zanata-platform/818#-LD-xvVGEMlw3EAShtPJ:-LD010b91p0H3VSIJC5I:b-d5q2i1) ([raw file](https://github.com/zanata/zanata-platform/blob/95007a0256f3c2f22b4fdc98d90e72ea4bfaff2f/server/services/src/main/java/org/zanata/log4j/logger.kt#L11)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

The code seems to use the lambda class as logger instead of package
</blockquote></details>

Fixed. Thanks!

---

*[server/services/src/main/java/org/zanata/log4j/logger.kt, line 16 at r4](https://reviewable.io/reviews/zanata/zanata-platform/818#-LD-xtF04WTvzQXfvSii:-LD011bT0J7oFaTMf2G5:brtg3bi) ([raw file](https://github.com/zanata/zanata-platform/blob/95007a0256f3c2f22b4fdc98d90e72ea4bfaff2f/server/services/src/main/java/org/zanata/log4j/logger.kt#L16)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Is this used?
</blockquote></details>

Is now. Thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/818)*

**Comment by huangp** [comment]
Reviewed 1 of 6 files at r1, 22 of 86 files at r2, 36 of 77 files at r3, 3 of 21 files at r4, 10 of 11 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/services/src/main/resources/messages.properties, line 1271 at r4](https://reviewable.io/reviews/zanata/zanata-platform/818#-LD0GOTo7MMR2DHGSeTS:-LD0GOTo7MMR2DHGSeTT:bnw3s18) ([raw file](https://github.com/zanata/zanata-platform/blob/95007a0256f3c2f22b4fdc98d90e72ea4bfaff2f/server/services/src/main/resources/messages.properties#L1271)):*
> ```INI
> # NB unicode 2014 is em dash
> email.templates.tm_merge.WordsCharsMessages={0} word(s) \u2014 {1} character(s) \u2014 {2} message(s)
> email.templates.tm_merge.TriggeredByYou=You triggered a Translation Memory merge operation.
> ```

check if these are used

---

*[server/services/src/main/resources/org/zanata/email/templates/tm_merge.vm, line 150 at r4](https://reviewable.io/reviews/zanata/zanata-platform/818#-LD0GgG87wGdm5RQS1TX:-LD0GgG87wGdm5RQS1TY:b-1r0vbi) ([raw file](https://github.com/zanata/zanata-platform/blob/95007a0256f3c2f22b4fdc98d90e72ea4bfaff2f/server/services/src/main/resources/org/zanata/email/templates/tm_merge.vm#L150)):*
> ```
> </div>
> </body>
> </html>
> ```

no longer needed

---

*[server/services/src/test/java/org/zanata/ZanataJpaTest.java, line 141 at r4](https://reviewable.io/reviews/zanata/zanata-platform/818#-LD0HGJw0TOUDDXN35ud:-LD0HGJw0TOUDDXN35ue:b-5tj6q6) ([raw file](https://github.com/zanata/zanata-platform/blob/95007a0256f3c2f22b4fdc98d90e72ea4bfaff2f/server/services/src/test/java/org/zanata/ZanataJpaTest.java#L141)):*
> ```Java
> 
>     protected void purgeLuceneIndexes() {
>         purgeLuceneIndexes(em);
> ```

somewhere else is also purging lucene indexes

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/818)*

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/818#-:-LD0QHPzBUt4jC_F80bp:b9a2vem)*

**Comment by spathare21** [comment]
@seanf  looks like there is some failure in the build. 
Also I didn't receive any pdf report as mentioned in Jira ticket. 

Does it include only this ?

screenshot from 2018-05-21 14-00-54

**Comment by seanf** [comment]
@spathare21 The PDF generation is in the optional/"future enhancement" category.

That report does look pretty empty - is it possible there was nothing to copy? I'll look at handling that case better.

**Comment by spathare21** [comment]
@seanf lgtm

**Pull request merged**
