### PR TITLE
fix(ZNTA-2231) add css-linter to webpack

### PR DESCRIPTION
**Pull request by kathryngo**
https://zanata.atlassian.net/browse/ZNTA-2231

Added the postcss stylelint linter for the bootstrap less css to webpack.  Also added the cssnano plugin to postcss so that things minify correctly.

Only one rule has been added to the stylelintrc file which frontend passes. I will add more rules and correct the errors over time.

## Checklist

- JIRA link ✔️ 
- Check target branch ✔️ 
- Make sure all commit statuses are green or otherwise documented reasons to ignore ✔️
- QA needs to evaluate against the JIRA ticket ✔️
- Changed files and commits make sense for this PR ✔️

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/569)

### CODE REVIEW

**Comment by davidmason** [comment]
Reviewed 6 of 9 files at r1, 6 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/package.json, line 3 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/569#-Kw3J1M8Mim3TUA59U3p:-Kw3J1M8Mim3TUA59U3q:b-nhrqv7) ([raw file](https://github.com/zanata/zanata-platform/blob/1243c9f9f7e6a49b0b75ea4305d7c45f3c125d2c/server/zanata-frontend/src/frontend/package.json#L3)):*
> ```JSON
> {
>   "name": "zanata-frontend",
>   "version": "1.1.0",
> ```

We aren't really doing releases on frontend - we don't publish it to npm so there's no point really. I've just been leaving this alone. If you have a versioning scheme that is useful to you then you're pretty much free to do whatever with this since we're not using it for anything.

---

*[server/zanata-frontend/src/frontend/app/components/VersionTMMergeModal/VersionTMMergeModal.story.js, line 69 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/569#-Kw3JrpXM7J5ze7Fteox:-Kw3JrpXM7J5ze7Fteoy:bipsnyw) ([raw file](https://github.com/zanata/zanata-platform/blob/1243c9f9f7e6a49b0b75ea4305d7c45f3c125d2c/server/zanata-frontend/src/frontend/app/components/VersionTMMergeModal/VersionTMMergeModal.story.js#L69)):*
> ```JavaScript
>                   imported TM, filtered using the active
>                   conditions, then the best matching translation is copied to
>                   the target project-version. more..</p>
> ```

This doesn't make sense if `more...` is not a link. I guess this is just to avoid an error about improper nesting? Since it is just the body of a story I guess it isn't really an issue.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ActivityFeedItem/index.js, line 59 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/569#-Kw3OURg521Qz5qw3g3z:-Kw3OURg521Qz5qw3g4-:bsi87ri) ([raw file](https://github.com/zanata/zanata-platform/blob/6cd77e2b398c439cb7b93d0d4d551a60fda2e1cb/server/zanata-frontend/src/frontend/app/editor/components/ActivityFeedItem/index.js#L59)):*
> ```JavaScript
>       'untranslated']),
>     textStatus: PropTypes.oneOf(['u-textWarning', 'u-textDanger', 'u-textHighlight']).isRequired,
>     type: PropTypes.oneOf(['comment', 'revision']).isRequired,
> ```

This component is going to break if we don't pass in a valid one of these. I think we need to keep most of these as `.isRequired`. Let's take a look at this in person to save excessive typing.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.js, line 22 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/569#-Kw3KX3rr12ZLO6OKx2Y:-Kw3KX3rr12ZLO6OKx2Z:babl9yo) ([raw file](https://github.com/zanata/zanata-platform/blob/1243c9f9f7e6a49b0b75ea4305d7c45f3c125d2c/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.js#L22)):*
> ```JavaScript
>     onHide: PropTypes.func,
>     toggleDropdown: PropTypes.func,
>     isOpen: PropTypes.bool,
> ```

This seems like a bad idea. We should always be telling our modal component whether it is open or closed. I'm guessing there's a reason you're removing a bunch of `.isRequired`, so we'd better work out how to solve whatever obstacle it is causing you without making the components fragile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/569)*

**Comment by kathryngo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/package.json, line 3 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/569#-Kw3J1M8Mim3TUA59U3p:-Kw3TilJZWARaW9N22c6:btcg257) ([raw file](https://github.com/zanata/zanata-platform/blob/1243c9f9f7e6a49b0b75ea4305d7c45f3c125d2c/server/zanata-frontend/src/frontend/package.json#L3)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

We aren't really doing releases on frontend - we don't publish it to npm so there's no point really. I've just been leaving this alone. If you have a versioning scheme that is useful to you then you're pretty much free to do whatever with this since we're not using it for anything.
</blockquote></details>

I might leave this alone for the meantime. Will discuss with the team at a later date. 

---

*[server/zanata-frontend/src/frontend/app/components/VersionTMMergeModal/VersionTMMergeModal.story.js, line 69 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/569#-Kw3JrpXM7J5ze7Fteox:-Kw3TproBshmlhjxm3PM:b-53nitv) ([raw file](https://github.com/zanata/zanata-platform/blob/1243c9f9f7e6a49b0b75ea4305d7c45f3c125d2c/server/zanata-frontend/src/frontend/app/components/VersionTMMergeModal/VersionTMMergeModal.story.js#L69)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

This doesn't make sense if `more...` is not a link. I guess this is just to avoid an error about improper nesting? Since it is just the body of a story I guess it isn't really an issue.
</blockquote></details>

The `panel-header` considers any content to be a link (its a react-bootstrap component), so the `p` class becomes a link. I was getting storybook failures because there was a link tag within this (more...) and links within links (`a > a`)  fails the tests.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ActivityFeedItem/index.js, line 59 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/569#-Kw3OURg521Qz5qw3g3z:-Kw3Ud9rPLWrJ8-B7S3y:bva6ng1) ([raw file](https://github.com/zanata/zanata-platform/blob/6cd77e2b398c439cb7b93d0d4d551a60fda2e1cb/server/zanata-frontend/src/frontend/app/editor/components/ActivityFeedItem/index.js#L59)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

This component is going to break if we don't pass in a valid one of these. I think we need to keep most of these as `.isRequired`. Let's take a look at this in person to save excessive typing.
</blockquote></details>

Added it back. Thought it was breaking tests but I was mistaken.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.js, line 22 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/569#-Kw3KX3rr12ZLO6OKx2Y:-Kw3WfL8Y31SbCPSUmff:bbh1hoj) ([raw file](https://github.com/zanata/zanata-platform/blob/1243c9f9f7e6a49b0b75ea4305d7c45f3c125d2c/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.js#L22)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

This seems like a bad idea. We should always be telling our modal component whether it is open or closed. I'm guessing there's a reason you're removing a bunch of `.isRequired`, so we'd better work out how to solve whatever obstacle it is causing you without making the components fragile.
</blockquote></details>

Fixed by adding `isRequired` back and adding the prop to the storybook file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/569)*

**Comment by davidmason** [comment]
Reviewed 2 of 3 files at r3.
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.story.js, line 26 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/569#-Kw3XbBmQEXZ36JhJ5T9:-Kw3XbBmQEXZ36JhJ5TA:b1h3h9q) ([raw file](https://github.com/zanata/zanata-platform/blob/7ea5b6b5d76c81f456c5489139bb80a9cd0aff7e/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.story.js#L26)):*
> ```JavaScript
>     ))
>     .add('Translation errors (critical)', () => (
>         <RejectTranslationModal show isOpen={true}
> ```

If the value is `true`, you can just use `isOpen` instead of `isOpen={true}`. In fact there's probably a linter warning about this, except we don't run the linter in the storybook build (I have eslint running in my editor so it still shows up for me).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/569)*

**Comment by davidmason** [comment]
Reviewed 1 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/569)*

**Comment by kathryngo** [comment]
Shall ignore code cov while it remains broken.

**Pull request merged**
