### PR TITLE
Use configure-app-server.js for rundev.sh

### PR DESCRIPTION
**Pull request by seanf**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2441

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 11 of 12 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/761#-:-L9NG0XM7wFV5XAfJlLR:b9a2vem)*

**Comment by seanf** [comment]
Note for QA: @spathare21 has already done some testing to ensure that sending email still works for rundev.

**Comment by djansen-redhat** [comment]
Anything valid in Codacy/Codefactor?

**Comment by djansen-redhat** [comment]
I think this is OK to go

**Comment by seanf** [comment]
> Anything valid in Codacy/Codefactor?

@djansen-redhat I think I can live with the remaining issues for now.

**Pull request merged**
