### PR TITLE
Remove atteo-classindex

### PR DESCRIPTION
**Pull request by seanf**
The minor performance gain doesn't justify the complexity of enabling
annotation processors across multiple modules and build tools. It also
makes Arquillian micro-deployments more difficult.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/480)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/480#-:-KrdHV7rnI4P4uYsK278:bnfp4nl)*

**Comment by seanf** [comment]
@aeng I had to make a number of changes since you reviewed this. Could you take another look please?

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 33 of 34 files at r2.
Review status: 37 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/480#-:-KsC2KuwgnUo_VuXtjuH:bnfp4nl)*

**Comment by aeng** [comment]
@seanf all good!

**Comment by aeng** [comment]
Reviewed 1 of 34 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/480)*

**Pull request merged**
