### PR TITLE
fix: AddLanguageTest selenium id for notifications

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: N/A

Update the AddLanguageTest notification close button selenium id

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efloden)

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/896#-:-LEqPzM13j5koshSvXGk:bnfp4nl)*

**Comment by efloden** [comment]
Thanks @djansen-redhat, waiting for Jenkins to pass

**Comment by djansen-redhat** [comment]
I have a concern that this only applies to half of the notifications.
Should there be two different elements to click?

**Comment by efloden** [comment]
@djansen-redhat the "btn-notification-close" was targeting our notification component that was based on a react-bootstrap modal, so with the conversion to ant components there should no longer be any targets with this id

**Pull request merged**
