### PR TITLE
fix(ZNTA-2139): Match% < 100 will auto enable 'different context' option

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2139

Disables the 'different context' checkbox and sets to checked when user selects a match
percentage < 100%

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/449)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed But see my comment in the jira. We may not need this change.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js, line 303 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/449#-Kpw887g4G-e3Do8OmCE:-Kpw887g4G-e3Do8OmCF:b7g0ikq) ([raw file](https://github.com/zanata/zanata-platform/blob/f20f4ba79cb77d65e357ade02b8918c1ddf3bed5/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js#L303)):*
> ```JavaScript
>       })
>     }
>   }
> ```

I think this can be shortened to
```
const newState = {
    matchPercentage: percent,
    differentContext: percent < 100
}
this.setState(newState)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/449#-:-Kpw81RQUeoPrag23s3p:b-q6kckc)*

**Comment by efloden** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js, line 303 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/449#-Kpw887g4G-e3Do8OmCE:-KpwKn_p0tyqyua1m1Gm:b-7zeoll) ([raw file](https://github.com/zanata/zanata-platform/blob/f20f4ba79cb77d65e357ade02b8918c1ddf3bed5/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js#L303)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

I think this can be shortened to
```
const newState = {
    matchPercentage: percent,
    differentContext: percent < 100
}
this.setState(newState)
```
</blockquote></details>

That is much nicer, applied this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/449)*

**Comment by djansen-redhat** [comment]
❌ Build 2 is red

**Comment by efloden** [comment]
Original issue not valid for all cases: In most cases, resId is generated from the content hash, but this depends on the source format. This won't be true for eg Properties files, nor for Gettext entries which have msgctxt.

**Pull request closed without merging**
