### PR TITLE
fix(ZNTA-2186) remove borders from editor inputs

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2186

The component css for RejectTranslationModal overrides the editor root/css unless specific classes and IDs are used. Please see the JIRA issue for a screenshot of the bug before it was fixed. 

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/496)

### CODE REVIEW

**Comment by davidmason** [comment]
Reviewed 2 of 4 files at r1, 2 of 5 files at r2.
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.css, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaMVdeH2qkudxmmK26:-KsaMVdeH2qkudxmmK27:b-djbp9c) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.css#L21)):*
> ```CSS
> }
> 
> .modal-body {
> ```

Does this rule apply to all our modals? We could include the component name at the top of the component to make this all specific to this component.

e.g. `.RejectTranslationModal.modal-body` or `#rejection-modal.modal-body` (not quite SUIT, but I'm assuming react-bootstrap doesn't let us replace `modal-body`.

If it is intended for all modals, it should go in the main Modal component css.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/496)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.css, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaMVdeH2qkudxmmK26:-KsaPJJzTyHkAXZROWq3:b-7ql1td) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.css#L21)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Does this rule apply to all our modals? We could include the component name at the top of the component to make this all specific to this component.

e.g. `.RejectTranslationModal.modal-body` or `#rejection-modal.modal-body` (not quite SUIT, but I'm assuming react-bootstrap doesn't let us replace `modal-body`.

If it is intended for all modals, it should go in the main Modal component css.
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/496)*

**Comment by davidmason** [comment]
Reviewed 2 of 4 files at r1, 3 of 5 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 16 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaOilcqcFAt8KUppk4:-KsaOilcqcFAt8KUppk5:biytofn) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L16)):*
> ```CSS
>   --Editor-color-dark: #20718a;
>   --Editor-color-bright: #1ba7d9;
>   --InputGroup-rhythm: 1.5rem;
> ```

This file, `app/editor/containers/Root/index.css` is meant for css that is relevant to the `Root` container (top-level layout stuff). We need to get all the other stuff split out into smaller modules that we can keep track of.

Utility css should go somewhere in `app/editor/css`, but these all look like they belong to a component called `InputGroup` so we should probably make `app/editor/components/InputGroup/index.css` and include that. Even if we don't have a React component for it, it still seems conceptually like a component. 

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 728 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaQyUDngbxOy9yT2zg:-KsaQyUEwRk6sa0HWTSy:bqsi3f) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L728)):*
> ```CSS
>     right;
>     background-size: var(--rhythm) 100%,
>     50% 100%;
> ```

Have you got some auto-formatter running on your css? The formatting in this section has been messed up a bit. This line should be indented further than the line above, or joined onto the line above.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.js, line 52 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaRUfGUkX4RyX5qNka:-KsaRUfGUkX4RyX5qNkb:b-rwitzl) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.js#L52)):*
> ```JavaScript
>         show
>         onHide={this.props.onClose}
>         id="suggestions-modal">
> ```

If we're going to use an ID, let's make it exactly match the component so there's no chance of clashes. `id="SuggestionDetailsModal"`. It means fewer names to remember too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/496)*

**Comment by davidmason** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.css, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaMVdeH2qkudxmmK26:-KsaSDDp59ix_narMuIR:b-r2ru6z) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.css#L21)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

fixed
</blockquote></details>

I was meaning to imply that the same is the case for everything below as well. I forgot people can't read my mind :confused: .

Since this is the css for a specific component, we should make sure everything in here only applies to that component.  The id `#rejection-modal` is the only way we can be really sure of that. 

e.g. I am sure there will be other places with `.Dropdown-item` so we'd better lock that down to `#rejection-modal.Dropdown-item`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/496)*

**Comment by kathryngo** [comment]
Review status: 3 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.css, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaMVdeH2qkudxmmK26:-KsaXag0aCq8pdl8MQoE:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.css#L21)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

I was meaning to imply that the same is the case for everything below as well. I forgot people can't read my mind :confused: .

Since this is the css for a specific component, we should make sure everything in here only applies to that component.  The id `#rejection-modal` is the only way we can be really sure of that. 

e.g. I am sure there will be other places with `.Dropdown-item` so we'd better lock that down to `#rejection-modal.Dropdown-item`
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 16 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaOilcqcFAt8KUppk4:-KsaXc7i5ziX-lGNeU9S:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L16)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

This file, `app/editor/containers/Root/index.css` is meant for css that is relevant to the `Root` container (top-level layout stuff). We need to get all the other stuff split out into smaller modules that we can keep track of.

Utility css should go somewhere in `app/editor/css`, but these all look like they belong to a component called `InputGroup` so we should probably make `app/editor/components/InputGroup/index.css` and include that. Even if we don't have a React component for it, it still seems conceptually like a component. 
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 728 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaQyUDngbxOy9yT2zg:-KsaXcc5Z-NJDcNXSmh3:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L728)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Have you got some auto-formatter running on your css? The formatting in this section has been messed up a bit. This line should be indented further than the line above, or joined onto the line above.
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.js, line 52 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaRUfGUkX4RyX5qNka:-KsaXdLuqdTDEftUWLQt:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.js#L52)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

If we're going to use an ID, let's make it exactly match the component so there's no chance of clashes. `id="SuggestionDetailsModal"`. It means fewer names to remember too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/496)*

**Comment by davidmason** [comment]
Reviewed 3 of 7 files at r4.
Review status: 6 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 728 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaQyUDngbxOy9yT2zg:-KsaYQdcCCzsXnXUqo7Z:b-1nx6tk) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L728)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Again with the no mind-reading :crystal_ball:  - same thing for the lines above, expect `right;` to be indented or joined to the line above, and the second `linear-gradient` under `background` to be indented.

I really need to get the linter running on this, machines are supposed to be helping us with this stuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/496)*

**Comment by davidmason** [comment]
Reviewed 4 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/496)*

**Comment by kathryngo** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 728 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-KsaQyUDngbxOy9yT2zg:-Ksa_7oLNeSMX22u3X6x:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/1b1c135d318e95123bc8ceee315da12ca2769862/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L728)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Again with the no mind-reading :crystal_ball:  - same thing for the lines above, expect `right;` to be indented or joined to the line above, and the second `linear-gradient` under `background` to be indented.

I really need to get the linter running on this, machines are supposed to be helping us with this stuff.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/496)*

**Comment by davidmason** [comment]
:lgtm: -(Under review) +Reviewed 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/496#-:-Ksa_aqdYodXEYQQizup:bns32bj)*

**Pull request merged**
