### PR TITLE
ZNTA-1865 - can merge translation from TM

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1865

* server side rest endpoint

QA：
Use postman or curl to call endpoint: 
http://localhost:8080/rest/project/gettext-project/version/1/tm-merge
with payload
```
{
	"localeId": "zh-Hans",
	"thresholdPercent": 90,
	"differentDocumentRule": "FUZZY",
	"differentContextRule": "FUZZY",
	"importedMatchRule": "REJECT",
	"fromProjectVersions": [
		"gettext/master"
		]
}
```
Change relevant values according to to match your test case. This endpoint will trigger a TM merge on version. You can open up editor to receive the changes.

There is also a modified endpoint:
http://localhost:8080/rest/search/projects?q=gettext&includeVersion=true
This will search a project with query "gettext" and return a response with project versions in them.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/389)

### CODE REVIEW

**Comment by aeng** [comment]
Missing documentation (readthedocs) for this feature and screenshot.

---

Reviewed 27 of 32 files at r1.
Review status: 27 of 32 files reviewed at latest revision, 8 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java, line 194 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZl9X31mvIcXCrM5aI:-KmZl9X31mvIcXCrM5aJ:b2a1rxn) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java#L194)):*
> ```Java
>      * Retrieves a full list of locales enabled in project version.
>      *
>      * @see ProjectIterationLocalesResource#get()
> ```

Shouldn't be ProjectIterationLocalesResource#get refer to this? or update this instead?

---

*[server/zanata-war/src/main/java/org/zanata/dao/TextFlowDAO.java, line 313 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZm_rbsivVlqo2IXXp:-KmZm_rcAI0SohUFxsOX:b-exgi71) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/dao/TextFlowDAO.java#L313)):*
> ```Java
>     }
> 
>     public long getUntranslatedOrFuzzyTextFlowCountInVersion(Long targetVersionId, HLocale targetLocale) {
> ```

Can this share some of the query code with ...getTextFlowsInVersion?

---

*[server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java, line 336 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZnt-yR1eaphfXmu4D:-KmZnt-yR1eaphfXmu4E:b-rsosc7) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java#L336)):*
> ```Java
> 
>     @POST
>     @Path(VERSION_SLUG_TEMPLATE + "/tm-merge")
> ```

No security check? anyone can perform TM-merge?

---

*[server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java, line 343 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZnbZGIBM11NQZafO2:-KmZnbZHolm-d4ARDizU:b-3fqk0y) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java#L343)):*
> ```Java
>         if (percent < 80 || percent > 100) {
>             return Response.status(Response.Status.BAD_REQUEST)
>                     .entity("{\"error\":\"percentThreshold must be between 80 and 100\"}")
> ```

Is this rule in the interface (comment for enunciate)?

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java, line 389 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZoq0U_QiF_4hjHG_w:-KmZoq0U_QiF_4hjHG_x:b-r11llz) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java#L389)):*
> ```Java
>                 .map(ModelEntityBase::getId).collect(Collectors.toList());
> 
>         // TODO pahuang do we need to check this? If it's empty, should we default to current project versions?
> ```

I think this block check is valid and should be uncommented.

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java, line 395 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZp9iEiMHxHtklpuQb:-KmZp9iEiMHxHtklpuQc:b-w56ksg) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java#L395)):*
> ```Java
> //        }
> 
>         if (isVersionEmpty(targetVersion)) {
> ```

This check and the one below should go to before we do any DAO query on top.

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java, line 412 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZpUNslAFLxqH2hq-h:-KmZpUNslAFLxqH2hq-i:bfplerh) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java#L412)):*
> ```Java
>                 Optional.fromNullable(handle);
>         if (taskHandleOpt.isPresent()) {
>             prepareMergeTranslationsHandle2(mergeTargetCount, taskHandleOpt.get());
> ```

prepareMergeTranslationsHandle2? we queue it up?

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java, line 163 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZpjBiLaW9GJyaBVVm:-KmZpjBiLaW9GJyaBVVn:bpyup1d) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java#L163)):*
> ```Java
> 
>     /**
>      * TODO this is only used by test. Should we remove it?
> ```

Yes please. Remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-:-KmZqZp2NHGA5eZg9MhP:bxz5n6c)*

**Comment by huangp** [comment]
Document will come in later when the frontend is finished. I will put more javadoc for the API.

---

Review status: 17 of 39 files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java, line 194 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZl9X31mvIcXCrM5aI:-Km_9CQI5-GtYtNY18lG:b-9lq2vz) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java#L194)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Shouldn't be ProjectIterationLocalesResource#get refer to this? or update this instead?
</blockquote></details>

The other one is a superset of this one. The other one returns locale aliases (used by CLI). This is a tech debt and should be dealt with separately. 

---

*[server/zanata-war/src/main/java/org/zanata/dao/TextFlowDAO.java, line 313 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZm_rbsivVlqo2IXXp:-Km_9pqkxSHFbLweIoFG:b-hbavdn) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/dao/TextFlowDAO.java#L313)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Can this share some of the query code with ...getTextFlowsInVersion?
</blockquote></details>

Which method are you referring to? Getting untranslated text flow is always the hardest because we need to cater for having null target and having target with state 'Untranslated'.  So it's hard to share query code with other query that does not involve untranslated state.

---

*[server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java, line 336 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZnt-yR1eaphfXmu4D:-Km_Adws-VUThf7iStVV:bii10fp) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java#L336)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

No security check? anyone can perform TM-merge?
</blockquote></details>

Good catch. I had a todo tag forgot to implement

---

*[server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java, line 343 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZnbZGIBM11NQZafO2:-Km_AWz5UxAbXDGGIRDv:b7q9ips) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java#L343)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is this rule in the interface (comment for enunciate)?
</blockquote></details>

This is not a public API. It's used by frontend only (at least for now). Enunciate will not process it.

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java, line 389 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZoq0U_QiF_4hjHG_w:-Km_Al-9scovrwS7MVQv:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java#L389)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think this block check is valid and should be uncommented.
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java, line 395 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZp9iEiMHxHtklpuQb:-Km_B3F0ZgoaJxO8awrC:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java#L395)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This check and the one below should go to before we do any DAO query on top.
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java, line 412 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZpUNslAFLxqH2hq-h:-Km_BIG85csajVAWBfJl:bm1miuw) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java#L412)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

prepareMergeTranslationsHandle2? we queue it up?
</blockquote></details>

leftover method name. Fixed

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java, line 163 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZpjBiLaW9GJyaBVVm:-Km_BXIUONeAm76MKEhR:b3o9q9t) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java#L163)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Yes please. Remove it.
</blockquote></details>

We will do it in separate PR. This will bit quite a big refactoring

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-:-Km_Bmi0ygjnxOThW0bY:b-qe6e3d)*

**Comment by aeng** [comment]
Reviewed 3 of 32 files at r1, 3 of 13 files at r2, 10 of 14 files at r3.
Review status: 33 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/zanata-war/src/main/java/org/zanata/dao/GenericDAO.java, line 11 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KnqMwpgv4TQboRl2w3m:-KnqMwpgv4TQboRl2w3n:bs488g4) ([raw file](https://github.com/zanata/zanata-platform/blob/5c8e59cf861efd36f052152cb3df1ca17e6264d9/server/zanata-war/src/main/java/org/zanata/dao/GenericDAO.java#L11)):*
> ```Java
> public interface GenericDAO<T, ID extends Serializable> {
> 
>     int MAX_PARAMS_IN_IN_CLAUSE = 50;
> ```

What is this for? Only for the projectIterationDAO?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/389)*

**Comment by aeng** [comment]
Review status: 33 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java, line 336 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KmZnt-yR1eaphfXmu4D:-KnqNAjXE1e8clmAtMXm:b-3c6nf1) ([raw file](https://github.com/zanata/zanata-platform/blob/c1d5b612002b57e15de6c95fad6e82bf4b10196e/server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java#L336)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Good catch. I had a todo tag forgot to implement
</blockquote></details>

Is the security check in place yet?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/389)*

**Comment by aeng** [comment]
Reviewed 1 of 13 files at r2, 2 of 14 files at r3.
Review status: 36 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/389)*

**Comment by aeng** [comment]
Reviewed 1 of 14 files at r3.
Review status: 37 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/389)*

**Comment by aeng** [comment]
Review status: 37 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/zanata-war/src/main/java/org/zanata/dao/GenericDAO.java, line 11 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KnqMwpgv4TQboRl2w3m:-KnqOBwnBjYQpaedZcLj:b4b54cu) ([raw file](https://github.com/zanata/zanata-platform/blob/5c8e59cf861efd36f052152cb3df1ca17e6264d9/server/zanata-war/src/main/java/org/zanata/dao/GenericDAO.java#L11)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

What is this for? Only for the projectIterationDAO?
</blockquote></details>

Should move to projectiterationdao if its only use by that dao.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/389)*

**Comment by huangp** [comment]
Review status: 37 of 39 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-war/src/main/java/org/zanata/dao/GenericDAO.java, line 11 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KnqMwpgv4TQboRl2w3m:-KnqW5dOxgnjQRzSegqW:b-suhore) ([raw file](https://github.com/zanata/zanata-platform/blob/5c8e59cf861efd36f052152cb3df1ca17e6264d9/server/zanata-war/src/main/java/org/zanata/dao/GenericDAO.java#L11)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should move to projectiterationdao if its only use by that dao.
</blockquote></details>

It's a general guide for parameters in "in" clause. e.g. ```select * from HProject where id in (:ids)```. It should limit the size of parameter list named ```ids``` to 50. 

---

*[server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java, line 404 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KnqWcQls1NyC0DXuTHt:-KnqWcQmjs5z0eGhmikX:b-7v7t4c) ([raw file](https://github.com/zanata/zanata-platform/blob/5c8e59cf861efd36f052152cb3df1ca17e6264d9/server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java#L404)):*
> ```Java
>         }
> 
>         identity.checkPermission("modify-translation", hProject, hLocale);
> ```

Here it checks permission.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/389)*

**Comment by aeng** [comment]
Reviewed 1 of 14 files at r3.
Review status: 38 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/zanata-war/src/main/java/org/zanata/dao/GenericDAO.java, line 11 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KnqMwpgv4TQboRl2w3m:-KnqbhDtZLCvZtVkxyk8:bqild8x) ([raw file](https://github.com/zanata/zanata-platform/blob/5c8e59cf861efd36f052152cb3df1ca17e6264d9/server/zanata-war/src/main/java/org/zanata/dao/GenericDAO.java#L11)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

It's a general guide for parameters in "in" clause. e.g. ```select * from HProject where id in (:ids)```. It should limit the size of parameter list named ```ids``` to 50. 
</blockquote></details>

Should it move to the DAO rather than in parent class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/389)*

**Comment by huangp** [comment]
Review status: 38 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/zanata-war/src/main/java/org/zanata/dao/GenericDAO.java, line 11 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-KnqMwpgv4TQboRl2w3m:-KnqiFFWD-kcDNY54Vkm:b2em2wc) ([raw file](https://github.com/zanata/zanata-platform/blob/5c8e59cf861efd36f052152cb3df1ca17e6264d9/server/zanata-war/src/main/java/org/zanata/dao/GenericDAO.java#L11)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should it move to the DAO rather than in parent class?
</blockquote></details>

Right now only ProjectIterationDAO uses it. But if other DAO also need to check this, they can get it from the parent class. I am fine to move it to ProjectIerationDAO though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/389)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 13 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/389#-:-KnqlAjumnZYtq-Vfefo:bnfp4nl)*

**Comment by djansen-redhat** [comment]
I'm not sure, but I think this breaks TM search in the editor - it just indicates "Searching..." indefinitely.

**Comment by djansen-redhat** [comment]
This one requires further work, @spathare21

**Comment by djansen-redhat** [comment]
Browser console:
```
(All lines on translate:45:84, but I removed them for readability)
(-:-) 2017-07-04 13:57:47,276 [INFO ] GWT-RPC response code: 0 for class NoOpAsyncCallback  
(-:-) 2017-07-04 13:57:50,462 [INFO ] Loading Zanata Web Editor...

(-:-) 2017-07-04 13:57:51,275 [INFO ] EventProcessor is now listening for events in the domain en-US:thang/pot
(-:-) 2017-07-04 13:57:51,839 [INFO ] Received doc list for thang/pot: 1 elements, loading time: 248ms
(-:-) 2017-07-04 13:57:51,861 [INFO ] =========== now firing current history state =========== 
(-:-) 2017-07-04 13:57:51,867 [INFO ] [gwt-history] Responding to history token: view:doc;doc:mobydick.txt;textflow:19490
(-:-) 2017-07-04 13:57:51,876 [INFO ] requesting transUnits: GetTransUnitList{offset=0, count=25, documentId=10:mobydick.txt, filterStates=ContentStateGroup(hasNew=true, hasFuzzy=true, hasTranslated=true, hasApproved=true, hasRejected=true), filterHasError=false, targetTransUnitId=19490, needReloadIndex=true, editorFilter=EditorFilter{textInContent=undefined, resId=undefined, lastModifiedBefore=undefined, lastModifiedAfter=undefined, lastModifiedByUser=undefined, sourceComment=undefined, transComment=undefined, msgContext=undefined}}
(-:-) 2017-07-04 13:57:51,881 [INFO ] [gwt-history] document id: 10:mobydick.txt
(-:-) 2017-07-04 13:57:51,884 [INFO ] view to show is:Editor
(-:-) 2017-07-04 13:57:52,704 [INFO ] result size: 25
(-:-) 2017-07-04 13:57:53,052 [INFO ] current row:-1 rowSelected:22
(-:-) 2017-07-04 13:57:53,053 [INFO ] current row:-1 about to select row:22
```
Zanata log:
```
04:13:14,749 INFO  [org.zanata.webtrans.server.TranslationWorkspaceImpl] (default task-108) Added user admin with editorClientId ORAXpR_rvxON1z4RfkOE3UUNGjJj7L6jim913pJo:2 to workspace en-US:thang/pot
04:13:14,987 INFO  [de.novanic.eventservice.service.EventServiceImpl] (default task-109) Server: Client "ORAXpR_rvxON1z4RfkOE3UUNGjJj7L6jim913pJo-2" initialized.
04:13:15,528 INFO  [org.zanata.webtrans.server.TranslationWorkspaceImpl] (default task-112) EditorClientId ORAXpR_rvxON1z4RfkOE3UUNGjJj7L6jim913pJo:2 has connectionId ORAXpR_rvxON1z4RfkOE3UUNGjJj7L6jim913pJo-2
04:13:16,171 INFO  [org.zanata.webtrans.server.rpc.GetTransUnitListHandler] (default task-116) action: GetTransUnitList{offset=0, count=25, documentId=10:mobydick.txt, filterStates=ContentStateGroup(hasNew=true, hasFuzzy=true, hasTranslated=true, hasApproved=true, hasRejected=true), filterHasError=false, targetTransUnitId=19490, needReloadIndex=true, editorFilter=EditorFilter{textInContent=null, resId=null, lastModifiedBefore=null, lastModifiedAfter=null, lastModifiedByUser=null, sourceComment=null, transComment=null, msgContext=null}}
```

**Comment by huangp** [comment]
@djansen-redhat you may need to perform a re-index as admin (select all three options for HTextFlowTarget). I just checked mine TM works.

**Comment by djansen-redhat** [comment]
@aeng this does not seem to have fixed the problem. I've reindexed and such a few times, I don't think that is the issue.

**Comment by djansen-redhat** [comment]
@huangp I deleted my database, and now it works - which concerns me - but I can let that go for now. 

The only other thing I noticed is that if I try to do rest "TM Merge fromProjectVersions:source1 -> dest1" and then "TM Merge fromProjectVersions:source2 -> dest1" it will reply with statusCode:"running". This is not conceptually correct as it's only source1 that is running - it should return an error if it cannot fulfil the user's request. (e.g. already running, try later).
You can either attend to this here, or create this as a separate task - I'll let you choose.

**Comment by huangp** [comment]
I will deal with this separately. We will be returning an error to indicate a process is running and ask the user to try again later.

**Pull request merged**
