### PR TITLE
fix(ZNTA-2712) admin breadcrumbs

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2712

admin breadcrumb links - same size, spacing and links working
width of admin cache page header

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by spathare21** [comment]
@kathryngo getting an error after clicking on Process manager and Overall statistics Also Administration on Translation memory page is not clickable

05:08:32,407 ERROR [org.zanata.exception.handler.AbstractExceptionHandler] (default task-30) exception happened in view: /admin/processmanager.xhtml: javax.faces.view.facelets.FaceletException: Error Parsing /admin/processmanager.xhtml: Error Traced[line: 54] The element type "p" must be terminated by the matching end-tag "</p>".


05:09:24,733 ERROR [org.zanata.exception.handler.AbstractExceptionHandler] (default task-48) exception happened in view: /admin/stats.xhtml: javax.faces.view.facelets.FaceletException: Error Parsing /admin/stats.xhtml: Error Traced[line: 197] The element type "p" must be terminated by the matching end-tag "</p>".

**Comment by kathryngo** [comment]
@spathare21 fixed

**Comment by spathare21** [comment]
@kathryngo does latest commit include any Userprofile related fix saw modified recent contribution file

**Comment by kathryngo** [comment]
@spathare21 fixed

**Pull request merged**
