### PR TITLE
fix: restrict access text on permissions tab made less ambiguous

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-579*

*[Made 'restrict access....' checkbox text less ambiguous - now states that it restricts access to translations in a project to certain user types.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/116)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/main/resources/messages_en_GB.properties, line 377 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/116#-KZP_-0Pk6Jk6sMeIDfM:-KZP_-0Pk6Jk6sMeIDfN:bwgkzb9) ([raw file](https://github.com/zanata/zanata-platform/blob/d19411e5c19ce761f3d15ecf6ec2721214525779/server/zanata-war/src/main/resources/messages_en_GB.properties#L377)):*
> ```INI
> jsf.RemoveLocale=< Remove
> # translation auto-copied from project Zanata server, version master, document zanata-war/src/main/resources/messages, author Damian Jansen
> jsf.RestrictRoleAccessMessage=Restrict access to translations in this project\
> ```

We don't need to change text in this property file. The translation should be updated in translate.zanata.org for Zanata project.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/116)*

**Comment by kathryngo** [comment]
*[server/zanata-war/src/main/resources/messages_en_GB.properties, line 377 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/116#-KZP_-0Pk6Jk6sMeIDfM:-KZPgAkfb1wrWOUx29b7:br36khf) ([raw file](https://github.com/zanata/zanata-platform/blob/d19411e5c19ce761f3d15ecf6ec2721214525779/server/zanata-war/src/main/resources/messages_en_GB.properties#L377)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

We don't need to change text in this property file. The translation should be updated in translate.zanata.org for Zanata project.
</blockquote></details>

So the other file (messages.properties) is correct? 
Do I just need to revert this change?
I am not sure what you mean by it being updated in translate.zanata.org instead
These 2 files are the only ones in platform with the reference to the required checkbox string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/116)*

**Comment by aeng** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/main/resources/messages_en_GB.properties, line 377 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/116#-KZP_-0Pk6Jk6sMeIDfM:-KZPl0urRC5fEGpUPXlz:b-e8vk1c) ([raw file](https://github.com/zanata/zanata-platform/blob/d19411e5c19ce761f3d15ecf6ec2721214525779/server/zanata-war/src/main/resources/messages_en_GB.properties#L377)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

So the other file (messages.properties) is correct? 
Do I just need to revert this change?
I am not sure what you mean by it being updated in translate.zanata.org instead
These 2 files are the only ones in platform with the reference to the required checkbox string
</blockquote></details>

Revert this change. This file is pulled from translate.zanata.org.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/116)*

**Comment by kathryngo** [comment]
*[server/zanata-war/src/main/resources/messages_en_GB.properties, line 377 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/116#-KZP_-0Pk6Jk6sMeIDfM:-KZQ6vagKDiq61ndwBMa:b-3fjml0) ([raw file](https://github.com/zanata/zanata-platform/blob/d19411e5c19ce761f3d15ecf6ec2721214525779/server/zanata-war/src/main/resources/messages_en_GB.properties#L377)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Revert this change. This file is pulled from translate.zanata.org.
</blockquote></details>

Will I need to change the file on translate.zanata.org or can this entire issue  be closed? I will ask about how to do this in the office

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/116)*

**Comment by kathryngo** [comment]
@aeng , ready for review 😄

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/116#-:-KZU7IiLdAwzosMsh3yh:bnfp4nl)*

**Comment by spathare21** [comment]
Verified text is changed to Restrict access to translations in this project to certain user roles?

**Comment by aeng** [comment]
@spathare21 correct.

**Pull request merged**
