### PR TITLE
ZNTA-2111 migrate css/js from assets

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2111

Moved all the css and js (plus fonts and icons) from zanata-assets (non-minified) to zanata-platform

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/433)

### CODE REVIEW

**Comment by kathryngo** [comment]
@aeng 

Can you please look at how to fix the references to zanata-assets. I do not know enough about JSF to do this at this point.

Current errors from inspector:
`
:8080/404?dswid=8217:1 Uncaught SyntaxError: Unexpected token <
`

`
?dswid=2768:89 Uncaught ReferenceError: zanata is not defined
    at ?dswid=2768:89
    at h.execute (signals.min.js.xhtml:9)
    at e.dispatch (signals.min.js.xhtml:13)
    at e.dispatch (signals.min.js.xhtml:8)
    at n.parse (crossroads.min.js.xhtml:6)
    at updateStateFromUrl (components-script.js.xhtml:40)
    at HTMLDocument.<anonymous> (?dswid=2768:92)
    at fire (jquery.js:786)
    at Object.fireWith [as resolveWith] (jquery.js:819)
    at Function.ready (jquery.js:879)
`

**Comment by aeng** [comment]
Reviewed 59 of 92 files at r2.
Review status: 47 of 66 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/zanata-war/src/main/webapp/resources/assets/css/_globals/font-variables.css, line 0 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY6DRhrDGiLzi7SJN0:-KpY6DRibjis2goHveqh:beraebz) ([raw file](https://github.com/zanata/zanata-platform/blob/6d5e57450acfed2fa379224b5ef61001c3a39245/server/zanata-war/src/main/webapp/resources/assets/css/_globals/font-variables.css#L0)):*
This file is empty, should remove.

---

*[server/zanata-war/src/main/webapp/resources/assets/img/logo/logo-32@2x.png, line 0 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY6nLTyak-GHfqLBqK:-KpY6nLTyak-GHfqLBqL:b3cg5rp) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/img/logo/logo-32@2x.png#L0)):*
Do we need all the logo in here? I think we should just include whatever that is reference from the server. The same set copy is already in http://zanata.org/images/logo/

---

*[server/zanata-war/src/main/webapp/resources/assets/img/rgbapng/0000007f-5.png, line 0 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY74em6oR8biwFcZJA:-KpY74em6oR8biwFcZJB:b-o9lcbw) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/img/rgbapng/0000007f-5.png#L0)):*
This file seems weird.. is this being used?

---

*[server/zanata-war/src/main/webapp/resources/assets/js/components/example.js, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY7CzhhkIO-e6aNj91:-KpY7CzhhkIO-e6aNj92:bq13qs1) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/js/components/example.js#L1)):*
> ```JavaScript
> jQuery(function () {
> ```

Dont think we need this file?

---

*[server/zanata-war/src/main/webapp/resources/assets/js/components/reveal.js, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY7P-z-hFUT-mvDwsQ:-KpY7P-z-hFUT-mvDwsR:b61l0o9) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/js/components/reveal.js#L1)):*
> ```JavaScript
> (function ($) {
> ```

Do we need all the js files? I remember we only include script.min.js in zanata-server.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/433)*

**Comment by aeng** [comment]
Please remove any files which are not referenced from zanata server.  

---

Review status: 47 of 66 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-:-KpY7ql2EVBmOXgvbKql:b-e9dv2z)*

**Comment by kathryngo** [comment]
Review status: 47 of 66 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/zanata-war/src/main/webapp/resources/assets/img/logo/logo-32@2x.png, line  at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY6nLTyak-GHfqLBqK:-KpY94MGVKjw1Lf-FJnm:bk70lo3) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/img/logo/logo-32@2x.png#L)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we need all the logo in here? I think we should just include whatever that is reference from the server. The same set copy is already in http://zanata.org/images/logo/
</blockquote></details>

Ok will remove

---

*[server/zanata-war/src/main/webapp/resources/assets/img/rgbapng/0000007f-5.png, line  at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY74em6oR8biwFcZJA:-KpY90fjcLrdudQspSWq:b-usbnlo) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/img/rgbapng/0000007f-5.png#L)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This file seems weird.. is this being used?
</blockquote></details>

I just copied the images folder over from assets so probably not

---

*[server/zanata-war/src/main/webapp/resources/assets/js/components/example.js, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY7CzhhkIO-e6aNj91:-KpY97OQI3glorSfaolU:bjmlex3) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/js/components/example.js#L1)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Dont think we need this file?
</blockquote></details>

Like with the other folders, I just included all the js files. I will include only the minified one and reference that.

---

*[server/zanata-war/src/main/webapp/resources/assets/js/components/reveal.js, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY7P-z-hFUT-mvDwsQ:-KpY9CcVIKgwzUSRsOM4:b-r1q3jn) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/js/components/reveal.js#L1)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we need all the js files? I remember we only include script.min.js in zanata-server.
</blockquote></details>

Shall make it so only the minified one is used

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/433)*

**Comment by kathryngo** [comment]
@aeng I am still getting errors like I posted in a previous comment here.  

`
:8080/404?dswid=8217:1 Uncaught SyntaxError: Unexpected token <
`

`
?dswid=2768:89 Uncaught ReferenceError: zanata is not defined at ?dswid=2768:89 at h.execute (signals.min.js.xhtml:9) at e.dispatch (signals.min.js.xhtml:13) at e.dispatch (signals.min.js.xhtml:8) at n.parse (crossroads.min.js.xhtml:6) at updateStateFromUrl (components-script.js.xhtml:40) at HTMLDocument.<anonymous> (?dswid=2768:92) at fire (jquery.js:786) at Object.fireWith [as resolveWith] (jquery.js:819) at Function.ready (jquery.js:879)
`

 These errors are the reason I cannot get the activity panel to show on the dashboard I think. Please see this screenshot.

If you could look at what is causing this error it would be greatly appreciated. 
dashboardissue

**Comment by kathryngo** [comment]
Review status: 31 of 53 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/zanata-war/src/main/webapp/resources/assets/css/_globals/font-variables.css, line  at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY6DRhrDGiLzi7SJN0:-KplghyM0E4h55G1qi6r:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/6d5e57450acfed2fa379224b5ef61001c3a39245/server/zanata-war/src/main/webapp/resources/assets/css/_globals/font-variables.css#L)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This file is empty, should remove.
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/webapp/resources/assets/js/components/example.js, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY7CzhhkIO-e6aNj91:-Kplgj3azO4SXRix_2UE:bjix4fz) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/js/components/example.js#L1)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Like with the other folders, I just included all the js files. I will include only the minified one and reference that.
</blockquote></details>

Yep, the site doesn't work without these JS files.

---

*[server/zanata-war/src/main/webapp/resources/assets/js/components/reveal.js, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY7P-z-hFUT-mvDwsQ:-KplgnRqeEsHo2u3p9jo:b-aefzl0) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/js/components/reveal.js#L1)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Shall make it so only the minified one is used
</blockquote></details>

Have included both, attempted to fix issues with the dashboard rendering by using the minified file instead. It didn't work.

FYI `Uncaught SyntaxError: Unexpected token <` appears when any page is loaded, including the login page

---

*[server/zanata-war/src/main/webapp/resources/assets/img/logo/logo-32@2x.png, line  at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY6nLTyak-GHfqLBqK:-KplgwwDMq0uXjWVsn5k:bn7y3db) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/img/logo/logo-32@2x.png#L)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Ok will remove
</blockquote></details>

Removed in addition to the other images that aren't used

---

*[server/zanata-war/src/main/webapp/resources/assets/img/rgbapng/0000007f-5.png, line  at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/433#-KpY74em6oR8biwFcZJA:-Kplh2XaWYw_VkQkg29-:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/e532bad52942b5a35ce8e6384ff6471e541bf526/server/zanata-war/src/main/webapp/resources/assets/img/rgbapng/0000007f-5.png#L)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

I just copied the images folder over from assets so probably not
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/433)*

**Comment by kathryngo** [comment]
Reopened as PR #442

**Pull request closed without merging**
