### PR TITLE
refactor(ZNTA-1304): Delombok the code

### PR DESCRIPTION
**Pull request by seanf**
The annotations `@NonNull`, `@Cleanup` and `@Synchronized` were delomboked by
hand due to limitations of the IntelliJ plugin.

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1304

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/152)

### CODE REVIEW

**Comment by huangp** [comment]
It seems to messed up all the import orders. I think your IDE's import order is not consistent with the eclipse-organize-imports.importorder file. When doing refactoring, I think IntelliJ will use its own setting rather than using eclipse code formatter. 
Either you change your import order setting first then redo the delombok, or do a bulk re-organize import on all the files (some files are not consistent already anyway)

**Comment by huangp** [comment]
```@ToString``` will turn into string concatenation. We may want to do a search on that and put TODO to convert the implementation to something better.

**Comment by huangp** [comment]
```@EqualsAndHashCode``` turn into something really odd. e.g.
```
+    public boolean equals(Object o) {
+        if (o == this) return true;
+        if (!(o instanceof HAccount)) return false;
+        final HAccount other = (HAccount) o;
+        if (!other.canEqual((Object) this)) return false;
+        if (!super.equals(o)) return false;
+        final Object this$username = this.getUsername();
+        final Object other$username = other.getUsername();
+        if (this$username == null ? other$username != null :
+                !this$username.equals(other$username)) return false;
+        final Object this$passwordHash = this.getPasswordHash();
+        final Object other$passwordHash = other.getPasswordHash();
+        if (this$passwordHash == null ? other$passwordHash != null :
+                !this$passwordHash.equals(other$passwordHash)) return false;
+        if (this.isEnabled() != other.isEnabled()) return false;
+        final Object this$apiKey = this.getApiKey();
+        final Object other$apiKey = other.getApiKey();
+        if (this$apiKey == null ? other$apiKey != null :
+                !this$apiKey.equals(other$apiKey)) return false;
+        return true;
+    }
```
Might also do a sed script and put TODO tag on these classes and change it manually later

**Comment by seanf** [comment]
I've reported https://github.com/mplushnikov/lombok-intellij-plugin/issues/127 for the `@ToString` problem. Going by the StackOverflowErrors in many of the tests (eg `VersionGroupServiceImplTest.isVersionInGroupTest()`), I think there is a problem with some of the delomboked `hashCode`/`equals` methods too.

I think I'll have to start again with delombok via Maven instead.

**Comment by seanf** [comment]
The StackOverflowError problem in hashCode/equals has been reported as https://github.com/mplushnikov/lombok-intellij-plugin/issues/342

**Comment by seanf** [comment]
See https://github.com/zanata/zanata-platform/pull/157 for the Maven-based Delombok effort.

**Pull request closed without merging**
