### PR TITLE
fix(ZNTA-2617) add spacing to delete entry buttons on language page

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2617

fix(ZNTA-2617) add spacing to delete entry buttons on language page & fix alignment of no languages statement when page is loading

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by efloden** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/887#-:-LERvG9hDsrA1E3ZTfdE:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo conflicts with latest release branch

**Comment by djansen-redhat** [comment]
Looks like the conflict was resolved.

**Comment by spathare21** [comment]
@djansen-redhat nope still shows conflicts for server/zanata-frontend/src/app/styles/antd.less

**Comment by spathare21** [comment]
verified looks good, codecov seems failing ig have to ignore merge it.

**Comment by efloden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/887#-:-LEl8bAm3eGU_c_WS12r:bnfp4nl)*

**Pull request merged**
