### PR TITLE
Migrate Commons Lang to Lang3 and Text

### PR DESCRIPTION
**Pull request by seanf**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/538)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 91 of 91 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/538#-:-Kv0r9990qRXqDRejv5c:bnfp4nl)*

**Comment by seanf** [comment]
@aeng Could you please review the extra changes?

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/538#-:-Kv4FbybSa61OrrSNev8:bnfp4nl)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r3, 1 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/538#-:-KvUcVz4AndZB14w80DZ:bnfp4nl)*

**Pull request merged**
