### PR TITLE
fix(ZNTA-2387): Add email and name to user search query

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2387

Admin can search for users via display name, email or username.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@seanf I've dropped the Kotlin convert as it opened a bit of a rabbit hole, but saved it elsewhere. I'll try it after this goes through.

**Comment by seanf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/services/src/main/java/org/zanata/dao/AccountDAO.java, line 130 at r2](https://reviewable.io/reviews/zanata/zanata-platform/794#-LBIsGd5-G-U-sUNYFcz:-LBIsGd5-G-U-sUNYFd-:be5uu45) ([raw file](https://github.com/zanata/zanata-platform/blob/55a3f19cdf70c0ccdd3ac20e5b07def009170783/server/services/src/main/java/org/zanata/dao/AccountDAO.java#L130)):*
> ```Java
>     public List<String> getUserNames(String filter, int offset, int maxResults) {
>         Query query = createFilteredQuery(
>                 "select distinct acc.username from HAccount acc ", filter)
> ```

"distinct" seems like overkill if username has a unique index, but okay.

---

*[server/services/src/main/java/org/zanata/dao/AccountDAO.java, line 143 at r2](https://reviewable.io/reviews/zanata/zanata-platform/794#-LBIsK7q5CcpnSdD4BqA:-LBIsK7q5CcpnSdD4BqB:bn61bne) ([raw file](https://github.com/zanata/zanata-platform/blob/55a3f19cdf70c0ccdd3ac20e5b07def009170783/server/services/src/main/java/org/zanata/dao/AccountDAO.java#L143)):*
> ```Java
>                 "select count(*) from HAccount acc ", filter)
>                 .setComment("accountDAO.getUserCount");
>         return ObjectUtils.firstNonNull((Long) query.uniqueResult(), 0).intValue();
> ```

I'm pretty sure "select count(*)" is guaranteed to return a value. But if it doesn't, I think a noisy exception beats silent misbehaviour. So firstNonNull shouldn't be needed.

Ah, I see that the old code was doing something similar. Best to change it though, I think.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/794)*

**Comment by djansen-redhat** [comment]
*[server/services/src/main/java/org/zanata/dao/AccountDAO.java, line 143 at r2](https://reviewable.io/reviews/zanata/zanata-platform/794#-LBIsK7q5CcpnSdD4BqA:-LBJW7W-3gqZjNs1-NCr:bb6un1j) ([raw file](https://github.com/zanata/zanata-platform/blob/55a3f19cdf70c0ccdd3ac20e5b07def009170783/server/services/src/main/java/org/zanata/dao/AccountDAO.java#L143)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I'm pretty sure "select count(*)" is guaranteed to return a value. But if it doesn't, I think a noisy exception beats silent misbehaviour. So firstNonNull shouldn't be needed.

Ah, I see that the old code was doing something similar. Best to change it though, I think.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/794)*

**Comment by djansen-redhat** [comment]
*[server/services/src/main/java/org/zanata/dao/AccountDAO.java, line 130 at r2](https://reviewable.io/reviews/zanata/zanata-platform/794#-LBIsGd5-G-U-sUNYFcz:-LBJWHm99rhvRyYJo2Ay:b-x4wifx) ([raw file](https://github.com/zanata/zanata-platform/blob/55a3f19cdf70c0ccdd3ac20e5b07def009170783/server/services/src/main/java/org/zanata/dao/AccountDAO.java#L130)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

"distinct" seems like overkill if username has a unique index, but okay.
</blockquote></details>

I wasn't sure if I'd get a duplicated result with the OR

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/794)*

**Comment by spathare21** [comment]
@djansen-redhat verified search works fine but looks like build failed for codecov

**Comment by djansen-redhat** [comment]
Codecov is loopy.

**Pull request merged**
