### PR TITLE
fix(ZNTA-2143) frontend css refactor/tidy

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2143

Frontend css is getting messy, needs duplicates removed. It needs to be cleaned up using the css methodology SUIT so it is more component focused and in line with the code in editor.

## Please note 
1. GWT code still sits in zanata-war - unless we want to break the entire site we shouldn't touch this.
2. Frontend code has been tidied (2500 lines removed from style.less). This was achieved by moving code to its container or component folder. The majority of code remains in style.less - as this provides the foundation for the bootstrap styling. 
3. I did not move the bootstrap css to the folders I created the bootstrap react components in. For management, it is best I keep all the bootstrap css in one file, and the custom component classes in their own folders. 
4. I have tried to use Suit CSS class names wherever I can ie [componentName-element--state] but you will notice some classes do not follow this. This is because they either are part of GWT, the older editor or bootstrap classes.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/515)

### CODE REVIEW

**Comment by kathryngo** [comment]
For my reference - css bugs that need to be fixed

settings-fix
tmmodal-fix
langmodal-fix
languages-fix
profile-fix
admin-fix

**Comment by aeng** [comment]
Reviewed 18 of 97 files at r1, 5 of 20 files at r2.
Review status: 23 of 103 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 2 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN76u6c-QazQwZxdMc:-KuN76u6c-QazQwZxdMd:b-k1an7) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L2)):*
> ```CSS
> #tmxExportModal .modal-header {
>   padding-bottom: 0 !important;
> ```

Can we have a standard css class for padding-bottom 0? apply that class into the html tag?

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 6 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN72bcR6IHhDFMqDdK:-KuN72bcR6IHhDFMqDdL:b-moaqzv) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L6)):*
> ```CSS
> 
> #tmxExportModal .modal-body {
>   padding-top: 0 !important;
> ```

Can we have a standard css class for padding-top 0? apply that class into the html tag?

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 16 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN6q0ftlci8cxDpdlq:-KuN6q0g9hQMwqsktjnQ:b-xsi1yc) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L16)):*
> ```CSS
> 
> .tmxExport {
>   text-align: center;
> ```

Can we have a standard css class for text-align center and apply that class into the html tag?

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 20 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN6eeYPhyIjSX0yEUr:-KuN6eeYPhyIjSX0yEUs:br04wpx) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L20)):*
> ```CSS
> 
> .tmxExport p.lead {
>   font-weight: 500;
> ```

Do we have a standard css class that defined font-weight that we can reuse? instead of just for TMX?

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 24 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN6Q81l3C2yp25BqOd:-KuN6Q81l3C2yp25BqOe:bw8bilq) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L24)):*
> ```CSS
> 
> .tmxExport p.u-textWarning {
>   font-size: 0.75em;
> ```

Do we have a standard css class that defined font-size that we can reuse? instead of just for TMX?

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 42 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN7AR-inmj7IamSwkv:-KuN7AR-inmj7IamSwkw:b9b396) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L42)):*
> ```CSS
> 
> table.tmxTable tbody tr td:first-child {
>   color: #03A6D7;
> ```

Is this color only used in tmx? or its from a standard set of colors that we can reuse?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by kathryngo** [comment]
Review status: 23 of 103 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 20 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN6eeYPhyIjSX0yEUr:-KuN7imhHLR-_BD6nvkV:b-yub6xp) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L20)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we have a standard css class that defined font-weight that we can reuse? instead of just for TMX?
</blockquote></details>

Can't use variables like the style.less file in this file so I have defaulted to hex codes. I can always set some variables at the top of the file if you like specific to this css

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 24 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN6Q81l3C2yp25BqOd:-KuN7eEIjQ4IAdft-k3r:b-st9wc8) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L24)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we have a standard css class that defined font-size that we can reuse? instead of just for TMX?
</blockquote></details>

See previous comment

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 42 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN7AR-inmj7IamSwkv:-KuN7tqLpkgqzgaTumd9:b-ya81ng) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L42)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is this color only used in tmx? or its from a standard set of colors that we can reuse?
</blockquote></details>

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by aeng** [comment]
Review status: 23 of 103 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 20 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN6eeYPhyIjSX0yEUr:-KuNClP-dOWEcS8Taic9:bzdrnsz) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L20)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Can't use variables like the style.less file in this file so I have defaulted to hex codes. I can always set some variables at the top of the file if you like specific to this css
</blockquote></details>

We need to figure out a way to allow these css files to use variables, otherwise, we are not solving the reusability problem. Can we make it .less instead, and have it import a set a common variables sitting somewhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by kathryngo** [comment]
Review status: 20 of 104 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 20 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN6eeYPhyIjSX0yEUr:-KuNHmfWEvqsR-Pd0jMe:b-5anddl) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L20)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

We need to figure out a way to allow these css files to use variables, otherwise, we are not solving the reusability problem. Can we make it .less instead, and have it import a set a common variables sitting somewhere?
</blockquote></details>

Understood. By converting the css files to less files I am able to reuse the import variables statement. By default it only imports the file once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by kathryngo** [comment]
Review status: 20 of 104 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 6 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN72bcR6IHhDFMqDdK:-KuNOCuCRGp9AaYqgSoW:b-681lmp) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L6)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Can we have a standard css class for padding-top 0? apply that class into the html tag?
</blockquote></details>

Not in this case. This is an override of styling on the modal-body bootstrap class. 

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.css, line 16 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN6q0ftlci8cxDpdlq:-KuNOINYvAGQSRU7JrGS:b5xsmir) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.css#L16)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Can we have a standard css class for text-align center and apply that class into the html tag?
</blockquote></details>

This is a class I had to add to override the bootstrap styling. It makes more sense to give it a semantic name so examples like the statement below are easier to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by kathryngo** [comment]
Review status: 20 of 104 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/components/TMX/index.less, line 2 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuN76u6c-QazQwZxdMc:-KuNhtmlrO3Uj0SrOQ7-:bf7k48x) ([raw file](https://github.com/zanata/zanata-platform/blob/5b3f8ccc31da9676bfdf00627b1b6b72d8ec129e/server/zanata-frontend/src/frontend/app/components/TMX/index.less#L2)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Can we have a standard css class for padding-bottom 0? apply that class into the html tag?
</blockquote></details>

Not in this case. This is an override of styling on the modal-body bootstrap class.

This is all ready for another review now. Have used variables.less throughout

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by aeng** [comment]
Reviewed 27 of 105 files at r1, 2 of 28 files at r2, 11 of 21 files at r3.
Review status: 55 of 104 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/index.less, line 4 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRHcDJeR-RA29VmanX:-KuRHcDJeR-RA29VmanY:b-8yyeri) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-frontend/src/frontend/app/containers/Glossary/index.less#L4)):*
> ```Less
> 
> :root {
>   --GlossaryTitle-fontSize: 1.44rem;
> ```

Should title use a standard font-size from variables?

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/index.less, line 4 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRIApB8cOkFCHX4vbR:-KuRIApB8cOkFCHX4vbS:bohna8w) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-frontend/src/frontend/app/containers/Languages/index.less#L4)):*
> ```Less
> 
> :root {
>   --LanguagesLangCode-fontSize: 0.9rem;
> ```

Should this font size use something from variables.less?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by kathryngo** [comment]
Review status: 55 of 104 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/index.less, line 4 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRHcDJeR-RA29VmanX:-KuRKaiCkwgw4xGKBehQ:blodr5e) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-frontend/src/frontend/app/containers/Glossary/index.less#L4)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should title use a standard font-size from variables?
</blockquote></details>

It's not used elsewhere and is specific to this container, but if I need to use it again then I will move it to the variables file. 

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/index.less, line 4 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRIApB8cOkFCHX4vbR:-KuRKPyxIXTSA5ZMkmff:b-xo502w) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-frontend/src/frontend/app/containers/Languages/index.less#L4)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should this font size use something from variables.less?
</blockquote></details>

It's not used elsewhere and is specific to this container, but if I need to use it again then I will move it to the variables file. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by aeng** [comment]
Reviewed 33 of 105 files at r1, 6 of 28 files at r2, 1 of 21 files at r3.
Review status: 95 of 104 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json, line 57 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRLXO2jSSMYyRg2wbK:-KuRLXO2jSSMYyRg2wbL:b4miu43) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json#L57)):*
> ```JSON
>     "defaultMessage": "{name} has {deletedTranslation}"
>   }
> ]
> ```

Should revert the change

---

*[server/zanata-war/src/main/webapp/resources/fontello/demo.html, line 219 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRLlQJDx-hY1oNJ4XF:-KuRLlQJDx-hY1oNJ4XG:bgh2zkq) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-war/src/main/webapp/resources/fontello/demo.html#L219)):*
> ```HTML
> }
> 
> .container--fluid:before,
> ```

We should not change anything under fontello folder. Its a imported library

---

*[server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml, line 14 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRMhBhV1Yin0w0RWyp:-KuRMhBhV1Yin0w0RWyq:b4q37jl) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml#L14)):*
> ```HTML
>           rendered="#{identity.loggedIn and identity.hasPermission(languageAction.locale, 'manage-language-team')}">
>           <a href="#" class="button button--snug l--push-all-half"
>             id="addMember-btn"
> ```

Do we change the naming standard for ID too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by kathryngo** [comment]
*[server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml, line 14 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRMhBhV1Yin0w0RWyp:-KuRNES-lG8GU40dNQmP:bm5z2c0) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml#L14)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we change the naming standard for ID too?
</blockquote></details>

Not in zanata-war, will start to break things. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by kathryngo** [comment]
*[server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml, line 14 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRMhBhV1Yin0w0RWyp:-KuRNY_P7vBKBLsyeKtt:b-kri4l1) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml#L14)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Not in zanata-war, will start to break things. 
</blockquote></details>

To clarify, difficult to refactor without breaking things. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by kathryngo** [comment]
Review status: 95 of 102 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json, line 57 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRLXO2jSSMYyRg2wbK:-KuROJN4sZo2CdMFrgYL:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json#L57)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should revert the change
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/webapp/resources/fontello/demo.html, line 219 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRLlQJDx-hY1oNJ4XF:-KuROKUPoZ5Oj-qdYgDq:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-war/src/main/webapp/resources/fontello/demo.html#L219)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

We should not change anything under fontello folder. Its a imported library
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r4.
Review status: 95 of 102 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml, line 14 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRMhBhV1Yin0w0RWyp:-KuRPYTfUTNfjvZIcCFD:b-xogifo) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml#L14)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

To clarify, difficult to refactor without breaking things. 
</blockquote></details>

We  should revert this change back to `add-team-member-button` then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by kathryngo** [comment]
Review status: 95 of 102 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml, line 14 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-KuRMhBhV1Yin0w0RWyp:-KuRRqKraog7_ilmHV3f:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/67a1a0309d8e6c7c43ee2549712b8d4561292987/server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml#L14)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

We  should revert this change back to `add-team-member-button` then.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r5.
Review status: 95 of 101 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 105 files at r1, 9 of 21 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-:-KuRVv3nPAkGZXrmBVLu:bnfp4nl)*

**Comment by djansen-redhat** [comment]
Executing a full ft build.

**Comment by djansen-redhat** [comment]
Project glossary alignment issues:
1: project name
2: row items
screenshot from 2017-09-21 14-53-35

**Comment by kathryngo** [comment]
@djansen-redhat ok thanks. Don't know how this slipped past, must of not tested this page in Firefox.

**Comment by kathryngo** [comment]
@djansen-redhat changes made, ready for you to look at again. Alongside fixing the glossary I increased the width of the searchbar on the explore page for mobile views and corrected the colour of the toggles on the project settings page.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-:-KuYa-EkhHTrwFjm-9dj:bozp7w0)*

**Comment by spathare21** [comment]
@kathryngo observe few ui css issues on Chrome and Firefox

1. Cancel button on explore page (Firefox and Chrome)

explore_page_chrome ff

2. Dashboard page on Chrome. 

dashboard_chrome

3. Project page on Chrome.

project_page_chrome

4. Glossary dropdown scroll (Firefox and Chrome)

glossary_dd_chrome_ff

5. Profile page view on Chrome

profile_page_chrome

6. Settinng page on Chrome.

settings_page_chrome


7. Add language (Chrome and Firefox)

add_new_lang_ff_chrome

**Comment by kathryngo** [comment]
@spathare21 please clear your cache, this is not how the branch looks when refreshed.

**Comment by spathare21** [comment]
@kathryngo After clearing cache and with incognito window still I get same result/issues with more issues on dashboard, profile and settings tab. 

Attaching log file as well. 

screenshot from 2017-09-25 12-28-23

screenshot from 2017-09-25 12-28-36

screenshot from 2017-09-25 12-29-57

**Comment by kathryngo** [comment]
@spathare21 try a clean build. it is definitely not the css that has done this. I had this happen to me last week and a private browser window fixed it. what you are seeing are pages that are half loaded. the error logs points to something with your build I think.

**Comment by spathare21** [comment]
@kathryngo ok let me check again

**Comment by kathryngo** [comment]
@spathare21 good luck. If you still have troubles I will try to replicate and fix the issue when I get into the office in the morning

**Comment by spathare21** [comment]
@kathryngo no luck tried clean build using "./build --all -ciQ" but still same, is there any other way to do clean build ?.

**Comment by kathryngo** [comment]
@spathare21 from src/zanata-frontend run mvn clean install

**Comment by kathryngo** [comment]
@spathare21 I tried a clean build the way I usually do it (mentioned in previous comment), and it works for me. I also tried the way you build it and it works, looks fine across browsers in Browserstack also. I really have no idea why you are getting this issue. 
@aeng, @djansen-redhat any ideas?

**Comment by spathare21** [comment]
@kathryngo tested this PR on another pc and it works fine but one issue still shows on language page for add language pop-up

lang

**Comment by kathryngo** [comment]
thanks @spathare21 shall fix that first thing tomorrow

**Comment by kathryngo** [comment]
@spathare21 ready for another check

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 3 of 21 files at r3, 3 of 4 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-:-Kv-syXIFd51tSHZIp3C:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo tested this PR, language dialogue looks good and found another issue  

Firefox browser

screenshot from 2017-09-27 13-26-26

screenshot from 2017-09-27 13-28-30

screenshot from 2017-09-27 13-29-35

Also still facing same issue on my personel lappy not sure whats wrong  will check with Alex/Sean 
@djansen-redhat can you please this pr on your env as well.

**Comment by kathryngo** [comment]
looks like its not built correctly again, at least for the languages page.  can you try a clean build? it should resolve most if not all of these issues like it did before

**Comment by aeng** [comment]
Reviewed 1 of 21 files at r3, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515)*

**Comment by spathare21** [comment]
@kathryngo tried clean build using ./build -c -Q --server from zanata root.  process manager and export UI looks good but still I am seeing the issue on language page for add new language pop-up on chrome and firefox as well. 

screenshot from 2017-09-28 14-20-30


Also observe 1 more issue language page refresh every time we tye keyword in language search bar. 
liek if we enter 'a' and need to enter another char then again we need to click on search box using mouse to enter another character.

**Comment by kathryngo** [comment]
@spathare21 sorry I missed that, shall fix. thank you for looking at this again

**Comment by kathryngo** [comment]
@spathare21 Alongside that fix for the languages drop down, I had to fix some merge conflicts which also meant updating some css for the alpha editor sidebar. (right alignment of 'x' in sidebar titles, colour of Glossary tab text)

**Comment by spathare21** [comment]
@kathryngo looks good i think you missed my last comment this issue still occurs

 language page refresh every time we enter character in language search bar.
like if we enter 'a' and need to enter another char then again we need to click on search box using the mouse to enter another character.

**Comment by kathryngo** [comment]
That is not something I can fix in css and is out of the scope of this PR. Could you please log an issue in Jira for this so one of the other team members can look at this?

**Comment by spathare21** [comment]
yes sure, then marking this PR as verified

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 21 files at r3, 4 of 7 files at r9, 3 of 3 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/515#-:-KvUCpJEgpyP5JWqJyAn:bnfp4nl)*

**Comment by kathryngo** [comment]
@aeng am I right to merged this despite the code cov failure above?

**Pull request merged**
