### PR TITLE
Add Maven Wrapper, clean up tests for Jenkins Pipeline

### PR DESCRIPTION
**Pull request by seanf**
Various changes and fixes needed for https://github.com/zanata/zanata-platform/pull/2

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/11)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.mvn/wrapper/maven-wrapper.jar, line 0 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/11#-KUzSHU_53VmNqKHtTDs:-KUzSHUam6yMLPHwMrKp:b-a108dt) ([raw file](https://github.com/zanata/zanata-platform/blob/9c4b9de5cb16a97b9bd702d5164dc7bad363713f/.mvn/wrapper/maven-wrapper.jar#L0)):*
do we have to commit a jar into git?

---

*[server/functional-test/src/main/java/org/zanata/util/MavenHome.java, line 37 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/11#-KUzRDppdFuiN7aC6QPs:-KUzRDppdFuiN7aC6QPt:b-sgl2np) ([raw file](https://github.com/zanata/zanata-platform/blob/9c4b9de5cb16a97b9bd702d5164dc7bad363713f/server/functional-test/src/main/java/org/zanata/util/MavenHome.java#L37)):*
> ```Java
>         String mavenHome = System.getProperty("maven.home");
>         // TODO will this work on windows (mvn.cmd)?
>         return mavenHome != null ? mavenHome + "/bin/mvn" : "mvn";
> ```

could we use a static field to store the result? We don' t need to check the system property every time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/11)*

**Comment by seanf** [comment]
Review status: 21 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[.mvn/wrapper/maven-wrapper.jar, line  at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/11#-KUzSHU_53VmNqKHtTDs:-KV3TiLJphJ6ZojIfqPL:b-6asy6h) ([raw file](https://github.com/zanata/zanata-platform/blob/9c4b9de5cb16a97b9bd702d5164dc7bad363713f/.mvn/wrapper/maven-wrapper.jar#L)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> do we have to commit a jar into git?
</details>
Yes, it's unavoidable, unfortunately. It's fairly small though, and I think it's worth it to be able to guarantee a specific version of Maven.

---

*[server/functional-test/src/main/java/org/zanata/util/MavenHome.java, line 37 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/11#-KUzRDppdFuiN7aC6QPs:-KV3UlC6PrYmI17hvWwW:bagq6xo) ([raw file](https://github.com/zanata/zanata-platform/blob/9c4b9de5cb16a97b9bd702d5164dc7bad363713f/server/functional-test/src/main/java/org/zanata/util/MavenHome.java#L37)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> could we use a static field to store the result? We don' t need to check the system property every time.
</details>
I doubt it will be a performance issue, but I've changed it anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/11)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/11#-:-KV3VRkbLRPv34op3tV3:b49ms4)*

**Comment by djansen-redhat** [comment]
:+1: This all looks pretty good to me. Thanks for putting in this effort.

**Pull request merged**
