### PR TITLE
fix: duplicate project result in explore page

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-2375

JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/704)

### CODE REVIEW

**Comment by huangp** [comment]
Sean and I have discussed this yesterday. The count query also need to update

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/704#-:-L4IZvrZg_yFrnPZiGkm:b456l92)*

**Comment by huangp** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/dao/ProjectDAO.java, line 126 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/704#-L4IjDjob2wE-6js2tgu:-L4IjDjob2wE-6js2tgv:b155jmh) ([raw file](https://github.com/zanata/zanata-platform/blob/fc96481c2c3a976cba10021c8c8beffc5c2afb53/server/services/src/main/java/org/zanata/dao/ProjectDAO.java#L126)):*
> ```Java
>         q.setCacheable(true)
>                 .setComment("ProjectDAO.getOffsetList")
>                 .setResultTransformer(Criteria.DISTINCT_ROOT_ENTITY);
> ```

I suspect this won't work https://stackoverflow.com/questions/300491/how-to-get-distinct-results-in-hibernate-with-joins-and-row-based-limiting-pagi?noredirect=1&lq=1
There are a couple of answers there. The accepted answer require two queries. Other answers all have people saying not working for them. I think we need to create a private project in the DAOTest to test the distinct and paging both work properly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/704)*

**Comment by aeng** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/dao/ProjectDAO.java, line 126 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/704#-L4IjDjob2wE-6js2tgu:-L4Iq5hRaXXgF1dHl0eN:bcv2h6v) ([raw file](https://github.com/zanata/zanata-platform/blob/fc96481c2c3a976cba10021c8c8beffc5c2afb53/server/services/src/main/java/org/zanata/dao/ProjectDAO.java#L126)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

I suspect this won't work https://stackoverflow.com/questions/300491/how-to-get-distinct-results-in-hibernate-with-joins-and-row-based-limiting-pagi?noredirect=1&lq=1
There are a couple of answers there. The accepted answer require two queries. Other answers all have people saying not working for them. I think we need to create a private project in the DAOTest to test the distinct and paging both work properly
</blockquote></details>

replaced with "distinct" keyword in search query

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/704)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/704#-:-L4IrMFiNu-tDVGP0UxM:b49ms4)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/dao/ProjectDAO.java, line 126 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/704#-L4IjDjob2wE-6js2tgu:-L4IrB5dGK3llAx9S5gD:bsknxgp) ([raw file](https://github.com/zanata/zanata-platform/blob/fc96481c2c3a976cba10021c8c8beffc5c2afb53/server/services/src/main/java/org/zanata/dao/ProjectDAO.java#L126)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

replaced with "distinct" keyword in search query
</blockquote></details>

+1 to the idea of a test for this (eg checking results for projects which have team/locale members)

---

*[server/services/src/main/java/org/zanata/dao/ProjectDAO.java, line 136 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/704#-L4IrMaGS0V69GWas_eP:-L4IrMaH5QRYDJKcAnUy:b-qbq39q) ([raw file](https://github.com/zanata/zanata-platform/blob/f827d21388eee0ad5f10047671964d1823b7d4ce/server/services/src/main/java/org/zanata/dao/ProjectDAO.java#L136)):*
> ```Java
>                 authenticatedAccount.getPerson() : null;
> 
>         String condition = constructFilterCondition(filterOutActive,
> ```

It would be good to add a javadoc comment to constructFilterCondition warning the caller to use `distinct`, owing to the use of left joins in the query.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/704)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/704#-:-L4J1Vo13OBw_bRHvY-l:bnfp4nl)*

**Pull request merged**
