### PR TITLE
refactor(ZNTA-2407) isolate frontend container and component css

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2407

### Containers:
- all have wrapper ID and have this ID applied to css classes used within it

### Components:
- the react-bootstrap components cannot be given a wrapper so the bStrapReact wrapper around the css in style.less will have to suffice 
- the custom-made components will be all given their own wrapper where they have their own less file, otherwise the bstrapReact wrapper is applied so the styling only applies in frontend

### Outcome:
1. the React containers will all be isolated - **done**
2. the bootstrap components css will sit all within the bstrapReact wrapper in style.less  - **done**
3. the custom components will be isolated with ids like the containers where they have their own less file, and in other instances wrapped with the bstrapReact class - **done**
4.  🐛 bug fixes (complete audit of changes to UI to make sure everything works as correctly) - **WIP**
Bug fixes/audit: 
* GWT editor - done
* React editor - done
* JSF frontend - done
* React frontend  - done

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by kathryngo** [comment]
for my reference - fixes to icons needed - classes for styling havent been applied
source-fix
langfix

**Comment by kathryngo** [comment]
arrows-fix

**Comment by kathryngo** [comment]
To Do:
- editor dropdown border fix
- run tests
- final audit

**Comment by efloden** [comment]
Reviewed 2 of 10 files at r1, 24 of 32 files at r2, 1 of 1 files at r3, 6 of 7 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[server/zanata-frontend/src/app/components/Sidebar/index.less, line 3 at r5](https://beta.reviewable.io/reviews/zanata/zanata-platform/753#-L84h2rg14SMQXDxQgAd:-L84h2rg14SMQXDxQgAe:b-x6ayf2) ([raw file](https://github.com/zanata/zanata-platform/blob/c903857706a1ade3fe562265d0e16401d4aaf366/server/zanata-frontend/src/app/components/Sidebar/index.less#L3)):*
> ```Less
> @import "../../styles/variables.less";
> 
> :root {
> ```

Is there a problem caused by using less variables?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/753)*

**Comment by kathryngo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/app/components/Sidebar/index.less, line 3 at r5](https://beta.reviewable.io/reviews/zanata/zanata-platform/753#-L84h2rg14SMQXDxQgAd:-L84mR2zDZw7Rh_t1DGl:b79ii9l) ([raw file](https://github.com/zanata/zanata-platform/blob/c903857706a1ade3fe562265d0e16401d4aaf366/server/zanata-frontend/src/app/components/Sidebar/index.less#L3)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Is there a problem caused by using less variables?
</blockquote></details>

Not in less files

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/753)*

**Comment by efloden** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/753#-:-L8AqQhTuSgyQ77wobv8:bnfp4nl)*

**Comment by efloden** [comment]
Reviewed 1 of 32 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/app/containers/Languages/index.js, line 119 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/753#-L8AuzN8J1aDC3Nub3g1:-L8AuzN8J1aDC3Nub3g2:bjblhru) ([raw file](https://github.com/zanata/zanata-platform/blob/c903857706a1ade3fe562265d0e16401d4aaf366/server/zanata-frontend/src/app/containers/Languages/index.js#L119)):*
> ```JavaScript
>         <div className='u-centerBlock'>
>           <div className='clearfix'
>             id='languages-form'>
> ```

This change breaks several selenium tests: addLanguageAsEnabledByDefault, AddLanguageTest etc. 
There will need to be an identifier on this element for these tests to work, if id='languages-form' is attached to some CSS we don't want we could remove that CSS?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/753)*

**Comment by kathryngo** [comment]
@efloden pretty sure that id needs to stay. I will fix this as soon as I am back. thank you for locating the problem - was looking at the selenium tests thing morning but had difficulty finding the source of the build failures

**Comment by efloden** [comment]
Reviewed 3 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/753)*

**Comment by spathare21** [comment]
Verified all action on page and UI looks fine

**Comment by efloden** [comment]
Reviewed 1 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/753)*

**Pull request merged**
