### PR TITLE
Update to rewrite 3.4.2.Final

### PR DESCRIPTION
**Pull request by seanf**
https://github.com/ocpsoft/rewrite/compare/3.4.1.Final...3.4.2.Final

### CODE REVIEW

**Comment by seanf** [comment]
Created https://github.com/ocpsoft/rewrite/issues/260

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/743#-:-L77hNehpwMcYd_wrLAJ:bnfp4nl)*

**Comment by aeng** [comment]
@seanf built failed

**Comment by seanf** [comment]
> @seanf built failed

The Jenkinsfile succeeded. That was just the useless branch build, which failed because something was missing from Maven Central at the time.

**Pull request merged**
