### PR TITLE
fix(ZNTA-1670): Prevent cli init accidental overwrite of project

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1670

Don't overwrite a project on create, if it already exists!

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/155)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/zanata-client-commands/src/main/java/org/zanata/client/commands/init/ProjectPrompt.java, line 196 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/155#-KapA5mBmqu6g_pQfSFM:-KapA5mBmqu6g_pQfSFN:b-2znacp) ([raw file](https://github.com/zanata/zanata-platform/blob/433247147fcc7a312242ac49262674619193e636/client/zanata-client-commands/src/main/java/org/zanata/client/commands/init/ProjectPrompt.java#L196)):*
> ```Java
>         consoleInteractor.printfln(Question, get("project.id.prompt"));
>         String projectId = consoleInteractor.expectAnyAnswer();
>         while (!validateProjectID(projectId)) {
> ```

Should this be `if` rather than while?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/155)*

**Comment by djansen-redhat** [comment]
@aeng it's a loop, keep asking until they get one that isn't taken. Is there a better way?

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/zanata-client-commands/src/main/java/org/zanata/client/commands/init/ProjectPrompt.java, line 196 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/155#-KapA5mBmqu6g_pQfSFM:-KapFAx1dDUbGLnJ9nt8:b3xmxyi) ([raw file](https://github.com/zanata/zanata-platform/blob/433247147fcc7a312242ac49262674619193e636/client/zanata-client-commands/src/main/java/org/zanata/client/commands/init/ProjectPrompt.java#L196)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Should this be `if` rather than while?
</blockquote></details>

Got it. its a loop for getting project id.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/155#-:-KapFGHCwkKgnPTVUhyC:bnfp4nl)*

**Comment by djansen-redhat** [comment]
- [ ] If create (option 2 is chosen) then an existing project id cannot be used
- [ ] An empty project id cannot be used
- [ ] Script will repeatedly request an id until a valid one is given

**Comment by spathare21** [comment]
@djansen-redhat , can you please provide more details, are you giving same project name,id,version and other config. while creating new project using zanata-cli .

**Comment by djansen-redhat** [comment]
@spathare21 this only affects project id (aka 'slug')

**Comment by spathare21** [comment]
yes got it seen your above comment thanks for quick reply

**Comment by spathare21** [comment]
Verified that it cant take existing project id and it can't be emtpy.

**Pull request merged**
