### PR TITLE
fix: add antd button information to storybook

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: N/A

Add antd button component information to frontend storybook

btn story

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by efloden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/790#-:-LAWCQZV3EuQ1wu98AX-:bnfp4nl)*

**Comment by efloden** [comment]
Might want to ensure the yarn storybook tests have been updated with this change

**Comment by kathryngo** [comment]
@efloden the test is failing due to something I do not understand. I can't work out what I am doing wrong: http://pastebin.test.redhat.com/579764

**Comment by kathryngo** [comment]
on hold because storybook is broken:
```
Summary of all failing tests
 FAIL  .storybook-frontend/storyshots-frontend.test.js (31.881s)
  ● Frontend Storyshots › Button › default

    Invariant Violation: getNodeFromInstance: Invalid argument.

      30 |   }))
      31 |   jest.mock('@storybook/addon-info', () => ({
    > 32 |     // without info, muahahahaha! ��
      33 |     withInfo: (_info) => (story) => story
      34 |   }))
      35 | }
      
      at invariant (node_modules/fbjs/lib/invariant.js:42:15)
      at Object.getNodeFromInstance (node_modules/react-dom/lib/ReactDOMComponentTree.js:162:77)
      at findDOMNode (node_modules/react-dom/lib/findDOMNode.js:49:41)
      at Button.fixTwoCNChar (node_modules/antd/lib/button/button.js:165:50)
      at Button.componentDidMount (node_modules/antd/lib/button/button.js:126:18)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:263:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:209:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:156:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:143:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render (node_modules/react-test-renderer/lib/ReactTestMount.js:128:18)
      at Object.snapshotWithoutDecorators [as test] (.storybook-editor/storyshots-util.js:32:5)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:174:28)
```

**Comment by efloden** [comment]
@kathryngo noticed this error in my branch #799 as well, the jest storyshot tests appear to have some problems with our antd components

**Comment by kathryngo** [comment]
@efloden yep, best to put the PR on hold until we can fix this

**Comment by efloden** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[server/zanata-frontend/src/app/components/Button/Button.story.js, line 6 at r1](https://reviewable.io/reviews/zanata/zanata-platform/790#-LBUXhvG0uCRnO9CWMS8:-LBUXhvG0uCRnO9CWMS9:b-u7lyw9) ([raw file](https://github.com/zanata/zanata-platform/blob/2794fbdd5b0e3bc7491f7b16fd949302da25111b/server/zanata-frontend/src/app/components/Button/Button.story.js#L6)):*
> ```JavaScript
> import {Button} from 'antd'
> storiesOf('Button', module)
>     .add('default', () => (
> ```

Changing this to 'default (no test)' will skip this story in the snapshot tests, not a permanent solution though

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/790)*

**Comment by efloden** [comment]
No problem @kathryngo :lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/790#-:-LBYBSDpCxW6PUahyLvY:b-s9rxuc)*

**Pull request merged**
