### PR TITLE
chore: handle build directory paths containing "@"

### PR DESCRIPTION
**Pull request by seanf**
Another fix for #2 (should have been included in #11).
## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.
- Code quality
  - [ ] Code passes style check (checkstyle/eslint)
  - [ ] Code is clear and concise
  - [ ] UI code is internationalised
  - [ ] Code has adequate comments where appropriate
  - Code is in an appropriate place
    - [ ] Classes are in appropriate packages
    - [ ] Code fits with class's responsibilities (SRP)
  - [ ] Configuration files are documented enough
  - If code is removed
    - [ ] No remaining code references the removed code
      - [ ] No orphaned rewrite rules
    - [ ] No orphaned config settings
    - [ ] No remaining comments refer to the removed code
    - [ ] Unused imports and libraries are removed
- Testing
  - [ ] New code has tests
  - [ ] Changed code has tests
  - [ ] All tests pass
  - [ ] Test coverage stable or increased
- Documentation
  - [ ] New features are documented
  - [ ] Docs removed for deleted features
  - [ ] Docs updated for all changed features
  - [ ] Developer/sysadmin docs updated if appropriate
- If there are new dependencies
  - [ ] Does each new dependency pass all the
     [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?
---

_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/23)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/23#-:-KVALBApnhiLjIkkKegw:b49ms4)*

**Comment by seanf** [comment]
Anything from you @djansen-redhat ?

**Comment by djansen-redhat** [comment]
I got this when pushing:
```
[INFO] pushing source doc [name=pot@example size=2] to server
[==   ][ERROR] Operation failed: javax.ws.rs.NotFoundException: operation to [http://localhost:8080/rest/async/projects/p/gettext/iterations/i/master/r/pot@example?ext=gettext&ext=comment&copyTrans=false] returned 404 (Not Found):

    To retry from the last document, please set the following option(s):

        --from-doc "pot@example"

.
[ERROR] Execution failed: 
java.lang.RuntimeException: javax.ws.rs.NotFoundException: operation to [http://localhost:8080/rest/async/projects/p/gettext/iterations/i/master/r/pot@example?ext=gettext&ext=comment&copyTrans=false] returned 404 (Not Found):
	at org.zanata.client.commands.push.PushCommand.pushCurrentModule(PushCommand.java:458)
	at org.zanata.client.commands.push.PushCommand.run(PushCommand.java:221)
	at org.zanata.client.commands.ConfigurableCommand.runWithActions(ConfigurableCommand.java:110)
	at org.zanata.client.commands.ArgsUtil.runCommand(ArgsUtil.java:48)
	at org.zanata.client.ZanataClient.processArgs(ZanataClient.java:177)
	at org.zanata.client.ZanataClient.main(ZanataClient.java:102)
Caused by: javax.ws.rs.client.ResponseProcessingException: javax.ws.rs.NotFoundException: operation to [http://localhost:8080/rest/async/projects/p/gettext/iterations/i/master/r/pot@example?ext=gettext&ext=comment&copyTrans=false] returned 404 (Not Found):
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:455)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.put(ClientInvocationBuilder.java:177)
	at org.zanata.rest.client.AsyncProcessClient.startSourceDocCreationOrUpdate(AsyncProcessClient.java:75)
	at org.zanata.client.commands.push.PushCommand.pushSrcDocToServer(PushCommand.java:565)
	at org.zanata.client.commands.push.PushCommand.pushCurrentModule(PushCommand.java:406)
	... 5 more
Caused by: javax.ws.rs.NotFoundException: operation to [http://localhost:8080/rest/async/projects/p/gettext/iterations/i/master/r/pot@example?ext=gettext&ext=comment&copyTrans=false] returned 404 (Not Found):
	at org.zanata.rest.client.ResponseStatusFilter.filter(ResponseStatusFilter.java:76)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:447)
	... 9 more

```

**Comment by seanf** [comment]
Okay, thanks @djansen-redhat 
Looks like the code isn't escaping `@` in filenames as it should. That URL should probably use an escaped `@`.

Have you tried `@` in filenames before?

**Comment by djansen-redhat** [comment]
@seanf no, it's admittedly not something I considered a valid filename character - lesson learned.

**Comment by seanf** [comment]
@djansen-redhat I was only trying to fix a build problem, which is running Zanata tests from a directory whose pathname includes "@". I only changed test code, not production code.

But it certainly does look as if Zanata has trouble handling documents which have "@". I think we prevent "@" from appearing in project/iteration slugs, but it looks like we don't do any validation on the document names. We have client and server code which converts between "/" and "," so that we can handle filenames which include "/", but it's a real kludge. It certainly wouldn't handle "," in a filename properly, and it looks like "@" is another, along with others I'm sure. 

For now, we should probably add validation to ensure we only accept doc names we can currently handle. Later on, the entire representation of document names in the DB and the API needs to be overhauled.

@djansen-redhat Would you mind putting some issues into JIRA?

**Comment by djansen-redhat** [comment]
@seanf Ah. A more helpful commit message would be appreciated. :laughing:

**Comment by djansen-redhat** [comment]
Issue for above comment: https://zanata.atlassian.net/browse/ZNTA-1468

**Pull request merged**
