### PR TITLE
feat: project version accumulate statistics

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1954

JIRA issue URL: *paste URL here*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/304)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[client/zanata-rest-client/src/main/java/org/zanata/rest/client/StatisticsResourceClient.java, line 36 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/304#-KjeSf4yYJ6C_QbKc9JH:-KjeSf4yYJ6C_QbKc9JI:b-ntoofd) ([raw file](https://github.com/zanata/zanata-platform/blob/98ae742f463f3aed7799829f5e6a97b2ca310806/client/zanata-rest-client/src/main/java/org/zanata/rest/client/StatisticsResourceClient.java#L36)):*
> ```Java
>  *         href="mailto:pahuang@redhat.com">pahuang@redhat.com</a>
>  */
> public class StatisticsResourceClient {
> ```

I think it's still better to implement the interface. But for that new method you can just put a comment and throw UnsupportedException. It will help in refactoring.

---

*[client/zanata-rest-client/src/test/java/org/zanata/rest/client/StatisticsResourceClientTest.java, line 36 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/304#-KjeT11vK31ZVLg0fkRz:-KjeT11vK31ZVLg0fkS-:buzc58k) ([raw file](https://github.com/zanata/zanata-platform/blob/98ae742f463f3aed7799829f5e6a97b2ca310806/client/zanata-rest-client/src/test/java/org/zanata/rest/client/StatisticsResourceClientTest.java#L36)):*
> ```Java
> import org.zanata.rest.service.StubbingServerRule;
> 
> import javax.ws.rs.core.Response;
> ```

unused?

---

*[server/zanata-war/src/test/java/org/zanata/rest/service/ProjectsServiceTest.java, line 62 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/304#-KjeUYGQqVon87Z-4VUd:-KjeUYGQqVon87Z-4VUe:bk15kct) ([raw file](https://github.com/zanata/zanata-platform/blob/98ae742f463f3aed7799829f5e6a97b2ca310806/server/zanata-war/src/test/java/org/zanata/rest/service/ProjectsServiceTest.java#L62)):*
> ```Java
>         beforeTestOperations.add(new DataSetOperation(
>                 "org/zanata/test/model/ProjectsData.dbunit.xml",
>                 DatabaseOperation.CLEAN_INSERT));
> ```

better to add a afterTestOperation then ClearAllTables again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/304)*

**Comment by aeng** [comment]
@huangp updated the PR.

**Comment by huangp** [comment]
Reviewed 2 of 3 files at r3.
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/zanata-war/src/test/java/org/zanata/rest/service/ProjectsServiceTest.java, line 62 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/304#-KjeUYGQqVon87Z-4VUd:-Kjj_5cgq_TxVxyMoGgq:bcduddm) ([raw file](https://github.com/zanata/zanata-platform/blob/98ae742f463f3aed7799829f5e6a97b2ca310806/server/zanata-war/src/test/java/org/zanata/rest/service/ProjectsServiceTest.java#L62)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

better to add a afterTestOperation then ClearAllTables again
</blockquote></details>

Shouldn't it be "org/zanata/test/model/ClearAllTables.dbunit.xml"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/304)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/304#-:-Kjl5JnmanwIKC03rjWq:b49ms4)*

**Comment by aeng** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-war/src/test/java/org/zanata/rest/service/ProjectsServiceTest.java, line 62 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/304#-KjeUYGQqVon87Z-4VUd:-KjobQkUaCNajwtDW3qY:b-6lrmf5) ([raw file](https://github.com/zanata/zanata-platform/blob/98ae742f463f3aed7799829f5e6a97b2ca310806/server/zanata-war/src/test/java/org/zanata/rest/service/ProjectsServiceTest.java#L62)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Shouldn't it be "org/zanata/test/model/ClearAllTables.dbunit.xml"?
</blockquote></details>

Its only the entry above. beforeTestOperations - ClearAllTables, then ProjectsData

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/304)*

**Comment by spathare21** [comment]
verified it returns the stats of project with rest request  e.g http://localhost:8180/rest/stats/project/zanata-server/version/master/2017-04-01..2017-12-05

**Pull request merged**
