### PR TITLE
Add component creation script

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: there is no JIRA for this, just a weekend project

Adds a script to frontend, so `make component` will ask a few questions then set up a new component in storybook ready for development.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/383)

### CODE REVIEW

**Comment by aeng** [comment]
I think we should update the readme let developers know about this script.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/scripts/codemods/test.template.js, line 18 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/383#-Km9ypph8V_n2xjoycG0:-Km9ypph8V_n2xjoycG1:b39puja) ([raw file](https://github.com/zanata/zanata-platform/blob/a706d267bdb03601f1dd17ba636bac363319ccad/server/zanata-frontend/src/frontend/scripts/codemods/test.template.js#L18)):*
> ```JavaScript
>         onClick={clickFun} />)
>     const expected = ReactDOMServer.renderToStaticMarkup(
>       <div>TODO write a test for markup.</div>
> ```

I like this. Ensure the component comes with test. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/383#-:-Km9zJlklp5yj0K6KgB7:bwx5o4o)*

**Comment by davidmason** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/scripts/codemods/test.template.js, line 18 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/383#-Km9ypph8V_n2xjoycG0:-KmAAFi25XJaj8abcDj8:bpbhu2g) ([raw file](https://github.com/zanata/zanata-platform/blob/a706d267bdb03601f1dd17ba636bac363319ccad/server/zanata-frontend/src/frontend/scripts/codemods/test.template.js#L18)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I like this. Ensure the component comes with test. 
</blockquote></details>

Added in r2.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/383)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/383#-:-KmAAolJ5RxYLHfrCTgr:bnfp4nl)*

**Comment by efloden** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/383#-:-KmAEV2HAj9o2o-Hcu1b:bnfp4nl)*

**Pull request merged**
