### PR TITLE
refactor(ZNTA-2715) replace react-date-range component with antd DatePicker

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2715

Remove react-date-range component and replace with ant design DatePicker
Small styling fixes

### Modal open

cal2

### Modal closed, date range selected

cal1

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by kathryngo** [comment]
@efloden I have got most of this interface refactored without the react-date-range component, and using the antd datepicker component.
However, I am having trouble getting the line graph to populate. Would you mind having a look? Here's what it looks like currently.
calendar

**Comment by spathare21** [comment]
@kathryngo is it possible to align date range properly, also can we replace ~ with To os something else 

screenshot from 2018-07-31 11-57-13

screenshot from 2018-07-31 11-57-24

**Comment by kathryngo** [comment]
@spathare21 cannot replace the ~ as it is part of a third party component but I can fix the alignment of the date range in the modal

**Comment by kathryngo** [comment]
@spathare21 fixed. could only align the date to the first half of the modal
cal-date-align

**Pull request merged**
