### PR TITLE
chore: run Zanata and DB via docker-compose

### PR DESCRIPTION
**Pull request by seanf**
Revival of https://github.com/zanata/zanata-platform/pull/198

Note to QA: this change introduces `rundev2.sh` which works much the same as `rundev.sh` but with fewer options. It also starts and stops the database automatically.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/548)

### CODE REVIEW

**Comment by seanf** [comment]
@carlosmunoz This is a rebase of #198 (which you reviewed) with just one new commit, 4eb5a60.

**Comment by carlosmunoz** [comment]
Still looks good. Perhaps the only thing to note is that there is no guarantee that the database will be up before the Jboss server attempts to connect to it. In practice it should be ready as the jboss server is not the quickest to start.

---

Reviewed 5 of 7 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/548#-:-KvXYcV4e7DaaivZ82XV:bazrbv6)*

**Comment by seanf** [comment]
@carlosmunoz No_QA?

**Comment by seanf** [comment]
@carlosmunoz Another review please?

Re: the database startup problem, I'm suggesting we ignore that problem for now, and uncomment the `healthcheck` in `docker-compose.yml` when Fedora 27 is out (because F26 and F27's docker-compose will support `healthcheck`, but F25 doesn't).

**Comment by carlosmunoz** [comment]
Reviewed 1 of 7 files at r3, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/548)*

**Comment by carlosmunoz** [comment]
Reviewed. 
Um... why not just enable it and make it clear this will only work with a specific version of docker-compose. If you are on Fedora 25, then you either need to upgrade, or manually install a latest version of docker compose. Lets just enable it and benefit from it starting now.

**Comment by seanf** [comment]
@carlosmunoz Thanks.

For one thing, _I'm_ still on Fedora 25. (And I'm not sure it's easy to install docker.io's docker-compose without breaking Fedora's docker installation.)

**Comment by carlosmunoz** [comment]
I went with docker.io's one when I was on F25. You definitely don't want to try and set them both up, but then again, why would you want both versions, if you have the most recent one? Stop being so cautious and upgrade to F26 already :stuck_out_tongue:

**Pull request merged**
