### PR TITLE
fix: update API key generation

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1325

JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/645)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/645#-:-L1ubVxVjAHoyxcKXXxw:b49ms4)*

**Comment by huangp** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/645)*

**Comment by huangp** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/dao/AccountDAO.java, line 90 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/645#-L1yRGb0vWZyR9_PkWSX:-L1yRGb3uVT7pfQipqOL:bi2aq95) ([raw file](https://github.com/zanata/zanata-platform/blob/9cf019cf0a5e0a1e75c3c80e8fae64dc939c3c29/server/services/src/main/java/org/zanata/dao/AccountDAO.java#L90)):*
> ```Java
>     }
> 
>     protected static String createSaltedApiKey() {
> ```

We no longer use salt. Might rename this method to be clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/645)*

**Comment by aeng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/dao/AccountDAO.java, line 90 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/645#-L1yRGb0vWZyR9_PkWSX:-L1yUsTyLlGHme2fDLNi:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/9cf019cf0a5e0a1e75c3c80e8fae64dc939c3c29/server/services/src/main/java/org/zanata/dao/AccountDAO.java#L90)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

We no longer use salt. Might rename this method to be clear.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/645)*

**Comment by huangp** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/645)*

**Comment by huangp** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/645#-:-L1yV6COVgmMU8e_PfJz:bnfp4nl)*

**Comment by spathare21** [comment]
here i checked that the API key is generated correctly and working with client

**Pull request merged**
