### PR TITLE
test(E2E): Create a user end-to-end test and add sub-suites

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: n/a

Create an E2E test for the purpose of streamlining PR builds

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/206)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 5 of 30 files at r1, 11 of 25 files at r2.
Review status: 16 of 48 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java, line 357 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/206#-Kdi72d8OUvqrNHs1cyC:-Kdi72d8OUvqrNHs1cyD:bb7jn98) ([raw file](https://github.com/zanata/zanata-platform/blob/fb91a657bc6a8fbad0acf48134bc70fdadeddca1/server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java#L357)):*
> ```Java
>         HashMap<String, Object> prefs = new HashMap<>();
>         prefs.put("profile.default_content_settings.popups", 0);
>         prefs.put("download.default_directory", "/tmp/");
> ```

Could you please add comments and links to docs for these settings?

---

*[server/functional-test/src/test/java/org/zanata/feature/account/AccountTestSuite.java, line 16 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/206#-Kdi7azPSnRMzqPlb_eS:-Kdi7azPSnRMzqPlb_eT:b4gr8al) ([raw file](https://github.com/zanata/zanata-platform/blob/fb91a657bc6a8fbad0acf48134bc70fdadeddca1/server/functional-test/src/test/java/org/zanata/feature/account/AccountTestSuite.java#L16)):*
> ```Java
>     EmailValidationTest.class
> })
> public class AccountTestSuite {
> ```

I think it's time we had a README explaining what all the suites are for. 

The readme could also explain the general rationale of the functional testing approach. I was under the impression you were creating two big tests, one for user, one for admin, but now it seems they might be suites (which sounds better but slower).

---

*[server/functional-test/src/test/java/org/zanata/feature/account/ChangePasswordTest.java, line 54 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/206#-Kdi7pcW7muq4Ur6jMqX:-Kdi7pcXSl5HYegKsh1M:bkpvd56) ([raw file](https://github.com/zanata/zanata-platform/blob/103f3eaaf7acba0e7791125c77bc8a7b0f64083d/server/functional-test/src/test/java/org/zanata/feature/account/ChangePasswordTest.java#L54)):*
> ```Java
>             tcmsTestPlanIds = 5316, tcmsTestCaseIds = 86823)
>     @Test(timeout = ZanataTestCase.MAX_SHORT_TEST_DURATION)
>     @Category(BasicAcceptanceTest.class)
> ```

I see some tests (like this) were removed from BAT suite, but the BAT suite class wasn't. Is that intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/206)*

**Comment by djansen-redhat** [comment]
*[server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java, line 357 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/206#-Kdi72d8OUvqrNHs1cyC:-KdiLR743w0I6ADLPBF_:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/fb91a657bc6a8fbad0acf48134bc70fdadeddca1/server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java#L357)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Could you please add comments and links to docs for these settings?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/206)*

**Comment by djansen-redhat** [comment]
*[server/functional-test/src/test/java/org/zanata/feature/account/AccountTestSuite.java, line 16 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/206#-Kdi7azPSnRMzqPlb_eS:-KdiM7VpD3zmD1i0KXn3:br7rrr4) ([raw file](https://github.com/zanata/zanata-platform/blob/fb91a657bc6a8fbad0acf48134bc70fdadeddca1/server/functional-test/src/test/java/org/zanata/feature/account/AccountTestSuite.java#L16)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I think it's time we had a README explaining what all the suites are for. 

The readme could also explain the general rationale of the functional testing approach. I was under the impression you were creating two big tests, one for user, one for admin, but now it seems they might be suites (which sounds better but slower).
</blockquote></details>

All the "contexts" are suites, with top level BAT/Detailed suites.
By context, I mean Account, Admin, Security etc are suites, as well as one for EndToEnd. Ideally the dev can specify "Account" somewhere in his PR to suggest running the BAT + Account tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/206)*

**Comment by djansen-redhat** [comment]
*[server/functional-test/src/test/java/org/zanata/feature/account/ChangePasswordTest.java, line 54 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/206#-Kdi7pcW7muq4Ur6jMqX:-KdiLaD9wQvnn4dJySnA:bh5dtm2) ([raw file](https://github.com/zanata/zanata-platform/blob/103f3eaaf7acba0e7791125c77bc8a7b0f64083d/server/functional-test/src/test/java/org/zanata/feature/account/ChangePasswordTest.java#L54)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I see some tests (like this) were removed from BAT suite, but the BAT suite class wasn't. Is that intentional?
</blockquote></details>

Yes. Only the two User/AdminEndToEndTest cases are now BAT. All others will be Detailed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/206)*

**Comment by djansen-redhat** [comment]
*[server/functional-test/src/test/java/org/zanata/feature/account/AccountTestSuite.java, line 16 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/206#-Kdi7azPSnRMzqPlb_eS:-KdnPPoxs6FGmBc-VoHa:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/fb91a657bc6a8fbad0acf48134bc70fdadeddca1/server/functional-test/src/test/java/org/zanata/feature/account/AccountTestSuite.java#L16)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

All the "contexts" are suites, with top level BAT/Detailed suites.
By context, I mean Account, Admin, Security etc are suites, as well as one for EndToEnd. Ideally the dev can specify "Account" somewhere in his PR to suggest running the BAT + Account tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/206)*

**Comment by djansen-redhat** [comment]
@seanf added some docs

**Comment by seanf** [comment]
Good readme. 

I would just suggest adding a comment to each end-to-end test explaining the reason for piling in so many different things into one test (ie performance).

I wonder if we should boost the flaky retries a bit. A longer test is more likely to bump into Selenium's flakiness.

---

Reviewed 19 of 30 files at r1, 14 of 25 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/functional-test/README.md, line 17 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/206#-KdxpiQRQllNUlKpDWYr:-KdxpiQRQllNUlKpDWYs:blve7lg) ([raw file](https://github.com/zanata/zanata-platform/blob/f2af254a2cc4ae5ece99078f7ad7846eb478a4ce/server/functional-test/README.md#L17)):*
> ```Markdown
> When successful, a `[INFO] Press Ctrl-C to stop the container...` message will show to indicate the
> container is running and ready to accept connections.<br>
> If desired, the instance can be accessed from a browser at [http://localhost:8180/zanata]()
> ```

Is it still /zanata? Unfortunate.

---

*[server/functional-test/README.md, line 41 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/206#-KdxpxrGT9IN5OF6x2ou:-KdxpxrGT9IN5OF6x2ov:b-t2sgw2) ([raw file](https://github.com/zanata/zanata-platform/blob/f2af254a2cc4ae5ece99078f7ad7846eb478a4ce/server/functional-test/README.md#L41)):*
> ```Markdown
> recognised behaviour - such as `new LoginWorkFlow().signInAs("admin", "admin)`.  These are a good
> way to start a test, placing the action in a predictable location without too many repetitive lines in
> the test itself.
> ```

Did we come up with workflows, or are they another documented Selenium pattern (like the use of page objects)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/206#-:-KdxqqUJlVmWPeP7TmhK:bi91jv4)*

**Comment by djansen-redhat** [comment]
@seanf will do.  
I think (hope) the flakiness will actually be less, as there is not a great deal of bouncing about in cleanup, before and after functions.

> Is it still /zanata? Unfortunate.

Seems that way

> Did we come up with workflows, or are they another documented Selenium pattern (like the use of page objects)?

This was set up by @huangp and seemed to be quite useful. With a bit of searching it doesn't seem to be commented on in any great detail, and I can't say I've used it myself previously.

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 25 files at r2, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/206#-:-KdyN_Gam3f7IPIL7nf0:bnfp4nl)*

**Pull request merged**
