### PR TITLE
ZNTA-1255 - enable debug logging for Weld msg with 'Catching'

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: _[https://zanata.atlassian.net/browse/ZNTA-1255]_

This will enable debug logging for and CDI related errors. To reproduce a "ERROR log: WELD-000019 Error destroying an instance org.zanata.security.ZanataIdentity" error log, sign in, visit settings page, then log out. You should see detailed stacktrace logged _in the file_ (console log has threshold of INFO)
## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.
- Code quality
  - [ ] Code passes style check (checkstyle/eslint)
  - [ ] Code is clear and concise
  - [ ] UI code is internationalised
  - [ ] Code has adequate comments where appropriate
  - Code is in an appropriate place
    - [ ] Classes are in appropriate packages
    - [ ] Code fits with class's responsibilities (SRP)
  - [ ] Configuration files are documented enough
  - If code is removed
    - [ ] No remaining code references the removed code
      - [ ] No orphaned rewrite rules
    - [ ] No orphaned config settings
    - [ ] No remaining comments refer to the removed code
    - [ ] Unused imports and libraries are removed
- Testing
  - [ ] New code has tests
  - [ ] Changed code has tests
  - [ ] All tests pass
  - [ ] Test coverage stable or increased
- Documentation
  - [ ] New features are documented
  - [ ] Docs removed for deleted features
  - [ ] Docs updated for all changed features
  - [ ] Developer/sysadmin docs updated if appropriate
- If there are new dependencies
  - [ ] Does each new dependency pass all the
     [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?
---

_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/7)

### CODE REVIEW

**Comment by seanf** [comment]
There seems to be a typo in the sentence "This will enable debug logging for and CDI related errors. "

We don't want to turn on DEBUG logging for all of Weld, just normal logging plus exceptions.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/docker/conf/standalone.xml, line 140 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtCuZvExN-rzrzO9uy:-KUtCuZvExN-rzrzO9uz:b5mdlkg) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L140)):*
> ```XML
>             <logger category="org.jboss.as.server.deployment">
>                 <level name="DEBUG"/>
>                 <filter-spec value="not(any( match(&quot;JBAS015960&quot;), match(&quot;JBAS015893&quot;) ))"/>
> ```

We should try to be consistent with the ordering of these elements. I suggest sorting `filter-spec` before `level`.

Also, do we really want this to be `DEBUG`? Wouldn't `WARN` be enough here?

---

*[server/docker/conf/standalone.xml, line 152 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtD86XK-ZygvSP5eSO:-KUtD86XK-ZygvSP5eSP:b-bhg3yg) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L152)):*
> ```XML
>             
>             <logger category="org.richfaces.log.Application">
>                 <filter-spec value="not( match(&quot;JMS API was found on the classpath&quot;) )"/>
> ```

I guess we have the same verbosity problem here, given that `level` is apparently not being inherited? Perhaps we should add `<level name="WARN" />` wherever `filter-spec` is found alone.

---

*[server/docker/conf/standalone.xml, line 160 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtEMPYubd78ewF8Ibv:-KUtEMPYubd78ewF8Ibw:b-lac6lk) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L160)):*
> ```XML
>             <logger category="org.jboss.weld">
>                 <filter-spec value="match(&quot;.*Catching.*&quot;)"/>
>                 <level name="DEBUG" />
> ```

Isn't this going to block all other messages from Weld, besides "Catching"?

We may need a more complex filter expression. See https://docs.jboss.org/author/display/WFLY10/Logging+Configuration#LoggingConfiguration-FilterExpressions

Perhcaps `any(match(&quot;.*Catching.*&quot;), levels(INFO, WARN, ERROR))` would work. (I'm not sure if quotes are required around the level names.)

Or even something using `levelChange` to boost "Catching" messages to `WARN`. See https://developer.jboss.org/thread/230458

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-:-KUtDz8lGDPwpv9emRdB:b-iqedhd)*

**Comment by huangp** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/docker/conf/standalone.xml, line 140 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtCuZvExN-rzrzO9uy:-KUu3pqgjhKFX1hu4nFR:bfea2ot) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L140)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> We should try to be consistent with the ordering of these elements. I suggest sorting `filter-spec` before `level`.
> 
> Also, do we really want this to be `DEBUG`? Wouldn't `WARN` be enough here?
</details>
I don't know what's the original purpose of this category so I don't really know the answer. I put debug here just to stop all those directory scanning trace log. If you think warn is enough then I will change it to warn.

---

*[server/docker/conf/standalone.xml, line 152 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtD86XK-ZygvSP5eSO:-KUu4A-V8W2Dnp1AfW4p:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L152)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I guess we have the same verbosity problem here, given that `level` is apparently not being inherited? Perhaps we should add `<level name="WARN" />` wherever `filter-spec` is found alone.
</details>
Done.

---

*[server/docker/conf/standalone.xml, line 160 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtEMPYubd78ewF8Ibv:-KUuG0I0RtlJaJl91Pul:b-q2cts2) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L160)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Isn't this going to block all other messages from Weld, besides "Catching"?
> 
> We may need a more complex filter expression. See https://docs.jboss.org/author/display/WFLY10/Logging+Configuration#LoggingConfiguration-FilterExpressions
> 
> Perhcaps `any(match(&quot;.*Catching.*&quot;), levels(INFO, WARN, ERROR))` would work. (I'm not sure if quotes are required around the level names.)
> 
> Or even something using `levelChange` to boost "Catching" messages to `WARN`. See https://developer.jboss.org/thread/230458
</details>
After a bit of testing this is not going to block other messages. I think the root logger will eventually catch and log them. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7)*

**Comment by seanf** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/docker/conf/standalone.xml, line 140 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtCuZvExN-rzrzO9uy:-KUuT_YbT3B3L1oQ1Z__:b-huheqk) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L140)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> I don't know what's the original purpose of this category so I don't really know the answer. I put debug here just to stop all those directory scanning trace log. If you think warn is enough then I will change it to warn.
</details>
Well, you've exposed a bug in the logging config. The idea was just to block certain messages, *not* to make the logging really verbose.

---

*[server/docker/conf/standalone.xml, line 160 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtEMPYubd78ewF8Ibv:-KUuXbpmHFPtmcIB39vl:bpic710) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L160)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> After a bit of testing this is not going to block other messages. I think the root logger will eventually catch and log them. 
</details>
But if that's the case, we shouldn't have had to add `<level name="WARN" />` to the other loggers which use `filter-spec`. Something seems fishy.

How would you explain the behaviour you've seen? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7)*

**Comment by huangp** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/docker/conf/standalone.xml, line 160 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtEMPYubd78ewF8Ibv:-KUy9bdrG_kYxUTOrL7B:boe36wb) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L160)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> But if that's the case, we shouldn't have had to add `<level name="WARN" />` to the other loggers which use `filter-spec`. Something seems fishy.
> 
> How would you explain the behaviour you've seen? 
</details>
If we don't put ```<level name="WARN" />``` to other logger with filter spec, it will mean, for anything matching the filter spec, regardless its log level, I want you to log it.  The verbose disk scanning log does not have word ```JBAS015960``` (matching the filter spec) and it's at level TRACE, so it's logged. I think the bug we have in our log config was because of our filter spec (not match something). It means anything other than those we want to disable will get logged regardless level.

For org.jboss.weld category, if a log matches the word "Catching", the log level is debug according to this config so it gets logged. For a log with org.jboss.weld that is at info or error level but without the word "Catching", it does not satisfy this config entry but it satisfy the root logger. So it still gets logged. 

This is my understanding though. From observation this is what happened.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7)*

**Comment by huangp** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/docker/conf/standalone.xml, line 160 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtEMPYubd78ewF8Ibv:-KV2KUjdcNSpaRd7iuoZ:b-rlntta) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L160)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> If we don't put ```<level name="WARN" />``` to other logger with filter spec, it will mean, for anything matching the filter spec, regardless its log level, I want you to log it.  The verbose disk scanning log does not have word ```JBAS015960``` (matching the filter spec) and it's at level TRACE, so it's logged. I think the bug we have in our log config was because of our filter spec (not match something). It means anything other than those we want to disable will get logged regardless level.
> 
> For org.jboss.weld category, if a log matches the word "Catching", the log level is debug according to this config so it gets logged. For a log with org.jboss.weld that is at info or error level but without the word "Catching", it does not satisfy this config entry but it satisfy the root logger. So it still gets logged. 
> 
> This is my understanding though. From observation this is what happened.
</details>
I will take it back. It shouldn't go to root logger. But the two conditions (log level, filter spec) may be disjunction?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7)*

**Comment by seanf** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/docker/conf/standalone.xml, line 160 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtEMPYubd78ewF8Ibv:-KV8V6kpAtGSjWhCotBA:b3i5rxn) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L160)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> I will take it back. It shouldn't go to root logger. But the two conditions (log level, filter spec) may be disjunction?  
</details>
Okay, I ran some tests with a modified wildfly helloworld project. From my testing of JBoss Logging:

* If a `<filter-spec>` is present, the `<level>` filter from root is ignored. This is why our filter-specs caused extra unwanted logging, as you discovered.
* If both `<level>` and `<filter-spec>` are present on a logger, a message only goes through if it passes *both* the level filter and the filter-spec filter. 
* `levelChange` only seems useful for changing the level of a message which already passes a filter (eg downgrade a warning to info), not for helping a message to pass a filter

*So* if we're trying to let some DEBUG Catching messages through, we can't use `<level name="WARN" />` or `<level name="INFO" />`, nor will `levelChange(WARN)` help.

I think we need to use this sort of pattern in general:

    <filter-spec value="all(any(levelRange[INFO, ERROR], match(&quot;.*WANTED.*&quot;)), not(match(&quot;.*UNWANTED.*&quot;)))"/>

which in this case can be simplified to:

    <filter-spec value="any(levelRange[INFO, ERROR], match(&quot;.*WANTED.*&quot;))"/>

but we *can't* use this here:

    <filter-spec value="match(&quot;.*WANTED.*&quot;)"/>
    <level name="INFO"/>

However, for the other cases (where we just want to block some messages), we can do this:

    <filter-spec value="not(match(&quot;.*UNWANTED.*&quot;))"/>
    <level name="INFO"/>

---

*[server/docker/conf/standalone.xml, line 140 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KV8b6lW_hF7zv6Lp1jw:-KV8b6lW_hF7zv6Lp1jx:b-4f3qeu) ([raw file](https://github.com/zanata/zanata-platform/blob/fae1e6ca9d6ae7793ca4a21c160a1f72f89be0e1/server/docker/conf/standalone.xml#L140)):*
> ```XML
>             <logger category="org.jboss.as.server.deployment">
>                 <filter-spec value="not(any( match(&quot;JBAS015960&quot;), match(&quot;JBAS015893&quot;) ))"/>
>                 <level name="WARN"/>
> ```

Sorry, I should have said INFO, since that's what we have on the root logger.

---

*[server/docker/conf/standalone.xml, line 153 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KV8b9ork-uXNnnJbywu:-KV8b9ork-uXNnnJbywv:b-4f3qeu) ([raw file](https://github.com/zanata/zanata-platform/blob/fae1e6ca9d6ae7793ca4a21c160a1f72f89be0e1/server/docker/conf/standalone.xml#L153)):*
> ```XML
>             <logger category="org.richfaces.log.Application">
>                 <filter-spec value="not( match(&quot;JMS API was found on the classpath&quot;) )"/>
>                 <level name="WARN" />
> ```

Sorry, I should have said INFO, since that's what we have on the root logger.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7)*

**Comment by huangp** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/docker/conf/standalone.xml, line 160 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtEMPYubd78ewF8Ibv:-KVN-ZpCVan3V920CyH5:bsamndp) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L160)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Okay, I ran some tests with a modified wildfly helloworld project. From my testing of JBoss Logging:
> 
> * If a `<filter-spec>` is present, the `<level>` filter from root is ignored. This is why our filter-specs caused extra unwanted logging, as you discovered.
> * If both `<level>` and `<filter-spec>` are present on a logger, a message only goes through if it passes *both* the level filter and the filter-spec filter. 
> * `levelChange` only seems useful for changing the level of a message which already passes a filter (eg downgrade a warning to info), not for helping a message to pass a filter
> 
> *So* if we're trying to let some DEBUG Catching messages through, we can't use `<level name="WARN" />` or `<level name="INFO" />`, nor will `levelChange(WARN)` help.
> 
> I think we need to use this sort of pattern in general:
> 
>     <filter-spec value="all(any(levelRange[INFO, ERROR], match(&quot;.*WANTED.*&quot;)), not(match(&quot;.*UNWANTED.*&quot;)))"/>
> 
> which in this case can be simplified to:
> 
>     <filter-spec value="any(levelRange[INFO, ERROR], match(&quot;.*WANTED.*&quot;))"/>
> 
> but we *can't* use this here:
> 
>     <filter-spec value="match(&quot;.*WANTED.*&quot;)"/>
>     <level name="INFO"/>
> 
> However, for the other cases (where we just want to block some messages), we can do this:
> 
>     <filter-spec value="not(match(&quot;.*UNWANTED.*&quot;))"/>
>     <level name="INFO"/>
> 
</details>
With my current config, I do get both ERROR and DEBUG logging (the error log does not contain the word "Cathcing")
```
2016-10-30 23:51:15,672 ERROR [org.jboss.weld.Bean] (default task-43) WELD-000019: Error destroying an instance org.zanata.security.ZanataIdentity$Proxy$_$$_WeldSubclass@7cb835f7 of Managed Bean [class org.zanata.security.ZanataIdentity] with qualifiers [@Default @Named @Any]
2016-10-30 23:51:15,678 DEBUG [org.jboss.weld.Bean] (default task-43) Catching: org.jboss.weld.context.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped
	at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:689) [weld-core-impl-2.3.5.Final.jar:2.3.5.Final]
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:90) [weld-core-impl-2.3.5.Final.jar:2.3.5.Final]
```
I am curious how your test works differently. Adding a ```any(levelRange[INFO, FATAL], match(...))``` would definitely be more explicit though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7)*

**Comment by seanf** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/docker/conf/standalone.xml, line 160 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtEMPYubd78ewF8Ibv:-KVN5eg8a5FLmFsvtZOY:b-iw8xa6) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L160)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> With my current config, I do get both ERROR and DEBUG logging (the error log does not contain the word "Cathcing")
> ```
> 2016-10-30 23:51:15,672 ERROR [org.jboss.weld.Bean] (default task-43) WELD-000019: Error destroying an instance org.zanata.security.ZanataIdentity$Proxy$_$$_WeldSubclass@7cb835f7 of Managed Bean [class org.zanata.security.ZanataIdentity] with qualifiers [@Default @Named @Any]
> 2016-10-30 23:51:15,678 DEBUG [org.jboss.weld.Bean] (default task-43) Catching: org.jboss.weld.context.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped
> 	at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:689) [weld-core-impl-2.3.5.Final.jar:2.3.5.Final]
> 	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:90) [weld-core-impl-2.3.5.Final.jar:2.3.5.Final]
> ```
> I am curious how your test works differently. Adding a ```any(levelRange[INFO, FATAL], match(...))``` would definitely be more explicit though.
</details>
I was testing with WildFly 10.1. I can give you the `standalone.xml` and modified `HelloWorldServlet.java` if you want them.

This stuff doesn't seem to be fully documented, so it wouldn't surprise me if the behaviour changes from one version of JBoss Logging to another (eg the interaction between `<level>` and `<filter-spec>`, or the inheritance of ROOT's `level`). 

To be safe, I think we should avoid using `<level>` and `<filter-spec>` together anywhere, and just use a `filter-spec` that includes `match` and `levelRange`. That way there's no ambiguity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7)*

**Comment by huangp** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/docker/conf/standalone.xml, line 160 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtEMPYubd78ewF8Ibv:-KVN8BzPPr3dwSKXpB70:bo650rm) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L160)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I was testing with WildFly 10.1. I can give you the `standalone.xml` and modified `HelloWorldServlet.java` if you want them.
> 
> This stuff doesn't seem to be fully documented, so it wouldn't surprise me if the behaviour changes from one version of JBoss Logging to another (eg the interaction between `<level>` and `<filter-spec>`, or the inheritance of ROOT's `level`). 
> 
> To be safe, I think we should avoid using `<level>` and `<filter-spec>` together anywhere, and just use a `filter-spec` that includes `match` and `levelRange`. That way there's no ambiguity.
</details>
If I took out level and only use filter spec (with match and level range), it start to log everything (trace messages start to appear in log).  I am testing with zanata docker image which is also wildfly 10.1..0.Final. I will stick with the safer option (both level and filter-spec and filter spec also has levelRange). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7)*

**Comment by seanf** [comment]
Reviewed 3 of 5 files at r3.
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/docker/conf/standalone.xml, line 160 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KUtEMPYubd78ewF8Ibv:-KVNR9XeteYNbviXHajf:blatpa8) ([raw file](https://github.com/zanata/zanata-platform/blob/1798b415b6cbc2dde4bcb2c9ac6ef3a79b97aff6/server/docker/conf/standalone.xml#L160)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> If I took out level and only use filter spec (with match and level range), it start to log everything (trace messages start to appear in log).  I am testing with zanata docker image which is also wildfly 10.1..0.Final. I will stick with the safer option (both level and filter-spec and filter spec also has levelRange). 
</details>
Weird. Okay.

---

*[server/functional-test/src/test/resources/conf/standalone.xml, line 121 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KVNQzgILCjw0j88jsEO:-KVNQzgJ5Y4-8tZZfOxq:b3hur69) ([raw file](https://github.com/zanata/zanata-platform/blob/a2a6ecf8d2a2826f42e91485f0236a392086cb64/server/functional-test/src/test/resources/conf/standalone.xml#L121)):*
> ```XML
>             <logger category="org.jboss.as.server.deployment">
>                 <filter-spec value="not(any( match(&quot;JBAS015960&quot;), match(&quot;JBAS015893&quot;) ))"/>
>                 <level name="INFO"/>
> ```

We should keep the indentation at 2 in this file.

---

*[server/zanata-war/src/test/resources/arquillian/standalone-arquillian.xml, line 139 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KVNRIkNonKQSKtqNiQb:-KVNRIkOAHzCVTgHMqzF:b-90fcpc) ([raw file](https://github.com/zanata/zanata-platform/blob/a2a6ecf8d2a2826f42e91485f0236a392086cb64/server/zanata-war/src/test/resources/arquillian/standalone-arquillian.xml#L139)):*
> ```XML
>             <logger category="org.jboss.weld">
>                 <filter-spec value="any(match(&quot;.*Catching.*&quot;), levelRange[INFO, FATAL])"/>
>                 <level name="DEBUG" />
> ```

This file seems to be using indentation of 2 as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7)*

**Comment by huangp** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/functional-test/src/test/resources/conf/standalone.xml, line 121 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KVNQzgILCjw0j88jsEO:-KVNXIbyNTp4cVs3XcLd:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/a2a6ecf8d2a2826f42e91485f0236a392086cb64/server/functional-test/src/test/resources/conf/standalone.xml#L121)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> We should keep the indentation at 2 in this file.
</details>
Done.

---

*[server/zanata-war/src/test/resources/arquillian/standalone-arquillian.xml, line 139 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KVNRIkNonKQSKtqNiQb:-KVNXJILrPRanhiyEko_:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/a2a6ecf8d2a2826f42e91485f0236a392086cb64/server/zanata-war/src/test/resources/arquillian/standalone-arquillian.xml#L139)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> This file seems to be using indentation of 2 as well.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7)*

**Comment by huangp** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/docker/conf/standalone.xml, line 140 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KV8b6lW_hF7zv6Lp1jw:-KVNXLvLpN3MaY7YTTYv:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/fae1e6ca9d6ae7793ca4a21c160a1f72f89be0e1/server/docker/conf/standalone.xml#L140)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Sorry, I should have said INFO, since that's what we have on the root logger.
</details>
Done.

---

*[server/docker/conf/standalone.xml, line 153 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/7#-KV8b9ork-uXNnnJbywu:-KVNXMPtsG0R-Krg288f:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/fae1e6ca9d6ae7793ca4a21c160a1f72f89be0e1/server/docker/conf/standalone.xml#L153)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Sorry, I should have said INFO, since that's what we have on the root logger.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/7)*

**Comment by seanf** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:white_check_mark: I'm fine with this

**Pull request merged**
