### PR TITLE
feat: allow src locale selection in tmx export 

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1771

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/459)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 39 of 41 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/service/LocalesResource.java, line 81 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-KqRaeSEGMy9TvujAIvN:-KqRaeSEGMy9TvujAIvO:b3dnp9t) ([raw file](https://github.com/zanata/zanata-platform/blob/731e9334feefbc0d211138561ceb473539820fbe/api/zanata-common-api/src/main/java/org/zanata/rest/service/LocalesResource.java#L81)):*
> ```Java
> 
>     /**
>      * Returns list of active source locales of all documents for all active projects.
> ```

Should we add to the doc this is only available to admin?

---

*[server/zanata-frontend/src/frontend/app/actions/tmx-actions.js, line 85 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-KqVB9odKGoL4QkYXTxT:-KqVB9odKGoL4QkYXTxU:bc3zxng) ([raw file](https://github.com/zanata/zanata-platform/blob/731e9334feefbc0d211138561ceb473539820fbe/server/zanata-frontend/src/frontend/app/actions/tmx-actions.js#L85)):*
> ```JavaScript
>       if ((project || !isUndefined(project)) &&
>           (!version || isUndefined(version))) {
>         type = TMX_TYPE[1] // project type
> ```

Why don't we just define three const ```TMX_ALL, TMX_PROJECT, TMX_VERSION``` and use them instead of in an array. That way we don't need all these comment to help us remember which is which. Here you could also define ```let endpint``` and then base on type to construct endpoint so you won't need the switch statement below.

---

*[server/zanata-frontend/src/frontend/app/actions/tmx-actions.js, line 120 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-KqVByXkCCQUMEMdaLEU:-KqVByXkCCQUMEMdaLEV:b-v3yjoi) ([raw file](https://github.com/zanata/zanata-platform/blob/731e9334feefbc0d211138561ceb473539820fbe/server/zanata-frontend/src/frontend/app/actions/tmx-actions.js#L120)):*
> ```JavaScript
>     const type = getState().tmx.tmxExport.type
>     let endpoint
>     switch (type) {
> ```

I think we can move all these into a util file. I created a EnumValueUtil.js file to handle enum like value and related util functions

---

*[server/zanata-frontend/src/frontend/app/components/TMX/TMXExportModal.js, line 79 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-KqWJMQx5LWPUomValVo:-KqWJMQx5LWPUomValVp:bqug2j0) ([raw file](https://github.com/zanata/zanata-platform/blob/1500a0ed8bd69dc820dcd1b6ba474eec7c503582/server/zanata-frontend/src/frontend/app/components/TMX/TMXExportModal.js#L79)):*
> ```JavaScript
>               Produces a TMX file (srclang=*all*)
>               which some systems can't import.
>           </Tooltip>)
> ```

I think you can create a stateless component DownloadTooltip or something and extract this logic to that component (with a single optional prop localeDetails). This will make here clear.

---

*[server/zanata-frontend/src/frontend/app/components/TMX/TMXExportModal.js, line 87 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-KqWJku2gC8Q9wzi4WSg:-KqWJku2gC8Q9wzi4WSh:b-ya81ng) ([raw file](https://github.com/zanata/zanata-platform/blob/1500a0ed8bd69dc820dcd1b6ba474eec7c503582/server/zanata-frontend/src/frontend/app/components/TMX/TMXExportModal.js#L87)):*
> ```JavaScript
>           : (<Tooltip id={localeId + '-locale-tooltip'}>
>               All source locales
>           </Tooltip>)
> ```

Same as above

---

*[server/zanata-frontend/src/frontend/app/components/TMX/TMXExportModal.js, line 94 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-KqWLn-haP3Gs27wLNm-:-KqWLn-haP3Gs27wLNm0:b-lfjdao) ([raw file](https://github.com/zanata/zanata-platform/blob/1500a0ed8bd69dc820dcd1b6ba474eec7c503582/server/zanata-frontend/src/frontend/app/components/TMX/TMXExportModal.js#L94)):*
> ```JavaScript
>         )
>         const downloadTMX = handleExportTMX.bind(undefined,
>             (srcLang.localeDetails ? localeId : undefined), project, version)
> ```

Could we move this conditional logic into the handleExportTMX function? So that we don't need to do function binding here.

---

*[server/zanata-frontend/src/frontend/app/reducers/tmx-reducer.js, line 37 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-KqWQU3d_T37eQxBHBAI:-KqWQU3d_T37eQxBHBAJ:b-m4ucht) ([raw file](https://github.com/zanata/zanata-platform/blob/1500a0ed8bd69dc820dcd1b6ba474eec7c503582/server/zanata-frontend/src/frontend/app/reducers/tmx-reducer.js#L37)):*
> ```JavaScript
>           type: action.payload
>         }
>       }
> ```

I think we are switching to use immutable js

---

*[server/zanata-war/src/main/java/org/zanata/dao/LocaleDAO.kt, line 130 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-KqWRzwcJdU7fnN-jSVW:-KqWRzwcJdU7fnN-jSVX:b1d4r1) ([raw file](https://github.com/zanata/zanata-platform/blob/1500a0ed8bd69dc820dcd1b6ba474eec7c503582/server/zanata-war/src/main/java/org/zanata/dao/LocaleDAO.kt#L130)):*
> ```Kotlin
>     }
> 
>     fun processGetSourceLocalesAndDocCount(query: Query): Map<HLocale, Int> {
> ```

You can replace this function with a ResultTransformer. Use ```query.setResultTransformer()``` to get a list of map Entry object. 

---

*[server/zanata-war/src/main/java/org/zanata/rest/service/LocalesService.java, line 202 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-KqWTuYyIPv7En22ejRA:-KqWTuYyIPv7En22ejRB:b-50fwy2) ([raw file](https://github.com/zanata/zanata-platform/blob/1500a0ed8bd69dc820dcd1b6ba474eec7c503582/server/zanata-war/src/main/java/org/zanata/rest/service/LocalesService.java#L202)):*
> ```Java
>         if (results.size() > 1) {
>             int count = documentDAO.getTotalDocCount();
>             results.add(new SourceLocaleDetails(count, null));
> ```

So the null detail means total doc count. I think we should put a comment here and in the dto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/459)*

**Comment by aeng** [comment]
Review status: 38 of 43 files reviewed at latest revision, 9 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/actions/tmx-actions.js, line 120 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-KqVByXkCCQUMEMdaLEU:-KqW_PXjf6gZtjcrfV7B:b2k9jz1) ([raw file](https://github.com/zanata/zanata-platform/blob/731e9334feefbc0d211138561ceb473539820fbe/server/zanata-frontend/src/frontend/app/actions/tmx-actions.js#L120)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

I think we can move all these into a util file. I created a EnumValueUtil.js file to handle enum like value and related util functions
</blockquote></details>

Most of the stuff here is TMX specific, not sure its a good idea to put it in the util file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/459)*

**Comment by aeng** [comment]
Review status: 38 of 43 files reviewed at latest revision, 9 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/dao/LocaleDAO.kt, line 130 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-KqWRzwcJdU7fnN-jSVW:-KqZyVFuXBRz0sM5WpKF:b-h2p4q2) ([raw file](https://github.com/zanata/zanata-platform/blob/1500a0ed8bd69dc820dcd1b6ba474eec7c503582/server/zanata-war/src/main/java/org/zanata/dao/LocaleDAO.kt#L130)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

You can replace this function with a ResultTransformer. Use ```query.setResultTransformer()``` to get a list of map Entry object. 
</blockquote></details>

Until I'm more familiar with kotlin, I think its best I stick with this for the time being :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/459)*

**Comment by huangp** [comment]
Reviewed 10 of 12 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/459)*

**Comment by huangp** [comment]
-(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 1 of 12 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/459#-:-KqaACBediuOhD0HpvLS:b-1amvkm)*

**Pull request merged**
