### PR TITLE
Admin manage react

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: _[paste URL here]_

_[Add a short description of what is changed here.]_
## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.
- Code quality
  - [ ] Code passes style check (checkstyle/eslint)
  - [ ] Code is clear and concise
  - [ ] UI code is internationalised
  - [ ] Code has adequate comments where appropriate
  - Code is in an appropriate place
    - [ ] Classes are in appropriate packages
    - [ ] Code fits with class's responsibilities (SRP)
  - [ ] Configuration files are documented enough
  - If code is removed
    - [ ] No remaining code references the removed code
      - [ ] No orphaned rewrite rules
    - [ ] No orphaned config settings
    - [ ] No remaining comments refer to the removed code
    - [ ] Unused imports and libraries are removed
- Testing
  - [ ] New code has tests
  - [ ] Changed code has tests
  - [ ] All tests pass
  - [ ] Test coverage stable or increased
- Documentation
  - [ ] New features are documented
  - [ ] Docs removed for deleted features
  - [ ] Docs updated for all changed features
  - [ ] Developer/sysadmin docs updated if appropriate
- If there are new dependencies
  - [ ] Does each new dependency pass all the
     [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?
---

_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/10)

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[zanata-frontend/src/frontend/webpack.config.js, line 53 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyB2O_wuJyq1akvTbS:-KUyB2O_wuJyq1akvTbT:bpjj75d) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/webpack.config.js#L53)):*
> ```JavaScript
>     failOnError: true
>   }
> }
> ```

Should revert this as per master version.

---

*[zanata-frontend/src/frontend/app/containers/Root.js, line 6 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyB7ygbdLGHM3Y9OHz:-KUyB7ygbdLGHM3Y9OI-:b-sl5zdk) ([raw file](https://github.com/zanata/zanata-platform/blob/714243a0fc6e7c8167fab3a883947b39ab9534bf/zanata-frontend/src/frontend/app/containers/Root.js#L6)):*
> ```JavaScript
> import App from '../containers/App'
> import Glossary from '../containers/Glossary'
> import Languages from '../containers/Languages'
> ```

Why is this removed?

---

*[zanata-frontend/src/frontend/app/containers/Root.js, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyBD4g7wanW54JcEGf:-KUyBD4g7wanW54JcEGg:b-ipk2di) ([raw file](https://github.com/zanata/zanata-platform/blob/714243a0fc6e7c8167fab3a883947b39ab9534bf/zanata-frontend/src/frontend/app/containers/Root.js#L25)):*
> ```JavaScript
>               <Route path='explore' component={Explore} />
>               <Route path='glossary' component={Glossary} />
>               <Route path='languages' component={Languages} />
> ```

Why is this removed? bad merge?

---

*[zanata-frontend/src/frontend/app/containers/Languages/index.js, line 0 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyBKnCGbi2LDfZMkL0:-KUyBKnCGbi2LDfZMkL1:b-sl5zdk) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/app/containers/Languages/index.js#L0)):*
Why is this removed?

---

*[zanata-frontend/src/frontend/app/containers/ManageRoles/index.js, line 153 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyBQWBRbv0uuprAp0Q:-KUyBQWBRbv0uuprAp0R:bqowk1q) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/app/containers/ManageRoles/index.js#L153)):*
> ```JavaScript
> }
> 
> export default ManageRoles
> ```

I think all the "Manage*" should be inside /containers/admin folder. And probably no need to have "Manage" in the file since its all sitting inside admin directory.

---

*[zanata-frontend/src/frontend/app/containers/ManageSearch/index.js, line 168 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyBZ7gVs3TPXNnc1ki:-KUyBZ7gVs3TPXNnc1kj:b-61hqm2) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/app/containers/ManageSearch/index.js#L168)):*
> ```JavaScript
>   }
> }
> export default ManageSearch
> ```

I think all the "Manage*" should be inside /containers/admin folder.

---

*[zanata-frontend/src/frontend/app/containers/ManageUsers/index.js, line 158 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyB_IAZ37TnAcpABT_:-KUyB_IAZ37TnAcpABTa:b-61hqm2) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/app/containers/ManageUsers/index.js#L158)):*
> ```JavaScript
> }
> 
> export default ManageUsers
> ```

I think all the "Manage*" should be inside /containers/admin folder.

---

*[zanata-frontend/src/frontend/app/styles/style.less, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyCIjdFnxQJoeIYrym:-KUyCIjdFnxQJoeIYryn:b-ei8iop) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/app/styles/style.less#L1)):*
> ```Less
> #admin-lang,
> ```

I can see alot of reuse of certain color hard-coded to css class. Should it be a constant variable? Also, with padding, margin, and font-size, some is using px, some is using em. I think we should make it consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/10)*

**Comment by kathryngo** [comment]
*[zanata-frontend/src/frontend/app/containers/Root.js, line 6 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyB7ygbdLGHM3Y9OHz:-KV1vnwescJZQIgdUm1P:bk37s2g) ([raw file](https://github.com/zanata/zanata-platform/blob/714243a0fc6e7c8167fab3a883947b39ab9534bf/zanata-frontend/src/frontend/app/containers/Root.js#L6)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Why is this removed?
</details>
Bad merge

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/10)*

**Comment by kathryngo** [comment]
*[zanata-frontend/src/frontend/app/containers/Root.js, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyBD4g7wanW54JcEGf:-KV1vu7SGpDMZo_xJDjJ:bk37s2g) ([raw file](https://github.com/zanata/zanata-platform/blob/714243a0fc6e7c8167fab3a883947b39ab9534bf/zanata-frontend/src/frontend/app/containers/Root.js#L25)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Why is this removed? bad merge?
</details>
Bad merge

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/10)*

**Comment by kathryngo** [comment]
*[zanata-frontend/src/frontend/app/containers/Languages/index.js, line  at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyBKnCGbi2LDfZMkL0:-KV1w0q_bl_Mj4G4nDKI:bk37s2g) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/app/containers/Languages/index.js#L)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Why is this removed?
</details>
Bad merge

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/10)*

**Comment by kathryngo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[zanata-frontend/src/frontend/app/containers/ManageRoles/index.js, line 153 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyBQWBRbv0uuprAp0Q:-KV1w4yF-ZOfMNh9KZBx:btjfmt0) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/app/containers/ManageRoles/index.js#L153)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> I think all the "Manage*" should be inside /containers/admin folder. And probably no need to have "Manage" in the file since its all sitting inside admin directory.
</details>
Good idea. Shall fix.

---

*[zanata-frontend/src/frontend/app/containers/ManageSearch/index.js, line 168 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyBZ7gVs3TPXNnc1ki:-KV1w5nXApRV2p7bH_XL:btjfmt0) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/app/containers/ManageSearch/index.js#L168)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> I think all the "Manage*" should be inside /containers/admin folder.
</details>
Good idea. Shall fix.

---

*[zanata-frontend/src/frontend/app/containers/ManageUsers/index.js, line 158 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyB_IAZ37TnAcpABT_:-KV1w6bKJGa5Cf6jfw1z:btjfmt0) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/app/containers/ManageUsers/index.js#L158)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> I think all the "Manage*" should be inside /containers/admin folder.
</details>
Good idea. Shall fix.

---

*[zanata-frontend/src/frontend/app/styles/style.less, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyCIjdFnxQJoeIYrym:-KV1w7JJcjUAXQAArNl1:btjfmt0) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/app/styles/style.less#L1)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> I can see alot of reuse of certain color hard-coded to css class. Should it be a constant variable? Also, with padding, margin, and font-size, some is using px, some is using em. I think we should make it consistent.
</details>
Good idea. Shall fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/10)*

**Comment by kathryngo** [comment]
*[zanata-frontend/src/frontend/webpack.config.js, line 53 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-KUyB2O_wuJyq1akvTbS:-KV1wbqSvD_9JxpuEzDr:bbhwbh9) ([raw file](https://github.com/zanata/zanata-platform/blob/c6f79b1e59c8df127400d5429fe0cb73f213bb69/zanata-frontend/src/frontend/webpack.config.js#L53)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Should revert this as per master version.
</details>
Master says the same, false on warning, true on error
Is that correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/10)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 13 files at r1, 6 of 14 files at r2, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-:-KV3nP9G0p9vdU4nhfnV:bnfp4nl)*

**Comment by aeng** [comment]
@kathryngo since this is just mock pages. Please do not merge into master. Also, some print screen on the design would help.

**Comment by kathryngo** [comment]
No worries. Will add some screenshots at some point

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/10#-:-KV3oiAK26Afufwtpjc2:b-vleviw)*

**Comment by kathryngo** [comment]
@aeng , should this go to QA for feedback or should I close this PR?

**Comment by aeng** [comment]
@kathryngo Dont think there's anything for QA as this is a mock page. But it should be demo to the team for feedback

**Comment by kathryngo** [comment]
:thumbsup:

**Comment by kathryngo** [comment]
After I merge in the css next week, I will tidy up the design a bit (especially on the search page). Just got a few overrides to remove still.

**Comment by kathryngo** [comment]
Images have been added to the Jira issue: https://zanata.atlassian.net/browse/ZNTA-1335

**Pull request closed without merging**
