### PR TITLE
fix(ZNTA-2133): Close modal on ESC keydown or on click outside

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2133

ESC keydown and clicks outside of the modal will now  trigger a close

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/448)

### CODE REVIEW

**Comment by huangp** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js, line 398 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/448#-Kq0wLONvGf9IzhauyVw:-Kq0wLONvGf9IzhauyVx:bax6txm) ([raw file](https://github.com/zanata/zanata-platform/blob/77a82a612e338ed549f5859b20d9d524e6151656/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js#L398)):*
> ```JavaScript
>   // Close modal on escape key pressed
>   handleKeyDown = (e) => {
>     if (e.keyCode === 27) {
> ```

We could make use of the library 'combokeys' from editor dependency. So
```import specialKeys from 'combokeys/helpers/special-keys-map'```
should give you an object with keyCode to string representation of the key. e.g. specialKeys[27] === 'esc'. So here we could write:
```
if (specialKeys[e.keyCode] === 'esc') 
```
It makes it easier to understand.
```


---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js, line 399 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/448#-Kq0wBqYMjdElAIgHuBI:-Kq0wBqYMjdElAIgHuBJ:bn0wb8o) ([raw file](https://github.com/zanata/zanata-platform/blob/77a82a612e338ed549f5859b20d9d524e6151656/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js#L399)):*
> ```JavaScript
>   handleKeyDown = (e) => {
>     if (e.keyCode === 27) {
>       this.props.openTMMergeModal()
> ```

we should rename the function and prop name to toggleTMMergeModal as it does open and close

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js, line 403 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/448#-Kq18399-biz3PloXLDs:-Kq1-2WyDcNSixDyX1-B:bcruz4j) ([raw file](https://github.com/zanata/zanata-platform/blob/77a82a612e338ed549f5859b20d9d524e6151656/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js#L403)):*
> ```JavaScript
>   }
>   // Close modal when clicking outside
>   handleClickOutsideModal = (e) => {
> ```

I think we could try some approach here https://stackoverflow.com/questions/32553158/detect-click-outside-react-component 
so that we don't have to rely on class names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/448)*
<!-- Sent from Reviewable.io -->

**Comment by efloden** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js, line 398 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/448#-Kq0wLONvGf9IzhauyVw:-Kq5ZTxLlceyRQVJvwGn:bcc3p0l) ([raw file](https://github.com/zanata/zanata-platform/blob/77a82a612e338ed549f5859b20d9d524e6151656/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js#L398)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

We could make use of the library 'combokeys' from editor dependency. So
```import specialKeys from 'combokeys/helpers/special-keys-map'```
should give you an object with keyCode to string representation of the key. e.g. specialKeys[27] === 'esc'. So here we could write:
```
if (specialKeys[e.keyCode] === 'esc') 
```
It makes it easier to understand.
</blockquote></details>

Okay, making use of this library here now

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js, line 399 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/448#-Kq0wBqYMjdElAIgHuBI:-Kq5apsQ3Cs80M1QjHfQ:b121alo) ([raw file](https://github.com/zanata/zanata-platform/blob/77a82a612e338ed549f5859b20d9d524e6151656/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js#L399)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

we should rename the function and prop name to toggleTMMergeModal as it does open and close
</blockquote></details>

Okay, this one had to change in a few different files, tested it with a new build

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/448)*

**Comment by huangp** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js, line 398 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/448#-Kq0wLONvGf9IzhauyVw:-Kq6dM_lsAM10DigXE1-:b-ucxvc3) ([raw file](https://github.com/zanata/zanata-platform/blob/77a82a612e338ed549f5859b20d9d524e6151656/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js#L398)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Okay, making use of this library here now
</blockquote></details>

If you can use combokeys directly that will be even better. But since this component is not on a real single page app I won't bother too much if it's hard to integrate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/448)*

**Comment by efloden** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js, line 403 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/448#-Kq18399-biz3PloXLDs:-Kq6lLURh1_t7Uo0rdP7:b-83kmah) ([raw file](https://github.com/zanata/zanata-platform/blob/77a82a612e338ed549f5859b20d9d524e6151656/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js#L403)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

I think we could try some approach here https://stackoverflow.com/questions/32553158/detect-click-outside-react-component 
so that we don't have to rely on class names.
</blockquote></details>

Used the onBlur approach from here to implement this in the Modal component directly with a `backdrop` boolean prop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/448)*

**Comment by efloden** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js, line 398 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/448#-Kq0wLONvGf9IzhauyVw:-Kq6mSOZqX5x_ERKrFhn:b4ygv8f) ([raw file](https://github.com/zanata/zanata-platform/blob/77a82a612e338ed549f5859b20d9d524e6151656/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js#L398)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

If you can use combokeys directly that will be even better. But since this component is not on a real single page app I won't bother too much if it's hard to integrate.
</blockquote></details>

Since I've moved this to the Modal component do you think I should use combokeys directly there ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/448)*

**Comment by huangp** [comment]
:lgtm: -(Under review) +Reviewed +(On QA) 

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/448#-:-Kq7vAseA2oLLOTfZH4j:b-nx6778)*

**Pull request merged**
