### PR TITLE
feat(ZNTA-2409): Frontend Internationalization Workflow

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2409

Finalize a functional localization workflow for the Zanata frontend.
1. Configure local extract-messages script
2. Disable react-intl message extraction
3. Make en-us or en language file the default
4. Create scripts to push/pull translated messages files to/from Zanata *

Configured zanata-frontend/zanata.xml and pom.xml to include the frontend messages in the existing translations push script.
The currently running version of translate.zanata.org does not support the messages json files.
Once translate.zanata.org has been upgraded, we can test the workflow for push/pull of zanata frontend translations.

QA:
Tested the workflow with a local rundev Zanata instance, created some new Japanese language translations for the Activity Panel.
These can be observed by changing the application language to Japanese from the "More" options page, and loading/refreshing the react editor:
newlocalizations 1

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

### CODE REVIEW

**Comment by seanf** [comment]
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/730)

**Comment by seanf** [comment]
Reviewed 1 of 1 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[server/zanata-frontend/src/webpack.config.js, line 288 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8BCdtD6NNRxQvteSvA:-L8BCdtD6NNRxQvteSvB:b277qzo) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/webpack.config.js#L288)):*
> ```JavaScript
>       // This puts the strings generated by react-intl into a single file.
>       // fullBuild
>       //   ? new ReactIntlAggregatePlugin({
> ```

Please remove this plugin (also from package.json).

---

*[server/zanata-frontend/src/messages/en.json, line 3 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8BCn4IBBezu_0BRwV-:-L8BCn4IBBezu_0BRwV0:b-igmbqb) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/messages/en.json#L3)):*
> ```JSON
> {
>   "ActivityFeedItem.comment": {
>     "defaultMessage": "{name} has commented on this translation"
> ```

Do we actually need to be committing this file to git, considering this text is available at runtime from the FormattedMessage anyway?

---

*[server/zanata-frontend/src/messages/ja.json, line 43 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8BCxOjDl-Kxvpq_iRP:-L8BCxOjDl-Kxvpq_iRQ:b-575avx) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/messages/ja.json#L43)):*
>   "TranslatingIndicator.viewing": {
>     "defaultMessage": "表示専用モード"
>   }

"表示専用モード" is not really a default message.

I thought we we going to end up with something like this in the translation files:

```
  "TranslatingIndicator.viewing": "表示専用モード"
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/730)*

**Comment by seanf** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/webpack.config.js, line 288 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/730#-L8BCdtD6NNRxQvteSvA:-L8FFVz-KfiM_Ex-WiOT:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/webpack.config.js#L288)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Please remove this plugin (also from package.json).
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/730)*

**Comment by efloden** [comment]
Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/messages/en.json, line 3 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8BCn4IBBezu_0BRwV-:-L8F1xUMEO06tUTyLT6V:bvnux9y) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/messages/en.json#L3)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Do we actually need to be committing this file to git, considering this text is available at runtime from the FormattedMessage anyway?
</blockquote></details>

I've removed this file and added it to the frontend git ignore

---

*[server/zanata-frontend/src/messages/ja.json, line 43 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8BCxOjDl-Kxvpq_iRP:-L8BGOTBBRrQXlMT8e77:bqrpelw) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/messages/ja.json#L43)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

>   "TranslatingIndicator.viewing": {
>     "defaultMessage": "表示専用モード"
>   }

"表示専用モード" is not really a default message.

I thought we we going to end up with something like this in the translation files:

```
  "TranslatingIndicator.viewing": "表示専用モード"
```

</blockquote></details>

The react-intl-flatten-webpack-plugin looks for this "defaultMessage" key specifically, I was also hoping we could later make use of the "description" keys by updating Zanata to handle these json files to use them as source comments

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/730)*

**Comment by seanf** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/.gitignore, line 3 at r5](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8FNgmjBmvdHcfx2cJg:-L8FNgmjBmvdHcfx2cJh:b-tgn7j4) ([raw file](https://github.com/zanata/zanata-platform/blob/2bdac4f2fc524fb25e7fdd4e93773921aeebb050/server/zanata-frontend/src/.gitignore#L3)):*
> ```
> build/
> .awcache/
> messages/en.json
> ```

perhaps messages/en-us.json too?

---

*[server/zanata-frontend/src/messages/en.json, line 3 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8BCn4IBBezu_0BRwV-:-L8FNc-HCoxjwCIn8By7:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/messages/en.json#L3)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

I've removed this file and added it to the frontend git ignore
</blockquote></details>

:+1: 

---

*[server/zanata-frontend/src/messages/ja.json, line 43 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8BCxOjDl-Kxvpq_iRP:-L8FNpSe9Qnym1OP7C-F:b-ozyan0) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/messages/ja.json#L43)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

The react-intl-flatten-webpack-plugin looks for this "defaultMessage" key specifically, I was also hoping we could later make use of the "description" keys by updating Zanata to handle these json files to use them as source comments
</blockquote></details>

We shouldn't need `react-intl-flatten-webpack-plugin` either now. `extract-messages.js` only outputs one file. It's up to us to ensure it's structured the way we need (eg without `description` for now).

https://github.com/zanata/zanata-platform/blob/master/server/zanata-frontend/src/scripts/extract-messages.js

---

*[server/zanata-frontend/src/scripts/extract-messages.js, line 29 at r5](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8FOfbE7L-8qHi5m6TB:-L8FOfbE7L-8qHi5m6TC:bd2qlyl) ([raw file](https://github.com/zanata/zanata-platform/blob/2bdac4f2fc524fb25e7fdd4e93773921aeebb050/server/zanata-frontend/src/scripts/extract-messages.js#L29)):*
> ```JavaScript
>       // TODO: Update Zanata to handle muli-value JSON objects
>       // description: r.description
>     }
> ```

Until Zanata is updated, we need something like this instead:

    // TODO: Update Zanata to read react-intl JSON (with defaultMessage and
    // description) and output flattened JSON (id:translationText)
    messages[r.id] = r.defaultMessage

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/730)*

**Comment by efloden** [comment]
Review status: 8 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/.gitignore, line 3 at r5](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8FNgmjBmvdHcfx2cJg:-L8FSZin2ooLGtdYQdcR:b-35uo1g) ([raw file](https://github.com/zanata/zanata-platform/blob/2bdac4f2fc524fb25e7fdd4e93773921aeebb050/server/zanata-frontend/src/.gitignore#L3)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

perhaps messages/en-us.json too?
</blockquote></details>

Yes they could both be considered a default we'd want available, added messages/en-us.json here

---

*[server/zanata-frontend/src/messages/ja.json, line 43 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8BCxOjDl-Kxvpq_iRP:-L8G4VTVEnwHJ0tyM1AP:b-qvyhhu) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/messages/ja.json#L43)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We shouldn't need `react-intl-flatten-webpack-plugin` either now. `extract-messages.js` only outputs one file. It's up to us to ensure it's structured the way we need (eg without `description` for now).

https://github.com/zanata/zanata-platform/blob/master/server/zanata-frontend/src/scripts/extract-messages.js
</blockquote></details>

The plugin aggregates all the messages files, flattens them and includes them in the dist directory during the webpack build, that last part is really all we need if the files are already in the expected react intl format. I could implement this to replace the plugin? 

---

*[server/zanata-frontend/src/scripts/extract-messages.js, line 29 at r5](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8FOfbE7L-8qHi5m6TB:-L8G60kPAqGD1Yuxngqo:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/2bdac4f2fc524fb25e7fdd4e93773921aeebb050/server/zanata-frontend/src/scripts/extract-messages.js#L29)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Until Zanata is updated, we need something like this instead:

    // TODO: Update Zanata to read react-intl JSON (with defaultMessage and
    // description) and output flattened JSON (id:translationText)
    messages[r.id] = r.defaultMessage

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/730)*

**Comment by seanf** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/messages/ja.json, line 43 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8BCxOjDl-Kxvpq_iRP:-L8GFLvK2SDaC27CT3FG:bgiggm0) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/messages/ja.json#L43)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

The plugin aggregates all the messages files, flattens them and includes them in the dist directory during the webpack build, that last part is really all we need if the files are already in the expected react intl format. I could implement this to replace the plugin? 
</blockquote></details>

Will that be much work? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/730)*

**Comment by efloden** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/messages/ja.json, line 43 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8BCxOjDl-Kxvpq_iRP:-L8GFwY6BCn4QQ1CJM8G:b-j5ezjj) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/messages/ja.json#L43)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Will that be much work? 
</blockquote></details>

I've been learning a bit about webpack to see how it could work, think I am close to a solution

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/730)*

**Comment by efloden** [comment]
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/messages/ja.json, line 43 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/730#-L8BCxOjDl-Kxvpq_iRP:-L8_TrYUmiR0swGnvI31:b-phzg83) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/messages/ja.json#L43)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

I've been learning a bit about webpack to see how it could work, think I am close to a solution
</blockquote></details>

Replaced the react-intl-flatten-plugin with the webpack copy-webpack-plugin, using this to copy the translation files to dist/messages, it takes a transform function which I've used to also minify the files

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/730)*

**Comment by seanf** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/messages/ja.json, line 43 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-L8BCxOjDl-Kxvpq_iRP:-L8fUrN75UBAEuQAQkea:bfye0y4) ([raw file](https://github.com/zanata/zanata-platform/blob/1b552a5c23378ec886f86c8a8d09702c5e0481e8/server/zanata-frontend/src/messages/ja.json#L43)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Replaced the react-intl-flatten-plugin with the webpack copy-webpack-plugin, using this to copy the translation files to dist/messages, it takes a transform function which I've used to also minify the files
</blockquote></details>

:+1: Nice work!

Could I get you to add a couple of npm scripts to handle the Zanata push/pull workflow? Then we can set up a daily Jenkins job which will push new source text to Zanata, and another job (manually triggered) to fetch the latest translations into the source tree.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/730)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/730#-:-L99C6FwDATuFuXDTHqy:bnfp4nl)*

**Comment by spathare21** [comment]
@efloden  looks good tested functionality as you mentioned above but looks like build failure

**Comment by efloden** [comment]
@spathare21 looks like the build timed out on some tests, rebuild looks green now

**Pull request merged**
