### PR TITLE
fix(ZNTA-1668): Allow translator to see untranslated glossary entries

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1668

Glossary entries have value, even if they are not translated. Show all
matching entries with translations if available.

Tester notes:
- Entries in system and project glossary that match the source, or search term, will show
- Entries that have a translation for the current language will show it
- Entries that do not have a translation for the current language show `-none-` in lighter text and a disabled copy button
- Source / Target in glossary search now shows Source / Translation

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/541)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
screenshot from 2017-09-28 18-45-31

@kathryngo @davidmason - the above is what it looks like, and I'm wondering if the greyed "-none-" placeholder is appropriate, or if you have a better suggestion.

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/541#-:-KvUevyrbezFOYqe8S8b:bnfp4nl)*

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/541#-:-KvV-72TQcCISWwqwtLA:bnfp4nl)*

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/541#-:-KvVHzoYZpWcmkFMUQtm:bnfp4nl)*

**Comment by djansen-redhat** [comment]
@spathare21 ready for QA. Tester notes added to top comment.

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/541#-:-KvjNN4jLgQ3NTHAe5RW:bnfp4nl)*

**Comment by djansen-redhat** [comment]
@spathare21 could you give this a quick check in the GWT editor?

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 3 files at r4, 4 of 4 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/541#-:-KvvnWtmfFkkccWlP3sT:bnfp4nl)*

**Comment by spathare21** [comment]
@djansen-redhat , now it showing no result in a glossary. 

screenshot from 2017-10-10 14-39-10
screenshot from 2017-10-10 14-39-16

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/541#-:-KxpI5TdtxFr1v3srsTK:bnfp4nl)*

**Comment by spathare21** [comment]
verified untranslated glossary entries show's in both editor's

screenshot from 2017-11-01 10-40-37

screenshot from 2017-11-01 10-41-14

screenshot from 2017-11-01 10-43-11

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r8, 1 of 1 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/541#-:-Ky-Sek0jEmy31DrbzXQ:bnfp4nl)*

**Pull request merged**
