### PR TITLE
ZNTA-2391: admin react page

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL:  https://zanata.atlassian.net/browse/ZNTA-2391

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/723)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r1, 3 of 5 files at r2, 1 of 1 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/services/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, line 102 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/723#-L5S8_Iv6zOLKpEUdTTo:-L5S8_Iv6zOLKpEUdTTp:brh98dd) ([raw file](https://github.com/zanata/zanata-platform/blob/4850c071dcf9a4aac93ec88f270520da8a50e63b/server/services/src/main/java/org/zanata/servlet/UrlRewriteConfig.java#L102)):*
> ```Java
>                 .where("path").matches(anyOf(
>                         "admin/review",
>                         "admin/home",
> ```

should we change it to just `admin/`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/723)*

**Comment by kathryngo** [comment]
I have attempted to route the admin homepage to /admin instead of /admin/home but the /admin page just returns the text forbidden. Unsure how to fix this.

**Comment by kathryngo** [comment]
@aeng the url cannot be changed to /admin because if I do that the other admin jsf pages have broken links and will not load (they automatically have .xhtml appended in their url). I have looked at the code and cannot fix this myself. I think that this may be a reason that admin/home was used in the first place.

xhtml

**Comment by kathryngo** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/services/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, line 102 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/723#-L5S8_Iv6zOLKpEUdTTo:-L5gcxm7WSPCpN-TB5Pg:bw50ky8) ([raw file](https://github.com/zanata/zanata-platform/blob/4850c071dcf9a4aac93ec88f270520da8a50e63b/server/services/src/main/java/org/zanata/servlet/UrlRewriteConfig.java#L102)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

should we change it to just `admin/`?
</blockquote></details>

I tried this and I either get a forbidden message or the other admin pages do not work. I thin that is why it is admin/home to start with. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/723)*

**Comment by kathryngo** [comment]
@efloden I have made the necessary changes to get the admin page working but the link to the Export all to TMX modal is not working. 
modal

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/723#-:-L5ksV6AcHJ00vODuwMs:bnfp4nl)*

**Comment by kathryngo** [comment]
@aeng, thanks. Will make those changes for you tomorrow.

**Comment by kathryngo** [comment]
Changes made. The admin setting is already applied to the page.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/723#-:-L5qMy3g2nWW7OGyvWQu:bnfp4nl)*

**Comment by kathryngo** [comment]
Updated faces-config.xml - ready for continued review

---

Review status: 19 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/723#-:-L5rExXi4OrmRcvBJ4J5:b-8d4hfu)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/723#-:-L5uFvwmsCTphL2nGi5L:bnfp4nl)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/723#-:-L5vQb3e6oshOaIbwHNk:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo 
All options from admin panel are working fine is the admin panel design final or it is going to change.

I can't see any changes apart from admin landing homepage design.

screenshot from 2018-02-22 11-32-40

**Comment by kathryngo** [comment]
@spathare21 that's how it should look. This PR was changing the page from JSF to React, so it should look and function the same as the previous admin homepage. Sorry for any confusion.

**Comment by spathare21** [comment]
ok thanks @kathryngo

**Pull request merged**
