### PR TITLE
fix(ZNTA-2293): design changes to project version sidebar [storybook]

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2293

- added glossary link (ZNTA-2049)
- export project to TMX option is in options dropdown (ZNTA-2051)
- processing box shown in view (ZNTA-2050)

pvsidebar-storybook

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/617)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/617#-:-L-9maaa3vUM95WzuhSK:bnfp4nl)*

**Comment by aeng** [comment]
@kathryngo It's best to merge master into this branch when the master build is green again.

**Comment by aeng** [comment]
@kathryngo master is green now. But failure for this build is due to other reason:

70:32  error  Expected indentation of 20 space characters but found 31  react/jsx-indent-props
01:57:12 [INFO]

**Comment by kathryngo** [comment]
@aeng yep picked it up, hopefully it builds green now

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/617)*

**Pull request merged**
