### PR TITLE
fix(ZNTA-2522) added spacing between languages on user profile

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2522

langs

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by efloden** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/827#-:-LD-KtgR04VpBcTHw52S:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo if a user is a member of more than 3 langs latest languages are hides on the profile page. 

screenshot from 2018-05-21 10-34-16

**Comment by kathryngo** [comment]
cheers @spathare21 fixing now

**Comment by kathryngo** [comment]
fixed
langlist

**Comment by spathare21** [comment]
@kathryngo thanks, but looks like codecov failed

**Comment by kathryngo** [comment]
need to target release branch instead

**Pull request closed without merging**
