### PR TITLE
feat(ZNTA-87): notify failed translation saves in alpha editor

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-87

Implemented failed save notifications with Ant notification component.
notifysaveerror

## QA
Steps to Reproduce:
1. Sign in to Zanata and open any document that you are allowed to edit in the Angular editor
2. In a different browser tab or window, open the Zanata homepage
3. Sign out of Zanata in the different browser tab or window
4. Return to the tab with Alpha editor, change the text in a row click the save button (labeled "Needs Work" or "Translated").

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/877#-:-LEhPM0xAnwY2rqVcJ9I:bnfp4nl)*

**Comment by spathare21** [comment]
@efloden  looks good, but I think that notification message needs to change which says "Unable to save phraseId 10 as ..."  instead we can add a different message which will inform him about failure reason.

**Comment by djansen-redhat** [comment]
Saving as 'untranslated' shows a truncated message. Maybe the ' as $' part of the message could be in a _"if (saveInfo.translations[0] is not empty)"_

**Comment by efloden** [comment]
@spathare21 added the error status and status text ie '409 Conflict' for a concurrent edit conflict:
conflictwithtranslation
@djansen-redhat thanks for the suggestion, included the check for empty saveInfo.translations[0] to handle saving as untranslated:
conflictsave

**Comment by djansen-redhat** [comment]
Verified, new notifications look good

**Comment by djansen-redhat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efloden)

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/877#-:-LEmTiWC3Qch2Iw7H-mE:bnfp4nl)*

**Pull request merged**
