### PR TITLE
ZNTA-1817 and ZNTA-1868 compare DDL between liquibase and hibernate mapping and fix issues

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: 
https://zanata.atlassian.net/browse/ZNTA-1817
https://zanata.atlassian.net/browse/ZNTA-1868

* added a test to run hibernate validate and also to compare foreign keys and unique keys between liquibase and hibernate mapping
* fix up all the column type validation in hibernate validate

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/275)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/functional-test/src/test/java/org/zanata/DatabaseDDLTest.java, line 114 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Ki3woQiCkBUzZvRUWL3:-Ki3woQjLl3Yp7o4DrZc:b-n0mlgp) ([raw file](https://github.com/zanata/zanata-platform/blob/7e8200f6de0a78ecbf7f998e1fe5f305877adf46/server/functional-test/src/test/java/org/zanata/DatabaseDDLTest.java#L114)):*
> ```Java
>         // liquibase has more unique keys than in hibernate mapping
>         assertThat(ukFromLiquibase).containsAll(ukFromHibernate)
>                 .as("Liquibase unique keys contains all unique keys in hibernate mapping");
> ```

Shouldn't we add these missing unique keys to Hibernate then?

---

*[server/zanata-model/src/main/java/org/zanata/model/Activity.java, line 62 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Ki3xsrBX0QQ3ne3PGg2:-Ki3xsrCL9VygYgaiUGl:b-94u6k3) ([raw file](https://github.com/zanata/zanata-platform/blob/7e8200f6de0a78ecbf7f998e1fe5f305877adf46/server/zanata-model/src/main/java/org/zanata/model/Activity.java#L62)):*
> ```Java
>     private int startOffsetMillis;
>     @NotNull
>     private int endOffsetMillis;
> ```

Could you please add a comment explaining that we use`int` to match what's in the database? Or not a comment, just make it part of the pull request name - "compare DDL between liquibase and hibernate mapping" doesn't really explain these code changes.

And we should have a comment that the maximum offset we can store equates to about 24.8 days, since this is a signed `int`, but we only need one hour - see `org.zanata.model.Activity.EntityListener.onPrePersist()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275)*

**Comment by huangp** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[server/functional-test/src/test/java/org/zanata/DatabaseDDLTest.java, line 114 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Ki3woQiCkBUzZvRUWL3:-Ki7jbKpv_OYRVse3g2m:b-ur5qpu) ([raw file](https://github.com/zanata/zanata-platform/blob/7e8200f6de0a78ecbf7f998e1fe5f305877adf46/server/functional-test/src/test/java/org/zanata/DatabaseDDLTest.java#L114)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Shouldn't we add these missing unique keys to Hibernate then?
</blockquote></details>

I asked the question (should we make hibernate mapping matching what's in liquibase) in the planning session. We could but it will not provide much value (we still can't be sure the unique keys are equal because the query won't provide actual columns in the key). We could only assert the number of unique keys in each table are equal.

---

*[server/zanata-model/src/main/java/org/zanata/model/Activity.java, line 62 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Ki3xsrBX0QQ3ne3PGg2:-Ki7vprzaX_zREIHRJkX:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/7e8200f6de0a78ecbf7f998e1fe5f305877adf46/server/zanata-model/src/main/java/org/zanata/model/Activity.java#L62)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Could you please add a comment explaining that we use`int` to match what's in the database? Or not a comment, just make it part of the pull request name - "compare DDL between liquibase and hibernate mapping" doesn't really explain these code changes.

And we should have a comment that the maximum offset we can store equates to about 24.8 days, since this is a signed `int`, but we only need one hour - see `org.zanata.model.Activity.EntityListener.onPrePersist()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275)*

**Comment by seanf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/functional-test/src/test/java/org/zanata/DatabaseDDLTest.java, line 114 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Ki3woQiCkBUzZvRUWL3:-Ki7xyeHW3SOZfFk-upC:b7vqpxd) ([raw file](https://github.com/zanata/zanata-platform/blob/7e8200f6de0a78ecbf7f998e1fe5f305877adf46/server/functional-test/src/test/java/org/zanata/DatabaseDDLTest.java#L114)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

I asked the question (should we make hibernate mapping matching what's in liquibase) in the planning session. We could but it will not provide much value (we still can't be sure the unique keys are equal because the query won't provide actual columns in the key). We could only assert the number of unique keys in each table are equal.
</blockquote></details>

But if we check that the *number* of unique keys always match, we greatly reduce the chances of adding a unique key to one without adding it to the other. Even without checking the exact column.

How many unique keys are currently missing from Hibernate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275)*

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by huangp** [comment]
Review status: 20 of 34 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/functional-test/src/test/java/org/zanata/DatabaseDDLTest.java, line 114 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Ki3woQiCkBUzZvRUWL3:-Ki8vihKwTq5p6slcJGk:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/7e8200f6de0a78ecbf7f998e1fe5f305877adf46/server/functional-test/src/test/java/org/zanata/DatabaseDDLTest.java#L114)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

But if we check that the *number* of unique keys always match, we greatly reduce the chances of adding a unique key to one without adding it to the other. Even without checking the exact column.

How many unique keys are currently missing from Hibernate?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275)*

**Comment by seanf** [comment]
Reviewed 15 of 16 files at r3.
Review status: 34 of 35 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-model/src/main/java/org/zanata/model/HProjectGlossary.java, line 91 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-KiDasWpleveXrRtuI6j:-KiDasWqnq2wWoh9I7tE:b-l51685) ([raw file](https://github.com/zanata/zanata-platform/blob/4cc8740306ffb472c15f52f5bb1dfc672899f063/server/zanata-model/src/main/java/org/zanata/model/HProjectGlossary.java#L91)):*
> ```Java
>             HProjectGlossaryPk that = (HProjectGlossaryPk) o;
>             return Objects.equals(glossary.getId(), that.glossary.getId()) &&
>                     Objects.equals(project.getId(), that.project.getId());
> ```

We should use `Glossary.equals` and `HProject.equals` here, rather than coupling to their internals (eg these entities might switch to business key equality in future).

We may also need to implement `Glossary.equals` - in fact, it should probably implement business key equality by checking the immutable non-nullable `qualifiedName` field rather than the (nullable) `id` field.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275)*

**Comment by huangp** [comment]
Review status: 33 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-model/src/main/java/org/zanata/model/HProjectGlossary.java, line 91 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-KiDasWpleveXrRtuI6j:-KiE9oq1anvJtCB38p9c:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/4cc8740306ffb472c15f52f5bb1dfc672899f063/server/zanata-model/src/main/java/org/zanata/model/HProjectGlossary.java#L91)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should use `Glossary.equals` and `HProject.equals` here, rather than coupling to their internals (eg these entities might switch to business key equality in future).

We may also need to implement `Glossary.equals` - in fact, it should probably implement business key equality by checking the immutable non-nullable `qualifiedName` field rather than the (nullable) `id` field.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-:-KiENCEGIJMKlSfu8XRC:bnfp4nl)*

**Comment by huangp** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
Reviewed 1 of 2 files at r5, 8 of 8 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/functional-test/pom.xml, line 1150 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-KihzhrNBm5imBdcB_gj:-KihzhrNBm5imBdcB_gk:b-fhdqwb) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/functional-test/pom.xml#L1150)):*
> ```XML
>         <configuration>
>           <ignoredResourcePatterns>
>             <ignoredResourcePattern>log4j.xml</ignoredResourcePattern>
> ```

Where is log4j.xml coming from now?

---

*[server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml, line 95 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Kii-Di0uzgDA-DDFW7Z:-Kii-Di0uzgDA-DDFW7_:bkao48f) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml#L95)):*
> ```XML
>       <column name="projectIterationId"/>
>     </createIndex>
>   </changeSet>
> ```

This changeset should be split up, to minimise problems if the deployment times out after one of the intermediate steps.

---

*[server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml, line 131 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Kii-KMxowDoS7Iw3o_4:-Kii-KMxowDoS7Iw3o_5:bxkwm7x) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml#L131)):*
> ```XML
>     <dropColumn tableName="HTextFlowContentHistory" columnName="id" />
>     <addPrimaryKey tableName="HTextFlowContentHistory" columnNames="pos,text_flow_history_id"/>
>   </changeSet>
> ```

This changeset should only do one thing.

---

*[server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml, line 137 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Kii-NVk9K4SqeLUIGlO:-Kii-NVk9K4SqeLUIGlP:brhumzt) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml#L137)):*
> ```XML
>     <dropColumn tableName="HTextFlowTargetContentHistory" columnName="id" />
>     <addPrimaryKey tableName="HTextFlowTargetContentHistory" columnNames="pos,text_flow_target_history_id"/>
>   </changeSet>
> ```

Same here.

---

*[server/zanata-war/src/test/resources/org/zanata/test/model/MergeTranslationsData.dbunit.xml, line 59 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Kii-rB84C7Dcgdurt6Z:-Kii-rB9SGMP_WY2NsYh:b-t3g046) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/zanata-war/src/test/resources/org/zanata/test/model/MergeTranslationsData.dbunit.xml#L59)):*
> ```XML
>   <HTextFlow id="3" document_id="1" resId="tf3" revision="1" pos="2"
>     obsolete="0" plural="false" wordCount="11"
>     contentHash="5eb63bbbe01eeed093cb22bb8f5acdc0" content0="hello world3" />
> ```

What's the story here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275)*

**Comment by huangp** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/functional-test/pom.xml, line 1150 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-KihzhrNBm5imBdcB_gj:-Kii2wGVI3uJLfpE1eeR:b-7ytl7) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/functional-test/pom.xml#L1150)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Where is log4j.xml coming from now?
</blockquote></details>

from zanata-war test-jar even though the test-jar only contains persistence.xml. I don't know how it works out there is a log4j.xml there. 

---

*[server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml, line 95 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Kii-Di0uzgDA-DDFW7Z:-Kii4mqCSIi-7vhnbL3Q:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml#L95)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

This changeset should be split up, to minimise problems if the deployment times out after one of the intermediate steps.
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml, line 131 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Kii-KMxowDoS7Iw3o_4:-Kii4n5QipHD60azyxoo:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml#L131)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

This changeset should only do one thing.
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml, line 137 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Kii-NVk9K4SqeLUIGlO:-Kii4nUPELy2_LMt4QhG:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml#L137)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---

*[server/zanata-war/src/test/resources/org/zanata/test/model/MergeTranslationsData.dbunit.xml, line 59 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Kii-rB84C7Dcgdurt6Z:-Kii3IPREvcY-ac2R9mh:bfvoed8) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/zanata-war/src/test/resources/org/zanata/test/model/MergeTranslationsData.dbunit.xml#L59)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

What's the story here?
</blockquote></details>

content hash is of size char(32). this one is 33. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275)*

**Comment by seanf** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/test/resources/org/zanata/test/model/MergeTranslationsData.dbunit.xml, line 59 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Kii-rB84C7Dcgdurt6Z:-KiiOJrthgtBJMOqM3L3:b-9ewga1) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/zanata-war/src/test/resources/org/zanata/test/model/MergeTranslationsData.dbunit.xml#L59)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

content hash is of size char(32). this one is 33. 
</blockquote></details>

So this is an illegal record? What's it for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275)*

**Comment by huangp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-war/src/test/resources/org/zanata/test/model/MergeTranslationsData.dbunit.xml, line 59 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Kii-rB84C7Dcgdurt6Z:-Kilk5vc1-27R-SieKeZ:bsxgp8m) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/zanata-war/src/test/resources/org/zanata/test/model/MergeTranslationsData.dbunit.xml#L59)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

So this is an illegal record? What's it for?
</blockquote></details>

It was a string for content hash. Liquibase uses char(32) for this column. Now with the columnDefinition attribute you can tell hibernate what to use for string (default is varchar). So now the DDL became char(32) and previously this is for test data. I think someone just copy the other hash value and added one extra digit to make it different. Then it became illegal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275)*

**Comment by seanf** [comment]
:lgtm: Great stuff!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-war/src/test/resources/org/zanata/test/model/MergeTranslationsData.dbunit.xml, line 59 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-Kii-rB84C7Dcgdurt6Z:-Kilnm0ojEeucgWbDEQL:b-tz86sc) ([raw file](https://github.com/zanata/zanata-platform/blob/458504b037b995e937cadb216ab4c4d7878fdc41/server/zanata-war/src/test/resources/org/zanata/test/model/MergeTranslationsData.dbunit.xml#L59)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

It was a string for content hash. Liquibase uses char(32) for this column. Now with the columnDefinition attribute you can tell hibernate what to use for string (default is varchar). So now the DDL became char(32) and previously this is for test data. I think someone just copy the other hash value and added one extra digit to make it different. Then it became illegal.
</blockquote></details>

Oh, you mean it *was* 33, now you've changed it to be a legal 32!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/275#-:-KiloiyYk79KbvIbZ1JL:b-ksnpld)*

**Comment by spathare21** [comment]
@huangp After merging this branch build is successful but getting a failure while server startup. 
"liquibase.exception.ValidationFailedException: Validation Failed:"

http://pastebin.test.redhat.com/481037

**Comment by spathare21** [comment]
@huangp verified with the prod database given by Damian : http://file.bne.redhat.com/~djansen/translate.zanata.sanitised.sql.tar.gz  and its works fine now.

**Pull request merged**
