### PR TITLE
fix(ZNTA-2405): isolate frontend css

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2405

Isolate bootstrap css from the rest in frontend by using a wrapper class called bstrapReact. 

## Review
- Because there are some pages that are a mix of JSF and React (old pages that use the sidebar navigation), I had to add the class to the Nav component also.
- Some of the css from style.less was moved to legacy so the bootstrap css overrides do not apply.

## QA
I have tested this across frontend and both editors but I may have missed something so please test this thoroughly.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/app/styles/style.less, line 0 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/731#-L60DTqMSB5hqq-uuIfs:-L60DTqNDn8sMiFUTqaW:batogc0) ([raw file](https://github.com/zanata/zanata-platform/blob/af0536c25830fac0baf411a71b7ea743bf64d621/server/zanata-frontend/src/app/styles/style.less#L0)):*
I won't go through all the changes in this file. It is better to do manual testing and see if we actually break something.

---

*[server/zanata-war/src/main/webapp/WEB-INF/template/template.xhtml, line 97 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/731#-L60DqKlyQDo9BPtnh7x:-L60DqKlyQDo9BPtnh7y:b5enfs) ([raw file](https://github.com/zanata/zanata-platform/blob/af0536c25830fac0baf411a71b7ea743bf64d621/server/zanata-war/src/main/webapp/WEB-INF/template/template.xhtml#L97)):*
> ```HTML
>       data-links='{"loginUrl": "#{applicationConfigurationAction.getLoginUrl(request)}",
>                    "registerUrl": "#{applicationConfigurationAction.registerUrl}"}'
>       data-allow-register="#{allowPublicRegistration}"
> ```

Any reason this line is removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731)*

**Comment by aeng** [comment]
@kathryngo have you seen the last comment in reviewable?

**Comment by kathryngo** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/main/webapp/WEB-INF/template/template.xhtml, line 97 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/731#-L60DqKlyQDo9BPtnh7x:-L6JcGxFhAlkIITeUai6:b-c2kdqb) ([raw file](https://github.com/zanata/zanata-platform/blob/af0536c25830fac0baf411a71b7ea743bf64d621/server/zanata-war/src/main/webapp/WEB-INF/template/template.xhtml#L97)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Any reason this line is removed?
</blockquote></details>

No,  thanks for noticing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731#-:-L6JsxP0DuuEt992gcGV:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r2.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731)*

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731)*

**Comment by djansen-redhat** [comment]
- Page not extended fully to left
- Languages page search bar issue

screenshot from 2018-03-01 11-08-22

**Comment by djansen-redhat** [comment]
- Explore page search box issues

screenshot from 2018-03-01 11-11-13

**Comment by djansen-redhat** [comment]
- Possibly affects the profile date selector (will have to check master)
screenshot from 2018-03-01 11-13-36

**Comment by djansen-redhat** [comment]
- Name label seems odd
- Spacing of glossary entries broken
screenshot from 2018-03-01 11-15-00

**Comment by kathryngo** [comment]
Odd, am sure I fixed those especially the explore page one. Nvm, shall fix again :)

**Comment by spathare21** [comment]
Found below UI issue

- Explore page after search

screenshot from 2018-03-01 11-29-08

- Export version/project to tmx 

screenshot from 2018-03-01 11-34-28

screenshot from 2018-03-01 11-36-59


- Percentage completion for languages should be right aligned 

screenshot from 2018-03-01 11-34-52

screenshot from 2018-03-01 11-36-29

- Version TM merge pop-up

screenshot from 2018-03-01 11-35-31

- Glossart import, export, new, delete, info

screenshot from 2018-03-01 11-41-10

screenshot from 2018-03-01 11-41-21

screenshot from 2018-03-01 11-41-29

screenshot from 2018-03-01 11-41-38

screenshot from 2018-03-01 11-42-13

screenshot from 2018-03-01 11-41-57


- Add new Langauge page

screenshot from 2018-03-01 11-42-27

- Delete langauge

screenshot from 2018-03-01 11-43-24

- Admin page 

screenshot from 2018-03-01 11-44-51

**Comment by kathryngo** [comment]
No worries @spathare21, top priotity for tomorrow. Looks like the bstrapReact class isn't being applied properly and that some of the styling is still in style.less instead of legacy.less

**Comment by kathryngo** [comment]
Have fixed a few of these issues, should not take me long to fix the rest tomorrow

**Comment by kathryngo** [comment]
am adding a :thumbsup: for every comment I fix so I can keep track of them. For some reason @djansen-redhat's comments aren't showing in reviewable

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731)*

**Comment by aeng** [comment]
@kathryngo @djansen-redhat best to create a check-list in the description for this PR to keep track.

**Comment by kathryngo** [comment]
I am pretty sure to fix most of these I just need to alter/add some wrapping classes. The css fixes are there, they are just not being applied correctly. Should be an easy fix.

- [x] Languages page - search bar and page height
- [x] Explore page - search box and page height
- [ ] Profile date selector modal - width to handle side-by-side calendars
- [ ] Glossary naming label - fix styling, spacing of rows broken
- [ ] Export version/project to TMX  modal - pretty sure this just needs a bstrapReact class like most of the stuff here
- [ ] Percentage completion should be right aligned in project version pages - another fix I have made previously that just needs to be moved in code.
- [ ] Version TM Merge modal - dropdown broken
- [ ] Glossary modal design - Import
- [ ] Glossary modal design - Export
- [ ] Glossary modal design - New
- [ ] Glossary modal design - Details
- [ ] Glossary delete all entries button styling
- [ ] Add Languages modal
- [ ] Delete languages page
- [ ] Admin page height

**Comment by kathryngo** [comment]
@aeng @djansen-redhat @spathare21 ready for another review and continuation of QA

**Comment by aeng** [comment]
Instead of having all components to have ` bstrapReact` class, can't we put it in the root wrapper?

---

Reviewed 3 of 13 files at r4.
Review status: 5 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731#-:-L6nwp5_adA3RYxgaI6T:b-6pr1ef)*

**Comment by spathare21** [comment]
@kathryngo have to ignore the codecov ?

**Comment by aeng** [comment]
I understand the frontend module does not work nicely with codecov. I think we need to find a solution for this moving forward. One option is to measures  the frontend coverage by using different framework and exlude them from the codecov, or make it work with what we have now.

**Comment by spathare21** [comment]
@kathryngo 

- Explore search top spacing require 

screenshot from 2018-03-05 12-07-02

- space between username and image on explore page user search

screenshot from 2018-03-05 12-07-51

- Project, group creation date and time goes out of page

screenshot from 2018-03-05 12-16-12

screenshot from 2018-03-05 12-16-22

- Percentage shown for version 

screenshot from 2018-03-05 12-21-56


- Does left menu panel romved from gwt editor

screenshot from 2018-03-05 12-23-16

- User profile not loading

screenshot from 2018-03-05 12-25-17

- Glossary import, export new pop should be shown in center instead of left side.

screenshot from 2018-03-05 12-29-04

- Language delete 

screenshot from 2018-03-05 12-31-10

**Comment by kathryngo** [comment]
@aeng  sadly no, we need to specify that class in some components to avoid overrides and apply the css - the use of the sidebar nav on jsf pages has been a big part of this.
I would have done this so much quicker if it were just a matter of wrapping the root container, but that solution does not solve the issues with the different containers and wrappers used throughout the site and the mishmash of jsf/react stuff that needs to all work without conflict.

and yes, this codecov thing does not seem to be the best solution 

---

Review status: 5 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731#-:-L6sCBUOArYVuK2vcIRr:bg9s1cy)*

**Comment by kathryngo** [comment]
As I said in the descriptionL

- Because there are some pages that are a mix of JSF and React (old pages that use the sidebar navigation), I had to add the class to the Nav/Modal/some other components also.
- Some of the css from style.less was moved to legacy so the bootstrap css overrides do not apply.

**Comment by kathryngo** [comment]
I am almost finished with the bug fixes. The languages page popover and the gwt editor navigation are taking the most time. The trick with that gwt nav will be making sure the responsive layouts all work as expected, so this may take at most a few more days.

**Comment by kathryngo** [comment]
@spathare21 fixes made, ready for another look

**Comment by spathare21** [comment]
@kathryngo all looks fine now except below

- Still, it shows below pop-up after profile page click, looks like it occurred on master branch as well, have to create different issue for that ?

screenshot from 2018-03-08 16-44-10

- All admin pages are centered except Review criteria and Cache statistics page

**Comment by kathryngo** [comment]
@spathare21 I think so, as I am not having this issue at all. I will get someone else to test this branch and see if they are getting the same issue first.

**Comment by aeng** [comment]
@spathare21 perhaps force refresh might help?

**Comment by kathryngo** [comment]
@aeng I will fix all the codebeat/CodeFactor issues that I can in this PR also before asking you to review

**Comment by kathryngo** [comment]
@aeng the CodeBeat review is bringing up JS complaints, will have to ignore it in this PR. It is still passing so I don't think the errors matter at the moment.

**Comment by aeng** [comment]
@kathryngo Codebeat/CodeFactor sometimes throws complains which are not in our scope. You might want to filter out/ignore those that are not relevant to us.

**Comment by djansen-redhat** [comment]
The date range displayed in the dropdown is not valid.

I don't see the issues in the admin pages however.

**Comment by kathryngo** [comment]
@djansen-redhat I just need to center align the rejection criteria page in Admin. The cache statistics page cannot be adjusting without messing with the template for the other pages. Wrapper classes do not work. The cache statistics page has always been that way so lets just leave it for the moment.

**Comment by kathryngo** [comment]
@spathare21 have fixed the centering issue except for the caching page (see comment above). I will  file a bug report for the profile page problems. That should be resolved separately.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 6 of 13 files at r4, 1 of 5 files at r5, 4 of 6 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731#-:-L78ENaalM1b0CVmp18q:bnfp4nl)*

**Comment by aeng** [comment]
@kathryngo I reviewed all the changed files and trying to avoid any more delay for this PR. However, there are few components which we only used in full-react page only and should only require having the CSS namespace in the root wrapper instead of in the components. e.g. Components used only Glossary, UserProfile and Language.

**Comment by kathryngo** [comment]
Because those pages use the modal component the styling can be overridden unless you specify modal within bstrapReact for example. That is why in some places the bstrapReact class is used multiple times.
You will find in the old jsf code that this happened also, where the new-zanata class needed to be applied for overrides.

I will  reduce the scope of what I can css-wise in the component css isolation PR I shall work on when this is merged

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731#-:-L78FRHP0iEfKygH7Y1S:b-huzcbu)*

**Comment by aeng** [comment]
@kathryngo I think we should have the root element (App.js) to implement the class `bstrapReact` by default. That should allow all the child components to implement any styles under `bstrapReact`. And for those that are used with JSF without that wrapper, we can have `bstrapReact` class at the component level.

e.g. DeleteAllEntriesModal.jsx `<div className='u-block bstrapReact'>` shouldn't need the `bstrapReact` if we have it in App.js

**Comment by kathryngo** [comment]
It is not that simple. The specificity of some css means that this bstrapReact class is not enough to enforce some of the rules, and that is why I had to add them other places. 
I started with just putting it in that wrapper but it does not work that easily. That was of course the first thing I tried.
I still need to state that this class needs to be the parent target for things like the modals, nav and tooltips to work.
All of the changes that have been made are necessary to get the css to work. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/731#-:-L78Hh8Z-pt1FNuf-XGR:bm6zmxx)*

**Comment by aeng** [comment]
>  The specificity of some css means that this bstrapReact class is not enough to enforce some of the rules, and that is why I had to add them other places.

Does that mean there are some other css class that are not namespace properly and override the css in frontend component? I probably need to get to the bottom of this to have it properly fixed.

**Comment by kathryngo** [comment]
If we don't want messy code like this, the only solution is one css framework across everything otherwise there is always going to be overrides and scoping needed. It is not the best practice, but neither is having a system with so many different ui frameworks - until that is resolved and all the jsf stuff is gone this will continue to occasionally be an issue. Some browsers just apply weird rule overrides (even sometimes the stuff that is the most specific still isn't specific enough) and they need to be picked up in dev and testing.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/731#-:-L78LHP_BmwHlNZ1LL94:b-enw9xc)*

**Comment by seanf** [comment]
@aeng @kathryngo 

Ignoring codecov due to https://zanata.atlassian.net/browse/ZNTA-2424 - a pre-existing problem, related to the use of transpilation by Babel (before) and TypeScript (now).

The overall coverage did go down slightly, but it's too hard to fix when the patch coverage is so hard to interpret (due to the source map problem above).

**Comment by kathryngo** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
https://css-tricks.com/precedence-css-order-css-matters/
That might help explain how complex this gets, especially with load orders of css

**Comment by kathryngo** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731#-:-L7MaoPwjKWPkpiUFRb_:bnfp4nl)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/731#-:-L7NfTJuzLj6Kwh5Slh9:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo now all UI looks fine, and thanks for creating an issue related to a profile page.

**Comment by kathryngo** [comment]
@djansen-redhat I can't merge this because of those test failures

**Comment by djansen-redhat** [comment]
Admin page sizing on Navbar
screenshot from 2018-03-13 11-28-11

**Comment by kathryngo** [comment]
@aeng @djansen-redhat tests now pass but I had to fix an issue the code checkers picked up so full functional tests need to be run and a review of 2 files done before merge. None of the changes require QA.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/731#-:-L7Wk1xmDKMDLTh4OlJ8:bnfp4nl)*

**Pull request merged**
