### PR TITLE
fix(nav): highlight dashboard and settings for sidebar nav

### PR DESCRIPTION
**Pull request by aeng**
JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1559*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

https://zanata.atlassian.net/browse/ZNTA-1559

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/87)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/components/Nav/index.jsx, line 176 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/87#-KXmSoEo34gms4R5lwb_:-KXmSoEpszBzc-ua_uME:b-6nutjk) ([raw file](https://github.com/zanata/zanata-platform/blob/ea2af408e58432c1156a144b6acb2b8908c14e0d/server/zanata-frontend/src/frontend/app/components/Nav/index.jsx#L176)):*
> ```JSX
>            * 
>            * This is to handle profile page selection as url
>            * in server is been rewrite with /profile/username
> ```

"is been rewrite" -> "will be rewritten"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/87)*

**Comment by aeng** [comment]
@huangp Updated the comment.

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/87#-:-KXrjBP6ZQDMxu31iHUP:b49ms4)*

**Comment by huangp** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/87)*

**Comment by spathare21** [comment]
Verified

**Pull request merged**
