### PR TITLE
Upgrade Webpack to v3 (ZNTA-2118)

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2118

Upgrade to webpack 3, update the webpack configs so everything works.

 - upgrades storybook to latest (so it is compatible with webpack 3)
 - combines all the webpack config to a single file (uses env.buildtype to decide which config to include)
 - replaces rework with postcss (for css post-processing)

## Testing notes

- Frontend and editor build are impacted, so check they behave and look as expected.
  - files in the zanata-frontend jar file should be a similar size to the same on master
- Storybooks are impacted, check that they behave and look as expected.
- Frontend watch tasks are impacted, but probably don't need testing (devs use them so they will notice)

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/466)

### CODE REVIEW

**Comment by aeng** [comment]
I think we need some documentation to explain on how the new config is being triggered and how we can expend it if we need a new profile. 

---

Reviewed 54 of 55 files at r1.
Review status: 54 of 55 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/pom.xml, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/466#-KqePGr3DQR1Bi-QCwe9:-KqePGr3DQR1Bi-QCweA:b-u51p9v) ([raw file](https://github.com/zanata/zanata-platform/blob/3133bee3305637368f7bd4c9fce1cfd9d2b13934/server/zanata-frontend/pom.xml#L25)):*
> ```XML
>     
>     <node.version>v8.1.3</node.version>
>     <yarn.version>v0.27.5</yarn.version>
> ```

How can we make sure our local yarn is with the same version too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/466#-:-KqeS40gN3dAijdKlvy_:b-vg7qav)*

**Comment by davidmason** [comment]
I can add more commenting in the build script or in `webpack.config.js` - it is just standard webpack `env` that it uses, which you can specify on webpack command line but we use `scripts/build` instead.

---

Review status: 54 of 55 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/pom.xml, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/466#-KqePGr3DQR1Bi-QCwe9:-KqeWMkgrbDQP3vA4t62:b-sdh2ay) ([raw file](https://github.com/zanata/zanata-platform/blob/3133bee3305637368f7bd4c9fce1cfd9d2b13934/server/zanata-frontend/pom.xml#L25)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

How can we make sure our local yarn is with the same version too?
</blockquote></details>

That is worth looking into. I'll make a JIRA to investigate it (since it isn't directly related to this PR...

There: https://zanata.atlassian.net/browse/ZNTA-2161

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/466#-:-KqeVHbjiGsDv80cWXuV:b-wlszy6)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 55 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/466#-:-KqfAPxAbZgSbknPRxbi:bnfp4nl)*

**Comment by djansen-redhat** [comment]
✅ Looks good to me

**Pull request merged**
