### PR TITLE
fix: failed story-book watch

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-2261

JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/606)

### CODE REVIEW

**Comment by kathryngo** [comment]
Storybook doesn't work now.

I ran `make storybook-frontend` and the page doesn't load.
I can see the following console error
`Uncaught ReferenceError: webpackJsonp is not defined
    at manager.bundle.js:1`

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/606#-:-Kxuh1rweIP2Spl6sWuF:b-w0bat0)*

**Comment by aeng** [comment]
@kathryngo I can't start the story book in master branch too.

**Comment by aeng** [comment]
I think there's 2 separate issues here
1) Storybook watch does not work - Compiled JS file is different between release and master
2) Test failing due to storybook-plugin version - this PR should fix it.

**Comment by aeng** [comment]
Tried reverting package.json config to a7882886f2d9132f5256b1e3cc4473cc6e23c931 and the storybook watch works. Changes in ZNTA-2230 breaks the story book watch.

**Comment by kathryngo** [comment]
@aeng I am not able to fix these errors as ZNTA-2230 was worked on mostly by @huangp 
Reverting the versions from exact versions may fix this.

**Comment by aeng** [comment]
@kathryngo @djansen-redhat please test this again. 
1) Storybook watch
2) Yarn test/yarn test watch

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/606#-:-Kxw45J-nqVqnzRt99MX:bnfp4nl)*

**Pull request merged**
