### PR TITLE
ZNTA-1871 - set up storybooks and add a few frontend components

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1871

Seperate storybooks for frontend and editor have been set up. [Button](https://zanata.atlassian.net/browse/ZNTA-1875) and [Modal](https://zanata.atlassian.net/browse/ZNTA-1885) components for frontend have been added. This needs to be reviewed before I continue on with adding the other components listed in the [Epic](https://zanata.atlassian.net/browse/ZNTA-1837)

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/271)

### CODE REVIEW

**Comment by davidmason** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/app/components/Button/story.js, line 12 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/271#-Ki2a0iDODyQh0UjMX8m:-Ki2a0iEjwWPplnA4F6v:bu8pnw8) ([raw file](https://github.com/zanata/zanata-platform/blob/d4d10cc9cbd9561a691d2d53040cba04c94b5ae2/server/zanata-frontend/src/frontend/app/components/Button/story.js#L12)):*
> ```JavaScript
>     ))
> 
> storiesOf('Button', module)
> ```

We don't need to repeat `storiesOf()` for the same module.  You can just chain a bunch of `.add()` together.

Check out one of the existing stories where we have done it. It is basically like `storiesOf('Button', module).add(...).add(...).add(...)`, but we split it over more lines to make it easier to read:

```
storiesOf('Button', module)
  .add(...)
  .add(...)
  .add(...)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/271)*

**Comment by aeng** [comment]
Reviewed 10 of 19 files at r1, 4 of 8 files at r2, 4 of 5 files at r3, 1 of 7 files at r4.
Review status: 9 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/.storybook-editor/README.md, line 15 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/271#-Ki2aS_01HfUF59lB2Tn:-Ki2aS_1sGbYXpHn_V7w:b-76u5xk) ([raw file](https://github.com/zanata/zanata-platform/blob/d4d10cc9cbd9561a691d2d53040cba04c94b5ae2/server/zanata-frontend/src/frontend/.storybook-editor/README.md#L15)):*
> ```Markdown
> 
> ```
> make storybook
> ```

make storybook-frontend or storybook-editor?

---

*[server/zanata-frontend/src/frontend/.storybook-frontend/storybook.less, line 9 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/271#-Ki2bRzaN-Y96P5EF8YP:-Ki2bRzaN-Y96P5EF8YQ:b-5f5w2r) ([raw file](https://github.com/zanata/zanata-platform/blob/d4d10cc9cbd9561a691d2d53040cba04c94b5ae2/server/zanata-frontend/src/frontend/.storybook-frontend/storybook.less#L9)):*
> ```Less
>  */
> 
> @import '../app/styles/index.less';
> ```

Is storybook.less the only css file storybook will import? Can it load index.less directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/271)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/.storybook-editor/README.md, line 15 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/271#-Ki2aS_01HfUF59lB2Tn:-Ki2eqoqBObdz7YDgNft:bazswye) ([raw file](https://github.com/zanata/zanata-platform/blob/d4d10cc9cbd9561a691d2d53040cba04c94b5ae2/server/zanata-frontend/src/frontend/.storybook-editor/README.md#L15)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

make storybook-frontend or storybook-editor?
</blockquote></details>

this is the editor one as far as I know
the storybook was split into two (one for frontend and one for editor) in this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/271)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/components/Button/story.js, line 12 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/271#-Ki2a0iDODyQh0UjMX8m:-Ki2flb2OhRHSs6tXzIt:bb6un1j) ([raw file](https://github.com/zanata/zanata-platform/blob/d4d10cc9cbd9561a691d2d53040cba04c94b5ae2/server/zanata-frontend/src/frontend/app/components/Button/story.js#L12)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

We don't need to repeat `storiesOf()` for the same module.  You can just chain a bunch of `.add()` together.

Check out one of the existing stories where we have done it. It is basically like `storiesOf('Button', module).add(...).add(...).add(...)`, but we split it over more lines to make it easier to read:

```
storiesOf('Button', module)
  .add(...)
  .add(...)
  .add(...)
```
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/271)*

**Comment by davidmason** [comment]
Review status: 9 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/.storybook-frontend/storybook.less, line 9 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/271#-Ki2bRzaN-Y96P5EF8YP:-Ki2hDrBKLBp8EK0wf2n:bidfld1) ([raw file](https://github.com/zanata/zanata-platform/blob/d4d10cc9cbd9561a691d2d53040cba04c94b5ae2/server/zanata-frontend/src/frontend/.storybook-frontend/storybook.less#L9)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is storybook.less the only css file storybook will import? Can it load index.less directly?
</blockquote></details>

There's a bit of strangeness with how imports and paths work with style files in webpack. You have to have a wrapper file above the main one or it uses the wrong path for the second level imports. It's messy, unfortunately, but it works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/271)*

**Comment by davidmason** [comment]
Review status: 9 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/.storybook-editor/README.md, line 15 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/271#-Ki2aS_01HfUF59lB2Tn:-Ki2kMfLjZwdIenqekDV:b-jwtn7) ([raw file](https://github.com/zanata/zanata-platform/blob/d4d10cc9cbd9561a691d2d53040cba04c94b5ae2/server/zanata-frontend/src/frontend/.storybook-editor/README.md#L15)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

this is the editor one as far as I know
the storybook was split into two (one for frontend and one for editor) in this PR
</blockquote></details>

I noticed this before and went through and fixed all the references to storybook and .storybook to point to the right place. See r4 - I think I got them all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/271)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 19 files at r1, 2 of 8 files at r2, 6 of 7 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/271#-:-Ki34DIbiNwLUKdMqUxK:bnfp4nl)*

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by kathryngo** [comment]
@seanf, is this ready to merge even though the jenkins job and codecov stuff fails?

**Comment by seanf** [comment]
@kathryngo re: the tests, if _either_ ghprb or continuous-integration/jenkins/pr-merge passes, that's fine.

re: codecov, Ideally the changed code **would** get unit tests, but the developer and the reviewer(s) should discuss the feasibility of testing this code. If it is agreed that this is not practical, we can go ahead despite the codecov message.

I've talked to @aeng about this, and he is going to investigate the options for unit testing storybook example markup, and get back to us. In the worst case, we might move the storybook js out of the main src directories.

**Comment by davidmason** [comment]
@seanf Unit testing the story.js files themselves would not be appropriate since they are just examples of using the code. That would be almost the same as saying that we should unit test the unit test code.

We should unit test the components themselves, but this PR does not add any components.

**Comment by kathryngo** [comment]
@davidmason well that makes sense. I will wait for confirmation before I merge.

**Comment by aeng** [comment]
@davidmason perhaps we should ignore story coverage in jest, https://facebook.github.io/jest/docs/configuration.html#coveragepathignorepatterns-array-string

**Comment by davidmason** [comment]
@aeng good idea, I can look into that.

**Comment by seanf** [comment]
@kathryngo I thought you won't going to merge it yet!

**Comment by seanf** [comment]
> the story.js files... are just examples of using the components.

Funny... that's what unit tests are! [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)!

@davidmason examples can be unit tested. The best technical books these days have unit tests for all the code samples. It's a matter of making sure the code samples are executable (and accessible), so that they can be tested. 

For instance, perhaps the unit test could call into `story.js` to get some markup (instead of putting similar markup into the unit test), render it, and then make assertions about the rendering of the component. 

Unfortunately, looking at https://github.com/storybooks/storybook/ it appears that storybook isn't really set up for DRY unit tests like that yet, so I agree that we should exclude `story.js` for now. But let's not get in the habit of making lots of exceptions!

If and when storybook enables DRY unit testing, we should re-evaluate.

**Comment by davidmason** [comment]
@seanf I agree, each example in storybook would generally make a reasonable unit test. They should be hard-coded and therefore have predictable output.

There is no technical barrier to defining the content of each story outside of the storybook structure and importing it into there so it is available in other places too, I would just want to make sure we can do it cleanly so we have something that is easy to read and maintain.

**Comment by kathryngo** [comment]
@seanf I merged because the IgnoreCodeCov label was added. Since it will take some time to set up tests, I thought it's probably best I keep working on adding components to it while that gets sorted.  Sorry about this.

**Pull request merged**
