### PR TITLE
Switch Maven plugin to use annotations

### PR DESCRIPTION
**Pull request by seanf**
NB You can generate a file listing all options with:

    mvn -pl . org.zanata:zanata-maven-plugin:4.0.0-SNAPSHOT:help -Ddetail > zanata-maven-options.txt

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.
- Code quality
  - [ ] Code passes style check (checkstyle/eslint)
  - [ ] Code is clear and concise
  - [ ] UI code is internationalised
  - [ ] Code has adequate comments where appropriate
  - Code is in an appropriate place
    - [ ] Classes are in appropriate packages
    - [ ] Code fits with class's responsibilities (SRP)
  - [ ] Configuration files are documented enough
  - If code is removed
    - [ ] No remaining code references the removed code
      - [ ] No orphaned rewrite rules
    - [ ] No orphaned config settings
    - [ ] No remaining comments refer to the removed code
    - [ ] Unused imports and libraries are removed
- Testing
  - [ ] New code has tests
  - [ ] Changed code has tests
  - [ ] All tests pass
  - [ ] Test coverage stable or increased
- Documentation
  - [ ] New features are documented
  - [ ] Docs removed for deleted features
  - [ ] Docs updated for all changed features
  - [ ] Developer/sysadmin docs updated if appropriate
- If there are new dependencies
  - [ ] Does each new dependency pass all the
     [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

---

_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/17)

### CODE REVIEW

**Comment by seanf** [comment]
@aeng Have you got time to review this? With quite a few minor changes, it's probably easier to review in GitHub than Reviewable.

Other than adding a deprecation javadoc or two, it's basically just switching to equivalent annotations throughout. Pretty straightforward.

**Comment by seanf** [comment]
You can see exactly how the parameters have changed in this gist: https://gist.github.com/seanf/88962ae6cab8df5cee3af6e5d2cac6b9/revisions?diff=unified

**Comment by aeng** [comment]
Reviewed 21 of 22 files at r1.
Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/zanata-maven-plugin/src/main/java/org/zanata/maven/PullModuleMojo.java, line 30 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/17#-KWA3XtyDILWsdertpTZ:-KWA3XtyDILWsdertpT_:bvycoa1) ([raw file](https://github.com/zanata/zanata-platform/blob/87ebd344acf9449e8c35679524f60997e6fa127c/client/zanata-maven-plugin/src/main/java/org/zanata/maven/PullModuleMojo.java#L30)):*
> ```Java
>  * @author Sean Flanigan <a href="mailto:sflaniga@redhat.com">sflaniga@redhat.com</a>
>  */
> @Mojo(name = "pull-module", requiresOnline = true, requiresProject = false)
> ```

requiresProject = true? as per original?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/17)*

**Comment by aeng** [comment]
@seanf done first round review.

**Comment by seanf** [comment]
Review status: 20 of 22 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/zanata-maven-plugin/src/main/java/org/zanata/maven/PullModuleMojo.java, line 30 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/17#-KWA3XtyDILWsdertpTZ:-KWAcYJBMDkxQ_mXebUk:b-ubb87t) ([raw file](https://github.com/zanata/zanata-platform/blob/87ebd344acf9449e8c35679524f60997e6fa127c/client/zanata-maven-plugin/src/main/java/org/zanata/maven/PullModuleMojo.java#L30)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> requiresProject = true? as per original?
</details>
Good catch, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/17)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/17#-:-KWAdgbyXLzicfWzoCf8:bnfp4nl)*

**Comment by djansen-redhat** [comment]
:white_check_mark: tested

**Pull request merged**
