### PR TITLE
ZNTA-1760 - add missing database constraints

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1760

* delete user will cascade delete project locale members

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/239)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/239#-:-KfdmNkvF7B2y8N_07EJ:bnfp4nl)*

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
✅ Looks good to me

**Comment by seanf** [comment]
@huangp The liquibase changesets need to handle the case where the missing constraints have been violated. 

Also, it looks like a lot of functional tests have been failing since this was merged to `master`. I suppose the basic functional tests weren't affected by this change, but the full set was.

@djansen-redhat I don't suppose you tested the migrations against production data?

**Comment by seanf** [comment]
> @huangp The liquibase changesets need to handle the case where the missing constraints have been violated.

Sorry @huangp, I see that you included an SQL block for that. Please ignore that bit.

> Also, it looks like a lot of functional tests have been failing since this was merged to `master`. I suppose the basic functional tests weren't affected by this change, but the full set was.

We still need your help on this one please, @huangp .

**Comment by huangp** [comment]
see #255

**Pull request merged**
