### PR TITLE
feat(project-version): Allow user to update version write state

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: *[paste URL here]*

Enable --version-status active/readonly

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/149)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/149)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/149#-:-KajZiMazXeqGujJWSgU:bnfp4nl)*

**Comment by aeng** [comment]
@djansen-redhat checkstyle failed.

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/149)*

**Comment by djansen-redhat** [comment]
@spathare21 test that the project owner can set a project to active, readonly, and then back.

**Comment by spathare21** [comment]
@djansen-redhat , did't understand what has changed with this PR , before merging this PR also , i was able to make project version read-only and writable. does anything which need to test other than that ?

**Comment by djansen-redhat** [comment]
@spathare21 it's for the client.
```
$path/zanata-cli put-version --url "http://localhost:8180/" --username $ZADMINUSER --key $ZADMINKEY --version-project myproject --version-slug myversion --project-type file --version-status active
```
where 'myproject' and 'myversion' are the project and version.
--version-status can be active or readonly, anything else will result in an error.

**Comment by spathare21** [comment]
thanks @djansen-redhat , verified that we can change version  writable and readonly using zanata client and for any unknow status it shows Execution failed: version-status can only be active or readonly

**Pull request merged**
