### PR TITLE
ZNTA-1604-components

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1604*

*removed all atomic css references from the remaining components in frontend (nav and notification)*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/133)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 4 of 6 files at r1, 2 of 3 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/yarn.lock, line 211 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/133#-Ka9zVNTuhB6qYBB8ZtA:-Ka9zVNUGl2ooZGFnc6J:b-4joalm) ([raw file](https://github.com/zanata/zanata-platform/blob/dc7c3c20ed8e6469305f33f85ba534fd72dcc543/server/zanata-frontend/src/frontend/yarn.lock#L211)):*
> ```
>   version "0.9.2"
>   resolved "https://registry.yarnpkg.com/async/-/async-0.9.2.tgz#aea74d5e61c1f899613bf64bda66d4c78f2fd17d"
> ```

Please revert this as there's no changes in package.json

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/133)*

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/133)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/133#-:-KaA1bKFC7ocjM98Q4Ot:bnfp4nl)*

**Comment by spathare21** [comment]
Verified nav and subpages works well

**Pull request merged**
