### PR TITLE
feat(ZNTA-2116): Implement TriCheckbox component into TM Merge Modal

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2116
Relates to: https://zanata.atlassian.net/browse/ZNTA-1865

Checkboxes in the TM Merge Modal now use the TriCheckbox component. 
When selecting source project versions to merge the `project` checkbox now displays the intermediate state when some but not all of the `version` checkboxes are selected.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/462)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/ProjectVersionPanels.js, line 126 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/462#-KqWWl3hOkr-rQEIrPPE:-KqWWl3ib8kLd1Y877x_:b1zf0qo) ([raw file](https://github.com/zanata/zanata-platform/blob/4c4d1f59c80b04709c7e818548adf21571253c6a/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/ProjectVersionPanels.js#L126)):*
> ```JavaScript
>       selectedVersionsInProject.length > 0
>     return (
>       <label >
> ```

Does it needs to be inside a label?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/462)*

**Comment by efloden** [comment]
*[server/zanata-frontend/src/frontend/app/containers/ProjectVersion/ProjectVersionPanels.js, line 126 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/462#-KqWWl3hOkr-rQEIrPPE:-KqWXmYlF1jvd07x_jQQ:bkvj576) ([raw file](https://github.com/zanata/zanata-platform/blob/4c4d1f59c80b04709c7e818548adf21571253c6a/server/zanata-frontend/src/frontend/app/containers/ProjectVersion/ProjectVersionPanels.js#L126)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Does it needs to be inside a label?
</blockquote></details>

It needs to be wrapped in the label for the icon and text to also trigger the checkbox on click, which I think is standard for a checkbox input: https://facebook.github.io/react/docs/forms.html (the label also maintains the keyboard navigation and selection functionality which is nice)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/462)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/462#-:-KqWajpMEn2OTVQyUE2L:bnfp4nl)*

**Comment by spathare21** [comment]
@efloden I see only last three check box are changed is that the only targeted one . why other checbox are not implemented with TriCheckbox. see attached screen capture

screenshot from 2017-08-02 13-17-11

**Comment by efloden** [comment]
@spathare21 The options and UI at the top of the modal are planned to change to use switches, but for consistency I have applied the new component to all of the checkboxes in the modal now - started a new build for this commit

**Comment by spathare21** [comment]
ok thanks @efloden , build 3 pass verified.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/462#-:-KqfH6Er0yNYXNP_Shar:bnfp4nl)*

**Comment by aeng** [comment]
I think its best to go through another round of QA, just to make sure.

**Comment by spathare21** [comment]
I have retested it but its better if another person also tests it. @djansen-redhat can you please test this

**Comment by djansen-redhat** [comment]
@efloden @aeng @spathare21 This appears to have conflicts

**Comment by efloden** [comment]
Resolved the merge conflicts with master branch

**Comment by djansen-redhat** [comment]
✅ Looks good to me

**Pull request merged**
