### PR TITLE
fix: statistics update after save

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-2616

JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by efloden** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/888#-:-LESTEX5Dc2hqlLA59LI:bnfp4nl)*

**Comment by spathare21** [comment]
@aeng now the statistics updated correctly but, on selecting the statistics count it does not shows selected  text flow,  eg. if I select approved count  it doesn't show approved translation

screenshot from 2018-06-08 11-31-49

screenshot from 2018-06-08 11-32-00

screenshot from 2018-06-08 11-32-14

screenshot from 2018-06-08 11-32-23

screenshot from 2018-06-08 11-32-33

**Comment by seanf** [comment]
I thought ZNTA-2616 was about stats in the GWT editor, but this PR seems to change the React editor only. Is one of the descriptions wrong?

**Comment by efloden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @aeng)

---

*[server/zanata-frontend/src/app/editor/reducers/phrase-reducer/index.js, line 106 at r2](https://reviewable.io/reviews/zanata/zanata-platform/888#-LEh9lXB1FpDr4Iz8wMJ:-LEh9lXB1FpDr4Iz8wMK:bmq9lsz) ([raw file](https://github.com/zanata/zanata-platform/blob/9e2e46fcd1792d1bc5ab3b152f440d84e8e5a7cd/server/zanata-frontend/src/app/editor/reducers/phrase-reducer/index.js#L106)):*
> ```JavaScript
> 
>   [COPY_FROM_ALIGNED_SOURCE]: (state, {getState}) => updatePhrase(
>     state, getState().headerData.context.selectedDoc.id, state.selectedPhraseId,
> ```

I think using getState() in a reducer function might be an anti-pattern, but we should be able to get the required state in the action instead:
https://redux.js.org/faq/reducers#how-do-i-share-state-between-two-reducers-do-i-have-to-use-combinereducers

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/888)*

**Comment by aeng** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[server/zanata-frontend/src/app/editor/reducers/phrase-reducer/index.js, line 106 at r2](https://reviewable.io/reviews/zanata/zanata-platform/888#-LEh9lXB1FpDr4Iz8wMJ:-LEhFT0RA8Sd-XxTsVC9:b-nfhgva) ([raw file](https://github.com/zanata/zanata-platform/blob/9e2e46fcd1792d1bc5ab3b152f440d84e8e5a7cd/server/zanata-frontend/src/app/editor/reducers/phrase-reducer/index.js#L106)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

I think using getState() in a reducer function might be an anti-pattern, but we should be able to get the required state in the action instead:
https://redux.js.org/faq/reducers#how-do-i-share-state-between-two-reducers-do-i-have-to-use-combinereducers
</blockquote></details>

I agree with that. But I would refactor it as a separate PR, as the same approach is being used in many places
in general, the header-data should be accessible by all

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/888)*

**Comment by efloden** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/888)*

**Comment by spathare21** [comment]
Verified looks good to me, merged it once jenkins build pass

**Pull request merged**
