### PR TITLE
Prep for editor/frontend css merge

### PR DESCRIPTION
**Pull request by kathryngo**
https://zanata.atlassian.net/browse/ZNTA-2252

Before I can merge the css of frontend and editor, a few housekeeping tasks need to be completed:
 * ~~manually look at css resets - load normalize first~~
* ~~remove duplicate css statements with postcss-discard-duplicates~~
* ~~remove any border-box: box-sizing css from frontend and editor - is messing up width of components~~
* ~~combine css in a bundle, open app/index.js and import ./editor/index.css (frontend.js imports editor entry point)~~
* ~~merge in #573 then redo work as necessary~~
* ~and fix any css issues that occur from the above actions: ~gwt~, ~alpha editor~, frontend~
* ~improve glossary layout so the icons are all visible in the header in all media queries~

### Reviewers/QA 
please check interface of Zanata before approving for merge - these changes affect the UI 

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/582)

### CODE REVIEW

**Comment by aeng** [comment]
@kathryngo perhaps we should start breaking this PR down before this gets too big to review.

**Comment by kathryngo** [comment]
@aeng, it's done. It looks bigger than it is because I needed to rebase a heap of changes after updating from master.

**Comment by aeng** [comment]
Reviewed 38 of 45 files at r1.
Review status: 38 of 45 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/postcss.config.js, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMGIfF3bof7Upk1gTT:-KzMGIfF3bof7Upk1gTU:bc15iq8) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/postcss.config.js#L7)):*
> ```JavaScript
>     'postcss-cssnext': {},
>     'stylelint': {},
>     'cssnano': {},
> ```

Does the order matters?

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/index.less, line 11 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMGtI2RtPtjCdqLKOk:-KzMGtI3cffxlAn2_1QT:b-ormaf3) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Glossary/index.less#L11)):*
> ```Less
> }
> 
> td.languageSelect span.Select-value-label {
> ```

This is a very specific rule? Is it because of CSS conflict with assets + frontend + editor?

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/index.less, line 16 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMGhFIvdd1TnAhFSVG:-KzMGhFIvdd1TnAhFSVH:b-ormaf3) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Glossary/index.less#L16)):*
> ```Less
> 
> table.glossaryEntry .td-3 .textInput,
> table.glossaryEntry .hidesmall.td-2 .textInput {
> ```

This is a very specific rule? Is it because of CSS conflict with assets + frontend + editor?

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/NewEntryModal.js, line 127 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMGvZ0Gn0zffPpD1Cr:-KzMGvZ0Gn0zffPpD1Cs:bmpue6s) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Glossary/NewEntryModal.js#L127)):*
> ```JavaScript
>         </Modal.Body>
>         <Modal.Footer>
>           <div className='u-pullRight'>
> ```

Any reason for not using Buttongroup anymore?

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/index.less, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMH3ob7i0wocoR3sBY:-KzMH3ob7i0wocoR3sBZ:bfrs1v7) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Languages/index.less#L7)):*
> ```Less
> }
> 
> .languages h1 {
> ```

Shouldn't H1 be the same across all pages?

---

*[server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css, line 57 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMHikqdxiFdr6Nu_-z:-KzMHikrKL3GPfzAzrrF:b-4ecbr6) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css#L57)):*
> ```CSS
> 
> .InputEditorSearch .EditorInputGroup-addon button {
>   color: #546677;
> ```

Is this a new color that won't be reused by elsewhere?

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.css, line 230 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMJ8_VQzSqFrWb0iva:-KzMJ8_VQzSqFrWb0ivb:b-b82vn4) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.css#L230)):*
> ```CSS
> .GlossaryText * {
>   color: var(--Sidebar-panel-dark);
>   font-size: 0.875rem;
> ```

Can we have a css for this font-size instead? or make this a variable so it can be reuse.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.css, line 158 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMJKg5FAhhDU326irS:-KzMJKg5FAhhDU326irT:by6qzfy) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.css#L158)):*
> ```CSS
> }
> 
> .label {
> ```

Possible to move or merge this class to the general `label` class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by kathryngo** [comment]
Review status: 38 of 45 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/postcss.config.js, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMGIfF3bof7Upk1gTT:-KzMKRRdIwRPX3ZH4Y89:b3npqlh) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/postcss.config.js#L7)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Does the order matters?
</blockquote></details>

yes. linting should come before minification.

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/index.less, line 11 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMGtI2RtPtjCdqLKOk:-KzMKTuOZA_Faiq5ZrcK:brhn4rf) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Glossary/index.less#L11)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This is a very specific rule? Is it because of CSS conflict with assets + frontend + editor?
</blockquote></details>

indeed it is. 

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/index.less, line 16 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMGhFIvdd1TnAhFSVG:-KzMKWe4fqaU1at3ZDoR:b-exskih) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Glossary/index.less#L16)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This is a very specific rule? Is it because of CSS conflict with assets + frontend + editor?
</blockquote></details>

Once again, yep. I need to target elements very specifically to get some overrides working.

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/NewEntryModal.js, line 127 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMGvZ0Gn0zffPpD1Cr:-KzMKbPicNgplTksXPKm:bv3ufzp) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Glossary/NewEntryModal.js#L127)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Any reason for not using Buttongroup anymore?
</blockquote></details>

Isn't necessary, adds weird padding. Button Groups should be used for buttons that appear right next to each other.

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/index.less, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMH3ob7i0wocoR3sBY:-KzMKjLRmak4d6k2uonf:buee4hz) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Languages/index.less#L7)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Shouldn't H1 be the same across all pages?
</blockquote></details>

No because the css for h1 on Glossary is very different, and because the languages page has a different layout to other react pages, some specific padding was needed.

---

*[server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css, line 57 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMHikqdxiFdr6Nu_-z:-KzMKvKEStIew8qV61iX:b-90pigm) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css#L57)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is this a new color that won't be reused by elsewhere?
</blockquote></details>

No, it's the same as the dark blue used throughout Zanata. 

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.css, line 230 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMJ8_VQzSqFrWb0iva:-KzML1mjg6O08QpcgEur:b-mfhd8x) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.css#L230)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Can we have a css for this font-size instead? or make this a variable so it can be reuse.
</blockquote></details>

I will make it a variable like the color is above it.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.css, line 158 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMJKg5FAhhDU326irS:-KzML6iCiMj5ZJ15p7cC:b-2s1tf1) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.css#L158)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Possible to move or merge this class to the general `label` class?
</blockquote></details>

Will do, thanks for noticing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by kathryngo** [comment]
Review status: 37 of 45 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css, line 57 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMHikqdxiFdr6Nu_-z:-KzMT0YhVbAeqSaFhnFL:b53b40j) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css#L57)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

No, it's the same as the dark blue used throughout Zanata. 
</blockquote></details>

I just added some variables for the colours to this file, so if I need to use them again I can refer to the variable name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by aeng** [comment]
Reviewed 5 of 45 files at r1, 3 of 4 files at r2.
Review status: 44 of 45 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/index.less, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMH3ob7i0wocoR3sBY:-KzMMbqTrFILNv_HO-74:blaj1xf) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Languages/index.less#L7)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

No because the css for h1 on Glossary is very different, and because the languages page has a different layout to other react pages, some specific padding was needed.
</blockquote></details>

Noted. Please create a new Jira to refactor the pages for consistency across all pages. Especially on layout.

---

*[server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css, line 57 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMHikqdxiFdr6Nu_-z:-KzMN4vTzQDBuTMCmbmK:b-cp3a1f) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css#L57)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

No, it's the same as the dark blue used throughout Zanata. 
</blockquote></details>

Is the colour already defined somewhere as a variable that we can use it here? 

---

*[server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css, line 64 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMz02pY9tHz9nFf8Er:-KzMz02pY9tHz9nFf8Es:bwtaw7c) ([raw file](https://github.com/zanata/zanata-platform/blob/7d0ac4bf06b3ee68d782259d55960c9430ee5fb2/server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css#L64)):*
> ```CSS
>   color: var(--Input-color-dark);
> }
> ```

Will `var(--Input-color-dark);` works in .css file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by kathryngo** [comment]
Review status: 44 of 45 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css, line 64 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMz02pY9tHz9nFf8Er:-KzNAsA3eyaEnAGFlwvv:b28qaa5) ([raw file](https://github.com/zanata/zanata-platform/blob/7d0ac4bf06b3ee68d782259d55960c9430ee5fb2/server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css#L64)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Will `var(--Input-color-dark);` works in .css file?
</blockquote></details>

Aha, will change to .less

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by kathryngo** [comment]
Review status: 44 of 45 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/index.less, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMH3ob7i0wocoR3sBY:-KzNBVaFrqz49yPFlA7f:bfg0spf) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Languages/index.less#L7)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Noted. Please create a new Jira to refactor the pages for consistency across all pages. Especially on layout.
</blockquote></details>

The languages page uses a different size container to the explore page and glossary for a reason (the languages page uses a different width to display the bootstrap table), so there is no layout changes here to be corrected. The heading needed to be changed to position it correctly within the parent container.

---

*[server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css, line 57 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMHikqdxiFdr6Nu_-z:-KzNC-ZnxMvsCTibmBm0:b-yi7xjh) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css#L57)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is the colour already defined somewhere as a variable that we can use it here? 
</blockquote></details>

We need to define it at the top of the file, is a limitation of css variables.

---

*[server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css, line 64 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMz02pY9tHz9nFf8Er:-KzNC5Yc_-kiOxxEEjFW:bt565un) ([raw file](https://github.com/zanata/zanata-platform/blob/7d0ac4bf06b3ee68d782259d55960c9430ee5fb2/server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css#L64)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Aha, will change to .less
</blockquote></details>

Does not need to be changed to .less - works correctly in .css files as it does throughout the other editor css files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by aeng** [comment]
Review status: 44 of 45 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/index.less, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMH3ob7i0wocoR3sBY:-KzNMkNdIYL5EZe2J7p3:b-98ajvo) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Languages/index.less#L7)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

The languages page uses a different size container to the explore page and glossary for a reason (the languages page uses a different width to display the bootstrap table), so there is no layout changes here to be corrected. The heading needed to be changed to position it correctly within the parent container.
</blockquote></details>

So there is no default layout that we should follow when creating new page? Even with current page, I think its best to have at least some sort of default layout for all pages. I just dont want to end up where we got heaps of refactoring and cleanup to do as frontend builds up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by aeng** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by aeng** [comment]
Reviewed 1 of 45 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by kathryngo** [comment]
Review status: 44 of 45 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/index.less, line 7 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzMH3ob7i0wocoR3sBY:-KzQ56fGvANMuU0z4PTT:b-ceednc) ([raw file](https://github.com/zanata/zanata-platform/blob/3775914f5a5b77494b9ba4dde3b3fc0c2684ba56/server/zanata-frontend/src/frontend/app/containers/Languages/index.less#L7)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

So there is no default layout that we should follow when creating new page? Even with current page, I think its best to have at least some sort of default layout for all pages. I just dont want to end up where we got heaps of refactoring and cleanup to do as frontend builds up.
</blockquote></details>

Yes, we should use the languages page layout. This is the default one. Because the other pages were built before my bootstrap additions they have a different width set to handle the menu and page content. There are some minor changes to the glossary and explore page for example in the style.less file. A class called wideView is used to handle pages like Languages and any other I create in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by aeng** [comment]
Reviewed 13 of 13 files at r3, 3 of 4 files at r4.
Review status: 52 of 53 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/index.less, line 12 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzSCG_d9EBhOn7uzLtc:-KzSCG_d9EBhOn7uzLtd:bu5vfur) ([raw file](https://github.com/zanata/zanata-platform/blob/5226c4714e89f585dd958fba8ed0ab26c82d95ac/server/zanata-frontend/src/frontend/app/containers/Languages/index.less#L12)):*
> ```Less
>   display: inline-flex;
>   flex-wrap: wrap;
>   widt: 90%;
> ```

typo? width?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by kathryngo** [comment]
Review status: 51 of 53 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/index.less, line 12 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-KzSCG_d9EBhOn7uzLtc:-KzScifd49oAA4dYgWPu:b8bi21p) ([raw file](https://github.com/zanata/zanata-platform/blob/5226c4714e89f585dd958fba8ed0ab26c82d95ac/server/zanata-frontend/src/frontend/app/containers/Languages/index.less#L12)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

typo? width?
</blockquote></details>

Oops. Fixed. I also needed to make some minor changes to the languages toolbar layout since this typo was stopping some code from rendering. All done now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-:-KzVwNS2fmbLaF_9ChMH:bnfp4nl)*

**Comment by djansen-redhat** [comment]
Some things noted during the check, unsure how much is related to the changes.

Hiding suggestions panel does not allow display of textflows - large unused space.
screenshot from 2017-11-22 15-48-54

110% browser zoom shows jagged edge on save dropdown
screenshot from 2017-11-22 15-47-24

Incorrectly sized dropdowns in glossary
screenshot from 2017-11-22 15-36-11

Extra X after adding text to textflow filter
screenshot from 2017-11-22 15-50-36

Wrapped "More..." in version validation settings
screenshot from 2017-11-22 15-42-50

Misaligned project name in project glossary
screenshot from 2017-11-22 15-41-45

'Manage search' title wrapped unnecessarily
screenshot from 2017-11-22 15-38-44

**Comment by kathryngo** [comment]
@djansen-redhat 
the first issue has been there for a while, I can't recall how long. and I have no freakin idea how to fix that.
the others, well those are my fault. I shall fix them and attempt to fix #1 also

**Comment by djansen-redhat** [comment]
A few glossary issues:
Top panel does not extend full width of display
screenshot from 2017-11-23 09-58-54

Items per page selector floats when scrolled
screenshot from 2017-11-23 09-58-36

Truncation/eliding potentially needed for terms
screenshot from 2017-11-23 09-57-40

**Comment by djansen-redhat** [comment]
Also, I got a "warning: CRLF will be replaced by LF in server/zanata-frontend/src/frontend/app/components/Icon/list.js"

**Comment by kathryngo** [comment]
Warning fixed here. Shall fix  the other bugs, may take a while depending how fiddly this is

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-:-KzaU0PeVbGw5AGq5VXp:b-j166m2)*

**Comment by kathryngo** [comment]
Review status: 47 of 55 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-Kzfa9WJxtHe5fiX1_Ne:-Kzfa9WJxtHe5fiX1_Nf:bgb2cw8) (no related file):*
@djansen-redhat, I have made those changes where possible 

1. **Hidden suggestions panel** - I cannot replicate this problem, I used to be able to. Odd. Could you post on Jira about this and leave the specs of your browser and OS?

2. **Zoomed buttons** Fixed, involved increasing the length of the buttons with the dropdowns so the rounded edges can't be seen when zoomed to at least 120%

3. **Languages dropdown - Glossary** I have made them as long as I am able to manually without reworking the entire Select component - this way they will always fit the content although its not the optimal solution. I will add this to Jira so I can fix it at a later date.

4. **Editor Search Input** Extra 'x' is gone, this was a brutal one. Updated EditorSearchInput test file also.

5. **Version Settings** It should be like this, it looks weird having the 'More...' on the next line because of the right aligned buttons.

6. **Glossary** Fixed alignment of Project Glossary title.

7. **Manage Search**. Manage Search title will wrap because of the stupid GWT templates, but I have at least pushed the Current Progress box down so it doesn't cut it off. It would be better to just redo this page in react alongside the other admin pages instead of spending ages trying to modify the templates used.

8. **Glossary heading** I have intentionally moved the search and buttons down to under the Glossary heading so the heading is consistent with other pages and the search and buttons always appear regardless of screen size (was breaking on small screens)

9. **Glossary item selector** Fixed floating of items per page selector

10. **Handling of long glossary entries** Ellipsis taking too much time and effort to get working on the text inputs, have set a max width to these lines, and you can view the entire text on hover.
I might make these tooltips in the future so they are easier to read. Thoughts?
At this point I am just wanting to get this working and pushed.

11. **CRLF warning** can be fixed by going to frontend/app and running the following in bash
```
find . \( -name \*.js -o -name \*.jsx \) -print | xargs dos2unix
```
I fixed it locally but a build reverted the change, so I did it again before my final commit. Just in case you get the same issues, use the code above that Sean gave me.

When this is passed QA, would you mind doing a quick review on the changes @aeng ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by djansen-redhat** [comment]
@kathryngo I entered some comments as quotes inline above ^

**Comment by kathryngo** [comment]
@djansen-redhat Cheers, will have a look in the morning. It's very weird that some of the changes aren't showing for you (like the extra x in the search bar/the button zoom fix/item selector in glossary).
I have changed the js pages so some things aren't generated anymore so you should not see the second 'x' at all - shall try to rebuild and locate the problem.

**Comment by kathryngo** [comment]
1. **Hidden suggestions panel** - I cannot replicate this problem, I used to be able to. Odd. Could you post on Jira about this and leave the specs of your browser and OS?

Added comment on Jira.

> Responded on Jira - is one of those weird bugs I can't seem to replicate. Will spend some time in browserstack trying to replicate - will need to be an issue of its own.

2. **Zoomed buttons** Fixed, involved increasing the length of the buttons with the dropdowns so the rounded edges can't be seen when zoomed to at least 120%

Still seeing the jagged edge at 110% (Google Chrome 62 on Fedora 27)

>  I have managed to fix this by decreasing the size of the arrow icon (I wasn't able to get the jagged edges to show until zooming to 125%). 

4. **Editor Search Input** Extra 'x' is gone, this was a brutal one. Updated EditorSearchInput test file also.

Still seeing the purple x (Google Chrome 62 on Fedora 27)

> Ok, now it's fixed. It's actually blue and I cannot change the way it looks easily - unsure how to at this point and I have spent a fair bit of time working it out. That is the correct 'x' for the search, which David implemented.

9. **Glossary item selector** Fixed floating of items per page selector

> Fixed, needed to fiddle with positioning for other elements

**Comment by djansen-redhat** [comment]
This looks good to me. @aeng can you review the last remaining parts so I can progress it?

**Comment by aeng** [comment]
Reviewed 4 of 8 files at r6, 4 of 5 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-:-L--Dh64zKc2I_tCl-pT:bnfp4nl)*

**Comment by kathryngo** [comment]
Shall merge once build has passed

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/582#-:-L--DxXF0w6K9a0uQyfU:bnfp4nl)*

**Pull request merged**
