### PR TITLE
ZNTA-1606-bootstrapallatomic

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1606

- classnames more consistent (will use hyphens instead of camel case as this is what bootstrap uses)
- refactored and consolidated variables (for colours and margins, repeated padding etc)
- removed atomic css from frontend

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/182)

### CODE REVIEW

**Comment by kathryngo** [comment]
I have made all the necessary changes for this issue - [ZNTA-1721](https://zanata.atlassian.net/browse/ZNTA-1721) (removal of atomic/zanata-ui) needs to be resolved before this can be merged into master.
I could not even do a `yarn remove zanata-ui` without build failures. 😕

**Comment by aeng** [comment]
Reviewed 8 of 35 files at r3, 24 of 27 files at r4.
Review status: 32 of 35 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/ViewHeader.js, line 195 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/182#-KcQj5228DdXB6yrau1W:-KcQj5228DdXB6yrau1X:b-a37r9l) ([raw file](https://github.com/zanata/zanata-platform/blob/8378404c7797b3ec746a4bca17aced157e28f66a/server/zanata-frontend/src/frontend/app/containers/Glossary/ViewHeader.js#L195)):*
> ```JavaScript
>                     English (United States)
>                     </span>
>                     <span className='term-count'>{termCount}</span>
> ```

Is it possible to use text-muted and some general margin-left class? Not sure css class just for a span

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/ViewHeader.js, line 234 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/182#-KcQjKWtms-Ao5jvRX04:-KcQjKWuR5RwjZYNrrJr:bal4gjw) ([raw file](https://github.com/zanata/zanata-platform/blob/8378404c7797b3ec746a4bca17aced157e28f66a/server/zanata-frontend/src/frontend/app/containers/Glossary/ViewHeader.js#L234)):*
> ```JavaScript
>                         : <Icon name='chevron-up' className='s1' />
>                       : ''}
>                     <span className='partofspeech'>
> ```


Possible to use a general margin-left class?

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/Entry.js, line 67 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/182#-KcQjV9tok5C_XPxJ191:-KcQjV9tok5C_XPxJ192:b-c5qt5b) ([raw file](https://github.com/zanata/zanata-platform/blob/8378404c7797b3ec746a4bca17aced157e28f66a/server/zanata-frontend/src/frontend/app/containers/Languages/Entry.js#L67)):*
> ```JavaScript
>         </td>
>         <td>
>           <span className='user-count'>
> ```

Can `user-count` possibly be some general class which can be used in other views?

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/NewLanguageModal.js, line 194 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/182#-KcQjjHLyfRchAdNStqU:-KcQjjHLyfRchAdNStqV:b-wub88t) ([raw file](https://github.com/zanata/zanata-platform/blob/8378404c7797b3ec746a4bca17aced157e28f66a/server/zanata-frontend/src/frontend/app/containers/Languages/NewLanguageModal.js#L194)):*
> ```JavaScript
>                 </a>
>                 {showPluralFormsWarning &&
>                   <div className='plurals'
> ```

Again, can we use combination of general css class? or class which is reusable. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/182)*

**Comment by kathryngo** [comment]
Review status: 31 of 36 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/ViewHeader.js, line 195 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/182#-KcQj5228DdXB6yrau1W:-KcQvd-Lyy4WOqv7-bBH:b-kbkvrc) ([raw file](https://github.com/zanata/zanata-platform/blob/8378404c7797b3ec746a4bca17aced157e28f66a/server/zanata-frontend/src/frontend/app/containers/Glossary/ViewHeader.js#L195)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is it possible to use text-muted and some general margin-left class? Not sure css class just for a span
</blockquote></details>

Done. Class 'muted-left'

---

*[server/zanata-frontend/src/frontend/app/containers/Glossary/ViewHeader.js, line 234 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/182#-KcQjKWtms-Ao5jvRX04:-KcQxDvqR1HlMxTNzkE0:b-yp4vr) ([raw file](https://github.com/zanata/zanata-platform/blob/8378404c7797b3ec746a4bca17aced157e28f66a/server/zanata-frontend/src/frontend/app/containers/Glossary/ViewHeader.js#L234)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Possible to use a general margin-left class?
</blockquote></details>

Uses 'left-rq' after the variable name of the margin sizen

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/Entry.js, line 67 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/182#-KcQjV9tok5C_XPxJ191:-KcQxBtHLryU9N6Q3XyA:b-rt5oli) ([raw file](https://github.com/zanata/zanata-platform/blob/8378404c7797b3ec746a4bca17aced157e28f66a/server/zanata-frontend/src/frontend/app/containers/Languages/Entry.js#L67)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Can `user-count` possibly be some general class which can be used in other views?
</blockquote></details>

Now uses 'text-muted'

---

*[server/zanata-frontend/src/frontend/app/containers/Languages/NewLanguageModal.js, line 194 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/182#-KcQjjHLyfRchAdNStqU:-KcQx8vQ5U9o7M1VulQJ:b-2zdvn0) ([raw file](https://github.com/zanata/zanata-platform/blob/8378404c7797b3ec746a4bca17aced157e28f66a/server/zanata-frontend/src/frontend/app/containers/Languages/NewLanguageModal.js#L194)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Again, can we use combination of general css class? or class which is reusable. 
</blockquote></details>

Done. '.small-text'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/182)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/182#-:-KcQyFrwC_g4UF--WEkP:bnfp4nl)*

**Comment by kathryngo** [comment]
Thanks for reviewing this so quickly @aeng 👍

**Comment by aeng** [comment]
@kathryngo Should this PR targetting release branch?

**Comment by kathryngo** [comment]
Yes it should. I am fixing one tidy css issue then I will make sure to change the target branch. 

---

Review status: 34 of 36 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/182#-:-KcR0_1yf7lfYEbN36fX:b-3r5ryq)*

**Comment by aeng** [comment]
Reviewed 4 of 49 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/182)*

**Comment by aeng** [comment]
Reviewed 3 of 3 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/182)*

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by kathryngo** [comment]
@zanata-jenkins retest this please

**Comment by kathryngo** [comment]
@zanata-jenkins retest this please

**Comment by kathryngo** [comment]
@aeng, @djansen-redhat, @spathare21: I have made css changes to the navigation sidebar height so you will need to test and verify this for me. I have tested it in Chrome and Firefox but it's always good for someone else to check. :)

**Comment by kathryngo** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/182)*

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/182)*

**Comment by djansen-redhat** [comment]
I think I'm happy with this.

**Comment by spathare21** [comment]
everything looks good to me.

**Comment by djansen-redhat** [comment]
@spathare21 almost - we shall when the ghprb build goes green

**Comment by kathryngo** [comment]
tis green!

**Comment by kathryngo** [comment]
@aeng shouldn't this go into master also?

**Pull request merged**
