### PR TITLE
fix(warnings): Add equals and hashcode methods to activity

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: n/a

Add equals method for Activity, using business rules.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/242)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@seanf it was a bit difficult to decide what should be the business keys for this one

**Comment by seanf** [comment]
@djansen-redhat :
> it was a bit difficult to decide what should be the business keys for this one

Looking at `ActivityDAO.findActivity` (which is supposed to return a single Activity), it looks like these are the important properties:

    personId, contextId, activityType, contextType, approxTime.

The unique key UKActivity seems to agree, because it has these columns:

    actor_id (ie personId), context_id, activityType, contextType, approxTime.

So I think we need to add contextId and approxTime to equals/hashCode.

Arguably, we should also add `@NaturalId` to those five properties, if only for documentation purposes, even if we don't make use of Hibernate's NaturalId support yet.

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/242#-:-Kihnl2DJv_fSprJEbjN:bnfp4nl)*

**Comment by seanf** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/242)*

**Pull request merged**
