### PR TITLE
Update Windows manual instructions

### PR DESCRIPTION
**Pull request by seanf**
Related to https://zanata.atlassian.net/browse/ZNTA-2432

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/757#-:-L80Uta9s5CzQmebeMwK:bnfp4nl)*

**Comment by aeng** [comment]
@seanf do you think we should remove the last line `Run the following command java -cp lib/* org.zanata.client.ZanataClient to start zanata-cli.`?

**Comment by seanf** [comment]
@aeng 
> do you think we should remove the last line Run the following command java -cp lib/* org.zanata.client.ZanataClient to start zanata-cli.?

I thought I did?!

**Comment by aeng** [comment]
My bad. missed that.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/757#-:-L80zb0i7qRB7B0xbqOG:bnfp4nl)*

**Comment by seanf** [comment]
Verified by @djansen-redhat.

**Pull request merged**
