### PR TITLE
Ensure JS tests can fail the build

### PR DESCRIPTION
**Pull request by seanf**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/675)

### CODE REVIEW

**Comment by seanf** [comment]
Good, the build failed. (Because there are broken unit tests in frontend right now!)

**Comment by kathryngo** [comment]
@seanf just merged the test fixes into release

**Comment by seanf** [comment]
Thanks @kathryngo, I'll run it again.

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/675#-:-L3Bf7JO2MIl8yGQbvz2:bnfp4nl)*

**Comment by seanf** [comment]
The broken build is the one which tests this branch without merging in release, so the test failure is expected. The merged builds are fine.

**Pull request merged**
