### PR TITLE
Znta 1924 compiler warning 2

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1924

Replace org.jboss.resteasy.client.ClientRequest and ClientResponse.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/339)

### CODE REVIEW

**Comment by seanf** [comment]
@aeng that last commit 20774d7 looks like a prime candidate for its own, nicely focussed PR.

**Comment by huangp** [comment]
Reviewed 26 of 125 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/AccountRawCompatibilityITCase.java, line 144 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2KVPMh5dJY3Ps_18G:-Kl2KVPMh5dJY3Ps_18H:b-eeatwq) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/AccountRawCompatibilityITCase.java#L144)):*
> ```Java
>                     throws IOException {
>                 assertThat(response.getStatus(),
>                         is(Status.UNAUTHORIZED.getStatusCode()));
> ```

I think we need to call response.close() to release the connection

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/AccountRawCompatibilityITCase.java, line 205 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2Kwv1Q3-Zk396n2yh:-Kl2Kwv1Q3-Zk396n2yi:b-ll62xm) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/AccountRawCompatibilityITCase.java#L205)):*
> ```Java
> 
>         // Assert initial put
>         assertThat(putResponse.getStatus(), is(Status.CREATED.getStatusCode()));
> ```

should call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/AccountRawCompatibilityITCase.java, line 209 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2Kzbbm94hwPsyCC-E:-Kl2KzbcMOpqWss_6sXl:b-ll62xm) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/AccountRawCompatibilityITCase.java#L209)):*
> ```Java
>         // Modified Account
>         a.setName("New Account Name");
>         putResponse = accountClient.put(a);
> ```

should call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/AccountRawCompatibilityITCase.java, line 242 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2L1f7uZ6vhJlwaQyv:-Kl2L1f7uZ6vhJlwaQyw:b-ll62xm) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/AccountRawCompatibilityITCase.java#L242)):*
> ```Java
> 
>         // Assert initial put
>         assertThat(putResponse.getStatus(), is(Status.FORBIDDEN.getStatusCode()));
> ```

should call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java, line 98 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2LnySlR40uqOOSfzW:-Kl2LnySlR40uqOOSfzX:b-ydo52q) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java#L98)):*
> ```Java
>                         + SimpleComment.ID), true);
> 
>         assertThat(response.getStatus(), is(Status.CREATED.getStatusCode())); // 201
> ```

need to call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java, line 153 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2LrTmpOrgKGLtCtkX:-Kl2LrTmpOrgKGLtCtkY:b-ydo52q) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java#L153)):*
> ```Java
>                         + SimpleComment.ID), true);
> 
>         assertThat(response.getStatus(), is(Status.CREATED.getStatusCode())); // 201
> ```

need to call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java, line 160 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2LsGtJFewFlwg4t_b:-Kl2LsGtJFewFlwg4t_c:b-ydo52q) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java#L160)):*
> ```Java
>                         + SimpleComment.ID), true);
> 
>         assertThat(response.getStatus(), is(Status.CONFLICT.getStatusCode())); // 409
> ```

need to call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java, line 183 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2Lt8sxBCC7WtI7CAf:-Kl2Lt8sxBCC7WtI7CAg:b-ydo52q) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java#L183)):*
> ```Java
>                         PoHeader.ID + ";" + SimpleComment.ID), false);
> 
>         assertThat(response.getStatus(), is(Status.CREATED.getStatusCode())); // 201
> ```

need to call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java, line 272 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2Ltu0klqrW-WnnHit:-Kl2Ltu0klqrW-WnnHiu:b-ydo52q) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java#L272)):*
> ```Java
>                         PoHeader.ID + ";" + SimpleComment.ID), false);
> 
>         assertThat(response.getStatus(), is(Status.CREATED.getStatusCode())); // 201
> ```

need to call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java, line 278 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2LuU9o1JP_Q_NFrwi:-Kl2LuU9o1JP_Q_NFrwj:b-ydo52q) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java#L278)):*
> ```Java
>                 sourceDocClient.deleteResource(res.getName());
> 
>         assertThat(deleteResponse.getStatus(), is(Status.OK.getStatusCode())); // 200
> ```

need to call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java, line 284 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2LvS8332Q-aSyKfQC:-Kl2LvS8332Q-aSyKfQD:b-ydo52q) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java#L284)):*
> ```Java
>                 sourceDocClient.getResource(res.getName(), null);
>         assertThat(getResponse.getStatus(),
>                 is(Status.NOT_FOUND.getStatusCode())); // 404
> ```

need to call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java, line 319 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2Lw8IK9BI_mnZL3SZ:-Kl2Lw8IK9BI_mnZL3S_:b-ydo52q) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java#L319)):*
> ```Java
>                 sourceDocClient.putResourceMeta("my,path,document-2.txt",
>                         resMeta, null);
>         assertThat(putResponse.getStatus(), is(Status.OK.getStatusCode())); // 200
> ```

need to call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java, line 418 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2LwkMXqd2BdV-ilgK:-Kl2LwkMXqd2BdV-ilgL:b-ydo52q) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java#L418)):*
> ```Java
>                                 SimpleComment.ID), "auto");
> 
>         assertThat(putResponse.getStatus(), is(Status.OK.getStatusCode())); // 200
> ```

need to call response.close()

---

*[server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java, line 466 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-Kl2LxNNszcq3IPcPENJ:-Kl2LxNOfzouj48HDo0j:b-ydo52q) ([raw file](https://github.com/zanata/zanata-platform/blob/bf84261a0a8b32981e81aef5bf259bdc34bae375/server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java#L466)):*
> ```Java
>                         LocaleId.EN_US);
> 
>         assertThat(response.getStatus(), is(Status.OK.getStatusCode())); // 200
> ```

need to call response.close()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/339)*

**Comment by aeng** [comment]
@huangp I've updated the PR as per commented.

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(No QA \(2nd vote\)) 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/339#-:-KlLi1UiC1RcgKuPWLdT:b-jf39vt)*

**Comment by seanf** [comment]
@aeng it looks like this PR increased the number of warnings we get in `master`.

**Pull request merged**
