### PR TITLE
Add some missing assertions

### PR DESCRIPTION
**Pull request by seanf**
Found using IntelliJ IDEA's structural search:

    assertThat($actual$)
        .$as$($description$);

where `$as$` is the regex: `(as|describedAs)`

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by seanf** [comment]
@djansen-redhat I added FIXMEs for a few where the intended assertion wasn't clear. See if you can tell.

**Comment by djansen-redhat** [comment]
*[server/functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java, line 76 at r2](https://reviewable.io/reviews/zanata/zanata-platform/835#-LDdc_a17vdrLigCYyRd:-LDdc_a17vdrLigCYyRe:bff1b5y) ([raw file](https://github.com/zanata/zanata-platform/blob/8031f7f3ce194e5e72e84417c9a4a964db2dd60f/server/functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java#L76)):*
> ```Java
>         assertThat(serverConfigurationPage.expectFieldValue(
>                 ServerConfigurationPage.registerUrlField, url))
>                 // FIXME add assertion? this will never be false (timeout exception if missing)
> ```

That indeed looks like a bit of wonky thought on my part. The assertThat is redundant, as is the boolean.
I expect this may have looked different at some point, due to Server Config page lazy loading the content - e.g. waitFor(field present, not empty) return getText == expected.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/835)*

**Comment by djansen-redhat** [comment]
*[server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java, line 89 at r2](https://reviewable.io/reviews/zanata/zanata-platform/835#-LDdtQl647V-naa-RGIs:-LDdtQl647V-naa-RGIt:b-nk3i0) ([raw file](https://github.com/zanata/zanata-platform/blob/8031f7f3ce194e5e72e84417c9a4a964db2dd60f/server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java#L89)):*
> ```Java
>                         .gotoDocumentTab();
>         assertThat(versionDocumentsPage.expectSourceDocsContains(testFileName))
>                 // FIXME should there be another assertion here? (expectSourceDocsContains has one)
> ```

Again, redundant assertThat. Waitforpagesilence may handle this now, not sure.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/835)*

**Comment by aeng** [comment]
Reviewed 2 of 4 files at r2, 3 of 4 files at r3.
Review status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @seanf and @djansen-redhat)

---

*[server/functional-test/src/test/java/org/zanata/feature/project/EditProjectGeneralTest.java, line 87 at r2](https://reviewable.io/reviews/zanata/zanata-platform/835#-LDdvN0U4fjMgJ1BkA82:-LElXQM4-YDGvAheRO07:bn2s3vi) ([raw file](https://github.com/zanata/zanata-platform/blob/8031f7f3ce194e5e72e84417c9a4a964db2dd60f/server/functional-test/src/test/java/org/zanata/feature/project/EditProjectGeneralTest.java#L87)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Yes. There is something definitely missing there.
</blockquote></details>

yup. Need checking on the project status. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/835)*

**Comment by seanf** [comment]
Review status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @seanf and @djansen-redhat)

---

*[server/functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java, line 76 at r2](https://reviewable.io/reviews/zanata/zanata-platform/835#-LDdc_a17vdrLigCYyRd:-LEltGT892Pi-ltHzcKn:bss4a2b) ([raw file](https://github.com/zanata/zanata-platform/blob/8031f7f3ce194e5e72e84417c9a4a964db2dd60f/server/functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java#L76)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

That indeed looks like a bit of wonky thought on my part. The assertThat is redundant, as is the boolean.
I expect this may have looked different at some point, due to Server Config page lazy loading the content - e.g. waitFor(field present, not empty) return getText == expected.
</blockquote></details>

Removed.

---

*[server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java, line 89 at r2](https://reviewable.io/reviews/zanata/zanata-platform/835#-LDdtQl647V-naa-RGIs:-LEltEQcC0JHOAL7N-5m:bss4a2b) ([raw file](https://github.com/zanata/zanata-platform/blob/8031f7f3ce194e5e72e84417c9a4a964db2dd60f/server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java#L89)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Again, redundant assertThat. Waitforpagesilence may handle this now, not sure.
</blockquote></details>

Removed.

---

*[server/functional-test/src/test/java/org/zanata/feature/project/EditProjectGeneralTest.java, line 87 at r2](https://reviewable.io/reviews/zanata/zanata-platform/835#-LDdvN0U4fjMgJ1BkA82:-LEltf_M2b6UxID4ttlT:b9lsnr1) ([raw file](https://github.com/zanata/zanata-platform/blob/8031f7f3ce194e5e72e84417c9a4a964db2dd60f/server/functional-test/src/test/java/org/zanata/feature/project/EditProjectGeneralTest.java#L87)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

yup. Need checking on the project status. 
</blockquote></details>

I'll just leave a TODO for now. At least now we know about the missing check.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/835)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r3.
Review status: all files reviewed, 3 unresolved discussions (waiting on @djansen-redhat)

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/835#-:-LEluv6o5tK5eyhvXm-a:bnfp4nl)*

**Pull request merged**
