### PR TITLE
fix: AddLanguageTest selenium ids

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: N/A

Ant Design form validation getFieldDecorator method overrides the input id's, update selenium test ids to match the overridden form id's in the add language modal.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/829#-:-LD-gn530hLLl4roPE0s:bnfp4nl)*

**Comment by efloden** [comment]
Still waiting for functional test results on this one

**Comment by efloden** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/functional-test/src/main/java/org/zanata/page/administration/AddLanguagePage.java, line 146 at r2](https://reviewable.io/reviews/zanata/zanata-platform/829#-LD0XPCmBMHWC0Yy3o4S:-LD3xsiU4rcS7adgfGrT:bapgmsu) ([raw file](https://github.com/zanata/zanata-platform/blob/c21db971778d108cc185be25f1ee566edb4fcbab/server/functional-test/src/main/java/org/zanata/page/administration/AddLanguagePage.java#L146)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Why did these change?
</blockquote></details>

The ant design checkbox was not being discovered as Enabled with our clickElement method, which does a check for existingElement then isEnabled before attempting to click()

---

*[server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js, line 214 at r2](https://reviewable.io/reviews/zanata/zanata-platform/829#-LD0WyXQ1i75dfh4waXd:-LD3z9kjD0NCyBmCYuwL:bl3qk6k) ([raw file](https://github.com/zanata/zanata-platform/blob/c21db971778d108cc185be25f1ee566edb4fcbab/server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js#L214)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Are these legal comments in JSX? I thought we needed something like `{/* comment /*}`
</blockquote></details>

This <Input> is a react component, so commenting out the prop with // is legal here

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/829)*

**Comment by seanf** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/829#-:-LD4LBS3BrgMtuYeCHuR:bnfp4nl)*

**Pull request merged**
