### PR TITLE
chore(ZNTA-2610): upgrade react to 16.4.0

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2610

Upgrade React to 16.4.0
Upgrade all affected packages.
Resolve new Jest warnings.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 7 of 10 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/882#-:-LEfzqN91iH6mTRl-gkK:bnfp4nl)*

**Comment by djansen-redhat** [comment]
This seems to break the glossary entry details button 

> react-dom.production.min.js:211 Uncaught TypeError: Cannot read property 'contains' of undefined
    at contains.js:17
    at t.B.focus (Modal.js:557)
    at t.B.onShow (Modal.js:486)
    at t.value (Modal.js:243)
    at pr (react-dom.production.min.js:219)
    at fr (react-dom.production.min.js:211)
    at sr (react-dom.production.min.js:210)
    at ur (react-dom.production.min.js:210)
    at interactiveUpdates (react-dom.production.min.js:225)
    at Ke (react-dom.production.min.js:89)

**Comment by djansen-redhat** [comment]
I'll have to check, but I think this may also break pagination on the explore page (page not incremented)

**Comment by djansen-redhat** [comment]
Breaks language page delete function

> middleware.js:176 DELETE http://localhost:8180/rest/locales/locale/ar 405 (Method Not Allowed)
(anonymous) @ middleware.js:176
s @ runtime.js:72
(anonymous) @ runtime.js:334
e.(anonymous function) @ runtime.js:105
s @ runtime.js:72
t @ runtime.js:146
(anonymous) @ runtime.js:154
Promise.then (async)
t @ runtime.js:153
(anonymous) @ runtime.js:191
t @ $.export.js:30
r @ runtime.js:190
n @ runtime.js:211
e.(anonymous function) @ runtime.js:105
Y//3.P.async @ runtime.js:228
(anonymous) @ middleware.js:44
(anonymous) @ index.js:9
dispatch @ applyMiddleware.js:45
(anonymous) @ languages-actions.js:282
(anonymous) @ index.js:9
handleDelete @ index.js:268
n.resetSearchText @ index.js:73
onClick @ DeleteEntry.js:36
n.handleClick @ button.js:112
o @ react-dom.production.min.js:15
invokeGuardedCallback @ react-dom.production.min.js:16
invokeGuardedCallbackAndCatchFirstError @ react-dom.production.min.js:16
c @ react-dom.production.min.js:20
d @ react-dom.production.min.js:22
v @ react-dom.production.min.js:22
p @ react-dom.production.min.js:21
y @ react-dom.production.min.js:24
b @ react-dom.production.min.js:24
ze @ react-dom.production.min.js:88
mr @ react-dom.production.min.js:221
X @ react-dom.production.min.js:44
We @ react-dom.production.min.js:89
interactiveUpdates @ react-dom.production.min.js:225
Ke @ react-dom.production.min.js:89
react-dom.production.min.js:187 TypeError: Cannot read property 'contains' of undefined
    at contains.js:17
    at t.B.focus (Modal.js:557)
    at t.B.onShow (Modal.js:486)
    at t.value (Modal.js:230)
    at pr (react-dom.production.min.js:218)
    at fr (react-dom.production.min.js:211)
    at sr (react-dom.production.min.js:210)
    at ur (react-dom.production.min.js:210)
    at or (react-dom.production.min.js:208)
    at $n (react-dom.production.min.js:206)

**Comment by efloden** [comment]
@djansen-redhat Looks like that error is caused by the react-bootstrap modal:
https://github.com/react-bootstrap/react-bootstrap/issues/2812
Just as well we are replacing them with ant components

**Comment by djansen-redhat** [comment]
Verified

**Pull request merged**
