### PR TITLE
feat(ZNTA-2544): Download user information button added to profile

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2544

_Download user information_ button added to dashboard settings

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 2 of 3 files at r1, 1 of 10 files at r2, 2 of 2 files at r3, 46 of 56 files at r4, 2 of 3 files at r5, 6 of 6 files at r6.
Review status: all files reviewed, 1 unresolved discussion (waiting on @kathryngo)

---

*[server/services/src/main/java/org/zanata/service/GraphQLScalars.kt, line 14 at r6](https://reviewable.io/reviews/zanata/zanata-platform/920#-LFoSBce037OLpEjDuR7:-LFoSBcf1j80DRmxgncR:b3txet8) ([raw file](https://github.com/zanata/zanata-platform/blob/87ce1510d1a3c23fc067bf8bef022f69f9bd6a44/server/services/src/main/java/org/zanata/service/GraphQLScalars.kt#L14)):*
> ```Kotlin
> 
> /**
>  * T must have a public constructor which accepts a String, and a suitable toString() method.
> ```

The JAX-RS standard is to have a static method fromString(String) to convert between Java object and json string. It might be helpful to piggybacking on this so the DTO/object can be used both in graphql and JAX-RS. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/920)*

**Comment by seanf** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @kathryngo)

---

*[server/services/src/main/java/org/zanata/service/GraphQLScalars.kt, line 14 at r6](https://reviewable.io/reviews/zanata/zanata-platform/920#-LFoSBce037OLpEjDuR7:-LFoid7b8SHDjNL8VcNq:b-sjcmr3) ([raw file](https://github.com/zanata/zanata-platform/blob/87ce1510d1a3c23fc067bf8bef022f69f9bd6a44/server/services/src/main/java/org/zanata/service/GraphQLScalars.kt#L14)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

The JAX-RS standard is to have a static method fromString(String) to convert between Java object and json string. It might be helpful to piggybacking on this so the DTO/object can be used both in graphql and JAX-RS. 
</blockquote></details>

Can you point me at that info, please? The closest I can find is ParamConverter, but it's a separate interface, and thus doesn't specify a static method:

https://dennis-xlc.gitbooks.io/restful-java-with-jax-rs-2-0-en/en/part1/chapter5/common_functionality.html (section "ParamConverters")

Although there is the static method valueOf(): see the section "Java object conversion" in the book above.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/920)*

**Comment by huangp** [comment]
Reviewed 1 of 6 files at r7, 4 of 4 files at r8.
Review status: all files reviewed, 1 unresolved discussion (waiting on @seanf and @kathryngo)

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/920)*

**Comment by spathare21** [comment]
Verified looks good

**Comment by spathare21** [comment]
@kathryngo it is showing 2 buttons for exporting user data
screenshot from 2018-06-25 11-17-11

**Comment by kathryngo** [comment]
thanks for noticing that @spathare21 
shall fix

**Comment by kathryngo** [comment]
@spathare21 fixed, ready for continued QA

**Comment by seanf** [comment]
Merged as https://github.com/zanata/zanata-platform/commit/91c1a6ff6beceab147739417e3c73a2ca9c98b9a

**Pull request closed without merging**
