### PR TITLE
Add Maven badges for Zanata clients

### PR DESCRIPTION
**Pull request by seanf**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/417)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[client/README.md, line 4 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/417#-KoeQWMKZlx5cUcgXDMA:-KoeQWMKZlx5cUcgXDMB:b-k99r4v) ([raw file](https://github.com/zanata/zanata-platform/blob/5aefa2f0a41bb77f55dd8cfa096fa5fe6527a37c/client/README.md#L4)):*
> ```Markdown
> It also contains client-side bindings for interacting with a Zanata server's REST API.
> 
> Latest version of zanata-cli: [Maven Central](https://maven-badges.herokuapp.com/maven-central/org.zanata/zanata-cli)
> ```

Just comment, I used shields.io for zanata-mt, but i think its the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/417#-:-KoeQle2BsaFKo6l3XqY:bnfp4nl)*

**Comment by seanf** [comment]
@aeng I added a badge for the licence, and found that `licensee` thinks Zanata is GPL. I've renamed the files, which should fix the problem once this is merged to `master` (I think).

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/417#-:-KoiY-GGP0fcRqS70Cfq:bnfp4nl)*

**Comment by aeng** [comment]
@seanf checkstyle failure.

**Pull request merged**
