### PR TITLE
Polyfills for tablets (ZNTA-1988, ZNTA-1989)

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL:

* https://zanata.atlassian.net/browse/ZNTA-1988
* https://zanata.atlassian.net/browse/ZNTA-1989
* ~~https://zanata.atlassian.net/browse/ZNTA-1790~~

Polyfill `Symbol` and `Intl` for mobile browsers. The `Intl` polyfill is large so it is loaded as a separate chunk only loaded if needed. ~~Sets the history basename so that the editor should work for any path the server is deployed to (e.g. /zanata)~~

*Reviewers* note that index.js has most of its contents wrapped in a function, so it looks like a lot of changes but really it is just indented. The new part is the `if (window.Intl)` block at the bottom, the `history.basename` line and the assignment to `__webpack_public_path__`

## Testing notes

- Test it for Symbol and Intl with BrowserStack.
   - The layout is broken on Safari 8, but that is a separate issue and needs a separate JIRA.
- ~~Deploy to /zanata and confirm that editor loads properly instead of giving a message about a different required URL structure.~~

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/341)

### CODE REVIEW

**Comment by kathryngo** [comment]
@davidmason 
Bum bow...
`
[Error] SyntaxError: Unexpected token '<'
(anonymous function) (intl-polyfill.min.js, line 1)
`

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/341#-:-KlMRqU0NAgrqyjxWy3E:bnfp4nl)*

**Comment by aeng** [comment]
Should we implement this for frontend too?

**Comment by davidmason** [comment]
> Should we implement this for frontend too?

@aeng only if we start using `Intl` in frontend - we can bring it across if we do.
The other two fixes are not needed in frontend - the fix was actually to make editor do the same thing frontend was already doing.

**Comment by djansen-redhat** [comment]
Using browserstack, I can't seem to load the gwt editor, and loading the alpha editor has a 3.5MB asset

bs_macelc_safari_9 1 1
bs_macelc_safari_9 1

**Comment by djansen-redhat** [comment]
navmenulayoutbad-left_pr-right_release

**Comment by djansen-redhat** [comment]
/zanata deployment did not seem to work in cargo

**Pull request merged**
