### PR TITLE
ZNTA-2225 - define java.home sys prop

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2225
- add system property zanata.home as a root for all storage related properties

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/550)

### CODE REVIEW

**Comment by seanf** [comment]
@huangp Do we need to change anything in org.zanata.liquibase.custom.MigrateRawDocumentsToFileSystem ?

**Comment by seanf** [comment]
@huangp I think you need to look at FileSystemPersistService too. It might help if you make SystemPropertyConfigStore.KEY_DOCUMENT_FILE_STORE private like the other property names.

**Comment by seanf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvVn_nWFF_bq3BOnFxM:-KvVn_nWFF_bq3BOnFxN:bbkkaty) (no related file):*
@huangp You should add something to the release notes about the change in system properties.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/550)*

**Comment by huangp** [comment]
No need to change MigrateRawDocumentsToFileSystem as it refers to the old system property. It's used when running liquibase in standalone mode. For this reason, it can't be made as private. 

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvVn_nWFF_bq3BOnFxM:-KvVq5rO7gCArEYMays6:bb6un1j) (no related file):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

@huangp You should add something to the release notes about the change in system properties.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-:-KvVq9CqrLZfODoXr0T8:b-7tf0jo)*

**Comment by seanf** [comment]
Reviewed 2 of 3 files at r1, 1 of 2 files at r2.
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java, line 129 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvVtNMPUosw5KGRhNNZ:-KvVtNMPUosw5KGRhNN_:bm96set) ([raw file](https://github.com/zanata/zanata-platform/blob/e23b3c01740b2707106687f17a935d58f996bd01/server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java#L129)):*
> ```Java
> 
>     public String getDocumentFileStorageLocation() {
>         return System.getProperty(KEY_DOCUMENT_FILE_STORE, new File(getZanataHome(), "file").getAbsolutePath());
> ```

This method used to return null if the admin hadn't configured the system property, which allowed FileSystemPersistService to detect that situation and generate a useful error message.

---

*[server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java, line 133 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvVt1PM3vGY9CHyGVQZ:-KvVt1PM3vGY9CHyGVQ_:b-deay65) ([raw file](https://github.com/zanata/zanata-platform/blob/e23b3c01740b2707106687f17a935d58f996bd01/server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java#L133)):*
> ```Java
> 
>     public String getHibernateSearchIndexBase() {
>         return System.getProperty(KEY_HIBERNATE_SEARCH_INDEX_BASE, new File(getZanataHome(), "indexes").getAbsolutePath());
> ```

I don't think Hibernate Search calls this method. It's still going to look at the system property `hibernate.search.default.indexBase` unless we start configuring Hibernate/Search programmatically.

---

*[server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java, line 137 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvVryFXW9pMO0v3qnxL:-KvVryFXW9pMO0v3qnxM:b7ufwq) ([raw file](https://github.com/zanata/zanata-platform/blob/e23b3c01740b2707106687f17a935d58f996bd01/server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java#L137)):*
> ```Java
> 
>     public String getZanataHome() {
>         return System.getProperty(KEY_ZANATA_HOME);
> ```

`FileSystemPersistService.ensureDocsDirectory()` used to throw an exception if its system property was unset. Perhaps we ought to do that here (or ZanataInit, but here might be cleaner) if zanata.home is unset. As an improvement, we could make sure it happens at deploy time (ie startup).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/550)*

**Comment by huangp** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java, line 129 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvVtNMPUosw5KGRhNNZ:-KvVvMjRvMFZbbWRDs3K:b6zt3qe) ([raw file](https://github.com/zanata/zanata-platform/blob/e23b3c01740b2707106687f17a935d58f996bd01/server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java#L129)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

This method used to return null if the admin hadn't configured the system property, which allowed FileSystemPersistService to detect that situation and generate a useful error message.
</blockquote></details>

But now that we will use a default derived from zanata.home. There won't be a case for missing the value any more.

---

*[server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java, line 133 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvVt1PM3vGY9CHyGVQZ:-KvVx7Vn0pDSxbN_pWRj:b-j2siob) ([raw file](https://github.com/zanata/zanata-platform/blob/e23b3c01740b2707106687f17a935d58f996bd01/server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java#L133)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I don't think Hibernate Search calls this method. It's still going to look at the system property `hibernate.search.default.indexBase` unless we start configuring Hibernate/Search programmatically.
</blockquote></details>

True. So it will be the same as javamelody. We can't make this optional.

---

*[server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java, line 137 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvVryFXW9pMO0v3qnxL:-KvVvi-pVZmk1u1YESNE:buagrl0) ([raw file](https://github.com/zanata/zanata-platform/blob/e23b3c01740b2707106687f17a935d58f996bd01/server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java#L137)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

`FileSystemPersistService.ensureDocsDirectory()` used to throw an exception if its system property was unset. Perhaps we ought to do that here (or ZanataInit, but here might be cleaner) if zanata.home is unset. As an improvement, we could make sure it happens at deploy time (ie startup).
</blockquote></details>

If admin didn't configure it, it will be defaulted to under zanata.home. There is no need to warn or throw error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/550)*

**Comment by huangp** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java, line 137 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvVryFXW9pMO0v3qnxL:-KvVzDn29iEMiZ9QRtKt:brc66uv) ([raw file](https://github.com/zanata/zanata-platform/blob/e23b3c01740b2707106687f17a935d58f996bd01/server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java#L137)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

If admin didn't configure it, it will be defaulted to under zanata.home. There is no need to warn or throw error.
</blockquote></details>

Sorry this is about java.home. It's under REQUIRED_PROP_KEYS which is checked at startup. So an error message will be thrown at startup if missing. Same goes with the other two (hibernate search and javamelody). Only zanata.file.storage became optional now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/550)*

**Comment by seanf** [comment]
Reviewed 1 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/release-notes.md, line 5 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvW1vPyXsFoJEFHZ7w4:-KvW1vPyXsFoJEFHZ7w5:b-yptivy) ([raw file](https://github.com/zanata/zanata-platform/blob/29656ef73fdc273add65584d59ff9e5b6c5b23a6/docs/release-notes.md#L5)):*
> Previously defined 'zanata.file.directory' will still work.
> But if you omit it, it will be derived from 'zanata.home' as sub directories.

"directories" should be singular now. I suggest this wording:

The property 'zanata.file.directory' is still supported, but if it is missing, a sub-directory of 'zanata.home' will be used.

---

*[server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java, line 137 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvVryFXW9pMO0v3qnxL:-KvW18v2qjW10rq1tM86:bq5q2ov) ([raw file](https://github.com/zanata/zanata-platform/blob/e23b3c01740b2707106687f17a935d58f996bd01/server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java#L137)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Sorry this is about java.home. It's under REQUIRED_PROP_KEYS which is checked at startup. So an error message will be thrown at startup if missing. Same goes with the other two (hibernate search and javamelody). Only zanata.file.storage became optional now.
</blockquote></details>

Okay. For clarity, it would be good to have an `assert` about the result being non-null/non-empty here.

---

*[server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java, line 65 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvW0j-5pb29FntFi2-w:-KvW0j-5pb29FntFi2-x:b-7hsfoo) ([raw file](https://github.com/zanata/zanata-platform/blob/29656ef73fdc273add65584d59ff9e5b6c5b23a6/server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java#L65)):*
> ```Java
>             "javamelody.storage-directory";
>     private static final String KEY_ZANATA_HOME = "zanata.home";
>     private static final Set<String> REQUIRED_PROP_KEYS = ImmutableSet
> ```

Could you please add a comment pointing at SystemConfigStartupCheck to explain that these will be checked at startup? The fact that it happens in a different file obscures the intention a bit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/550)*

**Comment by huangp** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/release-notes.md, line 5 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvW1vPyXsFoJEFHZ7w4:-KvZccByzlk_pAoznfqO:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/29656ef73fdc273add65584d59ff9e5b6c5b23a6/docs/release-notes.md#L5)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

> Previously defined 'zanata.file.directory' will still work.
> But if you omit it, it will be derived from 'zanata.home' as sub directories.

"directories" should be singular now. I suggest this wording:

The property 'zanata.file.directory' is still supported, but if it is missing, a sub-directory of 'zanata.home' will be used.
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java, line 137 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvVryFXW9pMO0v3qnxL:-KvZcZpsrn_Dnf-ugX8g:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/e23b3c01740b2707106687f17a935d58f996bd01/server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java#L137)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Okay. For clarity, it would be good to have an `assert` about the result being non-null/non-empty here.
</blockquote></details>

Done.

---

*[server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java, line 65 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-KvW0j-5pb29FntFi2-w:-KvZca_7O82DAzDWI9q3:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/29656ef73fdc273add65584d59ff9e5b6c5b23a6/server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java#L65)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Could you please add a comment pointing at SystemConfigStartupCheck to explain that these will be checked at startup? The fact that it happens in a different file obscures the intention a bit.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/550)*

**Comment by seanf** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/etc/scripts/zanata-config-test-common.cli, line 14 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-Kvf0ToTMzbcZCOrqXh5:-Kvf0ToUwrIC_1jnGSwl:bys4oqj) ([raw file](https://github.com/zanata/zanata-platform/blob/e2ce1d355a0892fc9422da7f3aaa9175143c9132/server/etc/scripts/zanata-config-test-common.cli#L14)):*
> ```
> /system-property="javamelody.storage-directory":add(value="${jboss.server.data.dir}/zanata/stats: ")
> /system-property="hibernate.search.default.indexBase":add(value="${jboss.server.data.dir}/zanata/indexes: ")
> /system-property="zanata.home":add(value="${jboss.server.data.dir}/zanata: ")
> ```

I've noticed some directories with names like `stats:` being created in the zanata directory. Are you sure the colon works as expected here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/550)*

**Comment by huangp** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/etc/scripts/zanata-config-test-common.cli, line 14 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-Kvf0ToTMzbcZCOrqXh5:-Kvj0IqVImTF8oJOrBZM:bzb0jgq) ([raw file](https://github.com/zanata/zanata-platform/blob/e2ce1d355a0892fc9422da7f3aaa9175143c9132/server/etc/scripts/zanata-config-test-common.cli#L14)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I've noticed some directories with names like `stats:` being created in the zanata directory. Are you sure the colon works as expected here?
</blockquote></details>

Fixed. It used to evaluate the variable at cli application time. Therefore the colon trick to workaround it. Now it won't so no need to at that colon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/550)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-:-KvjYAvmUHyCV2z2BJku:bnfp4nl)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/550#-:-KvjhA2zJEWHPpcPRBia:bnfp4nl)*

**Pull request merged**
