### PR TITLE
ZNTA-1445 - use jboss cli script to modify standalone-full.xml

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1445

Use jboss cli script to customize standalone-full.xml for docker zanata dev 

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/30)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/docker/Dockerfile, line 11 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/30#-KVe1-uqEBextieTxRDe:-KVe1-uqEBextieTxRDf:bxhiehb) ([raw file](https://github.com/zanata/zanata-platform/blob/9bd693c291e40b4fb01435a023970a3575a69333/server/docker/Dockerfile#L11)):*
> ```Dockerfile
>     ln -sf /usr/share/java/mysql-connector-java.jar /opt/jboss/wildfly/modules/com/mysql/main/mysql-connector-java.jar
> 
> COPY conf/zanata-config.cli.script /opt/jboss/wildfly/standalone/configuration/
> ```

You know, you can always override the .gitignore with `git add -f`, or we could consider removing .cli from the .gitignore. The comment says "binary files" which seems to be a mistake.

It looks like `.cli` _is_ the conventional extension for these files.

---

*[server/docker/Dockerfile, line 15 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/30#-KVe47Rdl0NieQkOvj_V:-KVe47Rdl0NieQkOvj_W:b9sejuc) ([raw file](https://github.com/zanata/zanata-platform/blob/9bd693c291e40b4fb01435a023970a3575a69333/server/docker/Dockerfile#L15)):*
> ```Dockerfile
> USER jboss
> 
> RUN /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/wildfly/standalone/configuration/zanata-config.cli.script
> ```

We should be able to a layer by using --file=- to read the cli script from stdin, instead of adding it to the image.

---

*[server/docker/Dockerfile, line 18 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/30#-KVe3tcdSHXR5gYvdZIF:-KVe3tceUjvi_gp-KOSd:b7orp7g) ([raw file](https://github.com/zanata/zanata-platform/blob/9bd693c291e40b4fb01435a023970a3575a69333/server/docker/Dockerfile#L18)):*
> ```Dockerfile
> 
> # Enable debugging of the appserver
> #RUN echo "JAVA_OPTS=\"\$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n\"" >> /opt/jboss/wildfly/bin/standalone.conf
> ```

Why is this commented out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/30)*

**Comment by huangp** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/docker/Dockerfile, line 11 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/30#-KVe1-uqEBextieTxRDe:-KVgRGTFqOCguoRk2Pq4:bkcitt4) ([raw file](https://github.com/zanata/zanata-platform/blob/9bd693c291e40b4fb01435a023970a3575a69333/server/docker/Dockerfile#L11)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> You know, you can always override the .gitignore with `git add -f`, or we could consider removing .cli from the .gitignore. The comment says "binary files" which seems to be a mistake.
> 
> It looks like `.cli` _is_ the conventional extension for these files.
</details>
I know I can use ```git add -f``` but I am not sure what happens next time when the file is changed. I don't want to remember to use -f each time. If removing .cli from the top level ignore file is ok, I will change the name back. cli is the convention for jboss cli script.

---

*[server/docker/Dockerfile, line 15 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/30#-KVe47Rdl0NieQkOvj_V:-KVgTzNrCCtQmN4gARXi:b-4ridvo) ([raw file](https://github.com/zanata/zanata-platform/blob/9bd693c291e40b4fb01435a023970a3575a69333/server/docker/Dockerfile#L15)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> We should be able to a layer by using --file=- to read the cli script from stdin, instead of adding it to the image.
</details>
When I try to use ```--file=-``` result in ```File /opt/jboss/- doesn't exist.``` We still need to copy other files under that folder. If we really want to save a layer, we could combine the COPY and RUN.  I'd rather keep it simple

---

*[server/docker/Dockerfile, line 18 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/30#-KVe3tcdSHXR5gYvdZIF:-KVgSGvfxGGJ6hn9T3Ir:b-sama7z) ([raw file](https://github.com/zanata/zanata-platform/blob/9bd693c291e40b4fb01435a023970a3575a69333/server/docker/Dockerfile#L18)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Why is this commented out?
</details>
Because it's not needed. I changed the CMD to have ```--debug``` which does this for us. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/30)*

**Comment by seanf** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/docker/Dockerfile, line 15 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/30#-KVglwH_Loav5o4Akq9x:-KVglwH_Loav5o4Akq9y:b-1uryqh) ([raw file](https://github.com/zanata/zanata-platform/blob/757b3d310ed929b3ae13b1fcdb9f01d151055c8d/server/docker/Dockerfile#L15)):*
> ```Dockerfile
> USER jboss
> 
> RUN /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/wildfly/standalone/configuration/zanata-config.cli
> ```

I think it's misleading to put the temporary file zanata-config.cli into /opt/jboss/wildfly/standalone/configuration/. If we can't eliminate the file, let's just put it in /tmp.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/30)*

**Comment by huangp** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/docker/Dockerfile, line 15 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/30#-KVglwH_Loav5o4Akq9x:-KVh4NekM7EsD852WNA9:bp9gsmw) ([raw file](https://github.com/zanata/zanata-platform/blob/757b3d310ed929b3ae13b1fcdb9f01d151055c8d/server/docker/Dockerfile#L15)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I think it's misleading to put the temporary file zanata-config.cli into /opt/jboss/wildfly/standalone/configuration/. If we can't eliminate the file, let's just put it in /tmp.
</details>
It's part of configuration process. But I am fine with putting it to /tmp.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/30)*

**Comment by seanf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/30)*

**Comment by seanf** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/30#-:-KVhBmPczrq3NeIhAG4G:bnfp4nl)*

**Pull request merged**
