### PR TITLE
Flux Standard Actions

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: *I didn't make a JIRA for this, just hacking :)*

This PR makes all the redux actions in the editor into "Flux Standard Actions" (FSAs).
I also changed all the `Symbol` action types back to strings, because `Symbol` was a bad idea (not serializable so it means we would never be able to set up time-travel debugging).

## Reviewer Info

I changed a single action in each commit, and updated any related action creators, where the reducer used that action, and tests for the reducer. I recommend reviewing commit-by-commit because it will be a lot easier to see each logical set of changes.

### What are FSAs?

This relates to the diagram in `frontend/app/editor/README.md`, specifically `dispatch(action)` - those actions are what are being updated here.

An action is just an object with a type, and it can have anything else in there

```
{
  type: 'UNCOOL_ACTION',
  stuff: [1, 2, 3]
  junk: 'this is junk'
}
```

That action there is not a Flux Standard Action (FSA). FSAs have a specific structure, which makes it easier to remember where the data is (if they have any data) and easier to make libraries to work with them (like `redux-api-middleware`). An FSA is structured like this:

```
{
  type: 'COOL_ACTION`,
  payload: [4, 5, 6],     // optional
  meta: { sweet: true },  // very optional
  error: false
}
```

So they have a standard way to indicate when there's an error (the error detail usually goes in the payload when `error` is `true`, a standard place to put the data (`payload`), and a standard place to put related data that is not part of the payload (`meta`).

### Why use FSAs

So as well as the standard place for errors etc., another benefit is we can use `createAction` from `redux-actions` to make an action creator function for these actions. It can save a lot of boilerplate.

Instead of this:

```
const setUsername = (name) => ({
  type: 'SET_USERNAME',
  payload: name
})
```

we can use this:

```
const setUsername = createAction('SET_USERNAME')
```

Both of them return the same thing when you call them (e.g. `setUsername('Humpty Dumpty')`).

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/533)

### CODE REVIEW

**Comment by kathryngo** [comment]
Reviewed 28 of 29 files at r1.
Review status: 28 of 29 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json, line 57 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/533#-KurxganDM41MDaTepM0:-KurxganDM41MDaTepM1:b-grctt0) ([raw file](https://github.com/zanata/zanata-platform/blob/58d726788ca4b5275938082f9317f4fdcac8855d/server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json#L57)):*
> ```JSON
>     "defaultMessage": "{name} has {deletedTranslation}"
>   }
> ]
> ```

New line needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/533)*

**Comment by davidmason** [comment]
Review status: 28 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json, line 57 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/533#-KurxganDM41MDaTepM0:-KuvU6fcwgnnvvQMwp-J:b-bzhdiw) ([raw file](https://github.com/zanata/zanata-platform/blob/58d726788ca4b5275938082f9317f4fdcac8855d/server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json#L57)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

New line needed
</blockquote></details>

I don't even know how that got in there. I didn't even touch that file. Oh well, fixing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/533)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json, line 57 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/533#-KurxganDM41MDaTepM0:-KuwBQNyRRmqM3mzoZ4_:btity3k) ([raw file](https://github.com/zanata/zanata-platform/blob/58d726788ca4b5275938082f9317f4fdcac8855d/server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json#L57)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

I don't even know how that got in there. I didn't even touch that file. Oh well, fixing.
</blockquote></details>

I know that feeling all too well. Shall approve as soon as this is fixed. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/533)*

**Comment by davidmason** [comment]
Review status: 28 of 29 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json, line 57 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/533#-KurxganDM41MDaTepM0:-KuvUe19_qxWwUV5YZnr:b-s44gsm) ([raw file](https://github.com/zanata/zanata-platform/blob/58d726788ca4b5275938082f9317f4fdcac8855d/server/zanata-frontend/src/frontend/build/messages/app/editor/components/ActivityFeedItem/index.json#L57)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

I know that feeling all too well. Shall approve as soon as this is fixed. :)
</blockquote></details>

Oh wait, this is a generated file for translations. If we add a newline on it, it will just get overwritten next time a build runs. I probably added a newline last time.

... and I just realized I forgot to publish this comment yesterday :confounded: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/533)*

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 1 of 29 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/533#-:-Kv-TZgxRpTbt8ezDfWT:bnfp4nl)*

**Comment by kathryngo** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/533)*

**Comment by kathryngo** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/533#-:-KvArqiD_HiaQBp2UVx1:bnfp4nl)*

**Comment by djansen-redhat** [comment]
I think this is good to go.

**Comment by davidmason** [comment]
This has been merged with #545

**Pull request closed without merging**
