### PR TITLE
refactor: rename tribes to languages

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1684:

JIRA issue URL: *paste URL here*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/323)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/dto/Account.java, line 147 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/323#-KkDxHlD7zIf4Zquq8lz:-KkDxHlEpswt1sDVMA-T:bxluqt4) ([raw file](https://github.com/zanata/zanata-platform/blob/b2d4e8efb95b4c5162bd418eb67fc3691d3ebc64/api/zanata-common-api/src/main/java/org/zanata/rest/dto/Account.java#L147)):*
> ```Java
>     @JsonProperty("languages")
>     @DocumentationExample(value = "es", value2 = "ja")
>     public Set<String> getLanguages() {
> ```

This breaks backward compatibility. We might need to retain the old getter method (with all annotations) and put @Deprecated on it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/323)*

**Comment by carlosmunoz** [comment]
This will have an impact on API users, how are we handling this?

**Comment by aeng** [comment]
@huangp Updated the PR.
@carlosmunoz at the moment, it is backward compatible.

**Comment by huangp** [comment]
:lgtm: just remove the old setter method -(Awaiting review)  +Reviewed +(On QA) 

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[api/zanata-common-api/src/main/java/org/zanata/rest/dto/Account.java, line 170 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/323#-KkDz_oy-XdQCPVbRvJw:-KkDz_oy-XdQCPVbRvJx:b7tzhpf) ([raw file](https://github.com/zanata/zanata-platform/blob/fbc588d04131020a2bb094c587979b8c82194e02/api/zanata-common-api/src/main/java/org/zanata/rest/dto/Account.java#L170)):*
> ```Java
>      */
>     @Deprecated
>     public void setTribes(Set<String> tribes) {
> ```

We can get rid of the setter method. It won't affect anything. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/323#-:-KkDznwwmefvv9lHEwYp:b-5lxp8o)*

**Pull request merged**
