### PR TITLE
fix(ZNTA-2396): TM suggestion highlighting shows mismatched diff 

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2396
Duplicates: https://zanata.atlassian.net/browse/ZNTA-2397 

Zanata TM highlighting is confusing for low-similarity matches due to a mismatch between the backend TM matching and the frontend (GWT and React Editor) diffing algorithms.

## QA
The TM Suggestions should now correctly display matches on full words for both the GWT editor and Alpha editor (using the same diff library). 
Punctuation not effect the diff now (punctuation causing the initial issue with matching words not being displayed).
The matching words of a source/target diff should be more evident now:
worddiff
The simple diff mode has also been modified to highlight the Matching parts, rather than non-matching:
highlightdiff
The diff views in the Alpha editor should be identical.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 4 of 4 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java, line 245 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/747#-L7YSEQK5RywNOJ3lpTJ:-L7YSEQK5RywNOJ3lpTK:b-3blsto) ([raw file](https://github.com/zanata/zanata-platform/blob/053b143460119e4ac765e2bb35807d288c7361ed/server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java#L245)):*
> ```Java
>             searchOnly.addStyleName("is-hidden");
>             notMatching.addStyleName("CodeMirror-searching");
>             notMatching.setText(messages.matching());
> ```

Could you please refactor `notMatching` to `matching`?

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java, line 276 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/747#-L7YSw-tLK4-fBBlx0bm:-L7YSw-tLK4-fBBlx0bn:bejfvf6) ([raw file](https://github.com/zanata/zanata-platform/blob/053b143460119e4ac765e2bb35807d288c7361ed/server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java#L276)):*
> ```Java
>         } else {
>             SafeHtml safeHtmlHighlight =
>                     TextContentsDisplay.asDiffHighlight(queriesPadded, sourceContents).toSafeHtml();
> ```

Such a simple fix, so painful to find!

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml, line 72 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/747#-L7YSKaZJSk4Z7WK_ydU:-L7YSKaZJSk4Z7WK_ydV:b-3zem7l) ([raw file](https://github.com/zanata/zanata-platform/blob/053b143460119e4ac765e2bb35807d288c7361ed/server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml#L72)):*
> ```XML
>         <g:FocusPanel ui:field="diffLegend" styleName="{style.legend} bx--inline">
>           <g:HTMLPanel styleName="bx--inline button--link">
>             <g:InlineLabel styleName="CodeMirror-searching l--pad-h-quarter" ui:field="notMatching">Matching</g:InlineLabel>
> ```

Could you please rename `notMatching` to `matching` in this file too?

---

*[server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap, line 7663 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/747#-L7YTC4limYrqtnIZy-P:-L7YTC4limYrqtnIZy-Q:bx4wcgm) ([raw file](https://github.com/zanata/zanata-platform/blob/053b143460119e4ac765e2bb35807d288c7361ed/server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap#L7663)):*
> ```
>   </ins>
>   <span>
>      it 
> ```

This all looks better to me, but @kathryngo should review this snapshot change.

---

*[server/zanata-frontend/src/app/editor/components/TextDiff/TextDiff.test.js, line 18 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/747#-L7YSmrvzwd9YSTTqtNj:-L7YSmrvzwd9YSTTqtNk:bszm2f7) ([raw file](https://github.com/zanata/zanata-platform/blob/053b143460119e4ac765e2bb35807d288c7361ed/server/zanata-frontend/src/app/editor/components/TextDiff/TextDiff.test.js#L18)):*
> ```JavaScript
>         <del>best</del>
>         <ins>worst</ins>
>         <span> of times</span>
> ```

Much better!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/747)*

**Comment by efloden** [comment]
Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java, line 245 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/747#-L7YSEQK5RywNOJ3lpTJ:-L7bBkYQ8YCM9xF_PKsw:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/053b143460119e4ac765e2bb35807d288c7361ed/server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java#L245)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Could you please refactor `notMatching` to `matching`?
</blockquote></details>

Done.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml, line 72 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/747#-L7YSKaZJSk4Z7WK_ydU:-L7bCJZC7fz9fYYCHR1y:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/053b143460119e4ac765e2bb35807d288c7361ed/server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml#L72)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Could you please rename `notMatching` to `matching` in this file too?
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap, line 7663 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/747#-L7YTC4limYrqtnIZy-P:-L7bJdDtA3u08J_NRrG6:b-tm470y) ([raw file](https://github.com/zanata/zanata-platform/blob/053b143460119e4ac765e2bb35807d288c7361ed/server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap#L7663)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

This all looks better to me, but @kathryngo should review this snapshot change.
</blockquote></details>

Kathryn likes the changes :+1: 

---

*[server/zanata-frontend/src/app/editor/components/TextDiff/TextDiff.test.js, line 18 at r3](https://beta.reviewable.io/reviews/zanata/zanata-platform/747#-L7YSmrvzwd9YSTTqtNj:-L7bCP7yDH_8jeMORNOr:b-95o49j) ([raw file](https://github.com/zanata/zanata-platform/blob/053b143460119e4ac765e2bb35807d288c7361ed/server/zanata-frontend/src/app/editor/components/TextDiff/TextDiff.test.js#L18)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Much better!
</blockquote></details>

Agreed! hopefully much more human readable

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/747)*

**Comment by seanf** [comment]
:lgtm: Good stuff!

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/747#-:-L7bQLfC6YIbU-0mMdOs:b-m6xbb3)*

**Comment by spathare21** [comment]
@efloden have to ignore the code coverage?

**Comment by efloden** [comment]
@spathare21 in this case the new file is being implemented differently in one of sean's branches, should I write a test for it here @seanf ?

**Comment by seanf** [comment]
The test in my branch will do. (https://github.com/zanata/zanata-platform/pull/511)

:lgtm: 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/747#-:-L7wuI5PVq6Qu9JZarut:b6l1dv6)*

**Pull request merged**
