### PR TITLE
ZNTA-1507 - enable javamelody heap dump

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1507

- include sun.jdk module in jboss deployment structure
- upgrade javamelody to 1.62.0
- add the missing class path to sun.jdk module file for dev docker image

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/52)

### CODE REVIEW

**Comment by davidmason** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/docker/conf/sun/jdk/module.xml, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/52#-KX2nCj9sgAszhVagxSh:-KX2nCjA_Ax_8-IFXim0:b-tx3212) ([raw file](https://github.com/zanata/zanata-platform/blob/f9e48ad0a420230195fae8016138f3b89fc37d2d/server/docker/conf/sun/jdk/module.xml#L24)):*
> ```XML
>   ~ 02110-1301 USA, or see the FSF site: http://www.fsf.org.
>   -->
> <module xmlns="urn:jboss:module:1.3" name="sun.jdk">
> ```

It looks like this file is copied from somewhere, then has a line added. We should state explicitly exactly where it was copied from.
If we include the issue URL here as well, it will be easy to do a search for the URL when we want to remove all these changes.

---

*[server/docker/conf/sun/jdk/module.xml, line 26 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/52#-KX2mxwTGtVYL2wS5Oqs:-KX2mxwTGtVYL2wS5Oqt:b-bybsg7) ([raw file](https://github.com/zanata/zanata-platform/blob/f9e48ad0a420230195fae8016138f3b89fc37d2d/server/docker/conf/sun/jdk/module.xml#L26)):*
> ```XML
> <module xmlns="urn:jboss:module:1.3" name="sun.jdk">
>     <resources>
>

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/docker/conf/sun/jdk/module.xml, line 26 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/52#-KX2mxwTGtVYL2wS5Oqs:-KX2qx5bk4qLx-xc6Kmq:b-1yylcr) ([raw file](https://github.com/zanata/zanata-platform/blob/f9e48ad0a420230195fae8016138f3b89fc37d2d/server/docker/conf/sun/jdk/module.xml#L26)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> Typo: "... has no way ..."
</details>
Actually, make that "... have no way ..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/52)*

**Comment by huangp** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/docker/conf/sun/jdk/module.xml, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/52#-KX2nCj9sgAszhVagxSh:-KX46oi_UDWzomLGCGpF:b-iextq0) ([raw file](https://github.com/zanata/zanata-platform/blob/f9e48ad0a420230195fae8016138f3b89fc37d2d/server/docker/conf/sun/jdk/module.xml#L24)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> It looks like this file is copied from somewhere, then has a line added. We should state explicitly exactly where it was copied from.
> If we include the issue URL here as well, it will be easy to do a search for the URL when we want to remove all these changes.
</details>
It's a JBoss module so follow JBoss/Wildfly convention. e.g ```${JBOSS_HOME}/modules/system/layers/base/``` then ```sun/jdk``` (as the module name is sun.jdk) I have a comment in the Dockerfile to explain why we need to have this file and what needs to change. It's meant for a temporary workaround until an issue in Javamelody is fixed.

---

*[server/docker/conf/sun/jdk/module.xml, line 26 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/52#-KX2mxwTGtVYL2wS5Oqs:-KX47gIsDwxgjDBoNbQC:b-45sfy6) ([raw file](https://github.com/zanata/zanata-platform/blob/f9e48ad0a420230195fae8016138f3b89fc37d2d/server/docker/conf/sun/jdk/module.xml#L26)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> Actually, make that "... have no way ..."
</details>
This will be a type from wildfly. All I do is add a comment plus an element. Using sed or something instead of copying a whole modified file will be better. I will try sed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/52)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/docker/conf/sun/jdk/module.xml, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/52#-KX2nCj9sgAszhVagxSh:-KX4BdiqCPaw8F2qZiix:bynxf1y) ([raw file](https://github.com/zanata/zanata-platform/blob/f9e48ad0a420230195fae8016138f3b89fc37d2d/server/docker/conf/sun/jdk/module.xml#L24)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> It's a JBoss module so follow JBoss/Wildfly convention. e.g ```${JBOSS_HOME}/modules/system/layers/base/``` then ```sun/jdk``` (as the module name is sun.jdk) I have a comment in the Dockerfile to explain why we need to have this file and what needs to change. It's meant for a temporary workaround until an issue in Javamelody is fixed.
</details>
I still think there should be a comment in this file here as well that says this information about where it was copied from.

---

*[server/docker/conf/sun/jdk/module.xml, line 26 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/52#-KX2mxwTGtVYL2wS5Oqs:-KX4BsEu1pkJio3giW4v:bxi8aul) ([raw file](https://github.com/zanata/zanata-platform/blob/f9e48ad0a420230195fae8016138f3b89fc37d2d/server/docker/conf/sun/jdk/module.xml#L26)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> This will be a type from wildfly. All I do is add a comment plus an element. Using sed or something instead of copying a whole modified file will be better. I will try sed.
</details>
That's fine, I don't think we should fix wildfly's typos, better if we only have the minimal changes we need.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/52)*

**Comment by davidmason** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/docker/conf/sun/jdk/module.xml, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/52#-KX2nCj9sgAszhVagxSh:-KX4CqBVRu7OnTw0nc4r:b-29pl6w) ([raw file](https://github.com/zanata/zanata-platform/blob/f9e48ad0a420230195fae8016138f3b89fc37d2d/server/docker/conf/sun/jdk/module.xml#L24)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> I still think there should be a comment in this file here as well that says this information about where it was copied from.
</details>
But it is moot if there is no checked-in copy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/52)*

**Comment by huangp** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/docker/conf/sun/jdk/module.xml, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/52#-KX2nCj9sgAszhVagxSh:-KX4Ck-UEBLyU8iO3IzD:b6pe8ht) ([raw file](https://github.com/zanata/zanata-platform/blob/f9e48ad0a420230195fae8016138f3b89fc37d2d/server/docker/conf/sun/jdk/module.xml#L24)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> I still think there should be a comment in this file here as well that says this information about where it was copied from.
</details>
Changed to use sed so this file is not needed.

---

*[server/docker/conf/sun/jdk/module.xml, line 26 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/52#-KX2mxwTGtVYL2wS5Oqs:-KX4CpPHSIny2Wcykv3P:bl78and) ([raw file](https://github.com/zanata/zanata-platform/blob/f9e48ad0a420230195fae8016138f3b89fc37d2d/server/docker/conf/sun/jdk/module.xml#L26)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> That's fine, I don't think we should fix wildfly's typos, better if we only have the minimal changes we need.
</details>
Changed to use sed to modify the file in place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/52)*

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/52#-:-KX4GxEp1-qO0hz7N2AE:bnfp4nl)*

**Comment by djansen-redhat** [comment]
:white_check_mark: This looks fine

**Pull request merged**
