### PR TITLE
fix(ZNTA-1934): set height for glossary search input in editor 

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1934

The height of the icon section and input section of the glossary search input in the editor is not the same height - looks fine in storybook but not in the alpha editor. A specific height must be set for this input so that it looks consistent.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/292)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/292#-:-KinQaeXWqruF-ljZFTF:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo  Getting conflicts while merging with latest master branch

**Comment by kathryngo** [comment]
Fixed merge conflicts. They were from the updated storybook branch that recently got merged.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/292#-:-Kj773arumrH_qXTKO40:btozz0)*

**Comment by spathare21** [comment]
@kathryngo verified but not seeing any difference in height of search icon on GUI.

**Comment by kathryngo** [comment]
@spathare there should be no change to the icon.
 the bottom border should now be even for the.icon and text input. There is an image of the bug in the jira issue.

**Comment by spathare21** [comment]
ok thanks @kathryngo then it looks good .

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/292#-:-KjAhvazZbKzHhaTUmzg:bnfp4nl)*

**Pull request merged**
