### PR TITLE
feat(ZNTA-2171) editing ActivityFeedItem component for reject translation feature

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2171

Add rejection history (with comment and criteria/priority) to editor storybook (ActivityFeedItem - rejected)

rejection

## To Do

- minor coding reformats (change priority to constants, ordering of statements etc)

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/495)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/495#-:-KtE4yfxnfDPB34tDkCI:bnfp4nl)*

**Comment by kathryngo** [comment]
@aeng merged in master, now there is a heap of files for you to check. I must have done something wrong here.

**Comment by aeng** [comment]
@kathryngo You got commits from ZNTA-2093 which is not merged yet. You might have merged in the wrong branch into this.

**Comment by kathryngo** [comment]
yeah looks like it. I am trying to revert this stuff now.

**Comment by kathryngo** [comment]
ok @aeng I have fixed things after much fiddling around. tests aren't working tho :/

**Comment by kathryngo** [comment]
@aeng can I get a second NOQA vote on this?

**Comment by aeng** [comment]
@kathryngo Assuming ActivityFeedItem is not used yet, then you're good to go :)

**Pull request merged**
