### PR TITLE
feat: add select all option in tm merge

### PR DESCRIPTION
**Pull request by aeng**
Insert a "select all" checkbox in tm merge modal to select all listed project/versions

https://zanata.atlassian.net/browse/ZNTA-2758

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by djansen-redhat** [comment]
- [ ] Select all shouldn't include the version being merged into.
- [ ] Inconsistent state when "this project (source) set, select all clicked, other projects (source) clicked, project searched and displayed, select all clicked again"

**Comment by aeng** [comment]
@djansen-redhat @spathare21 fixed the issues.

**Comment by aeng** [comment]
@djansen-redhat @spathare21 ready for QA now.

**Comment by djansen-redhat** [comment]
Verified. Requires final review approval.

**Pull request merged**
