### PR TITLE
fix: add limit to glossary fields

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-2340

JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/716)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
Storybook snapshot has a failure in:
Frontend Storyshots › EditableText › editing
Frontend Storyshots › TextInput › default
Frontend Storyshots › RejectionsForm › read only
Frontend Storyshots › RejectionsForm › editable
Frontend Storyshots › RejectionsForm › Admin screen
Frontend Storyshots › EditableText › editing

**Comment by djansen-redhat** [comment]
Reviewed 7 of 13 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/716)*

**Comment by djansen-redhat** [comment]
Still some failing snapshot tests.

**Comment by aeng** [comment]
@djansen-redhat updated.

**Comment by djansen-redhat** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/716)*

**Comment by spathare21** [comment]
@aeng I am creating glossary term with long character it shows term created but not searchable/visible in glossary list

Enter long characters in term, Part of speech and description until it accepts

screenshot from 2018-02-26 12-14-52

**Comment by aeng** [comment]
@spathare21 updated.

**Comment by spathare21** [comment]
@aeng  Thanks but the term is going out of text 

screenshot from 2018-02-27 18-26-13
screenshot from 2018-02-27 18-26-02
screenshot from 2018-02-27 18-26-20

**Comment by aeng** [comment]
@kathryngo Mind to have a quick look and see if its possible to sort it out using CSS?

**Comment by kathryngo** [comment]
@aeng shall give it a go

**Comment by kathryngo** [comment]
@aeng, sorry it cannot be done with css. max length of text inputs can only be set in html/js

**Comment by aeng** [comment]
@spathare21 Given that the UX is an existing, can we make it a separate PR for the UI?

**Comment by spathare21** [comment]
@aeng yes sure np :) marking it verify now.

**Comment by kathryngo** [comment]
@aeng, @spathare21 attempting to fix UI issue now

**Pull request merged**
