### PR TITLE
chore: move frontend directory a level up

### PR DESCRIPTION
**Pull request by aeng**
JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/573)

### CODE REVIEW

**Comment by aeng** [comment]
@davidmason Agreed. Will find the best time to merge this in without making too much impact on existing PR.

**Comment by huangp** [comment]
I am fine with the change. Check with @kathryngo to see if she has any pending PR potentially may be impacted by this.

**Comment by aeng** [comment]
@kathryngo any concern over this? If you got pending PR on frontend, you will need to rebase or merge this change into your branch.

**Comment by kathryngo** [comment]
@aeng @huangp Yes I do have work I have been doing on all the css files (getting ready to merge frontend and editor into one css file) but I can merge in your changes. Worst case, it won't take me too long to redo my work - so go for it.

**Comment by kathryngo** [comment]
I will hold off making further changes to my PR until I have merged in this stuff. 😃

**Comment by aeng** [comment]
Creating new PR based on latest master.

**Pull request closed without merging**
