### PR TITLE
Enable GWT draft mode by default

### PR DESCRIPTION
**Pull request by seanf**
Draft mode saves about 13 seconds in my unscientific tests running `mvn clean package` (with soft permutations - https://github.com/zanata/zanata-platform/pull/73), compared to `mvn clean package -Doptimise`.

Running `mvn clean package -Dgwt.validateOnly` only saves another 3, but `mvn clean package -Dgwt.compiler.skip` saves 39 seconds (compared to draft) - note that this doesn't run the GWT compiler at all, although it still runs the Java compiler.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/76)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/76#-:-KXOlzAPrrbPJx90bZIX:b9a2vem)*

**Comment by huangp** [comment]
-(Awaiting review) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/76#-:-KXOm2boFWP4d4D9a20I:b-o9bygt)*

**Comment by djansen-redhat** [comment]
@definite @huangp is it correct to put this in release?

**Comment by seanf** [comment]
I think I'll retarget to `master`. It should be pretty safe, but it's only 13 seconds.

**Comment by seanf** [comment]
@zanata-jenkins test this please.

**Pull request merged**
