### PR TITLE
Get Zanata dependencies from reactor if possible

### PR DESCRIPTION
**Pull request by seanf**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1463

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/32)

### CODE REVIEW

**Comment by huangp** [comment]
The build failed on dep requires upper bound

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java, line 82 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/32#-KVbPNdALw3g0O2kM-CV:-KVbPNdALw3g0O2kM-CW:bjxarpb) ([raw file](https://github.com/zanata/zanata-platform/blob/ad0a1a1457137a4f9b6a30cd4c99bdd585c8875b/server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java#L82)):*
> ```Java
>                 new ArrayList<>(archive.getContent().keySet());
>         Collections.sort(paths);
>         String contents = "  " + Joiner.on("\n  ").join(paths);
> ```

I used paths.forEach(System.out::println) in my PR. 

---

*[server/zanata-war/src/test/java/org/zanata/arquillian/DeploymentsSanityTest.java, line 53 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/32#-KVbQRun2bQFXu0mMAwb:-KVbQRun2bQFXu0mMAwc:b-j7rs5) ([raw file](https://github.com/zanata/zanata-platform/blob/ad0a1a1457137a4f9b6a30cd4c99bdd585c8875b/server/zanata-war/src/test/java/org/zanata/arquillian/DeploymentsSanityTest.java#L53)):*
> ```Java
>         List<File> depList = Arrays.asList(Deployments.runtimeAndTestDependenciesFromPom());
>         System.out.println("dependency count: " + depList.size());
>         System.out.println("zanata dependencies: ");
> ```

we should use log instead of system out.

---

*[server/zanata-war/src/test/java/org/zanata/arquillian/DeploymentsSanityTest.java, line 54 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/32#-KVbQk7rvDhzKhnchhVF:-KVbQk7rvDhzKhnchhVG:b-5sk860) ([raw file](https://github.com/zanata/zanata-platform/blob/ad0a1a1457137a4f9b6a30cd4c99bdd585c8875b/server/zanata-war/src/test/java/org/zanata/arquillian/DeploymentsSanityTest.java#L54)):*
> ```Java
>         System.out.println("dependency count: " + depList.size());
>         System.out.println("zanata dependencies: ");
>         depList.stream().filter(f -> f.getPath().contains("zanata")).forEach(System.out::println);
> ```

Using log instead (as debug)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/32#-:-KVbP9i6MjqjzrazXQC-:bif4a77)*

**Comment by seanf** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java, line 82 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/32#-KVbPNdALw3g0O2kM-CV:-KVc8Gq0JBIOMlXpZ55O:bmrwbo2) ([raw file](https://github.com/zanata/zanata-platform/blob/ad0a1a1457137a4f9b6a30cd4c99bdd585c8875b/server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java#L82)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> I used paths.forEach(System.out::println) in my PR. 
</details>
This is just moved from another method to help with problem solving; I didn't rewrite it for this PR. 

Besides, I like the indentation. And the sorting.

---

*[server/zanata-war/src/test/java/org/zanata/arquillian/DeploymentsSanityTest.java, line 54 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/32#-KVbQk7rvDhzKhnchhVF:-KVc8dvQ87zmV_EEa96M:b-bmuy7q) ([raw file](https://github.com/zanata/zanata-platform/blob/ad0a1a1457137a4f9b6a30cd4c99bdd585c8875b/server/zanata-war/src/test/java/org/zanata/arquillian/DeploymentsSanityTest.java#L54)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Using log instead (as debug)?
</details>
I would actually like to print all this info to the console on every build, since knowing what's being tested is important. 

Unfortunately, it's incredibly difficult to get surefire to send stdout anywhere unless the test fails. There's an option which is supposed to write stdout to a .txt file even if the test passes, but I can't get it to work.

So it's not really going to mess up your console.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/32)*

**Comment by seanf** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/test/java/org/zanata/arquillian/DeploymentsSanityTest.java, line 54 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/32#-KVbQk7rvDhzKhnchhVF:-KVcaPdKaf8ZoaUKn9VE:b-k9y58x) ([raw file](https://github.com/zanata/zanata-platform/blob/ad0a1a1457137a4f9b6a30cd4c99bdd585c8875b/server/zanata-war/src/test/java/org/zanata/arquillian/DeploymentsSanityTest.java#L54)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I would actually like to print all this info to the console on every build, since knowing what's being tested is important. 
> 
> Unfortunately, it's incredibly difficult to get surefire to send stdout anywhere unless the test fails. There's an option which is supposed to write stdout to a .txt file even if the test passes, but I can't get it to work.
> 
> So it's not really going to mess up your console.
</details>
I think part of the problem is that, for tests with failed assumptions, surefire doesn't save stdout *anywhere*.

Also, we have log4j set up only to log ERROR and above in our tests (probably due to excessive INFO/WARN logging in many zanata classes). Which means that most logging goes nowhere when running tests, unless you use stdout, stderr or log.error. 

I don't want to hide too much logging, because if this test ever breaks on Jenkins, debugging the problem will be horrendous without sufficient logging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/32)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 6 of 8 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/32#-:-KVcfivAgwKvqhQ_hLCF:b49ms4)*

**Comment by djansen-redhat** [comment]
:white_check_mark: tested by J-man

**Comment by seanf** [comment]
Squash-merged as part of https://github.com/zanata/zanata-platform/pull/9 in commit https://github.com/zanata/zanata-platform/commit/f733d6c8641dc39bf74a4480e55bfe2e28380a15.

**Pull request closed without merging**
