### PR TITLE
test: check session size/serializability

### PR DESCRIPTION
**Pull request by seanf**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/514)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/514#-:-KtTfg7bBzQe2zbzQe7A:b9a2vem)*

**Comment by djansen-redhat** [comment]
@seanf can you please clarify what this does?

**Comment by seanf** [comment]
@djansen-redhat @spathare21 It's a testing thing.

The idea is just to add some logging about HTTP sessions in the categories `org.zanata.test.SessionTracker` and `org.zanata.test.SessionChecker`, so that we can find excessive session data (which may use too much memory) or non-serialisable session data (which will prevent us from clustering Zanata with shared sessions).

If you search for those category names in the log after running functional tests (or in the Jenkins build log), you should see some new log messages.

Later on, we'll probably want tests to fail if we find huge or non-serialisable session data, but for now it's just logging.

**Comment by seanf** [comment]
@spathare21 have you had a chance to look at this again?

**Comment by spathare21** [comment]
@seanf , did't clear about which type logs/mesg your talking. and not clean exactly what to test

**Comment by seanf** [comment]
@spathare21 you can search for SessionChecker or SessionTracker within the build log to see the new log messages. There's not a whole lot to the feature.

**Pull request merged**
