### PR TITLE
fix: zanata-cli basic options positioning

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1117

JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/649)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/649#-:-L2N2ZAgtc2eRltlsyfI:b49ms4)*

**Comment by huangp** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/649)*

**Comment by spathare21** [comment]
@aeng I still not seeing any changes in the order or arguments before push/pull/put

`./zanata-cli --version
zanata-cli
Client version: 4.4.0-SNAPSHOT
Client timestamp: 20180109-0721
Client SCM describe: git-platform-4.3.3-431-g6797f0d
API version: 4.4.0-SNAPSHOT
API timestamp: 20180109-0721
API SCM describe: git-platform-4.3.3-431-g6797f0d
[spathare@dhcp201-105 bin]$ ./zanata-cli --help
Usage: zanata-cli [[help | init | list-remote | pull | push | put-project | put-user | put-version | stats | glossary-delete | glossary-push | glossary-pull]] [--batch-mode (-B)] [--debug (-X)] [--errors (-e)] [--help (-h)] [--quiet (-q)] [--version (-v)]

`

**Comment by aeng** [comment]
The change is to allow those options can be place anywhere in the command. Previously those options is only valid when place before push, pull

**Comment by spathare21** [comment]
ohh sorry i thought its sequence also changed on help displayed

**Pull request merged**
