### PR TITLE
Use CurrentUser to get authenticated HAccount

### PR DESCRIPTION
**Pull request by seanf**
I'm hoping this will help to get around the non-serialisable ValidatorImpl problem, which I suspect is caused by injecting Dependent-scoped `@Authenticated HAccount` into SessionScoped beans.

If this approach helps, we may need to use CurrentUser everywhere, but for now I've just converted some of the code to use CurrentUser instead of `@Authenticated HAccount`.

### CODE REVIEW

**Comment by oytuntez** [comment]
I am trying this PR now.

**Comment by seanf** [comment]
> I am trying this PR now.

Thanks @oytuntez, please let me know how it goes.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/693#-:-L5BlFc_lR1MyX_hqkgY:bnfp4nl)*

**Comment by seanf** [comment]
@aeng The patch coverage is a bit low, but the overall coverage is the same or higher than before. Ignore codecov?

**Comment by seanf** [comment]
@djansen-redhat Ready for QA, thanks.

**Comment by djansen-redhat** [comment]
@seanf Assuming pass of functional tests this seems ok to me

**Comment by seanf** [comment]
Actually, I think I need to check on these issues before I go ahead with this: https://rmannibucau.wordpress.com/2015/03/02/cdi-and-instance-3-pitfalls-you-need-to-know/

Specifically caching and ensuring the dependent HAccount is destroyed when the CurrentUser is.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/693#-:-L5RAHsS1YFBaJRSBnfr:bnfp4nl)*

**Comment by seanf** [comment]
Full functional tests passed.

**Comment by seanf** [comment]
@oytuntez I've made some changes to `CurrentUserImpl` - it's now `RequestScoped` instead of `SessionScoped`, and it no longer needs `javax.enterprise.inject.Instance` - I suspect it would have leaked memory allocating lots of `HAccount` objects before (hanging around until the user session expired).

Have you tried my changes in your cluster setup? Even without migrating all the other uses of `@Authenticated HAccount`, I would expect it to help with the `ValidatorImpl` serialisation problem you saw, at least to some extent. **If** my intuition was correct.

**Comment by seanf** [comment]
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/693)

**Comment by seanf** [comment]
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/693)

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/693#-:-L6EUrpu2EyNYzIbuVwz:bnfp4nl)*

**Pull request merged**
