### PR TITLE
refactor(ZNTA-2465): ant-design static buttons

### PR DESCRIPTION
**Pull request by kathryngo**
### Description
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2465

Test the feasibility of using TypeStyles with ant-design by replacing all static buttons in frontend. These are pure buttons, not using overlay triggers for tooltips or anything.

https://github.com/ant-design/ant-design
Ant-design looks the most promising as an alternative:

* Written in TypeScript
* Uses LESS
* V3 - https://ant.design/changelog#3.0.0
* Comprehensive list of components: https://ant.design
* webpack compatible - https://medium.com/@GeoffMiller/how-to-customize-ant-design-with-react-webpack-the-missing-guide-c6430f2db10f

### Tasks
- add antd to build ✅ 
- add new language button converted to antd from react-bootstrap ✅ 
- get icons working ✅ 
- get variables file working ✅
- add search icon to language page since antd icons are now imported ✅
- replace all static buttons in frontend ✅

Replace in:
…server/zanata-frontend/src/app/containers/Admin/Review.js ✅
…server/zanata-frontend/src/app/containers/Explore/index.js ✅
…server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx ✅
…server/zanata-frontend/src/app/containers/Glossary/index.js ✅
…server/zanata-frontend/src/app/containers/Languages/index.js ✅
…server/zanata-frontend/src/app/containers/UserProfile/CalendarMonthMatrix.jsx ✅
…server/zanata-frontend/src/app/containers/UserProfile/RecentContributions.jsx ✅
…server/zanata-frontend/src/app/components/DraggableVersionPanels/DraggableVersionPanels.test.js ✅
…server/zanata-frontend/src/app/components/DraggableVersionPanels/index.tsx ✅
…server/zanata-frontend/src/app/components/Notification/component.js ✅

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by kathryngo** [comment]
icon visibility issue related to: https://github.com/ant-design/ant-design/issues/6368

**Comment by kathryngo** [comment]
Requires upgrade to react 16

`
[ERROR] warning " > antd@3.4.0" has incorrect peer dependency "react@>=16.0.0".
[ERROR] warning " > antd@3.4.0" has incorrect peer dependency "react-dom@>=16.0.0".
[ERROR] warning "antd > rc-editor-mention@1.1.6" has unmet peer dependency "immutable@^3.7.4".
`

**Comment by kathryngo** [comment]
glossissues
for my reference

**Comment by efloden** [comment]
Reviewed 2 of 9 files at r1, 2 of 7 files at r2, 8 of 11 files at r3, 10 of 11 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/zanata-frontend/src/.yarnrc, line 10 at r4](https://beta.reviewable.io/reviews/zanata/zanata-platform/773#-LAG9SQ0DJratMCvFJfk:-LAG9SQ0DJratMCvFJfl:b-5z0v0o) ([raw file](https://github.com/zanata/zanata-platform/blob/8a839555570064a4ab8f7356a242e1fffb5a1d5e/server/zanata-frontend/src/.yarnrc#L10)):*
> ```
> # See https://github.com/yarnpkg/yarn/issues/4379#issuecomment-331971345 and
> # https://github.com/yarnpkg/yarn/issues/4379#issuecomment-334948680
> --install.frozen-lockfile true
> ```

Did you need to disable this to install the new libraries with 'yarn add [package]'? We can try to reset the changes to package.json and yarn.lock and add them through yarn again if there was a problem with the installation

---

*[server/zanata-frontend/src/webpack.config.js, line 49 at r4](https://beta.reviewable.io/reviews/zanata/zanata-platform/773#-LAGBNGJ3DnUwY6xAcrD:-LAGBNGJ3DnUwY6xAcrE:b-ld4utl) ([raw file](https://github.com/zanata/zanata-platform/blob/8a839555570064a4ab8f7356a242e1fffb5a1d5e/server/zanata-frontend/src/webpack.config.js#L49)):*
> ```JavaScript
>       }),
> 
>       autoprefixer({
> ```

Is auto-prefixing no longer required for supporting these browsers now?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/773)*

**Comment by kathryngo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/.yarnrc, line 10 at r4](https://beta.reviewable.io/reviews/zanata/zanata-platform/773#-LAG9SQ0DJratMCvFJfk:-LAGenwo379K7NQCdjqv:bvmvv6j) ([raw file](https://github.com/zanata/zanata-platform/blob/8a839555570064a4ab8f7356a242e1fffb5a1d5e/server/zanata-frontend/src/.yarnrc#L10)):*
<details><summary><i>Previously, kathryngo (Kathryn Gough) wrote…</i></summary><blockquote>

Have added it back. I did need to remove it to add the new 'antd' package. Everything looks fine now.
</blockquote></details>

I will ping you when I have the build fixed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/773)*

**Comment by efloden** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/773#-:-LAGkquJ7_oz0Vro4Kkp:bnfp4nl)*

**Comment by djansen-redhat** [comment]
Potentially broken by this change are the icons on the admin page buttons.

screenshot from 2018-04-18 13-30-40

**Comment by kathryngo** [comment]
cheers @djansen-redhat for picking that up, will look at that soon.

**Comment by djansen-redhat** [comment]
Looks good to me, should be a great change from what we have. Ok to merge when Jenkins gets its act together.

**Comment by efloden** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/773)*

**Pull request merged**
