### PR TITLE
refactor(test): Code coverage and test quality improvements

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: none

Various improvements to coverage and test code 

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/205)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
Say what?

ConstraintDeclarationException: HV000151: A method overriding another method must not alter the parameter constraint configuration, but method public org.zanata.rest.dto.resource.TranslationsResource org.zanata.adapter.OkapiFilterAdapter.parseTranslationFile(java.net.URI,org.zanata.common.LocaleId,java.lang.String,com.google.common.base.Optional) throws org.zanata.exception.FileFormatAdapterException,java.lang.IllegalArgumentException changes the configuration of public abstract org.zanata.rest.dto.resource.TranslationsResource org.zanata.adapter.FileFormatAdapter.parseTranslationFile(java.net.URI,org.zanata.common.LocaleId,java.lang.String,com.google.common.base.Optional) throws org.zanata.exception.FileFormatAdapterException,java.lang.IllegalArgumentException.

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
Reviewed 19 of 21 files at r1, 1 of 1 files at r2, 3 of 4 files at r3.
Review status: 22 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java, line 47 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KjAiWrO3b-ZhbsI6Vrd:-KjAiWrO3b-ZhbsI6Vre:b-y3qtxx) ([raw file](https://github.com/zanata/zanata-platform/blob/0e405869084eb0c947e51c46161c4bb0744ab994/server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java#L47)):*
> ```Java
> import javax.annotation.Nonnull;
> import java.net.URI;
> import java.util.*;
> ```

I think the our code styleguide prevent wildcard import?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/205)*

**Comment by seanf** [comment]
Reviewed 18 of 21 files at r1, 1 of 1 files at r2, 2 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/adapter/FileFormatAdapter.java, line 35 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMfph1d754yUVabfQl:-KlMfph1d754yUVabfQm:b-a9efdq) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/main/java/org/zanata/adapter/FileFormatAdapter.java#L35)):*
> ```Java
> import org.apache.commons.io.FilenameUtils;
> import org.apache.commons.lang.StringUtils;
> import org.hibernate.validator.constraints.NotEmpty;
> ```

I don't think the Hibernate Validator is active in these classes, so using this annotation might leave a false impression. The other annotations (like Nonnull) are more about compile-time checks (if we set them up*), Validator is more of a runtime thing.

* Or if we convert this class or its callers to Kotlin, which uses these annotations for null analysis.

---

*[server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java, line 97 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMgFPCwhgf9zyh3oiF:-KlMg3O8mjfpRVB7_cG4:b-i54s10) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java#L97)):*
> ```Java
>                     IllegalArgumentException {
>         Objects.requireNonNull(documentContent, "DocumentContent cannot be null");
>         Objects.requireNonNull(sourceLocale, "SourceLocale cannot be null");
> ```

This just seems like extra code to maintain, given the Nonnull annotation. We'd be better off setting up the checker framework for null analysis at compile time (or converting to Kotlin, with its null analysis and generated runtime checks like these).

(Applies to multiple files.)

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java, line 184 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMgcs4Y3jndc9nPcNz:-KlMgcs4Y3jndc9nPcO-:b-8l2rxf) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java#L184)):*
> ```Java
>             transRes = adapter.parseTranslationFile(tempFile.toURI(),
>                     doc.getSourceLocaleId(), localeId, getAdapterParams(doc));
>         } catch (FileFormatAdapterException | IllegalArgumentException e) {
> ```

Catching IllegalArgumentException is kind of a dangerous path (like catching NullPointerException), because it implies that you're trying to work around buggy code. At least you're rethrowing it, but why wrap it in another exception at all?

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java, line 252 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMgynOgBxpvNi52h7n:-KlMgynOgBxpvNi52h7o:b-afto2) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java#L252)):*
> ```Java
>             doc = adapter.parseDocumentFile(documentFile, new LocaleId("en"),
>                     params);
>         } catch (FileFormatAdapterException | IllegalArgumentException e) {
> ```

Again, catching IllegalArgumentException may not be a good idea.

---

*[server/zanata-war/src/test/java/org/zanata/adapter/AbstractAdapterTest.java, line 26 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMi4BHMvuI9gjJU92i:-KlMi4BHMvuI9gjJU92j:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/test/java/org/zanata/adapter/AbstractAdapterTest.java#L26)):*
> ```Java
>  * @author Damian Jansen <a href="mailto:djansen@redhat.com">djansen@redhat.com</a>
>  */
> abstract class AbstractAdapterTest {
> ```

:+1: 

---

*[server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java, line 156 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMhjuUIESEkqqeecty:-KlMhjuUIESEkqqeectz:bsqouqw) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java#L156)):*
> ```Java
>                 new LocaleId("dv-LL"));
>         TranslationsResource translationsResource =
>                 ((TSAdapter) adapter).parseTranslationFile(rawDocument,
> ```

You could avoid the repeated cast by adding a method getAdapter in the parent class, and making the return type more specific in this class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/205)*

**Comment by djansen-redhat** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[server/zanata-war/src/main/java/org/zanata/adapter/FileFormatAdapter.java, line 35 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMfph1d754yUVabfQl:-KlvWAMxzc4AR588POX3:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/main/java/org/zanata/adapter/FileFormatAdapter.java#L35)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I don't think the Hibernate Validator is active in these classes, so using this annotation might leave a false impression. The other annotations (like Nonnull) are more about compile-time checks (if we set them up*), Validator is more of a runtime thing.

* Or if we convert this class or its callers to Kotlin, which uses these annotations for null analysis.
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java, line 47 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KjAiWrO3b-ZhbsI6Vrd:-KlvWPPgvlkyw_uzQZRi:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/0e405869084eb0c947e51c46161c4bb0744ab994/server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java#L47)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think the our code styleguide prevent wildcard import?
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java, line 97 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMgFPCwhgf9zyh3oiF:-KlvWPtLYoMKZ83wGKCm:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java#L97)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

This just seems like extra code to maintain, given the Nonnull annotation. We'd be better off setting up the checker framework for null analysis at compile time (or converting to Kotlin, with its null analysis and generated runtime checks like these).

(Applies to multiple files.)
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java, line 184 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMgcs4Y3jndc9nPcNz:-KlvZLMS8juPJGQOsVBx:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java#L184)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Catching IllegalArgumentException is kind of a dangerous path (like catching NullPointerException), because it implies that you're trying to work around buggy code. At least you're rethrowing it, but why wrap it in another exception at all?
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java, line 252 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMgynOgBxpvNi52h7n:-KlvZKwmRzwxPEy8kNdQ:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java#L252)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Again, catching IllegalArgumentException may not be a good idea.
</blockquote></details>

Done.

---

*[server/zanata-war/src/test/java/org/zanata/adapter/AbstractAdapterTest.java, line 26 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMi4BHMvuI9gjJU92i:-KlvZRp8wGmRKa0pyyF6:bmi8ppe) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/test/java/org/zanata/adapter/AbstractAdapterTest.java#L26)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

:100: 

---

*[server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java, line 156 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMhjuUIESEkqqeecty:-KlvZJFvRaOjoy5rbMLR:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java#L156)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

You could avoid the repeated cast by adding a method getAdapter in the parent class, and making the return type more specific in this class.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/205)*

**Comment by seanf** [comment]
Reviewed 5 of 7 files at r6.
Review status: 20 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java, line 156 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMhjuUIESEkqqeecty:-KlwI74MmMhHjZay_qeq:b-d2ftqg) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java#L156)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I originally had in mind was something like this (putting the cast in one place):

```java
    class AbstractAdapterTest {
        private FileFormatAdapter adapter;
        protected FileFormatAdapter getAdapter() { return adapter; }
    }

    public class TSAdapter extends AbstractAdapterTest {
        protected TSAdapter getAdapter() { return (TSAdapter) super.getAdapter(); }
    }
```

although using generics would be a much better idea (no casts at all, less code):

```java
    class AbstractAdapterTest<T extends FileFormatAdapter> {
        T adapter;
        protected T getAdapter() { return adapter; }
    }

    public class TSAdapterTest extends AbstractAdapterTest<TSAdapter> {
        ...
    }
```

Ideally the field adapter would be private, with protected getter/setter used by the subclasses, but as long as it's package-private access, I'm not too concerned in the case of test code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/205)*

**Comment by seanf** [comment]
Reviewed 2 of 7 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/205)*

**Comment by djansen-redhat** [comment]
Review status: 20 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java, line 156 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KlMhjuUIESEkqqeecty:-Km4Mfpe3ermMvb8LrDG:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/7b38e3149e09bf4f017e33e715f8fcc8780593ea/server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java#L156)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

What I originally had in mind was something like this (putting the cast in one place):

```java
    class AbstractAdapterTest {
        private FileFormatAdapter adapter;
        protected FileFormatAdapter getAdapter() { return adapter; }
    }

    public class TSAdapter extends AbstractAdapterTest {
        protected TSAdapter getAdapter() { return (TSAdapter) super.getAdapter(); }
    }
```

although using generics would be a much better idea (no casts at all, less code):

```java
    class AbstractAdapterTest<T extends FileFormatAdapter> {
        T adapter;
        protected T getAdapter() { return adapter; }
    }

    public class TSAdapterTest extends AbstractAdapterTest<TSAdapter> {
        ...
    }
```

Ideally the field adapter would be private, with protected getter/setter used by the subclasses, but as long as it's package-private access, I'm not too concerned in the case of test code.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/205)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java, line 47 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-KjAiWrO3b-ZhbsI6Vrd:-Km4NW3GrdNyTxR6ymzL:b-77natf) ([raw file](https://github.com/zanata/zanata-platform/blob/0e405869084eb0c947e51c46161c4bb0744ab994/server/zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java#L47)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@aeng, could you please resolve this one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-:-Km4NTc6oezWOqXdWeu-:bnfp4nl)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/205#-:-Km4gmNlkYjR8NaVderi:bnfp4nl)*

**Pull request merged**
