### PR TITLE
chore: remove jboss maven repo

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1570

JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/651)

### CODE REVIEW

**Comment by seanf** [comment]
:+1:

**Comment by aeng** [comment]
QA, best to clear your local maven repository cache to test this PR.

**Comment by spathare21** [comment]
@aeng  I have deleted ./m2/repository but after deleteing it i am getting errors 
after ./build --all

[logs_build.txt](https://github.com/zanata/zanata-platform/files/1614969/logs_build.txt)

**Comment by aeng** [comment]
@spathare21 what command you use for the build? You will need to build all modules, e.g. `./build --all -c -i -U`

**Comment by seanf** [comment]
@spathare21 Try adding -T 1 at the end of your build command to force a non-parallel build. Sometimes Maven's artifact downloading goes silly when building modules in parallel. (Witness the .pom-in-progress reference.)

**Pull request merged**
