### PR TITLE
refactor: change invite only to private in project

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-2176

JIRA issue URL: *paste URL here*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/509)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 12 of 16 files at r1, 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/user-guide/projects/project-settings.md, line 44 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/509#-KuMIEN7DZ7Elymwamg1:-KuMIEN8hl5_GQNMIeQG:byrx0dz) ([raw file](https://github.com/zanata/zanata-platform/blob/d0d256b427e36a49d87e243bbd5f1f9ac226c71c/docs/user-guide/projects/project-settings.md#L44)):*
> ```Markdown
> 
> This setting determines if the project will be visible to all Zanata users or just subset of users.
> When it is activated, the project will only visible to assigned users and only translators in your [project team](/user-guide/projects/project-team/) are allowed to translate your project.
> ```

I can't see any change related to the visibility of the project. Looks like it will still be visible to all users but only assigned people can translate

---

*[server/services/src/main/resources/db/changelogs/db.changelog-4.3.xml, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/509#-KuMGnkIXHx_2htiT5wh:-KuMGnkIXHx_2htiT5wi:b-m7g1ac) ([raw file](https://github.com/zanata/zanata-platform/blob/d0d256b427e36a49d87e243bbd5f1f9ac226c71c/server/services/src/main/resources/db/changelogs/db.changelog-4.3.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8" standalone="no"?>
> ```

This will change 4.3 SHA. Is this change necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/509)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/user-guide/projects/project-settings.md, line 44 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/509#-KuMIEN7DZ7Elymwamg1:-KuMOPjf2HBV7w_dj3vz:ba4fsws) ([raw file](https://github.com/zanata/zanata-platform/blob/d0d256b427e36a49d87e243bbd5f1f9ac226c71c/docs/user-guide/projects/project-settings.md#L44)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

I can't see any change related to the visibility of the project. Looks like it will still be visible to all users but only assigned people can translate
</blockquote></details>

Yup, this is just one of the subtask broken down. This PR is about renaming the field, and will be follow by the security change and TM change.

https://zanata.atlassian.net/browse/ZNTA-2174
https://zanata.atlassian.net/browse/ZNTA-2175

---

*[server/services/src/main/resources/db/changelogs/db.changelog-4.3.xml, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/509#-KuMGnkIXHx_2htiT5wh:-KuMPJOnR1u6Cj41dnmn:bp3aow6) ([raw file](https://github.com/zanata/zanata-platform/blob/d0d256b427e36a49d87e243bbd5f1f9ac226c71c/server/services/src/main/resources/db/changelogs/db.changelog-4.3.xml#L1)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

This will change 4.3 SHA. Is this change necessary?
</blockquote></details>

Reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/509)*

**Comment by huangp** [comment]
-(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/509#-:-KuMfdAtTxdnvhCT9rNQ:b-1amvkm)*

**Comment by spathare21** [comment]
@aeng Verified it shows private in general setting tab. but not sure whats expected if selected private setting. 
What I observe is even though I checked private project it is visibile and searchable to other users who is not added as maintainer or member of project.

**Comment by aeng** [comment]
@spathare21 check the related tasks in the jira. This is just a part of it.

**Pull request merged**
