### PR TITLE
ZNTA-1427 - add option to customize cache location

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: _[https://zanata.atlassian.net/browse/ZNTA-1427]_
- added a new CLI option --cache-dir to customize pull cache file location (.zanata-cache folder)
- added a new maven option -Dzanata.cacheDir to customize pull cache file location
## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.
- Code quality
  - [ ] Code passes style check (checkstyle/eslint)
  - [ ] Code is clear and concise
  - [ ] UI code is internationalised
  - [ ] Code has adequate comments where appropriate
  - Code is in an appropriate place
    - [ ] Classes are in appropriate packages
    - [ ] Code fits with class's responsibilities (SRP)
  - [ ] Configuration files are documented enough
  - If code is removed
    - [ ] No remaining code references the removed code
      - [ ] No orphaned rewrite rules
    - [ ] No orphaned config settings
    - [ ] No remaining comments refer to the removed code
    - [ ] Unused imports and libraries are removed
- Testing
  - [ ] New code has tests
  - [ ] Changed code has tests
  - [ ] All tests pass
  - [ ] Test coverage stable or increased
- Documentation
  - [ ] New features are documented
  - [ ] Docs removed for deleted features
  - [ ] Docs updated for all changed features
  - [ ] Developer/sysadmin docs updated if appropriate
- If there are new dependencies
  - [ ] Does each new dependency pass all the
     [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?
---

_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/5)

### CODE REVIEW

**Comment by aeng** [comment]
Might want to update the docs too for this new option.

---

Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/PullCommand.java, line 14 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/5#-KUogQCIH0XStJcKtRvy:-KUogQCIH0XStJcKtRvz:bfr5hxs) ([raw file](https://github.com/zanata/zanata-platform/blob/43bf191cbdded6246b7e16f77c3c04b8e93664e3/client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/PullCommand.java#L14)):*
> ```Java
> 
> import javax.ws.rs.NotFoundException;
> import javax.ws.rs.client.ResponseProcessingException;
> ```

Not used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/5#-:-KUogj0gQu2NJR6Rv1co:b-oxullw)*

**Comment by huangp** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/PullCommand.java, line 14 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/5#-KUogQCIH0XStJcKtRvy:-KUonhyqzapHiAvl7hkY:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/43bf191cbdded6246b7e16f77c3c04b8e93664e3/client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/PullCommand.java#L14)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Not used?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/5)*

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/5)*

**Comment by aeng** [comment]
@huangp not sure if you see my comment, but should we include this new option on the documentation too?

**Comment by huangp** [comment]
We don't have any documentation mentioning cache or any other advanced options. Not sure we want to change it.

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/5#-:-KUp3SZiu6rdlJuI8awL:bnfp4nl)*

**Comment by huangp** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Pull request merged**
