### PR TITLE
ZNTA-2495: antd tooltips and buttons

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2495

Replace all other react-bootstrap buttons (those that arent static) in frontend (_not editor_)

Some refactors for tooltips and buttons still need to be done to modals - have not done these so they do not conflict with earl's work.

- snapshots are failing

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by kathryngo** [comment]
snapshot failures (for my ref mainly) http://pastebin.test.redhat.com/584310

**Comment by efloden** [comment]
Reviewed 2 of 10 files at r2, 19 of 22 files at r4, 9 of 9 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[server/zanata-frontend/src/app/components/DraggableVersionPanels/DraggableVersionPanels.test.js, line 63 at r5](https://reviewable.io/reviews/zanata/zanata-platform/797#-LBTfHpXDezsHC8iHt15:-LBTfHpYDwufHpAxTg5D:bh3hwvw) ([raw file](https://github.com/zanata/zanata-platform/blob/0cd03031601cc171b040c939bc8f8ba31f238bbf/server/zanata-frontend/src/app/components/DraggableVersionPanels/DraggableVersionPanels.test.js#L63)):*
> ```JavaScript
>     const expected = ReactDOMServer.renderToStaticMarkup(
>       <ListGroup>
>         <div>
> ```

Do we still need the outer div here?

---

*[server/zanata-frontend/src/app/components/DraggableVersionPanels/index.tsx, line 16 at r5](https://reviewable.io/reviews/zanata/zanata-platform/797#-LBTiTQoCJsA_TNkRhQa:-LBTiTQoCJsA_TNkRhQb:bz63zqn) ([raw file](https://github.com/zanata/zanata-platform/blob/0cd03031601cc171b040c939bc8f8ba31f238bbf/server/zanata-frontend/src/app/components/DraggableVersionPanels/index.tsx#L16)):*
> ```XML
>   ListGroupItem,
> } from "react-bootstrap";
> import Button from "antd/lib/button";
> ```

Are we not going to use the antd button styles: import 'antd/lib/button/style/' ?

---

*[server/zanata-frontend/src/app/components/Sidebar/index.jsx, line 80 at r5](https://reviewable.io/reviews/zanata/zanata-platform/797#-LBTgaUD73EGuh7VSvU9:-LBTgaUD73EGuh7VSvUA:b-e7iytd) ([raw file](https://github.com/zanata/zanata-platform/blob/0cd03031601cc171b040c939bc8f8ba31f238bbf/server/zanata-frontend/src/app/components/Sidebar/index.jsx#L80)):*
> ```JSX
>                     <ProgressBar className='progress-striped'
>                       now={12.5} key={4} />
>                     <Button className='btn-danger btn-sm'>Stop</Button>
> ```

This one might need the antd button size='small' prop rather than bootstraps btn-sm now 

---

*[server/zanata-frontend/src/app/containers/UserProfile/ContentStateFilter.jsx, line 24 at r5](https://reviewable.io/reviews/zanata/zanata-platform/797#-LBTi2wmAiK-N0wTa-As:-LBTi2wmAiK-N0wTa-At:br7vig8) ([raw file](https://github.com/zanata/zanata-platform/blob/12ac7dc66543985c195d7ad7d2e88af41c9e4731/server/zanata-frontend/src/app/containers/UserProfile/ContentStateFilter.jsx#L24)):*
> ```JSX
>     /* eslint-disable react/jsx-no-bind */
>     return (
>       <Button bsStyle='default' bsSize='small' key={option}
> ```

Should this button also have the antd size='small' prop?

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/797)*

**Comment by kathryngo** [comment]
Review status: 29 of 33 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/app/components/DraggableVersionPanels/DraggableVersionPanels.test.js, line 63 at r5](https://reviewable.io/reviews/zanata/zanata-platform/797#-LBTfHpXDezsHC8iHt15:-LBYDUxi1NY3ZLp-JjfG:b-cxa0r3) ([raw file](https://github.com/zanata/zanata-platform/blob/0cd03031601cc171b040c939bc8f8ba31f238bbf/server/zanata-frontend/src/app/components/DraggableVersionPanels/DraggableVersionPanels.test.js#L63)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Do we still need the outer div here?
</blockquote></details>

Probably not. Thanks for picking this up.

---

*[server/zanata-frontend/src/app/components/DraggableVersionPanels/index.tsx, line 16 at r5](https://reviewable.io/reviews/zanata/zanata-platform/797#-LBTiTQoCJsA_TNkRhQa:-LBYDXUj-pEXoYNTt5Do:b-ttk7d9) ([raw file](https://github.com/zanata/zanata-platform/blob/0cd03031601cc171b040c939bc8f8ba31f238bbf/server/zanata-frontend/src/app/components/DraggableVersionPanels/index.tsx#L16)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Are we not going to use the antd button styles: import 'antd/lib/button/style/' ?
</blockquote></details>

We don't need it for the styles it seems. The styles are brought in without using this afaik

---

*[server/zanata-frontend/src/app/components/Sidebar/index.jsx, line 80 at r5](https://reviewable.io/reviews/zanata/zanata-platform/797#-LBTgaUD73EGuh7VSvU9:-LBYDcp-7amQbPHeUca0:bsrrrow) ([raw file](https://github.com/zanata/zanata-platform/blob/0cd03031601cc171b040c939bc8f8ba31f238bbf/server/zanata-frontend/src/app/components/Sidebar/index.jsx#L80)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

This one might need the antd button size='small' prop rather than bootstraps btn-sm now 
</blockquote></details>

Gotcha, will fix

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/797)*

**Comment by kathryngo** [comment]
Review status: 29 of 33 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/app/containers/UserProfile/ContentStateFilter.jsx, line 24 at r5](https://reviewable.io/reviews/zanata/zanata-platform/797#-LBTi2wmAiK-N0wTa-As:-LBYDgSnAjNDAtplOwrZ:b-t6sugt) ([raw file](https://github.com/zanata/zanata-platform/blob/12ac7dc66543985c195d7ad7d2e88af41c9e4731/server/zanata-frontend/src/app/containers/UserProfile/ContentStateFilter.jsx#L24)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Should this button also have the antd size='small' prop?
</blockquote></details>

Yep, thanks for picking this up

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/797)*

**Comment by kathryngo** [comment]
Review status: 27 of 33 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/app/containers/UserProfile/ContentStateFilter.jsx, line 24 at r5](https://reviewable.io/reviews/zanata/zanata-platform/797#-LBTi2wmAiK-N0wTa-As:-LBYKl0U1leOZbhK5kHf:bvwz4y7) ([raw file](https://github.com/zanata/zanata-platform/blob/12ac7dc66543985c195d7ad7d2e88af41c9e4731/server/zanata-frontend/src/app/containers/UserProfile/ContentStateFilter.jsx#L24)):*
<details><summary><i>Previously, kathryngo (Kathryn Gough) wrote…</i></summary><blockquote>

Yep, thanks for picking this up
</blockquote></details>

The 'btn-sm' class from bootstrap has been applied here with custom styling just for this page.
At the end of migrating all the containers and components to antd I will go back and cherry pick out any essential css that we still require (like this btn-sm class)

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/797)*

**Comment by kathryngo** [comment]
Review status: 26 of 33 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/app/containers/UserProfile/ContentStateFilter.jsx, line 24 at r5](https://reviewable.io/reviews/zanata/zanata-platform/797#-LBTi2wmAiK-N0wTa-As:-LBYRLZWB_ALoqFbHhqS:b4trod9) ([raw file](https://github.com/zanata/zanata-platform/blob/12ac7dc66543985c195d7ad7d2e88af41c9e4731/server/zanata-frontend/src/app/containers/UserProfile/ContentStateFilter.jsx#L24)):*
<details><summary><i>Previously, kathryngo (Kathryn Gough) wrote…</i></summary><blockquote>

The 'btn-sm' class from bootstrap has been applied here with custom styling just for this page.
At the end of migrating all the containers and components to antd I will go back and cherry pick out any essential css that we still require (like this btn-sm class)
</blockquote></details>

Nope, turns out that styling was from antd button overrides. Have added minor css fixes to ensure the buttons look ok (can see the date and count)

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/797)*

**Comment by efloden** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/797#-:-LBYSqKa20eLhH5LXRN8:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo looks like it changed profile page date css 

screenshot from 2018-05-03 09-02-35

**Comment by kathryngo** [comment]
What do you mean @spathare21
I am aware the buttons have changed. I have restyled them to fit the design of the page.

**Comment by spathare21** [comment]
@kathryngo can you please see the attached screenshot

**Comment by kathryngo** [comment]
I see the screenshot but I don't know what you are talking about. Please be specific about what the problem is.

**Comment by efloden** [comment]
Reviewed 4 of 4 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/797)*

**Pull request merged**
