### PR TITLE
feat(ZNTA-75): Add live validations to React Editor

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-75

The React editor should be able to run any of the standard Validators, based on the settings for the project-version (off/warning/error).

If the Validator is not set as 'error' for the project version, the Validator options can be toggled from off/warning in the editor settings. This selection does not persist and should reset to the project-version settings when refreshing the editor.

List of validators (taken from GWT editor validation options):
- [x] HTML/XML tags
- [x] Java variables
- [x] Leading/trailing newline (\n)
- [x] Positional printf (XSI extension)
- [x] Printf variables
- [x] Tab characters (\t)
- [x] XML entity reference

Integrate Validators with alpha editor Validation component [ZNTA-2519](https://zanata.atlassian.net/browse/ZNTA-2519)
Apply Validators selected as Warning / Error in validation option settings [ZNTA-2425](https://zanata.atlassian.net/browse/ZNTA-2425)
editor_validation

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by seanf** [comment]
Review status: 10 of 35 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/zanata-frontend/src/app/utils/FeatureToggles.ts, line 9 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxk4vW8MlIvdmy_Eki:-LDxk4vW8MlIvdmy_Ekj:bet07lw) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/app/utils/FeatureToggles.ts#L9)):*
> ```XML
>  * Toggles the Validation Options feature in the Settings Panel.
>  */
> export const showValidationOptions = () => true;
> ```

Seems like this shouldn't be needed any more now.

---

*[server/zanata-frontend/src/app/validators/messages/en.json, line 2 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxkI7S-KGcJKRwGYsm:-LDxkI7S-KGcJKRwGYsn:b-jdh3ec) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/app/validators/messages/en.json#L2)):*
> ```JSON
> {
>   "ab": "string",
> ```

test data?

---

*[server/zanata-frontend/src/app/validators/messages/index.ts, line 4 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxlYyC7k0v655EBq11:-LDxlYyC7k0v655EBq12:bqqbugv) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/app/validators/messages/index.ts#L4)):*
> ```XML
> 
> import en from './en.json'
> import ja from './ja.json'
> ```

Perhaps add a readme in this directory, or just a comment at the top here (it is an "index" after all) explaining that these json files are for translations of the validators only (separate from frontend messages in the other json files).

---

*[server/zanata-frontend/src/app/validators/messages/index.ts, line 9 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxkc_LAml_M77IDtpj:-LDxkc_LAml_M77IDtpk:btf3le9) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/app/validators/messages/index.ts#L9)):*
> ```XML
>  * Aliases for message JSON files
>  * Plural support possible:
>  * invalidXMLEntity: "Invalid XML {COUNT, plural, =0 {entity: } =1 {entity: } other {entities: } } {ENTITY}"
> ```

Good to now, but we should probably avoid such plurals in our strings until Zanata has a feature to help translators with them.

---

*[server/zanata-frontend/src/app/validators/messages/index.ts, line 15 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxksZV55v2X-UvEZ8v:-LDxksZV55v2X-UvEZ8w:bo93ydp) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/app/validators/messages/index.ts#L15)):*
> ```XML
>   'en-US': en,
>   'ja': ja,
>   'ja-JP': ja
> ```

Why the doubling up? Presumably Zanata's locale selector doesn't offer all of these different locale codes. 

If we do need them, we should have comments here to explain.

---

*[server/zanata-frontend/src/app/validators/messages/ja.json, line 2 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxlF4C3HCgdc6seHjY:-LDxlF4C3HCgdc6seHjZ:b-jdh3ec) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/app/validators/messages/ja.json#L2)):*
> ```JSON
> {
>   "ab": "文字列",
> ```

test data?

---

*[server/zanata-frontend/src/messages/ja.json, line 29 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxm5817Uk7ZUNT1L-v:-LDxm5817Uk7ZUNT1L-w:b-nf9xyv) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/messages/ja.json#L29)):*
> ```JSON
>   "Validator.PRINTF_XSI_EXTENSION.title": "位置指定Printf（XSI拡張）",
>   "Validator.header.warnings": "警告: {warningCount}",
>   "Validator.header.errors": "エラー: {errorCount}",
> ```

It seems like some or all of these strings will be needed in other places too, not just frontend. Perhaps the individual validators should be able to tell their own localised names (titles).

The same might go for the last two strings here, but the main thing is to minimise the places which have to know about new validators as they are created.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/809)*

**Comment by efloden** [comment]
Review status: 5 of 36 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/app/utils/FeatureToggles.ts, line 9 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxk4vW8MlIvdmy_Eki:-LE714pyCTgRsOxykcRk:bb6un1j) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/app/utils/FeatureToggles.ts#L9)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Seems like this shouldn't be needed any more now.
</blockquote></details>

Done

---

*[server/zanata-frontend/src/app/validators/messages/en.json, line 2 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxkI7S-KGcJKRwGYsm:-LE70kgV7phucVvcMVx-:b-zbyrqh) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/app/validators/messages/en.json#L2)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

test data?
</blockquote></details>

Brought over from the Java Validators, but after writing the tests it doesn't look like we need it

---

*[server/zanata-frontend/src/app/validators/messages/index.ts, line 4 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxlYyC7k0v655EBq11:-LE7EFOB2Qy239uKuvZZ:bxnkmuv) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/app/validators/messages/index.ts#L4)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Perhaps add a readme in this directory, or just a comment at the top here (it is an "index" after all) explaining that these json files are for translations of the validators only (separate from frontend messages in the other json files).
</blockquote></details>

Added documentation in the index file for the validator messages

---

*[server/zanata-frontend/src/app/validators/messages/index.ts, line 15 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxksZV55v2X-UvEZ8v:-LE71V-o0zN-qkAZx6Rq:b-2s1gsl) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/app/validators/messages/index.ts#L15)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Why the doubling up? Presumably Zanata's locale selector doesn't offer all of these different locale codes. 

If we do need them, we should have comments here to explain.
</blockquote></details>

There are some discrepancies between the Zanata locale selection codes and the available react-intl localeData - I think this could be handled by having a locale selector in the editor itself that presents a list of all of the available react-intl locale codes rather than mapping the locale choices like this

---

*[server/zanata-frontend/src/messages/ja.json, line 29 at r2](https://reviewable.io/reviews/zanata/zanata-platform/809#-LDxm5817Uk7ZUNT1L-v:-LE7RSAj-SZGR5wYPZR0:b-ggjsol) ([raw file](https://github.com/zanata/zanata-platform/blob/d9ab982f92b81d4d44da821ac072b50b9e3ca429/server/zanata-frontend/src/messages/ja.json#L29)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

It seems like some or all of these strings will be needed in other places too, not just frontend. Perhaps the individual validators should be able to tell their own localised names (titles).

The same might go for the last two strings here, but the main thing is to minimise the places which have to know about new validators as they are created.
</blockquote></details>

That does seem more sensible for having this as a standalone, I've moved the label translation messages into the validators module so it can provide all the related localized text : labels, descriptions, and error messages

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/809)*

**Comment by seanf** [comment]
Review status: 22 of 36 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/zanata-frontend/src/app/editor/components/Validation/index.tsx, line 24 at r3](https://reviewable.io/reviews/zanata/zanata-platform/809#-LE8e8X098bKMYmmByEq:-LE8e8X098bKMYmmByEr:b-fk00ve) ([raw file](https://github.com/zanata/zanata-platform/blob/56840054fa2f8d789ea401cb3fc6cb92774e222d/server/zanata-frontend/src/app/editor/components/Validation/index.tsx#L24)):*
> ```XML
> 
> // TODO: only instantiate enabled validators (warning/error)
> function validatorFactory(_validationOptions: ValidationOption[], locale: string): any {
> ```

Try to avoid using `any` here. Should be `ValidationAction[]`, I think.

---

*[server/zanata-frontend/src/app/editor/components/Validation/index.tsx, line 32 at r3](https://reviewable.io/reviews/zanata/zanata-platform/809#-LE8c5jd7uXcR0NEeWgL:-LE8ZWEf3Hv4lQijvKeF:b-a4pqne) ([raw file](https://github.com/zanata/zanata-platform/blob/56840054fa2f8d789ea401cb3fc6cb92774e222d/server/zanata-frontend/src/app/editor/components/Validation/index.tsx#L32)):*
> ```XML
>   const validators = []
>   validators.push(
>     new HtmlXmlTagValidation(ValidationId.HTML_XML, Messages[resolvedLocale], resolvedLocale))
> ```

I think the ValidationAction implementations should know their own IDs.  They could probably just implement the `id` property directly, without even passing it up to AbstractValidationAction.

Perhaps you will be able to delete the ValidationId enum too (thus reducing the number of places which know about all the validators).

---

*[server/zanata-frontend/src/app/editor/components/Validation/index.tsx, line 45 at r3](https://reviewable.io/reviews/zanata/zanata-platform/809#-LE8bhDY0GpE-8f4TRT5:-LE8aVOuDlxdSvpLJF_4:bd8ldhw) ([raw file](https://github.com/zanata/zanata-platform/blob/56840054fa2f8d789ea401cb3fc6cb92774e222d/server/zanata-frontend/src/app/editor/components/Validation/index.tsx#L45)):*
> ```XML
>   validators.push(
>     new XmlEntityValidation(ValidationId.XML_ENTITY, Messages[resolvedLocale], resolvedLocale))
>   return validators
> ```


We should let the validators module do this, to keep knowledge of the individual validators localised.

---

*[server/zanata-frontend/src/app/editor/components/Validation/index.tsx, line 156 at r3](https://reviewable.io/reviews/zanata/zanata-platform/809#-LE8ej_28TYjyWq4Sq0R:-LE8ej_28TYjyWq4Sq0S:b-xp8109) ([raw file](https://github.com/zanata/zanata-platform/blob/56840054fa2f8d789ea401cb3fc6cb92774e222d/server/zanata-frontend/src/app/editor/components/Validation/index.tsx#L156)):*
> ```XML
> 
> interface ValidationProps {
>   intl: any,
> ```

Can you avoid this `any`? What sort of thing is `intl` here?

---

*[server/zanata-frontend/src/app/validators/AbstractValidationAction.ts, line 64 at r3](https://reviewable.io/reviews/zanata/zanata-platform/809#-LE8bxdz7myAVKXWGHq6:-LE8bxdz7myAVKXWGHq7:b1x55pr) ([raw file](https://github.com/zanata/zanata-platform/blob/56840054fa2f8d789ea401cb3fc6cb92774e222d/server/zanata-frontend/src/app/validators/AbstractValidationAction.ts#L64)):*
> ```XML
>   }
> 
>   protected abstract doValidate(source: string, target: string): string[]
> ```

You could move this into the ValidationAction interface.

---

*[server/zanata-frontend/src/app/validators/messages/index.ts, line 16 at r3](https://reviewable.io/reviews/zanata/zanata-platform/809#-LE8UM6K1mDhhCFO_sBu:-LE8UM6K1mDhhCFO_sBv:bpx6iws) ([raw file](https://github.com/zanata/zanata-platform/blob/56840054fa2f8d789ea401cb3fc6cb92774e222d/server/zanata-frontend/src/app/validators/messages/index.ts#L16)):*
> ```XML
> const Messages = {
>   'en': en,
>   'en-US': en,
> ```

Can we cast to ValidationMessages here? Will it be checked at compile time?

---

*[server/zanata-frontend/src/app/validators/messages/index.ts, line 18 at r3](https://reviewable.io/reviews/zanata/zanata-platform/809#-LE8US2o-PWKJd9zJyTZ:-LE8US2o-PWKJd9zJyT_:bigdf8o) ([raw file](https://github.com/zanata/zanata-platform/blob/56840054fa2f8d789ea401cb3fc6cb92774e222d/server/zanata-frontend/src/app/validators/messages/index.ts#L18)):*
> ```XML
>   'en-US': en,
>   'ja': ja,
>   'ja-JP': ja
> ```

If we merge the en object here to fill in missing translations (in the appropriate way? Object.merge?), TypeScript should be aware that the merged object also implements ValidationMessages.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/809)*

**Comment by seanf** [comment]
Review status: 22 of 36 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/zanata-frontend/src/app/editor/components/Validation/index.tsx, line 32 at r3](https://reviewable.io/reviews/zanata/zanata-platform/809#-LE8c5jd7uXcR0NEeWgL:-LEChXC04ljhs7YS2XsP:b-ec019s) ([raw file](https://github.com/zanata/zanata-platform/blob/56840054fa2f8d789ea401cb3fc6cb92774e222d/server/zanata-frontend/src/app/editor/components/Validation/index.tsx#L32)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Moved to the Validators package and removed the ValidationId enum, made it possible to have a single default export of the validatorsFactory and use that in the editor now. :)
</blockquote></details>

Excellent!

---

*[server/zanata-frontend/src/app/editor/components/Validation/index.tsx, line 38 at r4](https://reviewable.io/reviews/zanata/zanata-platform/809#-LEChiW53GPJCEaKVdrd:-LEChiW6EzZFVPvUSGH6:b-p2b4oo) ([raw file](https://github.com/zanata/zanata-platform/blob/a3bf78617383186b76acfa22694d7ec065d274b9/server/zanata-frontend/src/app/editor/components/Validation/index.tsx#L38)):*
> ```XML
>   const errorValidators = validationOptions.filter((v) => v.disabled)
> 
>   const validators = validatorFactory(intl.locale)
> ```

Perhaps a better name for the method would be createValidators.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/809)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/app/validators/impl/HtmlXmlTagValidation.ts, line 46 at r6](https://reviewable.io/reviews/zanata/zanata-platform/809#-LED2ogDCySXkHFlC635:-LED2ogDCySXkHFlC636:b-2foe8v) ([raw file](https://github.com/zanata/zanata-platform/blob/742d6690f67062a8a53fd81b3558d7d5b9a75c7f/server/zanata-frontend/src/app/validators/impl/HtmlXmlTagValidation.ts#L46)):*
> ```XML
>   private tagRegex = "<[^>]+>"
> 
>   constructor(messages: ValidationMessages, locale: string) {
> ```

I think it will be just slightly easier to understand if `locale` comes first in all these constructors, since it is passed to the superclass constructor (in the first and only position), then the subclass constructors add the second parameter `messages`.

---

*[server/zanata-frontend/src/app/validators/impl/HtmlXmlTagValidation.ts, line 67 at r6](https://reviewable.io/reviews/zanata/zanata-platform/809#-LED4cqLD44rttjm8U5k:-LED4cqLD44rttjm8U5l:b-1kqhks) ([raw file](https://github.com/zanata/zanata-platform/blob/742d6690f67062a8a53fd81b3558d7d5b9a75c7f/server/zanata-frontend/src/app/validators/impl/HtmlXmlTagValidation.ts#L67)):*
> ```XML
>       errors.push(tagsAdded)
>     }
>     if (errors.length <= 0) {
> ```

I think just checking === 0 will be a bit clearer.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/809)*

**Comment by efloden** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/zanata-frontend/src/app/editor/components/Validation/index.tsx, line 38 at r4](https://reviewable.io/reviews/zanata/zanata-platform/809#-LEChiW53GPJCEaKVdrd:-LED7Olf5NFZeaIDii13:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/a3bf78617383186b76acfa22694d7ec065d274b9/server/zanata-frontend/src/app/editor/components/Validation/index.tsx#L38)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Perhaps a better name for the method would be createValidators.
</blockquote></details>

Done.

---

*[server/zanata-frontend/src/app/validators/impl/HtmlXmlTagValidation.ts, line 46 at r6](https://reviewable.io/reviews/zanata/zanata-platform/809#-LED2ogDCySXkHFlC635:-LED7Rhc7TNrPCpE_Pzf:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/742d6690f67062a8a53fd81b3558d7d5b9a75c7f/server/zanata-frontend/src/app/validators/impl/HtmlXmlTagValidation.ts#L46)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I think it will be just slightly easier to understand if `locale` comes first in all these constructors, since it is passed to the superclass constructor (in the first and only position), then the subclass constructors add the second parameter `messages`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/809)*

**Comment by seanf** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/809#-:-LEILN0fBOZjeLGKjfE5:bnfp4nl)*

**Comment by spathare21** [comment]
@efloden  looks like following validations are not working 

- HTML validation is not working 

screenshot from 2018-06-12 12-42-53

screenshot from 2018-06-12 12-43-31


- Tab character (\t) is not working in the alpha editor

tab validation in gwt editor 
screenshot from 2018-06-12 12-47-49


- Java variables not working 

Not sure about following validations 

- Positional printf (XSI extention)
- Printf variables
- XML entity reference

**Comment by seanf** [comment]
@spathare21 what's wrong with that HTML validation? It appears that the ja translation does include extra HTML tags, which should produce that warning. You will need source text which contains HTML tags if you want more interesting validation messages.

**Comment by spathare21** [comment]
@seanf , in first image we have <html> and <body> tag which is not closed correctly and in second image we have closed both the tags </html> and </body> it shows same erorr for both, does html validation not validating that tags completion ?

**Comment by spathare21** [comment]
ok @efloden  thanks

**Comment by seanf** [comment]
> ok **@efloden** thanks

Um, you're welcome?! - **@seanf** :-)

**Comment by efloden** [comment]
@spathare21 for the Positional printf (XSI extention) and other validators there are "source" and "target" examples in the tests:
https://github.com/zanata/zanata-platform/blob/editor-live-validations/ZNTA-75/server/zanata-frontend/src/app/validators/impl/PrintfXSIExtensionValidation.test.js

**Pull request merged**
