### PR TITLE
feat(ZNTA-38): concurrent editing storybook

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-38

Storybook files created for concurrent editing UI.

Run `make storybook-editor`
Then go to Concurrent editing link
All work in Concurrent.story.js and accompanying css file

**Notification:**
conf-alert

**Transunit elements - username, conflict resolve button:**
transunit

**Modal:**
nflict-modal

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/624)

### CODE REVIEW

**Comment by aeng** [comment]
@kathryngo is https://zanata.atlassian.net/browse/ZNTA-38 the design only or including implementation?

**Comment by kathryngo** [comment]
@aeng design and storybook only, the issue on jira has the tag 'design' applied to it.

**Comment by aeng** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/app.css, line 38 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-dQsRp8p7OoIaOLrO0:-L-dQsRp8p7OoIaOLrO1:bn6bf4s) ([raw file](https://github.com/zanata/zanata-platform/blob/744fb860339bc242bc93a431a89f66979a36b4dd/server/zanata-frontend/src/frontend/app/editor/app.css#L38)):*
> ```CSS
> @import './components/RejectTranslationModal/index.css';
> @import './components/InputGroup/index.css';
> @import './components/ConcurrentEditing/index.css';
> ```

is `ConcurrentEditing` a component? or it is just an extension of an existing component?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by aeng** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/app.css, line 38 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-dQsRp8p7OoIaOLrO0:-L-dRqwUKOHcsjleaqpT:bclg6ci) ([raw file](https://github.com/zanata/zanata-platform/blob/744fb860339bc242bc93a431a89f66979a36b4dd/server/zanata-frontend/src/frontend/app/editor/app.css#L38)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

is `ConcurrentEditing` a component? or it is just an extension of an existing component?
</blockquote></details>

I can see its a new modal, perhaps we should make it clear on the name `ConcurrentEditingModal`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by kathryngo** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/app.css, line 38 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-dQsRp8p7OoIaOLrO0:-L-dRlXqn_AV25UI_O3C:bdqk93x) ([raw file](https://github.com/zanata/zanata-platform/blob/744fb860339bc242bc93a431a89f66979a36b4dd/server/zanata-frontend/src/frontend/app/editor/app.css#L38)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I can see its a new modal, perhaps we should make it clear on the name `ConcurrentEditingModal`
</blockquote></details>

The modal will need to be a new component.
The TransUnit items (username and button) will need to go in TransUnit

 If you look in the folder you will see a story file and a css file for specific css styling related to concurrent editing.

I have not called this ConcurrentEditingModal because it has the notification and the TransUnit elements in the story file also for the backend developer's reference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by aeng** [comment]
Reviewed 1 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ConcurrentEditing/Concurrent.story.js, line 50 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-dSjnrsl8ZNtD74Yl7:-L-dSjnrsl8ZNtD74Yl8:bf1uscz) ([raw file](https://github.com/zanata/zanata-platform/blob/744fb860339bc242bc93a431a89f66979a36b4dd/server/zanata-frontend/src/frontend/app/editor/components/ConcurrentEditing/Concurrent.story.js#L50)):*
> ```JavaScript
>     ))
>     .add('modal', () => (
>         <Modal show={true}
> ```

Not sure about this but shouldn't we create a component `a` and use that component in the storybook?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by kathryngo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ConcurrentEditing/Concurrent.story.js, line 50 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-dSjnrsl8ZNtD74Yl7:-L-dT01UoyPP4yV8myJ6:bihamra) ([raw file](https://github.com/zanata/zanata-platform/blob/744fb860339bc242bc93a431a89f66979a36b4dd/server/zanata-frontend/src/frontend/app/editor/components/ConcurrentEditing/Concurrent.story.js#L50)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Not sure about this but shouldn't we create a component `a` and use that component in the storybook?
</blockquote></details>

Yeah good point. I will create an index.js file and move the modal code in there.
The storybook file will still need to have the TransUnit elements and notification in there so that the developer can refer to them.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by kathryngo** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ConcurrentEditing/Concurrent.story.js, line 50 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-dSjnrsl8ZNtD74Yl7:-L-db6QXXMNnF4xEdKpB:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/744fb860339bc242bc93a431a89f66979a36b4dd/server/zanata-frontend/src/frontend/app/editor/components/ConcurrentEditing/Concurrent.story.js#L50)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Yeah good point. I will create an index.js file and move the modal code in there.
The storybook file will still need to have the TransUnit elements and notification in there so that the developer can refer to them.  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by kathryngo** [comment]
Have noticed unit tests are failing. Shall try to fix this and if I can't will ask Damian for some help

**Comment by aeng** [comment]
Reviewed 5 of 7 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css, line 43 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-dwnRa49fNRf6PBkkE:-L-dwnRa49fNRf6PBkkF:bngisbm) ([raw file](https://github.com/zanata/zanata-platform/blob/13b28029102f05ffff179c90029b7ba17f25e799/server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css#L43)):*
> ```CSS
> /* React bootstrap styling */
> 
> .alert {
> ```

I understand some of the styling needs to be customised for this modal, but shouldn't we reuse`alert`, `alert-XX`, `label`, `label-default` classes ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by aeng** [comment]
Reviewed 1 of 7 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by kathryngo** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css, line 43 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-dwnRa49fNRf6PBkkE:-L-dxR6VK-zWqSUsxjmN:bgkjqi3) ([raw file](https://github.com/zanata/zanata-platform/blob/13b28029102f05ffff179c90029b7ba17f25e799/server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css#L43)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I understand some of the styling needs to be customised for this modal, but shouldn't we reuse`alert`, `alert-XX`, `label`, `label-default` classes ?
</blockquote></details>

Sure. I will move them to root/index.css - where the global editor css is. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css, line 43 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-dwnRa49fNRf6PBkkE:-L-e19vh1EzvaK1rzq1H:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/13b28029102f05ffff179c90029b7ba17f25e799/server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css#L43)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Sure. I will move them to root/index.css - where the global editor css is. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by aeng** [comment]
Reviewed 1 of 7 files at r2, 1 of 2 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css, line 4 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-e2GQH00qqQhqy77NI:-L-e2GQH00qqQhqy77NJ:bajamgs) ([raw file](https://github.com/zanata/zanata-platform/blob/78661660a7ed09f097ac7a5670efb601db1e3b8b/server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css#L4)):*
> ```CSS
>   --ConcEditing-Button-primary-color: #03A6D7;
>   --ConcEditing-color-muted: #BDD4DC;
>   --ConcEditing-color-neutral: #a2b3be;
> ```

Any of these colors is already declared elsewhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by kathryngo** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css, line 4 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-e2GQH00qqQhqy77NI:-L-e2TtKvkB-l1uUxnPf:b4o8nwl) ([raw file](https://github.com/zanata/zanata-platform/blob/78661660a7ed09f097ac7a5670efb601db1e3b8b/server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css#L4)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Any of these colors is already declared elsewhere?
</blockquote></details>

We cannot use variable declarations from external css files here - they have to be declared at the top of the file like this.  This is the standard technique used throughout editor. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by kathryngo** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css, line 4 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-e2GQH00qqQhqy77NI:-L-e3T4-4itGMuk0qGVa:bpqglz7) ([raw file](https://github.com/zanata/zanata-platform/blob/78661660a7ed09f097ac7a5670efb601db1e3b8b/server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css#L4)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

We cannot use variable declarations from external css files here - they have to be declared at the top of the file like this.  This is the standard technique used throughout editor. 
</blockquote></details>

Only less files can use import statements, that's how we have handled this in frontend. Editor uses only css.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by aeng** [comment]
Reviewed 1 of 7 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css, line 4 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-e2GQH00qqQhqy77NI:-L-e4JMqj3ibMmZlCSBl:b-x2dr8) ([raw file](https://github.com/zanata/zanata-platform/blob/78661660a7ed09f097ac7a5670efb601db1e3b8b/server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css#L4)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Only less files can use import statements, that's how we have handled this in frontend. Editor uses only css.
</blockquote></details>

We probably need to convert it to `less` too in editor. But not in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-:-L-e4U-iB_BxTW1q5zOv:bnfp4nl)*

**Comment by kathryngo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css, line 4 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-L-e2GQH00qqQhqy77NI:-L-e4Xwg1lGArqtcE4YY:bz6y07z) ([raw file](https://github.com/zanata/zanata-platform/blob/78661660a7ed09f097ac7a5670efb601db1e3b8b/server/zanata-frontend/src/frontend/app/editor/components/ConcurrentModal/index.css#L4)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

We probably need to convert it to `less` too in editor. But not in this PR.
</blockquote></details>

Agreed. Less is much nicer to work with and more flexible. Shall make a note on Jira.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624)*

**Comment by kathryngo** [comment]
@aeng NO QA vote?

**Comment by aeng** [comment]
@kathryngo please wait for jenkins build passes before merge.

**Comment by kathryngo** [comment]
@aeng of course. watching it now to see if it finally passes :)

**Comment by kathryngo** [comment]
I will need to rebuild it with full functional tests, just want to make sure it passes this initial build first.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/624#-:-L-e6QyecW2Ujb6LuquQ:bb2gsb6)*

**Pull request merged**
