### PR TITLE
fix(ZNTA-2626): hide translation-comment search (can't show/edit)

### PR DESCRIPTION
**Pull request by seanf**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2626

Zanata can't currently show or edit translator comments, so it's just confusing to have a feature which searches for them. It can't even show the matching comment. PR #892 hid this feature in the GWT editor. This PR hides it in the React editor too.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/899#-:-LEr4u4WC0zyMYa87KN_:bnfp4nl)*

**Comment by spathare21** [comment]
looks good, but build shows failure

**Comment by seanf** [comment]
Yes, it looks like the story shot does need to be updated, as we originally thought. I'll have to look into it tomorrow.

**Comment by aeng** [comment]
`yarn test --updateSnapshot` I believe should do the trick

**Comment by seanf** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/899)*

**Pull request merged**
