### PR TITLE
Improve TraceDebugFilter; add debug for FileResourceClientTest

### PR DESCRIPTION
**Pull request by seanf**
## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/844#-:-LDFPhhSCY_KFAl2W70D:b9a2vem)*

**Comment by seanf** [comment]
@spathare21 to test this, you need to use the zanata-cli option `--log-http` with client commands, eg push, pull, stats. You should see the body of the response, if there was a body, logged to the console.

**Comment by seanf** [comment]
Thanks @djansen-redhat Mind reviewing the modified help text in reviewable?

**Comment by djansen-redhat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/844#-:-LDJuH1T1n_BvwWLteGj:bnfp4nl)*

**Pull request merged**
