### PR TITLE
Suggestion match details in React editor (ZNTA-61)

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-61

Adds suggestion match details modal to the React editor.

This is an early review - some changes left but nothing major so it is worth review now. For the moment this is the version with some sample data for easy back-and-forth editing. Ignore that since I will copy over the commit that will use the real data.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/100)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 9 of 15 files at r1.
Review status: 9 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/zanata-frontend/src/editor/app/components/SuggestionDetailsSummary.js, line 45 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHiYMtBg7xVq9Fg61q:-KYHiYMtCdWERgSIPq7W:b1dq7z) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/components/SuggestionDetailsSummary.js#L45)):*
> ```JavaScript
> 
>     const documentPath = topMatch.documentPath
>       ? topMatch.documentPath
> ```

we removed the ending slash?

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/ImportedTMDetailPanel.js, line 63 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHk-uq9opGaiEVjXH4:-KYHk-uqAIaGBVxsK-sl:b-mewldh) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/ImportedTMDetailPanel.js#L63)):*
> ```JavaScript
>               </Row>
>             </li>
>             <Label style={{'backgroundColor': '#20718a'}}>Imported</Label>
> ```

Not sure about using inline style. We should use css class.

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/ImportedTMDetailPanel.js, line 70 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHkXHsDq_lv25chMOP:-KYHkXHs3y9PzRZQ22fY:br9jsvs) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/ImportedTMDetailPanel.js#L70)):*
> ```JavaScript
>             <SuggestionUpdateMessage
>               lastChanged={lastChangedDate}
>               matchType={'imported'}
> ```

I understand this is a constant for this component, can we use const value from suggestion-utils or use the matchType method?

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js, line 118 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHlH7f0fhtkH3mDKw5:-KYHlH7f4dtGEd6PqvAj:b-d8qa6d) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js#L118)):*
> ```JavaScript
>                   or maybe just use a click on any of those detail items */}
>         <Button bsStyle="default"
>           onClick={::this.showModal}>Launch Modal</Button>
> ```

I don't think user will understand what "Launch Modal" is. We need better text for this button.

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js, line 149 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHljLt16TtLyrNh4hv:-KYHljLt6w2Vb5_8nDWr:b-hnraq) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js#L149)):*
> ```JavaScript
> //      detail based on an on/off state and the appropriate id.
> 
> export default SuggestionDetailsModal
> ```

Is this component hooked up to state yet? or just using test data at the moment?

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/LocalProjectDetailPanel.js, line 52 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHm2zk-Tleu7660Slu:-KYHm2zk36k1kTA1dlo2:byntkbm) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/LocalProjectDetailPanel.js#L52)):*
> ```JavaScript
>     const fullDocName = this.fullDocName(documentPath, documentName)
> 
>     // FIXME use standard styles when they are available
> ```

We should use css class for translated and approve backgroundColor. It should be easy enough extract it to a css class.

---

*[server/zanata-frontend/src/editor/app/css/less/style.less, line 6132 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHjKLb0pYadns3IlWC:-KYHjKLb5xYDrO3D7Q3z:b8t2i4p) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/css/less/style.less#L6132)):*
> ```Less
>     border: 1px solid #ddd !important;
>   }
> }
> ```

Need newline at the end.

Is this file same as the one in frontend?

---

*[server/zanata-frontend/src/editor/app/css/less/variables.less, line 891 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHjS_D5zUgfil5TvRh:-KYHjS_D1Qp-4uSRMYZv:blj8dvm) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/css/less/variables.less#L891)):*
> ```Less
> // Note: Deprecated @dropdown-caret-color as of v3.1.0
> @dropdown-caret-color:           #000;
> ```

Is this file same as the one in frontend?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100)*

**Comment by davidmason** [comment]
Review status: 9 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/zanata-frontend/src/editor/app/components/SuggestionDetailsSummary.js, line 45 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHiYMtBg7xVq9Fg61q:-KYHnNHm72NkgcAdM7v5:b-9sb823) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/components/SuggestionDetailsSummary.js#L45)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

we removed the ending slash?
</blockquote></details>

It was doing `path//filename.ext` so it was a bug. Fixed it since it was so easy.

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/ImportedTMDetailPanel.js, line 63 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHk-uq9opGaiEVjXH4:-KYHnZsaDh_t0J1CW19j:b-kqtu28) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/ImportedTMDetailPanel.js#L63)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Not sure about using inline style. We should use css class.
</blockquote></details>

Agreed - that's one of the things kgough is looking at tonight. We can leave this discussion open as a reminder.

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/ImportedTMDetailPanel.js, line 70 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHkXHsDq_lv25chMOP:-KYHnnsUALPkulDItp-Z:b-ligke3) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/ImportedTMDetailPanel.js#L70)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I understand this is a constant for this component, can we use const value from suggestion-utils or use the matchType method?
</blockquote></details>

Constants in the utils class is a good idea, I will do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100)*

**Comment by davidmason** [comment]
Review status: 8 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js, line 118 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHlH7f0fhtkH3mDKw5:-KYHpqbs9CZnTqt_vHFw:ba3tf6m) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js#L118)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I don't think user will understand what "Launch Modal" is. We need better text for this button.
</blockquote></details>

Sorry, that is just a leftover from early development that I didn't clean up yet. It will be opened by clicking any of the details or the text like "3 more occurrences" below the match. I can safely remove this now anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100)*

**Comment by davidmason** [comment]
Review status: 8 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js, line 149 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHljLt16TtLyrNh4hv:-KYHr0VICip3O4YvJdHg:bugk3y3) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js#L149)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is this component hooked up to state yet? or just using test data at the moment?
</blockquote></details>

Just test data, I am waiting until kgough finishes tweaking the UI before I merge in the code for using proper state.

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/LocalProjectDetailPanel.js, line 52 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHm2zk-Tleu7660Slu:-KYHrH339uwWW_OMljgs:b525882) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/LocalProjectDetailPanel.js#L52)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

We should use css class for translated and approve backgroundColor. It should be easy enough extract it to a css class.
</blockquote></details>

Agreed. Letting kgough do it so she can keep the css consistent.

---

*[server/zanata-frontend/src/editor/app/css/less/style.less, line 6132 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHjKLb0pYadns3IlWC:-KYHrUEd8cKw0K4IdgVp:b-x4jkdd) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/css/less/style.less#L6132)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Need newline at the end.

Is this file same as the one in frontend?
</blockquote></details>

Similar but I think they diverged a little bit. I think we will be able to copy across the new bits to frontend once this branch and the atomic-to-bootstrap one are merged, and just have editor point to the one in frontend.

---

*[server/zanata-frontend/src/editor/app/css/less/variables.less, line 891 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYHjS_D5zUgfil5TvRh:-KYHrphG8YeDbRMA9Kyv:b-a1f3lo) ([raw file](https://github.com/zanata/zanata-platform/blob/5ca259cb154a56656a475cd61d77d8349776818e/server/zanata-frontend/src/editor/app/css/less/variables.less#L891)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is this file same as the one in frontend?
</blockquote></details>

See comment on style.less

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100)*

**Comment by aeng** [comment]
Reviewed 9 of 14 files at r4.
Review status: 15 of 20 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/editor/app/actions/suggestions.js, line 340 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYL54EQCaJWoMYHe1_S:-KYL54EQ3FIdbBAMwNJW:b-58x17g) ([raw file](https://github.com/zanata/zanata-platform/blob/e73b8bdd5e9a82ed47f73c4ca52e698f496bd544/server/zanata-frontend/src/editor/app/actions/suggestions.js#L340)):*
> ```JavaScript
> }
> 
> export const SHOW_DETAIL_FOR_SUGGESTION_N =
> ```

why the _N?

---

*[server/zanata-frontend/src/editor/app/actions/suggestions.js, line 349 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYL56TPAuZ3Obu12GZ6:-KYL56TPBJaYjvKhm6r2:b-2gky77) ([raw file](https://github.com/zanata/zanata-platform/blob/e73b8bdd5e9a82ed47f73c4ca52e698f496bd544/server/zanata-frontend/src/editor/app/actions/suggestions.js#L349)):*
> ```JavaScript
>  *   the current suggestion list to show detail for that suggestion in the modal
>  */
> export function showDetailForSuggestionN (indexOrUndefined) {
> ```

why the N?

---

*[server/zanata-frontend/src/editor/app/components/SuggestionDetailsSummary.js, line 9 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYL4dntEc1BrwK33lTz:-KYL4dntDSbIGAUPNaBh:brq6fck) ([raw file](https://github.com/zanata/zanata-platform/blob/e73b8bdd5e9a82ed47f73c4ca52e698f496bd544/server/zanata-frontend/src/editor/app/components/SuggestionDetailsSummary.js#L9)):*
> ```JavaScript
> const SuggestionDetailsSummary = React.createClass({
>   propTypes: {
>     onClick: PropTypes.func,
> ```

Is this prop required?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100)*

**Comment by davidmason** [comment]
Review status: 15 of 20 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/editor/app/actions/suggestions.js, line 340 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYL54EQCaJWoMYHe1_S:-KYL7pJ29ayCIkewL2qM:b7kxhd9) ([raw file](https://github.com/zanata/zanata-platform/blob/e73b8bdd5e9a82ed47f73c4ca52e698f496bd544/server/zanata-frontend/src/editor/app/actions/suggestions.js#L340)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

why the _N?
</blockquote></details>

Because it is to show a the detail for a particular index **N**umber (rather than an ID or something). Like "Show detail for suggestion 5".

---

*[server/zanata-frontend/src/editor/app/actions/suggestions.js, line 349 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYL56TPAuZ3Obu12GZ6:-KYL8HOVETMNVFzJ7_B4:b-ya81ng) ([raw file](https://github.com/zanata/zanata-platform/blob/e73b8bdd5e9a82ed47f73c4ca52e698f496bd544/server/zanata-frontend/src/editor/app/actions/suggestions.js#L349)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

why the N?
</blockquote></details>

Same as above

---

*[server/zanata-frontend/src/editor/app/components/SuggestionDetailsSummary.js, line 9 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYL4dntEc1BrwK33lTz:-KYL8VUjAdTozz2UoSmz:b-grxtau) ([raw file](https://github.com/zanata/zanata-platform/blob/e73b8bdd5e9a82ed47f73c4ca52e698f496bd544/server/zanata-frontend/src/editor/app/components/SuggestionDetailsSummary.js#L9)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is this prop required?
</blockquote></details>

Not required - some instances of this are not clickable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100)*

**Comment by davidmason** [comment]
Review status: 15 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/zanata-frontend/src/editor/app/actions/suggestions.js, line 340 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYL54EQCaJWoMYHe1_S:-KYLM-bj0Ro05MbVYVea:bw7o1rm) ([raw file](https://github.com/zanata/zanata-platform/blob/e73b8bdd5e9a82ed47f73c4ca52e698f496bd544/server/zanata-frontend/src/editor/app/actions/suggestions.js#L340)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Because it is to show a the detail for a particular index **N**umber (rather than an ID or something). Like "Show detail for suggestion 5".
</blockquote></details>

Maybe `SHOW_DETAIL_FOR_SUGGESTION_BY_INDEX` would be clearer, or I could just drop the N - it wouldn't clash with anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100)*

**Comment by davidmason** [comment]
@zanata-jenkins retest this please.

**Comment by aeng** [comment]
Reviewed 1 of 15 files at r1, 1 of 14 files at r4, 2 of 2 files at r6.
Review status: 18 of 20 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/editor/app/actions/suggestions.js, line 340 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYL54EQCaJWoMYHe1_S:-KYQNvlE6QHFLEzi5nCf:b-4ookgj) ([raw file](https://github.com/zanata/zanata-platform/blob/e73b8bdd5e9a82ed47f73c4ca52e698f496bd544/server/zanata-frontend/src/editor/app/actions/suggestions.js#L340)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Maybe `SHOW_DETAIL_FOR_SUGGESTION_BY_INDEX` would be clearer, or I could just drop the N - it wouldn't clash with anything.
</blockquote></details>

I like `INDEX`, its clearer

---

*[server/zanata-frontend/src/editor/app/actions/suggestions.js, line 349 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYL56TPAuZ3Obu12GZ6:-KYQO14q2SX1ODXTq_KV:blmgdrq) ([raw file](https://github.com/zanata/zanata-platform/blob/e73b8bdd5e9a82ed47f73c4ca52e698f496bd544/server/zanata-frontend/src/editor/app/actions/suggestions.js#L349)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

`Index`?

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js, line 31 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYQOwij-UNiLoWBLLHf:-KYQOwij2mz0ef9QwMnW:bshwany) ([raw file](https://github.com/zanata/zanata-platform/blob/bbe611f0c1aa42ae13c1ac208024e024a1091c3f/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js#L31)):*
> ```JavaScript
> 
>     return (
>       <div>
> ```

Do we need a div to wrap around Modal?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100)*

**Comment by davidmason** [comment]
Review status: 18 of 20 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js, line 31 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-KYQOwij-UNiLoWBLLHf:-KYQZ3tvAA7dpMsXDuCC:b-pkcfn7) ([raw file](https://github.com/zanata/zanata-platform/blob/bbe611f0c1aa42ae13c1ac208024e024a1091c3f/server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js#L31)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we need a div to wrap around Modal?
</blockquote></details>

Good catch, I should have removed it when I took out the button.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100#-:-KYQfHr42xvJ0dj_5AzN:bnfp4nl)*

**Comment by djansen-redhat** [comment]
- [ ] Why does it show the text separated by 'untranslated' bar?
- [ ] It seems like the whole area of the listing is clickable, but only the portion where it displays the origin responds
- [ ] Does not manage a long filename in the suggestion correctly (or anywhere else in the react editor, for that matter)
- [ ] Translated/Approved label in details panel not vertically aligned with text
- [ ] There's a magic handle in the middle of the details panel that causes the bottom half to collapse. For what purpose?

Other:
- [ ] TM Suggestions shows low quality (0%) matches (gwt editor does not)
- [ ] Entering text into the TM search breaks the field (I think it's the "no results" panel)
screenshot from 2016-12-08 12-52-08

**Comment by davidmason** [comment]
>- [ ] Why does it show the text separated by 'untranslated' bar?

I was going for not showing any status there since it varies between the different details, but it is probably better to just show the same status as in the suggestions panel (the status of the first match).

>- [ ] It seems like the whole area of the listing is clickable, but only the portion where it displays the origin responds

Will look at changing it so that it only has the clicky cursor when over the origin information.

>- [ ] Does not manage a long filename in the suggestion correctly (or anywhere else in the react editor, for that matter)

Forgot about this, will look at truncating or wrapping.

>- [ ] Translated/Approved label in details panel not vertically aligned with text

True, will look at aligning it.

>- [ ] There's a magic handle in the middle of the details panel that causes the bottom half to collapse. For what purpose?

It must be a secret magic panel. Can you give more detail so I can find it? The detail is in an accordion panel and clicking the header will toggle the accordion panel open or closed - if you're testing something with just 1 detail item it might look like what you have described. If we make it force one panel to be open (i.e. never close a panel on click, just open) then it would work as an accordion and wouldn't look confusing when there is a single accordion panel.

I recommend:
 - upload a document to your test project
 - upload the same document with a different path
 - translate a string as "Translated" in one document, and the matching string as "Approved" in the other
 - export a TM of the project
 - upload the TM into a server custom TM

That should give you a full set of the possible match types, and will give you a full accordion panel.


>Other:
>- [ ] TM Suggestions shows low quality (0%) matches (gwt editor does not)

This is not related to the current change, so we should file it as a known issue.

>- [ ] Entering text into the TM search breaks the field (I think it's the "no results" panel)
>screenshot from 2016-12-08 12-52-08

Cause: looks like the bootstrap styles are interfering with existing elements and breaking them - in this case a `<button>` element (the cancel button that appears when you have any text there). Could be lots of other things broken by this. It may have been unwise to introduce the bootstrap styles in editor before we have any immediate plans for doing the migration. I'll look at whether I can pull them out for now and use some existing styles and components instead. I think it is mainly the accordion panel that we are using, the other elements would be very straightforward to change.

@kathryngo do you think the above would be possible?

**Comment by kathryngo** [comment]
@davidmason sounds like a good idea. I also think we should wait before moving bootstrap stuff in, if it is going to break stuff. Go ahead and try some existing styles and components I guess unless someone says otherwise.

**Comment by davidmason** [comment]
@kathryngo I don't think there is any accordion panel in the existing components, but it should be fairly easy to define one. I'll give it a go.

**Comment by djansen-redhat** [comment]
@davidmason looks like you helped me out with a gap in my testing of this PR. I completely neglected the system TM. Now that I realise they are accordion panels for multiple results it makes sense!
Perhaps not being able to collapse if there's only one item is an option, but it's almost a non-issue.

With regards to the separator colour, it may be misleading if it's the same colour as the first one, rather than the currently selected one.

**Comment by djansen-redhat** [comment]
The doc name wrapping is causing some issues
screenshot from 2016-12-15 13-57-41
screenshot from 2016-12-15 13-57-20

**Comment by davidmason** [comment]
@djansen-redhat yeah I noticed that, was going to look into it before I asked you to take another look. I'll ping you when I think it is ready.

**Comment by kathryngo** [comment]
tm-details


I have updated the css in the modal to deal with longer project and version names. I am wondering whether it would perhaps be best to list the information underneath each other to cater for long names. ie.
[ICON] PROJECT - project name
[ICON] VERSION - version name
[ICON] DOCUMENT - doc location

**Comment by spathare21** [comment]
@kathryngo is this PR ready to verify according to the Damian comments

**Comment by kathryngo** [comment]
@spathare21, I think so. I have fixed the layout of the details so that it handles longer file names better.

**Comment by spathare21** [comment]
Hi @kathryngo , yes the above modal with long file name looks good now , but two things are not looks good with long file name, have a look on below screens and also i have attached 1 video to jira ticket https://zanata.atlassian.net/browse/ZNTA-61.

long_filename

long_file

**Comment by kathryngo** [comment]
Since those new issues are not related to the modal, please open new tickets for them.

**Comment by spathare21** [comment]
ok thanks @kathryngo,then i am marking this PR as verified as modal looks fine with long file name. and will open new tickets for these issue.

**Comment by aeng** [comment]
Reviewed 1 of 15 files at r1, 6 of 12 files at r8, 3 of 3 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100)*

**Comment by aeng** [comment]
Reviewed 1 of 15 files at r1, 2 of 2 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/100)*

**Pull request merged**
