### PR TITLE
fix: handle redirect of error pages

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-2332

JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/661)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/rest/ZanataRestSecurityInterceptor.java, line 133 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/661#-L2s6thdb8jWw4XibnHe:-L2s6thdb8jWw4XibnHf:b-s804p4) ([raw file](https://github.com/zanata/zanata-platform/blob/e47bcc207f6934ea2713f6fef748d3e8b30e4b8e/server/services/src/main/java/org/zanata/rest/ZanataRestSecurityInterceptor.java#L133)):*
> ```Java
>             // here the tryLogin() will just set up the correct system state
>             zanataIdentity.tryLogin();
>         } else if (!ERROR_PAGES_URI.contains(request.getRequestURI()) &&
> ```

I don't think we need to change here. This interceptor is for REST request only and won't involve error page.

---

*[server/services/src/main/java/org/zanata/security/AnonymousAccessControlPhaseListener.java, line 80 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/661#-L2s6Xo81rQ-2x9mCgpo:-L2s6Xo9j5me9_bS60Jg:b-mzi3hc) ([raw file](https://github.com/zanata/zanata-platform/blob/e47bcc207f6934ea2713f6fef748d3e8b30e4b8e/server/services/src/main/java/org/zanata/security/AnonymousAccessControlPhaseListener.java#L80)):*
> ```Java
>     private boolean anonymousAccessIsNotAllowed() {
>         return !ERROR_PAGES_URI.contains(request.getRequestURI()) &&
>                 !allowAnonymousAccessProvider.get() && !identity.isLoggedIn();
> ```

I will suggest move this check to below requestingPageIsSignInOrRegister method (should also rename the method to requestingUnprotectedPage). This will make it clear which method is checking which.

---

*[server/services/src/main/java/org/zanata/security/UserRedirectBean.java, line 68 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/661#-L2s7aBOh9chkOUBufr_:-L2s7aBPgTgGE56hBglC:b3g4vkd) ([raw file](https://github.com/zanata/zanata-platform/blob/e47bcc207f6934ea2713f6fef748d3e8b30e4b8e/server/services/src/main/java/org/zanata/security/UserRedirectBean.java#L68)):*
> ```Java
>             ImmutableList.<String>builder()
>                     .add("/404.xhtml")
>                     .add("/error.xhtml")
> ```

This will only work if context path is "", e.g. deploy as ROOT.war. To make maintenance easier and consistent, I would suggest moving ```404.xhtml``` and ```error.xhtml``` to folder ```error/```, and rename error.xhtml to index.xhtml. And then in the AnonymousAccessControlPhaseLister class, we could just check whether it start with /error like the other two cases. (We can update the URL rewrite rule to maintain old external URL)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/661)*

**Comment by huangp** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/security/UserRedirectBean.java, line 69 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/661#-L2sTxA2zQU__RpNksu1:-L2sTxA3QQQtDeGQRdgs:bsgekt4) ([raw file](https://github.com/zanata/zanata-platform/blob/d9eac266ec41a0cdc08e227143b488065f71ccac/server/services/src/main/java/org/zanata/security/UserRedirectBean.java#L69)):*
> ```Java
>             ImmutableList.<String>builder()
>                     .add("/404")
>                     .add("/error/index")
> ```

I think the public url should just be ```/error/``` (from the UrlRewriteConfig class)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/661)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/security/UserRedirectBean.java, line 69 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/661#-L2sTxA2zQU__RpNksu1:-L2sUsGBPyShEaiCxS4G:biso97) ([raw file](https://github.com/zanata/zanata-platform/blob/d9eac266ec41a0cdc08e227143b488065f71ccac/server/services/src/main/java/org/zanata/security/UserRedirectBean.java#L69)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

I think the public url should just be ```/error/``` (from the UrlRewriteConfig class)
</blockquote></details>

the rule is `Join.path("/error/").to("/error/index.xhtml"))` which returns /error/index. I checked it locally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/661)*

**Comment by huangp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/security/UserRedirectBean.java, line 69 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/661#-L2sTxA2zQU__RpNksu1:-L2wAuyZVmwn3LLuxL8l:b-g1cah1) ([raw file](https://github.com/zanata/zanata-platform/blob/d9eac266ec41a0cdc08e227143b488065f71ccac/server/services/src/main/java/org/zanata/security/UserRedirectBean.java#L69)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

the rule is `Join.path("/error/").to("/error/index.xhtml"))` which returns /error/index. I checked it locally.
</blockquote></details>

do you think we should fix the url? looking at other rules. looks like changing index.xhtml to home.xhtml will work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/661)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/security/UserRedirectBean.java, line 69 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/661#-L2sTxA2zQU__RpNksu1:-L2wLxxkVe_XM61oA7Ln:b-oc6ejn) ([raw file](https://github.com/zanata/zanata-platform/blob/d9eac266ec41a0cdc08e227143b488065f71ccac/server/services/src/main/java/org/zanata/security/UserRedirectBean.java#L69)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

do you think we should fix the url? looking at other rules. looks like changing index.xhtml to home.xhtml will work?
</blockquote></details>

tried. will be `/error/home`. At this point. I think its better with index.html. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/661)*

**Comment by aeng** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/services/src/main/java/org/zanata/security/UserRedirectBean.java, line 69 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/661#-L2sTxA2zQU__RpNksu1:-L2wPStAa-vdp7p00R2H:bs9qxok) ([raw file](https://github.com/zanata/zanata-platform/blob/d9eac266ec41a0cdc08e227143b488065f71ccac/server/services/src/main/java/org/zanata/security/UserRedirectBean.java#L69)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

tried. will be `/error/home`. At this point. I think its better with index.html. What do you think?
</blockquote></details>

Done as discussed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/661)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 1 of 10 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/661#-:-L2wTI-Jz-NQT7BXXC6J:b49ms4)*

**Pull request merged**
