### PR TITLE
style: add .editorconfig for consistent whitespace

### PR DESCRIPTION
**Pull request by seanf**
http://editorconfig.org/

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/169)

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.editorconfig, line 62 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/169#-KbJ1dijEvrleit-drjv:-KbJ1dijEvrleit-drjw:b55kpkf) ([raw file](https://github.com/zanata/zanata-platform/blob/fa476ee1e802fcb26c87d4cf29b60f7b3de727c8/.editorconfig#L62)):*
> ```
> trim_trailing_whitespace = false
> 
> [{*.xml,*.xhtml}]
> ```

.html as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/169)*

**Comment by seanf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.editorconfig, line 62 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/169#-KbJ1dijEvrleit-drjv:-KbJ2rxb6p-5JLjuJlD0:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/fa476ee1e802fcb26c87d4cf29b60f7b3de727c8/.editorconfig#L62)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

.html as well?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/169)*

**Comment by huangp** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/169)*

**Comment by seanf** [comment]
Any more comments @aeng? Anything from you @kathryngo?

**Comment by kathryngo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/169#-:-KbJPm5bGMD9dKA7ad_S:bnfp4nl)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/169#-:-KbK_RE1lVz2EXg9SK8A:bnfp4nl)*

**Pull request merged**
