### PR TITLE
Change frontend paths ZNTA-1279

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL:

 - https://zanata.atlassian.net/browse/ZNTA-1279
 - https://zanata.atlassian.net/browse/ZNTA-1478 (path for /languages)
 - https://zanata.atlassian.net/browse/ZNTA-1480 (/a/more -> /info)

Changed alpha editor path, and path to frontend module components.

Alpha editor link should now open: /project/translate/{projectSlug}/v/{versionSlug}/{docId-slashes-not-encoded}?lang={localeId}

Frontend component URLs are now:

 - /profile/view/{username}
 - /glossary?locale={localeId}

## Known Issues

 - narrow viewport has a display glitch with locale label on textflow partially behind the status bar
 - does not load properly if query param 'lang' is not specified. Minor because link to alpha editor will always include it.
 - alpha editor does not redirect to login (existing issue)

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/40)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 7 of 8 files at r1, 4 of 9 files at r3, 23 of 23 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/AppView.java, line 270 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1HarDC0ViZU4At1xF:-KW1HarDC0ViZU4At1xG:b8ii919) ([raw file](https://github.com/zanata/zanata-platform/blob/fb2a5d0ace75db2bef9b2f989b66721c5d15ac2e/server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/AppView.java#L270)):*
> ```Java
>         newEditorLink.setHref(Application.getNewEditorLink(
>                 userWorkspaceContext.getWorkspaceContext().getWorkspaceId(),
>                 selectedDocId.replace("/", ",")));
> ```

So we treating everything after version as docId. May add a comment here as well.

---

*[server/zanata-frontend/src/editor/app/api/index.js, line 45 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1JsjF_NW3M9E5iPc_:-KW1JsjF_NW3M9E5iPca:b3filoc) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-frontend/src/editor/app/api/index.js#L45)):*
> ```JavaScript
> 
> export function fetchPhraseList (projectSlug, versionSlug, localeId, docId) {
>   // FIXME damason check that arguments are all defined
> ```

Is this something intended to be done by this PR?

---

*[server/zanata-frontend/src/editor/app/components/LanguagesDropdown.js, line 37 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1KTbbs3lVgpYTRrlU:-KW1KTbbs3lVgpYTRrlV:bts4rmp) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-frontend/src/editor/app/components/LanguagesDropdown.js#L37)):*
> ```JavaScript
>     const version = projectVersion.version
>     // FIXME this URL is too much information to keep in this component.
>     // FIXME loses any other query parameters
> ```

We might want to define a util method so this won't appear all over the place

---

*[server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, line 83 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1N5VpbFwhmmP3l_XW:-KW1N5VpbFwhmmP3l_XX:b-335b3k) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java#L83)):*
> ```Java
> 
>                 // Using this instead of "/project/{project}/v/{version}/translate/{document}"
>                 // needs discussion to decide whether to settle on this one
> ```

Have we agreed on this yet? If so will need to remove this comment

---

*[server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, line 86 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1OdA3Ib-FJ3FQ3aNP:-KW1OdA3Ib-FJ3FQ3aNQ:bn6bdci) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java#L86)):*
> ```Java
>                 .addRule(Join.path("/project/translate/{project}/v/{version}/{document}").to("/editor/index.xhtml"))
>                 .where("document").matches(".*")
>                 // FIXME should also work when a document is not yet selected
> ```

Do we have jira issue for this task? We may loose track if it's a FIXME tag in the source code.

---

*[server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, line 137 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1NeJzZlbsOVcKp4uH:-KW1NeK-NPzJvm2yGiNU:bkqvg7p) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java#L137)):*
> ```Java
> 
>                 // FIXME no longer exists: /profile/add_identity.xhtml
>                 .addRule(Join.path("/profile/add_identity").to("/profile/add_identity.xhtml"))
> ```

Could we get rid of it if it no long exists?

---

*[server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, line 140 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1NjBDBOtfKIhpmz2s:-KW1NjBDBOtfKIhpmz2t:b5fi0rr) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java#L140)):*
> ```Java
>                 .addRule(Join.path("/profile/create").to("/profile/create_user.xhtml"))
>                 // FIXME no longer exists: /profile/edit.xhtml
>                 .addRule(Join.path("/profile/edit").to("/profile/edit.xhtml"))
> ```

Could we get rid of this as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/40)*

**Comment by davidmason** [comment]
Review status: 32 of 34 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/AppView.java, line 270 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1HarDC0ViZU4At1xF:-KW1YDTkH0slMB-etL7W:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/fb2a5d0ace75db2bef9b2f989b66721c5d15ac2e/server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/AppView.java#L270)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> So we treating everything after version as docId. May add a comment here as well.
</details>
Done.

---

*[server/zanata-frontend/src/editor/app/api/index.js, line 45 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1JsjF_NW3M9E5iPc_:-KW1UWmDrJpNaqXk4pzv:b-8mzquh) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-frontend/src/editor/app/api/index.js#L45)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Is this something intended to be done by this PR?
</details>
No, anything that will generate and catch extra errors or change control flow I am leaving as separate issues. Flow may be able to handle null checks here so I may implement it with that if it is set up soon.

---

*[server/zanata-frontend/src/editor/app/components/LanguagesDropdown.js, line 37 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1KTbbs3lVgpYTRrlU:-KW1V7XmS6yF6Mni6Lek:bq3kqpc) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-frontend/src/editor/app/components/LanguagesDropdown.js#L37)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> We might want to define a util method so this won't appear all over the place
</details>
I have that as a separate JIRA task, since this is an existing problem from before this PR.

---

*[server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, line 83 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1N5VpbFwhmmP3l_XW:-KW1VQfE9JAuEhQU-zaB:b3a91rs) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java#L83)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Have we agreed on this yet? If so will need to remove this comment
</details>
Have talked to Sean and Carlos about it, so I will remove the comment.

---

*[server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, line 86 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1OdA3Ib-FJ3FQ3aNP:-KW1VmOUBhqO5QwejXgg:b-kwhlcw) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java#L86)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Do we have jira issue for this task? We may loose track if it's a FIXME tag in the source code.
</details>
I will add a JIRA for this instead. It is not a required feature yet since the only link to the editor includes the document.

---

*[server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, line 137 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1NeJzZlbsOVcKp4uH:-KW1WvO8oM01nUJsWTK5:b-ozfdqg) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java#L137)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Could we get rid of it if it no long exists?
</details>
Yes, no reason to keep them except to reference which URLs we used. I will remove both these rules.

---

*[server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, line 140 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1NjBDBOtfKIhpmz2s:-KW1YH5YxHOK0e29wZz5:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java#L140)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Could we get rid of this as well?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/40)*

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/editor/app/api/index.js, line 45 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1JsjF_NW3M9E5iPc_:-KW5L9sYTx8xKTZ-feJP:bvhbqn1) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-frontend/src/editor/app/api/index.js#L45)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> No, anything that will generate and catch extra errors or change control flow I am leaving as separate issues. Flow may be able to handle null checks here so I may implement it with that if it is set up soon.
</details>
I think we could just add a few invariant() here to show errors in the console. I think it's part of react.js and this is what it uses to check propTypes. But I am fine to leave it for later

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-:-KW5MPsDFn_Fi4glltm3:b9a2vem)*

**Comment by davidmason** [comment]
Review status: 30 of 34 files reviewed at latest revision, all discussions resolved.

---

*[server/zanata-frontend/src/editor/app/api/index.js, line 45 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KW1JsjF_NW3M9E5iPc_:-KWAizAkONAH8QO0nCD-:b-odn4we) ([raw file](https://github.com/zanata/zanata-platform/blob/644ef9edb37ef84e2e1d0db92597635903a1d196/server/zanata-frontend/src/editor/app/api/index.js#L45)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> I think we could just add a few invariant() here to show errors in the console. I think it's part of react.js and this is what it uses to check propTypes. But I am fine to leave it for later
</details>
invariant() is in flux, I think. I can look more into it, we do need a good standard way to handle checking for valid arguments (the ideal is a good type system).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/40)*

**Comment by davidmason** [comment]
This now includes https://zanata.atlassian.net/browse/ZNTA-1478 (update /languages URL) as well, since I needed to fix that so I could set up some test data.

---

Review status: 30 of 34 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-:-KWAjjua9aRRFOs0b94Q:b-amddpo)*

**Comment by huangp** [comment]
Reviewed 4 of 6 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-overlay/distros/wildfly/standalone/configuration/standalone-zanata.xml, line 48 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KWB-JmpKfS0MWhxPonK:-KWB-JmpKfS0MWhxPonL:b-a2hs7b) ([raw file](https://github.com/zanata/zanata-platform/blob/5bcf7e2d0654376bb8aeb1d67d37cd811659adff/server/zanata-overlay/distros/wildfly/standalone/configuration/standalone-zanata.xml#L48)):*
> ```XML
>         
>         <property name="zanata.origin.whitelist" value="http://localhost:8000" />
> ```

This is for zanata overlay. I don't think we want to allow it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/40)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-overlay/distros/wildfly/standalone/configuration/standalone-zanata.xml, line 48 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KWB-JmpKfS0MWhxPonK:-KWB-q9HVBixim1vpz7S:b-lwysb3) ([raw file](https://github.com/zanata/zanata-platform/blob/5bcf7e2d0654376bb8aeb1d67d37cd811659adff/server/zanata-overlay/distros/wildfly/standalone/configuration/standalone-zanata.xml#L48)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> This is for zanata overlay. I don't think we want to allow it here.
</details>
I think this must be another of those strange errors from the migration.

Looks like you have actually deleted that file in ZNTA-1445.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/40)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-overlay/distros/wildfly/standalone/configuration/standalone-zanata.xml, line 48 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-KWB-JmpKfS0MWhxPonK:-KWB2-pVQazv7d-rLe_o:b-8yvpzs) ([raw file](https://github.com/zanata/zanata-platform/blob/5bcf7e2d0654376bb8aeb1d67d37cd811659adff/server/zanata-overlay/distros/wildfly/standalone/configuration/standalone-zanata.xml#L48)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> I think this must be another of those strange errors from the migration.
> 
> Looks like you have actually deleted that file in ZNTA-1445.
</details>
*deleted server/docker/conf/standalone.xml I mean: https://github.com/zanata/zanata-platform/commit/a7c1e6a077969256b6581c78b3da1ede738dd132

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/40)*

**Comment by huangp** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-:-KWB5mWLkfxb9BZL2vBw:bnfp4nl)*

**Comment by djansen-redhat** [comment]
:white_check_mark: This looks fine, just waiting on Jenkins.

**Comment by huangp** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/40#-:-KWGiuUsHv15gYEHmPFq:bnfp4nl)*

**Pull request merged**
