### PR TITLE
fixes:(ZNTA-2159) version-group dropdown now showing correctly (ZNTA-2158) words no longer breaking over multiple lines in GWT

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2159
Other issue needing urgent fix in release: https://zanata.atlassian.net/browse/ZNTA-2158

Added css to make sure the version-group dropdown shows the entire list of options instead of being cut off in the parent container.

Before:
before

After:
after

Another issue (ZNTA-2158) which I have fixed in master but not in release correctly has been resolved in this issue since it only involved removing one word from a css rule. This is to make sure the GWT editor does not break words across multiple lines in the TM panel.

It now looks like this:
line-wrap-after

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/468)

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6047 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/468#-KqeWdX4O0VZOwLr_BYD:-KqeWdX4O0VZOwLr_BYE:b-f3onso) ([raw file](https://github.com/zanata/zanata-platform/blob/7d37a4f43b925e9152716e3419af4ae1c2949809/server/zanata-frontend/src/frontend/app/styles/style.less#L6047)):*
> ```Less
> }
> 
> .new-zanata #versionAutocomplete .autocomplete__results {
> ```

I think we should create a new file for anything with `.new-zanata` so keep track of all the jsf css we had. And import it into style.less 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/468)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/styles/style.less, line 6047 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/468#-KqeWdX4O0VZOwLr_BYD:-Kqe_HL8XiYsLt_ffSXr:bsm93n3) ([raw file](https://github.com/zanata/zanata-platform/blob/7d37a4f43b925e9152716e3419af4ae1c2949809/server/zanata-frontend/src/frontend/app/styles/style.less#L6047)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think we should create a new file for anything with `.new-zanata` so keep track of all the jsf css we had. And import it into style.less 
</blockquote></details>

Fair call. I think that should be part of the css task as I may be able to remove some of them as I go through the task.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/468)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/468#-:-KqfEWVmpGwGTyyV8ugc:bnfp4nl)*

**Comment by spathare21** [comment]
Verified build 1 pass

**Comment by kathryngo** [comment]
@spathare21 merged this, but there are merge conflicts with release and master (css). Shall look into this when I am in the office.

**Pull request merged**
