### PR TITLE
ZNTA-1626 only admin can create users

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1626

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/128)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 21 of 25 files at r1, 3 of 7 files at r2.
Review status: 22 of 28 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/components/Nav/index.jsx, line 148 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/128#-Ka4putIwC6VdJK2gjhV:-Ka4putIwC6VdJK2gjhW:bc46lo7) ([raw file](https://github.com/zanata/zanata-platform/blob/1557bb0d2307e3360d0211a761ad7798db156796/server/zanata-frontend/src/frontend/app/components/Nav/index.jsx#L148)):*
> ```JSX
>     // we don't allow public registration
>     const signUpIndex = items.findIndex(item => item.id === 'nav_sign_up')
>     items.splice(signUpIndex, 1)
> ```

I think this can be simplify by using https://lodash.com/docs#remove

---

*[server/zanata-war/src/main/java/org/zanata/action/AdminCreateUserAction.java, line 50 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/128#-Ka4rXFT2X5JYW2JVM90:-Ka4rXFT2X5JYW2JVM91:b-859ctg) ([raw file](https://github.com/zanata/zanata-platform/blob/1557bb0d2307e3360d0211a761ad7798db156796/server/zanata-war/src/main/java/org/zanata/action/AdminCreateUserAction.java#L50)):*
> ```Java
> @Named("adminCreateUserAction")
> @ViewScoped
> @Model
> ```

Does this class need this anotation?

---

*[server/zanata-war/src/main/java/org/zanata/action/AdminCreateUserAction.java, line 117 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/128#-Ka5awTMEeH6agsaljjB:-Ka5awTMEeH6agsaljjC:b-pj78zg) ([raw file](https://github.com/zanata/zanata-platform/blob/1557bb0d2307e3360d0211a761ad7798db156796/server/zanata-war/src/main/java/org/zanata/action/AdminCreateUserAction.java#L117)):*
> ```Java
>      * account
>      */
>     private boolean isNewUsernameValid(String username) {
> ```

Is it possible to share code with registerAction?

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/UserAccountServiceImpl.java, line 102 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/128#-Ka5geVeUrxthewg_mIH:-Ka5geVeUrxthewg_mII:b-2q225j) ([raw file](https://github.com/zanata/zanata-platform/blob/1557bb0d2307e3360d0211a761ad7798db156796/server/zanata-war/src/main/java/org/zanata/service/impl/UserAccountServiceImpl.java#L102)):*
> ```Java
> 
>     @Override
>     public HAccountResetPasswordKey requestPasswordReset(String username,
> ```

need comment for this method. Generate random key...

---

*[server/zanata-war/src/main/webapp/admin/create_user.xhtml, line 10 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/128#-Ka5hAlnCcXafqFbRXcv:-Ka5hAloET20RWXMy-ew:bentj8t) ([raw file](https://github.com/zanata/zanata-platform/blob/1557bb0d2307e3360d0211a761ad7798db156796/server/zanata-war/src/main/webapp/admin/create_user.xhtml#L10)):*
> ```HTML
>   xmlns:zanata="http://java.sun.com/jsf/composite/zanata">
> 
> <ui:composition template="../WEB-INF/template/template.xhtml">
> ```

you can remove `..`. So just template="/WEB-INF/template/template.xhtml"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/128)*

**Comment by huangp** [comment]
Review status: 22 of 28 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/components/Nav/index.jsx, line 148 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/128#-Ka4putIwC6VdJK2gjhV:-Ka5jGa8fLJ9sOcJP26v:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/1557bb0d2307e3360d0211a761ad7798db156796/server/zanata-frontend/src/frontend/app/components/Nav/index.jsx#L148)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think this can be simplify by using https://lodash.com/docs#remove
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/java/org/zanata/action/AdminCreateUserAction.java, line 50 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/128#-Ka4rXFT2X5JYW2JVM90:-Ka5hvQWJilH-BLX_PQM:b-pooj1b) ([raw file](https://github.com/zanata/zanata-platform/blob/1557bb0d2307e3360d0211a761ad7798db156796/server/zanata-war/src/main/java/org/zanata/action/AdminCreateUserAction.java#L50)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Does this class need this anotation?
</blockquote></details>

I copy it from UserAction class which is very similar. It's just a sterotype annotation. No harm to leave it.

---

*[server/zanata-war/src/main/java/org/zanata/action/AdminCreateUserAction.java, line 117 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/128#-Ka5awTMEeH6agsaljjB:-Ka5iALYu_fLB_OgE7rl:b-mpa3fy) ([raw file](https://github.com/zanata/zanata-platform/blob/1557bb0d2307e3360d0211a761ad7798db156796/server/zanata-war/src/main/java/org/zanata/action/AdminCreateUserAction.java#L117)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Is it possible to share code with registerAction?
</blockquote></details>

Already share most of the stuff  with my last commit.

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/UserAccountServiceImpl.java, line 102 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/128#-Ka5geVeUrxthewg_mIH:-Ka5jDQD84HvzjgZ9Cjj:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/1557bb0d2307e3360d0211a761ad7798db156796/server/zanata-war/src/main/java/org/zanata/service/impl/UserAccountServiceImpl.java#L102)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

need comment for this method. Generate random key...
</blockquote></details>

Done.

---

*[server/zanata-war/src/main/webapp/admin/create_user.xhtml, line 10 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/128#-Ka5hAlnCcXafqFbRXcv:-Ka5juT6oi7fcn_oTtMH:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/1557bb0d2307e3360d0211a761ad7798db156796/server/zanata-war/src/main/webapp/admin/create_user.xhtml#L10)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

you can remove `..`. So just template="/WEB-INF/template/template.xhtml"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/128)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/128#-:-Ka9wt-mY2CrewHEV5G4:bnfp4nl)*

**Comment by spathare21** [comment]
@aeng , After creating user on local instance email activation link should have to generat with local instance URL. but currently its generated with https://translate.engineering.redhat.com/account/activate/408be71006b7ce9c5d69fadf6143286f?resetPasswordKey=fc690ceb8c71d1ea838706d15cb64de0. 

hence we are unable to activate that account.

**Comment by huangp** [comment]
@spathare21 you may be using production data in your local environment. Go to admin -> server configuration and change the server URL there to your local host url

**Comment by spathare21** [comment]
yes thanks @huangp , it was production database.

**Comment by spathare21** [comment]
Verified user creattion. also activation mail sent within sec 

02:34:27,878 INFO  [org.zanata.email.EmailBuilder] (default task-9) Sending message with Subject "Zanata Account Activation" to Recipients [test_create_user2 <qw7utsk3htr5ovab@my10minutemail.com>] From [Zanata <noreply@translate.engineering.redhat.com>] Reply-To [Zanata <noreply@translate.engineering.redhat.com>]
02:34:30,702 INFO  [org.zanata.ui.faces.FacesMessages] (default task-9) message to user (wid: -2621): An activation email has been sent to user test_create_user2.)

also if try out with query param on existing account activation url it will redirect us to login page.

**Pull request merged**
