### PR TITLE
ZNTA-1654-userprofile

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1654

Remove all Zanata-UI dependencies from UserProfile containers

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/161)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/161#-:-Kb8_98g0vio2x5r5T-l:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo , some of the text box css changed and because of this text is getting cut for date on profile . dashboard view changed

**Comment by kathryngo** [comment]
Thanks @spathare21. I'll fix those issues first thing tomorrow .

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/161#-:-Kb8zYjJ8phOafiea8DO:b-3yahgq)*

**Comment by kathryngo** [comment]
These seem to be bugs only in Firefox, am correcting now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/161#-:-KbCo1X7tuZ63vXIUN8Q:b-rhptlf)*

**Comment by kathryngo** [comment]
Changes made. Please check and merge as soon as possible so I can continue onto next task (relies on this being merged into master). Thanks 😁

**Comment by spathare21** [comment]
Verified

**Comment by kathryngo** [comment]
Thanks @spathare21!

**Pull request merged**
