### PR TITLE
fix(ZNTA-2247): Remove magic numbers for glossary csv columns

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2247

Still expects column 0 to be the source locale, but checks that the
PoS and Description columns are named. This prevents garbage in
said fields.
This change also prevents repeatedly setting these fields, only
doing so once per row.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/592)

### CODE REVIEW

**Comment by aeng** [comment]
Need to update the docs too for this updated format that we support for CSV glossary

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVReader.java, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/592#-L0NAW2n793Fw_zgoYpP:-L0NAW2n793Fw_zgoYpQ:b-fqc6s3) ([raw file](https://github.com/zanata/zanata-platform/blob/271d61da2f517ee60a76cd9ed85a6f0b829d3571/common/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVReader.java#L25)):*
> ```Java
> import java.io.IOException;
> import java.io.Reader;
> import java.util.*;
> ```

I think we got a rule to not using wildcard imports

---

*[common/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVReader.java, line 84 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/592#-L0NBEc83jW_rex-AD8n:-L0NAq7Cl2MTPn2wqQct:b-wtcfmr) ([raw file](https://github.com/zanata/zanata-platform/blob/271d61da2f517ee60a76cd9ed85a6f0b829d3571/common/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVReader.java#L84)):*
> ```Java
>             Map<LocaleId, List<GlossaryEntry>> results = Maps.newHashMap();
> 
>             for (int i = 1; i < records.size(); i++) {
> ```

Not blocker, but can simplify this for loop statement if we are not using `i`: `for (String record: records)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/592#-:-L0NCJoW3gMJQTdXfunR:b-fi10wz)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/592#-:-L0NXu-4ywek7sbFFHtR:bnfp4nl)*

**Comment by spathare21** [comment]
@djansen-redhat did't get what to test here, what was the issue? and how to test this.

**Comment by djansen-redhat** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[common/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVReader.java, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/592#-L0NAW2n793Fw_zgoYpP:-L2TUXwaIaq-vQdKjbce:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/271d61da2f517ee60a76cd9ed85a6f0b829d3571/common/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVReader.java#L25)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think we got a rule to not using wildcard imports
</blockquote></details>

Done.

---

*[common/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVReader.java, line 84 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/592#-L0NBEc83jW_rex-AD8n:-L2TUW_jT9LrD-pcKAx5:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/271d61da2f517ee60a76cd9ed85a6f0b829d3571/common/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVReader.java#L84)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Not blocker, but can simplify this for loop statement if we are not using `i`: `for (String record: records)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/592)*

**Comment by djansen-redhat** [comment]
@spathare21 basically, the parser _assumed_ the last two columns of a csv were *pos* and *description*, when in fact they could be anything, and that "anything" will be stored in the database.
This change demands the column header is one of "pos/partofspeech/part of speech" and "desc/description/definition".

**Comment by aeng** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/592#-:-L2TYNJ3vb7tuMtqozkQ:bnfp4nl)*

**Pull request merged**
