### PR TITLE
refactor to make zanata-client-command more customizable

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1619

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/119)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/119#-:-KZUfnRgw7bZOLlafeBj:bnfp4nl)*

**Comment by spathare21** [comment]
@huangp can you please let me know what needs to be tested for verifying this PR

**Comment by huangp** [comment]
@spathare21 no functionality change. It's just refactor one big method (break it up into smaller ones and make them public so that other library can call them) and added a new method so that other library can customize an object. If the build passes I would say it's ok. You may also do some sanity test.

**Comment by spathare21** [comment]
Verified build is successful and ui and client sanity is green

**Pull request merged**
