### PR TITLE
ZNTA-2093 allow users to ignore certain context mismatch

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2093

- redesign of the UI
- allow users to ignore context mismatch (e.g. allow copy as translated even some meta data is different)

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/502)

### CODE REVIEW

**Comment by kathryngo** [comment]
I need to make some css styling changes to this modal since the backend changes have overridden some styles. I shall mark this as Awaiting Review once I have fixed things.

**Comment by kathryngo** [comment]
@huangp UI fixed, ready for review

**Comment by huangp** [comment]
@kathryngo I am seeing some warnings in browser console:
```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See MergeOptions > Panel > a > ... > a.
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>. See MergeOptions > p > ... > SelectableDropdown > DropdownButton > Uncontrolled(Dropdown) > Dropdown > ButtonGroup > div.
Warning: validateDOMNesting(...): <ul> cannot appear as a descendant of <p>. See MergeOptions > p > ... > SelectableDropdown > DropdownButton > Uncontrolled(Dropdown) > Dropdown > DropdownMenu > ul.
```
I think we need to change the element to avoid these warnings. But I am afraid it will break the style again. I will discuss with you when we are both in the office

**Comment by kathryngo** [comment]
Aha, thanks @huangp. I shall fix this first thing tomorrow.

**Comment by kathryngo** [comment]
@huangp Have fixed those errors as best I can, except this one. I cannot seem to find what is causing it.

```
 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
 See Panel > a > ... > a.

```

I tried to use the Link component in the one place I saw the ```a href``` element but it didn't fix it.

**Comment by huangp** [comment]
@kathryngo I fixed the warning. Now I think it's just the [more] "link". Right now it's just plain text. Unless you want to style it differently this is fine. The problem is the Accordion component will generate an <a> tag so we can't use any <a> tag inside it. (I used to use a <Button bsStyle="link">)

**Comment by kathryngo** [comment]
Thanks @huangp. I shall have a quick look at this branch and make any minor changes if needed. I thought it was to do with the heading in the panel but I had difficulty fixing it.

**Comment by kathryngo** [comment]
changes made. it's ready for review or QA now unless you have other changes @huangp

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 21 of 28 files at r1, 7 of 11 files at r2, 2 of 4 files at r3, 2 of 2 files at r6, 5 of 5 files at r7.
Review status: 36 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/502#-:-KtF_rE0dZ9oDzksYr-l:bnfp4nl)*

**Comment by kathryngo** [comment]
@huangp I shall attempt to fix these build errors for you

**Comment by huangp** [comment]
rerun the build. Now it's green.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/502#-:-KtPC5fZ4YgBUgRWh9qT:bnfp4nl)*

**Pull request merged**
