### PR TITLE
Znta 845 findbugs 2

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-845

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/317)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 20 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java, line 242 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/317#-Kk8Ux_vclgGoJq9mqsp:-Kk8Ux_vclgGoJq9mqsq:b-l2jvdx) ([raw file](https://github.com/zanata/zanata-platform/blob/7d0005306fd53e7b61b2c618ccd673506f44f160/server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java#L242)):*
> ```Java
>                 log.warn(logString);
>                 if ((firstException == null) && !ignorable(msg)) {
>                     String pageSource = shortenPageSource(getDriver());
> ```

Is this a bad merge? I remember Sean put in this shortenPageSource to prevent large page source in log.

---

*[server/zanata-war/src/main/java/org/zanata/security/ZanataIdentity.java, line 439 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/317#-Kk8WpzuIl4dPgTM5nmm:-Kk8WpzuIl4dPgTM5nmn:b17ekl3) ([raw file](https://github.com/zanata/zanata-platform/blob/56ad6425a51d3e1396d776ef57097c72c628348c/server/zanata-war/src/main/java/org/zanata/security/ZanataIdentity.java#L439)):*
> ```Java
> 
>     // based on org.jboss.seam.security.Identity.authenticate()
>     private void authenticate() throws LoginException {
> ```

Can we justify removing synchronized won't affect the functionality?

---

*[server/zanata-war/src/test/java/org/zanata/limits/LeakyBucketTest.java, line 108 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/317#-Kk8XteYJ_2RaKhntAZX:-Kk8XteYJ_2RaKhntAZY:bjq97p0) ([raw file](https://github.com/zanata/zanata-platform/blob/7d0005306fd53e7b61b2c618ccd673506f44f160/server/zanata-war/src/test/java/org/zanata/limits/LeakyBucketTest.java#L108)):*
> ```Java
>         when(ticker.read()).thenReturn(timeOverRefillDuration * 2);
>         assertThat(bucket.tryAcquire(), Matchers.is(true));
>         assertThat(bucket.tryAcquire(), Matchers.is(true));
> ```

Why is test removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/317)*

**Comment by aeng** [comment]
Review status: 19 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java, line 242 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/317#-Kk8Ux_vclgGoJq9mqsp:-Kk8i0kN5s8lffigOqSP:b-230o7j) ([raw file](https://github.com/zanata/zanata-platform/blob/7d0005306fd53e7b61b2c618ccd673506f44f160/server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java#L242)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Is this a bad merge? I remember Sean put in this shortenPageSource to prevent large page source in log.
</blockquote></details>

Yup. Bad merge, reverting it.

---

*[server/zanata-war/src/test/java/org/zanata/limits/LeakyBucketTest.java, line 108 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/317#-Kk8XteYJ_2RaKhntAZX:-Kk8i86poN_SrgD1Nb2O:bfguhob) ([raw file](https://github.com/zanata/zanata-platform/blob/7d0005306fd53e7b61b2c618ccd673506f44f160/server/zanata-war/src/test/java/org/zanata/limits/LeakyBucketTest.java#L108)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Why is test removed?
</blockquote></details>

There's another test on top that is covering it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/317)*

**Comment by huangp** [comment]
:lgtm: build fail though -(Awaiting review) 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-war/src/main/java/org/zanata/security/ZanataIdentity.java, line 439 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/317#-Kk8WpzuIl4dPgTM5nmm:-Kk8uKJ3fRB7ZyMCO6oR:b-3l413j) ([raw file](https://github.com/zanata/zanata-platform/blob/56ad6425a51d3e1396d776ef57097c72c628348c/server/zanata-war/src/main/java/org/zanata/security/ZanataIdentity.java#L439)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Can we justify removing synchronized won't affect the functionality?
</blockquote></details>

For the record, there is a @Synchronize annotation at the class level so no need to add synchronized here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/317#-:-Kk8uW-sEqHgXY4pG_Hx:bvpnhj8)*

**Comment by djansen-redhat** [comment]
This can be best evaluated under release testing.

**Pull request merged**
