### PR TITLE
fix(ZNTA-481): Log in with username or email address

### PR DESCRIPTION
**Pull request by djansen-redhat**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-481

Log in with username or email address

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/315)

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-war/src/main/java/org/zanata/action/LoginAction.java, line 89 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/315#-KjurxOeNPC2Inv0zWO0:-KjurxOf3r8xBktgUbi9:b-zdzlfd) ([raw file](https://github.com/zanata/zanata-platform/blob/1b52b6eaa486b9a2a176a1beb21b29b806f197d0/server/zanata-war/src/main/java/org/zanata/action/LoginAction.java#L89)):*
> ```Java
>         switch (credentials.getAuthType()) {
>         case INTERNAL:
>             if (new EmailValidator().isValid(username, null)) {
> ```

Should put comment on Internal auth allows both username and email use for login.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/315)*

**Comment by djansen-redhat** [comment]
@aeng Done

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/315)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/315#-:-Kk8-zfgocUSG3DS3SNn:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/315)*

**Comment by spathare21** [comment]
[] Verified

**Pull request merged**
