### PR TITLE
fix: add non-nullable constrain in criteria description

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-2360

JIRA issue URL: *paste URL here*

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/683)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/services/src/main/java/org/zanata/rest/review/ReviewService.java, line 163 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/683#-L3R0oElCYUcIYFrnncM:-L3R0oElCYUcIYFrnncN:b-m01aw8) ([raw file](https://github.com/zanata/zanata-platform/blob/db5aa4a597c1e4b524d5940f43c375dbc888719c/server/services/src/main/java/org/zanata/rest/review/ReviewService.java#L163)):*
> ```Java
>     private Optional<Response> validateReviewCriteria(TransReviewCriteria criteria) {
>         String description = criteria.getDescription();
>         if (StringUtils.isBlank(description) ||
> ```

We could just ```@Inject private Validator validator;``` and put the @Size annotation on the dto to validate here

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 126 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/683#-L3R-D-Dw8n2kCqQJpB0:-L3R-D-Dw8n2kCqQJpB1:b-4hfaht) ([raw file](https://github.com/zanata/zanata-platform/blob/db5aa4a597c1e4b524d5940f43c375dbc888719c/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L126)):*
> ```JavaScript
>       )
>       : DO_NOT_RENDER
>     const formBtn = true ? (
> ```

why removing isAdminMode? if it's not admin, it should not display the edit form

---

*[server/zanata-model/src/main/java/org/zanata/model/ReviewCriteria.java, line 55 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/683#-L3QzzrdiusN4WL1p3Ss:-L3QzzrdiusN4WL1p3St:b-xtc1ow) ([raw file](https://github.com/zanata/zanata-platform/blob/db5aa4a597c1e4b524d5940f43c375dbc888719c/server/zanata-model/src/main/java/org/zanata/model/ReviewCriteria.java#L55)):*
> ```Java
>     private IssuePriority priority;
>     private boolean editable;
>     @NotEmpty
> ```

Here we could just add ```@Size(max = 255)```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/683)*

**Comment by djansen-redhat** [comment]
@aeng will this conflict with @kathryngo's work on #672 ?

**Comment by aeng** [comment]
Nope. nothing in conflict.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/services/src/main/java/org/zanata/rest/review/ReviewService.java, line 163 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/683#-L3R0oElCYUcIYFrnncM:-L3RQujtkBGQO0-klKNY:b-cg4wj3) ([raw file](https://github.com/zanata/zanata-platform/blob/db5aa4a597c1e4b524d5940f43c375dbc888719c/server/services/src/main/java/org/zanata/rest/review/ReviewService.java#L163)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

We could just ```@Inject private Validator validator;``` and put the @Size annotation on the dto to validate here
</blockquote></details>

The DTO is located in gwt-shared package which does not have hibernate dependency. That is why this method is used for the validation. I prefer to do another PR if we plan to move the DTO package or include a new dependency to the module.

---

*[server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js, line 126 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/683#-L3R-D-Dw8n2kCqQJpB0:-L3RPRozslrNE7ANotx0:bvj0vb6) ([raw file](https://github.com/zanata/zanata-platform/blob/db5aa4a597c1e4b524d5940f43c375dbc888719c/server/zanata-frontend/src/frontend/app/components/RejectionsForm/index.js#L126)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

why removing isAdminMode? if it's not admin, it should not display the edit form
</blockquote></details>

Accident. Was testing the feature. restored

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/683#-:-L3RPaLhozqKgaNogFno:b-gkd1gf)*

**Comment by aeng** [comment]
Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-model/src/main/java/org/zanata/model/ReviewCriteria.java, line 55 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/683#-L3QzzrdiusN4WL1p3Ss:-L3RRfQ57Wkl4cWqAvOQ:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/db5aa4a597c1e4b524d5940f43c375dbc888719c/server/zanata-model/src/main/java/org/zanata/model/ReviewCriteria.java#L55)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Here we could just add ```@Size(max = 255)```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/683)*

**Comment by huangp** [comment]
-(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/683#-:-L3RSCkgIX_9e6IrTPzH:b-1amvkm)*

**Comment by spathare21** [comment]
@aeng Build failed.
Save button is not enabled until we enter some text in review criteria. but textbox looks red border, I don't think so it required.

screenshot from 2018-01-22 14-19-06

**Comment by aeng** [comment]
@spathare21 I have updated the PR.

**Comment by spathare21** [comment]
Verified : )

**Pull request merged**
