### PR TITLE
ZNTA-1966 - include TransMemoryUnit id into the result id list

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1966

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/316)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/316)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/316#-:-KjurQRtKxgNFVF8qvxV:bnfp4nl)*

**Comment by spathare21** [comment]
@huangp , I  have't got any error message while TM merge having TM from TMX. but i got and below error message when i load editor 

`07:03:38,719 WARN  [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Lucene query returned 20 results (out of approx 231196). Increasing zanata.tm.max.results might produce more matches.
07:03:38,760 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,761 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,761 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,762 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,762 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,763 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,763 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,763 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,763 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,763 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,763 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,763 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.
07:03:38,763 ERROR [org.zanata.service.impl.TranslationMemoryServiceImpl] (default task-49) Query results include null entity. You may need to re-index.`

tried before merging this PR as well.

**Comment by huangp** [comment]
@spathare21 This message means your index is out of date. Log in as admin and go to admin page->manage index and then re-index will fix it. If you are using production database, it might take a while to complete. Alternatively you can copy the production index files over.

**Comment by spathare21** [comment]
@huangp thanks it works. verified

**Pull request merged**
