### PR TITLE
fix(ZNTA-2607) remove badge component from tmx export modal

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2607

The TMX Export modal was showing incorrectly due to the use of the antd Badge component that doesn't exist. The tag component should be used instead. In this case, the badge was just turned into muted text for the document count. See below:

tmx

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by efloden** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/881#-:-LERqNVJ4Zfx9HY0ELFi:bnfp4nl)*

**Comment by efloden** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/881)*

**Comment by spathare21** [comment]
@efloden this should be targeted to release branch right?

**Comment by efloden** [comment]
@spathare21 Yes we can target release with this one

**Comment by djansen-redhat** [comment]
This contains 48 commits, I think someone may have accidentally pulled master while targeting release.

**Comment by kathryngo** [comment]
@djansen-redhat damn, you are right. I will have to redo this quick fix in a new PR

**Pull request closed without merging**
