### PR TITLE
fix(ZNTA-2327) isolated highlight styling to Editor

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2327

Isolate editor highlight styling so it does not affect frontend

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/654)

### CODE REVIEW

**Comment by efloden** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/654#-:-L2XT3YYQyFJclJvXC0-:bnfp4nl)*

**Comment by djansen-redhat** [comment]
Verified fixed. Still waiting on Jenkins.

**Comment by djansen-redhat** [comment]
@kathryngo Jenkins1 can be ignored. Merge as desired.

**Comment by kathryngo** [comment]
@djansen-redhat cheers, shall wait to see what happens with both the tests still building

**Pull request merged**
