### PR TITLE
feat(ZNTA-2425): Validation Options for Editor sidebar backend

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2425

Implement Validation Options Settings in the React Editor sidebar.
validationoptions
Implementation functionality should be identical to the GWT editor.
Created new project version service to retrieve validation options from server.
Options are presented as:
'Error' status = checkbox disabled and checked
'Warning' status = checkbox checked and toggleable 
'Off' status = checkbox unchecked and toggleable

This feature implements a Feature Switch in server/zanata-frontend/src/app/utils/FeatureToggles.ts
The feature can be enabled for QA by returning true from the corresponding function in this file, in this case the "showValidationOptions" function.

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/services/src/main/java/org/zanata/rest/editor/service/ProjectService.java, line 75 at r2](https://beta.reviewable.io/reviews/zanata/zanata-platform/750#-L80bHZZ4I5bZm2N5Xjc:-L80bHZZ4I5bZm2N5Xjd:bh6sqdh) ([raw file](https://github.com/zanata/zanata-platform/blob/5cfb308b27886ac31bdcd982f13dc172134fd667/server/services/src/main/java/org/zanata/rest/editor/service/ProjectService.java#L75)):*
> ```Java
>         }
> 
>         HashMap<ValidationId, ValidationAction.State> result =
> ```

The left hand side assignee normally use interface type so that it only expose public methods to callers. So here Map will do.

---

*[server/services/src/main/java/org/zanata/rest/editor/service/resource/ProjectResource.java, line 48 at r2](https://beta.reviewable.io/reviews/zanata/zanata-platform/750#-L80d5-_70w2492I85_b:-L80d5-_70w2492I85_c:b-g3a088) ([raw file](https://github.com/zanata/zanata-platform/blob/5cfb308b27886ac31bdcd982f13dc172134fd667/server/services/src/main/java/org/zanata/rest/editor/service/resource/ProjectResource.java#L48)):*
> ```Java
> 
>     /**
>      * Returns Validation settings for a Project.
> ```

for a project version.

---

*[server/services/src/main/java/org/zanata/rest/editor/service/resource/ProjectResource.java, line 65 at r2](https://beta.reviewable.io/reviews/zanata/zanata-platform/750#-L80l84aAO8H4HAdYb9Y:-L80l84aAO8H4HAdYb9Z:b-vrw6ub) ([raw file](https://github.com/zanata/zanata-platform/blob/5cfb308b27886ac31bdcd982f13dc172134fd667/server/services/src/main/java/org/zanata/rest/editor/service/resource/ProjectResource.java#L65)):*
> ```Java
>     @GET
>     @Produces({ MediaType.APPLICATION_JSON })
>     @Path("/validators/{projectSlug}")
> ```

Normally we put both project slug and version slug in path. e.g. /validators/{projectSlug}/{versionSlug}
Also the convention is to have path reflect resource hierarchy and meaningful. I would suggest to change it to /project/{projectSlug}/version/{versionSlug}/validators 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/zanata/zanata-platform/750)*

**Comment by djansen-redhat** [comment]
@efloden I'm not a fan of the header spacing. I think there needs to be a gap before 'Validation Options'.

**Comment by aeng** [comment]
@efloden @djansen-redhat let runs through it with @kathryngo on the UI side.

**Comment by huangp** [comment]
Reviewed 5 of 5 files at r3, 7 of 10 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/750)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/750#-:-L8GYeu6Q9zLy9QRrUpA:b49ms4)*

**Comment by djansen-redhat** [comment]
Seems to be an error in checking enabled state (see overlayed screenshot):

screenshot from 2018-03-26 13-06-11

**Comment by djansen-redhat** [comment]
Verified

**Pull request merged**
