### PR TITLE
feat: display projects in dashboard for member and maintainer

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-2578

*[description]*

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/852#-:-LDdPSxG7_le4IVPQMiQ:b49ms4)*

**Comment by spathare21** [comment]
@aeng as per Jira ticket non-maintainer should be able to view projects and group on dashboard ,
but looks like with this Pr maintainer can list project on dashboard.

**Comment by aeng** [comment]
@spathare21 right now in user dashboard, user can only see their maintained project/group. This PR allows the locale member to be able to see the project they are assigned to now. Nothing changes in group as there is no "members" concept.

**Comment by spathare21** [comment]
@aeng  ok thanks

**Pull request merged**
