### PR TITLE
ZNTA-2156-storybook-rejection-modal

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2156

Storybook for Reject Translation Modal for Alpha Editor

Please note:  Some work needs to be done to wire up the dropdown properly.  and to set the comment box as inactive for selections other than Other - although I think it will be useful if the reviewer can leave a comment on any type of rejection. If you have any questions, please ask! - K 

_Updated 17/08_
rejecmod

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/479)

### CODE REVIEW

**Comment by kathryngo** [comment]
@djansen-redhat can you have a look at this when you get back? Thanks

**Comment by aeng** [comment]
Reviewed 1 of 4 files at r1, 3 of 5 files at r5.
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.js, line 21 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/479#-KsCfv_bQVY8Zh8TM33z:-KsCfv_bQVY8Zh8TM34-:b-3fbk3y) ([raw file](https://github.com/zanata/zanata-platform/blob/bee8090426c11f8bd627bcf43196195dab2ff403/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.js#L21)):*
> ```JavaScript
>     priority: PropTypes.oneOf(
>         [
>           'Minor',
> ```

I remembered we worked out of using constants for these 3 values? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/479)*

**Comment by kathryngo** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.js, line 21 at r5](https://reviewable.io:443/reviews/zanata/zanata-platform/479#-KsCfv_bQVY8Zh8TM33z:-KsCgZhGRbYQAkCehgP-:b-91ac4j) ([raw file](https://github.com/zanata/zanata-platform/blob/bee8090426c11f8bd627bcf43196195dab2ff403/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/index.js#L21)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I remembered we worked out of using constants for these 3 values? 
</blockquote></details>

Aha, in a different branch. I shall update this branch to use the same approach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/479)*

**Comment by kathryngo** [comment]
@aeng a heap more files were added because I had to merge in master to fix some conflicts before pushing

**Comment by aeng** [comment]
Reviewed 4 of 5 files at r6.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.test.js, line 13 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/479#-KsH9u17iUt8oOo_CAcY:-KsH9u17iUt8oOo_CAcZ:b-n4zxwx) ([raw file](https://github.com/zanata/zanata-platform/blob/7596dfcf4b3ef1d91350f77b45d775c7f643a1fd/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.test.js#L13)):*
> ```JavaScript
>     <RejectTranslationModal show isOpen={true}
>       criteria="test criteria"
>       priority="Critical"  textState="u-textDanger" />
> ```

the value for `priority` needs to change to use the const? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/479)*

**Comment by kathryngo** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.test.js, line 13 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/479#-KsH9u17iUt8oOo_CAcY:-KsHFIRFrI9CQ-xXJdlQ:b-v60684) ([raw file](https://github.com/zanata/zanata-platform/blob/7596dfcf4b3ef1d91350f77b45d775c7f643a1fd/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.test.js#L13)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

the value for `priority` needs to change to use the const? 
</blockquote></details>

(sorry, posted this in the wrong branch in the wrong place initially)

If I change it to use the const ie. priority={CRITICAL}

then I get

`ReferenceError: CRITICAL is not defined`, the same for the similar review issue in #479 

What am I doing wrong? Btw, I will delete the test.js file as it is not needed yet, as the snapshots test the story files. The same issue applies to the storybook file though - if I change priority to take a constant in the story file then it fails. It passes everything if I don't, which is weird isn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/479)*

**Comment by aeng** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.test.js, line 13 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/479#-KsH9u17iUt8oOo_CAcY:-KsHFsv5iNB5JIeDr9kf:b-6plmic) ([raw file](https://github.com/zanata/zanata-platform/blob/7596dfcf4b3ef1d91350f77b45d775c7f643a1fd/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.test.js#L13)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

(sorry, posted this in the wrong branch in the wrong place initially)

If I change it to use the const ie. priority={CRITICAL}

then I get

`ReferenceError: CRITICAL is not defined`, the same for the similar review issue in #479 

What am I doing wrong? Btw, I will delete the test.js file as it is not needed yet, as the snapshots test the story files. The same issue applies to the storybook file though - if I change priority to take a constant in the story file then it fails. It passes everything if I don't, which is weird isn't it?




</blockquote></details>

I think you will need to export const from RejectTranslationModal, import them here and use it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/479)*

**Comment by kathryngo** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.test.js, line 13 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/479#-KsH9u17iUt8oOo_CAcY:-KsHGADqqGNlMH8ejlBh:bz685y2) ([raw file](https://github.com/zanata/zanata-platform/blob/7596dfcf4b3ef1d91350f77b45d775c7f643a1fd/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.test.js#L13)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

I think you will need to export const from RejectTranslationModal, import them here and use it. 
</blockquote></details>

how do you export and import? can you think of a file off your head that provides an example?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/479)*

**Comment by kathryngo** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.test.js, line 13 at r6](https://reviewable.io:443/reviews/zanata/zanata-platform/479#-KsH9u17iUt8oOo_CAcY:-KsHPXkw4MYyCOc7Rymq:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/7596dfcf4b3ef1d91350f77b45d775c7f643a1fd/server/zanata-frontend/src/frontend/app/editor/components/RejectTranslationModal/RejectTranslationModal.test.js#L13)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

how do you export and import? can you think of a file off your head that provides an example?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/479)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/479#-:-KsHQCIZdjfO1c4HWtXd:bnfp4nl)*

**Pull request merged**
