### PR TITLE
Trans Memory Merge for a single document

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1705

Now TM merge will operate on a single document for a single language. This will happen asynchronously on the server.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/228)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 40 of 51 files at r1, 1 of 2 files at r2.
Review status: 40 of 52 files reviewed at latest revision, 14 unresolved discussions.

---

*[server/gwt-editor/codeserver.sh, line 4 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepbK-Zbm2BiGweYW1y:-KepbK-Zbm2BiGweYW1z:b-klu3ny) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/codeserver.sh#L4)):*
> ```Shell
> 
> mvn clean org.codehaus.mojo:gwt-maven-plugin:run-codeserver -Dchrome
> ```

This file is needed for?

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeProgressEvent.java, line 2 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepbs3ztcEhPTb66qln:-Kepbs3ztcEhPTb66qlo:b-8k88p6) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeProgressEvent.java#L2)):*
> ```Java
> /*
>  * Copyright 2016, Red Hat, Inc. and individual contributors
> ```

2017?

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeProgressEvent.java, line 28 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepc00DpeEmF4hBU-tM:-Kepc00DpeEmF4hBU-tN:b-br6ikq) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeProgressEvent.java#L28)):*
> ```Java
> import com.google.gwt.event.shared.GwtEvent;
> 
> /**
> ```

Perhaps simple comment on what this is used for.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeStartOrEndEvent.java, line 29 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepc7qu3vE8mPz5Mgo7:-Kepc7qu3vE8mPz5Mgo8:b-8om8fh) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeStartOrEndEvent.java#L29)):*
> ```Java
> 
> import com.google.gwt.event.shared.GwtEvent;
> ```

Comment on what this is used for.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/TransMemoryMergePresenter.java, line 228 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepdB4e-dU6wyUSarlw:-KepdB4e-dU6wyUSarlx:b-w3fj73) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/TransMemoryMergePresenter.java#L228)):*
> ```Java
> 
>     private void handleEventFromOtherUser(TMMergeStartOrEndEvent event) {
>         if (!event.isEnded()) {
> ```

If TMMerge process is started/end by another user, will the rest of the users in the workspace received any notification? and they cant trigger another TMMerge?

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/auth/EditorClientId.java, line 21 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepe51yOpxmXjzd5lwU:-Kepe51yOpxmXjzd5lwV:b-38ahzl) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/auth/EditorClientId.java#L21)):*
> ```Java
> 
>     @SuppressWarnings("unused")
>     public EditorClientId() {
> ```

If empty constructor is being used, then the comment above it is incorrect.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/DocumentId.java, line 20 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepeKCGPQLH-K-Qai7R:-KepeKCGPQLH-K-Qai7S:bkmfij2) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/DocumentId.java#L20)):*
> ```Java
>     // for GWT
>     @SuppressWarnings("unused")
>     public DocumentId() {
> ```

If empty constructor is being used, the comment above it is incorrect.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/DocumentId.java, line 30 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepeIM3IkR2l8p3hiFc:-KepeIM4PewDYrnwLkd2:b-lifxpu) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/DocumentId.java#L30)):*
> ```Java
>     @Override
>     public String toString() {
> //        return id + SEPARATOR + docId;
> ```

remove not used comment.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/ProjectIterationId.java, line 15 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepeQ8Ut9FKbodptN3_:-KepeQ8Ut9FKbodptN3a:b-um7pgl) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/ProjectIterationId.java#L15)):*
> ```Java
>     // for GWT
>     @SuppressWarnings("unused")
>     public ProjectIterationId() {
> ```

If this is used, then comment above is incorrect.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rest/TransMemoryMergeResource.java, line 40 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepeayluVCt_B1OsTiD:-KepeayluVCt_B1OsTiE:b-otsibz) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rest/TransMemoryMergeResource.java#L40)):*
> ```Java
>     @Path(TMMERGE_PATH + "/cancel")
>     void cancelMerge(TransMemoryMergeCancelRequest request);
> }
> ```

Do we have endpoint to check status too?

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/TransMemoryMergeStartOrEnd.java, line 33 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepfJVXlZnCd7MuvW5g:-KepfJVXlZnCd7MuvW5h:b9063wv) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/TransMemoryMergeStartOrEnd.java#L33)):*
> ```Java
>  *         <a href="mailto:pahuang@redhat.com">pahuang@redhat.com</a>
>  */
> public class TransMemoryMergeStartOrEnd implements SessionEventData {
> ```

How we know if this object represents start or end of the process?

---

*[server/zanata-model/src/main/java/org/zanata/model/HLocale.kt, line 167 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepfWExG3jqNO4eVy11:-KepfWExG3jqNO4eVy12:b80vr15) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/zanata-model/src/main/java/org/zanata/model/HLocale.kt#L167)):*
> ```Kotlin
>     }
> 
> //    override fun toString(): String {
> ```

Any reason commenting this out?

---

*[server/zanata-war/src/main/java/org/zanata/dao/TextFlowDAO.java, line 355 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepg4dhU3P_bcRfALoY:-Kepg4dibMoHGu0UEGzy:bq8ambg) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/zanata-war/src/main/java/org/zanata/dao/TextFlowDAO.java#L355)):*
> ```Java
>         String queryString =
>                 "select count(*) from HTextFlow tf left join " +
>                         "tf.targets tfts WITH tfts.index=:locale" +
> ```

tfts.index = locale?

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/TransMemoryMergeServiceImpl.java, line 138 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepi7-OCVuBTergoV5J:-Kepi7-OCVuBTergoV5K:buoipvb) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/zanata-war/src/main/java/org/zanata/service/impl/TransMemoryMergeServiceImpl.java#L138)):*
> ```Java
>                     .getUntranslatedTextFlowCount(request.documentId, targetLocale);
> 
>             if (total > 0) {
> ```

if total <= 0, can we just skip the rest of the process? even the asyncTaskHandle.set* or return statement here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/228)*

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r2, 3 of 5 files at r3.
Review status: 42 of 51 files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/228)*

**Comment by huangp** [comment]
Review status: 42 of 52 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[server/gwt-editor/codeserver.sh, line 4 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepbK-Zbm2BiGweYW1y:-Kepm1t6BvMdwcrWAVlY:bcj4c39) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/codeserver.sh#L4)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

This file is needed for?
</blockquote></details>

running gwt code-server so that you don't have to recompile and redeploy

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeProgressEvent.java, line 2 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepbs3ztcEhPTb66qln:-KepmT-sTt4BSX3-kc5N:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeProgressEvent.java#L2)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

2017?
</blockquote></details>

Done.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeProgressEvent.java, line 28 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepc00DpeEmF4hBU-tM:-KepmTl_3Am4h-lZykXL:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeProgressEvent.java#L28)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Perhaps simple comment on what this is used for.
</blockquote></details>

Done.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeStartOrEndEvent.java, line 29 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepc7qu3vE8mPz5Mgo7:-KepmnFE0pP4cTOgsOnr:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TMMergeStartOrEndEvent.java#L29)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Comment on what this is used for.
</blockquote></details>

Done.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/TransMemoryMergePresenter.java, line 228 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepdB4e-dU6wyUSarlw:-KepmrBynEg3sZXU63SV:b7365li) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/TransMemoryMergePresenter.java#L228)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

If TMMerge process is started/end by another user, will the rest of the users in the workspace received any notification? and they cant trigger another TMMerge?
</blockquote></details>

They will receive notification. If they try to trigger another TM merge, the server will reject it. Only one async task for a single document and locale can exists at a time.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/auth/EditorClientId.java, line 21 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepe51yOpxmXjzd5lwU:-KepnAnl3FGb2Tu1pQpP:b-34b7m3) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/auth/EditorClientId.java#L21)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

If empty constructor is being used, then the comment above it is incorrect.
</blockquote></details>

It's not being used. Only used by GWT RPC or REST marshalling

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/DocumentId.java, line 20 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepeKCGPQLH-K-Qai7R:-KepnGWRX9-IHhE670EC:b-34b7m3) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/DocumentId.java#L20)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

If empty constructor is being used, the comment above it is incorrect.
</blockquote></details>

It's not being used. Only used by GWT RPC or REST marshalling

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/DocumentId.java, line 30 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepeIM3IkR2l8p3hiFc:-KepnXrGorJEdoIrWcg2:bi6c7vg) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/DocumentId.java#L30)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

remove not used comment.
</blockquote></details>

I was trying to debug something. Will revert.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/ProjectIterationId.java, line 15 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepeQ8Ut9FKbodptN3_:-Kepndysq5NFLwn6WFkh:b-34b7m3) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/ProjectIterationId.java#L15)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

If this is used, then comment above is incorrect.
</blockquote></details>

It's not being used. Only used by GWT RPC or REST marshalling

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rest/TransMemoryMergeResource.java, line 40 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepeayluVCt_B1OsTiD:-KepngjE2ot2RmdN3r5z:bc8cx5l) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rest/TransMemoryMergeResource.java#L40)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we have endpoint to check status too?
</blockquote></details>

No. The client will receive progress. Admin can go to process manager to see the status. We use event service to push notification down to client so no need to have an endpoint for polling result/status.

---

*[server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/TransMemoryMergeStartOrEnd.java, line 33 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepfJVXlZnCd7MuvW5g:-KepnwchUspSP5LNzACu:b-vwzmsw) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/TransMemoryMergeStartOrEnd.java#L33)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

How we know if this object represents start or end of the process?
</blockquote></details>

I tried to cut down the number of events in event service. If endTIme is null, then it's not end state. There is a method for it.

---

*[server/zanata-war/src/main/java/org/zanata/dao/TextFlowDAO.java, line 355 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepg4dhU3P_bcRfALoY:-KepoKgT4l5Y2nHb5TRt:b-opmz2p) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/zanata-war/src/main/java/org/zanata/dao/TextFlowDAO.java#L355)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

tfts.index = locale?
</blockquote></details>

yes. tfts is the targets map. This is the syntax to access the key of the map.

---

*[server/zanata-war/src/main/java/org/zanata/service/impl/TransMemoryMergeServiceImpl.java, line 138 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-Kepi7-OCVuBTergoV5J:-KeppBGSF7DP6rHJF1OX:b8tb8m5) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/zanata-war/src/main/java/org/zanata/service/impl/TransMemoryMergeServiceImpl.java#L138)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

if total <= 0, can we just skip the rest of the process? even the asyncTaskHandle.set* or return statement here.
</blockquote></details>

At this point the async process has already started on the server. So we should let user/admin know what this async task is about. However I do discover an issue here, I should publish the event regardless the total size. 

---

*[server/zanata-model/src/main/java/org/zanata/model/HLocale.kt, line 167 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KepfWExG3jqNO4eVy11:-Kepo7AZD1CwDnOHMhxn:bv246n6) ([raw file](https://github.com/zanata/zanata-platform/blob/24019b340a9472693693f2a15591749c19343c00/server/zanata-model/src/main/java/org/zanata/model/HLocale.kt#L167)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Any reason commenting this out?
</blockquote></details>

Was trying to debug an issue with mockito mock set up. Will revert.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/228)*

**Comment by aeng** [comment]
Reviewed 6 of 51 files at r1, 2 of 5 files at r3, 1 of 1 files at r4.
Review status: 51 of 52 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/gwt-editor/codeserver.sh, line 2 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KeqHMxldRA737H73YP4:-KeqHMxldRA737H73YP5:bj64ocs) ([raw file](https://github.com/zanata/zanata-platform/blob/3458f151c17fced8b9f400a92798a2475ac20d5a/server/gwt-editor/codeserver.sh#L2)):*
> ```Shell
> #!/bin/bash
> ```

Maybe some comment on how this file is being use would be nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/228)*

**Comment by huangp** [comment]
Review status: 51 of 52 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/gwt-editor/codeserver.sh, line 2 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-KeqHMxldRA737H73YP4:-KeqVyATs-RreLRMChiy:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/3458f151c17fced8b9f400a92798a2475ac20d5a/server/gwt-editor/codeserver.sh#L2)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Maybe some comment on how this file is being use would be nice.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/228)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/228#-:-KeqWAW8xBWcZgduUnLU:bnfp4nl)*

**Comment by spathare21** [comment]
Hi ,

After clicking on TM Merge , pop-up comes with TM merge started but TM Merge action taking too long to merge the translation, and if we try to cancel the merge it shows failed to cancel. and unabvle to move from pop-up page.

auto-fill-pop-up

Click on proceed to autofill without clicking on any checkbox.

tm_merge


Also if we check all checkboxes of copy as fuzzy and proceed to autofill the autofill TM pop-up with TM Marge Started message didn't vanish.  even the TM copied.

screenshot from 2017-03-10 12-09-15

**Comment by huangp** [comment]
@spathare21 try again now

**Comment by spathare21** [comment]
Verified it works fine now

**Comment by huangp** [comment]
@spathare21 sorry the build failed. I need to change the code. May need to re-test this.

**Comment by spathare21** [comment]
@huangp is it ready to test ?

**Comment by spathare21** [comment]
@huangp , verified all things mention in issue notes are working fine. but according to the issue title merging action to be applied to whole documents in a single language, for that i have uploaded single document with two different name and performed merge action but seems that merge action applied to the only one document. 

let me know if I am assuming wrong.

**Comment by huangp** [comment]
@spathare21 it is supposed to work on only one document at a time, which is the one you are viewing in the editor. So it's working as expected.

**Comment by spathare21** [comment]
ok thanks @huangp.

**Pull request merged**
