### PR TITLE
Avoid direct dependency on Nashorn classes

### PR DESCRIPTION
**Pull request by seanf**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/553)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/services/src/test/java/org/zanata/util/CommonMarkRendererTest.java, line 52 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/553#-KvyMmGWiiLYOmwTDsa_:-KvyMmGWiiLYOmwTDsaa:ba0plsw) ([raw file](https://github.com/zanata/zanata-platform/blob/658ec069b089ee9710d383c2ce00a2b1f8c71853/server/services/src/test/java/org/zanata/util/CommonMarkRendererTest.java#L52)):*
> ```Java
>     @Test
>     // 10,000 iterations should run in a few seconds
>     // if you reuse the ScriptEngine and CompiledScript correctly
> ```

This comment is irrelevant anymore?

---

*[server/services/src/test/java/org/zanata/util/CommonMarkRendererTest.java, line 65 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/553#-KvyNAwNqqC3UXyFk0KH:-KvyNAwOJvGCTk80IlnN:b1co6c7) ([raw file](https://github.com/zanata/zanata-platform/blob/658ec069b089ee9710d383c2ce00a2b1f8c71853/server/services/src/test/java/org/zanata/util/CommonMarkRendererTest.java#L65)):*
> ```Java
>         String expected = "<p>This text contains an <em>unsafe</em> <script>script</script> element.</p>\n";
> 
>         // 10,000 iterations should run in a few seconds
> ```

10,000 iterations or just 100?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/553)*

**Comment by seanf** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/services/src/test/java/org/zanata/util/CommonMarkRendererTest.java, line 52 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/553#-KvyMmGWiiLYOmwTDsa_:-KvypMKk85ZDWmnrZQ1S:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/658ec069b089ee9710d383c2ce00a2b1f8c71853/server/services/src/test/java/org/zanata/util/CommonMarkRendererTest.java#L52)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

This comment is irrelevant anymore?
</blockquote></details>

Done.

---

*[server/services/src/test/java/org/zanata/util/CommonMarkRendererTest.java, line 65 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/553#-KvyNAwNqqC3UXyFk0KH:-KvypNRrD_DaWHPyA-_i:btr1ki8) ([raw file](https://github.com/zanata/zanata-platform/blob/658ec069b089ee9710d383c2ce00a2b1f8c71853/server/services/src/test/java/org/zanata/util/CommonMarkRendererTest.java#L65)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

10,000 iterations or just 100?
</blockquote></details>

Updated comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/553)*

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/553#-:-Kvz5uOQA2lMOhqM9E1i:b9a2vem)*

**Comment by seanf** [comment]
@huangp Argh. I forgot the No_QA label again.

**Comment by seanf** [comment]
@huangp thanks

**Pull request merged**
