### PR TITLE
ZNTA 1476 use jbosscli script for arquillian and functional test

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1476

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/305)

### CODE REVIEW

**Comment by seanf** [comment]
Looks like we need to ignore codecov again, since the .java files haven't even been changed.

---

Reviewed 8 of 12 files at r1, 2 of 2 files at r2.
Review status: 10 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[server/etc/scripts/runJbossCli.groovy, line 8 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfiqJPXBPoRXXtvmSk:-KjfiqJPXBPoRXXtvmSl:b-oo7cwi) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/runJbossCli.groovy#L8)):*
> ```Groovy
> 
> /*
>  * Copyright 2016, Red Hat, Inc. and individual contributors
> ```

Time to update that template!

---

*[server/etc/scripts/runJbossCli.groovy, line 53 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-Kjfk67NbL-nVyeFq6wJ:-Kjfk67NbL-nVyeFq6wK:b-hm4vr9) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/runJbossCli.groovy#L53)):*
> ```Groovy
> Files.setPosixFilePermissions(jbossCLI.toPath(), permissions)
> 
> runJBossCLI(jbossCLI, funcTestCLIScript)
> ```

It seems like we run this script both for Arquillian and functional tests. Perhaps it should be zanata-config-test-common.cli?

---

*[server/etc/scripts/runJbossCli.groovy, line 68 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfkXGSVKrBk_iLqh3e:-KjfkXGT2ifyXQkyvsM-:b-dr8xtz) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/runJbossCli.groovy#L68)):*
> ```Groovy
>     proc.consumeProcessOutput(sout, serr)
> // give it 30 seconds
>     proc.waitForOrKill(30000)
> ```

Can we detect the "kill" case? Better to abort the build if that happens.

---

*[server/etc/scripts/zanata-config-arq-test.cli, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfklVXHRr2EHLsw_7w:-KjfklVXHRr2EHLsw_7x:b-501bkh) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-arq-test.cli#L1)):*
> ```
> # in addition to functional test cli script, this will add a h2 datasource
> ```

We should be able to have a single CLI script if we use if-else and pass in system properties (`--properties=/path/to/file.properties`).

---

*[server/etc/scripts/zanata-config-func-test.cli, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfmeDD2ulFltJ0CHjz:-KjfmeDD2ulFltJ0CHk-:b-udntgv) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-func-test.cli#L1)):*
> ```
> # run jboss-cli.sh --file=<location of this file> to apply messaging changes
> ```

Is this comment still relevant? Looks like it was copied from elsewhere.

---

*[server/etc/scripts/zanata-config-func-test.cli, line 25 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfnbwUGX8OLTskEwui:-KjfnbwUGX8OLTskEwuj:bpq58py) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-func-test.cli#L25)):*
> ```
> # ==== cached connection manager ====
> /subsystem=jca/cached-connection-manager=cached-connection-manager/:write-attribute(name=debug,value=true)
> /subsystem=jca/cached-connection-manager=cached-connection-manager/:write-attribute(name=error,value=true)
> ```

Could you please add a comment here? 

    we don't want error=true in production, but we use it here to help catch connection leaks during tests.

---

*[server/etc/scripts/zanata-config-func-test.cli, line 30 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfnpIWVaFTcTEFrqup:-KjfnpIWVaFTcTEFrquq:b-ilt9g8) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-func-test.cli#L30)):*
> ```
> # /subsystem=logging/logger=LOG_CATEGORY:add
> # /subsystem=logging/logger=LOG_CATEGORY:write-attribute(name=level,value=DEBUG)
> # /subsystem=logging/logger=LOG_CATEGORY:write-attribute(name=filter-spec, value=FILTER_EXPRESSION)
> ```

Can you remember what this is for? I can't find it in https://github.com/zanata/zanata-platform/blob/71967367143a34a67691760c158b4f6d94f5912f/server/functional-test/src/test/conf/standalone.xml#L97

---

*[server/etc/scripts/zanata-config-func-test.cli, line 64 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfoVgNoFjYDgPtgLJs:-KjfoVgOgFD_lh0nKPz9:bezutay) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-func-test.cli#L64)):*
> ```
> /subsystem=logging/logger=org.hibernate.type.descriptor.sql:write-attribute(name=level,value=TRACE)
> /subsystem=logging/logger=jboss.jdbc.spy:add
> /subsystem=logging/logger=jboss.jdbc.spy:write-attribute(name=level,value=TRACE)
> ```

I think the hibernate/jdbc logging had been disabled: https://github.com/zanata/zanata-platform/blob/71967367143a34a67691760c158b4f6d94f5912f/server/functional-test/src/test/conf/standalone.xml#L158

Perhaps we should keep them, but comment them out.

---

*[server/etc/scripts/zanata-config-func-test.cli, line 94 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfqTceXZRvAstEI5SM:-KjfqTceXZRvAstEI5SN:bi9gkh2) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-func-test.cli#L94)):*
> ```
> 
> # ==== mail session ====
> /socket-binding-group=standard-sockets/remote-destination-outbound-socket-binding=mail-smtp:write-attribute(name="port", value=${smtp.port,env.SMTP_PORT:2552})
> ```

What's the implication of switching from @smtp.port@ to env.SMTP_PORT? Does that affect the functional tests for email?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-:-KjfmFRBddGUgK3tUkp8:b-ppis05)*

**Comment by huangp** [comment]
Review status: 10 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[server/etc/scripts/runJbossCli.groovy, line 8 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfiqJPXBPoRXXtvmSk:-KjfsuHaVJcbxbrDbALA:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/runJbossCli.groovy#L8)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Time to update that template!
</blockquote></details>

Done.

---

*[server/etc/scripts/runJbossCli.groovy, line 53 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-Kjfk67NbL-nVyeFq6wJ:-Kjfy-LxHdYmK5_bWhVz:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/runJbossCli.groovy#L53)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

It seems like we run this script both for Arquillian and functional tests. Perhaps it should be zanata-config-test-common.cli?
</blockquote></details>

Done.

---

*[server/etc/scripts/runJbossCli.groovy, line 68 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfkXGSVKrBk_iLqh3e:-KjfuhQWFgQqURvgFK9a:b6v4shz) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/runJbossCli.groovy#L68)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Can we detect the "kill" case? Better to abort the build if that happens.
</blockquote></details>

The method itself return void. I can only check the exit code. Not sure if killing a process will cause a non-zero exit code though. Looks like not https://unix.stackexchange.com/questions/99112/default-exit-code-when-process-is-terminated 
The build will fail a little later when it tries to start the app server. 

---

*[server/etc/scripts/zanata-config-arq-test.cli, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfklVXHRr2EHLsw_7w:-KjfvvlMBgD_UQXrlu_V:blsb9mw) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-arq-test.cli#L1)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should be able to have a single CLI script if we use if-else and pass in system properties (`--properties=/path/to/file.properties`).
</blockquote></details>

If-else flow is not allowed in batch mode. I think this is more complicated than having 2 scripts.

---

*[server/etc/scripts/zanata-config-func-test.cli, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfmeDD2ulFltJ0CHjz:-Kjfwr0Rdwo4-17L3SI8:bcnkt0) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-func-test.cli#L1)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Is this comment still relevant? Looks like it was copied from elsewhere.
</blockquote></details>

Yes will remove

---

*[server/etc/scripts/zanata-config-func-test.cli, line 25 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfnbwUGX8OLTskEwui:-Kjfx0H2ciRf2NLn8Asg:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-func-test.cli#L25)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Could you please add a comment here? 

    we don't want error=true in production, but we use it here to help catch connection leaks during tests.
</blockquote></details>

Done.

---

*[server/etc/scripts/zanata-config-func-test.cli, line 30 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfnpIWVaFTcTEFrqup:-Kjfx8yMh-govAFm7_85:bcq64f1) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-func-test.cli#L30)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Can you remember what this is for? I can't find it in https://github.com/zanata/zanata-platform/blob/71967367143a34a67691760c158b4f6d94f5912f/server/functional-test/src/test/conf/standalone.xml#L97
</blockquote></details>

This is just comment (like a template). I use it to add new logging configuration.

---

*[server/etc/scripts/zanata-config-func-test.cli, line 64 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfoVgNoFjYDgPtgLJs:-KjfxaUmuGINXNmBQez-:b-rc11yw) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-func-test.cli#L64)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I think the hibernate/jdbc logging had been disabled: https://github.com/zanata/zanata-platform/blob/71967367143a34a67691760c158b4f6d94f5912f/server/functional-test/src/test/conf/standalone.xml#L158

Perhaps we should keep them, but comment them out.
</blockquote></details>

It's in master branch: https://github.com/zanata/zanata-platform/blob/master/server/functional-test/src/test/conf/standalone.xml

---

*[server/etc/scripts/zanata-config-func-test.cli, line 94 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfqTceXZRvAstEI5SM:-KjfxgXUxZmJPMLVbLAP:byid2o9) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-func-test.cli#L94)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

What's the implication of switching from @smtp.port@ to env.SMTP_PORT? Does that affect the functional tests for email?
</blockquote></details>

We were using maven to filter the files (hence @smtp.port@). I have changed it to use the same trick as other port (allocate-jboss-ports and then a profile to set env)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/305)*

**Comment by seanf** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/etc/scripts/runJbossCli.groovy, line 68 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfkXGSVKrBk_iLqh3e:-Kjg0fIfaxpzjFNT6vUS:b-w2czyn) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/runJbossCli.groovy#L68)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

The method itself return void. I can only check the exit code. Not sure if killing a process will cause a non-zero exit code though. Looks like not https://unix.stackexchange.com/questions/99112/default-exit-code-when-process-is-terminated 
The build will fail a little later when it tries to start the app server. 
</blockquote></details>

That StackExchange question was really about the result of `killall` being zero. Based on the answers, I think checking the exit code should work for us. 

---

*[server/etc/scripts/zanata-config-arq-test.cli, line 1 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfklVXHRr2EHLsw_7w:-Kjg39RWXYJy57NWS9-a:b38798y) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-arq-test.cli#L1)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

If-else flow is not allowed in batch mode. I think this is more complicated than having 2 scripts.
</blockquote></details>

Wow, no if-else in batches, and no nesting either? https://developer.jboss.org/wiki/If-elseControlFlow

I almost wonder if we'd be better off with https://developer.jboss.org/wiki/AdvancedCLIScriptingWithGroovyRhinoJythonEtc but then we'd probably find embedded mode doesn't work or something.

You're right, let's stick to this, for now at least.

---

*[server/etc/scripts/zanata-config-test-common.cli, line 64 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfoVgNoFjYDgPtgLJs:-Kjg1O4Bc1mk7KJQl9cA:b1zdl1) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-test-common.cli#L64)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

It's in master branch: https://github.com/zanata/zanata-platform/blob/master/server/functional-test/src/test/conf/standalone.xml
</blockquote></details>

You're right, I should have scrolled up. (I was thinking of https://github.com/zanata/zanata-platform/commit/ed3c38535f07a96090afd06af71b4c6ed9b383dd).  But I suggest we disable them anyway (they don't exist in production or Docker config). 

I haven't looked at those log entries in years, have you? Getting rid of them should speed up the tests a bit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/305)*

**Comment by huangp** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/etc/scripts/zanata-config-test-common.cli, line 64 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-KjfoVgNoFjYDgPtgLJs:-KjjZCxaRf56PxTKo_Gw:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/e6301068f4a37e5802881a142bad6d9508bfef73/server/etc/scripts/zanata-config-test-common.cli#L64)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

You're right, I should have scrolled up. (I was thinking of https://github.com/zanata/zanata-platform/commit/ed3c38535f07a96090afd06af71b4c6ed9b383dd).  But I suggest we disable them anyway (they don't exist in production or Docker config). 

I haven't looked at those log entries in years, have you? Getting rid of them should speed up the tests a bit.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/305)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/305#-:-KjjjZ3Ome3ag2nhktI-:bnfp4nl)*

**Pull request merged**
