### PR TITLE
fix(ZNTA-2341) add top spacing to editor search

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2341

* Added spacing above alpha editor suggestions search
* Removed the duplicate 'x' that closes the suggestions search
* Updated tests

I had to start again on a clean branch from release after all those release changes were made yesterday so it will need a second review. 

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/666)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/666#-:-L36YwEhVaa_57DUUUqm:bnfp4nl)*

**Comment by spathare21** [comment]
@kathryngo I see there are 2 cross buttons in search box is it required ?

screenshot from 2018-01-18 11-05-20

**Comment by kathryngo** [comment]
@spathare21 pretty sure the first one clears your input and the second closes the search box, but I will confirm this in a minute.

**Comment by spathare21** [comment]
@kathryngo both does the same work

**Comment by kathryngo** [comment]
@spathare21 just noticed that. I will remove the one on the right as part of this PR.

**Comment by huangp** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/666#-:-L3AjGzo_8fdiROpekZ3:bnfp4nl)*

**Pull request merged**
