### PR TITLE
style(ZNTA-2330): Fix classname for style highlighting in editor

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2330

Small stylefix for the highlighting in the editor, classname was not applying

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/659)

### CODE REVIEW

**Comment by kathryngo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/659#-:-L2clRTc4b1jYCR9H0ha:bnfp4nl)*

**Comment by efloden** [comment]
@aeng this one should be okay to merge into master?

**Comment by aeng** [comment]
@efloden check the failed jenkins job.

**Comment by efloden** [comment]
@aeng looks like the build has passed: https://zanata-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/github-zanata-org/job/zanata-platform/view/change-requests/job/PR-659/

**Pull request merged**
