### PR TITLE
fix(ZNTA-1940) added suggestions loader 

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1940

- added suggestions loader in editor (using LoaderText component in frontend)
- and made minor css fixes to translation panel loaders (left padding)
- also made changes to height of h1 in frontend to handle bottom-border on all pages

suggloader

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/367)

### CODE REVIEW

**Comment by kathryngo** [comment]
Going to try and fix test coverage

**Comment by davidmason** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js, line 12 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KlusOfJXdl3inbHyVV7:-KlusOfJXdl3inbHyVV8:b-2vsxjm) ([raw file](https://github.com/zanata/zanata-platform/blob/1fd45fdc06b9420cad32ace27071b5eed31e3b56/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js#L12)):*
> ```JavaScript
>     const actual = ReactDOMServer.renderToStaticMarkup(
>       <NoSuggestionsPanel
>         message="You are going to have to wait"
> ```

Why are you messing up my Predator quotes here? That doesn't seem necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by davidmason** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/SuggestionsBody.js, line 53 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KluskRJwvuo7FyIKyml:-KluskRJwvuo7FyIKymm:b2r47dp) ([raw file](https://github.com/zanata/zanata-platform/blob/1fd45fdc06b9420cad32ace27071b5eed31e3b56/server/zanata-frontend/src/frontend/app/editor/containers/SuggestionsBody.js#L53)):*
> ```JavaScript
>             </div>
>           </div>
>         </div>
> ```

It looks like you've copy-pasted the `NoSuggestionsPanel` component right in here. Make a component instead, but since it is mostly duplicated it could possibly just be another state of `NoSuggestionsPanel`.

You can just use a `LoaderText` in that component when `this.props.icon === 'loader` - no one needs to know how that is implemented under the hood.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by davidmason** [comment]
Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js, line 11 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KluuQBl7Lir2JgWB-xD:-KluuQBmZS5ZM8OQGhDo:b-vhn42p) ([raw file](https://github.com/zanata/zanata-platform/blob/5ce02141845752ca3bc0073a1a3248d7213c4b32/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js#L11)):*
> ```JavaScript
>   static propTypes = {
>     message: PropTypes.string.isRequired,
>     icon: PropTypes.oneOf(['loader', 'search', 'suggestions']).isRequired
> ```

This change should be reversed as part of the other changes mentioned below.

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js, line 13 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-Kluu8Ch95k5bC2XnlqV:-Kluu8Ch95k5bC2XnlqW:b-fgo6np) ([raw file](https://github.com/zanata/zanata-platform/blob/1fd45fdc06b9420cad32ace27071b5eed31e3b56/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js#L13)):*
> ```JavaScript
>       <NoSuggestionsPanel
>         message="You are going to have to wait"
>         icon="search"/>
> ```

We should keep the external interface of this component the same (i.e. still have `props.icon`), and just have it do different stuff internally when someone asks for `icon='loader'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js, line 12 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KlusOfJXdl3inbHyVV7:-Klv-6uAIzKA7XcoTYdI:b-8wsva7) ([raw file](https://github.com/zanata/zanata-platform/blob/1fd45fdc06b9420cad32ace27071b5eed31e3b56/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js#L12)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Why are you messing up my Predator quotes here? That doesn't seem necessary.
</blockquote></details>

Sorry, never again!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by kathryngo** [comment]
Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js, line 11 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KluuQBl7Lir2JgWB-xD:-KlvPVvQLTqXgF6LzU8b:b-886gsx) ([raw file](https://github.com/zanata/zanata-platform/blob/5ce02141845752ca3bc0073a1a3248d7213c4b32/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js#L11)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

This change should be reversed as part of the other changes mentioned below.
</blockquote></details>

Fixed

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js, line 13 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-Kluu8Ch95k5bC2XnlqV:-KlvP_kB8XIszQ1nTS-4:b-886gsx) ([raw file](https://github.com/zanata/zanata-platform/blob/1fd45fdc06b9420cad32ace27071b5eed31e3b56/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js#L13)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

We should keep the external interface of this component the same (i.e. still have `props.icon`), and just have it do different stuff internally when someone asks for `icon='loader'`
</blockquote></details>

Fixed

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js, line 18 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KlvPmli8STOABpHeZ0F:-KlvPmli8STOABpHeZ0G:brd2xzb) ([raw file](https://github.com/zanata/zanata-platform/blob/611a798a1cedbc3c08643bfe9b3c99c3d3f7d5cc/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js#L18)):*
> ```JavaScript
>     const expected = ReactDOMServer.renderToStaticMarkup(
>       <div
>         className="u-posCenterCenter u-textEmpty u-textCenter">
> ```

Had to include classes because the wrapperClasses thingy didn't work

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js, line 19 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KlvRokpV1A45GyF97JR:-KlvRokpV1A45GyF97JS:b-smjo2n) ([raw file](https://github.com/zanata/zanata-platform/blob/9f4cc630c485d666284490add81378d835c71a10/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js#L19)):*
> ```JavaScript
>       <div
>         className="u-posCenterCenter u-textEmpty u-textCenter">
>         <div className="u-sMB-1-4">
> ```

Tests now pass 

---

*[server/zanata-frontend/src/frontend/app/editor/containers/SuggestionsBody.js, line 53 at r2](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KluskRJwvuo7FyIKyml:-KlvPcHyoTuApl6pS4HU:b-w3qawm) ([raw file](https://github.com/zanata/zanata-platform/blob/1fd45fdc06b9420cad32ace27071b5eed31e3b56/server/zanata-frontend/src/frontend/app/editor/containers/SuggestionsBody.js#L53)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

It looks like you've copy-pasted the `NoSuggestionsPanel` component right in here. Make a component instead, but since it is mostly duplicated it could possibly just be another state of `NoSuggestionsPanel`.

You can just use a `LoaderText` in that component when `this.props.icon === 'loader` - no one needs to know how that is implemented under the hood.
</blockquote></details>

Also fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by davidmason** [comment]
Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js, line 18 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KlvPmli8STOABpHeZ0F:-KlvwmtSiQbp46_uj_1u:bq79wnk) ([raw file](https://github.com/zanata/zanata-platform/blob/611a798a1cedbc3c08643bfe9b3c99c3d3f7d5cc/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js#L18)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Had to include classes because the wrapperClasses thingy didn't work
</blockquote></details>

Probably just because of how I said to put it as `static` and maybe that meant it had to be accessed as `NoSuggestionsPanel.wrapperClasses`. We can still remove the duplicated stuff, just might need to do it a way that works.

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 195 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KlvzaceTtFof7TmEDAT:-KlvzaceTtFof7TmEDAU:bqaflkp) ([raw file](https://github.com/zanata/zanata-platform/blob/9f4cc630c485d666284490add81378d835c71a10/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L195)):*
> ```CSS
>   color:rgb(144, 184, 197);
>   font-weight: 600;
> }
> ```

Do we have a variable for the colour here?

This looks like a pretty narrow edge-case, is it really not covered by our more general styles?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js, line 26 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-Klw0NuzREHNYSgdNIiN:-Klw0NuzREHNYSgdNIiO:b-lvu2ma) ([raw file](https://github.com/zanata/zanata-platform/blob/9f4cc630c485d666284490add81378d835c71a10/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js#L26)):*
> ```JavaScript
>     } else {
>       return (
>         <div className="u-posCenterCenter u-textEmpty u-textCenter">
> ```

There are 2 general ways I can think of:

1. A `const` for the wrapper classes outside the component (instead of a static, so just put it up around line 5 or so).
2. Change back to how it was and make another conditional block for the paragraph. I think this is the better option. It would probably look something like this:

```javascript
    const isLoader = this.props.icon === 'loader'
    const icon = isLoader
      ? <LoaderText loading loadingText={this.props.message} />
      : <Icon name={this.props.icon} className="s5" />
    const messagePara = isLoader
      ? undefined
      : <p>{this.props.message}</p>

    return (
      <div className="u-posCenterCenter u-textEmpty u-textCenter">
        <div className="u-sMB-1-4">
          {icon}
        </div>
        {messagePara}
      </div>
    )
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by kathryngo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js, line 26 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-Klw0NuzREHNYSgdNIiN:-KlwDGSh2CfqSidpAH7D:b-8qqyav) ([raw file](https://github.com/zanata/zanata-platform/blob/9f4cc630c485d666284490add81378d835c71a10/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js#L26)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

There are 2 general ways I can think of:

1. A `const` for the wrapper classes outside the component (instead of a static, so just put it up around line 5 or so).
2. Change back to how it was and make another conditional block for the paragraph. I think this is the better option. It would probably look something like this:

```javascript
    const isLoader = this.props.icon === 'loader'
    const icon = isLoader
      ? <LoaderText loading loadingText={this.props.message} />
      : <Icon name={this.props.icon} className="s5" />
    const messagePara = isLoader
      ? undefined
      : <p>{this.props.message}</p>

    return (
      <div className="u-posCenterCenter u-textEmpty u-textCenter">
        <div className="u-sMB-1-4">
          {icon}
        </div>
        {messagePara}
      </div>
    )
```

</blockquote></details>

No worries, shall give the second option a go first 

---

*[server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, line 195 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KlvzaceTtFof7TmEDAT:-KlwCkdffWdBczJbNjAB:byux16q) ([raw file](https://github.com/zanata/zanata-platform/blob/9f4cc630c485d666284490add81378d835c71a10/server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css#L195)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Do we have a variable for the colour here?

This looks like a pretty narrow edge-case, is it really not covered by our more general styles?
</blockquote></details>

Saw that the equivalent hexcode was used in that css file so I created  a variable for that, alongside some other colours

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by kathryngo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js, line 26 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-Klw0NuzREHNYSgdNIiN:-KlwQmsFJl8lPtqg0Q80:b-dsuw9k) ([raw file](https://github.com/zanata/zanata-platform/blob/9f4cc630c485d666284490add81378d835c71a10/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js#L26)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

No worries, shall give the second option a go first 
</blockquote></details>

Option 2 didn't work even when quadruple checking my syntax. No linting errors. Just would return a blank editor screen with heaps of console errors about stuff not being minified.

So I went with option 1 and it worked!
I added a constant just after the import statements, and that works without the word static. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by kathryngo** [comment]
@davidmason this is ready for you to look at again

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-:-KlwRxDffzQFiBaMj8uZ:b-ro0j65)*

**Comment by kathryngo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js, line 18 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-KlvPmli8STOABpHeZ0F:-KlwTP7YymS-vWikYNRT:b-886gsx) ([raw file](https://github.com/zanata/zanata-platform/blob/611a798a1cedbc3c08643bfe9b3c99c3d3f7d5cc/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js#L18)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

Probably just because of how I said to put it as `static` and maybe that meant it had to be accessed as `NoSuggestionsPanel.wrapperClasses`. We can still remove the duplicated stuff, just might need to do it a way that works.
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by davidmason** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js, line 26 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-Klw0NuzREHNYSgdNIiN:-KlwdBhCJLFJB2x8keQ-:bzc7a69) ([raw file](https://github.com/zanata/zanata-platform/blob/9f4cc630c485d666284490add81378d835c71a10/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js#L26)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Option 2 didn't work even when quadruple checking my syntax. No linting errors. Just would return a blank editor screen with heaps of console errors about stuff not being minified.

So I went with option 1 and it worked!
I added a constant just after the import statements, and that works without the word static. 
</blockquote></details>

That sounds really odd. I would like to see the code and what it compiled like for option 2 - we shouldn't be making code style decisions based on some weird mystery error. Could you push that as a separate branch so I can investigate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by kathryngo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js, line 26 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-Klw0NuzREHNYSgdNIiN:-KlwjekKlXp3tBwQcvx-:buvbc8e) ([raw file](https://github.com/zanata/zanata-platform/blob/9f4cc630c485d666284490add81378d835c71a10/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js#L26)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary><blockquote>

That sounds really odd. I would like to see the code and what it compiled like for option 2 - we shouldn't be making code style decisions based on some weird mystery error. Could you push that as a separate branch so I can investigate?
</blockquote></details>

I got it working in a branch created from this one so I am retrying in this branch.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js, line 26 at r4](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-Klw0NuzREHNYSgdNIiN:-KlwlbFFUtWqxQ3Gwv45:b64ajhq) ([raw file](https://github.com/zanata/zanata-platform/blob/9f4cc630c485d666284490add81378d835c71a10/server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js#L26)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

I got it working in a branch created from this one so I am retrying in this branch.  
</blockquote></details>

And fixed :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367)*

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/367#-:-Km-62rvy2EF8HHDQN89:bnfp4nl)*

**Comment by djansen-redhat** [comment]
✅ verified

**Pull request merged**
