### PR TITLE
feat(ZNTA-1865):version merge modal

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1865

Frontend modal work for Version Merge Modal - made in storybook.

Run `make storybook-frontend`, then in storybook go to Modal -> version-merge.

* The **drag and drop** functionality was implemented using 'react-draggable' and could do with some tidying up (so it works in a nicer fashion if possible). I think this is best handled by someone with more backend experience.  https://github.com/mzabriskie/react-draggable

* The **+ and - arrows** (see mockups in JIRA) were difficult to add for me in this task. Unsure how to do it in es6 or if there is an easy way to show them - react-bootstrap doesn't seem to have functionality to do so. However the fact that one of these boxes is expanded from the outset provides an indicator that these are collapsable/expandable.  I think this is enough. 

- tooltips are provided for the info icon in the adjust priority panel as well as on the locked/read only icon

**Note:**  This modal shows the state when the word Project is searched. 
By default it should:
* show only the current project expanded to show all its versions 
* show the  'merge translations' button as disabled until a version is checked. 
* hide the right hand sort column until a version is checked also. 

vmerge

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/318)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 1 of 4 files at r1, 1 of 2 files at r3.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/package.json, line 109 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/318#-Kk8O_jkQRMasYJwB5aq:-Kk8O_jkQRMasYJwB5ar:b-dytat5) ([raw file](https://github.com/zanata/zanata-platform/blob/3167d3903c96732d812eaaa9e284cdbe2329d98b/server/zanata-frontend/src/frontend/package.json#L109)):*
> ```JSON
>     "react-date-range": "0.2.4",
>     "react-dom": "0.14.8",
>     "react-draggable": "^2.2.6",
> ```

try to use the exact version, removing ^

---

*[server/zanata-frontend/src/frontend/app/styles/style.less, line 2 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/318#-Kk8OnkRUvAH0bqfoD1t:-Kk8OnkRUvAH0bqfoD1u:bgdzbja) ([raw file](https://github.com/zanata/zanata-platform/blob/3167d3903c96732d812eaaa9e284cdbe2329d98b/server/zanata-frontend/src/frontend/app/styles/style.less#L2)):*
> ```Less
> @import "./variables.less";
> @import url('//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css');
> ```

anyway to import/make a copy of this css into the module? trying to avoid 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/318)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/styles/style.less, line 2 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/318#-Kk8OnkRUvAH0bqfoD1t:-Kk8fUIGM4LBlaIBr8t3:b-dza3ek) ([raw file](https://github.com/zanata/zanata-platform/blob/3167d3903c96732d812eaaa9e284cdbe2329d98b/server/zanata-frontend/src/frontend/app/styles/style.less#L2)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

anyway to import/make a copy of this css into the module? trying to avoid 
</blockquote></details>

Isn't needed because bootstrap font-awesome icons are included in frontend already :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/318)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/app/styles/style.less, line 2 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/318#-Kk8OnkRUvAH0bqfoD1t:-Kk8g1WIjb-1BE4Zcbxi:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/3167d3903c96732d812eaaa9e284cdbe2329d98b/server/zanata-frontend/src/frontend/app/styles/style.less#L2)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary><blockquote>

Isn't needed because bootstrap font-awesome icons are included in frontend already :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/318)*

**Comment by kathryngo** [comment]
*[server/zanata-frontend/src/frontend/package.json, line 109 at r3](https://reviewable.io:443/reviews/zanata/zanata-platform/318#-Kk8O_jkQRMasYJwB5aq:-Kk8g3fQ2pXq9pmnsY6w:b-896fix) ([raw file](https://github.com/zanata/zanata-platform/blob/3167d3903c96732d812eaaa9e284cdbe2329d98b/server/zanata-frontend/src/frontend/package.json#L109)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

try to use the exact version, removing ^
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/318)*

**Comment by aeng** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/318)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/318#-:-Kk8hrKFvClUKy1RhKKb:bnfp4nl)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/318#-:-Kk8kpMMH8bvEsRE3ME3:b-ew2adl)*

**Comment by aeng** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/318)*

**Pull request merged**
