### PR TITLE
Upgrade to React 15 (ZNTA-1922)

### PR DESCRIPTION
**Pull request by davidmason**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1922

Upgrade React to 15.5.x and fix all the deprecation errors by upgrading other modules and fixing code.

## Testing notes

- This touches many files in frontend and editor modules, so we need a general check of:
  - /explore
  - /glossary
  - /glossary/project/<project>
  - /languages
  - /profile/view/<user>
  - the React editor
- Changes to the router for frontend and editor module, so make sure page navigation works.
- Updates react-bootstrap and several other React modules, so make sure everything renders properly.
- Upgrades the chart library for the user profile page contribution graph, so that may look slightly different (with approval from @kathryngo )

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/397)

### CODE REVIEW

**Comment by davidmason** [comment]
Review status: 0 of 138 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/frontend/package.json, line 105 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/397#-KmiLSXm3MXN9pVqvZes:-KmiLSXm3MXN9pVqvZet:b-xwa78t) ([raw file](https://github.com/zanata/zanata-platform/blob/715b8c4cdc052df4d9e84d38b0d2a9332daa0982/server/zanata-frontend/src/frontend/package.json#L105)):*
> ```JSON
>     "react-autosuggest": "9.0.1",
>     "react-bootstrap": "0.31.0",
>     "react-chartjs": "https://github.com/merlinpatt/react-chartjs.git#28fda9c04237be533787112263a24e07fe29b0ae",
> ```

I am updating this to use `react-chartjs-2` so this will have a proper officially released version before I merge it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by efloden** [comment]
Reviewed 48 of 138 files at r1.
Review status: 48 of 138 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by efloden** [comment]
Reviewed 89 of 138 files at r1.
Review status: 137 of 138 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by efloden** [comment]
Reviewed 1 of 138 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/middlewares/new-context-fetch.js, line 20 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/397#-KmigdYb_ZoMIh2ET4gT:-KmigdYb_ZoMIh2ET4gU:bmmqh6p) ([raw file](https://github.com/zanata/zanata-platform/blob/715b8c4cdc052df4d9e84d38b0d2a9332daa0982/server/zanata-frontend/src/frontend/app/editor/middlewares/new-context-fetch.js#L20)):*
> ```JavaScript
> const getPageIndexFromQuery = (state) => {
>   return state.routing.locationBeforeTransitions
>     ? state.routing.locationBeforeTransitions.query.page
> ```

Should all routing change to use the routing.locationBeforeTransitions module now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by davidmason** [comment]
Review status: 136 of 138 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/editor/middlewares/new-context-fetch.js, line 20 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/397#-KmigdYb_ZoMIh2ET4gT:-KmihM2ML-dCiJ0tqsOw:b-30krp9) ([raw file](https://github.com/zanata/zanata-platform/blob/715b8c4cdc052df4d9e84d38b0d2a9332daa0982/server/zanata-frontend/src/frontend/app/editor/middlewares/new-context-fetch.js#L20)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Should all routing change to use the routing.locationBeforeTransitions module now?
</blockquote></details>

No, this is just a stopgap to get it working for now. Really I need to change it so it stops using `locationBeforeTransitions` at all, and instead get the location via `props`, but that is a bigger change so I want to do it separately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by efloden** [comment]
Review status: 136 of 138 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Explore/index.js, line 176 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/397#-KmiisVTFruAtOlvqYWp:-KmiisVTFruAtOlvqYWq:bi4qpsi) ([raw file](https://github.com/zanata/zanata-platform/blob/715b8c4cdc052df4d9e84d38b0d2a9332daa0982/server/zanata-frontend/src/frontend/app/containers/Explore/index.js#L176)):*
> ```JavaScript
> const mapStateToProps = (state, { location }) => {
>   const {
>     groupPage, languageTeamPage, personPage, projectPage, q } = location.query
> ```

This is just object destructuring the languages prop to make the code cleaner right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by efloden** [comment]
Reviewed 2 of 138 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by efloden** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397#-:-Kmijqtb6cqLv2n4xClm:bnfp4nl)*

**Comment by kathryngo** [comment]
Reviewed 138 of 138 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by kathryngo** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397#-:-KmikDtQZCAHBtFQ1lBm:bnfp4nl)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/zanata-frontend/src/frontend/app/containers/Explore/index.js, line 176 at r1](https://reviewable.io:443/reviews/zanata/zanata-platform/397#-KmiisVTFruAtOlvqYWp:-KmijyeWekOGAhDge--p:bfyd963) ([raw file](https://github.com/zanata/zanata-platform/blob/715b8c4cdc052df4d9e84d38b0d2a9332daa0982/server/zanata-frontend/src/frontend/app/containers/Explore/index.js#L176)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

This is just object destructuring the languages prop to make the code cleaner right?
</blockquote></details>

There are 2 things happening here. You are exactly right about one of them:  I noticed there was a lot of repeated `state.routing.location.query` just below so I pulled it out.

The other change is that I am getting location.query from `ownProps` now, but I am destructuring `ownProps`. This is because of a change to the router where it is now better to get the location from `props` on the component that is attached to a `Route`.

I could have written it like this:

```
const mapStateToProps = (state, ownProps) => {
  
  const {  
    groupPage, languageTeamPage, personPage, projectPage, q } = ownProps.location.query
```

This is in that diagram in editor/README.md - `state` comes from the redux store, and `ownProps` is the props that were passed to the component as attributes. We usually don't need to look at them so they are left off in most `mapStateToProps` calls - they just get automatically merged into the final props that the component receives.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by kathryngo** [comment]
One issue, the glossary rows aren't inline anymore. Only realised when I checked against master

glossary

**Comment by djansen-redhat** [comment]
🚫 Languages page filter does not work (no activity)

**Comment by djansen-redhat** [comment]
I think I'm losing the dswid on glossary and language pages.

**Comment by davidmason** [comment]
@djansen-redhat that is plausible with the router changes. I'll look into it.

**Comment by davidmason** [comment]
@djansen-redhat to me it looks like master is losing dswid on any page that is part of frontend app. This may be a separate issue (but high priority to fix).

**Comment by djansen-redhat** [comment]
@davidmason turns out it was just the Languages page that causes it, and I checked master with the Glossary page.
Pre-existing in master, will report.

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 7 of 138 files at r1.
Review status: 131 of 138 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397#-:-KmxtbqRqJx1ANb9gnxP:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 2 of 5 files at r2, 3 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by djansen-redhat** [comment]
Added label re graph render oddity

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by aeng** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/397)*

**Comment by djansen-redhat** [comment]
@davidmason looks good

**Pull request merged**
