### PR TITLE
fix(ZNTA-2606): validate duplicate glossary entries

### PR DESCRIPTION
**Pull request by efloden**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2606

Glossary entry allowed duplicate entries to be created.
Validate new glossary entry against existing entries, notify if exact duplicate (matching term, part of speech and description) exists.
glossaryvalidation

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js, line 132 at r1](https://reviewable.io/reviews/zanata/zanata-platform/891#-LEShZlv83hStkKmBqnu:-LEShZlv83hStkKmBqnv:btrag38) ([raw file](https://github.com/zanata/zanata-platform/blob/a3d3b3ea27d0037a86ecbec1696b6e9366ed073a/server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js#L132)):*
> ```JavaScript
>             type='primary'
>             disabled={!isAllowSave || isSaving}
>             onClick={this.handleCreate}>
> ```

Do we still reset the fields after saving?

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/891)*

**Comment by efloden** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js, line 132 at r1](https://reviewable.io/reviews/zanata/zanata-platform/891#-LEShZlv83hStkKmBqnu:-LESlXc51fQJN7ho62Sz:b-fn4x2j) ([raw file](https://github.com/zanata/zanata-platform/blob/a3d3b3ea27d0037a86ecbec1696b6e9366ed073a/server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js#L132)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary><blockquote>

Do we still reset the fields after saving?
</blockquote></details>

Yes, in handlCreate we reset the fields after saving if the validation passes

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/891)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/891#-:-LESllPr-t8qGMmY8Rf0:bnfp4nl)*

**Comment by spathare21** [comment]
@efloden, still I  the same issue, it shows glossary created second time as well with same inputs,
It works only when if i searched the same entry in glossary search and try to create the same one
Also have to ingore the codecov ? 

screenshot from 2018-06-08 11-13-26


screenshot from 2018-06-08 11-13-41


screenshot from 2018-06-08 11-14-15

**Comment by djansen-redhat** [comment]
@efloden an empty description should count as a similar description

**Comment by spathare21** [comment]
@efloden  @djansen-redhat , an empty description should count as a similar description does this means, If I created glossary term with "bar" pos "bar" and desc "bar" and second time i just give term "bar" , pos "bar" and desc empty right? currently, with this process, it creates two glossary entries for bar with desc and without description.

**Comment by spathare21** [comment]
@efloden build failed

**Comment by efloden** [comment]
@spathare21 @djansen-redhat accidentally merged master into this branch out of habit, re-opened as PR https://github.com/zanata/zanata-platform/pull/904
Discussed considering empty descriptions as similar with @aeng and while it can be implemented it would require some data migrations due to existing glossary terms that have empty descriptions, so we might leave it out of this PR

**Pull request closed without merging**
