### PR TITLE
fix: ZNTA-1899 changed '...' in profile to 'to'

### PR DESCRIPTION
**Pull request by spathare21**
JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1899*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/451)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@spathare21 this only changes the range in the dialog button, not in the activity details (which the feedback/bug was actually referring to)

**Comment by djansen-redhat** [comment]
screenshot from 2017-07-27 10-14-03

**Comment by spathare21** [comment]
@djansen-redhat done

**Comment by djansen-redhat** [comment]
@kathryngo just wanted your opinion on this change. It looks good to me, but perhaps could have 'to' italicised to separate it from the variables.

**Comment by kathryngo** [comment]
@djansen-redhat good thinking 99, shall do that now

**Comment by kathryngo** [comment]
@djansen-redhat I wish it was as simple as sticking some em tags in there or a classname but because the 'to' part is a string, any changes I make don't seem to work.
The whole chunk of that text is one class (text-bold-uppercase) so I cannot alter just the 'to' part with css.

**Comment by djansen-redhat** [comment]
No problem @kathryngo - I think this will do for now

**Comment by djansen-redhat** [comment]
✅ Verified
Build 2 id 🆗

**Pull request merged**
