### PR TITLE
test(upgrade jest): upgrade jest version for coverage

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1613

JIRA issue URL: *[paste URL here]*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/115)

### CODE REVIEW

**Comment by huangp** [comment]
Sean asked me before about how to upgrade jest version. He wanted to upgrade jest only not everything. This looks like you upgraded other things in shrinkwrap. 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/115#-:-KZTpR1uOlzxJW0fik5s:b-dmk4d9)*

**Comment by aeng** [comment]
We should wait for https://zanata.atlassian.net/browse/ZNTA-1555 before upgrading this. Yarn has better management for locking down dependency version.

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/115#-:-K_mOuCtUOSpYYfTEsb_:b49ms4)*

**Comment by aeng** [comment]
Issue with test in editor, relative path in zanata-ui causing Illegal character in babel-jest.

**Comment by seanf** [comment]
Patrick said:

> Sean asked me before about how to upgrade jest version. He wanted to upgrade jest only not everything. This looks like you upgraded other things in shrinkwrap.

I'm fine with upgrading other things (in `master`) as long as it works. I was just trying to minimise the breakage of things I wouldn't know how to fix.

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by huangp** [comment]
:lgtm: -(Work in progress) +(On QA) 

---

Reviewed 15 of 15 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/115#-:-KaZVWrmeDvS3FJGu-iQ:b2l0w6p)*

**Comment by spathare21** [comment]
@aeng buttons on all page and pop-ups on glossary, profile, language page are merged and disturb.

profile1

profile2

screenshot from 2017-01-16 10-11-40

screenshot from 2017-01-16 10-11-49

screenshot from 2017-01-16 10-12-03

screenshot from 2017-01-16 10-12-13

screenshot from 2017-01-16 10-12-22


screenshot from 2017-01-16 10-12-32

**Comment by spathare21** [comment]
verified all the pages and pop-up looks good

**Comment by aeng** [comment]
@seanf Can't put comment in yarnrc file. I put it in readme.md instead.

**Comment by aeng** [comment]
@spathare21 I've amended the last commit with only changes in readme.md file. No changes in code. So no further QA is needed.

**Pull request merged**
