### PR TITLE
fix: functional test

### PR DESCRIPTION
**Pull request by aeng**
JIRA issue URL: *paste URL here*

*[Add a short description of what is changed here.]*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/490)

### CODE REVIEW

**Comment by seanf** [comment]
@aeng I'm going to move your changes in b692f656f72e6d0b4bcd72c3e88807a2dc110bfc to the branch fix-java-warnings. https://github.com/zanata/zanata-platform/compare/fix-java-warnings?expand=1

**Comment by seanf** [comment]
@aeng also an archival copy of this branch before rebasing: https://github.com/zanata/zanata-platform/compare/fix-ft-old?expand=1

**Comment by huangp** [comment]
:lgtm: 

---

Reviewed 2 of 3 files at r1, 14 of 19 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/490#-:-KsN7_138j3kmQ2q4Hxf:bg7igkv)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 14 of 19 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/490#-:-KsNAyC_wIdd8QE6S3Tx:bnfp4nl)*

**Comment by djansen-redhat** [comment]
✅ Looks good to me. Thanks all for doing this.

**Comment by seanf** [comment]
I'm merging this to get the `master` build green, but see also https://zanata.atlassian.net/browse/ZNTA-2191 (probably the root cause) and https://zanata.atlassian.net/browse/ZNTA-2192 (more general solution for 429s on REST-heavy pages).

**Pull request merged**
