### PR TITLE
refactor(ZNTA-2514): react-bootstrap containers to antd

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2514

Refactor all frontend containers and the react-bootstrap components they use - exclude modals, alerts, notifications (complex components involving some coding beyond my ability)

* **The react-bootstrap components will be replaced with antd ones where they are used throughout `frontend/src/containers` -** - done ✔️ 
* TMMergeModal -  done ✔️ 
* Fix failing tests - done ✔️ 
* Audit frontend -  done ✔️ 

## Checklist

- JIRA link
- Check target branch
- Make sure all commit statuses are green or otherwise documented reasons to ignore
- QA needs to evaluate against the JIRA ticket
- Changed files and commits make sense for this PR

See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines) more for information.

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

### CODE REVIEW

**Comment by efloden** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx, line 6 at r7](https://reviewable.io/reviews/zanata/zanata-platform/807#-LD_6LEW5blqTjRSkQ6j:-LD_6LEX7LqS0LwYEE3K:biw1szn) ([raw file](https://github.com/zanata/zanata-platform/blob/a1ab000b83bdfd2d3963f74b2472b0819582fc68/server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx#L6)):*
> ```JSX
> import { Loader, Icon } from '../../components'
> import Button from 'antd/lib/button'
> import 'antd/lib/button/style/css'
> ```

Should we use the /css style entry for frontend as well?

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/807#-:-LD_98U37db_h1zK3-9O:bnfp4nl)*

**Comment by kathryngo** [comment]
@efloden can't see the harm in doing so. it should grab the less for frontend by doing this anyway right? I have had no problem with styling using this approach

**Comment by kathryngo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx, line 6 at r7](https://reviewable.io/reviews/zanata/zanata-platform/807#-LD_6LEW5blqTjRSkQ6j:-LDhyp1R4nAd3kmLKwAO:b83kq9p) ([raw file](https://github.com/zanata/zanata-platform/blob/a1ab000b83bdfd2d3963f74b2472b0819582fc68/server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx#L6)):*
<details><summary><i>Previously, efloden (Earl Floden) wrote…</i></summary><blockquote>

Should we use the /css style entry for frontend as well?
</blockquote></details>

Yes, I have been using that in frontend and changing the less imports to use the /css style entry

---


*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/807)*

**Comment by efloden** [comment]
Reviewed 8 of 8 files at r9.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/807)*

**Comment by djansen-redhat** [comment]
- [ ] Admin 'Review Criteria' page has an error:
>Select.js:560 Uncaught RangeError: Maximum call stack size exceeded
    at Select.js:560
    at Array.forEach (<anonymous>)
    at t.D.getOptionsInfoFromProps (Select.js:555)
    at t.D.componentWillReceiveProps (Select.js:287)
    at f.updateComponent (ReactCompositeComponent.js:614)
    at f.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at f._updateRenderedComponent (ReactCompositeComponent.js:754)
    at f._performComponentUpdate (ReactCompositeComponent.js:724)
    at f.updateComponent (ReactCompositeComponent.js:645)

**Comment by djansen-redhat** [comment]
- [ ] The entries become invisible when dragging them in TM Merge modal (minor)
screenshot from 2018-06-12 16-14-56

**Comment by kathryngo** [comment]
@efloden would you mind looking at the callstack error

**Comment by efloden** [comment]
Reviewed 1 of 1 files at r11, 6 of 6 files at r12.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/807)*

**Comment by djansen-redhat** [comment]
Looks good. Just waiting for Jenkins.

**Comment by efloden** [comment]
Reviewed 10 of 10 files at r13.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/807)*

**Comment by kathryngo** [comment]
@efloden once you are able to review the updated files and all functional tests pass this shoul be good to merge

**Comment by efloden** [comment]
Reviewed 4 of 4 files at r14.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/807)*

**Comment by kathryngo** [comment]
@djansen-redhat I will mark this as verified

**Comment by efloden** [comment]
Reviewed 3 of 3 files at r16.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/807)*

**Pull request merged**
