### PR TITLE
ZNTA-2212: improve css consistency in frontend

### PR DESCRIPTION
**Pull request by kathryngo**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2212

*Improvements*

* minor fixes to editor layout (sidebar border)
* removed zanata icon from minimised alpha editor header
* gwt fixes - button links, administration pages, other minor css fixes to frontend
* made popovers and tooltips consistent throughout reactJS pages in frontend
* minor fixes to glossary layout and TM Merge Modal (css)
* fix alignment of 'Clear selection' button on User Profile
* button heights now consistent, have box borders, minor css tweaks
* increased width of Languages page to 100% like other pages (excluding Explore)

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-platform/557)

### CODE REVIEW

**Comment by aeng** [comment]
For future PR, it would help with some screenshot attached. 
:lgtm:

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-platform/557#-:-Kvk01yKCLRPEBDhua91:bnf1l2m)*

**Comment by spathare21** [comment]
@kathryngo changed looks ok except below few ones I observed.

1. Cache statistics from the administrator.

screenshot from 2017-10-06 11-53-27

2. Language page on firefox (top two languages in the list don't have line breaks/border it shows cleary on chrome) . 

screenshot from 2017-10-06 12-11-52

3. Clear selection option not shown on user profile page.

**Comment by kathryngo** [comment]
@spathare21 
1. Due to limitations in the table design (it's absolutely horrible GWT stuff) I had to set a width on it for the horizontal scroll to work. Percentages and min,max-widths do not work.
2. Thanks for picking that up, shall fix it.
3. To see the Clear Selection option, select some buttons in the calendar matrix table.

**Comment by kathryngo** [comment]
@spathare21 I cannot replicate issue #2 in Firefox

See image
langrep

**Comment by spathare21** [comment]
@kathryngo I tried on a private window and still see this on Firefox (55.0.1 64 bit).

**Comment by kathryngo** [comment]
@spathare21 I will look at this Monday

**Comment by spathare21** [comment]
ok sure @kathryngo happy weekend : )

**Comment by kathryngo** [comment]
@spathare21 you too
maybe this is a fedora specific issue. I use macOS - shall check next week if it's OS specific

**Comment by kathryngo** [comment]
@spathare21 I still cannot replicate the issue with the language page. Will keep trying.

Also, you need to click one of the boxes in the calendar matrix to show the clear selection button. If you click the Sat button on the user profile example you provided then you should see it.

**Comment by kathryngo** [comment]
@spathare21 still cannot replicate that languages page issue. I think it may just be a weird Fedora bug, they do occasionally happen. I would say to just pass it through QA at this point once you are able to get the Clear Selection button to work. The languages page issue isn't related to functionality so I am happy to let this issue through.

**Comment by spathare21** [comment]
@kathryngo tested this PR on another machine and haven't seen that language page issue so marking as verified.

**Pull request merged**
